/* Frases filosóficas e sociológicas extras (ideias resumidas, sem citação literal) para completar 50 no e-book */
module.exports = [
 { autor:'Sócrates', ideia:'Reconhecer a própria ignorância é o ponto de partida do conhecimento: só quem questiona o que parece óbvio consegue construir saberes mais sólidos.', temas:'educação, desinformação, pensamento crítico' },
 { autor:'Friedrich Nietzsche', ideia:'Quando valores antes tidos como absolutos perdem força, surge o risco do niilismo, a perda de sentido, e a necessidade de uma sociedade criar valores que orientem a vida.', temas:'saúde mental, crise de valores, juventude' },
 { autor:'Nicolau Maquiavel', ideia:'A política deve ser analisada a partir de como o poder realmente funciona, e não apenas de como gostaríamos que funcionasse; por isso exige instituições fortes e vigilância dos cidadãos.', temas:'corrupção, política, cidadania' },
 { autor:'René Descartes', ideia:'A dúvida metódica propõe examinar com cuidado o que se recebe como verdade antes de aceitá-lo, atitude essencial diante do excesso de informações.', temas:'fake news, desinformação, ciência' },
 { autor:'John Stuart Mill', ideia:'A liberdade individual deve ser protegida até o ponto em que seu exercício causa dano a outras pessoas, o que equilibra direitos individuais e responsabilidade coletiva.', temas:'liberdade de expressão, discurso de ódio, direitos' },
 { autor:'Adam Smith', ideia:'A divisão do trabalho amplia a produtividade, mas, sem regras e proteção social, pode aprofundar desigualdades entre quem produz e quem se beneficia da riqueza.', temas:'trabalho, economia, desigualdade' },
 { autor:'Silvio Almeida', ideia:'O racismo é estrutural: está incorporado às instituições e às relações sociais, e por isso seu enfrentamento exige políticas públicas, e não apenas atitudes individuais.', temas:'racismo, desigualdade racial, políticas afirmativas' },
 { autor:'Djamila Ribeiro', ideia:'O "lugar de fala" lembra que a posição social influencia a experiência de cada pessoa, e que vozes historicamente silenciadas precisam ser ouvidas no debate público.', temas:'representatividade, racismo, machismo' },
 { autor:'Conceição Evaristo', ideia:'A "escrevivência" transforma a experiência de mulheres negras em escrita, dando visibilidade a histórias que foram apagadas da literatura e da sociedade.', temas:'invisibilidade, cultura, mulher negra' },
 { autor:'Florestan Fernandes', ideia:'O mito da democracia racial esconde as desigualdades que afetam a população negra e dificulta que o país reconheça e enfrente o racismo.', temas:'racismo, desigualdade, história do Brasil' },
 { autor:'Lélia Gonzalez', ideia:'A formação do Brasil não pode ser compreendida sem a contribuição de africanos e indígenas, cuja presença cultural foi muitas vezes marginalizada.', temas:'herança africana, identidade, cultura' },
 { autor:'Celso Furtado', ideia:'O subdesenvolvimento não é uma etapa natural, e sim resultado de processos históricos de dependência e de concentração de renda, que exigem planejamento para serem superados.', temas:'desigualdade regional, economia, desenvolvimento' },
 { autor:'Josué de Castro', ideia:'A fome é um fenômeno social, e não natural: decorre da desigualdade na distribuição de renda e de terras, e não da falta de alimentos.', temas:'insegurança alimentar, pobreza, desigualdade' },
 { autor:'Ulrich Beck', ideia:'Na "sociedade de risco", os perigos produzidos pelo próprio desenvolvimento, como os problemas ambientais e tecnológicos, atingem a todos e exigem responsabilidade coletiva.', temas:'meio ambiente, tecnologia, mudanças climáticas' },
 { autor:'Anthony Giddens', ideia:'A globalização intensifica a ligação entre locais distantes, de modo que decisões e eventos em um ponto do planeta afetam a vida de pessoas em outros.', temas:'globalização, economia, cultura' },
 { autor:'Manuel Castells', ideia:'Na "sociedade em rede", as informações circulam em tempo real e redefinem o trabalho, a política e as relações sociais, ampliando também as desigualdades de acesso.', temas:'internet, inclusão digital, tecnologia' },
 { autor:'Pierre Lévy', ideia:'A cibercultura cria uma inteligência coletiva, na qual o conhecimento é construído de forma compartilhada, o que exige educação para o uso crítico das tecnologias.', temas:'redes sociais, educação digital, conhecimento' },
 { autor:'Boaventura de Sousa Santos', ideia:'Existem saberes produzidos fora dos centros hegemônicos, como os saberes populares e tradicionais, que precisam ser reconhecidos para uma sociedade mais justa.', temas:'povos tradicionais, diversidade cultural, educação' },
 { autor:'Hannah Arendt', ideia:'A "banalidade do mal" mostra que atrocidades podem ser cometidas por pessoas comuns que deixam de pensar criticamente e apenas cumprem ordens.', temas:'violência, ética, autoritarismo' }
];
