/* =========================================================
   ARSENAL DE REDAÇÕES PARA O ENEM (conteúdo do produto)
   Lacunas entre colchetes, ex.: [TEMA], aparecem destacadas no app.
   ========================================================= */
window.ARSENAL = {

/* ---------- 1. MODELOS PRONTOS PARA INTRODUÇÃO ---------- */
introducao: [
  { titulo:'Alusão histórica', texto:'Durante [FATO HISTÓRICO], [O QUE ACONTECEU]. Embora o contexto seja outro, essa lógica ainda se manifesta no Brasil contemporâneo quando se observa [TEMA]. Nesse cenário, é fundamental analisar como [CAUSA 1] e [CAUSA 2] contribuem para a permanência desse problema.', dica:'Use uma alusão da aba "Alusões históricas". Funciona com quase todo tema social.' },
  { titulo:'Constituição Federal', texto:'A Constituição Federal de 1988, conhecida como "Constituição Cidadã", assegura a todos os brasileiros o direito à [DIREITO RELACIONADO AO TEMA]. Entretanto, na prática, essa garantia não se concretiza plenamente, como evidencia [TEMA]. Tal cenário decorre, sobretudo, de [CAUSA 1] e de [CAUSA 2].', dica:'O artigo 6º lista os direitos sociais: educação, saúde, alimentação, trabalho, moradia, transporte, lazer, segurança, previdência social, proteção à maternidade e à infância e assistência aos desamparados.' },
  { titulo:'Pensador ou filósofo', texto:'Segundo [PENSADOR], [IDEIA DO PENSADOR]. Sob essa ótica, é possível compreender [TEMA] no Brasil, problema que persiste em razão de [CAUSA 1] e de [CAUSA 2].', dica:'Escolha uma ideia na aba "Frases filosóficas" que converse diretamente com o tema.' },
  { titulo:'Declaração Universal dos Direitos Humanos', texto:'Em 1948, a Declaração Universal dos Direitos Humanos estabeleceu que todos os seres humanos nascem livres e iguais em dignidade e direitos. No entanto, essa premissa ainda está distante da realidade brasileira no que se refere a [TEMA], cenário agravado por [CAUSA 1] e por [CAUSA 2].', dica:'Ótimo para temas sobre minorias, violência, acesso a direitos e cidadania.' },
  { titulo:'Obra literária ou filme', texto:'Na obra "[TÍTULO]", de [AUTOR], [RESUMO DO QUE A OBRA MOSTRA]. Fora da ficção, essa realidade se aproxima do que ocorre no Brasil em relação a [TEMA], problema motivado por [CAUSA 1] e por [CAUSA 2].', dica:'Use só obras que você conhece de verdade. Repertório errado tira ponto na competência 2.' },
  { titulo:'Conceito sociológico', texto:'O sociólogo [AUTOR] desenvolveu o conceito de [CONCEITO], segundo o qual [EXPLICAÇÃO BREVE]. Essa reflexão ajuda a entender [TEMA] na sociedade brasileira, questão que se sustenta, principalmente, por [CAUSA 1] e por [CAUSA 2].', dica:'Bauman (modernidade líquida), Durkheim (anomia), Bourdieu (violência simbólica) e Han (sociedade do cansaço) se encaixam em muitos temas.' },
  { titulo:'Contraste com o ideal', texto:'Em uma sociedade que se pretende democrática, espera-se que [O QUE DEVERIA ACONTECER]. Contudo, no Brasil, [TEMA] revela um cenário oposto, marcado por [CAUSA 1] e por [CAUSA 2], o que exige atenção do poder público e da sociedade civil.', dica:'Boa opção quando você não lembra de nenhum repertório. Mas lembre: repertório legitimado vale mais na competência 2.' },
  { titulo:'Lei específica', texto:'A [NOME DA LEI], criada em [ANO], representa um avanço importante no combate a [PROBLEMA]. Apesar disso, [TEMA] ainda é uma realidade no país, o que demonstra que a existência da norma não basta diante de [CAUSA 1] e de [CAUSA 2].', dica:'Exemplos: Lei Maria da Penha (2006), Estatuto da Criança e do Adolescente (1990), Lei Brasileira de Inclusão (2015), LGPD (2018).' },
  { titulo:'Fato histórico mundial', texto:'A [EVENTO HISTÓRICO] transformou profundamente [ÁREA: o trabalho, a comunicação, a sociedade]. Séculos depois, os efeitos dessas mudanças ainda se refletem em [TEMA], desafio que se mantém no Brasil devido a [CAUSA 1] e a [CAUSA 2].', dica:'Revolução Industrial e Revolução Técnico-Científico-Informacional funcionam bem em temas de tecnologia e trabalho.' },
  { titulo:'Cenário atual', texto:'Nas últimas décadas, [MUDANÇA SOCIAL OU TECNOLÓGICA] alterou a forma como os brasileiros [AÇÃO RELACIONADA AO TEMA]. Nesse contexto, [TEMA] tornou-se um desafio relevante, sobretudo por causa de [CAUSA 1] e de [CAUSA 2].', dica:'Use quando o tema for muito atual (internet, dados, redes sociais, inteligência artificial).' }
],

/* ---------- 2. MODELOS PRONTOS PARA TESE ---------- */
tese: [
  'Nesse contexto, é evidente que [TEMA] decorre tanto de [CAUSA 1] quanto de [CAUSA 2].',
  'Diante disso, torna-se necessário discutir de que forma [CAUSA 1] e [CAUSA 2] contribuem para a manutenção de [TEMA].',
  'Tal problemática está relacionada, principalmente, a [CAUSA 1] e a [CAUSA 2], fatores que precisam ser enfrentados.',
  'Assim, cabe analisar como [CAUSA 1], aliada a [CAUSA 2], dificulta a superação de [TEMA] no país.',
  'Esse cenário é resultado, sobretudo, de [CAUSA 1] e de [CAUSA 2], aspectos que merecem atenção do Estado e da sociedade.',
  'Desse modo, percebe-se que [CAUSA 1] e [CAUSA 2] são os principais entraves para a resolução de [TEMA].',
  'Nessa perspectiva, entende-se que a persistência de [TEMA] tem raízes em [CAUSA 1] e se agrava com [CAUSA 2].',
  'Logo, é imprescindível compreender os impactos de [CAUSA 1] e de [CAUSA 2] para que [TEMA] seja combatido de forma eficaz.',
  'Com efeito, [TEMA] não é um problema isolado: ele se sustenta em [CAUSA 1] e é reforçado por [CAUSA 2].',
  'Por conseguinte, a superação de [TEMA] depende do enfrentamento de [CAUSA 1] e de [CAUSA 2].'
],

/* ---------- 3. TÓPICOS FRASAIS (início de cada parágrafo de desenvolvimento) ---------- */
topicos: [
  'Em primeiro lugar, é importante destacar que [CAUSA 1] contribui diretamente para [TEMA].',
  'De início, cabe ressaltar que [CAUSA 1] é um dos principais fatores que explicam [TEMA].',
  'Primordialmente, deve-se considerar que [CAUSA 1] está na raiz de [TEMA].',
  'Sob uma primeira análise, é notório que [CAUSA 1] agrava [TEMA].',
  'A princípio, convém analisar o papel de [CAUSA 1] na manutenção de [TEMA].',
  'Inicialmente, é válido pontuar que [CAUSA 1] intensifica [TEMA].',
  'Em uma primeira perspectiva, observa-se que [CAUSA 1] impede a superação de [TEMA].',
  'Antes de tudo, é preciso reconhecer que [CAUSA 1] alimenta [TEMA].',
  'Nesse sentido, um dos fatores que sustentam [TEMA] é [CAUSA 1].',
  'Convém ressaltar, de início, que a negligência em relação a [CAUSA 1] favorece [TEMA].',
  'Sob o viés histórico, nota-se que [CAUSA 1] tem origem em [ORIGEM] e ainda afeta [TEMA].',
  'Sob o viés social, percebe-se que [CAUSA 1] dificulta [TEMA].',
  'Sob o viés econômico, é evidente que [CAUSA 1] limita o enfrentamento de [TEMA].',
  'Sob o viés educacional, verifica-se que [CAUSA 1] perpetua [TEMA].',
  'Sob o viés cultural, observa-se que [CAUSA 1] naturaliza [TEMA].',
  'Sob o viés político, constata-se que [CAUSA 1] enfraquece as políticas sobre [TEMA].',
  'No âmbito familiar, é perceptível que [CAUSA 1] reforça [TEMA].',
  'No âmbito escolar, nota-se que [CAUSA 1] impede a discussão adequada de [TEMA].',
  'No campo da saúde pública, [CAUSA 1] amplia os efeitos de [TEMA].',
  'No ambiente digital, [CAUSA 1] potencializa [TEMA].',
  'Um dos aspectos centrais dessa questão é [CAUSA 1], que [CONSEQUÊNCIA].',
  'É fundamental compreender que [CAUSA 1] não ocorre por acaso, mas resulta de [ORIGEM].',
  'Não se pode ignorar que [CAUSA 1] tem impacto direto sobre [GRUPO AFETADO].',
  'Cabe destacar, nesse contexto, a omissão do Estado em relação a [CAUSA 1].',
  'Em uma análise inicial, a falta de [ALGO QUE FALTA] revela-se determinante para [TEMA].',
  'Além disso, outro fator relevante para a persistência de [TEMA] é [CAUSA 2].',
  'Ademais, é necessário considerar o papel de [CAUSA 2] nesse cenário.',
  'Somado a isso, [CAUSA 2] também contribui para o agravamento de [TEMA].',
  'Paralelamente, verifica-se que [CAUSA 2] reforça os efeitos de [TEMA].',
  'Por outro lado, não se pode desconsiderar a influência de [CAUSA 2].',
  'Outrossim, [CAUSA 2] colabora para a manutenção de [TEMA].',
  'Em segundo plano, mas igualmente relevante, destaca-se [CAUSA 2].',
  'Também merece atenção o fato de que [CAUSA 2] dificulta a mudança desse quadro.',
  'Ainda nesse sentido, [CAUSA 2] amplia as consequências de [TEMA].',
  'Além do fator já mencionado, [CAUSA 2] agrava a situação.',
  'Em uma segunda análise, percebe-se que [CAUSA 2] também sustenta [TEMA].',
  'Concomitantemente, [CAUSA 2] intensifica a gravidade do problema.',
  'Não menos importante, [CAUSA 2] revela outra face de [TEMA].',
  'Soma-se a esse panorama a questão de [CAUSA 2].',
  'Ademais, convém mencionar que [CAUSA 2] afeta especialmente [GRUPO AFETADO].',
  'Por fim, deve-se ponderar que [CAUSA 2] perpetua [TEMA] ao longo das gerações.',
  'Além disso, a ausência de [ALGO QUE FALTA] reforça o problema.',
  'Sob outra ótica, [CAUSA 2] evidencia a fragilidade das políticas públicas sobre [TEMA].',
  'De forma complementar, [CAUSA 2] mostra que o problema também é cultural.',
  'Vale lembrar, ainda, que [CAUSA 2] contribui para a invisibilidade de [TEMA].',
  'Em consonância com o que foi exposto, [CAUSA 2] aprofunda [TEMA].',
  'Nesse mesmo raciocínio, [CAUSA 2] impede avanços concretos.',
  'Igualmente, a influência de [CAUSA 2] não pode ser ignorada.',
  'Por conseguinte, [CAUSA 2] gera [CONSEQUÊNCIA], o que agrava [TEMA].',
  'Ainda que existam iniciativas de combate, [CAUSA 2] continua sendo um obstáculo.'
],

/* ---------- 4. ALUSÕES HISTÓRICAS ---------- */
alusoes: [
  { fato:'Revolta da Vacina (1904)', texto:'No Rio de Janeiro, a população se revoltou contra a vacinação obrigatória contra a varíola, em um contexto de desinformação e de ações autoritárias do governo.', temas:'saúde pública, vacinação, desinformação, comunicação do Estado' },
  { fato:'Lei Áurea (1888)', texto:'A abolição da escravidão não veio acompanhada de políticas de inclusão para a população negra liberta, que foi deixada à margem da sociedade.', temas:'racismo, desigualdade social, moradia, educação' },
  { fato:'Lei de Terras (1850)', texto:'A lei passou a exigir a compra para o acesso à terra, o que dificultou que ex-escravizados e pobres se tornassem proprietários e favoreceu a concentração fundiária.', temas:'moradia, reforma agrária, desigualdade' },
  { fato:'Constituição Federal (1988)', texto:'A Carta, chamada de "Constituição Cidadã", garantiu direitos sociais como educação, saúde, moradia e lazer, além de criar as bases do SUS.', temas:'cidadania, direitos sociais, praticamente qualquer tema' },
  { fato:'Declaração Universal dos Direitos Humanos (1948)', texto:'O documento, criado após a Segunda Guerra Mundial, afirma que todos nascem livres e iguais em dignidade e direitos.', temas:'dignidade, minorias, violência, refugiados' },
  { fato:'Revolução Industrial (século XVIII)', texto:'A mecanização da produção transformou o trabalho, acelerou a urbanização e intensificou a exploração da natureza.', temas:'trabalho, meio ambiente, urbanização, tecnologia' },
  { fato:'Revolução Francesa (1789)', texto:'O movimento difundiu os ideais de liberdade, igualdade e fraternidade, que inspiraram as democracias modernas.', temas:'democracia, igualdade, participação política' },
  { fato:'Iluminismo (século XVIII)', texto:'O movimento valorizou a razão, a ciência e a educação como caminhos para libertar o ser humano da ignorância.', temas:'educação, ciência, desinformação' },
  { fato:'Semana de Arte Moderna (1922)', texto:'Artistas como Mário de Andrade e Tarsila do Amaral defenderam uma arte com identidade brasileira, rompendo com modelos europeus.', temas:'cultura, identidade nacional, valorização da arte' },
  { fato:'Consolidação das Leis do Trabalho, a CLT (1943)', texto:'Criada durante o governo Vargas, a CLT reuniu direitos trabalhistas como jornada regulamentada e férias.', temas:'trabalho, direitos trabalhistas, informalidade' },
  { fato:'AI-5 (1968)', texto:'O Ato Institucional nº 5, durante a ditadura militar, ampliou a censura e suspendeu garantias individuais.', temas:'liberdade de expressão, democracia, imprensa' },
  { fato:'Diretas Já (1983 e 1984)', texto:'O movimento reuniu multidões para pedir eleições diretas para presidente no fim da ditadura.', temas:'participação política, cidadania, juventude' },
  { fato:'Estatuto da Criança e do Adolescente (1990)', texto:'O ECA reconheceu crianças e adolescentes como sujeitos de direitos, com proteção integral.', temas:'infância, trabalho infantil, educação, violência' },
  { fato:'Lei Maria da Penha (2006)', texto:'A lei criou mecanismos para coibir a violência doméstica e familiar contra a mulher.', temas:'violência contra a mulher, desigualdade de gênero' },
  { fato:'Lei do Feminicídio (2015)', texto:'A lei incluiu o feminicídio, o assassinato de mulheres por razões da condição de sexo feminino, no rol de crimes hediondos.', temas:'violência contra a mulher' },
  { fato:'Estatuto da Pessoa Idosa (2003)', texto:'O estatuto, antes chamado de Estatuto do Idoso, garante direitos e proteção às pessoas com 60 anos ou mais.', temas:'envelhecimento, abandono, saúde' },
  { fato:'Lei Brasileira de Inclusão (2015)', texto:'A lei, também chamada de Estatuto da Pessoa com Deficiência, assegura acessibilidade e combate à discriminação.', temas:'inclusão, acessibilidade, deficiência, surdos' },
  { fato:'Voto feminino no Brasil (1932)', texto:'O Código Eleitoral de 1932 garantiu às mulheres o direito ao voto, conquista resultante de anos de luta.', temas:'participação feminina, igualdade de gênero' },
  { fato:'Rosa Parks (1955)', texto:'Nos Estados Unidos, ela se recusou a ceder o lugar no ônibus a um homem branco, ato que impulsionou o movimento pelos direitos civis.', temas:'racismo, resistência, direitos civis' },
  { fato:'Apartheid (1948 a 1994)', texto:'O regime de segregação racial da África do Sul foi combatido por Nelson Mandela, que se tornou presidente do país em 1994.', temas:'racismo, segregação, reconciliação' },
  { fato:'Holocausto (Segunda Guerra Mundial)', texto:'O genocídio de milhões de judeus e de outros grupos pelo regime nazista mostra até onde a intolerância pode chegar.', temas:'intolerância, discurso de ódio, minorias' },
  { fato:'Revolução Técnico-Científico-Informacional (a partir de 1970)', texto:'A integração entre ciência, tecnologia e informação transformou a comunicação, o trabalho e a economia.', temas:'tecnologia, redes sociais, trabalho, educação a distância' },
  { fato:'ARPANET (1969)', texto:'A rede, criada pelo Departamento de Defesa dos Estados Unidos para conectar centros de pesquisa, deu origem à internet.', temas:'internet, tecnologia, comunicação' },
  { fato:'Rio-92 (1992)', texto:'A conferência da ONU sobre meio ambiente e desenvolvimento, realizada no Rio de Janeiro, difundiu a ideia de desenvolvimento sustentável.', temas:'meio ambiente, sustentabilidade' },
  { fato:'Protocolo de Kyoto (1997)', texto:'O acordo internacional estabeleceu metas de redução de gases do efeito estufa para países desenvolvidos.', temas:'mudanças climáticas, poluição' },
  { fato:'Acordo de Paris (2015)', texto:'O compromisso global busca limitar o aquecimento do planeta, com metas definidas por cada país.', temas:'clima, meio ambiente, energia' },
  { fato:'Rompimento da barragem de Fundão, em Mariana (2015)', texto:'O desastre despejou rejeitos de mineração no Rio Doce, com graves danos ambientais e sociais.', temas:'meio ambiente, responsabilidade de empresas, fiscalização' },
  { fato:'Rompimento da barragem de Brumadinho (2019)', texto:'A tragédia causou centenas de mortes e reacendeu o debate sobre a fiscalização da mineração.', temas:'meio ambiente, fiscalização, vida humana' },
  { fato:'Pandemia de covid-19 (a partir de 2020)', texto:'A pandemia expôs desigualdades no acesso à saúde, à internet e à educação, além dos efeitos da desinformação.', temas:'saúde, educação, desigualdade digital, desinformação' },
  { fato:'Criação do SUS (1988 e 1990)', texto:'O sistema, previsto na Constituição e regulamentado pela Lei 8.080 de 1990, garante saúde pública, gratuita e universal.', temas:'saúde pública, acesso a direitos' },
  { fato:'Gripe Espanhola (1918)', texto:'A pandemia matou milhões de pessoas no mundo e mostrou a importância de medidas de saúde pública.', temas:'saúde, pandemias, ciência' },
  { fato:'Peste Negra (século XIV)', texto:'A epidemia devastou a Europa medieval e mostrou como a falta de conhecimento científico agrava crises sanitárias.', temas:'saúde, ciência, desinformação' },
  { fato:'Reforma psiquiátrica, Lei 10.216 (2001)', texto:'A lei redirecionou o modelo de atenção em saúde mental, priorizando o tratamento em liberdade e em serviços comunitários.', temas:'saúde mental, estigma, inclusão' },
  { fato:'Hospital Colônia de Barbacena (século XX)', texto:'Retratado no livro "Holocausto Brasileiro", de Daniela Arbex, o hospício foi palco da morte de milhares de internos em condições desumanas.', temas:'saúde mental, estigma, direitos humanos' },
  { fato:'Lei de Cotas (2012)', texto:'A Lei 12.711 reservou vagas em instituições federais para estudantes de escolas públicas, de baixa renda, pretos, pardos e indígenas.', temas:'educação, racismo, desigualdade' },
  { fato:'Experiência de Angicos (1963)', texto:'Paulo Freire alfabetizou cerca de 300 trabalhadores em Angicos, no Rio Grande do Norte, partindo da realidade dos próprios alunos.', temas:'educação, analfabetismo, cidadania' },
  { fato:'Prensa de Gutenberg (século XV)', texto:'A invenção da prensa de tipos móveis ampliou o acesso aos livros e transformou a circulação do conhecimento.', temas:'leitura, informação, educação' },
  { fato:'Estado laico (1891)', texto:'A primeira Constituição republicana separou o Estado da Igreja no Brasil, base para a liberdade religiosa.', temas:'intolerância religiosa, liberdade de crença' },
  { fato:'Guerra de Canudos (1896 e 1897)', texto:'O massacre do arraial liderado por Antônio Conselheiro, narrado em "Os Sertões", de Euclides da Cunha, revela o abandono do sertão pelo Estado.', temas:'desigualdade regional, pobreza, violência do Estado' },
  { fato:'Revolta da Chibata (1910)', texto:'Marinheiros, em sua maioria negros, liderados por João Cândido, se rebelaram contra os castigos físicos na Marinha.', temas:'racismo, violência, direitos' },
  { fato:'Inauguração de Brasília (1960)', texto:'A construção da capital atraiu milhares de trabalhadores, os candangos, muitos dos quais ficaram sem moradia digna no plano urbano.', temas:'urbanização, moradia, desigualdade' },
  { fato:'Êxodo rural no Brasil (século XX)', texto:'A migração em massa do campo para as cidades, sem planejamento, contribuiu para o crescimento de favelas e periferias.', temas:'moradia, urbanização, mobilidade urbana' },
  { fato:'Crise de 1929', texto:'A quebra da Bolsa de Nova York gerou desemprego em massa e mostrou os riscos de uma economia sem regulação.', temas:'economia, desemprego, consumo' },
  { fato:'Revolução Verde (décadas de 1960 e 1970)', texto:'O uso intensivo de máquinas, sementes modificadas e agrotóxicos aumentou a produção, mas não acabou com a fome e trouxe impactos ambientais.', temas:'fome, agrotóxicos, meio ambiente' },
  { fato:'Mapa da Fome da ONU (2014)', texto:'O Brasil saiu do Mapa da Fome em 2014 e voltou a figurar nele anos depois, o que mostra que a segurança alimentar depende de políticas contínuas.', temas:'fome, insegurança alimentar, políticas públicas' },
  { fato:'Primavera Árabe (2010 e 2011)', texto:'Protestos em países do norte da África e do Oriente Médio foram organizados em grande parte pelas redes sociais.', temas:'redes sociais, democracia, mobilização' },
  { fato:'Caso Cambridge Analytica (2018)', texto:'A empresa usou dados de milhões de usuários do Facebook, sem o devido consentimento, para direcionar propaganda política.', temas:'dados pessoais, manipulação, internet, democracia' },
  { fato:'Lei Geral de Proteção de Dados, a LGPD (2018)', texto:'A lei regula o tratamento de dados pessoais no Brasil e garante ao cidadão o direito de saber como suas informações são usadas.', temas:'privacidade, dados, internet' },
  { fato:'Marco Civil da Internet (2014)', texto:'A lei estabeleceu princípios, direitos e deveres para o uso da internet no Brasil, como a neutralidade da rede.', temas:'internet, liberdade de expressão, privacidade' },
  { fato:'Lei Caó, Lei 7.716 (1989)', texto:'A lei definiu os crimes resultantes de preconceito de raça ou de cor, tornando o racismo crime no Brasil.', temas:'racismo, discriminação' },
  { fato:'Quilombo dos Palmares (século XVII)', texto:'O maior quilombo do período colonial, símbolo da resistência negra, teve Zumbi como uma de suas lideranças. O 20 de novembro, Dia da Consciência Negra, homenageia Zumbi.', temas:'herança africana, racismo, resistência' },
  { fato:'Criminalização da LGBTfobia pelo STF (2019)', texto:'O Supremo Tribunal Federal decidiu enquadrar a homofobia e a transfobia na Lei do Racismo até que o Congresso aprove lei específica.', temas:'LGBTfobia, discriminação, direitos' },
  { fato:'Acidente de Chernobyl (1986)', texto:'A explosão de um reator nuclear na antiga União Soviética mostrou os riscos de tecnologias sem fiscalização e transparência.', temas:'meio ambiente, energia, ciência' }
],

/* ---------- 5. FRASES CORINGAS ---------- */
coringas: [
  'Diante dos desafios contemporâneos, é fundamental repensar práticas e buscar soluções efetivas.',
  'É fundamental que a sociedade esteja consciente de seu papel na construção de um futuro mais justo.',
  'Fica evidente a necessidade de uma reflexão profunda sobre essa questão.',
  'Esse cenário revela uma contradição entre o que a lei garante e o que a realidade oferece.',
  'Trata-se de um problema estrutural, que não pode ser resolvido com medidas pontuais.',
  'A omissão do poder público contribui para a perpetuação desse quadro.',
  'Não se trata de um problema individual, mas de uma questão coletiva.',
  'Os efeitos desse problema atingem, sobretudo, as parcelas mais vulneráveis da população.',
  'A falta de informação de qualidade agrava ainda mais esse cenário.',
  'É preciso romper com a naturalização desse problema no cotidiano brasileiro.',
  'Sem a participação ativa da sociedade civil, qualquer mudança tende a ser limitada.',
  'Esse quadro evidencia a urgência de ações integradas entre Estado, escola e família.',
  'A educação, nesse sentido, é a principal ferramenta de transformação social.',
  'Ignorar esse problema significa compactuar com sua permanência.',
  'Essa realidade exige mudanças tanto no âmbito institucional quanto no cultural.',
  'A ausência de políticas públicas eficazes torna o problema ainda mais grave.',
  'É inegável que esse desafio compromete o pleno exercício da cidadania.',
  'O debate sobre essa questão precisa ultrapassar os muros das escolas e alcançar toda a sociedade.',
  'Tal situação reflete heranças históricas que ainda não foram superadas.',
  'Nesse sentido, a mudança de mentalidade é tão importante quanto a criação de leis.',
  'O problema persiste porque suas causas não são enfrentadas na raiz.',
  'Dessa forma, cria-se um ciclo vicioso difícil de ser rompido.',
  'A mídia, por seu alcance, tem papel decisivo na conscientização da população.',
  'Essa conjuntura impede que o Brasil avance rumo a uma sociedade mais igualitária.',
  'É imprescindível garantir que os direitos previstos em lei saiam do papel.',
  'A desigualdade social potencializa os efeitos negativos desse fenômeno.',
  'Esse problema tem consequências que se estendem por gerações.',
  'A negligência histórica em relação a essa questão explica parte de sua gravidade atual.',
  'Somente com esforço conjunto será possível modificar essa realidade.',
  'É dever do Estado assegurar condições dignas para todos os cidadãos.',
  'A escola, como espaço de formação cidadã, deve abordar essa temática de forma crítica.',
  'Esse cenário demonstra que o progresso tecnológico nem sempre acompanha o progresso social.',
  'Cabe à sociedade cobrar dos governantes medidas concretas e contínuas.',
  'O desafio, portanto, é transformar a indignação em ação.',
  'Essa questão revela o abismo entre os diferentes grupos sociais do país.',
  'Os dados sobre o tema mostram que o problema está longe de ser resolvido.',
  'Esse fenômeno compromete não apenas o presente, mas também o futuro do país.',
  'É urgente que essa pauta ganhe prioridade na agenda pública.',
  'Desconsiderar essa questão é negar a dignidade de milhares de brasileiros.',
  'A informação, quando bem utilizada, é capaz de quebrar preconceitos.',
  'O combate a esse problema exige continuidade, e não apenas ações isoladas.',
  'Essa realidade evidencia a necessidade de fiscalização mais rigorosa.',
  'A construção de uma sociedade democrática passa, necessariamente, pela solução desse problema.',
  'É nesse contexto que se torna indispensável a atuação de diferentes setores da sociedade.',
  'O silêncio diante desse problema contribui para sua perpetuação.',
  'Esse quadro reforça a importância de valorizar o conhecimento científico.',
  'A superação desse desafio depende de vontade política e de engajamento social.',
  'A empatia e o respeito às diferenças são essenciais para a convivência coletiva.',
  'Somente assim será possível garantir que o direito de poucos se torne o direito de todos.',
  'Dessa maneira, o país poderá avançar rumo a uma sociedade verdadeiramente justa e inclusiva.'
],

/* ---------- 6. FRASES FILOSÓFICAS E REPERTÓRIO DE PENSADORES ---------- */
filosofos: [
  { autor:'Zygmunt Bauman', ideia:'Vivemos uma "modernidade líquida", em que as relações, os valores e os vínculos se tornaram frágeis e passageiros.', temas:'relações sociais, consumo, redes sociais, solidão' },
  { autor:'Aristóteles', ideia:'O ser humano é um "animal político": vive em sociedade, e a política deve buscar o bem comum.', temas:'cidadania, participação política, coletividade' },
  { autor:'Immanuel Kant', ideia:'O ser humano deve ser tratado sempre como um fim em si mesmo, e nunca apenas como um meio.', temas:'dignidade, exploração, direitos humanos' },
  { autor:'Immanuel Kant', ideia:'O Esclarecimento é a saída do ser humano da "menoridade", isto é, da incapacidade de pensar por conta própria.', temas:'educação, desinformação, pensamento crítico' },
  { autor:'Hannah Arendt', ideia:'Com o conceito de "banalidade do mal", mostrou que pessoas comuns podem praticar o mal quando deixam de refletir sobre os próprios atos.', temas:'violência, intolerância, omissão' },
  { autor:'Michel Foucault', ideia:'Em "Vigiar e Punir", analisou como a sociedade disciplinar controla os indivíduos por meio da vigilância.', temas:'vigilância, dados, controle, sistema prisional' },
  { autor:'Émile Durkheim', ideia:'O conceito de "anomia" descreve o enfraquecimento das normas sociais, que gera desorientação e conflitos.', temas:'violência, crise de valores, instituições' },
  { autor:'Émile Durkheim', ideia:'Os "fatos sociais" são maneiras de agir e pensar que exercem força sobre o indivíduo e são exteriores a ele.', temas:'comportamento coletivo, preconceito, cultura' },
  { autor:'Max Weber', ideia:'O Estado é a instituição que detém o monopólio do uso legítimo da força em um território.', temas:'segurança pública, violência, papel do Estado' },
  { autor:'Karl Marx', ideia:'O trabalhador alienado não se reconhece no produto do próprio trabalho.', temas:'trabalho, exploração, desigualdade' },
  { autor:'Jean-Paul Sartre', ideia:'"O homem está condenado a ser livre": somos responsáveis por nossas escolhas.', temas:'responsabilidade individual, juventude, escolhas' },
  { autor:'Simone de Beauvoir', ideia:'"Ninguém nasce mulher: torna-se mulher." Os papéis de gênero são construções sociais.', temas:'igualdade de gênero, machismo, trabalho de cuidado' },
  { autor:'Paulo Freire', ideia:'Criticou a "educação bancária", em que o aluno apenas recebe conteúdo, e defendeu uma educação crítica e libertadora.', temas:'educação, cidadania, desigualdade' },
  { autor:'Pierre Bourdieu', ideia:'A "violência simbólica" é uma forma de dominação invisível, que faz o dominado aceitar como natural a própria desigualdade.', temas:'preconceito, desigualdade, padrões de beleza, educação' },
  { autor:'Byung-Chul Han', ideia:'Em "Sociedade do Cansaço", afirma que a cobrança por desempenho leva ao esgotamento e a doenças como a depressão e o burnout.', temas:'saúde mental, trabalho, produtividade' },
  { autor:'Guy Debord', ideia:'Na "sociedade do espetáculo", as relações entre as pessoas passam a ser mediadas por imagens.', temas:'redes sociais, mídia, consumo, aparência' },
  { autor:'Adorno e Horkheimer', ideia:'A "indústria cultural" transforma a cultura em mercadoria e padroniza o gosto do público.', temas:'cultura, mídia, consumo, cinema' },
  { autor:'Jürgen Habermas', ideia:'A democracia depende de uma "esfera pública" em que os cidadãos debatem de forma livre e racional.', temas:'democracia, debate público, redes sociais' },
  { autor:'Thomas Hobbes', ideia:'Sem um poder comum que garanta a ordem, a vida humana seria uma "guerra de todos contra todos".', temas:'violência, segurança, papel do Estado' },
  { autor:'John Locke', ideia:'Todo ser humano tem direitos naturais à vida, à liberdade e à propriedade, que o governo deve proteger.', temas:'direitos, papel do Estado, liberdade' },
  { autor:'Jean-Jacques Rousseau', ideia:'O "contrato social" deve expressar a vontade geral e garantir a liberdade e a igualdade entre os cidadãos.', temas:'democracia, igualdade, cidadania' },
  { autor:'Montesquieu', ideia:'Defendeu a separação entre os poderes Executivo, Legislativo e Judiciário para evitar abusos.', temas:'democracia, corrupção, instituições' },
  { autor:'Platão', ideia:'No "Mito da Caverna", as pessoas acorrentadas tomam sombras por realidade, metáfora da ignorância e da manipulação.', temas:'desinformação, fake news, educação' },
  { autor:'Hans Jonas', ideia:'O "princípio responsabilidade" afirma que devemos agir pensando nas gerações futuras.', temas:'meio ambiente, tecnologia, sustentabilidade' },
  { autor:'Milton Santos', ideia:'Em "Por uma outra globalização", criticou a globalização "perversa", que aprofunda desigualdades.', temas:'globalização, desigualdade, tecnologia' },
  { autor:'Sérgio Buarque de Holanda', ideia:'Em "Raízes do Brasil", descreveu o "homem cordial", que mistura o público e o privado nas relações.', temas:'corrupção, política, cultura brasileira' },
  { autor:'Norberto Bobbio', ideia:'Em "A Era dos Direitos", afirma que o grande problema dos direitos humanos hoje não é justificá-los, mas protegê-los.', temas:'direitos humanos, efetivação de leis' },
  { autor:'Amartya Sen', ideia:'Em "Desenvolvimento como Liberdade", defende que o desenvolvimento deve ampliar as liberdades reais das pessoas.', temas:'desigualdade, pobreza, educação, saúde' },
  { autor:'Ailton Krenak', ideia:'Em "Ideias para adiar o fim do mundo", critica a ideia de que a humanidade estaria separada da natureza.', temas:'meio ambiente, povos indígenas, comunidades tradicionais' },
  { autor:'Angela Davis', ideia:'Frase atribuída: "Numa sociedade racista, não basta não ser racista. É necessário ser antirracista."', temas:'racismo, herança africana, discriminação' },
  { autor:'Darcy Ribeiro', ideia:'Frase atribuída: "A crise da educação no Brasil não é uma crise; é um projeto."', temas:'educação, desigualdade, políticas públicas' }
],

/* ---------- 7. PROPOSTA DE INTERVENÇÃO ---------- */
proposta: {
  elementos: [
    { nome:'Agente', pergunta:'Quem vai fazer?', exemplos:'Ministério da Educação, Ministério da Saúde, Congresso Nacional, escolas, mídia, ONGs, famílias, empresas' },
    { nome:'Ação', pergunta:'O que vai ser feito?', exemplos:'criar campanhas, ampliar programas, fiscalizar, incluir no currículo, investir em' },
    { nome:'Meio ou modo', pergunta:'Como vai ser feito?', exemplos:'por meio de, mediante, através de parcerias com, com o uso de' },
    { nome:'Finalidade', pergunta:'Para quê?', exemplos:'a fim de, com o objetivo de, para que, com o intuito de' },
    { nome:'Detalhamento', pergunta:'Um detalhe a mais sobre qualquer elemento', exemplos:'explicar o agente ("órgão responsável por..."), o meio ou a finalidade' }
  ],
  frases: [
    'Portanto, cabe ao [AGENTE] [AÇÃO], por meio de [MEIO], a fim de [FINALIDADE].',
    'Diante do exposto, é imprescindível que o [AGENTE], órgão responsável por [DETALHAMENTO], [AÇÃO], mediante [MEIO], com o objetivo de [FINALIDADE].',
    'Dessa forma, o Ministério da Educação deve incluir o debate sobre [TEMA] na grade curricular, por meio de palestras e projetos interdisciplinares, a fim de formar cidadãos mais conscientes.',
    'Assim, compete à mídia, por seu grande alcance, promover campanhas de conscientização sobre [TEMA], por meio de propagandas em horário nobre e nas redes sociais, para que a população compreenda a gravidade do problema.',
    'Logo, o Estado deve ampliar os investimentos em [ÁREA], mediante a destinação de verbas específicas no orçamento, com o intuito de garantir [DIREITO] a toda a população.',
    'Em suma, as escolas, em parceria com as famílias, devem promover rodas de conversa sobre [TEMA], a fim de combater o preconceito desde a infância.',
    'Por conseguinte, o Congresso Nacional deve criar leis mais rígidas sobre [TEMA], por meio de projetos debatidos com especialistas e com a sociedade civil, para que haja punição efetiva aos infratores.',
    'Cabe, ainda, às organizações não governamentais atuar junto às comunidades mais afetadas, por meio de oficinas e de acolhimento, com o objetivo de reduzir os impactos de [TEMA].',
    'Diante disso, o Ministério da Saúde deve ampliar o atendimento relacionado a [TEMA] nas unidades básicas, mediante a contratação de profissionais especializados, a fim de garantir atendimento digno.',
    'Além disso, as empresas de tecnologia devem aprimorar seus mecanismos de controle, por meio de algoritmos de verificação e de canais de denúncia, para reduzir a circulação de conteúdos nocivos.',
    'Com isso, será possível [RESULTADO ESPERADO] e construir uma sociedade mais justa.',
    'Somente assim o Brasil poderá superar [TEMA] e garantir que os direitos previstos na Constituição sejam efetivamente cumpridos.',
    'Dessa maneira, a realidade descrita por [REPERTÓRIO DA INTRODUÇÃO] deixará de fazer parte do cotidiano brasileiro.',
    'Assim, [TEMA] deixará de ser um problema invisível e passará a ser tratado com a seriedade que merece.',
    'Desse modo, será possível construir um futuro em que [SITUAÇÃO IDEAL] seja uma realidade para todos.'
  ]
},

/* ---------- 8. CONECTIVOS (com exemplos de uso) ---------- */
conectivos: [
  { funcao:'Adição', lista:['além disso','ademais','outrossim','somado a isso','não só... mas também','bem como','igualmente'], exemplo:'A falta de investimento prejudica o ensino. Além disso, a evasão escolar agrava o problema.' },
  { funcao:'Oposição', lista:['entretanto','contudo','no entanto','todavia','porém','embora','apesar de','não obstante'], exemplo:'A Constituição garante o direito à moradia. Entretanto, milhões de brasileiros vivem em condições precárias.' },
  { funcao:'Causa', lista:['porque','visto que','uma vez que','já que','em razão de','devido a','haja vista'], exemplo:'O problema persiste, uma vez que as políticas públicas são insuficientes.' },
  { funcao:'Consequência', lista:['consequentemente','por conseguinte','de modo que','de forma que','tanto que','em decorrência disso'], exemplo:'Os jovens não têm acesso à informação. Consequentemente, tornam-se mais vulneráveis.' },
  { funcao:'Conclusão', lista:['portanto','logo','assim','dessa forma','desse modo','em suma','diante do exposto'], exemplo:'Portanto, cabe ao Estado ampliar os programas de inclusão.' },
  { funcao:'Exemplificação', lista:['por exemplo','como','a exemplo de','tal como','isto é','ou seja'], exemplo:'Há leis importantes sobre o tema, a exemplo da Lei Maria da Penha.' },
  { funcao:'Explicação', lista:['isto é','ou seja','em outras palavras','quer dizer','vale dizer'], exemplo:'A desigualdade é estrutural, ou seja, está presente nas bases da sociedade.' },
  { funcao:'Comparação', lista:['assim como','da mesma forma que','tal qual','de modo semelhante','analogamente'], exemplo:'Assim como no século XIX, ainda hoje a população negra enfrenta barreiras de acesso.' },
  { funcao:'Tempo', lista:['atualmente','hodiernamente','na contemporaneidade','outrora','desde então','à medida que'], exemplo:'Na contemporaneidade, as redes sociais influenciam o comportamento dos jovens.' },
  { funcao:'Condição', lista:['caso','se','desde que','contanto que','a menos que'], exemplo:'Caso nada seja feito, o problema tende a se agravar.' },
  { funcao:'Finalidade', lista:['a fim de','para que','com o intuito de','com o objetivo de','de modo a'], exemplo:'O governo deve investir em campanhas, a fim de conscientizar a população.' },
  { funcao:'Retomada e ênfase', lista:['nesse sentido','nesse contexto','sob essa ótica','diante disso','com efeito','de fato'], exemplo:'Nesse contexto, é fundamental compreender o papel da escola.' },
  { funcao:'Início de desenvolvimento', lista:['em primeiro lugar','primordialmente','inicialmente','a princípio','de início'], exemplo:'Em primeiro lugar, é preciso analisar a omissão estatal.' },
  { funcao:'Segundo desenvolvimento', lista:['em segundo lugar','paralelamente','concomitantemente','por outro lado','ademais'], exemplo:'Paralelamente, a falta de informação contribui para o preconceito.' }
],

/* ---------- 9. BÔNUS ---------- */
bonus: {
  estrutura: [
    { p:'1º parágrafo: Introdução (5 a 7 linhas)', itens:['Repertório que contextualiza o tema','Apresentação do problema','Tese com as duas causas que você vai desenvolver'] },
    { p:'2º parágrafo: Desenvolvimento 1 (7 a 9 linhas)', itens:['Tópico frasal com a causa 1','Explicação da causa','Repertório ou exemplo que prove o argumento','Fechamento ligando à tese'] },
    { p:'3º parágrafo: Desenvolvimento 2 (7 a 9 linhas)', itens:['Conectivo de retomada e tópico frasal com a causa 2','Explicação','Repertório ou exemplo','Fechamento'] },
    { p:'4º parágrafo: Conclusão (5 a 7 linhas)', itens:['Conectivo de conclusão','Proposta de intervenção com agente, ação, meio, finalidade e detalhamento','Frase final que retoma o repertório da introdução'] }
  ],
  competencias: [
    { c:'Competência 1', t:'Domínio da escrita formal da língua portuguesa', dicas:['Revise acentuação, concordância e crase','Evite gírias, abreviações e marcas de oralidade','Frases muito longas aumentam a chance de erro: prefira períodos médios'] },
    { c:'Competência 2', t:'Compreender a proposta e aplicar conceitos de várias áreas', dicas:['Não fuja do tema nem tangencie: use as palavras-chave do tema','Escreva no tipo dissertativo-argumentativo','Use repertório legitimado, pertinente e produtivo (ligado ao argumento)'] },
    { c:'Competência 3', t:'Selecionar, organizar e interpretar informações e argumentos', dicas:['Cada parágrafo defende uma ideia ligada à tese','Explique o "porquê" de cada argumento','Evite argumentos vagos, como "isso causa vários problemas"'] },
    { c:'Competência 4', t:'Mecanismos de coesão', dicas:['Use conectivos entre parágrafos e dentro deles','Varie os conectivos: não repita "além disso" o texto todo','Retome ideias com pronomes e sinônimos'] },
    { c:'Competência 5', t:'Proposta de intervenção', dicas:['Inclua os 5 elementos: agente, ação, meio, finalidade e detalhamento','A proposta precisa resolver as causas que você apresentou','Respeite os direitos humanos'] }
  ],
  zera: [
    'Fuga total ao tema',
    'Não obedecer ao tipo dissertativo-argumentativo',
    'Texto com até 7 linhas',
    'Cópia dos textos motivadores sem produção própria',
    'Impropérios, desenhos ou outras formas propositais de anulação',
    'Parte do texto deliberadamente desconectada do tema',
    'Assinatura, nome ou identificação fora do local indicado',
    'Texto predominantemente em língua estrangeira',
    'Folha de redação em branco, mesmo com texto no rascunho',
    'Letra ilegível'
  ],
  temasAnteriores: [
    '2024: Desafios para a valorização da herança africana no Brasil',
    '2023: Desafios para o enfrentamento da invisibilidade do trabalho de cuidado realizado pela mulher no Brasil',
    '2022: Desafios para a valorização de comunidades e povos tradicionais no Brasil',
    '2021: Invisibilidade e registro civil: garantia de acesso à cidadania no Brasil',
    '2020: O estigma associado às doenças mentais na sociedade brasileira',
    '2019: Democratização do acesso ao cinema no Brasil',
    '2018: Manipulação do comportamento do usuário pelo controle de dados na internet',
    '2017: Desafios para a formação educacional de surdos no Brasil',
    '2016: Caminhos para combater a intolerância religiosa no Brasil',
    '2015: A persistência da violência contra a mulher na sociedade brasileira'
  ],
  eixos: [
    'Saúde mental dos jovens','Desinformação e fake news','Inteligência artificial e trabalho','Envelhecimento da população',
    'Insegurança alimentar','Acesso à cultura e à leitura','Mobilidade urbana','Evasão escolar',
    'Racismo estrutural','Violência contra a mulher','Inclusão de pessoas com deficiência','Crise climática e eventos extremos',
    'Exposição de crianças nas redes sociais','Apostas on-line e endividamento','Povos indígenas e demarcação de terras','Trabalho por aplicativos',
    'Abandono de animais','Doação de órgãos e de sangue','Saneamento básico','Vacinação e cobertura vacinal'
  ]
}
};
