/* =========================================================
   QUESTÕES NO ESTILO DO ENEM (originais, autoria própria)
   m = matéria (id em resumos.js) · t = tema · c = índice da correta
   ========================================================= */
window.QUESTOES = [
/* ----- Matemática ----- */
{ m:'mat', t:'mat1', e:'Uma loja aumentou em 20% o preço de um tênis. No mês seguinte, anunciou uma promoção com 20% de desconto sobre o novo preço.\n\nEm relação ao preço original, o preço na promoção é', a:['igual ao preço original.','4% menor.','4% maior.','2% menor.','20% menor.'], c:1, x:'Multiplique os fatores: 1,20 × 0,80 = 0,96. O preço final é 96% do original, ou seja, 4% menor.' },
{ m:'mat', t:'mat2', e:'Em um mapa com escala 1 : 500 000, duas cidades estão a 6 cm de distância.\n\nA distância real entre essas cidades é de', a:['3 km.','30 km.','300 km.','0,3 km.','3 000 km.'], c:1, x:'6 cm × 500 000 = 3 000 000 cm. Como 1 km = 100 000 cm, a distância é 30 km.' },
{ m:'mat', t:'mat3', e:'As notas de um aluno em sete simulados foram: 5, 8, 6, 9, 7, 8 e 4.\n\nA mediana e a moda dessas notas são, respectivamente,', a:['7 e 8.','6,7 e 8.','8 e 7.','7 e 7.','6 e 8.'], c:0, x:'Em ordem: 4, 5, 6, 7, 8, 8, 9. O valor central (4º) é 7, a mediana. O valor que mais se repete é 8, a moda.' },
{ m:'mat', t:'mat5', e:'Uma caixa-d\'água tem formato de cilindro, com raio da base de 1 m e altura de 1,5 m. Use π = 3.\n\nA capacidade dessa caixa-d\'água, em litros, é', a:['450.','1 500.','3 000.','4 500.','9 000.'], c:3, x:'V = π · r² · h = 3 · 1² · 1,5 = 4,5 m³. Como 1 m³ = 1 000 L, a capacidade é 4 500 L.' },
{ m:'mat', t:'mat7', e:'Em um jogo, dois dados comuns, de seis faces, são lançados ao mesmo tempo.\n\nA probabilidade de a soma dos resultados ser 7 é', a:['1/36.','1/12.','1/6.','7/36.','1/2.'], c:2, x:'Há 36 resultados possíveis. Somam 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1), ou seja, 6 casos. 6/36 = 1/6.' },
/* ----- Física ----- */
{ m:'fis', t:'fis3', e:'Um chuveiro de 5 500 W fica ligado 20 minutos por dia durante 30 dias. A tarifa de energia é de R$ 0,80 por kWh.\n\nO custo mensal desse chuveiro é de', a:['R$ 4,40.','R$ 22,00.','R$ 44,00.','R$ 88,00.','R$ 132,00.'], c:2, x:'E = P · t = 5,5 kW × (1/3 h por dia) × 30 dias = 55 kWh. Custo: 55 × 0,80 = R$ 44,00.' },
{ m:'fis', t:'fis1', e:'Um carro a 72 km/h freia de modo uniforme e para completamente em 4 segundos.\n\nA distância percorrida durante a frenagem é de', a:['20 m.','40 m.','80 m.','144 m.','288 m.'], c:1, x:'72 km/h = 20 m/s. Na frenagem uniforme, a velocidade média é (20 + 0) / 2 = 10 m/s. Distância = 10 × 4 = 40 m.' },
{ m:'fis', t:'fis4', e:'Uma rádio FM transmite na frequência de 100 MHz. As ondas de rádio se propagam a 3 × 10⁸ m/s.\n\nO comprimento de onda dessa transmissão é de', a:['0,3 m.','3 m.','30 m.','300 m.','3 000 m.'], c:1, x:'λ = v / f = (3 × 10⁸) / (100 × 10⁶) = 3 m.' },
{ m:'fis', t:'fis3', e:'Nas residências, as tomadas e os aparelhos elétricos são ligados em paralelo.\n\nEssa ligação é usada porque', a:['a corrente é a mesma em todos os aparelhos.','os aparelhos recebem a mesma tensão e funcionam de forma independente.','o consumo total de energia diminui.','a resistência equivalente aumenta, evitando curtos.','apenas um aparelho pode funcionar de cada vez.'], c:1, x:'Em paralelo, todos os aparelhos ficam submetidos à mesma tensão da rede, e desligar um não interrompe os outros.' },
/* ----- Química ----- */
{ m:'qui', t:'qui1', e:'A água é formada pela reação 2 H₂ + O₂ → 2 H₂O. Massas molares: H = 1 g/mol e O = 16 g/mol.\n\nA massa de água produzida a partir de 4 g de gás hidrogênio, com oxigênio em excesso, é', a:['9 g.','18 g.','36 g.','72 g.','4 g.'], c:2, x:'4 g de H₂ (2 g/mol) = 2 mol. A proporção é 2 mol de H₂ para 2 mol de H₂O. 2 mol × 18 g/mol = 36 g.' },
{ m:'qui', t:'qui2', e:'Um técnico tem 100 mL de uma solução com concentração de 2 g/L e adiciona água até completar 400 mL.\n\nA concentração da nova solução é', a:['0,25 g/L.','0,5 g/L.','1 g/L.','4 g/L.','8 g/L.'], c:1, x:'Na diluição, C₁ · V₁ = C₂ · V₂: 2 × 100 = C₂ × 400, logo C₂ = 0,5 g/L.' },
{ m:'qui', t:'qui4', e:'Uma amostra de suco tem pH 3 e uma amostra de água de chuva tem pH 5.\n\nEm comparação com a água de chuva, a concentração de íons H⁺ no suco é', a:['2 vezes maior.','10 vezes maior.','100 vezes maior.','2 vezes menor.','100 vezes menor.'], c:2, x:'Cada unidade de pH equivale a 10 vezes na concentração de H⁺. Diferença de 2 unidades: 10 × 10 = 100 vezes maior.' },
{ m:'qui', t:'qui6', e:'O lançamento de esgoto rico em fosfatos em uma lagoa provocou a morte de muitos peixes.\n\nEsse processo ocorre porque', a:['os fosfatos são tóxicos e envenenam diretamente os peixes.','o excesso de nutrientes faz as algas proliferarem e, na decomposição delas, o oxigênio da água diminui.','os fosfatos aumentam a temperatura da água.','a água fica básica demais para os peixes.','os nutrientes impedem a entrada de luz solar no fundo da lagoa, congelando a água.'], c:1, x:'É a eutrofização: algas proliferam, morrem e são decompostas por bactérias que consomem o oxigênio dissolvido.' },
/* ----- Biologia ----- */
{ m:'bio', t:'bio2', e:'Um casal, ambos heterozigotos (Aa) para uma característica de herança recessiva, planeja ter um filho.\n\nA probabilidade de a criança manifestar a característica recessiva é', a:['0%.','25%.','50%.','75%.','100%.'], c:1, x:'Aa × Aa gera AA, Aa, Aa e aa. Só aa manifesta a característica recessiva: 1 em 4, ou 25%.' },
{ m:'bio', t:'bio3', e:'Uma pessoa picada por uma cobra peçonhenta foi levada ao hospital.\n\nO tratamento indicado é o', a:['soro, porque contém anticorpos prontos que agem rapidamente.','soro, porque estimula o corpo a produzir anticorpos.','antibiótico, porque o veneno é uma bactéria.','vacina, porque contém anticorpos prontos.','vacina, porque age em poucos minutos.'], c:0, x:'O soro traz anticorpos prontos (imunidade passiva) e age rápido. A vacina estimula a produção de anticorpos, o que leva tempo.' },
{ m:'bio', t:'bio6', e:'O uso indiscriminado de antibióticos tem levado ao aumento de bactérias resistentes.\n\nDe acordo com a teoria da seleção natural, isso ocorre porque', a:['as bactérias aprendem a resistir ao remédio.','o antibiótico provoca mutações para que as bactérias sobrevivam.','bactérias que já eram resistentes sobrevivem e se multiplicam.','as bactérias usam mais o gene da resistência e o fortalecem.','o corpo humano passa a produzir antibióticos naturais.'], c:2, x:'A variação já existia. O antibiótico elimina as sensíveis, e as resistentes sobrevivem e se reproduzem. As alternativas com "aprender" ou "usar mais" são ideias de Lamarck.' },
{ m:'bio', t:'bio1', e:'Em um lago contaminado por mercúrio, a cadeia alimentar é: fitoplâncton → pequenos peixes → peixes grandes → aves.\n\nA maior concentração de mercúrio por quilo de tecido será encontrada', a:['no fitoplâncton.','nos pequenos peixes.','nos peixes grandes.','nas aves.','igualmente em todos os níveis.'], c:3, x:'É a bioacumulação (magnificação trófica): substâncias não eliminadas se acumulam e se concentram ao longo da cadeia, chegando ao máximo no topo.' },
/* ----- História ----- */
{ m:'his', t:'his2', e:'A Lei Áurea, de 1888, aboliu a escravidão no Brasil sem estabelecer políticas de acesso à terra, à educação ou ao trabalho para os libertos.\n\nUma consequência desse processo foi', a:['a integração imediata dos libertos ao mercado de trabalho formal.','a marginalização social da população negra, com efeitos até hoje.','a distribuição de terras aos ex-escravizados.','o fim imediato do preconceito racial.','a criação de escolas públicas para os libertos.'], c:1, x:'Sem políticas de inclusão, a população negra foi deixada à margem, o que se relaciona com desigualdades raciais atuais.' },
{ m:'his', t:'his4', e:'O Ato Institucional nº 5, de 1968, é considerado o momento mais duro da ditadura militar brasileira.\n\nUma medida característica desse ato foi', a:['a convocação de eleições diretas para presidente.','a ampliação da censura e a suspensão de garantias individuais.','a anistia aos presos políticos.','a criação da Constituição de 1988.','o fim do bipartidarismo.'], c:1, x:'O AI-5 permitiu fechar o Congresso, ampliou a censura e suspendeu o habeas corpus para crimes políticos.' },
{ m:'his', t:'his3', e:'Em 1943, foi aprovada no Brasil a Consolidação das Leis do Trabalho (CLT), que reuniu direitos como a regulamentação da jornada e as férias.\n\nA CLT foi criada durante', a:['o Império.','a República Velha.','a Era Vargas.','a ditadura militar.','a Nova República.'], c:2, x:'A CLT é de 1943, durante o Estado Novo, período da Era Vargas (1930 a 1945).' },
{ m:'his', t:'his5', e:'"Liberdade, igualdade e fraternidade" foi o lema de um movimento do século XVIII que influenciou a formação das democracias modernas.\n\nEsse movimento foi a', a:['Revolução Industrial.','Revolução Francesa.','Reforma Protestante.','Revolução Russa.','Independência do Brasil.'], c:1, x:'O lema é da Revolução Francesa (1789), inspirada pelos ideais iluministas.' },
/* ----- Geografia ----- */
{ m:'geo', t:'geo7', e:'A cidade B está localizada 45° de longitude a leste da cidade A.\n\nQuando são 9 h na cidade A, na cidade B são', a:['6 h.','8 h.','9 h.','12 h.','15 h.'], c:3, x:'Cada 15° equivalem a 1 hora. 45° = 3 horas. Para leste, o horário é adiantado: 9 h + 3 h = 12 h.' },
{ m:'geo', t:'geo1', e:'Nas grandes cidades, a temperatura costuma ser mais alta no centro do que nas áreas periféricas com mais vegetação.\n\nEsse fenômeno, chamado ilha de calor, é causado principalmente', a:['pelo excesso de chuvas no centro.','pela concentração de asfalto, concreto e construções e pela pouca vegetação.','pelo aumento da altitude no centro.','pela proximidade com o oceano.','pela inversão térmica no verão.'], c:1, x:'Asfalto e concreto absorvem e liberam calor, e a falta de vegetação reduz a evapotranspiração, que resfria o ar.' },
{ m:'geo', t:'geo2', e:'Um bairro antigo e popular recebe investimentos, o valor dos imóveis e dos aluguéis sobe, e parte dos moradores originais é obrigada a se mudar.\n\nEsse processo é chamado de', a:['conurbação.','gentrificação.','metropolização.','êxodo rural.','desconcentração industrial.'], c:1, x:'Gentrificação é a valorização de uma área que leva à substituição da população de menor renda.' },
{ m:'geo', t:'geo5', e:'Em dias frios de inverno, é comum a poluição ficar concentrada perto do solo nas grandes cidades.\n\nIsso ocorre por causa da', a:['ilha de calor.','chuva ácida.','inversão térmica.','camada de ozônio.','maritimidade.'], c:2, x:'Na inversão térmica, uma camada de ar quente fica acima do ar frio junto ao solo e impede a dispersão dos poluentes.' },
/* ----- Filosofia e Sociologia ----- */
{ m:'fil', t:'fil3', e:'Para Émile Durkheim, os fatos sociais são maneiras de agir, pensar e sentir que existem fora do indivíduo e se impõem a ele.\n\nSão características dos fatos sociais:', a:['individualidade, liberdade e espontaneidade.','exterioridade, coercitividade e generalidade.','alienação, mais-valia e luta de classes.','carisma, tradição e legalidade.','razão, experiência e dúvida.'], c:1, x:'Durkheim define os fatos sociais como exteriores, coercitivos e gerais. Mais-valia é de Marx; carisma, tradição e legalidade são de Weber.' },
{ m:'fil', t:'fil3', e:'Para Max Weber, há uma forma de dominação baseada em regras impessoais, leis e na hierarquia de cargos, como na burocracia moderna.\n\nEssa forma é a dominação', a:['tradicional.','carismática.','legal ou racional.','patriarcal.','feudal.'], c:2, x:'A dominação legal (racional) se apoia em normas e procedimentos impessoais, típicos do Estado moderno.' },
{ m:'fil', t:'fil1', e:'No Mito da Caverna, de Platão, prisioneiros acorrentados veem apenas sombras na parede e acreditam que elas são a realidade.\n\nA alegoria pode ser usada para refletir sobre', a:['a importância da força física.','a passagem da ignorância ao conhecimento.','a superioridade da vida no campo.','a defesa da monarquia absoluta.','a teoria da evolução.'], c:1, x:'A saída da caverna representa o caminho do conhecimento, que liberta das aparências. Hoje a alegoria é usada para discutir desinformação.' },
{ m:'fil', t:'fil4', e:'Um grupo considera os costumes de outro povo "atrasados" apenas por serem diferentes dos seus.\n\nEssa postura é chamada de', a:['relativismo cultural.','etnocentrismo.','aculturação.','multiculturalismo.','sincretismo.'], c:1, x:'Etnocentrismo é julgar outras culturas tomando a própria como padrão. O relativismo busca compreender cada cultura em seu contexto.' },
/* ----- Linguagens ----- */
{ m:'lin', t:'lin4', e:'Um estudante riu da forma como um colega de outra região pronunciava algumas palavras.\n\nDo ponto de vista dos estudos linguísticos, essa atitude é', a:['adequada, pois existe uma única forma correta de falar.','um exemplo de preconceito linguístico, pois a variação é natural na língua.','correta, pois o sotaque deve ser corrigido na escola.','justificada, pois a fala regional não tem regras.','irrelevante, pois a língua não varia entre regiões.'], c:1, x:'A variação regional é legítima. Discriminar alguém pelo modo de falar é preconceito linguístico.' },
{ m:'lin', t:'lin3', e:'Um anúncio diz: "Não perca tempo! Garanta já o seu ingresso."\n\nNesse trecho predomina a função da linguagem', a:['referencial.','emotiva.','conativa ou apelativa.','metalinguística.','fática.'], c:2, x:'O texto se dirige ao leitor para convencê-lo a agir, com verbos no imperativo: é a função conativa.' },
{ m:'lin', t:'lin7', e:'Em um texto em inglês, aparece a frase: "He pretended to be asleep when his mother came in."\n\nO verbo "pretended" indica que ele', a:['pretendia dormir.','fingiu estar dormindo.','preferiu dormir.','precisou dormir.','prometeu dormir.'], c:1, x:'"Pretend" é um falso cognato: significa fingir, e não pretender.' },
{ m:'lin', t:'lin1', e:'"Ler não é apenas decifrar palavras. É relacionar o que está escrito com o que já se sabe, questionar e construir sentidos."\n\nA ideia central do trecho é que a leitura', a:['depende apenas do vocabulário do leitor.','é um processo ativo de construção de sentido.','deve ser feita em voz alta.','é mais importante que a escrita.','só é possível com textos literários.'], c:1, x:'O trecho apresenta a leitura como atividade ativa: relacionar, questionar e construir sentidos.' },
/* ----- Redação ----- */
{ m:'red', t:'red1', e:'Segundo os critérios do ENEM, qual das situações abaixo leva a redação a receber nota zero?', a:['Usar apenas um repertório sociocultural.','Escrever um texto com até 7 linhas.','Fazer a proposta de intervenção com só três elementos.','Usar conectivos repetidos.','Escrever a introdução em um único período.'], c:1, x:'Textos com até 7 linhas são considerados insuficientes e recebem zero. As outras situações tiram pontos, mas não zeram.' },
{ m:'red', t:'red4', e:'"Portanto, o governo deve criar campanhas de conscientização."\n\nNessa proposta de intervenção, estão presentes', a:['os cinco elementos exigidos.','apenas o agente e a ação.','apenas a finalidade.','o agente, a ação, o meio e a finalidade.','apenas o detalhamento.'], c:1, x:'Há agente (o governo) e ação (criar campanhas). Faltam meio, finalidade e detalhamento.' },
{ m:'red', t:'red2', e:'Qual conectivo é mais adequado para iniciar um parágrafo que apresenta uma ideia contrária à anterior?', a:['Além disso.','Portanto.','Entretanto.','Por exemplo.','Em primeiro lugar.'], c:2, x:'"Entretanto" expressa oposição. "Além disso" é adição; "portanto", conclusão; "por exemplo", exemplificação.' }
];
