/* Biologia: textos corridos, temas 22 a 25 */
module.exports = [
{ t:'Reprodução humana e métodos contraceptivos', txt:[
 { h:'Sistema reprodutor masculino e feminino', p:[
  'O **sistema reprodutor** é responsável pela produção dos gametas, pela fecundação e, nas mulheres, pelo desenvolvimento do embrião. No **sistema masculino**, os **testículos**, alojados na bolsa escrotal, produzem os espermatozoides e o hormônio **testosterona**. A bolsa escrotal mantém a temperatura dos testículos cerca de 2 a 3 °C abaixo da do corpo, condição necessária à produção de espermatozoides. Os espermatozoides amadurecem no **epidídimo** e seguem pelo **ducto deferente** até a **uretra**. A **próstata**, as **vesículas seminais** e as glândulas bulbouretrais produzem o líquido que, junto com os espermatozoides, forma o **sêmen**.',
  'No **sistema feminino**, os **ovários** produzem os óvulos e os hormônios **estrógeno** e **progesterona**. As **tubas uterinas** (trompas) conduzem o óvulo até o **útero**, órgão muscular onde o embrião se desenvolve; é nas tubas que normalmente ocorre a **fecundação**. O útero se comunica com o exterior pela **vagina**, que também recebe o sêmen e é o canal do parto. A parede interna do útero, o **endométrio**, espessa-se a cada ciclo para receber o embrião. As **glândulas mamárias** produzem leite sob a ação da prolactina e da ocitocina, que atua na ejeção do leite e nas contrações do parto.',
  'A produção dos gametas é diferente nos dois sexos. Nos homens, a **espermatogênese** inicia na puberdade e ocorre de forma contínua ao longo da vida, produzindo milhões de espermatozoides por dia. Nas mulheres, a **ovogênese** começa ainda na vida fetal, e a mulher nasce com todos os ovócitos que terá, e a partir da puberdade, em geral, um é liberado por ciclo, até a **menopausa**, por volta dos 45 a 55 anos, quando os ciclos cessam. Essa diferença explica por que a fertilidade feminina diminui de forma mais marcante com a idade.'] },
 { h:'Ciclo menstrual, fecundação e gravidez', p:[
  'O **ciclo menstrual** dura, em média, 28 dias, e é controlado por hormônios da hipófise e dos ovários. Na primeira fase, o **FSH** estimula o crescimento de folículos no ovário, que produzem estrógeno, e o endométrio se espessa. Na metade do ciclo, um pico de **LH** provoca a **ovulação**, liberação do óvulo, por volta do 14º dia. O folículo rompido forma o **corpo lúteo**, que produz **progesterona**, a qual prepara o útero. Se não houver fecundação, o corpo lúteo regride, os hormônios caem e o endométrio descama na **menstruação**.',
  'A **fecundação** é a união do espermatozoide com o óvulo, que forma o **zigoto**, a primeira célula do novo indivíduo, e ocorre na tuba uterina. O zigoto passa por divisões (clivagem), forma uma estrutura de muitas células, a **mórula** e depois a **blástula**, que se **implanta** no endométrio (nidação), cerca de 6 a 8 dias após a fecundação. A partir daí, o embrião libera o hormônio **hCG**, que mantém o corpo lúteo ativo, e que é detectado nos testes de gravidez. Forma-se a **placenta**, órgão de troca de nutrientes, gases e resíduos entre a mãe e o feto, sem que o sangue de ambos se misture.',
  'A **gestação** dura cerca de 40 semanas. O desenvolvimento passa por **embrião** (até a 8ª semana, quando se formam os órgãos) e **feto**. Durante a gravidez, o consumo de álcool, de cigarro e de certas drogas e medicamentos, e infecções como a rubéola, a toxoplasmose e a zika, podem causar malformações. O **ácido fólico** previne defeitos do tubo neural, e o **pré-natal** acompanha a saúde da mãe e do bebê. O **parto** é desencadeado por hormônios, como a ocitocina, e pode ser normal ou por cesariana. O **aleitamento materno** fornece nutrientes e anticorpos e é recomendado nos primeiros seis meses.'] },
 { h:'Métodos contraceptivos', p:[
  'Os **métodos contraceptivos** evitam a gravidez, e podem ser classificados por seu mecanismo. Os **de barreira** impedem o encontro dos gametas: o **preservativo masculino e o feminino** (camisinha), o diafragma e o espermicida. Os **hormonais** impedem a ovulação ou alteram o muco e o endométrio: pílula anticoncepcional, injetáveis, adesivos, anel vaginal, implante subdérmico e a pílula de emergência. Os **dispositivos intrauterinos** (DIU) podem ser de cobre ou hormonais, e dificultam a fecundação e a implantação. Os **definitivos** são a laqueadura tubária (mulheres) e a vasectomia (homens), que exigem cirurgia.',
  'Os **métodos comportamentais** (ou naturais), como a tabelinha, a medição da temperatura basal e a observação do muco, dependem da identificação do período fértil e têm **eficácia menor**, pois o ciclo pode variar. O **coito interrompido** também não é confiável, pois o líquido pré-ejaculatório pode conter espermatozoides. A **pílula do dia seguinte** é um contraceptivo de emergência, usado após uma relação desprotegida, que age principalmente retardando a ovulação, e não deve ser usado como método regular. É diferente do aborto, que é a interrupção da gravidez já estabelecida, e que tem regras legais próprias.',
  'Um ponto central é que **só o preservativo protege contra as infecções sexualmente transmissíveis** (ISTs), como HIV, sífilis, gonorreia, clamídia, HPV e hepatites, além de prevenir a gravidez. Os demais métodos só evitam a gravidez. Por isso, recomenda-se o uso do preservativo mesmo com outro método associado (dupla proteção). A escolha de um método deve levar em conta a saúde, a idade, os efeitos colaterais, a facilidade de uso e a orientação de um profissional. A **educação sexual** e o acesso gratuito a métodos pelo SUS são políticas importantes de saúde pública, de prevenção da gravidez na adolescência e de ISTs.'] },
 { h:'Infecções sexualmente transmissíveis, infertilidade e reprodução assistida', p:[
  'As **ISTs** são transmitidas principalmente por contato sexual, e algumas também por sangue ou da mãe para o filho. A **sífilis**, causada pela bactéria Treponema pallidum, tem fases e, sem tratamento, pode afetar o coração e o sistema nervoso; na gestação, pode causar malformações e perda do bebê. A **gonorreia** e a **clamídia**, bacterianas, podem causar infertilidade se não tratadas. O **HPV** é um vírus associado a verrugas genitais e ao câncer de colo do útero, e é prevenido pela vacina. A **hepatite B** também é prevenida por vacina, e o **HIV** é controlado com antirretrovirais.',
  'A **infertilidade** é a dificuldade de conseguir uma gravidez após um ano de tentativas, e pode ter causas masculinas, femininas ou mistas, como baixa produção de espermatozoides, obstrução das tubas, endometriose e distúrbios hormonais. As **técnicas de reprodução assistida** auxiliam nesses casos. Na **inseminação artificial**, os espermatozoides são colocados diretamente no útero. Na **fertilização in vitro**, os óvulos são fecundados em laboratório e os embriões são transferidos ao útero. Essas técnicas trazem debates éticos, como o descarte de embriões, a doação de gametas e a escolha de características.',
  'Os **gêmeos** podem ser **idênticos** (monozigóticos), quando um único zigoto se divide em dois embriões, e têm o mesmo material genético e o mesmo sexo; ou **fraternos** (dizigóticos), quando dois óvulos são fecundados por dois espermatozoides, e são geneticamente tão semelhantes quanto irmãos comuns. A determinação do sexo depende do espermatozoide, que leva X ou Y. Os conhecimentos de reprodução também se aplicam ao **planejamento familiar**, à saúde da mulher, e à discussão sobre direitos sexuais e reprodutivos, assunto presente em questões e em temas de redação.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em reprodução humana, o ENEM costuma cobrar o ciclo menstrual (gráficos hormonais e período fértil), os métodos contraceptivos (mecanismo de ação e eficácia), a prevenção de ISTs, a gravidez na adolescência e a gestação (cuidados, placenta, hCG), além da reprodução assistida e da formação de gêmeos. A abordagem é voltada à saúde e à cidadania, e o enunciado pode partir de uma campanha, de um folheto ou de uma situação do cotidiano.',
  'Dicas: em gráficos do ciclo, identifique o pico de LH (ovulação), o aumento de progesterona depois dela e a queda hormonal antes da menstruação; a ovulação ocorre, em média, na metade do ciclo, e o período fértil abrange alguns dias antes e depois, porque o espermatozoide sobrevive por vários dias; só o preservativo previne ISTs; e a pílula age impedindo a ovulação por manter os hormônios em nível constante, o que inibe o pico de LH. Atenção aos enunciados que pedem "o método mais eficaz" ou "o que previne também as ISTs".',
  'Para revisar: testículos produzem espermatozoides e testosterona, e ovários produzem óvulos, estrógeno e progesterona; a fecundação ocorre na tuba uterina e a implantação, no útero; a placenta faz as trocas entre mãe e feto; a pílula impede a ovulação, o DIU e os preservativos agem de outras formas; o preservativo protege contra ISTs; gêmeos idênticos vêm de um zigoto e fraternos, de dois. Esse tema se conecta a hormônios, genética e saúde pública, e é um dos mais próximos do cotidiano dos candidatos.'] }
]},
{ t:'Botânica', txt:[
 { h:'Os grupos de plantas e sua evolução', p:[
  'A **Botânica** estuda as plantas, organismos eucariontes, pluricelulares, autótrofos fotossintetizantes, com parede celular de celulose. Seu ciclo de vida apresenta **alternância de gerações**: uma fase **haploide** (gametófito), que produz gametas, e uma fase **diploide** (esporófito), que produz esporos. O tamanho relativo dessas fases varia entre os grupos. A conquista do ambiente terrestre exigiu adaptações, como a **cutícula** impermeável, que reduz a perda de água, os **estômatos**, que regulam as trocas gasosas, os **tecidos de sustentação** e de **condução** e a produção de **esporos e sementes** resistentes.',
  'Os grandes grupos são quatro. As **briófitas** (musgos e hepáticas) são pequenas, não têm vasos condutores e dependem da água para a fecundação, por isso vivem em locais úmidos; a fase dominante é o gametófito. As **pteridófitas** (samambaias e avencas) têm **vasos condutores**, mas não produzem sementes, e a fase dominante é o esporófito. As **gimnospermas** (pinheiros, araucárias e ciprestes) produzem **sementes sem frutos** e dispensam a água para a fecundação, com o pólen levado pelo vento. As **angiospermas** (a maioria das plantas) produzem **flores, frutos e sementes**.',
  'As angiospermas são o grupo mais diverso, com mais de 250 mil espécies, e se dividem em **monocotiledôneas** (capim, milho, arroz, trigo, palmeiras), com uma folha embrionária (cotilédone), folhas de nervuras paralelas, raízes fasciculadas e flores com partes em múltiplos de três; e **eudicotiledôneas** (feijão, soja, rosa, laranjeira), com dois cotilédones, folhas de nervuras ramificadas, raiz pivotante e flores com partes em múltiplos de quatro ou cinco. O fruto, que protege a semente e auxilia na dispersão, é uma das chaves do sucesso evolutivo desse grupo.'] },
 { h:'Morfologia: raiz, caule, folha, flor, fruto e semente', p:[
  'A **raiz** fixa a planta ao solo, absorve água e sais minerais pelos **pelos absorventes** e, em certos casos, armazena reservas (cenoura, mandioca, beterraba). O **caule** sustenta a planta, conduz as substâncias e pode armazenar reservas (cana-de-açúcar, batata, que é um caule subterrâneo). A **folha** é o principal órgão da fotossíntese e da transpiração. Na folha, a epiderme tem **estômatos**, estruturas que se abrem e se fecham para controlar as trocas gasosas e a perda de água, comandadas por células-guarda. A maior parte da água absorvida pela planta é perdida pela transpiração.',
  'A **flor** é o órgão reprodutor das angiospermas. É formada por **sépalas** (que compõem o cálice), **pétalas** (que compõem a corola e atraem polinizadores), **estames**, o órgão masculino (formado por antera, que produz pólen, e filete) e o **carpelo** (pistilo), órgão feminino, formado por estigma (que recebe o pólen), estilete e ovário (que contém os óvulos). Após a **polinização**, que pode ser feita por vento, insetos, aves ou morcegos, o grão de pólen forma um tubo que leva os gametas masculinos até o óvulo, e ocorre a **dupla fecundação**, característica das angiospermas.',
  'Depois da fecundação, o **óvulo** se desenvolve em **semente**, que contém o embrião e as reservas, e o **ovário** se transforma em **fruto**, que protege a semente e favorece sua dispersão. Existem **frutos verdadeiros**, formados a partir do ovário, e **pseudofrutos** (falsos frutos), em que outra parte da flor participa, como o pedúnculo no caju e o receptáculo no morango. A **dispersão** das sementes pode ocorrer pelo vento, pela água e por animais, que as ingerem ou as carregam. Frutos coloridos e saborosos atraem animais dispersores, em uma interação em que ambos se beneficiam.'] },
 { h:'Transporte de seiva, fotossíntese e transpiração', p:[
  'As plantas vasculares possuem dois tecidos de condução. O **xilema** (lenho) conduz a **seiva bruta**, formada por água e sais minerais absorvidos pela raiz, até as folhas, em sentido ascendente. O **floema** (líber) conduz a **seiva elaborada**, rica em açúcares produzidos na fotossíntese, das folhas para as demais partes da planta, e pode ser em ambos os sentidos. O xilema é formado por células mortas, dispostas como tubos, e o floema por células vivas. A retirada de um anel de casca de uma árvore (anelamento) interrompe o floema, e a raiz deixa de receber alimento, levando a planta à morte.',
  'A ascensão da seiva bruta, às vezes por dezenas de metros, é explicada pela **teoria da coesão-tensão**. Com a **transpiração** nas folhas, a perda de água pelos estômatos cria uma tensão que "puxa" a coluna de água do xilema, em que as moléculas de água permanecem unidas, graças à coesão e à adesão às paredes dos vasos. A **absorção** de água nas raízes é auxiliada pela osmose. Por isso, a transpiração é fundamental para o transporte de água e nutrientes, e também para o resfriamento da planta, mas, em excesso, causa murchamento.',
  'Os **estômatos** abrem-se em presença de luz e de água suficiente, permitindo a entrada de CO2 para a fotossíntese, mas também a saída de água. Em períodos de seca, as plantas fecham os estômatos para economizar água, o que reduz a fotossíntese. As plantas de ambientes secos, as **xerófitas**, têm adaptações como folhas pequenas, espinhos, cutícula espessa e estômatos em depressões. As de ambientes aquáticos, as **hidrófitas**, possuem tecidos com espaços de ar que auxiliam na flutuação. Essa relação entre estrutura, função e ambiente é muito explorada nas provas.'] },
 { h:'Hormônios vegetais, tropismos e importância das plantas', p:[
  'O desenvolvimento das plantas é regulado por **hormônios vegetais** (fitormônios). A **auxina** estimula o alongamento celular, produz o crescimento do caule e participa do **fototropismo**, a curvatura em direção à luz, pois se acumula no lado menos iluminado, que cresce mais. As **giberelinas** promovem o crescimento do caule e a germinação. As **citocininas** estimulam a divisão celular. O **etileno**, um gás, promove o **amadurecimento dos frutos**, e por isso uma banana madura acelera a maturação das demais. O **ácido abscísico** induz a dormência e o fechamento dos estômatos em períodos de seca.',
  'Os **tropismos** são movimentos de crescimento em resposta a estímulos. O **fototropismo** é a resposta à luz (positivo no caule, que cresce em direção a ela), o **geotropismo** (gravitropismo) é a resposta à gravidade (positivo na raiz, que cresce para baixo) e o **hidrotropismo** é a resposta à água. O **fotoperiodismo** é a resposta à duração do dia e da noite, e define a época de floração de muitas espécies, que podem ser plantas de dia curto, de dia longo ou indiferentes. Esse conhecimento é aplicado na agricultura, para controlar a floração e a produção.',
  'As plantas têm enorme importância para os seres humanos e para o planeta. São a base das cadeias alimentares, produzem o oxigênio, retiram CO2 da atmosfera, protegem o solo, regulam o ciclo da água e fornecem alimentos, fibras, madeira, medicamentos e matérias-primas. Os **fármacos** de origem vegetal, como a aspirina (da casca do salgueiro) e a quinina (da quina), têm grande valor. O uso de técnicas como a **cultura de tecidos** e a **propagação vegetativa** (enxertia, estaquia) permite produzir mudas idênticas, e a **engenharia genética** desenvolve variedades mais produtivas e resistentes.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Botânica no ENEM costuma aparecer em questões de contexto: polinização e a relação com animais e com a produção de alimentos, a perda de água e o uso de plantas em ambientes secos, hormônios vegetais na agricultura (amadurecimento de frutos), a importância das florestas, o reflorestamento, e as adaptações de plantas aos biomas. Também surgem esquemas de flores e de frutos, e experimentos com luz e crescimento. A questão costuma pedir que se relacione uma estrutura à sua função.',
  'Pontos de atenção: o xilema conduz seiva bruta (água e sais) e o floema conduz seiva elaborada (açúcares); a transpiração ocorre pelos estômatos e é o motor do transporte de água; o fruto vem do ovário e a semente, do óvulo; as angiospermas têm flores e frutos, as gimnospermas têm sementes sem frutos, e as briófitas e pteridófitas se reproduzem por esporos; o etileno amadurece os frutos; e a auxina atua no fototropismo. Em experimentos, observe qual fator foi variado e qual o resultado.',
  'Para revisar, faça um quadro com os quatro grupos de plantas e as inovações de cada um: briófitas (primeiras plantas terrestres, sem vasos), pteridófitas (vasos), gimnospermas (sementes) e angiospermas (flores e frutos). Associe cada órgão da planta à função, e cada hormônio a um efeito. Isso organiza o conteúdo e facilita a resolução de questões. O estudo seguinte, a Zoologia, fecha a parte de diversidade dos seres vivos e aprofunda as adaptações dos animais.'] }
]},
{ t:'Zoologia', txt:[
 { h:'Características gerais dos animais e dos invertebrados', p:[
  'Os **animais** são organismos eucariontes, pluricelulares, **heterótrofos** (ingerem o alimento), sem parede celular e, em geral, com capacidade de locomoção em alguma fase da vida. A maior parte tem **reprodução sexuada**, com desenvolvimento embrionário e, em muitos casos, larvas. Quanto ao número de folhetos embrionários, podem ser **diblásticos** (ectoderme e endoderme, como poríferos e cnidários) ou **triblásticos** (ectoderme, mesoderme e endoderme), e quanto à simetria, **assimétricos** (esponjas), de **simetria radial** (cnidários e equinodermos adultos) ou de **simetria bilateral** (a maioria).',
  'Os **poríferos** (esponjas) são aquáticos, sésseis, sem tecidos verdadeiros, e filtram a água por poros. Os **cnidários** (águas-vivas, corais, anêmonas) possuem **cnidócitos**, células urticantes de defesa e captura de presas, e cavidade digestória incompleta. Os **platelmintos** (planárias, tênias, esquistossomos) são vermes achatados, sem cavidade corporal (acelomados), e muitos são parasitas. Os **nematelmintos** (lombrigas, oxiúros) são vermes cilíndricos, com tubo digestório completo. Os **anelídeos** (minhocas, sanguessugas) têm o corpo segmentado em anéis, e as minhocas aeram o solo.',
  'Os **moluscos** (caramujos, mexilhões, lulas e polvos) têm corpo mole, em geral protegido por uma concha, e se dividem em gastrópodes, bivalves e cefalópodes, estes últimos os de maior inteligência entre os invertebrados. Os **artrópodes**, o maior grupo, têm **exoesqueleto de quitina**, corpo segmentado e apêndices articulados; incluem insetos (seis patas, três pares), aracnídeos (oito patas, como aranhas e escorpiões), crustáceos (camarões, caranguejos) e miriápodes (centopeias). Os **equinodermos** (estrelas-do-mar, ouriços) são marinhos, com simetria radial e sistema ambulacral. Cada grupo tem importância ecológica e econômica.'] },
 { h:'Os cordados e os vertebrados', p:[
  'Os **cordados** possuem, ao menos em alguma fase da vida, **notocorda** (um bastão de sustentação dorsal), **tubo nervoso dorsal**, **fendas branquiais** na faringe e cauda pós-anal. Nos **vertebrados**, a notocorda é substituída pela **coluna vertebral**, e há crânio, que protege o encéfalo. Os vertebrados se dividem em peixes, anfíbios, répteis, aves e mamíferos. Os **peixes** são aquáticos, têm respiração branquial, coração com duas cavidades e circulação simples, e se dividem em cartilaginosos (tubarões e raias) e ósseos (a maioria). Em geral, são ectotérmicos, ou seja, têm a temperatura corporal dependente do ambiente.',
  'Os **anfíbios** (sapos, rãs, salamandras) fazem a transição entre a água e a terra: as larvas (girinos) respiram por brânquias, e os adultos, por pulmões e pela pele, que é fina, úmida e permeável. Por isso dependem da água para a reprodução, e são muito sensíveis à poluição, servindo de bioindicadores. Os **répteis** (cobras, lagartos, jacarés, tartarugas) têm a pele seca, com escamas, e põem ovos com casca, que dispensam a água para o desenvolvimento do embrião, graças às **membranas extraembrionárias** (âmnio). Essa conquista foi decisiva para a ocupação definitiva do ambiente terrestre.',
  'As **aves** têm penas, bico, ossos pneumáticos (leves), respiração por pulmões com sacos aéreos, coração com quatro cavidades e circulação dupla e completa, e são **endotérmicas**, mantendo a temperatura corporal constante. Os **mamíferos** apresentam pelos, glândulas mamárias que produzem leite, diafragma e coração de quatro cavidades, e também são endotérmicos. Dividem-se em **monotremados** (ovíparos, como o ornitorrinco), **marsupiais** (filhotes concluem o desenvolvimento em uma bolsa, como o canguru e o gambá) e **placentários** (desenvolvimento no útero, com placenta, como os humanos). A endotermia permitiu a ocupação de ambientes frios, mas exige muita energia.'] },
 { h:'Adaptações, fisiologia comparada e reprodução', p:[
  'Os animais apresentam adaptações variadas ao ambiente. A **circulação** pode ser **aberta** (em artrópodes e moluscos, em que o sangue banha os tecidos) ou **fechada** (em anelídeos e vertebrados, em que o sangue permanece em vasos). A **respiração** pode ser cutânea (minhocas, anfíbios), branquial (peixes, crustáceos), traqueal (insetos, por tubos de ar) ou pulmonar (a maioria dos vertebrados terrestres). A **excreção** varia entre amônia, nos animais aquáticos, ureia nos mamíferos e anfíbios adultos, e ácido úrico nas aves, répteis e insetos, que economiza água. Essas diferenças refletem as condições de cada ambiente.',
  'A **reprodução** também varia. Há animais **ovíparos**, em que o embrião se desenvolve em um ovo fora do corpo da mãe, **vivíparos**, em que se desenvolve dentro do corpo materno, com alimentação pela placenta, e **ovovivíparos**, em que o ovo é retido no corpo, mas o embrião se alimenta de suas reservas. A fecundação pode ser externa, como em muitos peixes e anfíbios, que liberam grande quantidade de gametas na água, ou interna, que exige menos gametas, mas gera mais cuidado com os filhotes. O **cuidado parental** é maior nas aves e nos mamíferos.',
  'O **desenvolvimento** pode ser **direto**, quando o filhote lembra o adulto, ou **indireto**, com **metamorfose**, em que há uma larva diferente do adulto. Nos insetos, a metamorfose pode ser **completa** (holometábolos, com larva, pupa e adulto, como borboletas e moscas) ou **incompleta** (hemimetábolos, em que as ninfas lembram os adultos, como baratas e gafanhotos). Nos anfíbios, o girino se transforma em adulto. A metamorfose permite que larvas e adultos ocupem nichos diferentes e evita a competição entre eles, e está ligada a hormônios, como a ecdisona nos insetos e a tiroxina nos anfíbios.'] },
 { h:'Importância dos animais, biodiversidade e conservação', p:[
  'Os animais exercem papéis ecológicos essenciais: são consumidores em todas as cadeias alimentares, **polinizadores** e dispersores de sementes, controladores de populações, decompositores (como as minhocas) e engenheiros de ecossistemas (como os castores e os cupins). As abelhas, por exemplo, polinizam uma grande parte das culturas de alimentos, e o declínio de suas populações, associado a agrotóxicos, perda de habitat e doenças, ameaça a produção agrícola. Os animais também são importantes economicamente (alimentação, couro, lã, mel, pesquisa científica) e culturalmente.',
  'Muitas espécies animais têm importância para a saúde pública, como **vetores** de doenças: o mosquito Aedes (dengue), o Anopheles (malária), o barbeiro (doença de Chagas), o caramujo, hospedeiro do esquistossomo, e os roedores (leptospirose). O controle desses animais é feito com saneamento, higiene e controle de vetores, evitando, sempre que possível, o extermínio indiscriminado, que desequilibra os ecossistemas. Os animais peçonhentos, como cobras, aranhas e escorpiões, exigem cuidado, e os acidentes são tratados com **soro** específico.',
  'A **fauna brasileira** é uma das mais ricas do mundo, mas sofre ameaças: destruição de habitats, **caça** e **tráfico de animais silvestres**, poluição, atropelamentos e espécies invasoras. O tráfico é um dos maiores causadores de extinção. A conservação envolve unidades de conservação, fiscalização, **programas de reprodução em cativeiro**, **corredores ecológicos**, educação ambiental e **legislação**, como a Lei de Crimes Ambientais. Espécies **endêmicas**, as que só existem em uma região, como o mico-leão-dourado e a onça-pintada em certas áreas, exigem proteção especial.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Zoologia no ENEM costuma ser cobrada de maneira comparativa e contextualizada: adaptações de animais a ambientes, características que definem um grupo (por exemplo, "vertebrado de pele úmida e que depende da água para se reproduzir"), cladogramas de parentesco, ciclos de vida de parasitas e de vetores, excreção e economia de água, e a importância dos animais para o ambiente e para a saúde. Muitas questões usam um animal pouco conhecido, mas com informações suficientes no texto para a resolução.',
  'Dicas de estudo: aprenda as **novidades evolutivas** de cada grupo, que servem de chave para classificar (tecidos verdadeiros nos cnidários, tubo digestório completo nos nematelmintos, exoesqueleto nos artrópodes, coluna vertebral nos vertebrados, ovo com casca nos répteis, penas nas aves, pelos e leite nos mamíferos). Em cladogramas, siga os ramos para definir quem compartilha ancestral mais recente. Em adaptação, relacione o ambiente à estrutura: pele permeável, excreção por ácido úrico, ovos com casca e outras.',
  'Para revisar: poríferos e cnidários são os animais mais simples; platelmintos e nematelmintos incluem muitos parasitas; artrópodes têm exoesqueleto e são o maior grupo; vertebrados se dividem em peixes, anfíbios, répteis, aves e mamíferos; aves e mamíferos são endotérmicos; anfíbios dependem da água na reprodução e répteis, não; e a metamorfose pode ser completa ou incompleta. Com isso, você fecha a parte de diversidade de seres vivos e passa ao último tema da matéria, saúde, saneamento e doenças não transmissíveis.'] }
]},
{ t:'Saúde, saneamento e doenças não transmissíveis', txt:[
 { h:'Conceito de saúde, determinantes sociais e saúde pública', p:[
  'A **Organização Mundial da Saúde** define saúde como um estado de completo bem-estar físico, mental e social, e não apenas a ausência de doença. Essa visão ampliada mostra que a saúde depende não só de fatores biológicos, mas também de **determinantes sociais**: renda, moradia, educação, alimentação, trabalho, saneamento, acesso aos serviços de saúde e ambiente. Por isso, as condições de vida de uma população influenciam diretamente seus indicadores. Dois indivíduos com o mesmo agente infeccioso podem ter desfechos muito diferentes, conforme o acesso à água limpa, à nutrição e ao tratamento.',
  'A **saúde pública** busca prevenir doenças, promover a saúde e prolongar a vida pela ação organizada da sociedade. No Brasil, o **Sistema Único de Saúde** (SUS), criado pela Constituição de 1988, garante o acesso universal, integral e gratuito a ações e serviços de saúde, que incluem a atenção básica, as vacinas, a vigilância sanitária e epidemiológica, os transplantes e os tratamentos de alta complexidade. A prevenção é, em geral, mais barata e eficaz do que o tratamento, e envolve campanhas de vacinação, orientação, saneamento e vigilância das condições de trabalho e de consumo.',
  'Os **indicadores de saúde** ajudam a avaliar a situação de uma população: a **taxa de mortalidade infantil** (óbitos de menores de 1 ano a cada mil nascidos vivos), a **expectativa de vida** ao nascer, a taxa de natalidade e a cobertura vacinal e de saneamento. A queda da mortalidade infantil no Brasil nas últimas décadas se deve à vacinação, ao pré-natal, ao aleitamento materno, à reidratação oral e à ampliação do saneamento. Esses indicadores são usados em questões do ENEM para analisar gráficos e relacioná-los às políticas públicas.'] },
 { h:'Saneamento básico e doenças de veiculação hídrica', p:[
  'O **saneamento básico** reúne quatro serviços: o **abastecimento de água potável**, o **esgotamento sanitário** (coleta e tratamento de esgoto), a **limpeza urbana e o manejo de resíduos sólidos** e a **drenagem das águas da chuva**. É uma das medidas mais eficientes para melhorar a saúde de uma população, pois evita doenças infecciosas e parasitárias. Estima-se que cada real investido em saneamento economiza vários reais em gastos com saúde. No Brasil, porém, parte da população ainda não tem coleta e tratamento de esgoto e, em alguns locais, acesso a água tratada, o que atinge principalmente as regiões mais pobres.',
  'Muitas doenças estão ligadas à falta de saneamento, como as **doenças de veiculação hídrica**, transmitidas pela água contaminada por fezes: cólera, febre tifoide, hepatite A, poliomielite, diarreias infecciosas, giardíase, amebíase e muitas verminoses. A **leptospirose** está associada às enchentes e ao contato com água contaminada por urina de ratos. A **dengue**, a zika e a chikungunya se relacionam à água parada e ao acúmulo de lixo, que favorecem a proliferação do mosquito. A **esquistossomose** depende do contato com água contaminada com os caramujos hospedeiros. A educação em saúde reforça o papel de cada pessoa.',
  'O **tratamento da água** para consumo envolve etapas: captação, coagulação e floculação (com sulfato de alumínio), decantação, filtração e desinfecção com cloro, além da correção do pH e da adição de flúor para prevenção de cáries. O **tratamento de esgoto** inclui fases mecânicas (remoção de sólidos), biológicas (degradação da matéria orgânica por microrganismos) e, às vezes, químicas. Em locais sem rede, as **fossas sépticas** são uma alternativa. O destino correto do lixo, em aterros sanitários, a coleta seletiva, a compostagem e a drenagem urbana completam as ações de saneamento e previnem enchentes e doenças.'] },
 { h:'Doenças não transmissíveis: doenças cardiovasculares, diabetes e câncer', p:[
  'As **doenças crônicas não transmissíveis** (DCNT) não são causadas por agentes infecciosos e não passam de uma pessoa a outra. São de **longa duração**, de desenvolvimento lento e multifatorial, e hoje são a principal causa de morte no mundo e no Brasil. As mais importantes são as **doenças cardiovasculares** (hipertensão, infarto, AVC), o **diabetes**, o **câncer** e as **doenças respiratórias crônicas**. Os principais fatores de risco são o **tabagismo**, o consumo abusivo de **álcool**, a **alimentação inadequada**, o **sedentarismo**, o excesso de peso e o estresse, além da genética e da idade.',
  'No **diabetes mellitus**, o corpo não produz insulina suficiente (tipo 1) ou não responde adequadamente a ela (tipo 2, o mais comum e ligado ao excesso de peso e ao sedentarismo), e a glicose permanece alta no sangue. A longo prazo, causa lesões em olhos, rins, nervos e vasos. O controle exige alimentação equilibrada, atividade física, monitoramento da glicemia e, quando necessário, medicamentos ou insulina. O **câncer** resulta da multiplicação descontrolada de células alteradas por mutações e se relaciona a fatores como tabaco, radiação, alimentos ultraprocessados, infecções (HPV, hepatite B) e exposição a substâncias cancerígenas.',
  'A **obesidade** é o acúmulo excessivo de gordura que prejudica a saúde, e vem crescendo em todo o mundo, acompanhando o consumo de alimentos ultraprocessados e a redução da atividade física. É fator de risco para diabetes, hipertensão e doenças cardíacas. A **hipertensão** é silenciosa, e seu controle, com redução do sal, exercício e medicação, evita complicações. Muitas dessas doenças são **evitáveis**: estima-se que a maioria dos casos de doenças cardíacas, diabetes tipo 2 e vários tipos de câncer poderia ser prevenida com hábitos saudáveis e políticas públicas.'] },
 { h:'Prevenção, hábitos saudáveis, drogas e saúde mental', p:[
  'A promoção da saúde envolve **hábitos de vida**: alimentação variada, rica em frutas, legumes e fibras e com pouco sal, açúcar e gorduras; **atividade física** regular (pelo menos 150 minutos por semana para adultos); sono adequado; controle do estresse; não fumar; consumo moderado ou nulo de álcool; higiene pessoal; e acompanhamento médico, com exames preventivos, como a mamografia, o exame preventivo de colo do útero (Papanicolau) e a medição da pressão e da glicemia. A detecção precoce de doenças, como o câncer, aumenta muito as chances de cura.',
  'As **drogas**, lícitas ou ilícitas, trazem riscos à saúde individual e coletiva. O **tabaco** é responsável por muitas mortes por câncer, doenças cardiovasculares e respiratórias, e o fumo passivo também prejudica. O **álcool** causa dependência, doenças hepáticas e acidentes de trânsito, e o uso durante a gravidez pode levar à síndrome alcoólica fetal. As **drogas ilícitas** (cocaína, crack, maconha, entre outras) afetam o sistema nervoso e podem levar à dependência química, uma doença que exige tratamento, e não apenas "força de vontade". A prevenção envolve educação, apoio familiar e políticas públicas.',
  'A **saúde mental** também é parte da saúde. Transtornos como a depressão, a ansiedade e o estresse crônico afetam milhões de pessoas e se relacionam a fatores biológicos, psicológicos e sociais. O cuidado inclui psicoterapia, medicamentos quando indicados, apoio social e hábitos saudáveis, e a redução do estigma, que impede muitas pessoas de procurar ajuda. A **medicina preventiva**, as vacinas, o saneamento e a educação em saúde compõem o conjunto de ações que melhoram a qualidade e a expectativa de vida, em uma perspectiva que o ENEM valoriza.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Saúde, saneamento e doenças não transmissíveis são temas muito presentes no ENEM, e conectam a Biologia à vida real. As questões apresentam gráficos de mortalidade, de incidência de doenças ou de acesso a saneamento, e pedem que se relacione os dados com políticas públicas, hábitos de vida ou condições socioeconômicas. Outras tratam de campanhas de vacinação, de tratamento da água e do esgoto, de doenças como a dengue, a leptospirose e o diabetes, e do impacto do tabagismo e do sedentarismo.',
  'Estratégia de resolução: identifique se a doença é **infecciosa** (agente, transmissão e prevenção por saneamento, vacinas e controle de vetores) ou **crônica não transmissível** (fatores de risco e prevenção por hábitos de vida e acesso à saúde). Ao analisar um gráfico, observe as tendências e relacione-as à causa mais plausível, como a queda da mortalidade infantil com o aumento do saneamento e da vacinação. Prefira, nas respostas, as medidas que atacam as causas e que são de caráter coletivo, e não apenas as individuais.',
  'Para revisar, monte um quadro com três colunas: tipo de problema (doenças infecciosas, carências, doenças crônicas), exemplos e prevenção. E pratique relacionar saúde e condições de vida: saneamento reduz doenças de veiculação hídrica; vacinas reduzem doenças infecciosas; alimentação e atividade física reduzem doenças crônicas; e o SUS garante o acesso. Esse tema reúne vários dos anteriores, como o sistema imunológico, as doenças causadas por microrganismos, os sistemas do corpo humano e os impactos ambientais, e funciona como uma boa revisão final de Biologia.'] }
]}
];
