/* Biologia: textos corridos, temas 13 a 15 */
module.exports = [
{ t:'Ciclos biogeoquímicos', txt:[
 { h:'O que são ciclos biogeoquímicos e por que são importantes', p:[
  'Enquanto a energia flui em sentido único pelos ecossistemas, a **matéria circula**. Os elementos químicos que formam os seres vivos, como carbono, nitrogênio, oxigênio, hidrogênio, fósforo e enxofre, passam repetidamente entre o ambiente e os organismos, em ciclos chamados de **ciclos biogeoquímicos**. O nome indica que envolvem fatores biológicos (bio), geológicos (geo) e químicos (químicos). Sem esses ciclos, os nutrientes se esgotariam e a vida cessaria, pois a quantidade de matéria disponível na Terra é praticamente constante.',
  'Em todos os ciclos, há **reservatórios**, onde o elemento fica estocado por longos períodos (atmosfera, oceanos, rochas, solo, combustíveis fósseis), e **fluxos**, que transferem o elemento entre eles. Os seres vivos participam como **produtores**, que absorvem formas inorgânicas e as incorporam à matéria orgânica, **consumidores**, que a transferem pela cadeia alimentar, e **decompositores**, que a devolvem ao ambiente. As atividades humanas, como a queima de combustíveis, o uso de fertilizantes e o desmatamento, alteram esses ciclos e podem causar desequilíbrios.',
  'Os ciclos podem ser **gasosos**, quando o principal reservatório é a atmosfera (carbono, nitrogênio e oxigênio), ou **sedimentares**, quando o reservatório é a crosta terrestre e a circulação é mais lenta (fósforo e enxofre, em parte). Os ciclos gasosos tendem a ser mais rápidos e globais. O estudo desses ciclos conecta a Biologia a outras áreas, como a Química (as reações envolvidas), a Geografia (o clima, os oceanos) e as questões ambientais (efeito estufa, chuva ácida, eutrofização).'] },
 { h:'Ciclo do carbono', p:[
  'O **carbono** é o elemento básico das moléculas orgânicas. Seu principal reservatório rápido é a atmosfera, na forma de **CO2**, mas ele também está dissolvido nos oceanos, nos combustíveis fósseis (carvão, petróleo, gás natural), nas rochas calcárias e na biomassa. Na **fotossíntese**, os produtores absorvem o CO2 e o incorporam à matéria orgânica. Na **respiração**, dos produtores, consumidores e decompositores, o carbono volta à atmosfera como CO2. A **decomposição** da matéria morta também libera carbono, na forma de CO2 (em ambientes com oxigênio) ou de CH4 (em ambientes sem oxigênio, como pântanos).',
  'A **combustão** de madeira, de carvão e de derivados do petróleo libera CO2, e as **queimadas** e o **desmatamento** reduzem a captura do gás e liberam o carbono estocado. Os **oceanos** absorvem grande parte do CO2 atmosférico, que se dissolve e forma ácido carbônico. A partir da Revolução Industrial, a queima de combustíveis fósseis, que armazenam carbono por milhões de anos, injetou na atmosfera quantidades de CO2 muito maiores que as que a natureza consegue reabsorver, aumentando o efeito estufa e causando o aquecimento global.',
  'Daí a importância dos **sumidouros de carbono**, como florestas, solos e oceanos, e das propostas de mitigação: reduzir as emissões, substituir combustíveis fósseis por fontes renováveis, preservar florestas, reflorestar e usar técnicas agrícolas que mantenham o carbono no solo. O **crédito de carbono** é um mecanismo em que quem reduz suas emissões pode vender o direito a emitir a quem não consegue reduzir. Os **biocombustíveis**, como o etanol, devolvem à atmosfera o CO2 que a planta absorveu durante o crescimento, o que reduz, em parte, o saldo de emissões.'] },
 { h:'Ciclo do nitrogênio', p:[
  'O **nitrogênio** é essencial para a formação de proteínas e de ácidos nucleicos. O principal reservatório é a atmosfera, em que o gás **N2** forma cerca de 78% do ar, mas a maioria dos seres vivos **não consegue utilizá-lo diretamente**, pois a ligação tripla entre os átomos é muito estável. É preciso que ele seja transformado em compostos assimiláveis, como amônia, nitrito e nitrato, por organismos especializados. Esse é um ponto central: sem as bactérias, o nitrogênio do ar permaneceria indisponível para as plantas e, por consequência, para os animais.',
  'O ciclo tem etapas realizadas por microrganismos. Na **fixação**, bactérias como as do gênero Rhizobium, que vivem em nódulos nas raízes de leguminosas (feijão, soja, ervilha), e cianobactérias convertem N2 em amônia (NH3), em uma associação **mutualística** com as plantas. Na **amonificação**, os decompositores transformam as proteínas e outros compostos nitrogenados de organismos mortos em amônia. Na **nitrificação**, bactérias quimiossintetizantes (Nitrosomonas e Nitrobacter) oxidam a amônia a nitrito e, depois, a **nitrato** (NO3-), forma mais absorvida pelas plantas.',
  'Na **desnitrificação**, outras bactérias convertem o nitrato em N2, que volta à atmosfera, fechando o ciclo. As plantas absorvem o nitrato pelas raízes e o usam para produzir proteínas; os animais obtêm o nitrogênio ao se alimentar de plantas ou de outros animais. A **rotação de culturas** com leguminosas e o **adubo verde** aproveitam a fixação biológica para enriquecer o solo, reduzindo a necessidade de fertilizantes químicos. Já o excesso de fertilizantes nitrogenados escoa para rios e lagos e provoca a **eutrofização**, com proliferação de algas e queda de oxigênio na água.'] },
 { h:'Ciclos da água, do oxigênio e do fósforo', p:[
  'O **ciclo da água** (ou hidrológico) movimenta a água entre oceanos, atmosfera, continentes e seres vivos. A energia do Sol provoca a **evaporação** da água dos oceanos, rios e lagos, e a **transpiração** das plantas e dos animais. O vapor sobe, **condensa-se** e forma nuvens, e retorna à superfície como **precipitação** (chuva, neve, granizo). Parte da água escorre pela superfície, formando rios, e parte se **infiltra** no solo, abastecendo os lençóis freáticos. As florestas influenciam esse ciclo, pois as árvores liberam grande quantidade de vapor, e o desmatamento pode alterar o regime de chuvas.',
  'O **ciclo do oxigênio** está muito ligado ao do carbono. O O2 é produzido na **fotossíntese**, a partir da água, e é consumido na **respiração** e na **combustão**. A camada de ozônio (O3) na estratosfera protege a vida da radiação ultravioleta. A maior parte do oxigênio atmosférico (cerca de 21%) tem origem biológica, resultado de bilhões de anos de fotossíntese realizada por cianobactérias e algas, e é essa presença que permitiu a evolução de organismos aeróbios, de maior rendimento energético.',
  'O **ciclo do fósforo** é **sedimentar**: não há fase gasosa significativa. O fósforo é componente do DNA, do RNA, do ATP, das membranas e dos ossos e dentes. Ele está nas **rochas**, que, pelo intemperismo e erosão, liberam fosfatos para o solo e a água. As plantas os absorvem, os animais os obtêm pela alimentação, e os decompositores os devolvem ao solo. Como o fósforo é, muitas vezes, o nutriente limitante, os fertilizantes fosfatados são usados na agricultura. O excesso, porém, também contribui para a eutrofização de lagos e represas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Os ciclos biogeoquímicos aparecem no ENEM pelos seus impactos: efeito estufa e aquecimento global (carbono), fertilizantes, eutrofização e fixação biológica (nitrogênio e fósforo), desmatamento e regime de chuvas (água), e crédito de carbono. As questões costumam trazer um esquema do ciclo, com setas e lacunas, pedindo para identificar o processo (fotossíntese, respiração, decomposição, combustão, fixação, nitrificação) ou para avaliar o efeito de uma atividade humana.',
  'Alguns pontos devem ser memorizados: o nitrogênio do ar só é aproveitado após a fixação por bactérias; as leguminosas são usadas para enriquecer o solo; a nitrificação transforma a amônia em nitrato; a desnitrificação devolve N2 à atmosfera; a queima de combustíveis fósseis e o desmatamento aumentam o CO2; a fotossíntese remove o CO2 e a respiração e a decomposição o devolvem; e o fósforo vem das rochas. Para os esquemas, atente para o que é entrada e o que é saída em cada reservatório.',
  'Para revisar, faça um quadro com cada ciclo: reservatório principal, processos que removem e que devolvem o elemento, organismos envolvidos e principal impacto humano. Por exemplo, no carbono, o reservatório é a atmosfera (CO2), os processos são a fotossíntese e a respiração, e o impacto é o aquecimento global. Esse quadro serve como resumo e, ao mesmo tempo, como treino para ligar causas e consequências, habilidade importante em Ecologia. A seguir, estudaremos os biomas brasileiros e os impactos ambientais.'] }
]},
{ t:'Biomas brasileiros', txt:[
 { h:'O que é um bioma e os fatores que o determinam', p:[
  'Um **bioma** é um grande conjunto de ecossistemas terrestres, com clima, solo, vegetação e fauna característicos, em que predomina um tipo de vegetação. Os biomas são determinados principalmente pelo **clima** (temperatura e chuvas), mas também pelo solo, pelo relevo e pela altitude. O Brasil é um dos países de maior **biodiversidade** do planeta, e possui seis biomas continentais, segundo o IBGE: **Amazônia, Cerrado, Mata Atlântica, Caatinga, Pampa e Pantanal**. Há ainda os ecossistemas costeiros e marinhos, como os manguezais e os recifes de coral.',
  'A distribuição dos biomas no território reflete a variação de clima e de solo. A Amazônia, no Norte, tem clima equatorial, quente e úmido. A Caatinga, no sertão nordestino, tem clima semiárido. O Cerrado ocupa o Brasil Central, com estações bem definidas, chuvas concentradas no verão e seca no inverno. A Mata Atlântica se estende por toda a faixa litorânea, da região Nordeste ao Sul. O Pampa ocupa o sul do Rio Grande do Sul, e o Pantanal fica na planície do Mato Grosso e do Mato Grosso do Sul.',
  'A **biodiversidade** é a variedade de seres vivos, de genes e de ecossistemas, e é importante pelos serviços ecossistêmicos que presta: regulação do clima, ciclagem de nutrientes, polinização, controle de pragas, produção de água e recursos genéticos, medicinais e alimentícios. Os **hotspots** são regiões de grande biodiversidade, com muitas espécies endêmicas, que perderam boa parte da vegetação original. O Cerrado e a Mata Atlântica são considerados hotspots mundiais, o que reforça a necessidade de conservação e de políticas públicas.'] },
 { h:'Amazônia e Mata Atlântica', p:[
  'A **Amazônia** é a maior floresta tropical do mundo e ocupa quase metade do território brasileiro. O clima é quente e úmido, com chuvas abundantes ao longo do ano. A vegetação é de floresta **densa**, com árvores de grande porte e vários estratos, e a maior biodiversidade do planeta. Os solos, em geral, são **pobres em nutrientes**, pois a riqueza está na própria biomassa: os nutrientes são rapidamente reciclados pela decomposição da serapilheira. Por isso, quando a floresta é derrubada, o solo se esgota em poucos anos. A região também tem a maior bacia hidrográfica do mundo.',
  'A floresta amazônica tem papel no **equilíbrio climático**: regula o regime de chuvas, por meio da evapotranspiração, que forma os "rios voadores" que levam umidade a outras regiões do Brasil, e armazena grande quantidade de carbono. As principais ameaças são o **desmatamento** (para pecuária, agricultura e extração de madeira), as queimadas, o garimpo ilegal, que contamina rios com mercúrio, e a abertura de estradas e hidrelétricas. Povos indígenas e comunidades tradicionais vivem na região e são importantes na preservação, e as terras indígenas são barreiras ao avanço do desmatamento.',
  'A **Mata Atlântica** é uma floresta tropical úmida que originalmente cobria a faixa litorânea e parte do interior do país, onde hoje vive a maior parte da população brasileira. Restam cerca de 12% da cobertura original, resultado da exploração do pau-brasil, dos ciclos do café e da cana-de-açúcar e da urbanização. Mesmo assim, abriga enorme biodiversidade e muitas espécies **endêmicas**, como o mico-leão-dourado. É essencial para o abastecimento de água de grandes cidades, e a legislação específica protege seus remanescentes, que ainda sofrem pressões do desmatamento e da fragmentação.'] },
 { h:'Cerrado, Caatinga, Pampa e Pantanal', p:[
  'O **Cerrado** é a savana brasileira, e o segundo maior bioma do país. Tem duas estações bem marcadas, e a vegetação é composta por árvores de troncos retorcidos, com casca grossa e raízes profundas, e por um estrato de gramíneas. Essas adaptações permitem sobreviver à seca e ao fogo, que é um fator natural do bioma. Os solos são ácidos e pobres, mas foram corrigidos com calcário e adubos, e o bioma se tornou uma das principais fronteiras agrícolas, produzindo soja, milho e gado. É chamado de "berço das águas", pois nele nascem rios de grandes bacias hidrográficas. Cerca da metade da vegetação nativa já foi convertida.',
  'A **Caatinga** é o único bioma exclusivamente brasileiro e predomina no semiárido do Nordeste. O clima é quente e seco, com chuvas irregulares, e a vegetação é composta por plantas **xerófitas**, adaptadas à seca: cactos que armazenam água, plantas com folhas pequenas ou espinhos, que reduzem a perda de água, e árvores que perdem as folhas na estiagem. Muitas espécies são endêmicas. A região sofre com o desmatamento para lenha e agricultura e com a desertificação, e as populações precisam de tecnologias de convivência com o semiárido, como cisternas para captar água da chuva.',
  'O **Pampa**, ou campos sulinos, é caracterizado por paisagens abertas, com predomínio de gramíneas e poucas árvores, em clima subtropical com chuvas distribuídas ao longo do ano e invernos frios. É usado há séculos para a pecuária e, mais recentemente, para as lavouras de soja e de arroz e para a silvicultura, que ameaçam a vegetação nativa. O **Pantanal** é a maior planície alagável do mundo, com ciclo marcado por cheias e secas. Abriga enorme concentração de fauna, como jacarés, capivaras, onças e aves, e é muito afetado por incêndios, pecuária e alterações nos rios que o abastecem.'] },
 { h:'Ecossistemas costeiros, conservação e unidades de conservação', p:[
  'Além dos biomas continentais, há ecossistemas costeiros importantes. O **manguezal** ocupa áreas de encontro entre rio e mar, com solo lodoso e salgado. Sua vegetação, com raízes aéreas que ajudam na respiração e na fixação, é adaptada à salinidade. É um **berçário** de muitas espécies marinhas, protege a costa da erosão e filtra poluentes. As **restingas** ocupam as areias do litoral, e os **recifes de coral** abrigam enorme diversidade marinha. Esses ambientes sofrem com a especulação imobiliária, com a poluição e com o aquecimento e a acidificação dos oceanos.',
  'A conservação da biodiversidade depende de várias estratégias. As **Unidades de Conservação** (UCs), criadas pelo poder público, são divididas em **proteção integral** (parques nacionais, reservas biológicas, estações ecológicas), em que só se permite o uso indireto dos recursos, e **uso sustentável** (áreas de proteção ambiental, reservas extrativistas, florestas nacionais), em que se compatibiliza a conservação com o uso por populações locais. O **Código Florestal** estabelece as **Áreas de Preservação Permanente** (APPs), como margens de rios e topos de morros, e a **Reserva Legal**, parcela de cada propriedade rural que deve ser mantida com vegetação nativa.',
  'Outras medidas incluem a fiscalização contra o desmatamento e o tráfico de animais, a recuperação de áreas degradadas, os **corredores ecológicos**, que conectam fragmentos de vegetação e permitem o fluxo de animais e de genes, o pagamento por serviços ambientais e a educação ambiental. O uso sustentável de produtos da floresta, como a castanha, o açaí e a borracha, associa a renda das populações locais à conservação. É importante ressaltar que preservar não significa isolar a natureza das pessoas, mas encontrar formas de usar os recursos sem comprometer sua renovação.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Os biomas aparecem no ENEM em questões interdisciplinares com Geografia: características de cada bioma, adaptações de plantas e animais ao clima, impactos de atividades econômicas e políticas de conservação. É comum o enunciado descrever uma paisagem, ou uma adaptação (folhas pequenas, raízes profundas, casca grossa, raízes aéreas), e pedir a identificação do bioma. Outro formato é a análise de dados de desmatamento ou de mapa de cobertura vegetal.',
  'Associações para memorizar: Amazônia, floresta densa e úmida, biodiversidade máxima, solo pobre; Cerrado, árvores de troncos retorcidos, fogo, berço das águas; Caatinga, xerófitas, semiárido, exclusivo do Brasil; Mata Atlântica, litoral, poucos remanescentes, hotspot; Pampa, gramíneas e pecuária; Pantanal, planície alagável; manguezal, berçário marinho. Atenção às adaptações: cada característica da planta tem relação com o fator limitante do ambiente (água, fogo, nutrientes, salinidade).',
  'Para revisar, construa um quadro com cinco colunas: bioma, clima, vegetação, ameaças e proteção. E associe cada um a uma questão que já viu. Os conhecimentos de biomas ajudam a entender as questões de impactos ambientais e sustentabilidade, o tema seguinte, em que se discutem desmatamento, poluição, mudanças climáticas, uso da água e do solo, e as soluções para conciliar desenvolvimento e conservação.'] }
]},
{ t:'Impactos ambientais e sustentabilidade', txt:[
 { h:'Desmatamento, queimadas e perda de biodiversidade', p:[
  'Os **impactos ambientais** são as alterações no ambiente causadas por atividades humanas. O **desmatamento** é um dos mais sérios: a retirada da vegetação para pecuária, agricultura, mineração, madeira e urbanização leva à perda de habitat, ao empobrecimento do solo, ao assoreamento dos rios, à alteração do regime de chuvas e à emissão de CO2, que contribui para o aquecimento global. As **queimadas**, usadas para "limpar" terrenos, liberam fumaça, gases e partículas, prejudicam a saúde respiratória das populações e destroem a fauna e a flora.',
  'A **perda de biodiversidade** é consequência direta da destruição de habitats, mas também resulta da **caça e pesca predatórias**, do **tráfico de animais silvestres**, da **introdução de espécies invasoras**, da poluição e das mudanças climáticas. A **fragmentação de habitats**, em que áreas contínuas de vegetação se dividem em pedaços isolados, reduz o tamanho das populações, dificulta o fluxo gênico e aumenta o risco de extinção. Espécies de grande porte, de reprodução lenta ou com áreas de vida extensas são as mais vulneráveis.',
  'A perda de espécies não é apenas um problema ético: a biodiversidade fornece **serviços essenciais** à humanidade, como polinização das lavouras, controle natural de pragas, regulação do clima e da água, e matéria-prima para medicamentos, alimentos e fibras. Muitas espécies ainda não foram descritas pela ciência e podem ter potencial farmacêutico ou agrícola. As **listas de espécies ameaçadas**, como as do ICMBio e da IUCN, ajudam a definir prioridades de conservação, e a legislação ambiental brasileira prevê sanções para quem causa dano à fauna e à flora.'] },
 { h:'Poluição do ar, da água e do solo', p:[
  'A **poluição do ar** é causada principalmente pela queima de combustíveis fósseis em veículos e indústrias, e pelas queimadas. Os poluentes incluem o CO, os óxidos de enxofre e de nitrogênio, o material particulado e os compostos orgânicos voláteis. Eles provocam problemas respiratórios e cardiovasculares, **chuva ácida**, **smog** e a formação de **ozônio troposférico**. Em dias frios e secos, a **inversão térmica** impede a dispersão dos poluentes em grandes cidades. O **efeito estufa** intensificado, por sua vez, resulta do aumento do CO2, do metano e de outros gases.',
  'A **poluição da água** decorre do despejo de esgotos domésticos e industriais sem tratamento, do escoamento de fertilizantes e agrotóxicos, de resíduos sólidos e de derramamentos de petróleo. Provoca a **eutrofização**, a contaminação por metais pesados e por microrganismos patogênicos, a mortandade de peixes e a escassez de água potável. As doenças de **veiculação hídrica**, como cólera, hepatite A, leptospirose e esquistossomose, estão ligadas à falta de saneamento básico, e a universalização do saneamento é uma das principais medidas de saúde pública.',
  'A **poluição do solo** vem do descarte inadequado de lixo, de resíduos industriais, de pilhas e baterias, de agrotóxicos e de vazamentos. Os **lixões** a céu aberto produzem chorume, que contamina o solo e os lençóis freáticos. A **erosão**, a **compactação** e a **salinização** degradam o solo agrícola, e a **desertificação** transforma áreas produtivas em terras áridas. Para reduzir esses problemas, usam-se o **plantio direto**, as **curvas de nível**, a rotação de culturas e a recomposição da vegetação nas margens dos rios, que protegem o solo e a água.'] },
 { h:'Mudanças climáticas, resíduos sólidos e consumo', p:[
  'As **mudanças climáticas** são alterações de longo prazo no clima da Terra, que hoje se atribuem principalmente ao aumento dos gases de efeito estufa pela ação humana. Entre as consequências, estão a elevação da temperatura média, o derretimento de geleiras e calotas polares, a elevação do nível do mar, o aumento de eventos extremos (secas, enchentes, ondas de calor, furacões), a acidificação dos oceanos e as mudanças na distribuição de espécies e de doenças. Os países mais pobres e as populações vulneráveis tendem a sofrer mais, o que traz a discussão sobre justiça climática.',
  'Os **resíduos sólidos** são um desafio crescente com o aumento do consumo. A **Política Nacional de Resíduos Sólidos** (Lei 12.305/2010) estabelece a ordem de prioridade: **não gerar, reduzir, reutilizar, reciclar, tratar e, por último, dispor de forma adequada em aterros sanitários**. Prevê também a **logística reversa**, em que fabricantes e comerciantes devem recolher produtos como pilhas, pneus, lâmpadas e eletrônicos, após o consumo. A **coleta seletiva** e a **compostagem** reduzem o volume enviado aos aterros e reaproveitam materiais e nutrientes.',
  'O **consumo consciente** é peça central. A pegada ecológica mede a área de terra e de água necessária para sustentar o consumo de uma pessoa ou população e absorver seus resíduos. Hoje, a humanidade usa mais recursos do que a Terra consegue regenerar. Os 3 Rs (reduzir, reutilizar e reciclar) e, mais recentemente, a ideia de **economia circular**, em que os produtos são projetados para durar, ser consertados e reaproveitados, buscam romper o modelo linear de "extrair, produzir, consumir e descartar".'] },
 { h:'Desenvolvimento sustentável e soluções', p:[
  'O **desenvolvimento sustentável** é aquele que atende às necessidades do presente sem comprometer a capacidade das gerações futuras de atender às suas. O conceito foi popularizado pelo Relatório Brundtland (1987) e reforçado nas conferências internacionais, como a Rio-92 e os acordos climáticos, como o Acordo de Paris (2015), cuja meta é limitar o aquecimento global bem abaixo de 2 °C. A sustentabilidade tem três dimensões, que se complementam: a **ambiental**, a **social** (justiça, qualidade de vida, equidade) e a **econômica** (viabilidade e geração de renda).',
  'Entre as soluções, destaca-se a **transição energética**, com a substituição de combustíveis fósseis por fontes **renováveis**: solar, eólica, hidrelétrica, biomassa e biocombustíveis. Cada fonte tem vantagens e limitações: a solar e a eólica são limpas, mas intermitentes; a hidrelétrica é renovável, mas alaga grandes áreas e altera ecossistemas e comunidades; a nuclear não emite CO2, mas gera rejeitos radioativos; os biocombustíveis podem competir com a produção de alimentos e exigir terras. O ENEM costuma avaliar essas relações de custo e benefício.',
  'Outras estratégias incluem a **agricultura sustentável**, com manejo integrado de pragas, agroecologia, sistemas agroflorestais e menor uso de insumos químicos; a **conservação da água**, com reúso, captação da chuva e combate a desperdícios; as **cidades sustentáveis**, com transporte coletivo, áreas verdes e saneamento; a **educação ambiental**, que forma cidadãos críticos; e a **legislação e a fiscalização ambiental**. O sucesso dessas medidas depende da participação conjunta de governos, empresas e cidadãos, e do equilíbrio entre os interesses econômicos e a proteção da natureza.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Impactos ambientais e sustentabilidade são temas muito cobrados, em questões que unem Biologia, Química, Geografia e Sociologia. O ENEM apresenta um problema real, como o desmatamento, a poluição de um rio, o lixo plástico, o aquecimento global ou a escolha entre fontes de energia, e pede para identificar a causa, os efeitos ou a proposta de intervenção mais adequada. Frequentemente, o texto fornece dados ou gráficos para interpretar, e as alternativas contêm soluções com diferentes níveis de viabilidade.',
  'Estratégias de resolução: 1) identifique o problema central e o ambiente afetado; 2) relacione-o com os conceitos estudados (ciclos, cadeias alimentares, eutrofização, bioacumulação, efeito estufa); 3) avalie as soluções propostas, escolhendo as que atacam a causa e que são viáveis e abrangentes; 4) desconfie de respostas simplistas, como "basta" uma ação para resolver tudo. Valorize as soluções que combinam medidas técnicas, educação e políticas públicas, pois são as mais coerentes com a sustentabilidade.',
  'Para revisar: desmatamento reduz biodiversidade e altera o clima; poluição do ar causa chuva ácida e aquecimento; poluição da água causa eutrofização e doenças; resíduos exigem coleta seletiva, reciclagem e logística reversa; o desenvolvimento sustentável equilibra o ambiental, o social e o econômico; as energias renováveis ajudam, mas cada uma tem limitações. Esse tema também alimenta a redação, que costuma exigir propostas de intervenção, por isso vale guardar exemplos e dados que possam servir de argumento.'] }
]}
];
