/* Biologia: textos corridos, temas 4 a 6 */
module.exports = [
{ t:'Metabolismo energético', txt:[
 { h:'ATP, a moeda de energia da célula', p:[
  'As células precisam de energia o tempo todo: para se mover, transportar substâncias, sintetizar moléculas e se dividir. Essa energia é fornecida por uma molécula chamada **ATP** (trifosfato de adenosina). O ATP é formado por uma base nitrogenada (adenina), um açúcar (ribose) e três grupos fosfato. A energia fica armazenada nas ligações entre os fosfatos, principalmente na última. Quando a célula precisa de energia, ela quebra essa ligação, liberando o fosfato e formando o **ADP** (difosfato de adenosina).',
  'Por funcionar como um "dinheiro" universal, o ATP é produzido em locais de grande oferta de energia e gasto onde há demanda. O ciclo é contínuo: a energia dos alimentos é usada para reunir ADP e fosfato novamente em ATP (processo chamado de fosforilação), e o ATP é desfeito sempre que a célula realiza trabalho. Um ser humano adulto, em um dia, recicla uma quantidade de ATP próxima à de sua própria massa corporal, o que mostra o quanto esse sistema é dinâmico, já que o corpo contém apenas pequenas reservas dele.',
  'Os seres vivos obtêm a energia por duas estratégias principais. Os **autótrofos** produzem seu próprio alimento (matéria orgânica) a partir de substâncias inorgânicas: os **fotossintetizantes** usam a energia da luz e os **quimiossintetizantes** usam a energia de reações químicas. Já os **heterótrofos** dependem de matéria orgânica pronta, obtida pela alimentação. Em ambos os casos, a energia final fica armazenada no ATP, que sustenta o metabolismo celular, e a base da cadeia alimentar está nos autótrofos.'] },
 { h:'Fotossíntese: etapas e fatores', p:[
  'A **fotossíntese** é o processo pelo qual plantas, algas e algumas bactérias convertem energia luminosa em energia química, produzindo glicose e liberando oxigênio. Em geral, é resumida na equação 6 CO2 + 6 H2O → C6H12O6 + 6 O2, na presença de luz e clorofila. Nas plantas, ocorre nos **cloroplastos**, organelas que contêm a clorofila, pigmento verde que absorve luz principalmente nas faixas do vermelho e do azul, refletindo o verde, e daí a cor das folhas. É a base da quase totalidade das cadeias alimentares e da produção de oxigênio da atmosfera.',
  'O processo tem duas fases. Na **fase clara** (ou fotoquímica), que ocorre nas membranas dos tilacoides, a luz excita a clorofila, e a energia é usada para quebrar a água (fotólise), liberando **O2**, e para produzir **ATP** e **NADPH**. Na **fase escura** (ou ciclo de Calvin), que ocorre no estroma, o ATP e o NADPH produzidos na primeira fase são usados para fixar o **CO2** e formar glicose. A fase escura não precisa de luz diretamente, mas depende dos produtos da fase clara, e por isso também ocorre durante o dia.',
  'Vários fatores influenciam a taxa de fotossíntese: a **intensidade luminosa**, a **concentração de CO2** e a **temperatura**. Aumentar a luz ou o CO2 acelera o processo até um ponto de saturação, a partir do qual outro fator se torna limitante. A temperatura muito alta desnatura as enzimas e reduz a fotossíntese. O **ponto de compensação fótico** é a intensidade de luz em que a fotossíntese e a respiração se equivalem, e o saldo de O2 é zero; abaixo dele, a planta consome mais do que produz. Esses conceitos aparecem em gráficos e experimentos.'] },
 { h:'Respiração celular aeróbia', p:[
  'Na **respiração celular aeróbia**, a glicose é degradada na presença de oxigênio para liberar energia, usada para formar ATP. A equação geral é C6H12O6 + 6 O2 → 6 CO2 + 6 H2O + energia. É o inverso da fotossíntese em termos de substâncias, mas ocorre nas **mitocôndrias** e no citoplasma de praticamente todos os seres eucariontes, inclusive as plantas, que respiram durante o dia e a noite. A energia liberada é armazenada em ATP, com rendimento de cerca de 30 a 32 moléculas por glicose, e o restante se dissipa como calor.',
  'Ela ocorre em três etapas. A **glicólise**, no citosol, quebra a glicose (6 carbonos) em duas moléculas de piruvato (3 carbonos), com saldo de 2 ATP e formação de NADH, e não precisa de oxigênio. O **ciclo de Krebs**, na matriz mitocondrial, completa a oxidação do piruvato, liberando CO2 e formando mais NADH e FADH2, além de um pequeno número de ATP. Na **cadeia respiratória** (ou fosforilação oxidativa), nas cristas mitocondriais, os elétrons de NADH e FADH2 passam por uma série de proteínas, e a energia liberada é usada para sintetizar a maior parte do ATP. O oxigênio é o **aceptor final de elétrons**, formando água.',
  'É por isso que o oxigênio é indispensável aos organismos aeróbios: sem ele, a cadeia respiratória para e o rendimento energético cai drasticamente. O monóxido de carbono e o cianeto são tóxicos por interferirem na cadeia respiratória, e a falta de oxigênio faz as células recorrerem a processos menos eficientes. As mitocôndrias possuem membrana externa lisa e membrana interna dobrada em cristas, que aumentam a superfície para as reações. Tudo isso se relaciona à presença de muitas mitocôndrias em células de alta demanda energética.'] },
 { h:'Fermentação e quimiossíntese', p:[
  'Na ausência de oxigênio, a glicose pode ser degradada por **fermentação**, um processo anaeróbio, com baixo rendimento, de apenas 2 ATP por glicose, produzidos na glicólise. Na **fermentação alcoólica**, realizada por leveduras e algumas bactérias, o piruvato é convertido em etanol e CO2, e é usada na produção de pães, cervejas, vinhos e etanol combustível. O CO2 faz a massa do pão crescer, e o álcool evapora no cozimento. É um processo de grande importância econômica, com uso do Saccharomyces cerevisiae.',
  'Na **fermentação lática**, o piruvato é convertido em ácido lático, o que acontece em bactérias usadas na produção de iogurtes, queijos e coalhadas, e também nas **células musculares** humanas, quando o esforço é tão intenso que o oxigênio não é suficiente. O acúmulo de ácido lático contribui para a fadiga e a sensação de queimação, mas não é a causa da dor muscular tardia, como se acreditava. Quando o oxigênio volta a ser suficiente, o lactato é reconvertido em glicose, no fígado. A **fermentação acética** produz vinagre, e é realizada por bactérias a partir do etanol (em verdade, a etapa depende do oxigênio).',
  'A **quimiossíntese** é a produção de matéria orgânica pela energia liberada em reações de oxidação de substâncias inorgânicas, sem necessidade de luz. Bactérias quimiossintetizantes, como as que oxidam compostos de enxofre ou de nitrogênio (nitrificação), são fundamentais nos ciclos biogeoquímicos e sustentam ecossistemas em ambientes sem luz, como as fontes hidrotermais nas profundezas do oceano. Isso mostra que a vida pode se basear em outras fontes de energia além do Sol, e é uma referência importante nas discussões sobre a possibilidade de vida em outros planetas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O metabolismo energético é um dos temas favoritos do ENEM, por sua conexão com contextos práticos: produção de pães e bebidas, atividade física, fadiga muscular, ciclos de carbono e de oxigênio, aquecimento global, biocombustíveis e cultivo de plantas em ambiente fechado. As questões costumam fornecer gráficos de fotossíntese em função da luz ou do CO2, e pedir interpretação, ou descrever experimentos com leveduras e perguntar o que acontece com o CO2 liberado.',
  'Dicas: a fotossíntese e a respiração são processos complementares, mas ocorrem em organelas diferentes e plantas realizam os dois; o oxigênio liberado na fotossíntese vem da água, e não do CO2; a glicólise é comum a todos os processos e ocorre no citosol; o rendimento da fermentação é muito menor que o da respiração; e as plantas consomem parte da glicose que produzem. Em gráficos, identifique o fator limitante, que é aquele cuja variação altera a taxa, enquanto os outros estão em excesso.',
  'Revisão: ATP é a moeda de energia; a fotossíntese converte luz em glicose, com fases clara e escura; a respiração aeróbia tem glicólise, Krebs e cadeia respiratória, com rendimento de cerca de 30 ATP; a fermentação rende apenas 2 ATP e pode ser alcoólica, lática ou acética; a quimiossíntese usa reações químicas como fonte de energia. Relacione o tema com ecologia (cadeias alimentares e ciclo do carbono) e com a fisiologia do exercício.'] }
]},
{ t:'Ácidos nucleicos e síntese de proteínas', txt:[
 { h:'Estrutura do DNA e do RNA', p:[
  'Os **ácidos nucleicos**, DNA e RNA, são as moléculas que armazenam e expressam a informação genética. São polímeros formados por unidades chamadas **nucleotídeos**, cada um com três partes: um grupo **fosfato**, um açúcar (pentose) e uma **base nitrogenada**. No DNA, o açúcar é a **desoxirribose** e as bases são adenina (A), timina (T), citosina (C) e guanina (G). No RNA, o açúcar é a **ribose** e a timina é substituída pela **uracila** (U), de modo que as bases são A, U, C e G.',
  'O **DNA** tem a estrutura de uma **dupla hélice**, proposta por Watson e Crick em 1953, com base em dados de Rosalind Franklin e Maurice Wilkins. As duas fitas são antiparalelas e se mantêm unidas por **ligações de hidrogênio** entre as bases, que se emparelham de modo específico: A com T (duas ligações) e C com G (três ligações). Esse emparelhamento complementar tem como consequência que, em qualquer DNA, a quantidade de A é igual à de T e a de C é igual à de G, regra de Chargaff, que ajuda a resolver questões de cálculo de porcentagens.',
  'O **RNA** é, em geral, formado por uma única fita. Existem três tipos principais: o **RNA mensageiro** (RNAm), que leva a informação do DNA para os ribossomos; o **RNA transportador** (RNAt), que leva os aminoácidos até o ribossomo; e o **RNA ribossômico** (RNAr), que forma, com proteínas, os ribossomos. O DNA fica no núcleo (e nas mitocôndrias e cloroplastos), em células eucariontes, e é mais estável, enquanto o RNA é mais curto e menos duradouro, o que é adequado a seu papel de mensageiro temporário.'] },
 { h:'Duplicação do DNA e transcrição', p:[
  'Antes de uma célula se dividir, o DNA precisa ser copiado, em um processo chamado de **duplicação** ou replicação. Ela é **semiconservativa**: cada molécula-filha é formada por uma fita antiga, que serve de molde, e uma fita nova. Foi demonstrada por Meselson e Stahl, em 1958. O processo envolve a abertura da dupla hélice pela enzima helicase e a ação da **DNA polimerase**, que adiciona nucleotídeos complementares à fita molde. Assim, cada célula-filha recebe uma cópia idêntica do material genético.',
  'A **transcrição** é a síntese de uma molécula de RNA a partir de um trecho do DNA, o gene. A enzima **RNA polimerase** se liga ao DNA, abre a dupla hélice e produz uma fita de RNA complementar a uma das fitas do DNA, que atua como molde. Por exemplo, para o trecho TAC GGA do DNA, o RNAm terá AUG CCU. Em eucariontes, o RNA recém-formado passa por um processamento, no qual regiões não codificantes (íntrons) são removidas e as codificantes (éxons) são unidas, o que permite que um mesmo gene origine proteínas diferentes (splicing alternativo).',
  'Em seguida, o RNAm sai do núcleo para o citoplasma, onde se liga aos ribossomos. Em procariontes, como não há núcleo, a transcrição e a tradução ocorrem quase ao mesmo tempo. A informação genética flui, portanto, do **DNA para o RNA e do RNA para a proteína**, ideia conhecida como "dogma central da Biologia Molecular". Há exceções, como os retrovírus (por exemplo, o HIV), que transformam o RNA em DNA pela enzima transcriptase reversa, e que inspiraram técnicas de biotecnologia.'] },
 { h:'Código genético e tradução', p:[
  'O **código genético** é a correspondência entre as sequências de bases do RNAm e os aminoácidos das proteínas. Cada trinca de bases, o **códon**, codifica um aminoácido. Como existem 4 bases e os códons têm 3, há 64 combinações possíveis (4 × 4 × 4), para apenas 20 aminoácidos, o que mostra que o código é **degenerado** (ou redundante): um mesmo aminoácido pode ser codificado por mais de um códon. O códon AUG é o de **iniciação** (e codifica a metionina), e três códons (UAA, UAG e UGA) são de **terminação**, e não codificam aminoácidos.',
  'O código é **praticamente universal**, ou seja, é o mesmo em bactérias, plantas e animais, o que explica por que um gene humano, como o da insulina, pode ser expresso por uma bactéria na engenharia genética. A **tradução** é a síntese da proteína nos **ribossomos**. O RNAm se liga ao ribossomo, e os RNAt, cada um com um **anticódon** complementar ao códon, trazem os aminoácidos correspondentes, que são unidos por **ligações peptídicas**. A cadeia cresce até um códon de terminação, e o polipeptídio é liberado.',
  'As proteínas assim formadas dobram-se e assumem uma forma tridimensional específica, que determina sua função. Podem ser enzimas, hormônios, anticorpos, proteínas estruturais ou transportadoras. Como a sequência de aminoácidos depende da sequência do gene, qualquer alteração no DNA pode modificar a proteína. Assim, o genótipo (os genes) se expressa em um fenótipo (as características) por meio das proteínas, e entender essa ligação entre gene e característica é central para a Genética e para a Biotecnologia.'] },
 { h:'Mutações e suas consequências', p:[
  'As **mutações** são alterações na sequência do DNA. Podem ocorrer espontaneamente, por erros na duplicação, ou ser induzidas por **agentes mutagênicos**, como a radiação ultravioleta, os raios X, a radiação nuclear e substâncias químicas, como as presentes na fumaça do cigarro. As **mutações gênicas** (ou pontuais) afetam um ou poucos nucleotídeos. Nas substituições, uma base é trocada por outra, o que pode não alterar o aminoácido (mutação silenciosa, devido à degeneração do código), trocar um aminoácido (mutação de sentido trocado) ou criar um códon de parada.',
  'As **inserções** e **deleções** de bases são mais graves, pois deslocam a "fase de leitura" a partir do ponto da alteração, mudando todos os códons seguintes (**mutação por deslocamento do quadro**). As **mutações cromossômicas** modificam a estrutura ou o número dos cromossomos, como na síndrome de Down, em que há três cópias do cromossomo 21. As mutações que ocorrem em células somáticas afetam apenas o indivíduo, e podem levar ao câncer, enquanto as que ocorrem em células germinativas podem ser transmitidas à descendência.',
  'A maior parte das mutações é neutra ou prejudicial, mas algumas conferem uma vantagem em determinado ambiente. Elas são a **matéria-prima da evolução**, pois geram a variabilidade genética sobre a qual age a seleção natural. A anemia falciforme, causada por uma única troca de base no gene da hemoglobina, é um exemplo clássico: prejudica o portador de duas cópias, mas protege os portadores de uma cópia contra a malária. Esse equilíbrio mostra como a mesma mutação pode ter efeitos diferentes conforme o contexto e é um caso bastante explorado em provas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em questões de ácidos nucleicos, o ENEM costuma apresentar uma sequência de DNA e pedir o RNA correspondente, ou o aminoácido, usando uma tabela de códons fornecida. Também apresenta situações de mutação e pergunta qual seu efeito sobre a proteína, ou relaciona o DNA a testes de paternidade, à identificação de criminosos e à engenharia genética. Saber o caminho DNA → RNA → proteína e usar a complementaridade das bases com segurança resolve a maior parte dos casos.',
  'Cuidados: lembre que o RNA tem uracila no lugar da timina; que a tradução usa o RNAm, e não o DNA; que o códon do RNAm é complementar ao DNA molde, e o anticódon do RNAt é complementar ao códon; e que a degeneração do código explica por que algumas mutações não alteram a proteína. Em questões de porcentagem de bases, use a regra de Chargaff: A = T e C = G no DNA de fita dupla, mas não necessariamente no RNA de fita simples.',
  'Resumo para revisão: o DNA tem desoxirribose e bases A, T, C e G, em dupla hélice; o RNA tem ribose e uracila, e há três tipos; a duplicação é semiconservativa; a transcrição forma o RNAm; a tradução forma a proteína nos ribossomos; o código é degenerado e quase universal; as mutações são a fonte da variabilidade. Esse tema é a base para a divisão celular, para a genética e para a biotecnologia, que serão estudadas em seguida.'] }
]},
{ t:'Divisão celular', txt:[
 { h:'Ciclo celular e cromossomos', p:[
  'Para crescer, regenerar tecidos e se reproduzir, os organismos dependem da **divisão celular**. Antes de se dividir, a célula passa por um ciclo organizado de eventos, o **ciclo celular**, que tem duas grandes partes. A **interfase**, a fase mais longa, é o período em que a célula cresce e duplica seu DNA, e se divide em G1 (crescimento), S (síntese, quando o DNA é duplicado) e G2 (preparação para a divisão). Em seguida vem a **fase de divisão** propriamente dita, com a divisão do núcleo (mitose ou meiose) e do citoplasma (citocinese).',
  'Na interfase, o DNA está na forma de **cromatina**, que ao se condensar durante a divisão forma os **cromossomos**. Cada cromossomo, depois de duplicado, é formado por duas **cromátides-irmãs**, idênticas, ligadas por uma região chamada de **centrômero**. Os cromossomos **homólogos** são os que formam pares, um de origem materna e outro paterno, com os mesmos genes em posições equivalentes. As células **diploides** (2n) têm os dois conjuntos, e as **haploides** (n), como os gametas, têm apenas um.',
  'O ciclo celular é regulado por proteínas que verificam, em pontos de checagem, se o DNA está íntegro e se a célula está pronta para avançar. Quando o DNA sofre danos que não podem ser reparados, a célula pode entrar em morte programada, a **apoptose**, o que evita a multiplicação de células alteradas. No **câncer**, esse controle falha, por mutações em genes que estimulam ou que freiam a divisão, e as células se multiplicam sem limites, invadindo outros tecidos. Muitos tratamentos agem, por isso, sobre células em divisão rápida.'] },
 { h:'Mitose: etapas e função', p:[
  'A **mitose** é a divisão em que uma célula-mãe origina duas células-filhas **geneticamente idênticas** a ela e com o mesmo número de cromossomos. Ocorre em células somáticas e é responsável pelo crescimento, pela renovação e reparação de tecidos (como na cicatrização) e pela reprodução assexuada em organismos unicelulares. Suas etapas são **prófase**, **metáfase**, **anáfase** e **telófase**, seguidas da citocinese. Uma célula 2n com 46 cromossomos origina duas células 2n com 46 cromossomos.',
  'Na **prófase**, os cromossomos se condensam, a carioteca se desfaz e se forma o **fuso mitótico**, com fibras que partem dos centrossomos. Na **metáfase**, os cromossomos, muito condensados, alinham-se no plano equatorial da célula, e é a fase em que são mais visíveis, usada para a análise do cariótipo. Na **anáfase**, as cromátides-irmãs se separam e migram para polos opostos. Na **telófase**, os cromossomos se descondensam, a carioteca se reorganiza e a célula se divide em duas na **citocinese**: por estrangulamento nas células animais e por formação de uma placa celular nas vegetais.',
  'Como a mitose mantém o número de cromossomos e gera clones, ela garante a **estabilidade genética** das linhagens celulares. Porém, quando falha, podem surgir células com número anormal de cromossomos. A mitose é usada na cultura de tecidos, na produção de mudas de plantas por clonagem e na terapia com **células-tronco**, que se dividem e se diferenciam em diversos tipos celulares. Entender que a mitose produz células idênticas é fundamental para distinguir seu papel do da meiose, cujo objetivo é a variabilidade genética.'] },
 { h:'Meiose: etapas e variabilidade genética', p:[
  'A **meiose** é a divisão que ocorre nas células germinativas para formar os **gametas**. A partir de uma célula diploide (2n), originam-se **quatro células haploides** (n), com metade do número de cromossomos e geneticamente diferentes entre si. Ela é composta por duas divisões sucessivas, a **meiose I** (reducional, em que os cromossomos homólogos se separam) e a **meiose II** (equacional, em que as cromátides-irmãs se separam), precedidas por uma única duplicação do DNA. Por isso, o número de cromossomos é reduzido à metade.',
  'Dois eventos da meiose I geram **variabilidade genética**. O primeiro é o **crossing-over** (permutação), na prófase I, em que os cromossomos homólogos pareados trocam fragmentos entre si, produzindo cromossomos com combinações novas de genes. O segundo é a **segregação independente** dos cromossomos homólogos na anáfase I: a orientação de cada par é aleatória, de modo que as combinações de cromossomos maternos e paternos nos gametas variam. Uma pessoa pode formar mais de 8 milhões (2^23) de gametas diferentes, sem contar o crossing-over.',
  'A meiose é fundamental para a reprodução sexuada, pois mantém constante o número de cromossomos de uma espécie ao longo das gerações: ao se unirem os dois gametas haploides, na **fecundação**, restabelece-se o número diploide. Se não houvesse redução, o número de cromossomos dobraria a cada geração. Falhas na separação dos cromossomos, chamadas de **não disjunção**, geram gametas com número anormal de cromossomos e síndromes como a de Down (trissomia do 21), a de Turner (45, X) e a de Klinefelter (47, XXY).'] },
 { h:'Gametogênese e comparação entre mitose e meiose', p:[
  'A **gametogênese** é a formação dos gametas por meiose. Na **espermatogênese**, que ocorre nos testículos desde a puberdade, uma célula germinativa origina **quatro espermatozoides** funcionais, e a produção é contínua. Na **ovogênese**, que se inicia ainda na vida fetal e é interrompida em fases, uma célula origina **um único óvulo** funcional e três pequenas células, os glóbulos polares, que degeneram. Essa divisão desigual do citoplasma garante ao óvulo as reservas necessárias para o desenvolvimento inicial do embrião. A ovulação ocorre uma vez por ciclo.',
  'A comparação entre os dois processos é um clássico das provas. A **mitose** ocorre em células somáticas, tem uma divisão, produz duas células-filhas idênticas à mãe, mantém o número de cromossomos (2n → 2n) e serve para crescimento e reparação. A **meiose** ocorre em células germinativas, tem duas divisões, produz quatro células diferentes entre si, reduz o número de cromossomos (2n → n) e serve para a formação de gametas e a variabilidade. Só a meiose tem crossing-over e segregação independente.',
  'Em plantas e em muitos organismos, a meiose pode ocorrer em momentos diferentes do ciclo de vida, gerando esporos, como nas samambaias e nos musgos, mas o princípio é o mesmo: reduzir o número de cromossomos e gerar variabilidade. Nas leveduras e nos fungos, a meiose também ocorre. Outra diferença está no tempo: a meiose, especialmente na ovogênese, pode levar anos, com interrupções, enquanto a mitose dura de minutos a poucas horas. Essas diferenças ajudam a explicar fenômenos como o aumento do risco de síndromes com a idade da mãe.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a divisão celular costuma aparecer em questões sobre câncer, clonagem, células-tronco, síndromes cromossômicas, formação de gametas e variabilidade genética. A questão pode apresentar esquemas de células em diferentes fases e perguntar a qual processo correspondem, ou pedir que se compare o número de cromossomos antes e depois da divisão. O raciocínio mais útil é verificar se as células-filhas são iguais à mãe (mitose) ou diferentes e com metade dos cromossomos (meiose).',
  'Alguns pontos de atenção: na meiose I, separam-se os cromossomos homólogos, e na meiose II, as cromátides-irmãs; o crossing-over ocorre na prófase I; a duplicação do DNA ocorre na interfase, antes das duas divisões; a anáfase da mitose separa cromátides, enquanto a da meiose I separa cromossomos inteiros. Em esquemas, conte os cromossomos pelos centrômeros, e não pelas cromátides. Também lembre que o câncer envolve falhas no controle do ciclo e que o tratamento por quimioterapia atinge células de rápida divisão, como as do cabelo.',
  'Para revisar: o ciclo celular tem interfase (G1, S, G2) e divisão; mitose gera 2 células idênticas, em células somáticas; meiose gera 4 células haploides diferentes, em células germinativas; o crossing-over e a segregação independente aumentam a variabilidade; falhas de separação causam síndromes; e o câncer é descontrole da divisão. Esse tema prepara diretamente a Genética, pois explica como os genes passam de uma geração a outra por meio dos gametas.'] }
]}
];
