/* Biologia: textos corridos, temas 16 a 18 */
module.exports = [
{ t:'Vírus e doenças virais', txt:[
 { h:'Estrutura e características dos vírus', p:[
  'Os **vírus** são agentes infecciosos muito pequenos, que só podem ser vistos ao microscópio eletrônico, com dimensões entre 20 e 300 nanômetros. Sua estrutura é simples: um **material genético**, que pode ser DNA ou RNA, nunca os dois ao mesmo tempo, envolvido por uma **cápsula proteica**, o capsídeo. Alguns possuem ainda um envelope externo, derivado da membrana da célula hospedeira, com proteínas que os ajudam a reconhecer e invadir novas células, como a proteína "spike" do coronavírus. Os vírus não têm citoplasma, organelas nem metabolismo próprio.',
  'Por esse motivo, os vírus são **parasitas intracelulares obrigatórios**: só se reproduzem dentro de uma célula hospedeira, utilizando suas enzimas, ribossomos e energia. Fora das células, ficam inativos, como partículas, e por isso muitos cientistas não os consideram seres vivos no sentido pleno, embora possuam material genético, sofram mutações e evoluam. Cada tipo de vírus infecta células específicas, em função do encaixe entre suas proteínas e os receptores da célula hospedeira. Assim, os vírus que infectam bactérias, chamados de **bacteriófagos**, não infectam as humanas.',
  'O ciclo de multiplicação de um vírus tem etapas: **adsorção** (fixação à célula), **penetração** (entrada do material genético), **replicação** (produção de novas cópias do genoma e das proteínas virais pela maquinaria da célula), **montagem** das novas partículas e **liberação**, que pode ocorrer com a ruptura da célula (ciclo lítico) ou por brotamento. Em alguns casos, o material genético viral se integra ao DNA da célula e permanece inativo por um tempo (ciclo lisogênico), como no herpes, que pode reativar em períodos de baixa imunidade.'] },
 { h:'Principais doenças virais e suas formas de transmissão', p:[
  'Os vírus causam muitas doenças humanas. Algumas se transmitem pelo **ar**, por gotículas e aerossóis, como a gripe, o sarampo, a covid-19, a catapora e a rubéola. Outras, por **vetores** (insetos), como a dengue, a zika, a chikungunya e a febre amarela, transmitidas pelos mosquitos, principalmente o Aedes aegypti. Há as de transmissão por **contato** com fluidos corporais, como a hepatite B e C e o HIV (aids), e as de **via fecal-oral**, como a poliomielite e a hepatite A, pela água e por alimentos contaminados. A raiva se transmite pela mordida de animais infectados.',
  'A **dengue** é uma doença de grande impacto no Brasil, com febre, dor no corpo e atrás dos olhos e manchas na pele, podendo evoluir para formas graves, com hemorragia. Existem quatro sorotipos do vírus, e a infecção por um tipo não protege contra os outros. A **febre amarela** tem um ciclo silvestre (em macacos, com mosquitos do gênero Haemagogus) e outro urbano, e é prevenida com vacina. A **zika**, associada à microcefalia em bebês de mães infectadas na gravidez, e a **chikungunya**, que causa dores articulares fortes, são transmitidas pelo mesmo mosquito da dengue.',
  'O **HIV** é um retrovírus de RNA que ataca os **linfócitos T auxiliares** (CD4), células centrais do sistema imunológico, e leva à imunodeficiência, à síndrome da imunodeficiência adquirida (aids). Transmite-se por relações sexuais sem preservativo, pelo sangue (compartilhamento de seringas e transfusões não testadas) e da mãe para o filho (na gestação, parto ou amamentação). Não se transmite por abraço, beijo, picada de inseto ou compartilhamento de talheres. A terapia antirretroviral controla a infecção e permite longa expectativa de vida, e o uso de preservativos e a profilaxia pré-exposição ajudam a prevenir.'] },
 { h:'Prevenção, vacinas e tratamento', p:[
  'Para as doenças virais, a **prevenção** é a principal estratégia, pois os **antibióticos não funcionam contra vírus**, já que agem em estruturas das bactérias, como a parede celular, que os vírus não têm. Existem medicamentos **antivirais** para algumas infecções (herpes, HIV, hepatite C, gripe), mas são específicos e limitados. O tratamento de muitas viroses, como a dengue, é de suporte (hidratação, repouso e controle da febre), e o uso incorreto de medicamentos, como a aspirina, pode ser perigoso. Daí a importância do atendimento médico.',
  'As **vacinas** são a principal ferramenta contra as viroses. Elas apresentam ao sistema imunológico o vírus inativado ou atenuado, uma de suas proteínas ou o material genético que as codifica (como as vacinas de RNA mensageiro), sem causar a doença, estimulando a produção de anticorpos e de **células de memória**. Assim, em um contato futuro, a resposta é rápida e intensa. A vacinação em massa levou à **erradicação** da varíola e ao controle de doenças como a poliomielite e o sarampo, que voltam a ameaçar quando a cobertura vacinal diminui.',
  'As medidas de **saúde pública** complementam as vacinas: o controle do mosquito Aedes aegypti, eliminando água parada em pneus, vasos e caixas, para evitar criadouros; o saneamento básico, para as viroses de transmissão fecal-oral; o uso de máscaras, a higiene das mãos e a ventilação dos ambientes, para as de transmissão respiratória; o uso de preservativos e as campanhas de informação, para as infecções sexualmente transmissíveis. A combinação dessas ações reduz a propagação, o que é decisivo em epidemias e pandemias.'] },
 { h:'Mutação, evolução viral, epidemias e pandemias', p:[
  'Os vírus de RNA, como os da gripe, do HIV e do coronavírus, mutam com grande frequência, pois a enzima que copia seu genoma comete muitos erros e não os corrige tão bem. Isso gera **variantes** e dificulta a imunidade e o desenvolvimento de vacinas. O vírus da gripe muda tanto que é preciso atualizar a vacina todos os anos. Quando o vírus infecta vários animais e troca material genético com outros vírus, podem surgir cepas novas, como as da gripe aviária e suína, às quais a população humana não tem imunidade.',
  'Algumas definições são importantes: **endemia** é a presença constante de uma doença em uma região (a malária na Amazônia); **epidemia** é o aumento súbito do número de casos em uma região; **pandemia** é uma epidemia que se espalha por vários países e continentes, como a covid-19 e a gripe espanhola (1918). O **surto** é um aumento localizado, por exemplo, em uma escola. As **zoonoses**, doenças transmitidas de animais para humanos, são a origem de muitas novas viroses, e a destruição de ambientes naturais e o contato mais próximo com animais silvestres aumentam o risco de novas epidemias.',
  'Os **cientistas** acompanham a evolução viral por meio do **sequenciamento do genoma**, e ajustam as vacinas e as medidas de controle. Já os **vírus oncogênicos**, como o HPV, associado ao câncer de colo do útero, podem causar tumores, e a vacina contra o HPV reduz esse risco. Existem ainda vírus úteis: os **bacteriófagos** podem ser usados contra bactérias resistentes, e vírus modificados servem como **vetores** na terapia gênica e em vacinas. Isso mostra que a relação entre vírus e humanos é diversa e que conhecer sua biologia traz benefícios.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Vírus e doenças virais são muito frequentes no ENEM, em questões que relacionam a Biologia com saúde pública: dengue e controle do mosquito, vacinação e a importância da cobertura vacinal, aids e formas de transmissão, gripe e mutação do vírus, zika e microcefalia, covid-19 e medidas de prevenção, e hepatites. O texto geralmente descreve uma epidemia, um calendário de vacinação ou um gráfico de casos, e pergunta qual medida é mais eficaz ou qual característica do vírus explica o fenômeno.',
  'Pontos de atenção: vírus não são tratados com antibióticos; as vacinas previnem, e não curam; o vírus não tem metabolismo próprio; a dengue e a febre amarela são transmitidas por mosquitos, e a prevenção passa pela eliminação de criadouros; o HIV ataca os linfócitos T auxiliares; a alta taxa de mutação dos vírus de RNA exige atualização das vacinas. Em questões de gráficos, observe o crescimento do número de casos e relacione-o às medidas (vacinação, isolamento, sazonalidade das chuvas, que aumentam os criadouros).',
  'Para revisar, monte uma tabela com a doença, o agente, a forma de transmissão e a prevenção principal. Treine também diferenciar epidemia, endemia e pandemia, e explicar com suas palavras por que vírus não são afetados por antibióticos. Esse tema se conecta ao seguinte, que trata de bactérias, protozoários e verminoses, outras causas de doenças em que as medidas de saneamento e de educação em saúde têm papel decisivo.'] }
]},
{ t:'Bactérias, protozoários e verminoses', txt:[
 { h:'Bactérias: características e doenças bacterianas', p:[
  'As **bactérias** são organismos **unicelulares procariontes**, ou seja, sem núcleo definido nem organelas membranosas. Possuem parede celular, geralmente de peptideoglicano, e podem ter formas variadas: esféricas (**cocos**), em bastão (**bacilos**), em espiral (**espirilos**) e em vírgula (**vibriões**). Muitas se movem por flagelos, e algumas formam esporos resistentes, que sobrevivem a condições extremas. Reproduzem-se principalmente por **divisão binária**, muito rápida em condições favoráveis, e trocam material genético por **conjugação**, **transformação** e **transdução**, o que as torna muito adaptáveis.',
  'A maioria das bactérias é inofensiva ou útil. Elas são **decompositoras**, participam dos ciclos biogeoquímicos (como na fixação do nitrogênio), compõem a **microbiota intestinal**, que ajuda na digestão e na proteção contra patógenos, e são usadas na produção de alimentos (iogurte, queijo, vinagre), de medicamentos (insulina por engenharia genética) e na biorremediação, que degrada poluentes. Apenas uma pequena parte é patogênica, isto é, causa doenças, por infectar tecidos ou produzir toxinas.',
  'As doenças bacterianas importantes incluem: a **tuberculose** (transmissão pelo ar, afeta os pulmões), a **cólera** e a **febre tifoide** (pela água e alimentos contaminados), a **leptospirose** (pela urina de ratos, em enchentes), o **tétano** (pela contaminação de ferimentos com esporos), a **difteria** e a **coqueluche** (pelo ar), a **meningite bacteriana**, a **sífilis** e a **gonorreia** (infecções sexualmente transmissíveis), e a **hanseníase**. Muitas são evitadas com vacinas, saneamento e higiene, e tratadas com antibióticos, que combatem apenas bactérias.'] },
 { h:'Antibióticos e resistência bacteriana', p:[
  'Os **antibióticos** são substâncias que matam ou inibem o crescimento das bactérias, sem afetar, em geral, as células humanas. Atuam sobre estruturas específicas, como a parede celular (penicilina), os ribossomos bacterianos ou a síntese do DNA bacteriano. O primeiro foi a **penicilina**, descoberta por Alexander Fleming em 1928, a partir de um fungo do gênero Penicillium, que inibia o crescimento das bactérias em uma placa de cultura. Os antibióticos revolucionaram a medicina, reduzindo drasticamente a mortalidade por infecções.',
  'Contudo, o uso inadequado, como a automedicação, a interrupção do tratamento antes do tempo, o uso contra vírus e o uso em excesso na pecuária, favorece a **resistência bacteriana**. Na população de bactérias há variações genéticas, e algumas possuem mutações ou genes que as tornam resistentes. O antibiótico elimina as sensíveis e **seleciona** as resistentes, que se multiplicam e podem transferir os genes a outras bactérias. É um exemplo direto de **seleção natural** e uma das maiores ameaças à saúde pública, com o surgimento de "superbactérias", resistentes a vários antibióticos.',
  'Para reduzir o problema, é preciso usar antibióticos **somente com receita médica**, na dose e no tempo prescritos, completar o tratamento e evitar o uso desnecessário. Os hospitais adotam medidas de controle de infecções, como higiene das mãos e isolamento. A pesquisa de novos antibióticos, de alternativas, como os bacteriófagos, e de vacinas também é importante. Esse tema aparece com frequência no ENEM, ligando evolução, genética e saúde, e o raciocínio de seleção natural é o que deve guiar a resposta.'] },
 { h:'Protozoários e doenças protozoóticas', p:[
  'Os **protozoários** são organismos **unicelulares eucariontes**, heterótrofos, em geral de vida livre em ambientes aquáticos e úmidos, mas alguns são parasitas. Podem ser classificados pelo modo de locomoção: **amebas** (pseudópodes), **flagelados** (flagelos), **ciliados** (cílios) e **esporozoários** (sem estruturas locomotoras, todos parasitas). Reproduzem-se por divisão binária e, em alguns casos, de modo sexuado. Os de vida livre participam das cadeias alimentares, como parte do plâncton, e alguns são decompositores.',
  'Entre as doenças causadas por protozoários, a **malária** é transmitida pela picada da fêmea do mosquito Anopheles e causada pelo Plasmodium, com febre alta em ciclos, calafrios e anemia; é endêmica na Amazônia. A **doença de Chagas** é causada pelo Trypanosoma cruzi, transmitido pelas fezes do barbeiro, inseto que vive em casas de pau a pique, e também por alimentos contaminados (como o caldo de cana e o açaí) e por transfusão; pode afetar o coração e o intestino. A **leishmaniose** é transmitida pelo mosquito-palha. A **toxoplasmose**, causada pelo Toxoplasma gondii, é transmitida por fezes de gatos e carne crua, e é perigosa na gestação.',
  'Outras são a **giardíase** e a **amebíase**, de transmissão fecal-oral, que causam diarreia e se relacionam à falta de saneamento, e a **tricomoníase**, uma infecção sexualmente transmissível. A prevenção depende do controle dos vetores (uso de mosquiteiros, inseticidas, melhoria das moradias), do saneamento, da higiene de alimentos e da água e do tratamento dos doentes. Por afetarem sobretudo populações pobres, muitas dessas doenças são chamadas de **negligenciadas**, e o investimento em pesquisa e em políticas públicas é menor do que o necessário.'] },
 { h:'Verminoses: parasitas e prevenção', p:[
  'As **verminoses** são doenças causadas por vermes parasitas, do grupo dos platelmintos (vermes achatados) e dos nematelmintos (vermes cilíndricos). Entre os **platelmintos**, as **tênias** (Taenia solium e Taenia saginata) causam a **teníase** e a **cisticercose**, e vêm do consumo de carne de porco ou de boi crua ou malpassada. Já os **esquistossomos** (Schistosoma mansoni) causam a **esquistossomose**, ou "barriga d'água", adquirida pelo contato com água de lagoas com caramujos infectados, em que as larvas penetram pela pele.',
  'Entre os **nematelmintos**, a **ascaridíase** (lombriga) é transmitida por alimentos e água contaminados com ovos; a **ancilostomose** (amarelão) é transmitida por larvas que penetram pela pele dos pés descalços, e causa anemia; a **filariose** (elefantíase) é transmitida pelo mosquito Culex, e causa inchaço dos membros; e a **enterobiose** (oxiúro) causa coceira anal e é muito comum em crianças. Alguns vermes têm ciclos complexos, com **hospedeiros intermediários**, como o caramujo (esquistossomose) e o porco (teníase).',
  'A **prevenção** das verminoses depende, em grande parte, do **saneamento básico**, com tratamento da água e do esgoto, da **higiene** pessoal e dos alimentos (lavar as mãos, as frutas e as verduras, cozinhar bem as carnes), do **uso de calçados** e do tratamento dos infectados. A educação em saúde e o combate à pobreza são fundamentais. O ENEM costuma explorar a relação entre a doença e a falta de saneamento, e pedir que se identifique qual medida é mais eficaz e de que maneira o ciclo do parasita pode ser interrompido.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'As doenças causadas por bactérias, protozoários e vermes aparecem no ENEM em questões de **saúde pública e saneamento**. Os textos tratam de enchentes e leptospirose, malária na Amazônia, doença de Chagas e moradia, esquistossomose e lagoas, uso de antibióticos e resistência, calendários de vacinação e a eficácia das medidas de prevenção. É frequente o enunciado fornecer o ciclo do parasita e pedir em que ponto agir para interrompê-lo.',
  'Dicas: para identificar a doença, observe a **forma de transmissão** (água, ar, vetor, contato); para escolher a medida de prevenção, relacione-a ao ciclo (saneamento para doenças fecal-orais, controle de vetores para malária e dengue, calçados para amarelão, cozimento da carne para teníase); lembre que antibióticos funcionam contra bactérias, mas não contra vírus, protozoários ou vermes; e que o uso inadequado favorece a seleção de resistentes. Os medicamentos para protozoários e vermes são outros (antiparasitários).',
  'Para revisar, construa uma tabela: doença, agente (bactéria, protozoário ou verme), transmissão e prevenção. Por exemplo: cólera, bactéria, água, saneamento; malária, protozoário, mosquito Anopheles, controle do vetor; esquistossomose, verme, água com caramujo, saneamento; tuberculose, bactéria, ar, vacina BCG e tratamento. Esse quadro é uma ferramenta rápida de revisão. O tema seguinte, o sistema imunológico, explica como o organismo se defende desses agentes e como as vacinas atuam.'] }
]},
{ t:'Sistema imunológico e vacinas', txt:[
 { h:'Defesas do organismo: imunidade inata e adaptativa', p:[
  'O **sistema imunológico** é o conjunto de células, tecidos e moléculas que defendem o organismo contra agentes estranhos, como vírus, bactérias, fungos, parasitas e células alteradas. Ele atua em duas frentes. A **imunidade inata** (ou inespecífica) está presente desde o nascimento e responde da mesma forma a qualquer invasor, e de modo rápido. Inclui as **barreiras físicas e químicas** (pele, mucosas, cílios da traqueia, lágrimas, saliva, suco gástrico), a **inflamação** (com vermelhidão, calor, inchaço e dor), a **febre** e as células **fagocitárias** (neutrófilos e macrófagos), que englobam e destroem micróbios.',
  'A **imunidade adaptativa** (ou específica) é mais lenta no primeiro contato, mas muito eficiente e com **memória**. Reconhece moléculas específicas, os **antígenos**, de cada agente, e produz uma resposta direcionada. É realizada pelos **linfócitos**, glóbulos brancos que se originam na medula óssea. Os **linfócitos B** produzem **anticorpos** (imunoglobulinas), proteínas que se ligam aos antígenos e os neutralizam, e os **linfócitos T** coordenam a resposta (**T auxiliares**) ou destroem células infectadas (**T citotóxicos**). Após o combate, parte dessas células se torna **célula de memória**.',
  'Na **resposta primária**, no primeiro contato com um antígeno, a produção de anticorpos é lenta, leva dias e é de menor intensidade, e a pessoa geralmente adoece. Na **resposta secundária**, em um novo contato, as células de memória reagem de maneira **rápida e intensa**, produzindo muitos anticorpos em poucas horas e eliminando o agente antes que cause doença. Essa memória imunológica é a base do funcionamento das vacinas e explica por que certas doenças, como a catapora, em geral só acometem a pessoa uma vez.'] },
 { h:'Anticorpos, antígenos e imunidade ativa e passiva', p:[
  'Os **antígenos** são substâncias reconhecidas como estranhas pelo sistema imunológico, em geral proteínas ou polissacarídeos da superfície dos micróbios, ou toxinas. Os **anticorpos** são específicos: cada um reconhece um antígeno, como uma chave e uma fechadura. Eles agem neutralizando toxinas, impedindo que vírus infectem células, marcando micróbios para a fagocitose e ativando outras defesas. A produção de anticorpos específicos é a base dos testes sorológicos, que detectam a presença de anticorpos no sangue e indicam contato anterior com um agente.',
  'A **imunidade ativa** é aquela em que o próprio organismo produz anticorpos e células de memória, e é **duradoura**. Pode ser **natural**, após a doença, ou **artificial**, após a vacina. A **imunidade passiva** é aquela em que o organismo recebe anticorpos prontos, e por isso é **imediata, mas temporária**, pois não há formação de memória. Pode ser **natural**, como os anticorpos que o bebê recebe da mãe pela placenta e pelo leite materno, ou **artificial**, pela aplicação de **soro**, como o soro antiofídico e o antitetânico.',
  'É essencial distinguir **vacina** e **soro**. A vacina contém o agente ou parte dele (inativado, atenuado, ou o código para produzir seu antígeno), serve para **prevenir** e estimula a imunidade ativa. O soro contém anticorpos prontos, produzidos em outro organismo (como o cavalo), serve para **tratar** quem já foi exposto, como em acidentes com cobras ou aranhas, e confere imunidade passiva. Em uma situação de emergência, como uma picada de cobra peçonhenta, não há tempo para o organismo produzir anticorpos, por isso se usa o soro.'] },
 { h:'Vacinação, calendário vacinal e imunidade coletiva', p:[
  'As **vacinas** são a intervenção de saúde pública mais eficaz já criada. Existem vários tipos: de **vírus ou bactérias inativados** (mortos), de **agentes atenuados** (vivos, mas enfraquecidos), de **subunidades** ou **toxoides** (partes do agente ou toxinas inativadas, como a do tétano) e as de **material genético** (como as de RNA mensageiro), que instruem as próprias células a produzir um antígeno. As de agentes vivos atenuados costumam gerar resposta mais duradoura, mas não podem ser dadas a pessoas com imunidade muito baixa. Algumas exigem **doses de reforço**.',
  'O **Programa Nacional de Imunizações** (PNI) do Brasil, criado em 1973 e ligado ao SUS, oferece gratuitamente vacinas como BCG (tuberculose), hepatite B, poliomielite, tríplice viral (sarampo, caxumba e rubéola), febre amarela, HPV, influenza, entre outras, em um calendário que cobre todas as fases da vida. As campanhas de vacinação em massa permitiram eliminar a poliomielite do país e controlar muitas doenças. A queda recente das taxas de vacinação, por desinformação e por dificuldade de acesso, trouxe de volta doenças que estavam sob controle, como o sarampo.',
  'A **imunidade coletiva** (ou de rebanho) ocorre quando uma parcela grande da população está imune a uma doença, o que dificulta a circulação do agente e **protege também os não vacinados**, como bebês, imunossuprimidos e quem não pode receber a vacina. A porcentagem necessária varia conforme a transmissibilidade da doença: para o sarampo, que é muito contagioso, é preciso cerca de 95% de cobertura. Por isso, vacinar-se é um ato individual e social, e a recusa em vacinar pode colocar em risco pessoas que dependem da proteção coletiva.'] },
 { h:'Alergias, doenças autoimunes, transplantes e imunodeficiências', p:[
  'Nem sempre o sistema imunológico atua de modo benéfico. As **alergias** são respostas exageradas a substâncias inofensivas (alérgenos), como pólen, ácaros, pelos de animais e alimentos. Na primeira exposição, o organismo se sensibiliza e produz anticorpos que se ligam a células, como os mastócitos; em uma nova exposição, essas células liberam **histamina**, que causa coceira, espirros, inchaço e, nos casos graves, o **choque anafilático**, que pode ser fatal. O tratamento usa anti-histamínicos e, nos casos graves, adrenalina.',
  'Nas **doenças autoimunes**, o sistema imunológico ataca as próprias células do corpo, por perder a capacidade de distinguir o próprio do estranho. São exemplos o **diabetes tipo 1** (destruição das células produtoras de insulina), a **artrite reumatoide**, a **esclerose múltipla** e o **lúpus**. Nos **transplantes**, o sistema imunológico pode reconhecer o órgão como estranho e **rejeitá-lo**, por isso se busca a compatibilidade entre doador e receptor (sistema HLA) e se usam medicamentos **imunossupressores**, o que deixa o paciente mais vulnerável a infecções.',
  'As **imunodeficiências** são condições em que o sistema imunológico não funciona adequadamente. Podem ser **congênitas** (genéticas) ou **adquiridas**, como na aids, em que o HIV destrói os linfócitos T auxiliares. Com isso, o organismo fica exposto a **infecções oportunistas**, que raramente causam doença em pessoas saudáveis. Também há o **câncer**, em que células alteradas escapam da vigilância imunológica. As **imunoterapias** modernas, que estimulam o sistema imunológico a atacar tumores, são um avanço da medicina, resultado do conhecimento sobre essas interações.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM cobra imunologia com muita frequência, quase sempre em contextos de saúde: campanhas de vacinação, soros em acidentes com animais peçonhentos, doenças autoimunes, alergias, transfusões e transplantes, aids e infecções oportunistas, pandemias e imunidade coletiva. Os textos trazem gráficos de resposta imunológica ou descrições de calendários vacinais, e pedem para explicar por que determinada medida protege a população.',
  'Pontos que costumam decidir a questão: a diferença entre vacina (previne, imunidade ativa, com memória) e soro (trata, imunidade passiva, sem memória); a resposta secundária mais rápida e mais intensa, que explica a eficácia dos reforços; o papel dos linfócitos B (anticorpos) e T (coordenação e destruição de células infectadas); e o conceito de imunidade coletiva. Em gráficos de anticorpos, o segundo contato apresenta uma curva mais alta e mais rápida do que o primeiro.',
  'Para revisar, resuma assim: imunidade inata (barreiras, inflamação, fagócitos) e adaptativa (linfócitos B e T, com memória); anticorpos neutralizam antígenos; a vacina gera imunidade ativa duradoura; o soro dá imunidade passiva e imediata; imunidade coletiva protege quem não pode se vacinar; alergia é exagero da resposta; autoimunidade é o ataque ao próprio corpo; aids é a perda de linfócitos T auxiliares. Esse tema fecha o bloco de microrganismos e doenças, e o próximo trata dos sistemas do corpo humano, começando pela digestão e nutrição.'] }
]}
];
