/* Biologia: textos corridos, temas 10 a 12 */
module.exports = [
{ t:'Evolução', txt:[
 { h:'Ideias evolucionistas: de Lamarck a Darwin', p:[
  'Durante séculos, predominou a ideia do **fixismo**: as espécies teriam sido criadas como são e não sofreriam mudanças. No século XIX, essa visão passou a ser questionada. O naturalista francês **Jean-Baptiste Lamarck** foi um dos primeiros a propor uma teoria evolutiva, em 1809. Para ele, os organismos mudam ao longo do tempo por duas leis: a **lei do uso e desuso** (órgãos muito usados se desenvolvem, e os pouco usados se atrofiam) e a **lei da herança dos caracteres adquiridos** (as características adquiridas durante a vida seriam transmitidas aos descendentes).',
  'O exemplo clássico de Lamarck é o da girafa: o pescoço teria ficado longo porque seus ancestrais, ao esticá-lo para alcançar folhas altas, o alongavam, e esse alongamento seria passado aos filhotes. Hoje se sabe que essa segunda lei está **incorreta**: as modificações adquiridas ao longo da vida, como músculos desenvolvidos ou cicatrizes, não alteram o DNA dos gametas e, por isso, não são herdadas. Ainda assim, Lamarck teve o mérito de propor que os seres vivos mudam e se adaptam ao ambiente.',
  'Charles Darwin e Alfred Russel Wallace propuseram, de forma independente, a teoria da **seleção natural**, apresentada em 1858 e detalhada na obra "A Origem das Espécies" (1859). A viagem de Darwin no navio Beagle, em que observou a fauna das Ilhas Galápagos, como os tentilhões e as tartarugas, foi decisiva. Ele percebeu que as populações apresentavam variações e que as condições do ambiente favoreciam alguns indivíduos. Darwin, porém, desconhecia a Genética, e a origem da variação só foi explicada com a descoberta das mutações.'] },
 { h:'Seleção natural, adaptação e a teoria sintética', p:[
  'A **seleção natural** pode ser resumida em quatro ideias: 1) os indivíduos de uma população **variam** entre si; 2) parte dessa variação é **hereditária**; 3) nascem mais descendentes do que o ambiente suporta, o que gera **competição**; 4) os indivíduos com características mais vantajosas em dado ambiente têm maior chance de **sobreviver e se reproduzir**, deixando mais descendentes. Com o passar das gerações, as características vantajosas tornam-se mais frequentes na população. A seleção atua sobre os indivíduos, mas quem evolui são as **populações**.',
  'O caso das **mariposas Biston betularia**, na Inglaterra industrial, é um clássico. Antes da Revolução Industrial, predominavam as mariposas claras, camufladas nos troncos de árvores cobertos de líquens claros. Com a poluição, os troncos escureceram, e as mariposas escuras, antes raras, passaram a ser mais camufladas e menos predadas, tornando-se mais comuns. Outro exemplo é o da **resistência de bactérias a antibióticos**: o antibiótico elimina as sensíveis e favorece as poucas resistentes, que se multiplicam. O uso incorreto de antibióticos acelera esse processo.',
  'A **teoria sintética da evolução** (ou neodarwinismo), desenvolvida a partir da década de 1930, combinou a seleção natural com a Genética. Segundo ela, os fatores evolutivos são as **mutações** e a **recombinação gênica** (fontes de variabilidade), a **seleção natural**, a **deriva genética** (mudanças ao acaso nas frequências dos alelos, mais intensas em populações pequenas) e a **migração** (fluxo gênico). A evolução é definida como a mudança na frequência dos alelos de uma população ao longo do tempo. Ela não tem direção nem objetivo: apenas favorece o que funciona melhor em determinado ambiente.'] },
 { h:'Especiação, evidências da evolução e árvores filogenéticas', p:[
  'A **especiação** é o processo de formação de novas espécies. A forma mais comum é a **alopátrica** (ou geográfica): uma população é dividida por uma barreira (rio, montanha, formação de ilhas), e as partes isoladas passam a evoluir de modo independente, acumulando diferenças. Com o tempo, as populações tornam-se incapazes de se reproduzir entre si, e, nesse momento, formam espécies distintas, que mantêm o **isolamento reprodutivo**. A **irradiação adaptativa** ocorre quando uma espécie ancestral origina muitas outras que ocupam nichos diferentes, como os tentilhões de Darwin.',
  'As evidências da evolução são variadas. Os **fósseis** mostram a existência de formas extintas e transições, como os fósseis de baleias com patas. A **anatomia comparada** revela **órgãos homólogos**, com mesma origem embrionária, mesmo que tenham funções diferentes, como o braço humano, a asa do morcego e a nadadeira da baleia, o que indica ancestralidade comum, e **órgãos análogos**, com a mesma função, mas origem diferente, como as asas de insetos e de aves, resultado de **convergência adaptativa**. Os **órgãos vestigiais**, como o apêndice humano, também sugerem ancestrais que os usavam.',
  'A Biologia Molecular fornece outras evidências: o **código genético universal** e a semelhança de sequências de DNA e de proteínas entre espécies, que é maior quanto mais próximo é o parentesco. Os humanos e os chimpanzés compartilham cerca de 98% do DNA. As **árvores filogenéticas** (ou cladogramas) representam as relações de parentesco entre os grupos, em que cada ramificação indica um ancestral comum, e quanto mais recente o ancestral comum, mais próximas são as espécies. Ao ler um cladograma, é preciso observar os pontos de ramificação, e não a ordem em que os nomes aparecem nas pontas.'] },
 { h:'Evolução humana e como o tema cai no ENEM', p:[
  'A **evolução humana** é um tema recorrente. Os humanos e os demais primatas compartilham um ancestral comum, e não descendem dos chimpanzés. A linhagem humana (hominínios) surgiu na África, há alguns milhões de anos. Entre os grupos conhecidos estão os **Australopithecus**, bípedes, com cérebro pequeno; o **Homo habilis**, associado ao uso de ferramentas; o **Homo erectus**, que dominou o fogo e migrou da África; e o **Homo sapiens**, espécie atual, surgida na África há cerca de 300 mil anos. Os neandertais (Homo neanderthalensis) eram uma espécie próxima, que conviveu com o Homo sapiens e deixou parte de seus genes em populações atuais.',
  'No ENEM, a evolução costuma aparecer em questões que pedem a distinção entre a explicação de Lamarck e a de Darwin, a análise de um caso de seleção natural (resistência de bactérias e de insetos a defensivos, camuflagem, mimetismo), a interpretação de cladogramas e a identificação de órgãos homólogos e análogos. As alternativas incorretas frequentemente trazem a ideia de que os organismos mudam "por necessidade" ou "para se adaptar", o que reflete o pensamento lamarckista e deve ser evitado.',
  'Para revisar: Lamarck propôs uso e desuso e herança dos caracteres adquiridos (incorreta); Darwin e Wallace propuseram a seleção natural; a teoria sintética incorpora mutação, recombinação, seleção, deriva e migração; a especiação mais comum é a alopátrica; homologia indica ancestralidade comum e analogia indica convergência; e a evolução atua sobre populações. Relacione o tema com a genética (as mutações), com a ecologia (a pressão seletiva do ambiente) e com a saúde (resistência a antibióticos).'] }
]},
{ t:'Ecologia: conceitos e cadeias alimentares', txt:[
 { h:'Conceitos básicos: população, comunidade, ecossistema e nicho', p:[
  'A **Ecologia** estuda as relações entre os seres vivos e o ambiente em que vivem. O termo foi criado por Ernst Haeckel, em 1866. Para organizar o estudo, usam-se alguns conceitos. **População** é o conjunto de indivíduos da mesma espécie que vivem em uma área, em um dado tempo. **Comunidade** (ou biocenose) é o conjunto de populações de espécies diferentes que vivem em uma mesma área e interagem. **Ecossistema** é a comunidade mais os fatores abióticos (luz, água, temperatura, solo) com os quais interage. **Biosfera** é o conjunto de todos os ecossistemas da Terra.',
  'O **habitat** é o local onde uma espécie vive, o "endereço". O **nicho ecológico** é o conjunto de condições e recursos de que a espécie necessita e o papel que ela desempenha no ecossistema, a "profissão": o que come, quando e onde, como se reproduz e com quem interage. Duas espécies não podem ocupar exatamente o mesmo nicho por muito tempo no mesmo local, pois competiriam, e uma delas tenderia a ser eliminada, o chamado **princípio da exclusão competitiva**. Por isso, as espécies que convivem costumam diferenciar seus nichos.',
  'Os fatores do ambiente se dividem em **bióticos**, relacionados aos seres vivos (predação, competição, parasitismo) e **abióticos**, relacionados aos aspectos físicos e químicos (luz, temperatura, umidade, pH, salinidade). Esses fatores determinam onde cada espécie consegue viver, dentro de seus **limites de tolerância**. Os organismos que toleram pequenas variações de determinado fator são os **estenoicos** e podem servir como **bioindicadores** da qualidade do ambiente, como os líquens, sensíveis à poluição do ar, e certos insetos aquáticos, sensíveis à poluição da água.'] },
 { h:'Cadeias e teias alimentares', p:[
  'Os seres vivos de um ecossistema se relacionam pela alimentação, e esse fluxo é representado por **cadeias alimentares**, sequências lineares que mostram quem serve de alimento para quem. Cada nível é um **nível trófico**. O primeiro é o dos **produtores**, geralmente autótrofos, como plantas e algas, que convertem energia solar em energia química. Em seguida vêm os **consumidores**: **primários** (herbívoros), **secundários** (carnívoros que comem herbívoros), **terciários** e assim por diante. Os **decompositores**, como fungos e bactérias, atuam em todos os níveis, degradando a matéria orgânica e devolvendo os nutrientes ao ambiente.',
  'Na natureza, a maioria das espécies participa de várias cadeias, e as relações formam uma **teia alimentar**, rede complexa de cadeias interligadas. Quanto mais complexa e diversificada é a teia, mais estável é o ecossistema, pois, se uma espécie desaparece, os consumidores têm alternativas de alimento. A retirada de uma espécie-chave, ou a introdução de uma espécie exótica, pode causar desequilíbrios em cascata. Em exercícios, é comum pedir o que acontece com cada população se uma delas aumentar ou diminuir.',
  'As setas na cadeia alimentar indicam o **sentido do fluxo de energia e de matéria**, ou seja, apontam do alimento para quem o consome (por exemplo, capim → gafanhoto → sapo → cobra). Um erro comum é desenhar as setas no sentido oposto, "quem come quem". Também é importante lembrar que os decompositores não ocupam um nível específico, mas sim todos, e que os seres humanos, como onívoros, ocupam vários níveis, o que influencia a quantidade de energia necessária para a alimentação.'] },
 { h:'Fluxo de energia, pirâmides ecológicas e bioacumulação', p:[
  'A energia que entra no ecossistema vem do Sol, é captada pelos produtores e flui em **um só sentido**, de nível em nível, com grande perda. Em cada nível trófico, só cerca de **10%** da energia passa ao nível seguinte; o restante é gasto na respiração (como calor), na locomoção e nas partes não aproveitadas. Por isso, as cadeias alimentares são curtas (geralmente de 3 a 5 níveis) e há poucos predadores de topo em relação à quantidade de produtores. Já a **matéria** circula, sendo reaproveitada pelos decompositores, em ciclos.',
  'As **pirâmides ecológicas** representam esse padrão. A **pirâmide de energia** nunca é invertida: a energia disponível diminui a cada nível. A **pirâmide de biomassa** (massa de matéria orgânica) pode ser invertida em alguns ecossistemas aquáticos, em que os produtores (fitoplâncton) têm pouca biomassa em um dado momento, mas se reproduzem muito rápido. A **pirâmide de números**, que conta indivíduos, também pode ser invertida, como no caso de uma árvore grande com muitos insetos. Essas distinções são cobradas em questões de interpretação.',
  'A **bioacumulação** é o acúmulo de substâncias que não são degradadas nem excretadas, como o mercúrio, o chumbo e o DDT, nos tecidos dos organismos. Na **magnificação trófica** (ou biomagnificação), a concentração dessas substâncias **aumenta ao longo da cadeia alimentar**, de modo que os predadores de topo têm as maiores concentrações. Um exemplo é o mercúrio dos garimpos, que contamina peixes e populações ribeirinhas. Isso explica por que o consumo de peixes carnívoros grandes oferece maior risco do que o de peixes herbívoros ou de espécies menores.'] },
 { h:'Dinâmica das populações e sucessão ecológica', p:[
  'O tamanho de uma população varia conforme quatro fatores: **natalidade** e **imigração**, que aumentam a população, e **mortalidade** e **emigração**, que a diminuem. O **potencial biótico** é a capacidade máxima de crescimento de uma espécie em condições ideais, e a **resistência ambiental** é o conjunto de fatores (falta de alimento, predadores, doenças, competição) que limitam esse crescimento. O equilíbrio entre os dois define a **capacidade de suporte** do ambiente, que é o número máximo de indivíduos que ele pode sustentar. No gráfico, o crescimento tem formato de "S" (curva logística).',
  'A **sucessão ecológica** é o processo gradual de substituição de comunidades ao longo do tempo, até atingir uma comunidade estável, o **clímax**. Na **sucessão primária**, a colonização ocorre em um ambiente sem vida anterior, como uma rocha nua ou uma duna, e começa pelos **pioneiros**, como líquens e musgos, que formam o solo; na **secundária**, ocorre em áreas já ocupadas anteriormente e que foram perturbadas, como em uma floresta que sofreu queimada ou desmatamento, e é mais rápida, pois o solo já existe. Ao longo da sucessão, a diversidade e a complexidade aumentam, e a produção bruta tende a se equilibrar com a respiração.',
  'Esse conhecimento é aplicado na **recuperação de áreas degradadas**, em que se plantam espécies pioneiras, que preparam o ambiente para as demais, e na gestão de populações de espécies em risco ou pragas. O controle biológico, por exemplo, usa predadores ou parasitas naturais para controlar populações de pragas agrícolas, reduzindo o uso de agrotóxicos. Também ajuda a compreender fenômenos como a explosão populacional de espécies introduzidas, que, sem predadores naturais e com abundância de recursos, crescem rapidamente e desequilibram o ecossistema.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Ecologia é um dos temas mais cobrados do ENEM. As questões costumam fornecer uma teia alimentar, uma pirâmide ou um gráfico populacional e pedir previsões sobre o que ocorre quando um elemento muda, como a retirada de um predador, a introdução de uma espécie exótica ou o uso de um agrotóxico. Outras tratam de bioacumulação, sucessão ecológica e recuperação de áreas degradadas. A habilidade principal é raciocinar sobre as consequências em cadeia.',
  'Para resolver: identifique os níveis tróficos e o sentido das setas; pense nos efeitos diretos e indiretos de aumentar ou diminuir uma população; lembre que os produtores são a base e que a energia diminui a cada nível; e que substâncias persistentes se concentram nos níveis mais altos. Em gráficos populacionais, procure o ponto de estabilização, que representa a capacidade de suporte, e as oscilações em ciclos de presa e predador, em que o aumento da presa antecede o do predador.',
  'Resumo: população, comunidade e ecossistema são níveis de organização; nicho é o papel e habitat é o local; as cadeias alimentares têm produtores, consumidores e decompositores; a energia flui em sentido único com perda de cerca de 90% por nível; a matéria circula; a magnificação trófica concentra poluentes nos predadores de topo; e a sucessão ecológica leva ao clímax. Esse tema é a base dos seguintes, as relações ecológicas, os ciclos biogeoquímicos, os biomas e os impactos ambientais.'] }
]},
{ t:'Relações ecológicas', txt:[
 { h:'Classificação das relações ecológicas', p:[
  'Os seres vivos de uma comunidade interagem de várias formas, e essas interações são chamadas de **relações ecológicas**. Elas são classificadas, em primeiro lugar, quanto ao **efeito** sobre os envolvidos: **harmônicas** (ou positivas) quando nenhum dos participantes é prejudicado, e **desarmônicas** (ou negativas) quando ao menos um deles sofre prejuízo. Outra divisão separa as relações **intraespecíficas**, entre indivíduos da mesma espécie, das **interespecíficas**, entre espécies diferentes.',
  'Para analisar uma relação, uma boa estratégia é usar o sinal de cada participante: **+** se é beneficiado, **-** se é prejudicado e **0** se não é afetado. O mutualismo é (+/+); o comensalismo, (+/0); a predação e o parasitismo, (+/-); a competição, (-/-); e o amensalismo, (-/0). Em todas elas, o benefício se mede em termos de sobrevivência e de reprodução. As relações podem mudar conforme as circunstâncias, e uma mesma espécie pode participar de várias relações ao longo da vida.',
  'Entender essas relações é essencial para compreender o equilíbrio dos ecossistemas, o controle de pragas, a transmissão de doenças e a conservação da biodiversidade. Por exemplo, a remoção de predadores pode levar ao crescimento descontrolado de populações de presas, que passam a competir intensamente e a esgotar os recursos. Por outro lado, a perda de polinizadores põe em risco a reprodução de muitas plantas e, com isso, a produção de alimentos, o que mostra que as relações são fundamentais para a vida humana.'] },
 { h:'Relações harmônicas', p:[
  'Entre as relações **harmônicas intraespecíficas**, estão as **colônias**, em que os indivíduos permanecem unidos e podem ter funções diferentes, como os corais e as caravelas, e as **sociedades**, em que os indivíduos vivem organizados e cooperam, mas permanecem independentes, como as abelhas, as formigas, os cupins e os humanos. Nas sociedades de insetos há divisão de trabalho em castas (rainha, operárias, soldados). A cooperação traz vantagens, como a defesa do grupo e a obtenção de alimentos, mas também facilita a transmissão de doenças.',
  'Nas **harmônicas interespecíficas**, o **mutualismo** é uma associação em que os dois se beneficiam e que, em geral, é obrigatória para a sobrevivência: os **líquens** (fungo e alga ou cianobactéria), as **micorrizas** (fungos e raízes de plantas), as bactérias fixadoras de nitrogênio nas raízes de leguminosas e as bactérias da flora intestinal que auxiliam a digestão e produzem vitaminas. A **protocooperação** é uma associação em que ambos se beneficiam, mas **não é obrigatória**, como a do pássaro-palito e o crocodilo, ou a das aves que se alimentam de carrapatos do gado.',
  'O **comensalismo** é uma relação em que uma espécie é beneficiada e a outra não é prejudicada nem favorecida, como a das rêmoras, peixes que se prendem aos tubarões e se alimentam de restos de comida, e das bromélias que vivem sobre as árvores (**epifitismo**). O **inquilinismo** é um tipo de comensalismo em que uma espécie usa a outra como abrigo, como o peixe que vive dentro do pepino-do-mar. Na prática, é difícil provar que uma das partes não é afetada, e muitas relações classificadas assim foram reavaliadas como benefícios recíprocos ou pequenos prejuízos.'] },
 { h:'Relações desarmônicas', p:[
  'Nas **desarmônicas intraespecíficas**, está a **competição**, que ocorre entre indivíduos da mesma espécie pelos mesmos recursos (alimento, território, parceiros), e é mais intensa, pois os nichos são idênticos. Também há o **canibalismo**, em que um indivíduo se alimenta de outro da mesma espécie, como em algumas aranhas e peixes. Já a **competição interespecífica** ocorre entre espécies diferentes que disputam o mesmo recurso, e pode levar à exclusão de uma delas ou à divisão dos nichos entre as espécies.',
  'Entre as **desarmônicas interespecíficas**, a **predação** é a relação em que um indivíduo (predador) mata e consome outro (presa), e regula as populações de presas. O predador e a presa evoluem juntos, em uma "corrida armamentista": presas desenvolvem camuflagem, mimetismo e velocidade, e predadores aperfeiçoam sentidos e técnicas de caça. O **parasitismo** é a relação em que o parasita vive à custa do hospedeiro, prejudicando-o, mas geralmente sem matá-lo rapidamente, como no caso da lombriga, do carrapato e do vírus. Os parasitas podem ser **endoparasitas** (dentro do hospedeiro) ou **ectoparasitas** (fora).',
  'O **amensalismo** (ou antibiose) ocorre quando uma espécie libera substâncias que inibem ou matam outra, sem benefício direto, como o fungo Penicillium, que produz a penicilina e inibe bactérias, e a maré vermelha, causada por algas que liberam toxinas. O **esclavagismo** (ou sinfilia) é a relação em que uma espécie escraviza outra, como as formigas que capturam pupas de outras espécies. Outras relações incluem o **herbivorismo**, semelhante à predação, e o **parasitoidismo**, em que as larvas de uma vespa se desenvolvem dentro de outro inseto e acabam por matá-lo, usado no controle biológico.'] },
 { h:'Controle biológico, espécies invasoras e interações com os humanos', p:[
  'O conhecimento das relações ecológicas é aplicado no **controle biológico de pragas**, em que se usam predadores, parasitas ou parasitoides naturais para reduzir populações de organismos nocivos, em substituição, ou como complemento, aos agrotóxicos. Um exemplo é o uso de vespas que parasitam ovos de lagartas em plantações de cana-de-açúcar, e de joaninhas, que consomem pulgões. Há vantagens, como o menor impacto ambiental e a redução do custo, mas é preciso estudar o organismo introduzido, para que ele não se torne, ele mesmo, uma praga.',
  'As **espécies invasoras** (ou exóticas) são aquelas introduzidas em ambientes onde não ocorriam naturalmente. Sem predadores e com recursos abundantes, podem se multiplicar de forma explosiva e competir com as espécies nativas, levando-as à redução ou à extinção. Exemplos no Brasil incluem o mexilhão-dourado, o caramujo-africano, o javali e o capim-braquiária. Diversas introduções foram acidentais (por navios de carga, por exemplo) e outras foram intencionais. A prevenção é a principal estratégia, pois a erradicação é difícil e cara.',
  'A espécie humana também mantém relações com outros seres vivos. Somos hospedeiros de parasitas e dependemos do mutualismo com a microbiota intestinal. Exercemos predação e competição, e mantemos relações com animais domésticos e plantas cultivadas. Porém, nossa atuação em larga escala, com desmatamento, caça e introdução de espécies, tem desestabilizado muitas dessas relações. Ao ler uma questão de contexto ambiental, vale perguntar quais relações ecológicas foram afetadas e como a mudança em uma delas repercute no restante da comunidade.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, as relações ecológicas costumam ser cobradas pela **identificação do tipo de relação em uma situação descrita**: um texto sobre a associação entre um peixe e uma anêmona, entre formigas e plantas, entre fungos e raízes, ou sobre a ação de um parasita, seguidos da pergunta "qual é a relação?". Também aparecem em contextos de controle biológico e de espécies invasoras, e em gráficos de populações de presa e predador, que oscilam em ciclos.',
  'Um método eficaz: 1) identifique os organismos envolvidos; 2) atribua os sinais (+, -, 0) para cada um; 3) escolha a relação que combina com os sinais; 4) verifique se é obrigatória (mutualismo) ou facultativa (protocooperação). Atenção a pegadinhas, como confundir predação e parasitismo (o predador mata e consome a presa; o parasita vive às custas do hospedeiro, sem matá-lo logo) e comensalismo com mutualismo (no primeiro, o outro não ganha nem perde).',
  'Para revisar: mutualismo (+/+, obrigatório), protocooperação (+/+, facultativo), comensalismo (+/0), inquilinismo e epifitismo (tipos de comensalismo), predação (+/-), parasitismo (+/-), competição (-/-) e amensalismo (-/0). Associe cada relação a um exemplo de que se lembre bem, como líquen, rêmora, onça e capivara, carrapato e boi, e penicilina. Em seguida, vale estudar os ciclos biogeoquímicos, que mostram como a matéria circula entre os seres vivos e o ambiente.'] }
]}
];

/* separa "Evolução humana" do bloco final e acrescenta mais um parágrafo */
{
  const evo = module.exports[0];
  const ult = evo.txt.pop();
  evo.txt.push({ h:'Evolução humana', p:[
    ult.p[0],
    'Três características marcam a linhagem humana. O **bipedalismo**, anterior ao grande aumento do cérebro, liberou as mãos para carregar objetos e fabricar ferramentas. O **aumento do cérebro** acompanhou o uso de ferramentas, a cooperação e a linguagem. E a **cultura**, ou seja, o conhecimento transmitido de uma geração a outra pelo aprendizado, tornou-se um fator tão importante quanto os genes. Vale lembrar que a evolução humana não foi uma linha reta, de "macaco" a "homem", e sim um "arbusto" ramificado, em que várias espécies de hominínios coexistiram em diferentes épocas.'
  ]});
  evo.txt.push({ h:'Como esse conteúdo aparece no ENEM', p:[ ult.p[1], ult.p[2] ] });
}

module.exports[0].txt[4].p.push('Uma dica final de estudo: ao ler qualquer questão de evolução, procure o que é **variação preexistente** e o que é **seleção pelo ambiente**. Se o texto diz que os organismos "precisaram" mudar, a explicação é lamarckista e geralmente está errada. Se diz que, entre os indivíduos variados, os mais bem ajustados deixaram mais descendentes, a explicação é darwinista e costuma ser a correta. Esse critério resolve muitas questões do tema.');
