/* Biologia: textos corridos, temas 1 a 3 */
module.exports = [
{ t:'Características dos seres vivos', txt:[
 { h:'O que define um ser vivo', p:[
  'A Biologia é a ciência que estuda a vida, mas definir o que é um ser vivo não é tão simples quanto parece. Não existe uma única característica que separe os seres vivos da matéria não viva, e sim um conjunto de propriedades que, juntas, caracterizam a vida. Uma pedra, por exemplo, pode crescer por acúmulo de material, mas não possui metabolismo, não se reproduz e não responde ao ambiente. Já uma bactéria, muito menor, reúne todas essas propriedades e, por isso, é considerada viva.',
  'As principais características dos seres vivos são: **organização celular**, **metabolismo**, **reprodução**, **hereditariedade**, **crescimento e desenvolvimento**, **homeostase**, **irritabilidade (resposta a estímulos)**, **adaptação e evolução**. Algumas são mais fundamentais do que outras: a composição celular e o metabolismo são universais, enquanto o movimento, por exemplo, não é: muitas plantas e fungos passam toda a vida fixos no mesmo lugar e nem por isso deixam de ser vivos.',
  'Os vírus são um caso limite que costuma gerar debates. Eles possuem material genético e evoluem, mas não têm células, não realizam metabolismo próprio e só se reproduzem dentro de uma célula hospedeira. Por isso, a maioria dos biólogos os considera **acelulares** e fora dos grandes grupos de seres vivos, embora estudados dentro da Biologia. Entender esse debate ajuda a perceber que as definições científicas são construções que podem ter exceções e fronteiras.'] },
 { h:'Organização celular, níveis de organização e a composição química da vida', p:[
  'Todos os seres vivos são formados por **células**, a unidade básica estrutural e funcional da vida. Alguns organismos, como bactérias e protozoários, são **unicelulares**, e todas as funções vitais ocorrem em uma única célula. Outros, como plantas e animais, são **pluricelulares**, e suas células se organizam em tecidos, órgãos e sistemas. A **teoria celular** resume essa ideia em três pontos: todo ser vivo é formado por células; a célula é a unidade básica da vida; e toda célula se origina de outra célula preexistente.',
  'Os níveis de organização da vida vão do mais simples ao mais complexo: átomo, molécula, organela, célula, tecido, órgão, sistema, organismo, população, comunidade, ecossistema, bioma e biosfera. Cada nível apresenta propriedades que não existem nos níveis inferiores, e que emergem da interação entre as partes. Um tecido muscular, por exemplo, é capaz de se contrair, algo que uma proteína isolada não faz sozinha. Essa visão ajuda a conectar temas de Citologia, Fisiologia e Ecologia, que podem ser cobrados em uma mesma questão.',
  'Do ponto de vista químico, os seres vivos compartilham uma composição semelhante. A **água** é a substância mais abundante e funciona como solvente. As **proteínas**, os **carboidratos**, os **lipídios** e os **ácidos nucleicos** são as macromoléculas orgânicas básicas, e as **vitaminas** e os **sais minerais** completam a lista. Os elementos mais comuns são carbono, hidrogênio, oxigênio e nitrogênio. Essa unidade química é uma forte evidência de que todos os seres vivos têm uma origem comum e justifica o uso de modelos como bactérias e moscas para estudar processos humanos.'] },
 { h:'Metabolismo, homeostase e resposta ao ambiente', p:[
  'O **metabolismo** é o conjunto de reações químicas que ocorrem em um organismo para manter a vida. Divide-se em **anabolismo**, as reações de síntese, que constroem moléculas complexas a partir de simples e consomem energia (como a fotossíntese e a produção de proteínas), e **catabolismo**, as reações de degradação, que quebram moléculas complexas e liberam energia (como a respiração celular). A energia obtida no catabolismo é armazenada em moléculas de ATP e usada nas atividades celulares, como movimento, transporte e síntese.',
  'A **homeostase** é a capacidade de manter o meio interno relativamente constante, apesar das variações do ambiente. A regulação da temperatura corporal, da concentração de glicose e de sais no sangue e do pH são exemplos. Em geral, funciona por **retroalimentação negativa**: quando uma variável se afasta do valor ideal, mecanismos agem para trazê-la de volta. Quando a temperatura sobe, por exemplo, a sudorese aumenta, e quando cai, ocorrem arrepios e contração dos vasos da pele. Esse tema se conecta à fisiologia humana.',
  'Os seres vivos também **respondem a estímulos** do ambiente, uma propriedade chamada de irritabilidade ou sensibilidade. A planta que se curva em direção à luz (fototropismo), o animal que foge de um predador e a bactéria que se move em direção a nutrientes (quimiotaxia) são exemplos. Essa capacidade permite ajustar o comportamento às mudanças do meio, aumentando as chances de sobrevivência e de reprodução. Em animais, o sistema nervoso e o endócrino coordenam essas respostas, e nas plantas, os hormônios vegetais têm papel semelhante.'] },
 { h:'Reprodução, hereditariedade e evolução', p:[
  'A **reprodução** é a capacidade de gerar novos indivíduos e garante a continuidade das espécies. Ela pode ser **assexuada**, em que um único organismo origina descendentes geneticamente idênticos a ele, como na divisão binária das bactérias e na brotação das leveduras, ou **sexuada**, em que ocorre a união de gametas de dois indivíduos, gerando descendentes geneticamente diferentes dos pais. A reprodução assexuada é rápida e eficiente em ambientes estáveis, mas a sexuada produz variabilidade genética, importante em ambientes que mudam.',
  'A **hereditariedade** é a transmissão de características dos pais aos filhos por meio do material genético, o **DNA**, que contém as instruções para a construção e o funcionamento do organismo. O código genético é praticamente universal: o mesmo trio de bases codifica o mesmo aminoácido na maioria dos seres vivos, o que reforça a ideia de ancestralidade comum. Pequenas alterações no DNA, as **mutações**, geram novas características e são a fonte primária da variabilidade, sobre a qual atua a seleção natural.',
  'A **evolução** é a mudança das características das populações ao longo das gerações. Segundo a teoria de Darwin e Wallace, indivíduos com características mais vantajosas em determinado ambiente têm maior chance de sobreviver e deixar descendentes, e essas características se tornam mais comuns na população, processo chamado de **seleção natural**. A **adaptação** é o resultado desse processo: uma característica que aumenta a chance de sobrevivência e reprodução em dado ambiente. A evolução explica tanto a diversidade da vida quanto as semelhanças entre os grupos.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Dificilmente o ENEM pergunta "quais são as características dos seres vivos" de forma isolada. Esse conteúdo costuma aparecer como base para outras questões: um texto sobre a descoberta de vida em ambientes extremos, uma discussão sobre se os vírus são seres vivos, uma situação de homeostase (como a regulação da glicose) ou uma análise de adaptação ao ambiente. Entender os conceitos fundamentais ajuda a interpretar enunciados de qualquer área da Biologia.',
  'Fique atento às armadilhas de linguagem: "adaptação" não significa que o indivíduo muda por necessidade, e sim que a seleção natural favorece variações que já existem; "metabolismo" envolve construção e degradação, e não apenas gasto de energia; "homeostase" não significa que tudo permanece fixo, mas que há regulação em torno de valores ideais. Perceba também que as questões costumam pedir a relação entre um dado experimental e uma propriedade da vida, como a resposta a estímulos.',
  'Para a revisão, faça uma lista curta: organização celular, metabolismo, reprodução, hereditariedade, crescimento, homeostase, resposta a estímulos e evolução. Associe cada item a um exemplo cotidiano e a um tema que será estudado em seguida, como a célula (Citologia), a produção de energia (metabolismo energético), o DNA (genética) e a seleção natural (evolução). Esse tema serve como mapa da matéria, e a boa compreensão dele facilita o estudo de todos os demais.'] }
]},
{ t:'Citologia: a célula', txt:[
 { h:'Células procariontes e eucariontes', p:[
  'A **Citologia** é o ramo da Biologia que estuda as células. Existem dois tipos fundamentais: as **procariontes**, mais simples e antigas, e as **eucariontes**, mais complexas. Nas procariontes, que formam as bactérias e as arqueas, o material genético fica disperso no citoplasma, em uma região chamada de nucleoide, sem envoltório nuclear, e não há organelas membranosas. Nas eucariontes, que formam protozoários, algas, fungos, plantas e animais, o DNA fica protegido pelo **núcleo** e há organelas delimitadas por membranas.',
  'As células procariontes, em geral, são menores (de 1 a 10 micrômetros) do que as eucariontes (de 10 a 100 micrômetros). Possuem membrana plasmática, parede celular (na maioria), ribossomos, que são as organelas responsáveis pela síntese de proteínas, e um cromossomo circular único. Muitas têm também flagelos, para locomoção, e plasmídios, pequenos fragmentos circulares de DNA que podem conferir, por exemplo, resistência a antibióticos e que são usados na engenharia genética.',
  'A origem das células eucariontes é explicada pela **teoria endossimbiótica**: as mitocôndrias e os cloroplastos teriam surgido de bactérias que foram englobadas por uma célula maior e passaram a viver em simbiose com ela. As evidências incluem o fato de essas organelas terem DNA próprio, circular como o das bactérias, ribossomos semelhantes aos bacterianos, dupla membrana e capacidade de se dividir de maneira independente. É um dos exemplos mais claros de como a cooperação também é uma força evolutiva.'] },
 { h:'Organelas e suas funções', p:[
  'A **membrana plasmática** envolve a célula e controla a entrada e a saída de substâncias. O **citoplasma** é o espaço entre a membrana e o núcleo, preenchido por uma solução aquosa, o citosol, e pelas organelas. O **núcleo** guarda o DNA, em cromossomos, e comanda as atividades da célula; ele é envolvido pela carioteca e contém o nucléolo, onde são produzidos os ribossomos. Os **ribossomos** fazem a síntese de proteínas e ficam soltos no citoplasma ou aderidos ao retículo endoplasmático.',
  'O **retículo endoplasmático rugoso** possui ribossomos e participa da produção e do transporte de proteínas, enquanto o **liso**, sem ribossomos, produz lipídios e esteroides e atua na desintoxicação, como nas células do fígado. O **complexo golgiense** modifica, empacota e envia as proteínas para seu destino, e forma os lisossomos. Os **lisossomos** contêm enzimas digestivas e realizam a digestão intracelular, quebrando partículas e organelas velhas. Os **peroxissomos** degradam substâncias como a água oxigenada, que é tóxica.',
  'As **mitocôndrias** são as organelas da respiração celular, em que a glicose é oxidada e se produz a maior parte do ATP. São mais abundantes em células com muita demanda de energia, como as musculares. Os **cloroplastos**, presentes nas plantas e nas algas, realizam a fotossíntese, pois contêm clorofila. O **vacúolo** das plantas armazena água e substâncias e ajuda a manter a pressão interna. O **citoesqueleto**, uma rede de filamentos de proteínas, dá forma à célula, permite seu movimento e sustenta o transporte de organelas, e os **centríolos** participam da divisão celular em animais.'] },
 { h:'Célula animal, célula vegetal e outras diferenças', p:[
  'Embora ambas sejam eucariontes, as células vegetais e animais apresentam diferenças. As **células vegetais** possuem **parede celular** de celulose, que dá sustentação e proteção, **cloroplastos** e um grande **vacúolo central**. As **células animais** não têm parede celular, cloroplastos nem vacúolo central, e têm **centríolos**, que as vegetais, em geral, não possuem. Ambas têm membrana plasmática, núcleo, mitocôndrias, retículos, complexo golgiense e ribossomos, e por isso as duas realizam respiração celular, ainda que apenas as vegetais façam fotossíntese.',
  'Os **fungos** também têm parede celular, mas ela é feita de **quitina**, o mesmo material do exoesqueleto dos artrópodes, e não de celulose. As **bactérias** possuem parede de peptideoglicano, característica que explica por que os antibióticos como a penicilina, que impedem a formação dessa parede, afetam as bactérias, mas não as células humanas. Esse tipo de relação entre estrutura celular e ação de medicamentos é bastante utilizado em questões, pois exige raciocínio, e não só memorização.',
  'A forma das células é adequada à sua função. As hemácias são discos bicôncavos sem núcleo, que aumentam a superfície para transportar oxigênio. Os neurônios têm prolongamentos longos para conduzir impulsos nervosos. As células musculares são alongadas e ricas em mitocôndrias. As células do intestino têm microvilosidades, que aumentam a superfície de absorção. Essa relação entre forma e função é um princípio central da Biologia, e aparece da escala da célula à do organismo.'] },
 { h:'Núcleo, cromossomos e o ciclo da célula', p:[
  'O **núcleo** contém o DNA, associado a proteínas chamadas **histonas**, formando a **cromatina**. Quando a célula vai se dividir, a cromatina se condensa e forma os **cromossomos**, visíveis ao microscópio. Cada espécie tem um número característico de cromossomos: a humana tem 46, em 23 pares, sendo 22 pares de autossomos e 1 par de cromossomos sexuais (XX nas mulheres e XY nos homens). Células com dois conjuntos de cromossomos são **diploides** (2n), e os gametas, com apenas um conjunto, são **haploides** (n).',
  'O **ciclo celular** é a sequência de eventos pela qual uma célula cresce, duplica seu DNA e se divide. É formado pela **interfase**, em que a célula cresce e o DNA é duplicado (fases G1, S e G2), e pela **divisão**, na qual ocorrem a mitose e a citocinese. A maior parte da vida da célula ocorre em interfase. O controle do ciclo é feito por proteínas que funcionam como "pontos de checagem", e quando eles falham, as células podem se multiplicar sem controle, o que está na origem do câncer.',
  'O **DNA** é a molécula que guarda a informação genética e sua estrutura é a de uma dupla hélice, formada por nucleotídeos com as bases A, T, C e G. A cada divisão, ele é copiado de modo semiconservativo, de maneira que cada nova molécula guarda uma fita antiga e uma nova. Esse processo será estudado com mais detalhe nos temas de ácidos nucleicos e divisão celular. Por ora, vale lembrar que a célula é a unidade que armazena, copia e lê o DNA, e que suas organelas atuam de modo coordenado.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em Citologia, o ENEM prefere questões que relacionam a estrutura da célula com a sua função ou com situações do cotidiano. Exemplos: por que as células musculares têm muitas mitocôndrias; por que certos antibióticos atuam apenas em bactérias; qual organela está relacionada a doenças de armazenamento; como a quebra de células explica a liberação de uma substância; ou como o experimento de um cientista com uma célula revela a função de uma organela. A leitura de esquemas e imagens é frequente.',
  'Alguns pontos merecem atenção: a diferença entre procariontes e eucariontes (presença de núcleo e de organelas membranosas); as diferenças entre célula animal e vegetal (parede, cloroplastos e vacúolo); a função de cada organela; e a teoria endossimbiótica. Um erro comum é achar que toda célula tem núcleo (as hemácias maduras não têm) e que o DNA existe apenas no núcleo (também está nas mitocôndrias e nos cloroplastos).',
  'Para revisar, associe cada organela a uma "profissão": núcleo é o escritório central, ribossomo é a fábrica de proteínas, retículo é a rede de transporte, golgi é o correio, lisossomo é a reciclagem, mitocôndria é a usina de energia e cloroplasto é a cozinha que produz alimento a partir da luz. Esse tipo de analogia ajuda na memorização. Em seguida, estude a membrana e o transporte celular, que explicam como a célula se relaciona com o meio.'] }
]},
{ t:'Membrana e transporte celular', txt:[
 { h:'Estrutura da membrana plasmática: o modelo do mosaico fluido', p:[
  'A **membrana plasmática** é uma película muito fina que envolve todas as células, separando o meio interno do externo e controlando as trocas entre eles. Ela é seletiva: deixa passar certas substâncias e barra outras. Esse comportamento é chamado de **permeabilidade seletiva**. A estrutura é descrita pelo **modelo do mosaico fluido**, segundo o qual a membrana é formada por uma dupla camada de lipídios, a **bicamada lipídica**, na qual estão inseridas proteínas, que se movem lateralmente, como em um mosaico em constante movimento.',
  'Os principais lipídios da membrana são os **fosfolipídios**, moléculas com uma "cabeça" **hidrofílica** (que tem afinidade pela água) e duas "caudas" **hidrofóbicas** (que repelem a água). Em meio aquoso, eles se organizam em duas camadas, com as cabeças voltadas para fora, em contato com a água do meio e do citoplasma, e as caudas voltadas para dentro, protegidas da água. O **colesterol** é encontrado em membranas de células animais e regula a fluidez. As **proteínas** podem atravessar a bicamada ou ficar na superfície, e funcionam como canais, transportadores, receptores e enzimas.',
  'Na face externa, muitas membranas têm cadeias de carboidratos ligadas a proteínas ou a lipídios, formando o **glicocálix**. Ele atua na proteção, no reconhecimento entre células e na adesão. Por exemplo, os grupos sanguíneos A, B e O são determinados por carboidratos do glicocálix das hemácias, e o reconhecimento de células estranhas pelo sistema imunológico depende de marcadores na membrana. Nas plantas e em outros organismos, a membrana é revestida externamente pela parede celular, que protege, mas não regula as trocas.'] },
 { h:'Transporte passivo: difusão simples, facilitada e osmose', p:[
  'O **transporte passivo** ocorre **sem gasto de energia** (ATP), a favor de um gradiente de concentração, isto é, do meio mais concentrado para o menos concentrado. A **difusão simples** é a passagem direta de pequenas moléculas apolares ou sem carga, como o oxigênio, o gás carbônico e o álcool, pela bicamada lipídica. Quanto maior a diferença de concentração, mais rápida é a difusão. É assim que o oxigênio entra nas células e o CO2 sai, o que sustenta a respiração celular.',
  'Na **difusão facilitada**, moléculas que não atravessam bem a bicamada, como a glicose, os aminoácidos e os íons, passam por **proteínas transportadoras** ou **canais** da membrana, também a favor do gradiente e sem gasto de energia. A velocidade tem um limite, pois depende do número de proteínas disponíveis, e quando todas estão ocupadas, atinge um ponto de saturação. As **aquaporinas** são canais específicos para a água e estão presentes, por exemplo, nas células dos rins, que reabsorvem água.',
  'A **osmose** é a difusão da **água** por uma membrana semipermeável, do meio **hipotônico** (menos concentrado em solutos) para o **hipertônico** (mais concentrado). Em um meio isotônico, não há movimento líquido. Hemácias colocadas em água pura (hipotônica) absorvem água e podem estourar (hemólise); em meio hipertônico, perdem água e murcham (crenação). As células vegetais, por terem parede celular, não estouram em meio hipotônico, mas ficam **túrgidas**; em meio hipertônico, a membrana se solta da parede, e a célula sofre **plasmólise**.'] },
 { h:'Transporte ativo e transporte em massa', p:[
  'No **transporte ativo**, a célula move substâncias **contra o gradiente de concentração**, ou seja, do meio menos concentrado para o mais concentrado, e para isso **gasta energia** na forma de ATP. Um exemplo importante é a **bomba de sódio e potássio** (Na+/K+), uma proteína que expulsa três íons sódio da célula e leva dois íons potássio para dentro, mantendo as concentrações diferentes entre os dois lados. Essa diferença é essencial para a condução dos impulsos nervosos e para a contração dos músculos.',
  'Esse tipo de transporte consome grande parte da energia da célula, e explica por que células muito ativas, como as dos rins e as nervosas, têm muitas mitocôndrias. A absorção de nutrientes no intestino, a reabsorção de glicose nos rins e a absorção de sais minerais pelas raízes das plantas também envolvem transporte ativo. Um veneno que inibe a produção de ATP, como o cianeto, bloqueia o transporte ativo e, em consequência, inviabiliza o funcionamento das células, o que ajuda a entender sua toxicidade.',
  'Moléculas grandes, como proteínas e partículas, são transportadas em bolsas de membrana, em um processo chamado de **transporte em massa**, que também gasta energia. Na **endocitose**, a célula engloba material do meio: na **fagocitose**, partículas sólidas, como bactérias, são "engolidas" por meio de pseudópodes, como fazem os glóbulos brancos; na **pinocitose**, gotas de líquido são englobadas. Na **exocitose**, vesículas se fundem à membrana e liberam seu conteúdo para fora, como na secreção de hormônios e de enzimas digestivas.'] },
 { h:'Comunicação celular, junções e aplicações', p:[
  'A membrana também tem função de **comunicação**. Na superfície das células existem **receptores**, geralmente proteínas, que reconhecem moléculas sinalizadoras, como hormônios e neurotransmissores, e desencadeiam respostas no interior da célula. A insulina, por exemplo, liga-se a receptores nas células do corpo e promove a entrada de glicose; no diabetes, esse processo é falho. Muitos medicamentos agem imitando ou bloqueando a ligação com receptores, e vários venenos e toxinas também têm esse mecanismo.',
  'As células de um tecido podem estar unidas por **junções celulares**. As **junções de oclusão** (tight junctions) vedam o espaço entre células, como nas paredes do intestino, impedindo a passagem de substâncias entre elas; os **desmossomos** fixam as células umas às outras, dando resistência mecânica, como na pele; e as **junções comunicantes** (gap) formam pequenos canais que permitem a passagem de íons e moléculas pequenas entre células vizinhas, como no músculo cardíaco, em que coordenam a contração.',
  'Esses conhecimentos têm aplicações. A **fibrose cística** é causada por defeito em um canal de cloreto da membrana, que provoca muco espesso. A **diarreia por cólera** envolve uma toxina que abre canais de íons, levando à perda intensa de água por osmose. A **desidratação** e o uso de **soro caseiro**, que tem sal e açúcar, ligam-se à absorção de sódio e glicose juntos, por transporte facilitado. O uso de sal em conservação de alimentos remove água dos microrganismos por osmose. Em todos os casos, a explicação passa pela membrana.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a membrana e o transporte aparecem em situações como conservação de alimentos com sal ou açúcar, murchamento de verduras temperadas, desidratação, soro fisiológico e caseiro, hemólise, absorção de nutrientes e doenças ligadas a falhas de transporte. A questão pede, em geral, que você identifique o tipo de transporte envolvido, considerando se há gasto de energia e a direção do movimento em relação à concentração.',
  'Uma rotina de análise ajuda: 1) A substância se move a favor ou contra o gradiente? 2) Há gasto de ATP? 3) A molécula é pequena e apolar, ou grande e polar? 4) Há proteínas envolvidas? Se for a favor do gradiente e sem energia, é transporte passivo (difusão simples, facilitada ou osmose); se for contra o gradiente e com energia, é ativo; se envolve vesículas, é transporte em massa. Lembre-se de que a osmose se refere à água e que o sentido é do meio hipotônico para o hipertônico.',
  'Para revisar: a membrana é um mosaico fluido de fosfolipídios e proteínas, com permeabilidade seletiva; difusão simples e facilitada são passivas; a osmose é a passagem da água; o transporte ativo gasta ATP e vai contra o gradiente; a endocitose e a exocitose movimentam partículas grandes. Conecte esse tema ao de metabolismo energético, que explica como a célula produz o ATP que sustenta o transporte ativo e outras atividades.'] }
]}
];
