/* Biologia: textos corridos, temas 7 a 9 */
module.exports = [
{ t:'Genética: leis de Mendel', txt:[
 { h:'Conceitos básicos da Genética', p:[
  'A **Genética** estuda a transmissão das características hereditárias de uma geração a outra. Seu fundador foi Gregor Mendel, um monge austríaco que, a partir de 1856, cruzou milhares de pés de ervilha-de-cheiro e analisou os resultados com métodos estatísticos. Seus trabalhos, publicados em 1866, só foram reconhecidos no início do século XX. Mendel escolheu a ervilha por ser fácil de cultivar, ter ciclo curto, produzir muitas sementes e apresentar características bem contrastantes, como sementes lisas ou rugosas, amarelas ou verdes.',
  'Alguns termos são indispensáveis. **Gene** é o trecho do DNA que determina uma característica; **alelos** são as diferentes formas de um mesmo gene; **genótipo** é o conjunto de alelos que um indivíduo possui, e **fenótipo** é a característica observável, resultante do genótipo e da influência do ambiente. Um indivíduo é **homozigoto** quando tem dois alelos iguais (AA ou aa) e **heterozigoto** quando tem alelos diferentes (Aa). O alelo **dominante**, em letra maiúscula, manifesta-se mesmo em dose única, e o **recessivo**, em letra minúscula, só se manifesta em homozigose.',
  'Para organizar os cruzamentos, usa-se a notação P (geração parental), F1 (primeira geração filial, filhos do cruzamento de P) e F2 (segunda geração, filhos do cruzamento entre indivíduos de F1). O **quadro de Punnett** é uma tabela que mostra todas as combinações possíveis de gametas de dois pais, e permite calcular as proporções genotípicas e fenotípicas esperadas. O uso desse quadro, ou de um raciocínio equivalente com probabilidades, é essencial para resolver questões de Genética, principalmente as que pedem a probabilidade de um descendente com certa característica.'] },
 { h:'A primeira lei de Mendel: lei da segregação', p:[
  'Mendel cruzou plantas de ervilha de linhagem pura de sementes amarelas com plantas de sementes verdes. Todos os descendentes da geração F1 tinham sementes amarelas, e a cor verde parecia desaparecer. Ao cruzar entre si os indivíduos de F1, a cor verde reapareceu na geração F2, na proporção de **3 amarelas para 1 verde**. Ele concluiu que a característica "verde" não havia sumido: estava presente, mas escondida pela "amarela", que é dominante.',
  'A **primeira lei de Mendel**, ou lei da **segregação dos fatores**, afirma que cada característica é determinada por **um par de fatores** (hoje chamados de alelos), que se separam durante a formação dos gametas, de modo que cada gameta recebe apenas um deles. Assim, um indivíduo Aa produz 50% de gametas A e 50% de gametas a. No cruzamento Aa × Aa, a F2 tem 25% AA, 50% Aa e 25% aa, o que corresponde à proporção genotípica 1:2:1 e à fenotípica 3:1 (três com a característica dominante para um com a recessiva).',
  'O **cruzamento-teste** (ou retrocruzamento) serve para descobrir se um indivíduo de fenótipo dominante é homozigoto (AA) ou heterozigoto (Aa): cruza-se esse indivíduo com um homozigoto recessivo (aa). Se todos os descendentes têm o fenótipo dominante, o indivíduo testado é AA; se houver descendentes com o fenótipo recessivo (proporção 1:1), ele é Aa. Esse raciocínio é usado na criação de animais e plantas, para selecionar linhagens puras, e aparece em questões de probabilidade em heredogramas.'] },
 { h:'A segunda lei de Mendel e a probabilidade', p:[
  'Em seguida, Mendel analisou duas características ao mesmo tempo, como a cor (amarela ou verde) e a textura (lisa ou rugosa) das sementes. Cruzando linhagens puras de sementes amarelas e lisas (VVRR) com verdes e rugosas (vvrr), obteve uma F1 toda amarela e lisa (VvRr). No cruzamento entre os indivíduos de F1, a F2 apresentou quatro fenótipos, na proporção de **9:3:3:1**: 9 amarelas e lisas, 3 amarelas e rugosas, 3 verdes e lisas e 1 verde e rugosa.',
  'A **segunda lei de Mendel**, ou lei da **segregação independente**, afirma que os pares de alelos de genes diferentes se separam de modo independente na formação dos gametas, desde que os genes estejam em **cromossomos diferentes** (ou muito distantes no mesmo cromossomo). Um indivíduo VvRr produz quatro tipos de gametas em proporções iguais: VR, Vr, vR e vr, cada um com 25%. Essa lei é explicada pelo comportamento dos cromossomos na meiose, e hoje se sabe que ela não vale para genes **ligados** (muito próximos no mesmo cromossomo), que tendem a ser herdados juntos.',
  'Para resolver problemas de duas ou mais características, é prático usar a **regra do "e" e do "ou"** da probabilidade: a probabilidade de dois eventos independentes ocorrerem juntos é o **produto** das probabilidades de cada um (regra do "e"), e a de um ou outro evento mutuamente exclusivo é a **soma** (regra do "ou"). Por exemplo, a probabilidade de um filho de dois heterozigotos Aa ser aa é 1/4. Se os pais são AaBb, a probabilidade de aabb é 1/4 × 1/4 = 1/16. Essa técnica dispensa o quadro de Punnett e é muito mais rápida.'] },
 { h:'Heredogramas, dominância incompleta e codominância', p:[
  'O **heredograma** (ou genealogia) é um diagrama que representa as relações de parentesco e a ocorrência de uma característica em uma família. Os homens são representados por quadrados e as mulheres por círculos, e os indivíduos que apresentam a característica, geralmente em preto. Para interpretá-lo, é preciso descobrir se a herança é dominante ou recessiva e determinar os genótipos. Uma regra útil: se **dois pais sem a característica têm um filho que a apresenta**, a característica é **recessiva**, e ambos os pais são heterozigotos.',
  'Nem toda herança segue a dominância completa. Na **dominância incompleta** (ou herança intermediária), o heterozigoto apresenta um fenótipo **intermediário** entre os dois homozigotos, como a flor-maravilha, em que o cruzamento de plantas vermelhas (VV) com brancas (BB) gera plantas rosas (VB), e a proporção em F2 é 1:2:1 tanto para genótipos quanto para fenótipos. Na **codominância**, os dois alelos se expressam por completo no heterozigoto, como no grupo sanguíneo AB, em que as hemácias apresentam os dois tipos de antígeno.',
  'Há ainda genes **letais**, que causam a morte do indivíduo, em geral em homozigose, alterando as proporções esperadas (por exemplo, 2:1 em vez de 3:1); a **pleiotropia**, em que um gene afeta várias características, como no gene da anemia falciforme; e a **herança quantitativa** (poligênica), em que vários genes somam seus efeitos e produzem variações graduais, como a cor da pele e a altura. O ambiente também influencia o fenótipo: a mesma pessoa pode ter cor de pele diferente conforme a exposição ao sol, e a hortênsia muda de cor conforme o pH do solo.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'As Leis de Mendel são um dos temas mais frequentes de Biologia no ENEM. As questões costumam apresentar um cruzamento, um heredograma ou uma situação familiar (doenças genéticas, características físicas, criação de animais ou plantas) e pedir a probabilidade de um descendente ter determinado genótipo ou fenótipo. Quase sempre, a resolução envolve identificar o tipo de herança e aplicar o raciocínio de probabilidade, com frações simples.',
  'Dicas práticas: anote os genótipos possíveis de cada indivíduo; comece pelos indivíduos com fenótipo recessivo, cujo genótipo é conhecido (aa); lembre que pais normais com um filho afetado são portadores de um alelo recessivo; use 1/4 para um filho de heterozigotos com o fenótipo recessivo, 3/4 para o dominante e 2/3 para a probabilidade de um filho normal ser heterozigoto. Preste atenção à pergunta: ela pede a probabilidade de um filho "do sexo masculino"? De "uma criança afetada" ou de "a próxima criança"?',
  'Revisão: alelos dominantes se expressam em dose única e recessivos só em homozigose; a primeira lei trata da separação dos alelos em gametas; a segunda lei trata da segregação independente de genes em cromossomos diferentes; o cruzamento Aa × Aa dá 3:1; o cruzamento duplo-híbrido dá 9:3:3:1; dominância incompleta e codominância são exceções à dominância completa. O próximo tema amplia o estudo para grupos sanguíneos e herança ligada ao sexo, que são casos particulares dessas leis.'] }
]},
{ t:'Genética: grupos sanguíneos e herança ligada ao sexo', txt:[
 { h:'Sistema ABO: alelos múltiplos', p:[
  'Os **grupos sanguíneos do sistema ABO** são determinados pela presença ou ausência de dois antígenos (aglutinogênios), A e B, na superfície das hemácias. No plasma, existem anticorpos (aglutininas) contra os antígenos que a pessoa não tem. Esse é um caso de **alelos múltiplos** (polialelia): existem três alelos para o mesmo gene, **IA, IB e i**, mas cada pessoa tem apenas dois deles. Os alelos IA e IB são **codominantes** entre si e ambos são dominantes sobre o alelo **i**, que é recessivo.',
  'Os fenótipos e genótipos possíveis são: **grupo A**, com genótipos IAIA ou IAi, antígeno A nas hemácias e anticorpo anti-B no plasma; **grupo B**, com genótipos IBIB ou IBi, antígeno B e anticorpo anti-A; **grupo AB**, genótipo IAIB, com antígenos A e B e nenhum anticorpo; e **grupo O**, genótipo ii, sem antígenos e com os dois anticorpos, anti-A e anti-B. Assim, quatro fenótipos resultam de seis genótipos. O grupo O é o mais comum, em muitas populações, e o AB é o mais raro.',
  'Esse sistema é fundamental para as **transfusões de sangue**. Se um receptor recebe sangue com um antígeno que não possui, seus anticorpos o reconhecem e provocam a aglutinação das hemácias doadas, o que pode causar a morte. Por isso o grupo **O** é chamado de "doador universal" (as hemácias não têm antígenos), e o grupo **AB**, de "receptor universal" (não tem anticorpos no plasma). Na prática, a compatibilidade é testada com rigor, pois há outros sistemas. O sistema ABO é também usado em investigações de paternidade para excluir possíveis pais.'] },
 { h:'Sistema Rh e a doença hemolítica do recém-nascido', p:[
  'O **sistema Rh** é outro sistema de grupos sanguíneos, que depende da presença do fator Rh (antígeno D) nas hemácias. Quem tem o fator é **Rh positivo** (Rh+), com genótipo DD ou Dd, e quem não o tem é **Rh negativo** (Rh-), com genótipo dd. A herança é simples, com dominância do alelo para a presença do fator. Ao contrário do sistema ABO, as pessoas Rh- não possuem anticorpos anti-Rh desde o nascimento: elas só os produzem depois de serem expostas ao sangue Rh+, em um processo de **sensibilização**.',
  'Isso é importante na gestação. Se uma mulher Rh- engravida de um homem Rh+ e o bebê é Rh+, durante o parto, uma pequena quantidade de sangue do bebê pode passar para a circulação materna e sensibilizá-la, levando-a a produzir anticorpos anti-Rh. Na primeira gestação, em geral, não há problemas, mas, em uma **segunda gestação** com um bebê Rh+, os anticorpos maternos atravessam a placenta e destroem as hemácias do feto, causando a **eritroblastose fetal** (doença hemolítica do recém-nascido), que pode levar a anemia grave e até à morte.',
  'A prevenção é feita com a aplicação de **imunoglobulina anti-Rh** na mãe Rh-, nas primeiras 72 horas após o parto de um bebê Rh+, que destrói as hemácias fetais antes que o sistema imunológico da mãe as reconheça. Assim, evita-se a sensibilização. O acompanhamento pré-natal inclui a tipagem sanguínea da gestante e, quando necessário, do pai. Esse caso é um clássico para explicar, de forma aplicada, a interação entre genética e imunologia, e costuma ser cobrado em questões de contexto de saúde.'] },
 { h:'Herança ligada ao sexo: cromossomos X e Y', p:[
  'Os seres humanos têm 23 pares de cromossomos: 22 pares de **autossomos** e 1 par de **cromossomos sexuais**, XX nas mulheres e XY nos homens. O cromossomo X é grande e carrega muitos genes que não têm correspondentes no Y, que é bem menor. Por isso, os homens são **hemizigotos** para os genes do X, ou seja, têm apenas um alelo, e a característica codificada por ele se manifesta mesmo que seja recessiva. Já as mulheres têm dois alelos, como nos autossomos. O sexo do filho é definido pelo espermatozoide, que pode levar X ou Y.',
  'As doenças causadas por **alelos recessivos ligados ao X** são mais frequentes nos homens. Os exemplos mais conhecidos são o **daltonismo** (dificuldade de distinguir cores, especialmente verde e vermelho) e a **hemofilia** (deficiência na coagulação do sangue). Um homem afetado (XdY ou XhY) herda o alelo da mãe e o transmite às filhas, que serão portadoras, mas nunca aos filhos homens, pois a eles passa o Y. Uma mulher só é afetada se for homozigota recessiva, e para isso o pai deve ser afetado e a mãe, ao menos portadora.',
  'A herança ligada ao X recessiva tem padrões característicos nos heredogramas: há mais homens afetados do que mulheres; a característica "pula" gerações, passando por mulheres portadoras; e um pai afetado não transmite a doença a filhos homens. Em cruzamentos, uma mulher portadora (XDXd) com um homem normal (XDY) tem 50% de probabilidade de ter filhos homens afetados e 0% de ter filhas afetadas, embora metade das filhas seja portadora. É preciso prestar atenção à pergunta: a probabilidade pode ser sobre "um filho homem afetado" ou sobre "uma criança afetada".'] },
 { h:'Outros tipos de herança ligada ao sexo e genes holândricos', p:[
  'Existem também características determinadas por genes **dominantes ligados ao X**, em que a característica se manifesta em homens e mulheres, mas é mais comum nas mulheres (que têm duas chances de herdar o alelo). Um pai afetado transmite a todas as filhas, mas a nenhum filho homem. Um exemplo raro é o raquitismo resistente à vitamina D. Os genes **holândricos** localizam-se na região do cromossomo Y sem correspondente no X, e passam apenas de pai para filho, como ocorre com a hipertricose das orelhas.',
  'A herança **influenciada pelo sexo** é diferente: os genes estão em autossomos, mas sua expressão depende do sexo, por efeito de hormônios. A calvície é um exemplo, pois o mesmo genótipo pode se expressar em homens, mas não em mulheres. Já a herança **limitada pelo sexo** ocorre quando a característica só aparece em um dos sexos, como a produção de leite, que depende de genes presentes em ambos os sexos, mas só expressos em fêmeas. Essas distinções são raras em provas, mas ajudam a compreender que sexo e herança se relacionam de maneiras variadas.',
  'Nas mulheres, uma das duas cópias do cromossomo X é **inativada** em cada célula, no início do desenvolvimento embrionário, de modo aleatório, e forma uma estrutura chamada de **corpúsculo de Barr**. Assim, homens e mulheres têm a mesma "dose" de genes do X ativos. A inativação aleatória explica por que as mulheres portadoras de alelos recessivos de doenças ligadas ao X podem ter sintomas leves, como as gatas de pelagem tricolor, cujos manchados resultam da inativação de cópias diferentes do X em regiões diferentes da pele.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em grupos sanguíneos e herança ligada ao sexo, o ENEM costuma apresentar situações de paternidade, transfusão, gestação com incompatibilidade Rh e heredogramas de doenças como a hemofilia e o daltonismo. As questões pedem a probabilidade de um filho ter certo genótipo ou fenótipo, a compatibilidade entre doador e receptor, ou a interpretação de um heredograma. É comum combinar dois sistemas em uma só questão, como ABO e Rh.',
  'Dicas: no sistema ABO, monte uma tabela com antígenos e anticorpos de cada tipo, e verifique se o receptor possui anticorpos contra os antígenos do doador; em testes de paternidade, o ABO só pode **excluir** a paternidade, e nunca confirmá-la; na herança ligada ao X, represente os genótipos com o cromossomo (XDXd, XdY) e lembre que o filho homem recebe o X da mãe. Se o enunciado fornece o heredograma, comece procurando um homem afetado e descubra de quem ele herdou o alelo.',
  'Para revisar: o sistema ABO tem três alelos (IA, IB, i), com codominância entre IA e IB; o grupo O é doador universal e o AB é receptor universal; o fator Rh é determinado pelo alelo D, e a eritroblastose fetal ocorre em segunda gestação de mãe Rh- com bebê Rh+; o daltonismo e a hemofilia são recessivos ligados ao X, e afetam mais os homens. Esse tema fecha a parte de Genética clássica, e o próximo, de Biotecnologia, aplica o conhecimento do DNA à tecnologia.'] }
]},
{ t:'Biotecnologia', txt:[
 { h:'O que é biotecnologia e as técnicas de manipulação do DNA', p:[
  'A **biotecnologia** é o conjunto de técnicas que usam seres vivos, ou partes deles, para produzir bens e serviços. Ela existe desde a Antiguidade, na fabricação de pão, vinho, queijo e cerveja, por meio da fermentação, mas ganhou novas possibilidades com a **engenharia genética**, que permite modificar diretamente o DNA. A partir da década de 1970, com a descoberta das **enzimas de restrição**, foi possível cortar o DNA em pontos específicos e unir fragmentos de origens diferentes, formando o chamado **DNA recombinante**.',
  'As **enzimas de restrição** funcionam como "tesouras moleculares": reconhecem sequências específicas de bases e cortam o DNA naquele ponto. Outra enzima, a **DNA ligase**, une os fragmentos como uma "cola". Para introduzir o gene de interesse em uma célula, usam-se **vetores**, como os plasmídios bacterianos e certos vírus. Esse é o princípio da produção de **insulina humana** por bactérias: o gene humano da insulina é inserido em um plasmídio, que é colocado em uma bactéria, e a bactéria passa a produzir a proteína, em grande escala, para tratar o diabetes.',
  'Outras técnicas importantes incluem a **PCR** (reação em cadeia da polimerase), que copia milhões de vezes um fragmento de DNA a partir de uma pequena amostra, e a **eletroforese em gel**, que separa fragmentos de DNA por tamanho, pois os menores migram mais depressa. Combinando-as, é possível obter o "perfil" de DNA de uma pessoa. O **sequenciamento** do DNA lê a ordem das bases, e o Projeto Genoma Humano, concluído em 2003, determinou a sequência do genoma humano, aberto o caminho para a medicina genômica.'] },
 { h:'Organismos transgênicos e aplicações na agricultura', p:[
  'Um organismo **transgênico** (ou geneticamente modificado, OGM) é aquele que recebeu um gene de outra espécie por técnicas de engenharia genética. Na agricultura, existem plantas com genes que conferem resistência a insetos (como o milho Bt, que produz uma proteína tóxica a certas pragas, derivada da bactéria Bacillus thuringiensis), tolerância a herbicidas (como a soja resistente ao glifosato) ou maior valor nutricional (como o "arroz dourado", com precursor da vitamina A). Esses cultivos podem aumentar a produtividade e reduzir o uso de alguns defensivos.',
  'Os transgênicos também levantam debates. Entre os **benefícios** citados estão o aumento da produtividade, a redução de perdas, o menor uso de inseticidas e a possibilidade de alimentos mais nutritivos. Entre as **preocupações** estão os possíveis impactos ambientais (como a transferência dos genes para plantas selvagens e o surgimento de pragas resistentes), os efeitos sobre a biodiversidade, a concentração de sementes em poucas empresas e as dúvidas de parte da população sobre a segurança alimentar. No Brasil, a liberação depende de avaliação da CTNBio, e os produtos devem trazer rotulagem específica.',
  'Há, ainda, outras aplicações. Na pecuária, animais podem ser modificados para produzir proteínas medicinais no leite. Na indústria, microrganismos geneticamente modificados produzem enzimas para detergentes, biocombustíveis e fármacos. Na medicina, já se produzem hormônio do crescimento, vacinas, fatores de coagulação e anticorpos monoclonais por técnicas de DNA recombinante. Em todos os casos, o ENEM tende a pedir que se avaliem benefícios e riscos de forma equilibrada, argumentando com base em conhecimentos científicos e considerando aspectos éticos e sociais.'] },
 { h:'Clonagem, células-tronco e terapia gênica', p:[
  'A **clonagem** é a produção de indivíduos geneticamente idênticos. Na natureza, ocorre na reprodução assexuada, nos gêmeos idênticos (monozigóticos) e na propagação vegetativa. A **clonagem reprodutiva** de animais, como a da ovelha Dolly, nascida em 1996, utiliza a **transferência nuclear**: o núcleo de uma célula somática do animal a ser clonado é inserido em um óvulo cujo núcleo foi retirado, e o embrião resultante é implantado em uma fêmea. Dolly mostrou que uma célula adulta pode ser "reprogramada", mas a técnica tem baixa eficiência e levanta questões éticas, principalmente se aplicada a humanos.',
  'As **células-tronco** são células indiferenciadas que se multiplicam e podem se diferenciar em diversos tipos celulares. As **embrionárias**, obtidas de embriões em fase inicial, são **pluripotentes**, e as **adultas**, presentes na medula óssea e em outros tecidos, têm potencial mais restrito. As células-tronco induzidas (iPS), obtidas pela reprogramação de células adultas, evitam o uso de embriões. Elas têm potencial em terapias de reposição de tecidos, como na lesão medular, no diabetes e em doenças degenerativas. O transplante de medula óssea, usado em leucemias, é a aplicação já estabelecida.',
  'A **terapia gênica** consiste em inserir genes normais em células de pacientes com doenças genéticas, usando, em geral, vírus modificados como vetores. Já foi aplicada em casos de imunodeficiências e de certas doenças hereditárias, com resultados promissores, mas há riscos. A edição de genomas, com a técnica **CRISPR-Cas9**, que permite cortar e alterar trechos de DNA com precisão, abriu novas possibilidades e debates éticos, principalmente em relação à edição de embriões humanos. O ENEM costuma contextualizar essas técnicas para avaliar a capacidade de argumentação sobre ciência e sociedade.'] },
 { h:'Identificação genética, testes de DNA e bioética', p:[
  'Cada pessoa tem um padrão único de sequências repetitivas de DNA, exceto os gêmeos idênticos. Por isso, o **perfil de DNA** (a "impressão digital genética") é usado na **identificação de pessoas**: no teste de paternidade, o filho herda metade do DNA de cada genitor, e o perfil do suposto pai deve coincidir com as bandas que o filho não herdou da mãe; na **medicina legal**, o DNA de cabelos, sangue ou saliva encontrados em uma cena de crime pode ser comparado ao de suspeitos; e na identificação de vítimas de desastres e de desaparecidos. O teste é muito preciso, com probabilidade de acerto superior a 99,99%.',
  'Os testes genéticos também permitem identificar predisposição a doenças, portadores de alelos de doenças recessivas e a compatibilidade de doadores de órgãos e de medula. Na agricultura, o DNA é usado para identificar variedades, e na ecologia, para monitorar o tráfico de animais silvestres e estudar populações. Os **bancos de DNA** podem armazenar informação sensível, o que traz questões de privacidade: quem deve ter acesso aos dados genéticos de uma pessoa, e como evitar discriminação por empregadores ou seguradoras?',
  'A **bioética** é o campo que discute os limites éticos da pesquisa e das aplicações biotecnológicas. As principais questões envolvem o uso de embriões em pesquisas, a clonagem humana (proibida em diversos países, inclusive no Brasil), a edição de genes em células germinativas, o patenteamento da vida, a segurança dos alimentos transgênicos e o acesso justo às tecnologias de saúde. O ENEM não exige uma posição, mas sim a capacidade de reconhecer valores em conflito e de fundamentar argumentos com base em conhecimento científico, o que se conecta à redação.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A biotecnologia é muito presente no ENEM, por ser um tema atual. Aparecem questões sobre produção de insulina por bactérias, transgênicos, clonagem, células-tronco, testes de paternidade, vacinas de DNA, CRISPR, biocombustíveis e fermentação. O enunciado costuma fornecer um texto jornalístico ou um esquema do processo, e pedir para identificar a técnica usada, relacionar com o conceito de DNA recombinante ou avaliar vantagens e riscos de uma aplicação.',
  'Alguns pontos para fixar: enzimas de restrição cortam o DNA e a ligase une; plasmídios são vetores usados em bactérias; transgênico recebeu gene de outra espécie, enquanto um clone tem o mesmo DNA do doador; a PCR amplifica o DNA e a eletroforese separa fragmentos; as células-tronco embrionárias são pluripotentes. Um erro comum é confundir transgenia com clonagem, ou achar que o transgênico é "contaminado" com o gene do outro organismo, quando na verdade o gene foi incorporado ao genoma.',
  'Para revisar, organize o tema em três blocos: ferramentas (enzimas de restrição, ligase, vetores, PCR, eletroforese, sequenciamento), aplicações (insulina, vacinas, transgênicos, terapia gênica, células-tronco, clonagem, perfil de DNA) e debate ético (riscos, patentes, privacidade, equidade). Pratique escrever dois ou três argumentos favoráveis e contrários a cada aplicação, pois isso serve tanto para as questões de Biologia quanto para a redação, que frequentemente aborda temas de ciência, tecnologia e sociedade.'] }
]}
];
