/* Biologia: textos corridos, temas 19 a 21 */
module.exports = [
{ t:'Sistema digestório e nutrição', txt:[
 { h:'Nutrientes e alimentação equilibrada', p:[
  'Os alimentos fornecem as substâncias de que o organismo precisa para obter **energia**, construir e renovar seus tecidos e regular as funções vitais. Esses componentes são os **nutrientes**. Os **carboidratos** são a principal fonte de energia, com cerca de 4 kcal por grama, e estão em pães, massas, arroz, frutas e açúcares. As **proteínas**, também com 4 kcal por grama, têm função estrutural, enzimática e de defesa, e vêm de carnes, ovos, leite e leguminosas. Os **lipídios**, com 9 kcal por grama, armazenam energia, compõem membranas e hormônios e transportam vitaminas.',
  'Os **sais minerais** (como cálcio, ferro, sódio, potássio e iodo) e as **vitaminas** não fornecem energia, mas regulam processos essenciais. A falta de vitaminas e minerais causa **doenças carenciais**: a carência de vitamina C causa escorbuto, a de vitamina A causa cegueira noturna, a de vitamina D leva ao raquitismo, a de ferro à anemia, a de iodo ao bócio, e a de cálcio à fragilidade dos ossos. A **água** é o componente mais abundante do corpo e atua como solvente, no transporte e na regulação da temperatura. As **fibras**, presentes em vegetais, não são digeridas, mas ajudam o funcionamento do intestino.',
  'Uma **dieta equilibrada** reúne alimentos variados, em quantidades adequadas às necessidades de cada pessoa. A **pirâmide alimentar** e o guia alimentar brasileiro recomendam priorizar alimentos **in natura** e minimamente processados, limitar os ultraprocessados (ricos em açúcar, gordura e sódio) e manter hábitos regulares. A **desnutrição** resulta da ingestão insuficiente de energia e nutrientes, e a **obesidade**, do consumo excessivo associado ao sedentarismo, e ambas são problemas de saúde pública. O **índice de massa corporal** (IMC = massa em kg dividida pelo quadrado da altura em metros) é um dos indicadores usados para a avaliação.'] },
 { h:'Os órgãos do sistema digestório e as etapas da digestão', p:[
  'O **sistema digestório** é formado pelo **tubo digestório**, que vai da boca ao ânus, e pelas **glândulas anexas**: glândulas salivares, fígado e pâncreas. A **digestão** é a quebra dos alimentos em moléculas pequenas o suficiente para serem absorvidas, e acontece de dois modos: **mecânico** (mastigação e movimentos do tubo digestório) e **químico**, realizado por **enzimas** que agem em condições específicas de pH. Os movimentos de contração e relaxamento que empurram o alimento ao longo do tubo são chamados de **peristaltismo**.',
  'Na **boca**, os dentes trituram o alimento e a saliva, que contém a **amilase salivar** (ptialina), inicia a digestão do amido. O bolo alimentar passa pela faringe e pelo esôfago até o **estômago**, onde o suco gástrico, que contém **ácido clorídrico** (pH em torno de 2) e a enzima **pepsina**, inicia a digestão das proteínas. O muco protege a parede do estômago do próprio ácido, e quando essa proteção falha podem surgir gastrites e **úlceras**, muitas vezes associadas à bactéria Helicobacter pylori. O alimento, transformado em quimo, passa ao intestino.',
  'No **intestino delgado**, que tem cerca de 6 a 7 metros, ocorre a maior parte da digestão e da absorção. Ali o quimo recebe o **suco pancreático**, com enzimas que digerem carboidratos (amilase), proteínas (tripsina) e lipídios (lipase), a **bile**, produzida no fígado e armazenada na vesícula biliar, que emulsifica as gorduras, e o **suco entérico**, com enzimas que completam a digestão. No **intestino grosso**, ocorre a absorção de água e de sais, e a formação das fezes, com a participação da microbiota, que produz vitaminas, como a K. Os resíduos são eliminados pelo ânus.'] },
 { h:'Absorção, glândulas anexas e doenças', p:[
  'A **absorção** dos nutrientes ocorre principalmente no intestino delgado, cuja parede apresenta dobras, **vilosidades** e **microvilosidades**, que aumentam enormemente a superfície de contato, chegando à área comparável à de uma quadra de tênis. Os nutrientes passam para o sangue ou para a linfa. Os monossacarídeos (como a glicose), os aminoácidos, as vitaminas hidrossolúveis e os sais minerais vão para os **capilares sanguíneos** e seguem ao fígado pela veia porta. Os ácidos graxos e o glicerol, após reconstituídos, são absorvidos pelos **vasos linfáticos**.',
  'O **fígado** é a maior glândula do corpo, e tem funções como produzir a bile, armazenar glicogênio e vitaminas, transformar substâncias tóxicas (como o álcool e medicamentos), sintetizar proteínas do plasma e controlar a glicose do sangue. O **pâncreas** produz o suco pancreático, com enzimas digestivas, e também os hormônios **insulina** e **glucagon**, que regulam a glicose. A **vesícula biliar** apenas armazena e concentra a bile, e a formação de cálculos nela, ou "pedras", pode causar dor e exigir cirurgia. Sem a bile, a digestão das gorduras fica prejudicada.',
  'Entre as doenças e distúrbios, estão a **diarreia**, que pode levar à desidratação, especialmente em crianças, e que se trata com **soro de reidratação**; a **prisão de ventre**, ligada a uma dieta pobre em fibras e em água; a **intolerância à lactose**, causada pela falta da enzima lactase, que digere o açúcar do leite; a **doença celíaca**, uma reação ao glúten; e a **hepatite**, inflamação do fígado. Os hábitos de higiene e o saneamento evitam muitas infecções do sistema digestório, e a alimentação saudável reduz o risco de doenças crônicas, como a obesidade, o diabetes e as doenças cardíacas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM aborda o sistema digestório em questões ligadas à nutrição e à saúde: análise de rótulos de alimentos, cálculo de calorias, doenças carenciais, intolerância à lactose, ação de enzimas e do pH, diarreias e reidratação, e saneamento. Também cobra a função de cada órgão, e a relação entre estrutura e função, como as vilosidades que aumentam a absorção. Um enunciado típico descreve uma situação, como a remoção de um órgão, e pergunta qual digestão é afetada.',
  'Para resolver, lembre onde cada nutriente começa a ser digerido: o **amido** na boca, as **proteínas** no estômago e os **lipídios** no intestino delgado, com a ajuda da bile. As enzimas funcionam em pH específico: a pepsina age em meio ácido (estômago), e as pancreáticas, em meio básico (intestino delgado), pois o suco pancreático neutraliza o ácido. Atenção à confusão comum: a bile **não é uma enzima**, ela apenas emulsifica as gorduras, aumentando a ação das lipases. Em rótulos, atente para o valor energético por porção.',
  'Resumo para revisar: carboidratos e lipídios são fontes de energia, e proteínas têm função estrutural; as vitaminas e os minerais evitam doenças carenciais; a digestão mecânica e a química ocorrem do início ao fim do tubo digestório; a maior parte da absorção está no intestino delgado, graças às vilosidades; o fígado produz bile e o pâncreas, enzimas e hormônios; e o intestino grosso absorve água. Em seguida, vem o estudo do transporte e da respiração, que levam os nutrientes e o oxigênio às células.'] }
]},
{ t:'Sistemas circulatório e respiratório', txt:[
 { h:'O coração e a circulação do sangue', p:[
  'O **sistema circulatório** transporta substâncias pelo corpo: oxigênio, gás carbônico, nutrientes, hormônios, resíduos e células de defesa. É formado pelo **coração**, pelos **vasos sanguíneos** e pelo **sangue**. O coração é um órgão muscular, dividido em quatro cavidades: dois **átrios** (superiores), que recebem o sangue, e dois **ventrículos** (inferiores), que o bombeiam. As **valvas** garantem que o sangue circule em um só sentido. O lado direito do coração recebe sangue pobre em oxigênio, e o esquerdo, sangue rico em oxigênio, e os dois lados não se misturam: a circulação humana é **dupla e completa**.',
  'Na **pequena circulação** (pulmonar), o sangue venoso sai do **ventrículo direito**, vai aos pulmões pelas artérias pulmonares, onde recebe oxigênio (hematose), e volta ao **átrio esquerdo** pelas veias pulmonares. Na **grande circulação** (sistêmica), o sangue arterial sai do **ventrículo esquerdo** pela artéria aorta, distribui-se pelo corpo, onde troca gases com os tecidos, e retorna ao **átrio direito** pelas veias cavas. Uma observação importante: as artérias pulmonares transportam sangue pobre em oxigênio, e as veias pulmonares, sangue rico, exceções à regra de "artéria = sangue oxigenado".',
  'Os vasos sanguíneos têm características específicas. As **artérias** conduzem o sangue do coração para os órgãos, têm paredes grossas e elásticas, pois suportam alta pressão, e o pulso é sentido nelas. As **veias** levam o sangue de volta ao coração, têm paredes mais finas e possuem **válvulas** que impedem o refluxo. Os **capilares** são vasos muito finos, de parede de uma só camada de células, onde ocorrem as trocas com os tecidos. O batimento do coração é regulado por um grupo de células chamado de **marca-passo**, e a frequência aumenta durante o exercício, pela ação do sistema nervoso e dos hormônios.'] },
 { h:'O sangue, a linfa e a pressão arterial', p:[
  'O **sangue** é um tecido líquido formado pelo **plasma** (cerca de 55%, com água, proteínas, sais, nutrientes e hormônios) e por **elementos figurados**. As **hemácias** (glóbulos vermelhos) transportam oxigênio pela **hemoglobina**, proteína que contém ferro, e não têm núcleo nos mamíferos. Os **leucócitos** (glóbulos brancos) atuam na defesa do organismo. As **plaquetas**, fragmentos de células, participam da **coagulação**, que forma o coágulo e estanca o sangramento. A produção das células do sangue ocorre na medula óssea vermelha. A anemia é a redução das hemácias ou da hemoglobina, e pode ser causada pela falta de ferro.',
  'A **linfa** é um líquido que circula nos vasos linfáticos e recolhe o excesso de líquido dos tecidos, devolvendo-o ao sangue. Também transporta gorduras absorvidas no intestino e células de defesa, e passa por **linfonodos** (os "gânglios"), que filtram micróbios e produzem linfócitos. Quando há uma infecção, os linfonodos próximos podem inchar. O sistema linfático é, portanto, um complemento da circulação e da defesa do corpo. A obstrução dos vasos linfáticos por parasitas, como na filariose, causa inchaço das pernas.',
  'A **pressão arterial** é a força exercida pelo sangue sobre as paredes das artérias, e é medida por dois valores: a **sistólica** (máxima, durante a contração do coração) e a **diastólica** (mínima, no relaxamento), por exemplo, 120/80 mmHg. A **hipertensão** (pressão alta) é uma doença crônica, silenciosa, que aumenta o risco de infarto e de acidente vascular cerebral (AVC). Os principais fatores de risco são o excesso de sal, o sedentarismo, o tabagismo, o estresse, o excesso de peso e a predisposição genética. A **aterosclerose**, acúmulo de gordura nas paredes das artérias, estreita-as e dificulta a passagem do sangue.'] },
 { h:'Sistema respiratório e trocas gasosas', p:[
  'O **sistema respiratório** garante a troca de gases entre o organismo e o ambiente: o oxigênio entra e o gás carbônico sai. As vias aéreas começam nas **fossas nasais**, onde o ar é filtrado, aquecido e umedecido, e passam por **faringe**, **laringe** (onde estão as cordas vocais), **traqueia** (revestida por cílios e muco, que retêm partículas), **brônquios**, **bronquíolos** e **alvéolos pulmonares**. Os alvéolos são pequenas bolsas de parede finíssima, envolvidas por capilares, e é neles que ocorre a **hematose**, ou seja, a troca de gases por difusão: o O2 passa para o sangue e o CO2 passa para os alvéolos.',
  'A ventilação pulmonar acontece por meio dos movimentos de **inspiração** e **expiração**, comandados pelo **diafragma** (músculo abaixo dos pulmões) e pelos músculos intercostais. Na inspiração, o diafragma se contrai e desce, as costelas se elevam, o volume da caixa torácica aumenta e a pressão diminui, o que faz o ar entrar. Na expiração, os músculos relaxam, o volume diminui e o ar sai. O ritmo respiratório é controlado pelo **bulbo**, no sistema nervoso, que responde principalmente à **concentração de CO2** no sangue, e não à de O2.',
  'No sangue, o oxigênio é transportado principalmente ligado à **hemoglobina** (formando a oxi-hemoglobina), e o gás carbônico, em grande parte, na forma de íons **bicarbonato** dissolvidos no plasma. O **monóxido de carbono** (CO) liga-se à hemoglobina com afinidade muito maior que a do O2, e impede o transporte do oxigênio, o que explica a intoxicação em ambientes fechados com queima incompleta. Em altitudes elevadas, o ar tem menos oxigênio, e o organismo se adapta com o aumento do número de hemácias e da frequência respiratória.'] },
 { h:'Doenças, hábitos de vida e prevenção', p:[
  'Entre as doenças do sistema respiratório, estão a **gripe** e o **resfriado** (virais), a **asma** (inflamação crônica das vias aéreas, com crises de falta de ar), a **bronquite**, a **pneumonia** (infecção dos alvéolos), a **tuberculose** e a **enfisema pulmonar**, geralmente causado pelo tabagismo, em que há destruição dos alvéolos. O **tabagismo** é a principal causa evitável de doenças e mortes: a fumaça contém mais de 4.000 substâncias, incluindo a nicotina (que causa dependência), o monóxido de carbono, o alcatrão (com substâncias cancerígenas) e outros irritantes. Ele aumenta o risco de câncer de pulmão, de doenças cardíacas e de AVC.',
  'No sistema circulatório, as principais doenças são o **infarto do miocárdio** (obstrução de uma artéria coronária, que leva à morte de parte do músculo cardíaco), o **AVC** (obstrução ou rompimento de um vaso cerebral), a **hipertensão**, a **aterosclerose**, as **varizes** (dilatação de veias com válvulas deficientes) e a **trombose**, formação de coágulos nos vasos. As **doenças cardiovasculares** são a principal causa de morte no mundo, e sua prevenção passa por alimentação equilibrada, exercício físico, controle do peso, da pressão e do colesterol, e abandono do cigarro.',
  'O **colesterol** é um lipídio importante, componente das membranas e precursor de hormônios, mas seu excesso no sangue favorece a aterosclerose. É transportado por lipoproteínas: a **LDL** (o "colesterol ruim") leva o colesterol aos tecidos e pode depositá-lo nas artérias, e a **HDL** (o "colesterol bom") recolhe o excesso e o leva ao fígado. O exercício físico regular aumenta o HDL e melhora a circulação e a capacidade respiratória. Esses conhecimentos são úteis para interpretar exames, rótulos de alimentos e campanhas de saúde, que costumam aparecer em questões do ENEM.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Os sistemas circulatório e respiratório aparecem no ENEM em questões sobre esquemas do coração e da circulação, trocas gasosas, efeitos do exercício físico, do tabagismo e da altitude, doenças cardiovasculares, pressão arterial, intoxicação por monóxido de carbono e doação de sangue. É frequente a interpretação de um desenho do coração, com a indicação do caminho do sangue, ou de um gráfico da frequência cardíaca ou respiratória durante uma atividade.',
  'Alguns cuidados: lembre que a circulação é dupla e completa, sem mistura entre sangue venoso e arterial; que o sangue oxigenado está nas veias pulmonares e nas artérias sistêmicas; que a hematose ocorre nos alvéolos e nos capilares dos tecidos; que o CO2 é o principal estímulo para a respiração; e que o monóxido de carbono impede o transporte de oxigênio. Quando a questão trata de exercício físico, pense no aumento da demanda de oxigênio, que eleva os batimentos e o ritmo respiratório.',
  'Para revisar: pequena circulação leva o sangue do coração aos pulmões e de volta; grande circulação leva o sangue do coração aos tecidos e de volta; as hemácias transportam O2 pela hemoglobina; a pressão arterial é medida em sistólica e diastólica; os alvéolos são a sede da hematose; o diafragma comanda a ventilação; o tabagismo e a vida sedentária favorecem doenças cardiovasculares e respiratórias. O próximo tema é o sistema nervoso e o endócrino, que coordenam todas essas funções e a resposta do corpo ao ambiente.'] }
]},
{ t:'Sistemas nervoso e endócrino', txt:[
 { h:'O neurônio e a transmissão do impulso nervoso', p:[
  'O **sistema nervoso** recebe informações do ambiente e do próprio corpo, as processa e comanda as respostas. Sua unidade funcional é o **neurônio**, célula especializada em conduzir sinais elétricos. Um neurônio tem o **corpo celular**, onde está o núcleo, os **dendritos**, prolongamentos curtos e ramificados que **recebem** os estímulos, e o **axônio**, um prolongamento longo que **conduz** o impulso até outras células. Em muitos axônios, há uma camada de gordura, a **bainha de mielina**, que acelera a condução do impulso. A perda de mielina, como na esclerose múltipla, prejudica a comunicação nervosa.',
  'O **impulso nervoso** é uma onda de variação elétrica ao longo da membrana do neurônio. Em repouso, a membrana está **polarizada**, com o interior negativo em relação ao exterior, graças à bomba de sódio e potássio e à permeabilidade seletiva. Quando um estímulo atinge um limiar, canais de sódio se abrem, o Na+ entra e a membrana se **despolariza**; em seguida, o K+ sai e restabelece a polaridade (**repolarização**). Esse processo se propaga pelo axônio, na lei do **tudo ou nada**: o impulso ocorre com intensidade total ou não ocorre. Os neurônios são células que, em geral, não se dividem em adultos.',
  'A transmissão entre neurônios, ou entre neurônio e outra célula, ocorre nas **sinapses**. Na sinapse química, o impulso chega à terminação do axônio e provoca a liberação de **neurotransmissores** (como acetilcolina, dopamina, serotonina e noradrenalina) na fenda sináptica; eles se ligam a receptores na célula seguinte e geram um novo impulso. Muitos medicamentos e drogas atuam sobre as sinapses: os antidepressivos aumentam a disponibilidade de serotonina, e a cocaína e outras drogas alteram o sistema de recompensa, por meio da dopamina, o que explica a dependência.'] },
 { h:'Organização do sistema nervoso e arco reflexo', p:[
  'O sistema nervoso se divide em **central** (SNC) e **periférico** (SNP). O SNC, formado pelo **encéfalo** (cérebro, cerebelo e tronco encefálico) e pela **medula espinhal**, processa as informações. O **cérebro** é responsável pelo pensamento, memória, linguagem, emoções e movimentos voluntários; o **cerebelo** coordena o equilíbrio e a coordenação motora; o **tronco encefálico**, que inclui o **bulbo**, controla funções vitais, como a respiração e os batimentos cardíacos. A **medula espinhal** conduz impulsos entre o encéfalo e o corpo e comanda os reflexos.',
  'O **SNP** é formado por **nervos** e **gânglios**, e liga o SNC ao resto do corpo. Divide-se em **sistema somático**, que controla os movimentos voluntários da musculatura esquelética, e **sistema nervoso autônomo**, que controla as funções involuntárias (músculos lisos, cardíaco e glândulas). O autônomo tem duas partes que, em geral, atuam de forma antagônica: o **simpático**, que prepara o corpo para situações de estresse e de luta ou fuga (acelera o coração, dilata as pupilas, aumenta a glicose) e o **parassimpático**, que promove o repouso e a digestão (reduz os batimentos e estimula a digestão).',
  'Os **atos reflexos** são respostas rápidas, involuntárias e automáticas, como retirar a mão de uma superfície quente. Seguem o **arco reflexo**: um **receptor** capta o estímulo, um **neurônio sensitivo** conduz o impulso até a medula, um **neurônio associativo** (interneurônio) faz a conexão, e um **neurônio motor** leva a ordem ao órgão efetor, que responde. Por não passar pelo cérebro, a resposta é mais rápida e protege o organismo, e só depois a informação chega ao cérebro e a pessoa percebe a dor. Já os atos **voluntários** envolvem o córtex cerebral e a decisão consciente.'] },
 { h:'Sistema endócrino e hormônios', p:[
  'O **sistema endócrino** regula as funções do corpo por meio de **hormônios**, substâncias químicas produzidas por **glândulas endócrinas** e lançadas diretamente na corrente sanguínea, que as leva até as **células-alvo**, dotadas de receptores específicos. Ao contrário da resposta nervosa, que é rápida e de curta duração, a resposta hormonal é **mais lenta e mais duradoura**. Os dois sistemas se integram: o **hipotálamo**, no encéfalo, produz hormônios e controla a **hipófise**, glândula que regula muitas outras e é chamada de "glândula mestra".',
  'As principais glândulas e hormônios: a **hipófise** produz o hormônio do crescimento (GH), os hormônios que estimulam outras glândulas (TSH, ACTH, FSH e LH) e a prolactina; a **tireoide** produz tiroxina, que regula o metabolismo e exige iodo (a falta causa bócio); as **paratireoides** regulam o cálcio; as **suprarrenais** produzem adrenalina, que prepara o corpo para situações de estresse, e cortisol; o **pâncreas** produz insulina e glucagon; as **gônadas** produzem os hormônios sexuais (testosterona nos testículos; estrógeno e progesterona nos ovários). A **melatonina**, da glândula pineal, regula o ciclo do sono.',
  'O controle da glicose é um exemplo clássico de **regulação por retroalimentação negativa**. Após uma refeição, a glicose sobe no sangue, e o pâncreas libera **insulina**, que estimula as células a captarem a glicose e o fígado a armazená-la como glicogênio, e a glicemia cai. Em jejum, o pâncreas libera **glucagon**, que estimula o fígado a quebrar o glicogênio e liberar glicose. No **diabetes tipo 1**, há falta de insulina por destruição das células pancreáticas (doença autoimune); no **tipo 2**, as células respondem mal à insulina, associado à obesidade e ao sedentarismo. O controle envolve dieta, exercício e medicamentos.'] },
 { h:'Hormônios sexuais, ciclo menstrual e uso de substâncias', p:[
  'Os **hormônios sexuais** determinam as características sexuais secundárias na puberdade: na mulher, o aumento das mamas e o alargamento do quadril; no homem, o crescimento de pelos, o engrossamento da voz e o aumento da massa muscular. No **ciclo menstrual**, que dura em média 28 dias, a hipófise libera FSH, que estimula o amadurecimento de um folículo ovariano, o qual produz estrógeno. O pico de LH provoca a **ovulação**, por volta do 14º dia. O corpo lúteo formado produz progesterona, que prepara o útero; se não há fecundação, os hormônios caem e ocorre a **menstruação**.',
  'O uso de **anabolizantes** (derivados da testosterona), para aumentar a massa muscular, pode causar graves efeitos colaterais, como alterações hepáticas e cardíacas, redução da produção de espermatozoides e masculinização nas mulheres. O **estresse crônico** mantém altos os níveis de cortisol, o que prejudica o sistema imunológico, o sono e o metabolismo. Os **disruptores endócrinos**, substâncias presentes em alguns plásticos e agrotóxicos, podem imitar ou bloquear hormônios, e são alvo de pesquisa e de regulação. A correta atuação dos hormônios depende, portanto, de hábitos de vida e do ambiente.',
  'As **drogas** psicoativas atuam sobre o sistema nervoso, alterando a percepção, o humor e o comportamento. Podem ser **depressoras** (álcool, benzodiazepínicos, opioides), que reduzem a atividade cerebral; **estimulantes** (cafeína, nicotina, cocaína, anfetaminas), que a aumentam; e **perturbadoras** (maconha, LSD), que alteram a percepção. O uso contínuo causa **tolerância** e **dependência**, pelas modificações nos circuitos de recompensa. O álcool, droga lícita, é responsável por muitos acidentes e doenças hepáticas. A prevenção envolve informação, apoio familiar e social, e política pública de saúde.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Sistema nervoso e endócrino aparecem no ENEM em contextos como o efeito de drogas e de medicamentos sobre as sinapses, o diabetes e o controle da glicose, o ciclo menstrual e os métodos hormonais, o hipotireoidismo, o estresse e a adrenalina, o uso de anabolizantes e doenças neurodegenerativas, como o Alzheimer e o Parkinson. A questão costuma apresentar um gráfico, como o da glicemia ou dos hormônios do ciclo menstrual, ou um esquema do neurônio, e pedir para interpretar.',
  'Pontos para dominar: a diferença entre o controle nervoso (rápido, por impulsos elétricos e neurotransmissores) e o endócrino (mais lento, por hormônios no sangue); as partes do neurônio; as etapas da sinapse; a ação oposta da insulina e do glucagon; o papel do hipotálamo e da hipófise; e a ação do simpático e do parassimpático. Em gráficos hormonais, identifique o pico de LH (ovulação) e a queda dos hormônios (menstruação). Lembre-se de que a adrenalina é a resposta rápida ao estresse.',
  'Para revisar: neurônios conduzem o impulso (dendritos recebem, axônio conduz, sinapse transmite); o SNC é encéfalo e medula, e o SNP, nervos; os reflexos passam pela medula; as glândulas endócrinas lançam hormônios no sangue; insulina reduz e glucagon eleva a glicemia; a hipófise controla outras glândulas; e as drogas agem sobre as sinapses e causam dependência. O próximo tema, a reprodução humana e os métodos contraceptivos, aplica muito do conhecimento hormonal que você acabou de revisar.'] }
]}
];

/* quinto bloco do tema Sistema digestório e nutrição */
{
  const dig = module.exports[0];
  const ult = dig.txt.pop();
  dig.txt.push({ h:'Energia, calorias e distúrbios alimentares', p:[
    'A energia dos alimentos é medida em **quilocalorias** (kcal), o que popularmente se chama de "caloria". Uma caloria é a quantidade de calor necessária para elevar em 1 °C a temperatura de 1 grama de água, e uma quilocaloria equivale a 1.000 calorias, ou a cerca de 4,18 quilojoules. O gasto de energia de uma pessoa depende da **taxa metabólica basal**, da energia consumida na digestão e da atividade física. Para manter o peso, o consumo de energia deve se equilibrar com o gasto: o excesso é armazenado, sobretudo como gordura, e a falta obriga o corpo a recorrer às reservas.',
    'Os rótulos de alimentos trazem a **tabela nutricional**, que informa o valor energético e a quantidade de carboidratos, proteínas, gorduras totais, saturadas e trans, fibras e sódio por porção, e o percentual de valores diários. Para calcular as calorias de um alimento, multiplica-se a massa de cada nutriente por seu valor energético (4, 4 e 9 kcal por grama) e somam-se os resultados. A atenção ao tamanho da porção é essencial, pois a tabela se refere a ela, e não à embalagem inteira. Esse tipo de cálculo é muito comum no ENEM.',
    'Os **distúrbios alimentares**, como a anorexia nervosa, a bulimia e a compulsão alimentar, são transtornos psiquiátricos graves, que envolvem uma relação alterada com a comida e com a imagem corporal, e exigem acompanhamento médico e psicológico. A **desnutrição** infantil prejudica o crescimento e o desenvolvimento do cérebro, e a **obesidade** aumenta o risco de diabetes, hipertensão e doenças cardiovasculares. A **segurança alimentar** é o direito de acesso regular a alimentos de qualidade, em quantidade suficiente, e é uma discussão que une Biologia, Geografia e Sociologia.'
  ]});
  dig.txt.push(ult);
}
