/* Filosofia: textos corridos, temas 7 a 9 */
module.exports = [
{ t:'Filosofia helenística', txt:[
 { h:'O contexto helenístico e a busca pela tranquilidade', p:[
  'Com a morte de **Alexandre, o Grande**, em 323 a.C., o império macedônico se dividiu entre seus generais, e as antigas cidades-Estado gregas perderam a autonomia política. Começou o **período helenístico**, que vai do século IV ao I a.C., marcado pela mistura entre a cultura grega e as culturas orientais, e depois pela dominação de Roma. Nesse novo mundo, grande e cosmopolita, o cidadão da pólis, que participava das decisões coletivas, passou a se sentir pequeno, desamparado e inseguro, diante de poderes distantes e de guerras constantes. Essa mudança alterou o foco da Filosofia.',
  'Em vez de se concentrar na política e na construção da cidade ideal, como Platão e Aristóteles, os filósofos helenísticos se voltaram para o **indivíduo** e para a pergunta de **como viver bem** em um mundo instável: como alcançar a **felicidade**, a **tranquilidade da alma** e a **liberdade interior**, independentemente das circunstâncias externas? A Filosofia passou a ser vista como uma **terapia da alma**, uma arte de viver, que cura os medos, as angústias e as paixões. Seu foco era a **ética**, e a física e a lógica serviam como fundamento para ela.',
  'As principais escolas desse período são o **epicurismo**, o **estoicismo**, o **ceticismo** e o **cinismo**. Embora diferentes em suas doutrinas, compartilham a busca da **ataraxia** (ausência de perturbação da alma) e da **autarquia** (autossuficiência), o ideal do sábio que não depende do que lhe é externo. Atenas continuou como centro filosófico, com o Jardim de Epicuro e o Pórtico dos estoicos, e, mais tarde, essas ideias se difundiram em Roma, com pensadores como Lucrécio, Sêneca, Epiteto e Marco Aurélio, e influenciaram o cristianismo e o pensamento moderno.'] },
 { h:'O epicurismo: prazer, ataraxia e a crítica ao medo', p:[
  '**Epicuro** (341-270 a.C.) fundou, em Atenas, a escola chamada de **Jardim**, uma comunidade aberta a todos, inclusive mulheres e escravos, onde se vivia de modo simples, em amizade. Para ele, o **bem supremo** é o **prazer** (hedoné), mas entendido de forma diferente do que se costuma pensar: não é o prazer desenfreado, nem a busca por riqueza e luxo, e sim a **ausência de dor no corpo** (aponia) e de **perturbação na alma** (ataraxia). Uma vida feliz é uma vida de tranquilidade, serenidade e amizade, e não de excessos, que levam ao sofrimento.',
  'Epicuro classifica os desejos em três tipos: os **naturais e necessários** (comer, beber, abrigar-se, que devem ser satisfeitos), os **naturais e não necessários** (como os alimentos requintados, que podem ser desfrutados com moderação) e os **vãos e não naturais** (riqueza, fama, poder, que devem ser evitados, pois são insaciáveis e geram ansiedade). O sábio busca a autossuficiência, contentando-se com pouco, e valoriza a **amizade**, considerada a maior fonte de felicidade, e a prudência (phronesis), que orienta a escolha dos prazeres. "Quem não se contenta com pouco, nada o contenta", resume o ideal.',
  'Para combater o **medo**, principal obstáculo à tranquilidade, Epicuro apoiou-se na física **atomista** de Demócrito: o universo é formado por átomos e vazio, e a alma também é material, e se dissolve com a morte. Assim, não há o que temer depois da morte: "a morte nada é para nós, pois, enquanto existimos, ela não está presente, e, quando ela chega, nós não existimos mais". Os deuses existem, mas não se preocupam com os humanos, e não punem ou premiam. Essa libertação do medo dos deuses e da morte permite a serenidade. Na linguagem comum, o termo "epicurista" costuma ser usado de forma equivocada, como sinônimo de hedonista e de luxo, o que distorce a doutrina.'] },
 { h:'O estoicismo: razão, virtude e aceitação do destino', p:[
  'O **estoicismo** foi fundado por **Zenão de Cício** (c. 334-262 a.C.), que ensinava em um pórtico (stoa) pintado, em Atenas. Desenvolveu-se em três fases: a antiga (Zenão e Crisipo), a média e a **romana** (Sêneca, Epiteto e o imperador Marco Aurélio), da qual temos mais textos. Para os estoicos, o universo é regido por uma **razão universal** (logos), ou providência divina, que organiza tudo, e todas as coisas acontecem segundo uma ordem necessária, o **destino** (fatum). Os seres humanos, dotados de razão, fazem parte dessa ordem e devem viver **de acordo com a natureza**, isto é, de acordo com a razão.',
  'A virtude é o **único bem**, e o vício, o único mal; a riqueza, a saúde, a fama e até a vida são "indiferentes", pois não dependem de nós, e não determinam a felicidade. O sábio estoico distingue o que **depende de nós** (nossos julgamentos, desejos e ações) do que **não depende de nós** (o corpo, os bens, a reputação, os acontecimentos). Como diz **Epiteto**, nos primeiros parágrafos do Manual, devemos concentrar-nos no primeiro e aceitar o segundo com serenidade. As **paixões** (medo, raiva, desejos excessivos) são juízos equivocados, e o sábio busca a **apatia** (ausência de paixões perturbadoras) e a **imperturbabilidade**.',
  'O estoicismo valoriza a **cidadania universal** (cosmopolitismo): todos os seres humanos, por compartilharem a razão, são cidadãos do mundo e devem se tratar com respeito e solidariedade. **Marco Aurélio**, imperador romano, escreveu as **Meditações**, em que reflete sobre a brevidade da vida e o dever de agir com justiça. **Sêneca** discutiu a ira, a brevidade da vida e a serenidade. O estoicismo exerceu grande influência na ética cristã, no direito romano e, hoje, é retomado em livros de autoajuda e de psicologia (a terapia cognitivo-comportamental se inspira em suas ideias), embora seja preciso distinguir a doutrina original de usos simplificados.'] },
 { h:'O ceticismo e o cinismo', p:[
  'O **ceticismo** (do grego skeptikós, "aquele que investiga") foi fundado por **Pirro de Élis** (c. 360-270 a.C.), que teria acompanhado Alexandre à Índia, e desenvolvido por **Sexto Empírico**. Os céticos observam que, para cada argumento, é possível apresentar outro, de igual força, em sentido contrário, e que os sentidos e a razão nos enganam e divergem. Diante disso, defendem a **suspensão do juízo** (epoché): não afirmar nem negar, e evitar o dogmatismo. A consequência é a **ataraxia**: quem deixa de se atormentar para descobrir verdades definitivas encontra a tranquilidade. Não é negar a verdade, mas manter a dúvida e a investigação.',
  'O ceticismo antigo influenciou a Filosofia moderna. **Descartes** usou a **dúvida metódica**, inspirada nos céticos, para buscar uma certeza indubitável, e **Hume** foi um cético quanto à causalidade e à razão. A atitude cética, em sentido amplo, é útil na ciência e na vida: desconfiar das aparências, exigir provas, reconhecer os limites do conhecimento. Mas também pode ser levada ao extremo, e resultar em relativismo e em paralisia. O ENEM costuma associar o ceticismo à **dúvida** e à suspensão do juízo, e distingue-o do **dogmatismo**, que afirma verdades sem questionar.',
  'O **cinismo** foi fundado por **Antístenes** e popularizado por **Diógenes de Sinope** (c. 412-323 a.C.), que viveu em um barril, em Atenas, e é famoso por anedotas, como a de andar com uma lâmpada em plena luz do dia, "procurando um homem", e a de ter pedido a Alexandre que saísse da frente de seu Sol. O termo vem de kynikós ("como um cão"), pois os cínicos desprezavam as convenções sociais, a riqueza e o poder, e viviam de maneira simples, em liberdade e **autossuficiência**, e criticavam com ironia a hipocrisia. A palavra "cínico", hoje, designa quem age de forma falsa ou descarada, um sentido bem diferente do antigo.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a Filosofia helenística aparece em questões que trazem trechos de Epicuro (carta a Meneceu), de Sêneca, de Epiteto ou de Marco Aurélio, e pedem a identificação da escola e do conceito central: o prazer como ausência de dor e a ataraxia (epicurismo), a aceitação do destino e a distinção entre o que depende ou não de nós (estoicismo), a suspensão do juízo (ceticismo). Também podem comparar a busca da felicidade em diferentes tradições, ou relacionar essas ideias com a realidade atual, como o consumismo, a ansiedade e a busca por bem-estar.',
  'Pontos de atenção: o epicurismo defende o prazer moderado, a amizade, a simplicidade e a libertação do medo da morte, e não a busca desenfreada de prazeres; o estoicismo propõe a vida de acordo com a razão e a natureza, a aceitação do que não depende de nós e o autocontrole das paixões; o ceticismo propõe a suspensão do juízo e a dúvida; o cinismo defende a simplicidade e a liberdade em relação às convenções. A palavra "estoico", no uso comum, indica alguém que suporta a dor sem reclamar, o que reflete só parte da doutrina. Distinga as escolas pelos conceitos-chave.',
  'Para revisar, monte um quadro com as quatro escolas (fundador, ideia central, concepção de felicidade e conceito-chave), e uma frase representativa de cada uma. Reflita sobre exemplos atuais: qual escola inspira a busca de uma vida simples (epicurismo), a resiliência diante de problemas (estoicismo), o cuidado com as fontes e a dúvida diante de notícias (ceticismo)? Esse tema fecha a Filosofia antiga e prepara o seguinte, a Filosofia medieval, em que a relação entre a fé cristã e a razão grega passa a ser o grande problema.'] }
]},
{ t:'Filosofia medieval', txt:[
 { h:'O contexto medieval e a relação entre fé e razão', p:[
  'A **Filosofia medieval** se desenvolveu na Europa, do século V ao XV, em um contexto dominado pelo **cristianismo** e pela autoridade da Igreja. Tem como marca a discussão sobre a relação entre **fé** e **razão**: como conciliar a revelação divina, contida na Bíblia e na tradição, com a razão herdada dos gregos, em especial de Platão e de Aristóteles? As respostas variaram: para alguns, a razão deve estar submetida à fé; para outros, ambas são complementares, e a razão pode ajudar a compreender a fé. A Filosofia foi, muitas vezes, "serva da teologia" (ancilla theologiae), mas também produziu reflexões originais.',
  'O pensamento medieval se organizou em duas grandes fases. A **Patrística** (séculos I a VII) reúne os Padres da Igreja, que defenderam e explicaram o cristianismo diante do mundo pagão e das heresias, recorrendo ao **platonismo**. O grande nome é **Agostinho de Hipona**. A **Escolástica** (séculos IX a XV), desenvolvida nas escolas e universidades (do latim schola), usava o método da discussão rigorosa (a disputatio) e passou a se apoiar em **Aristóteles**, redescoberto no Ocidente por meio dos comentadores árabes. O principal nome é **Tomás de Aquino**. Os filósofos do mundo islâmico (Avicena e Averróis) e judaico (Maimônides) também tiveram grande importância.',
  'Em um tempo de poucos livros, de alfabetização restrita e de poder da Igreja, a Filosofia se concentrava nos **mosteiros** e, depois, nas **universidades**, como as de Paris, Bolonha e Oxford. Os debates incluíam a existência de Deus, a natureza da alma, o livre-arbítrio, o problema do mal e a questão dos **universais**, isto é, se conceitos gerais (como "humanidade") existem de verdade ou são apenas nomes. A Idade Média, por muito tempo chamada de "idade das trevas", foi, na verdade, um período de intensa produção intelectual, que preservou e transformou a herança antiga.'] },
 { h:'Santo Agostinho: a Patrística, a alma e o tempo', p:[
  '**Agostinho de Hipona** (354-430), bispo no norte da África, nasceu em Tagaste e viveu uma juventude de busca, passou pelo maniqueísmo e pelo ceticismo, e, influenciado pelo neoplatonismo e por Ambrósio, converteu-se ao cristianismo. Escreveu **Confissões**, uma autobiografia espiritual, e **A Cidade de Deus**, em que reflete sobre a história, a partir da queda de Roma (410): a história é a luta entre a **cidade terrena**, fundada no amor de si, e a **cidade de Deus**, fundada no amor a Deus. Sua obra buscou integrar a fé cristã com o platonismo, e dominou o pensamento do Ocidente até o século XIII.',
  'Para Agostinho, a **fé** e a **razão** são complementares: "creio para compreender, e compreendo para crer". A verdade está em Deus, e o ser humano a busca pela **iluminação divina**, que ilumina a mente, como o Sol ilumina os olhos. Reinterpretou as **ideias** de Platão como pensamentos de Deus, modelos de tudo que existe. O mal, em sua visão, não é uma substância, mas uma **privação** do bem, resultado do **livre-arbítrio**, que o ser humano usou mal, ao se afastar de Deus, com o pecado original. Assim, Deus não é responsável pelo mal, e o ser humano é livre e responsável.',
  'Agostinho também fez uma célebre reflexão sobre o **tempo**, nas Confissões: "o que é, pois, o tempo? Se ninguém me perguntar, sei; se quiser explicar a quem me pergunta, não sei". Concluiu que o passado, o presente e o futuro só existem na **alma**: o passado como memória, o presente como atenção, e o futuro como expectativa. O tempo é, assim, uma "distensão da alma". Essa análise, que aparece em questões de Filosofia, mostra o caráter introspectivo do pensamento agostiniano, e influenciou a Filosofia moderna e contemporânea, como a de Descartes, de Husserl e de Heidegger.'] },
 { h:'Tomás de Aquino: a Escolástica e a conciliação com Aristóteles', p:[
  '**Tomás de Aquino** (1225-1274), frade dominicano, nascido na Itália, foi o maior filósofo e teólogo da Escolástica. Estudou em Paris e em Colônia, com Alberto Magno, e escreveu a **Suma Teológica** e a **Suma contra os Gentios**, obras monumentais que organizam o saber cristão. Seu projeto foi **conciliar a fé com a razão**, usando a Filosofia de **Aristóteles**, que havia chegado ao Ocidente por meio de traduções do árabe, e que alguns viam como uma ameaça à fé. Tomás mostrou que há **verdades de razão**, acessíveis ao conhecimento natural, e **verdades de fé**, reveladas, que superam a razão, mas não a contradizem, pois a verdade é uma só, e vem de Deus.',
  'A razão pode, por si só, demonstrar a **existência de Deus**. Tomás apresentou as **cinco vias**, argumentos a partir da experiência: do **movimento** (tudo que se move é movido por outro, e é preciso um Primeiro Motor imóvel), da **causa eficiente** (uma primeira causa), da **contingência** (os seres contingentes dependem de um ser necessário), dos **graus de perfeição** (um ser perfeitíssimo) e da **ordem** do universo (uma inteligência ordenadora). Essas provas partem do mundo sensível, seguindo Aristóteles, e se contrapõem ao argumento "ontológico" de Anselmo, que partia do conceito de Deus.',
  'Na **ética**, Tomás de Aquino adaptou a ética aristotélica da felicidade e da virtude, ao acrescentar as **virtudes teologais** (fé, esperança e caridade) às virtudes naturais (prudência, justiça, fortaleza e temperança), e defendeu que o fim último do ser humano é a **bem-aventurança**, a visão de Deus. Na política, formulou a teoria do **direito natural**: há leis naturais, acessíveis à razão, que fundamentam as leis humanas, e uma lei injusta não é verdadeira lei. A influência de Tomás é enorme, e sua obra é a base do pensamento católico. Ao conciliar fé e razão, preparou o terreno para o desenvolvimento da ciência e da Filosofia moderna.'] },
 { h:'Os universais, a crise da Escolástica e o legado medieval', p:[
  'A **querela dos universais** foi um dos grandes debates medievais: os conceitos gerais (como "ser humano", "cavalo" ou "beleza") têm existência real? Os **realistas**, na linha de Platão, afirmavam que os universais existem de fato, independentes das coisas individuais. Os **nominalistas**, como **Roscelino** e, mais tarde, **Guilherme de Ockham** (século XIV), defendiam que só existem os indivíduos, e que os universais são apenas nomes (termos) usados para agrupar coisas semelhantes. Aristóteles e Tomás adotaram uma posição intermediária, o **realismo moderado**: os universais existem nas coisas e na mente, que os abstrai.',
  '**Guilherme de Ockham** formulou o princípio da **navalha de Ockham**: "não se devem multiplicar os entes sem necessidade", ou seja, entre explicações concorrentes, deve-se preferir a mais simples. Sua defesa do nominalismo e a separação entre a fé e a razão, que ele considerava incapaz de provar verdades religiosas, enfraqueceram a síntese tomista e abriram caminho para a ciência empírica e para a Filosofia moderna. A partir do século XIV, a Escolástica entrou em crise, com a peste, as guerras, os conflitos da Igreja e o surgimento do humanismo e do Renascimento, que valorizavam a experiência e o ser humano.',
  'O **legado** da Filosofia medieval é duradouro: a criação das **universidades**, o método de argumentação rigorosa, o aprofundamento de temas como o livre-arbítrio, o mal, o tempo e a existência de Deus, e a preservação e a transmissão do saber antigo, graças aos mosteiros e aos filósofos árabes e judeus. A relação entre **fé e razão** continua a ser debatida, em questões como a ciência e a religião, a laicidade do Estado e a liberdade de crença. Compreender a Idade Média, sem preconceitos, permite ver como as ideias evoluem, e como a Filosofia moderna, que veremos a seguir, nasce em diálogo, e em ruptura, com essa tradição.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Filosofia medieval aparece no ENEM em questões que apresentam trechos de Agostinho (sobre o tempo, o livre-arbítrio ou a relação entre fé e razão) e de Tomás de Aquino (as provas da existência de Deus, a lei natural), e pedem a identificação do pensador, o contexto (Patrística e Escolástica) ou o problema central. Também podem ser cobrados a influência de Platão em Agostinho e de Aristóteles em Tomás, a discussão entre fé e razão e a importância das universidades. Em questões atuais, a relação entre ciência, religião e Estado laico pode ser retomada.',
  'Pontos de atenção: Agostinho é da Patrística e usa o platonismo; Tomás é da Escolástica e usa o aristotelismo; ambos buscam conciliar fé e razão, mas de modos diferentes; Agostinho explica o mal como privação do bem e defende o livre-arbítrio; Tomás propõe as cinco vias; a questão dos universais opõe realistas e nominalistas; Ockham propõe a navalha. Para memorizar: Agostinho, tempo e alma; Tomás, razão e Deus; Ockham, simplicidade. Evite dizer que a Idade Média não teve filosofia ou que a Igreja só proibia o pensamento.',
  'Para revisar, monte uma linha com os períodos (Patrística e Escolástica), os autores principais, as ideias e as influências (Platão e Aristóteles). Treine explicar a diferença entre verdades de fé e verdades de razão, e resumir as cinco vias. Esse tema leva ao seguinte, Maquiavel, que, no início da Idade Moderna, rompe com a visão cristã e moral da política, e propõe um pensamento realista sobre o poder, marcando o nascimento da Filosofia política moderna.'] }
]},
{ t:'Maquiavel', txt:[
 { h:'Maquiavel e o contexto do Renascimento italiano', p:[
  '**Nicolau Maquiavel** (1469-1527) foi um pensador, diplomata e funcionário público de Florença, na Itália renascentista, e é considerado o fundador da **ciência política moderna**. Viveu em uma época de instabilidade: a Itália estava dividida em cidades-Estado rivais (Florença, Veneza, Milão, Nápoles e os Estados papais), disputadas por potências estrangeiras, como a França e a Espanha, e atravessada por guerras, traições e conflitos. A família Médici governava Florença, foi expulsa e retornou. Maquiavel serviu à República florentina, como secretário e diplomata, e conheceu de perto os líderes da época, como César Bórgia.',
  'Com a volta dos Médici, em 1512, foi afastado, acusado de conspiração, preso e torturado, e retirou-se para sua propriedade rural, onde escreveu suas principais obras: **O Príncipe** (1513, publicado em 1532), um tratado sobre como conquistar e manter o poder, dedicado a Lourenço de Médici; os **Discursos sobre a primeira década de Tito Lívio**, que analisam a república romana, e a **História de Florença**. Seu objetivo era entender a política como ela **realmente é**, e não como deveria ser, com base na experiência dos acontecimentos contemporâneos e na história antiga, e oferecer um guia prático aos governantes.',
  'Esse enfoque representa uma **ruptura** com a tradição anterior. A filosofia política clássica e medieval, de Platão, Aristóteles e dos autores cristãos, tratava a política como parte da ética e da religião: o bom governante deveria ser virtuoso e orientado para o bem comum e para o bem moral. Maquiavel separa a política da moral e da religião, e a analisa como uma esfera com regras próprias, a da conquista e da manutenção do poder. Por isso, é chamado de **realista**, e seu pensamento gerou polêmica, dando origem ao termo "maquiavélico", muitas vezes usado para designar a astúcia e a falta de escrúpulos.'] },
 { h:'O Príncipe: virtù, fortuna e a conquista do poder', p:[
  'Em **O Príncipe**, Maquiavel descreve os diversos tipos de principados, as formas de os conquistar e de os manter, o papel do exército e as qualidades do governante. Dois conceitos são centrais. A **virtù** é a capacidade, a habilidade, a energia e a astúcia do príncipe para agir de acordo com as circunstâncias e conquistar e manter o poder. Não equivale à virtude moral cristã: é uma qualidade política, que combina coragem, prudência, força e esperteza. A **fortuna** é a sorte, o acaso, as circunstâncias imprevisíveis, simbolizada como uma deusa inconstante ou como um rio caudaloso, que pode destruir tudo.',
  'Para Maquiavel, a fortuna governa cerca de metade das ações humanas, e a virtù deve governar a outra metade. O príncipe habilidoso deve **se adaptar** às mudanças da fortuna e aproveitar as oportunidades: como um rio, que se pode prevenir com diques, em tempos calmos. A política é o campo da incerteza, e o governante deve estar preparado, com **armas próprias**, e não com mercenários ou tropas alheias, que são pouco confiáveis. Daí a insistência de Maquiavel em um **exército de cidadãos**, que defenda a pátria, e na necessidade de o príncipe conhecer a arte da guerra.',
  'O governante, segundo Maquiavel, precisa **aparentar** certas qualidades, como clemência, lealdade e religiosidade, mas deve estar preparado para agir de modo diferente quando as circunstâncias exigirem. Usa a imagem do **leão** (força) e da **raposa** (astúcia): o príncipe deve ser os dois, pois o leão não se defende das armadilhas, e a raposa não se defende dos lobos. Em um dos trechos mais discutidos, afirma que "é mais seguro ser temido do que amado, quando se tem de renunciar a um dos dois", mas deve evitar ser odiado. Essas teses mostram que, para ele, o objetivo é a **estabilidade do Estado**, e que o sucesso político se mede pelos resultados.'] },
 { h:'Os fins e os meios, a moral e a república', p:[
  'Uma expressão atribuída a Maquiavel é "**os fins justificam os meios**", embora ela não apareça literalmente em sua obra. A ideia é que o governante, para preservar o Estado e garantir a ordem, pode ter de recorrer a ações que a moral comum condenaria, como a mentira, a dissimulação ou a violência, sempre que isso for necessário e eficaz. Maquiavel não faz apologia da crueldade gratuita: recomenda que a violência seja usada rápida e de uma só vez, quando necessária, e que se evitem a rapina e a ofensa aos súditos. A pergunta que ele propõe é de ordem ética: qual a **responsabilidade** do governante em relação aos resultados?',
  'Essa discussão foi retomada por vários autores. O sociólogo **Max Weber**, por exemplo, distinguiu a **ética da convicção** (agir de acordo com princípios, sem considerar as consequências) e a **ética da responsabilidade** (considerar as consequências previsíveis das ações), em A Política como Vocação. Maquiavel se aproxima da segunda. A discussão permanece atual: até onde podem ir os governantes para proteger o Estado? Quais limites a lei e os direitos humanos impõem? A **razão de Estado**, a ideia de que a conservação do Estado justifica medidas extraordinárias, é um conceito derivado dessas reflexões, e continua a gerar debates sobre segurança e liberdade.',
  'Embora O Príncipe seja a obra mais conhecida, Maquiavel também defendeu a **república** nos **Discursos**, considerando-a o regime mais estável, em que o conflito entre os grandes (que desejam dominar) e o povo (que deseja não ser dominado) produz as boas leis e a liberdade, se bem canalizado pelas instituições. Isso mostra que o autor não era simplesmente um defensor da tirania, e levou alguns intérpretes, como Rousseau, a ver em O Príncipe uma sátira que revela aos povos os segredos dos tiranos. Maquiavel valorizava a **liberdade** da pátria e o **patriotismo**, e sonhava com uma Itália unida e livre da dominação estrangeira, como se vê no último capítulo de O Príncipe.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Maquiavel é frequentemente cobrado no ENEM. As questões trazem trechos de O Príncipe e pedem a identificação de ideias como a separação entre a política e a moral, a virtù e a fortuna, a relação entre os fins e os meios, o dilema entre ser amado ou temido e a importância das aparências. Também pode ser pedida a comparação com outras concepções de poder (Platão, Aristóteles e os contratualistas), a análise de um fato político atual à luz de Maquiavel, ou a discussão sobre a ética na política.',
  'Pontos de atenção: Maquiavel é um pensador realista, que analisa a política como ela é, e não como deveria ser; separa a política da moral e da religião; virtù é a habilidade política, e não a virtude moral; fortuna é o acaso; o príncipe deve ser leão e raposa; a frase "os fins justificam os meios" é uma síntese popular, e não uma citação exata; o termo "maquiavélico" simplifica e distorce o pensamento do autor. Evite confundir Maquiavel com defensor do autoritarismo irrestrito: ele valoriza a república e a liberdade nos Discursos.',
  'Para revisar, monte um quadro com os conceitos de Maquiavel (virtù, fortuna, razão de Estado, leão e raposa, aparências) e uma situação atual para cada um. Compare-o com os pensadores políticos que vêm a seguir (Hobbes, Locke e Rousseau), que, em vez de descrever a conquista do poder, buscaram justificar a origem e a legitimidade do Estado. Esse tema inaugura a Filosofia moderna, e prepara a discussão do racionalismo e do empirismo, que transformarão a teoria do conhecimento.'] }
]}
];

/* quinto bloco do tema Maquiavel */
{
  const mq = module.exports[2];
  const ult = mq.txt.pop();
  mq.txt.push({ h:'O legado de Maquiavel: Estado moderno, poder e atualidade', p:[
    'Maquiavel foi um dos primeiros a usar a palavra **Estado** (lo stato) no sentido moderno, como uma organização política impessoal, distinta da pessoa do governante, que detém o poder sobre um território e uma população. Antes, falava-se em reinos, cidades e principados. Essa novidade de vocabulário expressa uma nova forma de pensar a política, que se desenvolveria com a formação dos **Estados nacionais** e das monarquias absolutas. Sua defesa da unificação da Itália e do exército nacional também antecipou o **nacionalismo** e a ideia de que o Estado deve ser forte, para garantir a segurança e a ordem.',
    'A influência de Maquiavel foi enorme e ambígua. Autores como **Hobbes** retomaram sua visão realista da natureza humana e da necessidade de um poder forte, enquanto **Rousseau** viu em sua obra uma crítica ao poder dos príncipes. Na época da Contrarreforma, O Príncipe foi incluído no Index dos livros proibidos da Igreja, e o termo "maquiavélico" se popularizou como adjetivo para a astúcia e a falta de escrúpulos. Pensadores do século XX, como **Gramsci**, retomaram a imagem do "príncipe moderno", o partido político que organiza a vontade coletiva, e **Hannah Arendt** e **Isaiah Berlin** discutiram suas ideias sobre a ética e a política.',
    'Na atualidade, Maquiavel é lido como um autor que obriga a pensar sobre a **distância entre o discurso e a prática política**: a importância da imagem pública, das aparências e da comunicação, a tensão entre a ética e a eficácia, o papel do conflito, a necessidade de instituições capazes de limitar o poder e a relação entre liderança e circunstâncias. Seus conceitos são usados em análises de política, de marketing, de gestão e de relações internacionais. Estudá-lo permite compreender como o poder funciona, e, por meio dessa compreensão, criar mecanismos de controle democrático, que evitem o abuso, em vez de apenas aceitar a ideia de que "a política é assim".'
  ]});
  mq.txt.push(ult);
}
