/* Filosofia: textos corridos, temas 13 a 15 */
module.exports = [
{ t:'Iluminismo e Montesquieu', txt:[
 { h:'O Iluminismo na Filosofia: razão, liberdade e crítica', p:[
  'O **Iluminismo** (ou Ilustração, Esclarecimento) foi o movimento filosófico e cultural que dominou o século XVIII na Europa, em especial na França, e que defendeu o uso da **razão** como guia para o conhecimento e para a transformação da sociedade. Os iluministas, também chamados de "filósofos" (philosophes), acreditavam que a razão podia libertar o ser humano da ignorância, da superstição, do dogmatismo religioso e do despotismo político, e que o **progresso** da humanidade seria resultado da ciência, da educação e da reforma das instituições. Sua influência foi decisiva para as revoluções liberais e para a formação do mundo moderno.',
  'O movimento se apoiou na **Revolução Científica** (Newton) e na Filosofia dos séculos XVII (Descartes, Bacon, Locke). Seus principais pensadores incluem **Voltaire**, defensor da tolerância e da liberdade de expressão, **Rousseau**, **Diderot** e **D\'Alembert**, organizadores da **Enciclopédia**, **Montesquieu**, **Kant**, na Alemanha, e **Adam Smith** e **Hume**, na Escócia. Os "salões" aristocráticos, os cafés, as academias e a imprensa difundiam as novas ideias. A **Enciclopédia** (1751 a 1772) reuniu o saber da época, e foi um instrumento de crítica à tradição e de divulgação científica.',
  'Entre as ideias centrais do Iluminismo estão: a **razão** como instrumento de conhecimento e de crítica; a **liberdade** individual, de pensamento, de expressão e de consciência; a **igualdade** perante a lei e a crítica aos privilégios de nascimento; a **tolerância** religiosa; o **progresso** da humanidade; e o **direito natural** e os direitos universais do homem. No plano político, criticou o **absolutismo** e defendeu a limitação do poder, a separação dos poderes, o governo por leis e, em alguns autores, a soberania popular. No plano econômico, o liberalismo de Adam Smith defendeu a liberdade de mercado, em oposição ao mercantilismo.'] },
 { h:'Montesquieu: o espírito das leis e a separação dos poderes', p:[
  '**Charles-Louis de Secondat, barão de Montesquieu** (1689-1755), nasceu na França, em uma família nobre, e foi magistrado em Bordeaux. Escreveu as **Cartas Persas** (1721), uma sátira da sociedade francesa vista por viajantes persas, e, sobretudo, **O Espírito das Leis** (1748), seu principal livro, resultado de quase vinte anos de pesquisa. A obra é um estudo comparativo das leis e das instituições de diversos povos, e busca explicar, de modo racional, a diversidade das formas de governo e das leis, em vez de simplesmente julgá-las. Ele inaugurou, assim, uma abordagem que antecipa a **sociologia** e a ciência política.',
  'Para Montesquieu, as leis são "as relações necessárias que derivam da natureza das coisas", e dependem de vários fatores: o **clima**, o **território**, a **economia**, a **religião**, os costumes e a história de cada povo. Esse conjunto de fatores forma o "**espírito geral**" de uma nação, e as leis devem ser adequadas a ele. Por isso, não existe uma forma de governo ideal para todos os lugares e épocas. Ele distinguiu três **formas de governo**, cada uma com seu **princípio**: a **república**, baseada na **virtude** cívica; a **monarquia**, baseada na **honra**; e o **despotismo**, baseado no **medo**.',
  'A contribuição mais famosa de Montesquieu é a teoria da **separação dos poderes**. Observando a Inglaterra, ele concluiu que a **liberdade política** só existe onde o poder não é abusado, e que "é uma experiência eterna que todo homem que tem poder tende a abusar dele; vai até onde encontra limites". Por isso, "é preciso que, pela disposição das coisas, o poder freie o poder". Para evitar o abuso, o poder do Estado deve ser dividido em três poderes independentes e harmônicos, que se controlam mutuamente: o **Legislativo** (que faz as leis), o **Executivo** (que as executa) e o **Judiciário** (que julga). É o sistema dos **freios e contrapesos**.'] },
 { h:'O legado de Montesquieu e das ideias iluministas', p:[
  'A separação dos poderes tornou-se um princípio básico do **constitucionalismo** moderno. Está presente na Constituição dos Estados Unidos (1787), na **Declaração dos Direitos do Homem e do Cidadão** (1789), que afirma que "toda sociedade em que a garantia dos direitos não é assegurada, nem a separação dos poderes determinada, não tem Constituição", e na maioria das constituições atuais, inclusive a brasileira de 1988, que, no artigo 2º, estabelece que "são Poderes da União, independentes e harmônicos entre si, o Legislativo, o Executivo e o Judiciário". É uma garantia contra o abuso do poder e a concentração tirânica.',
  'Outros autores iluministas complementaram essa visão. **Voltaire** (1694-1778) defendeu a **tolerância** e a liberdade de pensamento, atacou o fanatismo e a intolerância da Igreja (no Tratado sobre a Tolerância, a respeito do caso Calas), e admirava a monarquia inglesa. **Rousseau** enfatizou a soberania popular. **Diderot** e a Enciclopédia difundiram a ciência e a crítica. **Cesare Beccaria** criticou a tortura e a pena de morte, e propôs penas proporcionais, em Dos Delitos e das Penas. **Kant** definiu o Esclarecimento como a saída da menoridade, e o lema "Sapere aude". O conjunto desses pensamentos moldou as ideias de cidadania, de direitos humanos e de democracia.',
  'O Iluminismo também recebeu **críticas**. A **Escola de Frankfurt**, com Adorno e Horkheimer, na **Dialética do Esclarecimento** (1947), argumentou que a razão iluminista, ao se tornar **instrumental**, voltada para o domínio da natureza e dos seres humanos, pode gerar novas formas de dominação e de barbárie, como mostram o totalitarismo, o Holocausto e a indústria cultural. Outras críticas apontam o **eurocentrismo** e o uso do discurso da razão para justificar o colonialismo, e a limitação dos direitos proclamados, que excluíam mulheres, escravizados e colonizados. Reconhecer esses limites não implica abandonar os ideais iluministas, mas ampliá-los e aplicá-los de forma coerente.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O Iluminismo e Montesquieu aparecem no ENEM com frequência, em questões com trechos de O Espírito das Leis (a separação dos poderes), de Kant (o Esclarecimento), de Voltaire (a tolerância) ou de textos que descrevem as ideias do movimento. As perguntas pedem a identificação do princípio (a limitação do poder pela divisão em três poderes), a relação com a Constituição brasileira, o sentido do esclarecimento e a crítica à razão instrumental. Também podem ser cobradas situações atuais, em que a harmonia entre os poderes, ou o abuso de um deles, é tema de debate.',
  'Pontos de atenção: Montesquieu propõe a separação dos poderes em Legislativo, Executivo e Judiciário, para que o poder freie o poder; o princípio de cada governo é a virtude (república), a honra (monarquia) e o medo (despotismo); as leis dependem do clima, da cultura e da história; Voltaire defende a tolerância e a liberdade de expressão; Kant define o esclarecimento como a coragem de usar a própria razão. Não confunda Montesquieu (separação dos poderes) com Locke (direitos naturais e governo limitado) nem com Rousseau (soberania popular e vontade geral). O Iluminismo também foi criticado por seu eurocentrismo.',
  'Para revisar, monte um quadro com os principais iluministas e suas ideias: Locke (direitos naturais), Montesquieu (separação dos poderes), Voltaire (tolerância), Rousseau (soberania popular), Diderot (Enciclopédia), Beccaria (penas) e Kant (esclarecimento). Relacione-os às revoluções do século XVIII (Americana e Francesa) e às instituições atuais (Constituição, direitos humanos, laicidade). Esse tema fecha a Filosofia política dos séculos XVII e XVIII, e prepara o seguinte, em que Hegel e Marx discutem a história, o trabalho e as contradições da sociedade capitalista, e abrem a filosofia do século XIX.'] }
]},
{ t:'Hegel e Marx', txt:[
 { h:'Hegel: razão, história e dialética', p:[
  '**Georg Wilhelm Friedrich Hegel** (1770-1831) foi um dos maiores filósofos do idealismo alemão, e sua obra, extensa e complexa, influenciou profundamente o pensamento do século XIX e do XX. Escreveu a **Fenomenologia do Espírito** (1807), a **Ciência da Lógica**, a **Enciclopédia das Ciências Filosóficas** e a **Filosofia do Direito** (1821), além de cursos sobre a Filosofia da História. Para Hegel, a realidade é um **processo racional**, e a Filosofia é a compreensão de seu tempo em pensamento. A frase "tudo o que é racional é real, e tudo o que é real é racional" resume a ideia de que a razão se manifesta na história.',
  'O conceito central é o **Espírito** (Geist), a razão que se realiza no mundo, e que se desenvolve ao longo da **história** em direção à **liberdade**. Para Hegel, a história universal é o progresso da consciência da liberdade: no Oriente, apenas um (o déspota) era livre; na Grécia e em Roma, alguns eram livres; no mundo germânico-cristão, todos são reconhecidos como livres, em princípio. Esse movimento não ocorre em linha reta, mas por meio de **conflitos e contradições**, e os grandes homens e as paixões são "astúcias da razão", que realizam fins que superam suas intenções.',
  'O método de Hegel é a **dialética**: o pensamento e a realidade se desenvolvem por meio de contradições. Em esquema, que é simplificado e nem sempre usado por ele, uma **tese** (uma afirmação) gera sua oposição, a **antítese**, e o conflito é resolvido em uma **síntese**, que supera (conserva e nega ao mesmo tempo, **Aufhebung**) as anteriores, e se torna uma nova tese. Assim, as contradições não são falhas, mas o **motor** do desenvolvimento. Na Fenomenologia, a **dialética do senhor e do escravo** descreve a luta por reconhecimento: o senhor depende do trabalho do escravo, que, ao transformar a natureza, desenvolve sua consciência, o que inverte a relação.'] },
 { h:'Marx: materialismo histórico, trabalho e luta de classes', p:[
  '**Karl Marx** (1818-1883), alemão, estudou Filosofia, foi influenciado por Hegel, mas criticou seu idealismo. Perseguido, viveu exilado em Paris, Bruxelas e Londres, e escreveu, com **Friedrich Engels**, o **Manifesto Comunista** (1848), além de **A Ideologia Alemã**, os **Manuscritos Econômico-Filosóficos** e **O Capital** (1867), sua obra principal. Marx manteve a **dialética** de Hegel, mas a "colocou de pé": em vez de ser o Espírito que move a história, são as **condições materiais** de existência, isto é, o modo como os seres humanos produzem sua vida, que determinam a consciência. Daí a expressão **materialismo histórico**, ou "materialismo dialético".',
  'Para Marx, o ser humano se define pelo **trabalho**, atividade pela qual transforma a natureza e a si mesmo. Em cada época histórica, existe um **modo de produção**, formado pelas **forças produtivas** (instrumentos, técnicas, trabalhadores) e pelas **relações de produção** (a organização social do trabalho e da propriedade). Esse conjunto forma a **infraestrutura** (base econômica), sobre a qual se ergue a **superestrutura**: as instituições jurídicas e políticas, a religião, a arte e as ideias dominantes. "Não é a consciência dos homens que determina o seu ser, mas, ao contrário, o seu ser social que determina a sua consciência."',
  'A história é movida pela **luta de classes**: "a história de todas as sociedades até hoje é a história da luta de classes". Homens livres e escravos, patrícios e plebeus, senhores feudais e servos, burgueses e proletários se opõem. Na sociedade capitalista, a **burguesia** possui os **meios de produção** e o **proletariado**, que só possui sua força de trabalho, é obrigado a vendê-la em troca de salário. O capitalismo, ao acumular riqueza, produz também a desigualdade e crises, e cria as condições de sua própria superação: o proletariado, consciente, faria uma **revolução** e instauraria o **socialismo** e, depois, o **comunismo**, uma sociedade sem classes e sem exploração.'] },
 { h:'Alienação, mais-valia e ideologia', p:[
  'Nos Manuscritos de 1844, Marx descreve a **alienação** (ou estranhamento) do trabalhador no capitalismo. O trabalhador é alienado em quatro sentidos: do **produto** de seu trabalho, que pertence ao capitalista; do **processo** do trabalho, que é repetitivo, controlado e sem sentido; de sua **natureza humana** (o trabalho, que deveria ser realização criativa, torna-se mero meio de subsistência); e dos **outros seres humanos**, com quem compete. Quanto mais o trabalhador produz, mais pobre ele fica, e mais poder tem o capital. A alienação é, portanto, a perda do controle sobre o próprio trabalho e a própria vida.',
  'Em **O Capital**, Marx analisa o funcionamento do capitalismo. A **mercadoria** tem **valor de uso** (utilidade) e **valor de troca**. O valor é determinado pelo **tempo de trabalho socialmente necessário** à sua produção. O trabalhador recebe um salário que corresponde ao valor de sua força de trabalho, mas produz mais valor do que recebe: a diferença é a **mais-valia**, apropriada pelo capitalista, e que é a fonte do lucro. Assim, a exploração não decorre de um roubo ou fraude, mas do funcionamento normal do sistema. Marx também descreve o **fetichismo da mercadoria**: as relações entre as pessoas aparecem como relações entre coisas, escondendo a origem social do valor.',
  'A **ideologia**, para Marx, é um conjunto de ideias que expressam a visão de mundo da classe dominante e ocultam a realidade das relações de poder: "as ideias da classe dominante são, em cada época, as ideias dominantes". A educação, a religião e os meios de comunicação reproduzem essa visão, que apresenta a ordem existente como natural, e justifica a desigualdade (como a ideia de que a pobreza é falta de esforço). Essa noção de ideologia influenciou a Sociologia, a Escola de Frankfurt e a teoria crítica. A crítica da ideologia tem o objetivo de desvelar os interesses por trás das ideias, e de promover a consciência de classe e a emancipação.'] },
 { h:'Legado, críticas e atualidade', p:[
  'O pensamento de Marx teve enorme impacto. Inspirou movimentos operários, partidos socialistas e comunistas, e revoluções (Rússia, 1917; China, 1949; Cuba, 1959), embora os regimes que se diziam marxistas tenham praticado autoritarismo e violência, muito distantes do ideal de emancipação. Na **Sociologia**, influenciou a análise da desigualdade e da dominação, e, na **Economia**, a crítica ao capitalismo. Na Filosofia, deu origem ao **marxismo** e a diversas vertentes: Gramsci (hegemonia), Lukács, a Escola de Frankfurt, Althusser, e, na América Latina, a teologia da libertação e o pensamento dependentista.',
  'As **críticas** a Marx incluem: o **determinismo econômico**, que subestimaria o papel da política, da cultura e da religião; o fracasso de previsões, como a de que a revolução ocorreria nos países capitalistas mais avançados; os problemas de **planificação** e de **liberdade** nas economias socialistas; e a pouca atenção a questões de gênero, raça e meio ambiente. Defensores respondem que sua análise do capitalismo, de suas crises, da desigualdade e da alienação continua pertinente, e que as distorções dos regimes socialistas não decorrem necessariamente de suas ideias. Em tempos de globalização, de precarização do trabalho e de concentração de renda, conceitos como mais-valia e alienação são retomados.',
  'Hegel e Marx representam, assim, uma virada: a Filosofia passa a pensar a **história** e as **contradições sociais**. Marx escreveu, nas **Teses sobre Feuerbach**, que "os filósofos apenas interpretaram o mundo de diferentes maneiras; o que importa é transformá-lo". Essa frase expressa o caráter **prático** de seu pensamento. Para o estudante, é importante compreender os conceitos de forma crítica e histórica, sem caricaturas, entendendo suas contribuições e seus limites, e relacioná-los com a Sociologia (Marx é um dos clássicos), com a História (Revolução Industrial) e com a atualidade (trabalho e desigualdade).'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Hegel e Marx aparecem no ENEM em questões com trechos do Manifesto Comunista ou de O Capital, e pedem a identificação de conceitos como luta de classes, trabalho alienado, mais-valia, ideologia, infraestrutura e superestrutura, e a análise de situações atuais, como o trabalho precário, a exploração, a desigualdade e o consumismo. Hegel aparece, sobretudo, pela dialética e pela ideia de história como processo. As provas valorizam a capacidade de aplicar os conceitos a exemplos concretos e de relacioná-los com a Sociologia e a História.',
  'Pontos de atenção: para Marx, a base material (economia) determina, em última instância, a superestrutura (política, direito, ideias); a história é a luta de classes; no capitalismo, burguesia e proletariado se opõem; a mais-valia é o trabalho não pago apropriado pelo capitalista; a alienação é a perda do controle sobre o trabalho; a ideologia oculta a dominação. Em Hegel, a dialética é o movimento por contradições, e o Espírito se realiza na história. Evite confundir Marx com os regimes que se disseram marxistas, e com o determinismo simplista.',
  'Para revisar, escreva em poucas linhas cada conceito (alienação, mais-valia, ideologia, luta de classes, modo de produção) com um exemplo atual, como o trabalho por aplicativo. Faça um esquema da relação entre infraestrutura e superestrutura. Compare Hegel (o Espírito move a história) e Marx (as condições materiais movem a história). Esse tema se conecta à Escola de Frankfurt, que veremos adiante, e à Sociologia, e prepara o estudo de Nietzsche, que critica a moral, a razão e os valores da modernidade por outro caminho.'] }
]},
{ t:'Nietzsche', txt:[
 { h:'Nietzsche, vida e obra: o filósofo do martelo', p:[
  '**Friedrich Nietzsche** (1844-1900) nasceu na Prússia, filho de um pastor luterano, e foi um brilhante filólogo clássico, que se tornou professor na Universidade da Basileia aos 24 anos. Adoeceu, deixou a universidade e viveu como um andarilho, escrevendo em hotéis e pensões da Suíça, da Itália e da França. Em 1889, teve um colapso mental, e passou os últimos anos sem lucidez. Sua obra, escrita em forma de **aforismos**, de ensaios e de poemas, de estilo literário e provocador, inclui **O Nascimento da Tragédia**, **Humano, Demasiado Humano**, **A Gaia Ciência**, **Assim Falou Zaratustra**, **Além do Bem e do Mal**, **Genealogia da Moral** e **Crepúsculo dos Ídolos**.',
  'Nietzsche se autodefinia como alguém que filosofava "**com o martelo**": não para construir um sistema, mas para **demolir** os "ídolos", as crenças e valores que a cultura ocidental aceitava sem crítica, para "auscultá-los" e ver se soam ocos. Sua filosofia é uma **crítica radical da cultura**, da moral, da religião, da ciência e da própria Filosofia, em nome da **vida**. Para ele, os valores devem ser julgados por sua capacidade de **afirmar** ou de **negar** a vida: valores que empobrecem a vida e fazem as pessoas desprezarem o corpo, o mundo e os instintos são sintomas de decadência.',
  'Nietzsche foi influenciado por Schopenhauer, pela Grécia pré-socrática e pelos trágicos, e se opôs ao racionalismo, ao cristianismo, ao idealismo e ao otimismo do progresso. Seu pensamento foi mal compreendido e deturpado, em especial por sua irmã, Elisabeth, que o associou ao nacionalismo e ao antissemitismo, e pelos nazistas, que o utilizaram indevidamente. Nietzsche, na verdade, criticava o antissemitismo e o nacionalismo alemão. Sua obra deve ser lida com cuidado, em sua complexidade e em suas imagens, e não por meio de frases isoladas. É um dos pensadores que mais influenciaram a filosofia do século XX.'] },
 { h:'O apolíneo e o dionisíaco, a morte de Deus e o niilismo', p:[
  'Em **O Nascimento da Tragédia** (1872), Nietzsche interpreta a cultura grega a partir de dois impulsos, simbolizados por dois deuses. O **apolíneo**, de Apolo, é o impulso da ordem, da forma, da medida, da clareza e da individualidade, expresso nas artes plásticas e no sonho. O **dionisíaco**, de Dioniso, é o impulso da embriaguez, do êxtase, da desmedida, da música e da dissolução do indivíduo na unidade da vida, com seu lado trágico. A tragédia grega nasceu da união dos dois, e permitiu aos gregos afirmar a vida, mesmo com seu sofrimento. Para Nietzsche, essa harmonia foi rompida por **Sócrates** e pelo racionalismo, que valorizaram a razão e desprezaram os instintos.',
  'Em **A Gaia Ciência**, Nietzsche faz a célebre declaração: "**Deus está morto**". Não é uma afirmação de ateísmo simples, mas o diagnóstico de um acontecimento cultural: a fé no Deus cristão, que fundamentava a moral e o sentido da vida no Ocidente, perdeu a credibilidade, com o avanço da ciência e do racionalismo. O problema é que, sem esse fundamento, desaparece a base dos valores supremos, e ameaça-se cair no **niilismo**, a experiência de que "os valores supremos perdem o valor", e de que a vida não tem sentido. Nietzsche vê o niilismo como um perigo, mas também como uma oportunidade de criação de novos valores.',
  'Ele distingue o **niilismo passivo** (a resignação, a fuga em consolos e a negação da vida) do **ativo** (a destruição dos velhos valores, para abrir espaço ao novo). Para superá-lo, é necessário criar novos valores, em um movimento de **transvaloração de todos os valores**. A crítica de Nietzsche se estende à metafísica e à ideia de uma verdade absoluta: ele propõe o **perspectivismo**, a ideia de que não há fatos, apenas interpretações, e de que todo conhecimento é feito de uma perspectiva, ligada à vida e ao poder. Essa posição influenciou o pós-estruturalismo e a hermenêutica, e é muitas vezes relacionada ao relativismo, embora ele criticasse a falta de rigor intelectual.'] },
 { h:'A genealogia da moral: moral dos senhores e moral dos escravos', p:[
  'Na **Genealogia da Moral** (1887), Nietzsche investiga a **origem histórica** dos valores morais, em vez de aceitá-los como eternos. Distingue dois tipos de moral. A **moral dos senhores** (ou nobre) nasce da afirmação de si: os fortes, os nobres, chamam de "bom" a si mesmos, ao que é poderoso, saudável e criativo, e de "ruim" ao que é comum e fraco. É uma moral afirmativa, que valoriza a coragem, a força, a vitalidade e a criação. A **moral dos escravos** (ou do ressentimento) nasce da reação dos fracos, que, impotentes para vencer os fortes, invertem os valores: chamam de "mau" o que é forte e orgulhoso, e de "bom" o humilde, o fraco e o sofredor.',
  'O **ressentimento** é o sentimento do que não pode agir e se vinga imaginariamente: é a raiz da moral dos escravos, que, para Nietzsche, está na base da moral cristã e da moral ocidental, que valorizam a piedade, a humildade, a culpa e a renúncia. Ele critica a **má consciência**, a culpa e o "ideal ascético", que desvalorizam a vida terrena, o corpo e os instintos, em nome de um "outro mundo". Para ele, essa moral nega a vida e é sintoma de decadência. Nietzsche não faz um elogio à crueldade ou à dominação: trata-se de uma crítica aos valores que apequenam a vida e impedem a criação.',
  'Esse enfoque é chamado de **genealogia**, um método histórico e psicológico que mostra que os valores têm uma origem, interesses e relações de poder, e que não são naturais ou universais. Foi retomado por **Michel Foucault**, que aplicou a genealogia ao poder, à prisão e à sexualidade. A pergunta que Nietzsche faz é: "que valor têm os nossos valores?", e quer saber se eles favorecem ou prejudicam o florescimento humano. Essa postura de suspeita crítica, em relação às ideias que parecem óbvias, é um legado importante, e dialoga com Marx (ideologia) e Freud (o inconsciente), os três chamados de "mestres da suspeita", por Paul Ricoeur.'] },
 { h:'O além-do-homem, o eterno retorno e a vontade de potência', p:[
  'Em **Assim Falou Zaratustra** (1883 a 1885), Nietzsche apresenta o personagem de Zaratustra, que anuncia o **além-do-homem** (ou super-homem, Übermensch), o ser humano que supera a si mesmo e cria novos valores, ao afirmar a vida e a terra. Não é uma raça superior, nem um tirano, mas um ideal de superação: aquele que se torna "o que é", em um processo de criação de si, sem recorrer a consolos metafísicos ou religiosos. As **três metamorfoses do espírito** descrevem o caminho: o **camelo** (que carrega o peso dos deveres), o **leão** (que diz "não" e conquista a liberdade) e a **criança** (que é inocência, esquecimento, jogo e começo, capaz de criar valores).',
  'O **eterno retorno** é a ideia de que tudo retorna, infinitas vezes, da mesma forma. Nietzsche a apresenta como um **teste** ético e existencial: se você tivesse de viver sua vida, exatamente como ela é, repetida eternamente, o que sentiria? Aceitaria com alegria, ou com horror? A pessoa que consegue dizer "sim" a esse retorno é aquela que **afirma a vida**, inclusive seu sofrimento, em um **amor fati** (amor ao destino). Já a **vontade de potência** (vontade de poder) é, para Nietzsche, a força fundamental da vida: não o mero desejo de dominação, mas a tendência da vida a crescer, a se expandir, a se superar e a criar.',
  'A filosofia de Nietzsche influenciou o **existencialismo** (Sartre, Camus), a **psicanálise** (Freud), o **pós-estruturalismo** (Foucault, Deleuze, Derrida), a literatura e as artes. Também é muito utilizada, de modo simplificado, em livros de autoajuda, o que exige cuidado. A principal lição é a necessidade de **pensar de modo crítico e criativo**, de questionar os valores herdados, de assumir a responsabilidade pela própria vida e de afirmar a existência, apesar do sofrimento. Ao mesmo tempo, sua obra levanta questões sobre os riscos de uma moral sem fundamentos e do individualismo, que precisam ser discutidos com atenção.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Nietzsche aparece no ENEM em questões que trazem trechos de Assim Falou Zaratustra, de A Gaia Ciência ou da Genealogia da Moral, e pedem para identificar conceitos como a morte de Deus, o niilismo, a transvaloração dos valores, a moral dos escravos e dos senhores, o apolíneo e o dionisíaco e a vontade de potência. Também podem pedir a relação entre a crítica nietzschiana aos valores e situações do cotidiano, como o consumismo, a padronização e o conformismo, e a comparação com Marx e com Freud.',
  'Pontos de atenção: "Deus está morto" é um diagnóstico cultural sobre a perda de fundamento dos valores, e não uma simples declaração de ateísmo; o niilismo é a perda do sentido; a transvaloração é a criação de novos valores; a moral dos escravos nasce do ressentimento; o apolíneo é a ordem e o dionisíaco é o êxtase e a vida; o além-do-homem é o criador de valores; e o eterno retorno é um teste de afirmação da vida. Evite associar Nietzsche ao nazismo ou à apologia da violência, o que é uma distorção, e não confunda "vontade de potência" com mero desejo de dominar os outros.',
  'Para revisar, monte um quadro com os conceitos (apolíneo e dionisíaco, morte de Deus, niilismo, genealogia, moral dos senhores e dos escravos, além-do-homem, eterno retorno, vontade de potência) e escreva uma frase de cada. Relacione Nietzsche com o existencialismo, o próximo tema, que parte da ideia de que a vida não tem sentido dado e de que cada um deve criar o seu, e com Foucault, que usou a genealogia para analisar o poder. Esse tema encerra a trilogia de filósofos do século XIX (Hegel, Marx e Nietzsche), que transformaram a Filosofia contemporânea.'] }
]}
];

/* quinto bloco do tema Iluminismo e Montesquieu */
{
  const il = module.exports[0];
  const ult = il.txt.pop();
  il.txt.push({ h:'Liberalismo, economia e as revoluções do século XVIII', p:[
    'No campo econômico, o Iluminismo produziu o **liberalismo econômico**. O escocês **Adam Smith**, em A Riqueza das Nações (1776), argumentou que a riqueza vem do **trabalho** e da **divisão do trabalho**, e que, em um mercado livre, a busca de cada um pelo próprio interesse resulta, como se guiada por uma "**mão invisível**", em benefício de toda a sociedade. Defendeu a livre concorrência e a redução da intervenção do Estado, em oposição ao **mercantilismo**, que defendia o monopólio e o protecionismo. Os **fisiocratas**, na França, também afirmavam a liberdade econômica ("laissez-faire, laissez-passer"), e valorizavam a agricultura como fonte de riqueza.',
    'As ideias iluministas inspiraram as grandes revoluções. A **Revolução Americana** (1776) proclamou, na Declaração de Independência, que todos os homens são criados iguais e têm direitos inalienáveis à vida, à liberdade e à busca da felicidade, e a Constituição de 1787 adotou a separação dos poderes. A **Revolução Francesa** (1789) aboliu os privilégios do Antigo Regime e proclamou a liberdade, a igualdade e a fraternidade, na Declaração dos Direitos do Homem e do Cidadão. Na América Latina, as independências e os movimentos como a Inconfidência Mineira, no Brasil, foram influenciados por esses ideais. Ao mesmo tempo, as contradições entre os princípios e a prática, como a manutenção da escravidão, foram objeto de crítica e de lutas.',
    'O Iluminismo também influenciou o **despotismo esclarecido**, em que monarcas como Frederico II, da Prússia, Catarina II, da Rússia, José II, da Áustria, e o Marquês de Pombal, em Portugal, adotaram reformas inspiradas nas ideias iluministas, sem abrir mão do poder absoluto. Na educação, difundiu a ideia de **instrução pública** e de formação do cidadão. Na justiça, inspirou a humanização das penas e a presunção de inocência. No campo da religião, defendeu a tolerância e a separação entre Igreja e Estado. Esses legados explicam por que o Iluminismo é considerado a base ideológica da modernidade política, jurídica e científica.'
  ]});
  il.txt.push(ult);
}
