/* Filosofia: textos corridos, temas 10 a 12 */
module.exports = [
{ t:'Racionalismo e empirismo', txt:[
 { h:'O contexto da Filosofia moderna e o problema do conhecimento', p:[
  'A **Filosofia moderna** começa no século XVII, em um contexto de grandes transformações: o Renascimento, a Reforma Protestante, as Grandes Navegações e, sobretudo, a **Revolução Científica**, com Copérnico, Galileu, Kepler e Newton, que mostrou que a natureza pode ser descrita por leis matemáticas e investigada por observação e experimento. A autoridade da tradição e da Igreja foi abalada, e os filósofos passaram a se perguntar: como podemos ter conhecimento seguro? Qual é o método correto? Quais são a origem e os limites do conhecimento? Surge, assim, a **teoria do conhecimento** (epistemologia) como centro da reflexão.',
  'Duas respostas principais foram dadas. O **racionalismo**, desenvolvido sobretudo no continente europeu, afirma que a **razão** é a fonte principal e mais segura do conhecimento: as verdades universais e necessárias, como as da matemática, não vêm dos sentidos, que enganam, mas de ideias que a razão encontra em si mesma. O **empirismo**, desenvolvido principalmente na Inglaterra, sustenta que todo conhecimento vem da **experiência** sensível: a mente, ao nascer, é como uma folha em branco, e as ideias são construídas a partir das impressões dos sentidos.',
  'Os principais representantes do racionalismo são **Descartes**, **Espinosa** e **Leibniz**. Do empirismo, **Francis Bacon**, **Thomas Hobbes** (em parte), **John Locke**, **George Berkeley** e **David Hume**. As duas correntes concordam sobre a importância do método e da crítica à autoridade, mas divergem sobre a origem das ideias. O problema foi, em parte, sintetizado por **Kant**, que mostrou que o conhecimento resulta da combinação entre a experiência e as estruturas da razão. Para o ENEM, é essencial saber diferenciar as duas posições e associá-las a seus autores e a suas ideias centrais.'] },
 { h:'Descartes e o racionalismo', p:[
  '**René Descartes** (1596-1650), francês, é considerado o "pai da Filosofia moderna". Matemático e cientista, criou a geometria analítica e escreveu o **Discurso do Método** (1637) e as **Meditações Metafísicas** (1641). Insatisfeito com os saberes de sua época, propôs um **método** para chegar à verdade, inspirado na matemática, com quatro regras: **evidência** (só aceitar como verdadeiro o que se apresenta de modo claro e distinto), **análise** (dividir as dificuldades em partes), **síntese** (ordenar os pensamentos, do simples ao complexo) e **enumeração** (revisões completas, para não omitir nada).',
  'Para encontrar uma verdade indubitável, Descartes usa a **dúvida metódica**, uma dúvida provisória e radical: duvida dos sentidos, que às vezes nos enganam; da distinção entre sonho e vigília; e até das verdades matemáticas, imaginando a hipótese de um **gênio maligno** que nos engane sempre. Mas, mesmo duvidando de tudo, há algo de que não posso duvidar: que estou duvidando, e, portanto, **pensando**. Daí a célebre conclusão: "**penso, logo existo**" (cogito, ergo sum). O **cogito** é a primeira certeza, o fundamento sobre o qual se reconstrói o conhecimento, e coloca o **sujeito pensante** no centro da Filosofia.',
  'A partir do cogito, Descartes prova a existência de **Deus**, perfeito e veraz, que garante que as ideias claras e distintas são verdadeiras, e a existência do mundo material. Defende o **dualismo**: o ser humano é composto de duas substâncias distintas, a **alma** (res cogitans, a coisa pensante, imaterial) e o **corpo** (res extensa, a coisa extensa, material). Isso gera o problema da interação entre ambos, que ele propôs resolver na glândula pineal. O corpo e a natureza funcionam como máquinas, segundo leis mecânicas, o que favorece a ciência. Para Descartes, as **ideias inatas** (como Deus, a alma e os princípios matemáticos) existem na mente, independentemente da experiência.'] },
 { h:'O empirismo: Bacon, Locke, Berkeley e Hume', p:[
  '**Francis Bacon** (1561-1626) foi um precursor do empirismo e da ciência experimental. No **Novum Organum**, criticou a lógica aristotélica e propôs o **método indutivo**: partir da observação e da experimentação de casos particulares para chegar às leis gerais. Antes, o cientista deve se libertar dos **ídolos**, preconceitos que obstruem o conhecimento: os da **tribo** (limitações da natureza humana), da **caverna** (preconceitos individuais), do **foro** ou mercado (erros da linguagem) e do **teatro** (doutrinas filosóficas aceitas sem crítica). Sua máxima "saber é poder" expressa a ideia de que o conhecimento da natureza deve servir ao domínio e ao benefício humanos.',
  '**John Locke** (1632-1704), no **Ensaio sobre o Entendimento Humano**, nega as **ideias inatas**: a mente, ao nascer, é uma **tábula rasa** (folha em branco), e todo conhecimento vem da **experiência**, que pode ser de dois tipos: a **sensação** (percepção dos objetos externos) e a **reflexão** (percepção das operações da própria mente). As ideias simples, obtidas dessas fontes, combinam-se em ideias complexas. Locke distinguiu as **qualidades primárias** (extensão, forma e movimento, que pertencem aos objetos) das **secundárias** (cor, sabor, odor, que dependem do sujeito). **George Berkeley** radicalizou o empirismo: "ser é ser percebido" (esse est percipi), negando a existência da matéria independente da percepção.',
  '**David Hume** (1711-1776) levou o empirismo às últimas consequências. Distinguiu as **impressões** (percepções vivas, diretas) das **ideias** (cópias enfraquecidas das impressões), e sustentou que todo conhecimento factual vem da experiência. Questionou a noção de **causalidade**: o que observamos é a sucessão regular de dois eventos (o fogo e o calor), mas nunca a "conexão necessária" entre eles. Acreditamos na causalidade por **hábito** (costume) criado pela repetição, e não por razão. Isso implica que a ciência não oferece certezas absolutas, mas apenas **probabilidades**. Hume também criticou a ideia de uma substância e de um "eu" permanente: o eu seria um feixe de percepções.'] },
 { h:'Comparação, críticas e legado', p:[
  'Comparando as duas correntes: o **racionalismo** valoriza a razão e a dedução, defende a existência de ideias inatas e tem a matemática como modelo de conhecimento seguro; o **empirismo** valoriza a experiência e a indução, nega as ideias inatas e tem as ciências da natureza como modelo. Os racionalistas desconfiam dos sentidos, que enganam, e os empiristas desconfiam das ideias sem origem na experiência. Os racionalistas buscam verdades **necessárias e universais**, e os empiristas se contentam com verdades **prováveis**. Ambos tinham razão em parte, e cada um destacava um aspecto do processo de conhecer.',
  'Essa oposição foi mediada por **Immanuel Kant**, que despertou "do sono dogmático" ao ler Hume, e propôs uma síntese: o conhecimento começa com a experiência, mas depende das estruturas da razão (as formas da sensibilidade e as categorias do entendimento), que organizam o que recebemos. "Pensamentos sem conteúdo são vazios, intuições sem conceitos são cegas." Assim, a razão sem a experiência é vazia, e a experiência sem a razão é desordenada. A **revolução copernicana** de Kant, que coloca o sujeito como condição do conhecimento, é um marco, e será estudada no próximo tema.',
  'O legado dessas correntes é imenso. O racionalismo inspirou a matematização da natureza e a Filosofia da mente; o empirismo, a ciência experimental, o liberalismo político (Locke) e a filosofia analítica. O método cartesiano e o método indutivo de Bacon são a base do método científico moderno, que combina hipóteses racionais com observação e teste. A dúvida cartesiana e o ceticismo de Hume ensinam a **ter cautela** com as certezas e a verificar os fundamentos do que se acredita. Essas lições são muito úteis hoje, no combate à desinformação e na valorização do pensamento científico e crítico.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O racionalismo e o empirismo aparecem no ENEM em questões com trechos de Descartes (a dúvida metódica, o cogito, a razão) e de Locke, Bacon ou Hume (a experiência, a tábula rasa, os ídolos), em que se pede para identificar a posição, comparar as duas correntes ou aplicá-las a situações do cotidiano e da ciência. Também aparecem questões sobre o método científico, o papel da dúvida, a relação entre razão e experiência no desenvolvimento do conhecimento, e a importância da evidência.',
  'Pontos de atenção: o racionalismo (Descartes) valoriza a razão e as ideias inatas; o empirismo (Locke, Bacon e Hume) valoriza a experiência e a indução; a dúvida de Descartes é metódica, provisória, e não cética; o cogito é a primeira certeza; Locke fala de tábula rasa; Bacon propõe o método indutivo e critica os ídolos; Hume critica a causalidade, que seria hábito. Evite confundir a dúvida metódica com o ceticismo, que mantém a suspensão do juízo. Associe cada autor a uma frase: "penso, logo existo" (Descartes), "saber é poder" (Bacon), "tábula rasa" (Locke).',
  'Para revisar, monte um quadro com racionalismo e empirismo (origem do conhecimento, método, ideias inatas, modelo de ciência e autores). Treine explicar a dúvida cartesiana e o cogito com suas palavras, e dê um exemplo de indução e de dedução. Esse tema prepara o seguinte, Kant, que reconcilia as duas correntes, e, por consequência, estabelece uma nova visão do conhecimento e da moral, e uma ética do dever que também será muito cobrada.'] }
]},
{ t:'Kant e a ética do dever', txt:[
 { h:'Kant, o Iluminismo e a revolução copernicana', p:[
  '**Immanuel Kant** (1724-1804), nascido em Königsberg, na Prússia, é um dos maiores filósofos de todos os tempos. Professor universitário, levou uma vida metódica, e escreveu obras fundamentais: a **Crítica da Razão Pura** (1781), sobre o conhecimento; a **Crítica da Razão Prática** (1788) e a **Fundamentação da Metafísica dos Costumes** (1785), sobre a moral; e a **Crítica do Juízo** (1790), sobre a estética. Kant é o grande filósofo do **Iluminismo**. Em um texto de 1784, "Resposta à pergunta: o que é o Esclarecimento?", define-o como a saída do ser humano de sua **menoridade**, da qual ele próprio é culpado, e apresenta o lema "**Sapere aude**", ou seja, "ousa saber, tem a coragem de usar o teu próprio entendimento".',
  'Kant buscou resolver o impasse entre o racionalismo e o empirismo. Fez uma "**revolução copernicana**" na Filosofia: assim como Copérnico inverteu a relação entre o Sol e a Terra, Kant inverteu a relação entre o sujeito e o objeto. Em vez de supor que o conhecimento deve se conformar aos objetos, supôs que **os objetos se conformam às estruturas do sujeito** que conhece. O conhecimento resulta da combinação entre a **sensibilidade**, que fornece o conteúdo da experiência por meio das formas puras do **espaço** e do **tempo**, e o **entendimento**, que organiza esse conteúdo, por meio de **categorias** (como causalidade e substância).',
  'Essa teoria implica uma distinção entre o **fenômeno** (a coisa tal como aparece a nós, ou seja, estruturada pela nossa sensibilidade e entendimento) e o **númeno** ou "coisa em si" (a coisa tal como é independentemente do sujeito), que não podemos conhecer. Assim, o conhecimento científico é possível e universal, mas limitado ao mundo dos fenômenos. Questões como a existência de Deus, a imortalidade da alma e a liberdade não podem ser demonstradas pela razão teórica, que cai em contradições (antinomias) ao ultrapassar esses limites. Ela não nega essas ideias, mas as remete à razão prática, no campo da moral.'] },
 { h:'Autonomia, boa vontade e a ética do dever', p:[
  'Na moral, Kant buscou fundamentar princípios universais, válidos para todos, independentemente de interesses, inclinações e consequências. Seu ponto de partida é que a única coisa boa sem restrição é a **boa vontade**, isto é, a vontade que age por **dever**, e não por interesse, inclinação ou medo. Uma ação tem valor moral quando é realizada **por dever**, e não apenas **conforme ao dever**. Um comerciante que não engana os clientes porque teme perder a reputação age conforme ao dever; o que o faz por respeito à honestidade age por dever. O valor da ação está na **intenção** (na máxima que a orienta), e não em seus resultados.',
  'A moral kantiana se baseia na **autonomia**: o ser humano, por ser racional, é capaz de dar a si mesmo a lei moral, e não depender de uma autoridade externa (religiosa ou política) ou de seus desejos (heteronomia). Agir moralmente é agir segundo a lei que a **razão** reconhece como universal. Por isso, a moral kantiana é **deontológica** (do grego deon, "dever"), em oposição às éticas **consequencialistas**, como o utilitarismo, que julgam a ação pelas consequências. Kant considera que a liberdade é a condição da moral: somos responsáveis porque podemos escolher agir segundo a lei moral.',
  'Os imperativos que orientam a ação podem ser **hipotéticos**, que dizem o que fazer para alcançar um fim ("se queres ser saudável, pratica exercícios"), e dependem de um desejo, ou **categóricos**, que ordenam a ação por si mesma, de modo incondicional ("não mintas"). Os imperativos morais são categóricos: valem para todos, sempre, independentemente do que se deseje. Esse caráter incondicional dá à moral sua dignidade e distingue-a da prudência e da conveniência. A pergunta de Kant, "o que devo fazer?", é respondida pelo imperativo categórico, que se expressa em várias formulações.'] },
 { h:'O imperativo categórico e suas formulações', p:[
  'A formulação mais conhecida do **imperativo categórico** é a da **lei universal**: "**age somente segundo uma máxima tal que possas querer ao mesmo tempo que ela se torne lei universal**". Isso significa que, antes de agir, devemos verificar se o princípio que orienta nossa ação (a máxima) poderia ser adotado por todos, sem contradição. Por exemplo, a máxima "posso fazer promessas falsas para obter vantagens" não pode ser universalizada, pois, se todos mentissem, ninguém acreditaria em promessas, e a própria prática de prometer se tornaria impossível. Portanto, mentir é moralmente errado, em qualquer circunstância.',
  'A segunda formulação é a da **humanidade como fim em si**: "**age de tal maneira que uses a humanidade, tanto na tua pessoa como na pessoa de qualquer outro, sempre ao mesmo tempo como fim e nunca meramente como meio**". Os seres racionais têm **dignidade**, um valor absoluto, que não tem preço e não pode ser substituído por nada. Por isso, não devemos tratar as pessoas apenas como instrumentos para os nossos interesses. Essa formulação é a base da ideia moderna de **dignidade humana** e dos **direitos humanos**, e é usada para criticar a escravidão, a exploração, o trabalho degradante e a manipulação das pessoas.',
  'A terceira formulação é a da **autonomia**: agir de modo que a vontade possa se considerar, ao mesmo tempo, legisladora universal. Em sociedade, os seres racionais formam um "**reino dos fins**", em que cada um é legislador e súdito das leis morais. Kant aplicou essas ideias à política: propôs um Estado de direito (republicano), em que as leis garantam a liberdade de todos, e, em **A Paz Perpétua** (1795), a ideia de uma federação de Estados livres e de uma ordem cosmopolita, que antecipa as organizações internacionais. A moral kantiana é criticada por seu formalismo e rigor (como o dever de não mentir nunca), mas continua uma referência da ética contemporânea.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Kant é um dos autores mais frequentes do ENEM. As questões trazem trechos da Fundamentação da Metafísica dos Costumes ou do texto sobre o Esclarecimento, e pedem a identificação da ideia de autonomia, de dever, do imperativo categórico, da dignidade humana ("tratar as pessoas como fim e nunca como meio") ou da maioridade e da menoridade intelectual. Outras questões aplicam o imperativo categórico a situações práticas, como a mentira, a corrupção e o desrespeito às pessoas, e pedem para avaliar se a ação é moralmente aceitável pelo critério kantiano.',
  'Pontos de atenção: para Kant, a moral é autônoma, universal e racional; o valor moral está na intenção (agir por dever), e não nas consequências; o imperativo categórico ordena de forma incondicional, e o hipotético depende de um fim; a pessoa tem dignidade e nunca deve ser tratada apenas como meio; "Sapere aude" resume o Iluminismo; e o conhecimento resulta da síntese entre sensibilidade e entendimento. Para aplicar o teste da universalização, pergunte: "e se todos agissem assim?". Evite confundir Kant com o utilitarismo, que julga pelas consequências, ou com a moral religiosa, baseada na autoridade divina.',
  'Para revisar, escreva as três formulações do imperativo categórico em suas palavras e crie um exemplo para cada uma. Monte um quadro: conhecimento (fenômeno e númeno, categorias) e moral (boa vontade, dever, autonomia, imperativos). Compare Kant com Aristóteles (virtude e felicidade) e com os utilitaristas (consequências). Esse tema se conecta ao seguinte, o contratualismo (Hobbes, Locke e Rousseau), que discute a origem do Estado e da sociedade política, e ao Iluminismo em geral, de que Kant é um dos maiores expoentes.'] }
]},
{ t:'Contratualismo: Hobbes, Locke e Rousseau', txt:[
 { h:'A ideia de contrato social e o estado de natureza', p:[
  'O **contratualismo** é um conjunto de teorias políticas, desenvolvidas nos séculos XVII e XVIII, que explicam a origem e a legitimidade do **Estado** e da sociedade política por meio de um **contrato** (ou pacto) entre os indivíduos. Em contraste com as teorias medievais, que viam o poder como vindo de Deus (o direito divino dos reis), os contratualistas afirmam que o poder político resulta de um **acordo racional** entre pessoas livres e iguais, que decidem sair de uma situação anterior e criar um governo. Essa ideia inspirou as revoluções liberais e democráticas, e é a base das constituições modernas.',
  'Para entender o contrato, os autores partem de uma situação hipotética, anterior à sociedade, o **estado de natureza**: como seriam os seres humanos sem governo, sem leis e sem Estado? Não se trata de uma descrição histórica, mas de um **experimento mental**, que permite identificar a natureza humana e justificar a necessidade do poder. Cada autor descreve o estado de natureza de forma diferente, e, por isso, chega a conclusões distintas sobre a natureza do contrato, os direitos dos indivíduos e a forma de governo. A passagem do estado de natureza ao **estado civil** (ou sociedade política) é o ponto central.',
  'Os três principais contratualistas são **Thomas Hobbes** (1588-1679), **John Locke** (1632-1704) e **Jean-Jacques Rousseau** (1712-1778). Hobbes defendeu um Estado forte, e é associado ao **absolutismo**; Locke, o Estado limitado, os direitos naturais e a tolerância, e é o pai do **liberalismo**; Rousseau, a soberania popular e a vontade geral, e inspirou a **democracia** e os movimentos radicais da Revolução Francesa. A comparação entre eles é um clássico das provas, e exige atenção a cada elemento: o estado de natureza, os motivos do contrato, o que se cede, quem é o soberano e quando se pode resistir.'] },
 { h:'Hobbes: o Leviatã e o medo da guerra de todos contra todos', p:[
  'Hobbes escreveu **Leviatã** (1651), em meio à guerra civil inglesa. Para ele, no **estado de natureza**, os seres humanos são, por natureza, **iguais** (o mais fraco pode matar o mais forte) e movidos por desejo de poder, de segurança e de glória. Como os recursos são escassos e ninguém tem um poder superior para impor ordem, instala-se a **guerra de todos contra todos** (bellum omnium contra omnes), na famosa frase "o homem é o lobo do homem" (homo homini lupus), de Plauto. Não há propriedade, indústria, artes ou sociedade, e a vida é "solitária, pobre, sórdida, brutal e curta". O medo da morte violenta domina todos.',
  'Movidos pelo **medo** e pela **razão**, que apontam a paz como solução, os indivíduos decidem fazer um **contrato**, em que **renunciam a seus direitos naturais** (de se defender e de fazer justiça), e os transferem a um **soberano**, o Leviatã (um monstro bíblico, usado como símbolo do Estado), que pode ser um rei ou uma assembleia. O contrato é feito **entre os indivíduos**, que se comprometem a obedecer ao soberano, e não **com** o soberano, que, portanto, não está sujeito a obrigações perante os súditos. O poder do soberano é **absoluto** e indivisível: ele detém a espada (a força), faz as leis e julga, e garante a paz e a segurança.',
  'Para Hobbes, os súditos só podem resistir ao soberano se ele ameaçar sua **vida**, que foi o motivo do contrato. Fora disso, devem obedecer, pois, sem poder forte, o retorno à guerra é pior. Hobbes valoriza a **ordem** e a segurança acima da liberdade política, e reflete a experiência da guerra civil. Foi criticado por justificar o absolutismo, mas é considerado precursor do **Estado moderno**, laico e centralizado, que detém o monopólio da violência legítima, e do pensamento político realista. Sua visão negativa da natureza humana contrasta com as de Locke e de Rousseau.'] },
 { h:'Locke: direitos naturais, propriedade e governo limitado', p:[
  'John Locke, nos **Dois Tratados sobre o Governo** (1689), a obra que justificou a **Revolução Gloriosa** inglesa (1688), apresenta uma visão mais otimista. No **estado de natureza**, os seres humanos são livres, iguais e regidos pela **lei natural**, que a razão revela, e que determina que ninguém deve prejudicar outro em sua vida, liberdade ou propriedade. Esses são os **direitos naturais**: **vida, liberdade e propriedade**. A **propriedade** nasce do **trabalho**: quando alguém mistura seu trabalho a algo da natureza, torna-o seu. O estado de natureza não é de guerra, mas é **inconveniente**: falta um juiz imparcial, e cada um julga em causa própria.',
  'Para garantir esses direitos com segurança, os indivíduos celebram o **contrato social**, pelo qual criam um governo, por **consentimento**, com a função de proteger a vida, a liberdade e a propriedade. Diferentemente de Hobbes, o poder não é absoluto, e é **limitado** pelos direitos naturais e pela lei. Locke defende a **separação dos poderes** (principalmente o Legislativo, o mais importante, e o Executivo), o governo da **maioria** e o **Estado de direito**. Se o governante viola os direitos e age como tirano, rompe o contrato, e o povo tem o **direito de resistência** e de substituir o governo, inclusive pela força.',
  'Locke também defendeu a **tolerância religiosa** (Carta sobre a Tolerância), a separação entre Estado e Igreja e a liberdade de consciência, embora com restrições, como aos ateus e católicos. Suas ideias formam a base do **liberalismo político**, do constitucionalismo e do direito à propriedade privada, e inspiraram a Declaração de Independência dos Estados Unidos (1776) e a Revolução Francesa. Críticos apontam que seu liberalismo conviveu com a escravidão e com a colonização, pois Locke investiu na Companhia Real Africana e participou da redação da constituição da Carolina, o que mostra as contradições do liberalismo.'] },
 { h:'Rousseau: vontade geral, soberania popular e crítica da desigualdade', p:[
  'Jean-Jacques Rousseau, nascido em Genebra, escreveu o **Discurso sobre a Origem e os Fundamentos da Desigualdade entre os Homens** (1755) e **O Contrato Social** (1762). No **estado de natureza**, segundo ele, o ser humano é **bom por natureza** ("o bom selvagem"): livre, pacífico, movido por **amor de si** (instinto de conservação) e pela **piedade**, e vive em igualdade. A **sociedade**, ao criar a **propriedade privada**, as comparações e a vaidade (o amor-próprio), corrompe o ser humano e gera a **desigualdade**: "o primeiro que, tendo cercado um terreno, se lembrou de dizer "isto é meu" e encontrou pessoas bastante simples para acreditá-lo, foi o verdadeiro fundador da sociedade civil".',
  'No **Contrato Social**, Rousseau procura uma forma de associação que proteja a todos e na qual cada um, obedecendo a todos, obedeça somente a si mesmo e permaneça tão livre quanto antes. A solução é o contrato pelo qual cada indivíduo se entrega por inteiro à comunidade, e forma um **corpo político**, cujo poder é guiado pela **vontade geral**, que visa ao **bem comum**, distinta da **vontade de todos** (a soma dos interesses particulares). A **soberania** pertence ao **povo**, é **inalienável** e **indivisível**: não pode ser transferida a representantes. O governo é apenas um executor das leis, e pode ser substituído.',
  'Rousseau defende a **democracia direta**, ou ao menos uma ampla participação popular, e a ideia de que a **liberdade** é obedecer à lei que nós mesmos fizemos (autonomia). Para ele, a vontade geral é sempre reta, e seus críticos apontam o risco de que o conceito seja usado para suprimir as minorias, em nome de uma suposta vontade do povo. Sua obra inspirou a **Revolução Francesa**, em especial os jacobinos, e as teorias democráticas e socialistas. Também escreveu **Emílio**, sobre educação, em que defende uma educação natural e centrada na criança, o que o torna um dos grandes pensadores da pedagogia.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O contratualismo é um dos temas favoritos do ENEM. As questões trazem trechos do Leviatã, do Segundo Tratado ou do Contrato Social, e pedem a identificação do autor, do estado de natureza, do papel do soberano e da natureza do contrato. Também podem pedir a comparação entre os três autores, a relação com o Absolutismo, o Liberalismo e a Democracia, a ligação com a Revolução Francesa, a independência dos EUA e as constituições, ou a análise de situações atuais, como a legitimidade do poder e os limites da obediência.',
  'Para distinguir os autores: **Hobbes**, estado de natureza como guerra de todos contra todos, medo, soberano absoluto, paz e segurança; **Locke**, direitos naturais (vida, liberdade e propriedade), governo limitado, separação dos poderes, direito de resistência, liberalismo; **Rousseau**, o homem é bom, a sociedade corrompe, soberania popular, vontade geral, democracia. Atenção: em Hobbes, o contrato é entre os súditos, e o soberano não está limitado; em Locke, o governo é fiduciário e pode ser destituído; em Rousseau, o poder pertence ao povo e não se delega. Associe cada um a uma frase.',
  'Para revisar, monte uma tabela com os três autores (estado de natureza, motivo do contrato, o que se cede, forma de governo, direito de resistência e relação com a propriedade). Pense em situações atuais: manifestações contra governos, constituições, direitos individuais versus segurança. Esse tema se liga ao Iluminismo e a Montesquieu, que veremos a seguir, e à Revolução Francesa, estudada em História, pois as ideias contratualistas forneceram a base teórica para a crítica ao absolutismo e a defesa da liberdade e da soberania popular.'] }
]}
];

/* quinto bloco do tema Kant e a ética do dever */
{
  const kt = module.exports[1];
  const ult = kt.txt.pop();
  kt.txt.push({ h:'Kant, a política e a atualidade de seu pensamento', p:[
    'Na filosofia política e do direito, Kant defendeu que o **Estado** deve garantir a **liberdade externa** de cada pessoa, compatível com a liberdade de todos. Distinguiu o **direito**, que regula as ações externas e pode ser imposto pela coerção, da **moral**, que diz respeito às intenções e depende da autonomia interior. O melhor regime, para ele, é o **republicano**, com separação dos poderes e representação, e não necessariamente a democracia direta, que considerava propensa ao despotismo da maioria. Defendeu a **liberdade de pensamento** e de imprensa, e o "uso público da razão": cada pessoa deve poder criticar publicamente as leis e as instituições, embora deva obedecê-las no exercício de sua função.',
    'Em **A Paz Perpétua** (1795), Kant propôs condições para a paz entre os Estados: a abolição dos exércitos permanentes, a proibição de dívidas para a guerra, a não interferência na constituição de outros Estados, uma **federação de Estados livres** e um **direito cosmopolita**, de hospitalidade universal, que garanta ao estrangeiro o direito de não ser tratado com hostilidade. Essas ideias anteciparam a Liga das Nações e a ONU, e inspiram até hoje o debate sobre a paz mundial, os direitos humanos e o direito internacional. A paz, para Kant, não é um estado natural, mas uma tarefa política e moral.',
    'A **atualidade** de Kant é grande. A ideia de que toda pessoa tem **dignidade** e não pode ser usada como instrumento sustenta os direitos humanos, a bioética (por exemplo, no uso de seres humanos em pesquisas) e o combate ao trabalho análogo à escravidão e ao tráfico de pessoas. A exigência de **autonomia** e de pensamento crítico é um antídoto contra a manipulação por propaganda e por desinformação. O teste da universalização ("e se todos fizessem o mesmo?") é útil para avaliar atitudes como furar fila, jogar lixo na rua ou sonegar impostos. Mas também há críticas: seu rigor com os deveres absolutos, e a dificuldade de lidar com conflitos entre deveres, motivaram éticas que valorizam o cuidado, a virtude e as consequências.'
  ]});
  kt.txt.push(ult);
}
