/* Filosofia: textos corridos, temas 16 a 19 */
module.exports = [
{ t:'Existencialismo', txt:[
 { h:'O que é o existencialismo e seu contexto', p:[
  'O **existencialismo** é uma corrente filosófica e literária que se desenvolveu principalmente no século XX, em especial na França, após a Segunda Guerra Mundial. Seu tema central é a **existência concreta** do indivíduo: o ser humano real, que vive, escolhe, sofre, é livre e vai morrer, em oposição às grandes sistematizações abstratas, como a de Hegel, que dissolviam o indivíduo em categorias universais. Os existencialistas perguntam: o que significa existir? Qual o sentido da vida? Como assumir a liberdade e a responsabilidade em um mundo sem garantias? Essas questões ganharam força em um contexto de guerras, de genocídio e de crise de valores.',
  'O existencialismo teve precursores no século XIX. O dinamarquês **Søren Kierkegaard** (1813-1855), considerado o pai do pensamento existencial, destacou a **angústia**, a escolha individual e o "salto da fé", em oposição ao sistema hegeliano. **Friedrich Nietzsche** criticou os valores tradicionais e chamou a criar novos valores, e **Dostoiévski** explorou, em seus romances, os dilemas morais e a liberdade. No século XX, a **fenomenologia** de Husserl, que estuda as vivências da consciência, e a obra de **Martin Heidegger**, **Ser e Tempo** (1927), sobre o "ser-no-mundo", forneceram o método e os conceitos.',
  'Os principais representantes são **Jean-Paul Sartre** (1905-1980), **Simone de Beauvoir** (1908-1986), **Albert Camus** (1913-1960), **Maurice Merleau-Ponty** e **Gabriel Marcel**, entre outros. Embora diferentes entre si, e alguns (como Camus) rejeitassem o rótulo, todos compartilham o foco no indivíduo, na liberdade, na responsabilidade, na angústia e na finitude. Há um existencialismo **ateu** (Sartre, Beauvoir, Camus) e um **cristão** (Kierkegaard, Marcel). O movimento teve grande influência na literatura, no teatro, no cinema e na cultura, e marcou os debates políticos da época, como a descolonização e o engajamento dos intelectuais.'] },
 { h:'Sartre: a existência precede a essência', p:[
  'A frase mais célebre do existencialismo é a de **Sartre**: "a **existência precede a essência**". Em objetos fabricados, como uma faca, a essência (a ideia e a função) vem antes da existência: o artesão sabe o que vai produzir, e depois a produz. Para o ser humano, afirma Sartre, ocorre o contrário: não há uma natureza humana definida previamente, nem um plano divino. Primeiro, **existimos**, "lançados" no mundo, e só depois nos definimos por nossas escolhas e ações. O ser humano é "o que ele faz de si", e nada mais. Essa tese se baseia no ateísmo: se Deus não existe, não há um projeto prévio.',
  'Daí decorre a **liberdade radical**: o ser humano está "**condenado a ser livre**". Condenado porque não escolheu existir, e livre porque, a partir do momento em que existe, é responsável por tudo o que faz, sem poder se refugiar em desculpas, como a natureza, o destino, a sociedade ou Deus. Mesmo não escolher é uma escolha. Cada escolha envolve não só o indivíduo, mas toda a humanidade, pois, ao escolher, afirmamos o que consideramos valioso para todos, o que gera enorme **responsabilidade**. Essa liberdade causa **angústia**, a consciência de que somos totalmente responsáveis por nossas escolhas, sem garantias.',
  'Sartre denuncia a **má-fé** (mauvaise foi), a atitude de fugir da liberdade e da responsabilidade, ao negar a própria liberdade e se iludir. Quem diz "sou assim mesmo", "não tenho escolha" ou "faço o que mandam" age de má-fé, pois se trata como uma coisa, e não como uma consciência livre. O exemplo clássico é o do garçom que representa exageradamente seu papel, como se fosse apenas um garçom. Em **O Ser e o Nada** (1943), Sartre distingue o **ser-em-si** (as coisas, que são o que são) e o **ser-para-si** (a consciência humana, que é abertura e negação, sempre projeto, e que "não é o que é, e é o que não é").'] },
 { h:'Beauvoir, Camus e outras vozes existencialistas', p:[
  '**Simone de Beauvoir**, filósofa e escritora, aplicou o existencialismo à condição da mulher, em **O Segundo Sexo** (1949), obra fundadora do feminismo contemporâneo. Sua célebre frase é: "**não se nasce mulher, torna-se mulher**". Para ela, a feminilidade não é um destino biológico, mas uma construção social e histórica, que coloca a mulher na posição de **Outro**, de objeto, em relação ao homem, que se coloca como sujeito universal. Para se libertar, a mulher deve assumir sua **liberdade**, recusar essa posição e construir seu projeto, com a transformação das condições sociais. Beauvoir também escreveu sobre a ética da ambiguidade, a velhice e a morte.',
  '**Albert Camus** (1913-1960), escritor argelino-francês, desenvolveu a filosofia do **absurdo**. Em **O Mito de Sísifo** (1942), afirma que o absurdo nasce do **confronto** entre o desejo humano de sentido, de clareza e de unidade, e o **silêncio irracional do mundo**. Diante do absurdo, há três respostas: o **suicídio**, que Camus rejeita, o **salto** em direção a uma esperança metafísica ou religiosa (o "suicídio filosófico"), que ele também rejeita, e a **revolta**, que consiste em viver plenamente, mantendo a consciência do absurdo, sem ilusões. Sísifo, condenado a empurrar eternamente uma pedra montanha acima, é o herói absurdo: "é preciso imaginar Sísifo feliz".',
  'Os romances de Camus, como **O Estrangeiro** e **A Peste**, ilustram esses temas: o primeiro mostra um personagem indiferente às convenções, condenado pela sociedade, e o segundo, a solidariedade humana diante do mal e da morte. Já **Heidegger** descreve o ser humano como **Dasein** ("ser-aí"), lançado no mundo, que vive entre o cotidiano impessoal (o "a gente") e a possibilidade autêntica, ligada à consciência da **morte** ("ser-para-a-morte"). **Merleau-Ponty** destaca o papel do **corpo** na experiência. Esses autores mostram diferentes caminhos dentro do pensamento existencial, e enriquecem a discussão sobre o sentido e a liberdade.'] },
 { h:'Engajamento, crítica e atualidade do existencialismo', p:[
  'O existencialismo de Sartre e Beauvoir defendeu o **engajamento** (engagement): como a liberdade envolve responsabilidade, o intelectual não pode ficar neutro diante das injustiças. Sartre e Beauvoir participaram de lutas políticas: contra o colonialismo francês na Argélia, a guerra do Vietnã e o racismo, e se aproximaram do marxismo. Na **Crítica da Razão Dialética**, Sartre buscou conciliar existencialismo e marxismo. A literatura engajada, o teatro e o cinema foram instrumentos dessa intervenção. A frase de Sartre, "o existencialismo é um humanismo" (1946), defende que o ser humano é o criador de valores e o responsável por eles.',
  'As **críticas** ao existencialismo vêm de várias direções. Os marxistas o acusaram de individualismo e de ignorar as estruturas sociais que limitam a liberdade. Os estruturalistas, como Lévi-Strauss, e depois Foucault, argumentaram que os indivíduos são condicionados por estruturas (linguagem, poder e inconsciente), e que a ideia de um sujeito totalmente livre é ilusória. Outros veem na ênfase na angústia e no absurdo uma visão pessimista. Os defensores respondem que o existencialismo reconhece as condições (a **facticidade**), mas afirma que sempre há uma margem de escolha, e que o que fazemos com o que fizeram de nós é nossa responsabilidade.',
  'A atualidade do existencialismo é grande. Em um mundo de incertezas, de pressão por desempenho, de redes sociais e de crises de sentido, a reflexão sobre a **autenticidade**, a responsabilidade pelas escolhas e a criação de sentido continua relevante. A psicologia existencial e a logoterapia, de Viktor Frankl, que sobreviveu ao Holocausto e defendeu que a busca de sentido é a principal força humana, relacionam-se com o tema. Ao mesmo tempo, o existencialismo convida a refletir sobre a liberdade em contextos de desigualdade: ser livre para escolher exige condições materiais e sociais, tema que o pensamento de Beauvoir e outros ressaltaram, e que o ENEM costuma trazer em questões de ética e de cidadania.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O existencialismo aparece no ENEM em questões com trechos de Sartre ("a existência precede a essência", "o homem está condenado a ser livre") ou de Beauvoir ("não se nasce mulher, torna-se mulher"), em que se pede a identificação das ideias de liberdade, responsabilidade, angústia, má-fé e construção social da identidade. Também aparecem situações em que um personagem foge de uma escolha, ou culpa as circunstâncias, e a pergunta é qual conceito se aplica (má-fé), ou questões sobre o sentido da vida e o absurdo, de Camus.',
  'Pontos de atenção: para Sartre, a existência precede a essência, não há natureza humana prévia; o ser humano é condenado a ser livre e responsável por suas escolhas; a má-fé é a fuga da liberdade; Beauvoir aplica o existencialismo ao gênero e afirma que a mulher é construída socialmente; Camus fala do absurdo e da revolta; Kierkegaard destaca a angústia e a fé. Não confunda o existencialismo com niilismo ou com egoísmo: os existencialistas defendem a responsabilidade e, no caso de Sartre e Beauvoir, o engajamento social.',
  'Para revisar, escreva em suas palavras: existência e essência; liberdade e responsabilidade; angústia; má-fé; absurdo e revolta. Associe cada conceito a um autor e a uma frase. Pense em exemplos do cotidiano: alguém que culpa o contexto por não tentar algo (má-fé) ou que assume uma escolha difícil (autenticidade). Esse tema se conecta a Nietzsche (que vimos antes) e à Escola de Frankfurt, o próximo, que analisa a sociedade de massas, a indústria cultural e a razão instrumental, outra face da crise da modernidade.'] }
]},
{ t:'Escola de Frankfurt', txt:[
 { h:'A Escola de Frankfurt e a Teoria Crítica', p:[
  'A **Escola de Frankfurt** é o nome dado a um grupo de pensadores alemães, em geral de origem judaica e de esquerda, ligados ao **Instituto de Pesquisa Social**, fundado em Frankfurt, em 1923. Entre os principais nomes estão **Max Horkheimer**, **Theodor Adorno**, **Herbert Marcuse**, **Walter Benjamin**, **Erich Fromm** e, na segunda geração, **Jürgen Habermas**. Com a ascensão do nazismo, em 1933, o Instituto foi fechado e seus membros se exilaram, principalmente nos Estados Unidos, onde observaram de perto a sociedade de massas e a cultura industrial. Alguns voltaram à Alemanha após a guerra.',
  'O grupo desenvolveu a chamada **Teoria Crítica**, termo apresentado por Horkheimer em 1937, em oposição à **teoria tradicional**. A teoria tradicional, inspirada nas ciências naturais, descreve a realidade como ela é, de forma neutra, e acaba por **legitimar** a ordem existente. A teoria crítica, por sua vez, parte de Marx, de Hegel e de Freud e busca **compreender e criticar** a sociedade, revelando as contradições, as formas de dominação e as possibilidades de **emancipação**, com o objetivo de transformar a realidade. É, portanto, uma teoria comprometida com a liberdade e com a justiça, e que desconfia da aparente neutralidade da ciência.',
  'O ponto de partida é uma pergunta inquietante: por que a humanidade, que se tornou capaz de dominar a natureza com a ciência e a técnica, não chegou a um estado verdadeiramente humano, mas mergulhou em novas formas de barbárie, como o nazismo, o stalinismo e a guerra? E por que o proletariado, que Marx imaginava revolucionário, não se rebelou contra o capitalismo e, muitas vezes, aderiu ao fascismo ou ao consumismo? Para responder, os frankfurtianos combinaram a análise marxista da economia e da sociedade com a psicanálise, para entender a dimensão psíquica da dominação, e com a crítica da cultura.'] },
 { h:'A Dialética do Esclarecimento e a razão instrumental', p:[
  'Na **Dialética do Esclarecimento** (1947), **Adorno** e **Horkheimer** analisam a trajetória da razão ocidental. O **Esclarecimento** (o Iluminismo) pretendia libertar os seres humanos do medo e da superstição pelo conhecimento, e dominar a natureza. Mas, argumentam os autores, essa razão se transformou em **razão instrumental**: uma racionalidade voltada apenas para a eficácia, o cálculo e o controle, que se preocupa com os **meios**, e não com os **fins**, com a pergunta "como?", e não "para quê?". Ela trata a natureza, e também os seres humanos, como objetos a serem manipulados e dominados.',
  'Essa razão instrumental, ao se tornar absoluta, produz uma nova forma de **mito**: o domínio da natureza leva ao domínio dos seres humanos, e o esclarecimento "recai na mitologia". O resultado são as formas modernas de barbárie, como o fascismo, a burocracia, os campos de concentração, em que a racionalidade técnica e administrativa foi empregada para fins desumanos. O Holocausto, para Adorno, não é uma regressão ao irracional, mas um produto extremo da racionalidade instrumental. A célebre frase de Adorno, "escrever poesia depois de Auschwitz é um ato bárbaro", expressa a crise da cultura diante desse acontecimento.',
  'Os autores não renunciam à razão: pretendem uma **razão crítica**, que reflita sobre seus próprios limites e que seja capaz de criticar a dominação e de pensar fins humanos, como a liberdade e a reconciliação com a natureza. A crítica à razão instrumental atinge também a ciência e a técnica, quando se desligam de questões éticas e sociais, o que se reflete em debates atuais sobre tecnologia, meio ambiente, inteligência artificial e bioética. Para os frankfurtianos, o progresso científico e técnico não é, por si só, progresso humano, e é preciso questionar a quem ele serve e a que preço.'] },
 { h:'A indústria cultural', p:[
  'Um dos conceitos mais conhecidos da Escola é o de **indústria cultural**, desenvolvido por Adorno e Horkheimer. Designa a produção de bens culturais (cinema, rádio, televisão, música popular, revistas) em **escala industrial**, padronizados, voltados ao consumo de massa e ao lucro, segundo a lógica da mercadoria. Os autores observaram, nos Estados Unidos, que a cultura passou a ser organizada como uma indústria, com fórmulas repetidas, estereótipos e produtos feitos em série. A arte perde seu caráter crítico e se transforma em **entretenimento**, que oferece prazer fácil e imediato, e distrai, em vez de provocar reflexão.',
  'A indústria cultural cumpre uma função **ideológica**: ela **integra** os indivíduos ao sistema, ao oferecer diversão, que relaxa e disciplina a força de trabalho para o dia seguinte, e ao produzir **consumidores** conformados, que desejam o que lhes é oferecido. Cria **necessidades artificiais**, e reforça o conformismo, apresentando a ordem social como natural. A **padronização** e a **pseudoindividualização** (pequenas variações que dão a ilusão de originalidade) tornam as produções semelhantes. O resultado é a **massificação** e a perda da capacidade de crítica e de autonomia, o que dificulta o pensamento independente e a resistência.',
  'O conceito é muito discutido. Os críticos apontam que Adorno e Horkheimer teriam uma visão elitista, que desvaloriza a cultura popular e subestima a capacidade do público de interpretar e resistir. **Walter Benjamin**, em **A Obra de Arte na Era de sua Reprodutibilidade Técnica** (1936), tinha uma visão mais ambígua: a reprodução técnica faz perder a "aura" (a singularidade da obra), mas também democratiza a arte e abre possibilidades emancipatórias. Na atualidade, o conceito é usado para analisar as redes sociais, os algoritmos, as plataformas de streaming e a publicidade, que moldam gostos e comportamentos, e transformam a atenção em mercadoria.'] },
 { h:'Marcuse, Habermas e o legado da Teoria Crítica', p:[
  '**Herbert Marcuse**, em **O Homem Unidimensional** (1964), analisa a sociedade industrial avançada, em que o consumo, a tecnologia e a propaganda criam uma **falsa consciência** e **integram** os indivíduos ao sistema, eliminando a oposição. O homem se torna "unidimensional": perde a capacidade de pensar criticamente e de imaginar uma alternativa. Para ele, as necessidades são manipuladas, e a liberdade aparente esconde uma dominação. Sua obra inspirou os movimentos estudantis e de contracultura dos anos 1960, e a ideia da "**grande recusa**", a negação da ordem estabelecida por grupos marginais e pela juventude.',
  '**Jürgen Habermas** (nascido em 1929), da segunda geração, propõe uma renovação da teoria crítica. Em vez de uma razão instrumental, defende uma **razão comunicativa**, baseada no **diálogo** e no **entendimento** entre as pessoas, em condições de igualdade, em que valem apenas os argumentos. Desenvolve a ideia de **esfera pública**, o espaço em que cidadãos debatem questões de interesse comum, e a de **democracia deliberativa**, em que as decisões políticas devem resultar da discussão pública racional. Também criticou a "colonização do mundo da vida" pelo sistema econômico e administrativo. Suas ideias são centrais no debate sobre democracia, direito e ética.',
  'O legado da Escola de Frankfurt é amplo. A Teoria Crítica influenciou a Sociologia, a Comunicação, a Filosofia, os estudos culturais, a Psicologia e a Pedagogia (educação crítica). Conceitos como indústria cultural, razão instrumental, ideologia e esfera pública são usados para analisar a mídia, a publicidade, o consumo, as redes sociais e a política. Para o estudante, esses autores oferecem ferramentas para **desconfiar das aparências**, perceber os interesses por trás da cultura de massa e pensar em alternativas, o que se relaciona à cidadania e à competência de leitura crítica que o ENEM valoriza, tanto em questões de Filosofia e Sociologia quanto na redação.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Escola de Frankfurt é muito cobrada no ENEM, principalmente pelo conceito de **indústria cultural**. As questões trazem trechos de Adorno e Horkheimer, e pedem para identificar a padronização, a transformação da cultura em mercadoria, o consumo de massa e o papel ideológico da mídia. Também aparecem situações atuais (programas de TV, músicas, redes sociais, influenciadores e propaganda), e a pergunta é como o conceito explica o fenômeno. A razão instrumental e a crítica ao Iluminismo também podem aparecer, relacionadas à tecnologia e aos riscos da racionalidade técnica.',
  'Pontos de atenção: a indústria cultural transforma a cultura em mercadoria padronizada, para o consumo de massa, com função ideológica de integração e de conformismo; a razão instrumental se volta para os meios, e não para os fins; a Teoria Crítica visa à emancipação, em oposição à teoria tradicional; Marcuse fala do homem unidimensional; Benjamin trata da perda da aura da obra de arte; Habermas propõe a razão comunicativa e a esfera pública. Ao aplicar o conceito, procure sinais de repetição de fórmulas, de lucro, de passividade do público e de estímulo ao consumo.',
  'Para revisar, escreva os conceitos principais (Teoria Crítica, razão instrumental, indústria cultural, unidimensionalidade, razão comunicativa) e um exemplo atual de cada um. Compare a visão dos frankfurtianos (críticos) com uma visão mais otimista dos meios de comunicação, para treinar o equilíbrio na análise. Esse tema se liga a Marx (ideologia e alienação) e prepara o seguinte, Hannah Arendt, que analisa o totalitarismo, a banalidade do mal e a vida política, também a partir da experiência do século XX.'] }
]},
{ t:'Hannah Arendt', txt:[
 { h:'Vida e obra de Hannah Arendt', p:[
  '**Hannah Arendt** (1906-1975) foi uma filósofa e teórica política alemã, de origem judaica. Estudou Filosofia com Heidegger, Husserl e Karl Jaspers, e começou a carreira acadêmica na Alemanha. Com a ascensão do nazismo, foi presa por pouco tempo, fugiu para a França e, em 1941, para os Estados Unidos, onde viveu e lecionou. Viveu em primeira mão a perseguição e o exílio, o que marcou profundamente seu pensamento. Era **apátrida** por muitos anos, o que a fez refletir sobre o "direito a ter direitos". Suas principais obras são **As Origens do Totalitarismo** (1951), **A Condição Humana** (1958) e **Eichmann em Jerusalém** (1963).',
  'Arendt recusava o rótulo de "filósofa", preferindo ser chamada de **teórica política**, e desconfiava dos sistemas filosóficos. Seu pensamento se concentra em compreender os acontecimentos políticos do século XX (totalitarismo, antissemitismo, imperialismo, revoluções) e em pensar as condições da **liberdade**, da **ação** e da vida em comum. Seu método é a "**compreensão**", um esforço de pensar o que aconteceu, sem reduzi-lo a causas e a explicações que o tornem "normal", e sem aceitar a ideia de que o horror seja incompreensível. Para ela, "pensar" é uma atividade que protege contra a irreflexão e a conivência com o mal.',
  'Um traço marcante de sua obra é o **valor da política** e da **pluralidade**. Para Arendt, o ser humano é um ser que vive entre outros, em um mundo comum, e a política é o espaço onde os cidadãos, diferentes e iguais, agem e falam juntos, em liberdade. O fim da política, ou sua destruição, leva à violência e à dominação. Esse ponto de vista, que valoriza a **participação** e o **espaço público**, a coloca como uma das principais pensadoras da democracia no século XX, e sua influência se estende à ciência política, à Sociologia, ao Direito e à Filosofia.'] },
 { h:'O totalitarismo: origens e características', p:[
  'Em **As Origens do Totalitarismo**, Arendt analisa o **nazismo** e o **stalinismo** como formas inéditas de dominação, distintas da tirania e das ditaduras tradicionais. O **totalitarismo** busca o controle total da sociedade e dos indivíduos, em seus atos, em suas ideias e até em seus pensamentos, por meio da **ideologia**, do **terror** e da **propaganda**. Não se contenta com a obediência exterior: pretende transformar a natureza humana e produzir um "homem novo". Seu instrumento extremo são os **campos de concentração**, em que se realiza a ideia de que tudo é possível, e os seres humanos podem ser tornados "supérfluos".',
  'Para Arendt, o totalitarismo surgiu de condições históricas: o **antissemitismo**, o **imperialismo** e o racismo, a crise do Estado-nação, o desenraizamento e a solidão das massas na sociedade moderna, a perda de vínculos sociais e políticos. As **massas**, atomizadas, isoladas e sem representação política, aderem aos movimentos totalitários em busca de pertencimento e de sentido. O líder, a ideologia e a propaganda oferecem uma explicação total do mundo, e uma "lógica" que dispensa a experiência e a realidade. A **solidão** (loneliness), a sensação de ser descartável e abandonado, é o terreno fértil do totalitarismo.',
  'Os regimes totalitários destroem o **espaço público** e a **pluralidade**, e eliminam a capacidade de ação e de pensamento independentes. Usam a **mentira organizada**, que, em vez de convencer, desorienta e destrói a distinção entre fato e ficção, de modo que as pessoas não conseguem mais distinguir o verdadeiro do falso. Arendt advertia que "o súdito ideal do governo totalitário não é o nazista convicto nem o comunista convicto, mas as pessoas para quem a distinção entre fato e ficção e a distinção entre verdadeiro e falso já não existem". Essa observação é frequentemente retomada hoje, em discussões sobre desinformação, "pós-verdade" e populismo.'] },
 { h:'A banalidade do mal e o caso Eichmann', p:[
  'Em 1961, Arendt foi a Jerusalém, como repórter da revista The New Yorker, para acompanhar o julgamento de **Adolf Eichmann**, oficial nazista responsável pela logística da deportação de milhões de judeus para os campos de extermínio. Dessa experiência surgiu **Eichmann em Jerusalém: um relato sobre a banalidade do mal** (1963). Arendt esperava ver um monstro, um sádico, mas encontrou um **burocrata** comum, aparentemente normal, que falava por clichês, e dizia ter apenas cumprido ordens e feito seu trabalho. A "banalidade do mal" é a ideia de que o mal pode ser praticado por pessoas **comuns**, sem ódio nem maldade excepcionais, por **irreflexão**.',
  'O que caracterizava Eichmann, segundo ela, era a **ausência de pensamento**: a incapacidade de se colocar no lugar do outro, de refletir sobre o significado de seus atos, de questionar as ordens. Ele não era estúpido, mas **irrefletido**, e se refugiava na linguagem burocrática e nos lugares-comuns. Por isso, o mal não precisa de grandes vilões, e pode ser operado por funcionários que obedecem e que se recusam a pensar. A conclusão é que **pensar** é um ato ético e político: é a capacidade de dialogar consigo mesmo, de julgar e de recusar-se a participar do mal. "Banal" não significa que o mal seja pequeno, mas que sua origem pode ser cotidiana.',
  'A tese gerou **polêmica**. Críticos disseram que Arendt minimizava a responsabilidade de Eichmann, ou que ele, na verdade, era um antissemita convicto. Ela respondeu que não negava a responsabilidade, mas queria compreender como atos monstruosos podem ser cometidos por pessoas comuns. A ideia de "banalidade do mal" é frequente em debates sobre obediência, burocracia, violência de Estado e responsabilidade individual. Relaciona-se com experimentos da psicologia social, como o de Milgram, sobre a obediência à autoridade. Arendt lembra que, mesmo em regimes de terror, é possível recusar-se a colaborar, e que cada pessoa é responsável por seus atos.'] },
 { h:'A condição humana: trabalho, obra e ação', p:[
  'Em **A Condição Humana**, Arendt distingue três atividades fundamentais da vida ativa. O **trabalho** (labor) é a atividade ligada ao ciclo biológico, à manutenção da vida e à satisfação das necessidades (comer, vestir-se), repetitiva e perecível, em que o ser humano age como "animal laborans". A **obra** (work) é a atividade de fabricar objetos duráveis, que constituem um mundo artificial e estável, o "mundo comum", em que o ser humano age como "homo faber". A **ação** (action) é a atividade que se dá entre os seres humanos, sem mediação de coisas, pela palavra e pelo ato: é a **política**, e é a atividade em que se manifesta a liberdade e a singularidade.',
  'A **ação** está ligada à **natalidade**, à capacidade de começar algo novo: cada ser humano que nasce é um novo começo, e é capaz de iniciar o imprevisível. Ela depende da **pluralidade**, a condição de que vivemos entre outros, diferentes e iguais, e do **espaço público**, onde nos revelamos pelo discurso e pela ação. A política, para Arendt, não é a administração de necessidades ou o domínio, mas o espaço da **liberdade**, onde os cidadãos deliberam e agem juntos. O **poder**, para ela, nasce do agir em conjunto, e se distingue da **violência**, que é instrumental e destrói o poder.',
  'Arendt critica a tendência da sociedade moderna a valorizar o **trabalho** e o consumo acima da ação política, o que resulta em uma "sociedade de trabalhadores" que se preocupa com a necessidade, e que abandona o espaço público. A **política**, nesse caso, é reduzida a gestão e a economia, e as pessoas se isolam. Também defendeu o **perdão** e a **promessa** como capacidades da ação, que permitem lidar com a irreversibilidade e a imprevisibilidade. A expressão "direito a ter direitos" resume sua visão de que os direitos humanos só se efetivam se as pessoas pertencem a uma comunidade política que os garanta, o que tem relevância para refugiados e apátridas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Arendt aparece no ENEM em questões sobre totalitarismo, banalidade do mal, obediência e responsabilidade, política e liberdade. As questões podem trazer um trecho de Eichmann em Jerusalém e pedir o conceito, ou uma situação atual, como a participação de funcionários em atos de violência, a corrupção ordinária, a desinformação e a manipulação, para que se identifique a "banalidade do mal" ou os elementos do totalitarismo (propaganda, terror, controle). Também podem aparecer a distinção entre poder e violência e o valor do espaço público.',
  'Pontos de atenção: a banalidade do mal significa que atos terríveis podem ser cometidos por pessoas comuns, que deixam de pensar e se limitam a cumprir ordens; o totalitarismo busca o controle total, com terror e ideologia, e destrói o espaço público; o isolamento e a solidão favorecem os movimentos de massas; a ação política é a atividade da liberdade, e depende da pluralidade; poder e violência se distinguem. Evite interpretar "banal" como "pequeno" ou como justificativa: Arendt não desculpa quem obedece, mas enfatiza a responsabilidade pessoal de pensar e de julgar.',
  'Para revisar, escreva com suas palavras as ideias de totalitarismo, banalidade do mal, trabalho/obra/ação, pluralidade e esfera pública, com um exemplo atual para cada uma. Relacione-a a Marx e à Escola de Frankfurt (crítica da sociedade moderna) e a Foucault, o próximo tema, que analisa o poder, as instituições disciplinares e a vigilância. Esse conjunto de autores do século XX fornece repertório valioso para a redação, em temas como democracia, direitos humanos, tecnologia e responsabilidade individual.'] }
]},
{ t:'Foucault: poder e disciplina', txt:[
 { h:'Foucault e a análise do poder', p:[
  '**Michel Foucault** (1926-1984) foi um filósofo francês, professor do Collège de France, cuja obra transformou as ciências humanas. Estudou a história de instituições e de saberes, como a loucura, a medicina, as prisões e a sexualidade, e sempre se perguntou como os **discursos** e as **práticas** produzem **verdades**, **sujeitos** e **relações de poder**. Entre suas principais obras estão a **História da Loucura** (1961), **O Nascimento da Clínica** (1963), **As Palavras e as Coisas** (1966), **Vigiar e Punir** (1975) e **História da Sexualidade** (1976 a 1984). Seu método combina a **arqueologia** (análise dos discursos de uma época) e a **genealogia** (inspirada em Nietzsche: a história das origens e dos interesses por trás dos valores e das práticas).',
  'Para Foucault, o **poder** não é apenas algo que uma pessoa ou um Estado **possui** e exerce de cima para baixo, de forma repressiva (dizendo "não"). Ele é uma **relação**, que **circula** por toda a sociedade, em redes, nas instituições e nas práticas cotidianas, e é **produtivo**: o poder produz saberes, discursos, comportamentos, corpos e subjetividades. "Onde há poder, há resistência." Por isso, é preciso analisar os **micropoderes** (na escola, na família, na fábrica, no hospital, na prisão), e não apenas o poder do Estado. Poder e **saber** estão ligados: os saberes (medicina, psiquiatria, pedagogia, criminologia) produzem verdades que legitimam práticas de controle, e o poder utiliza esses saberes.',
  'Essa visão tem consequências para a compreensão do sujeito. Para Foucault, o indivíduo não é uma entidade natural, mas é **constituído** historicamente por práticas e discursos: o "louco", o "criminoso", o "doente" e o "homossexual" são categorias criadas por saberes e instituições, que classificam, normalizam e controlam. Isso não significa que o sujeito não possa resistir: Foucault valoriza as práticas de **liberdade** e de **cuidado de si**, em que os indivíduos se constituem como sujeitos éticos. Sua obra, assim, desafia as visões tradicionais de poder e liberdade, e incentiva a pensar criticamente instituições que parecem naturais.'] },
 { h:'Vigiar e Punir: do suplício à prisão e à sociedade disciplinar', p:[
  'Em **Vigiar e Punir**, Foucault estuda a história das punições. Descreve, no início, o **suplício** de Damiens, em 1757, na França: um condenado é publicamente torturado e esquartejado, em um espetáculo de poder do soberano sobre o corpo do criminoso. A punição era **pública**, **violenta** e voltada ao corpo. Ao longo dos séculos XVIII e XIX, essa forma de punir foi substituída pela **prisão**, a detenção em instituições fechadas, com horários e regras rígidas. Para Foucault, isso não foi apenas "humanização": foi uma nova **tecnologia de poder**, mais eficiente e menos custosa, que busca **corrigir** e **disciplinar** o indivíduo, em vez de apenas castigá-lo.',
  'O poder **disciplinar** atua sobre os corpos para torná-los **úteis** e **dóceis**: "corpos dóceis". Seus instrumentos são a **vigilância hierárquica**, a **sanção normalizadora** (que pune desvios em relação à norma) e o **exame** (que combina vigilância e registro). A disciplina organiza o **espaço** (a distribuição dos indivíduos em celas, carteiras e postos), o **tempo** (horários, rotinas) e as **atividades** (exercícios, gestos). Essas técnicas surgem em conventos, quartéis, escolas, hospitais e fábricas, e se espalham por toda a sociedade, que passa a ser uma "**sociedade disciplinar**": as instituições se assemelham entre si (a escola se parece com a fábrica, que se parece com a prisão).',
  'O símbolo desse poder é o **Panóptico**, um projeto de prisão de Jeremy Bentham: uma torre central, de onde o vigia pode ver todas as celas, dispostas em círculo, sem que os presos saibam se estão sendo observados. A consequência é que os presos **interiorizam** a vigilância, e passam a se vigiar a si mesmos, e se comportam de modo obediente: o poder funciona de forma automática, sem necessidade de violência constante. Foucault generaliza: vivemos em uma sociedade de **vigilância**, em que as pessoas são observadas, registradas e avaliadas (câmeras, cadastros, notas, avaliações de desempenho), e adotam voluntariamente os comportamentos esperados.'] },
 { h:'Biopoder, normalização e sexualidade', p:[
  'Nos anos 1970, Foucault identificou outra forma de poder, o **biopoder**, que surge nos séculos XVIII e XIX, e tem como alvo a **vida** biológica das populações: natalidade, mortalidade, saúde, longevidade, higiene. Se o poder soberano antigo tinha o direito de "fazer morrer e deixar viver", o biopoder atua no sentido de "**fazer viver** e deixar morrer": gerencia a vida, por meio de políticas de saúde, de estatísticas, de planejamento familiar e de controle de epidemias. Tem duas faces: a **anatomopolítica** do corpo individual (a disciplina) e a **biopolítica** da população, por meio da medicina, da demografia e da higiene pública.',
  'Esse poder atua pela **normalização**: estabelece **normas** (o normal, o saudável, o produtivo, o desejável) e classifica, avalia e corrige quem se desvia delas. As ciências humanas e a medicina, ao definir o "normal" e o "patológico", exercem poder. Em **História da Sexualidade**, Foucault mostra que a sexualidade, longe de ter sido simplesmente reprimida na época vitoriana, tornou-se objeto de **discursos** e de saberes (a medicina, a psiquiatria, a confissão), que a classificam, regulam e produzem identidades (como a do "homossexual", categoria criada no século XIX). O poder não apenas proíbe, mas **incita** a falar de sexo e a se conhecer, para melhor controlar.',
  'Foucault também estudou a **loucura**: na Idade Clássica, os "loucos" passaram a ser internados em hospitais gerais, ao lado de pobres e desocupados, em um "grande internamento", e a psiquiatria moderna, ao se constituir como saber, os transformou em "doentes mentais", objeto de tratamento e de controle. Essas análises não pretendem negar a existência de sofrimento psíquico, mas mostrar como a **fronteira** entre o normal e o anormal é histórica e relaciona-se com interesses de poder. A obra de Foucault influenciou movimentos de luta antimanicomial, os estudos de gênero, a criminologia crítica, a sociologia das instituições e a pedagogia crítica.'] },
 { h:'Resistência, atualidade e críticas', p:[
  'Para Foucault, onde há poder, há **resistência**. Ela não é externa ao poder, mas surge dentro das próprias relações de poder, de modo múltiplo e disperso. Não depende de uma revolução, mas de práticas locais, como as lutas de presos, de pacientes, de mulheres, de minorias sexuais e de estudantes, que questionam as normas e os saberes. Os intelectuais devem apoiar essas lutas, e não falar em nome delas. Nos últimos trabalhos, Foucault valorizou o "**cuidado de si**" e a "**estética da existência**", a possibilidade de os indivíduos constituírem a si mesmos como sujeitos éticos, por meio de práticas de liberdade, inspiradas na Antiguidade.',
  'A atualidade de Foucault é grande. Em tempos de **vigilância digital**, com câmeras, reconhecimento facial, monitoramento de redes sociais e de dados pessoais, o Panóptico é uma imagem poderosa. As **avaliações** constantes (notas, metas, rankings e avaliações de desempenho), a **normalização** dos corpos (padrões de beleza e de saúde) e a gestão da saúde pública, como se viu na pandemia, mostram o funcionamento dos mecanismos disciplinares e biopolíticos. Seus conceitos são usados na análise da educação, da saúde, das prisões, do trabalho e da tecnologia, e ajudam a compreender como a liberdade e o controle se entrelaçam.',
  'As **críticas** a Foucault incluem a de que sua análise do poder é tão ampla que dificulta distinguir formas legítimas e ilegítimas, a de que enfraquece a ideia de emancipação, a de que seu método histórico é seletivo e a de que não oferece critérios normativos para a crítica. Habermas, por exemplo, questionou o fundamento de sua crítica. Os defensores replicam que Foucault não pretendia fornecer uma teoria geral, mas "caixas de ferramentas" para pensar e para lutar. Seja como for, a leitura de Foucault convida a **desnaturalizar** o que parece óbvio e a perguntar: quem define a norma? Quem se beneficia? Que formas de resistência são possíveis?'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Foucault aparece no ENEM em questões com trechos de Vigiar e Punir ou de textos que descrevem a vigilância e a disciplina, e pedem a identificação de conceitos como poder disciplinar, panóptico, biopoder, normalização e sociedade de vigilância. Também são comuns as situações atuais: câmeras de segurança, monitoramento de funcionários, controle de comportamento nas escolas, redes sociais e uso de dados, e a pergunta é como o pensamento de Foucault explica o fenômeno. A ideia de que o poder se exerce em toda a sociedade, e não só pelo Estado, é central.',
  'Pontos de atenção: o poder, para Foucault, é uma relação, está em toda parte e é produtivo, não só repressivo; o poder disciplinar produz corpos dóceis por meio da vigilância, da normalização e do exame; o panóptico simboliza a vigilância que se internaliza; o biopoder gerencia a vida das populações; saber e poder estão ligados; e onde há poder, há resistência. Evite reduzir Foucault à ideia de que "o Estado oprime": ele analisa os micropoderes e as instituições, como a escola, o hospital e a prisão. Associe: Foucault, poder e disciplina; Arendt, totalitarismo; Adorno, indústria cultural.',
  'Para revisar, escreva com suas palavras: poder disciplinar, panóptico, normalização, biopoder, saber-poder e resistência, com exemplos do cotidiano (escola, trabalho, redes sociais). Compare Foucault com Marx (poder ligado à economia e às classes) e com Maquiavel (poder como conquista e manutenção). Esse tema dá repertório para a redação, em temas ligados à tecnologia, à vigilância, aos direitos e à educação. Em seguida, entramos nos temas sistemáticos de Filosofia: ética e moral, política e democracia, conhecimento, estética, tecnologia e lógica.'] }
]}
];
