/* Filosofia: textos corridos, temas 20 a 22 */
module.exports = [
{ t:'Ética e moral', txt:[
 { h:'Ética e moral: conceitos e diferenças', p:[
  'Os termos **moral** e **ética** costumam ser usados como sinônimos no dia a dia, mas, em Filosofia, é útil distingui-los. A **moral** (do latim mores, "costumes") é o conjunto de normas, valores e regras de conduta de uma sociedade ou de um grupo, que orientam o que é considerado certo ou errado, bom ou mau, e que se transmitem pela educação, pela religião e pela tradição. A **ética** (do grego ethos, "modo de ser", "caráter") é a **reflexão filosófica** sobre a moral: examina seus fundamentos, justifica ou critica as normas, e pergunta por que devemos agir de certa maneira. A moral é a prática, e a ética é a teoria sobre essa prática.',
  'Uma situação ilustra a diferença. Dizer que "roubar é errado" é um **juízo moral**, uma norma aceita em uma comunidade. Perguntar "por que é errado roubar? Esse princípio vale sempre? Em que casos poderia haver exceções, como roubar para salvar uma vida?" é uma **reflexão ética**. A ética investiga a origem e o fundamento dos valores, a natureza da liberdade e da responsabilidade, a relação entre intenção e consequência e o sentido do bem e da felicidade. É, portanto, um campo que exige análise, argumentação e abertura ao debate.',
  'A vida moral pressupõe algumas condições. Primeiro, a **liberdade**: só podemos ser responsabilizados por atos que escolhemos. Segundo, a **consciência**: a capacidade de distinguir o certo e o errado e de refletir sobre os próprios atos. Terceiro, a **responsabilidade**: arcar com as consequências do que fazemos. Quarto, a existência de **valores** e **normas**, que orientam a ação. Por isso, a ética está ligada à **autonomia**, a capacidade de agir segundo princípios que reconhecemos como válidos, e não apenas por obediência, medo ou conveniência, o que é um tema central em Kant.'] },
 { h:'Principais teorias éticas', p:[
  'A história da Filosofia apresenta várias respostas à pergunta "como devemos agir?". A **ética das virtudes**, de **Aristóteles**, enfatiza o **caráter**: a vida boa consiste em desenvolver virtudes (coragem, justiça, temperança, prudência), por meio do hábito, buscando o meio-termo, em vista da **felicidade** (eudaimonia). A pergunta central não é "o que devo fazer?", mas "que tipo de pessoa devo ser?". A ética do **dever** (deontologia), de **Kant**, afirma que a ação moral é a que se faz por **dever**, segundo princípios universais, como o imperativo categórico, independentemente das consequências.',
  'O **utilitarismo**, de **Jeremy Bentham** (1748-1832) e **John Stuart Mill** (1806-1873), é uma ética **consequencialista**: uma ação é boa se produz a maior **felicidade** (prazer, bem-estar) para o **maior número** de pessoas. O critério é a utilidade: calcula-se o resultado total. Mill distingue prazeres superiores (intelectuais) e inferiores, e defende a liberdade individual. A crítica é que o utilitarismo pode justificar o sacrifício de minorias ou de inocentes, em nome do bem da maioria. Já a **ética do cuidado**, de **Carol Gilligan** e outras filósofas, destaca as relações, a empatia e a responsabilidade pelos outros, em contraste com os princípios abstratos.',
  'Há também o **contratualismo moral** (as normas éticas são as que seriam aceitas por pessoas racionais em um acordo, como em **John Rawls**), o **existencialismo** (a moral é criada pela liberdade, sem fundamento prévio), o **relativismo** (os valores dependem da cultura e do contexto) e a **ética do discurso**, de **Habermas** (normas são válidas se puderem ser aceitas por todos os afetados em um diálogo racional). Cada teoria destaca um aspecto: o caráter, o dever, as consequências, o cuidado, o acordo ou a liberdade. No ENEM, o importante é reconhecer as ideias centrais de cada uma e aplicá-las a situações concretas.'] },
 { h:'Relativismo, universalismo e os dilemas éticos', p:[
  'Uma discussão importante é a que opõe o **relativismo moral** ao **universalismo**. O relativismo afirma que os valores morais variam conforme a cultura, a época e o grupo, e que não há critério universal para julgar. Tem o mérito de promover o respeito à diversidade cultural e de evitar o **etnocentrismo**, a tendência a julgar outras culturas pelos padrões da própria. Mas tem um problema: se tudo é relativo, torna-se difícil criticar práticas como a escravidão, a tortura ou a discriminação, por serem aceitas em certas sociedades. O **universalismo** defende que existem princípios válidos para todos, como a **dignidade humana** e os direitos humanos.',
  'Muitos filósofos propõem uma posição intermediária: reconhecer a diversidade de costumes, sem abandonar a possibilidade de **critérios racionais** para criticar práticas que violam a dignidade e a liberdade das pessoas. A **Declaração Universal dos Direitos Humanos** (1948) é uma tentativa de formular princípios mínimos comuns, embora seja discutida quanto a seu caráter ocidental. A pergunta de fundo é como conciliar a **tolerância** com a **defesa de valores universais**. Em questões atuais, como os direitos das mulheres, a liberdade religiosa e a bioética, esse debate é permanente.',
  'Os **dilemas éticos** são situações em que há conflito entre valores ou deveres, e qualquer escolha tem custos. O clássico "dilema do bonde" pergunta se é aceitável desviar um bonde desgovernado para matar uma pessoa, em vez de cinco: o utilitarista tende a aceitar, pelo resultado, e o deontólogo tende a rejeitar, pela proibição de usar alguém como meio. Dilemas atuais envolvem a eutanásia, o aborto, a pesquisa com embriões, a clonagem, a inteligência artificial e o uso de dados. Analisá-los exige reconhecer os valores em jogo, os argumentos de cada lado e as consequências, evitando posições simplistas.'] },
 { h:'Ética, cidadania e vida em sociedade', p:[
  'A ética não se limita à vida privada, mas envolve a **vida pública**. A **ética na política** trata da honestidade, da transparência, da prestação de contas e do combate à corrupção. A **ética profissional** orienta a atuação de médicos, advogados, jornalistas, engenheiros e outros, por meio de códigos que protegem as pessoas atendidas. A **bioética** discute as questões éticas das ciências da vida (transplantes, reprodução assistida, pesquisa com seres humanos). A **ética ambiental** trata do dever de preservar a natureza e as futuras gerações. A **ética digital** discute privacidade, desinformação e uso de algoritmos.',
  'A **cidadania** exige o exercício dos direitos e deveres, o respeito às leis e à diversidade, a participação e a solidariedade. A moral coletiva é construída em instituições (família, escola, religião, Estado e mídia) e se transforma com as lutas sociais: práticas aceitas antigamente, como a escravidão, a exclusão das mulheres do voto e a discriminação, passaram a ser consideradas injustas. Isso mostra que a moral é **histórica**, mas também que há um movimento de ampliação do reconhecimento da dignidade. Pensar eticamente é participar desse movimento de forma crítica e responsável.',
  'No Brasil, o debate sobre ética é frequente: corrupção, desigualdade, violência, desinformação, direitos humanos, meio ambiente. Muitos problemas não decorrem da falta de leis, mas da distância entre as normas e as práticas, o que os filósofos chamam de a lacuna entre o **dever ser** e o **ser**. O ENEM valoriza a capacidade de analisar uma situação à luz de princípios éticos, de identificar valores em conflito e de argumentar a favor de soluções fundamentadas na dignidade humana, na justiça e na responsabilidade. Esse tipo de raciocínio é essencial também na redação, na proposta de intervenção.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Ética e moral aparecem no ENEM em questões que trazem trechos de Aristóteles, Kant ou Mill, ou situações do cotidiano e dilemas contemporâneos, e pedem a identificação da diferença entre ética e moral, do tipo de teoria (virtude, dever ou consequências) ou de valores em conflito. Também aparecem questões sobre relativismo cultural, tolerância, direitos humanos e responsabilidade, em contextos de política, de ciência, de tecnologia e de meio ambiente, que pedem a capacidade de argumentar e de avaliar.',
  'Pontos de atenção: a moral é o conjunto de normas de um grupo, e a ética é a reflexão sobre elas; a ética das virtudes (Aristóteles) valoriza o caráter e o hábito; a deontologia (Kant) valoriza o dever e a intenção; o utilitarismo (Bentham e Mill) valoriza as consequências e a felicidade do maior número; o relativismo afirma a variação dos valores, e o universalismo defende princípios universais, como a dignidade; o consenso social não garante, por si só, que algo seja ético. Evite confundir a ética com religião ou com a lei: são esferas relacionadas, mas distintas.',
  'Para revisar, monte um quadro comparando as teorias éticas (autor, critério de ação, exemplo e crítica) e um conjunto de perguntas para analisar um dilema: quais valores estão em conflito? Quem é afetado? Quais as consequências? Que princípio universal poderia orientar? Esse tema prepara os seguintes, política e democracia e teoria do conhecimento, e dá repertório para a redação, em que a argumentação ética é frequentemente necessária, em especial nas propostas que envolvem direitos, deveres e responsabilidade social.'] }
]},
{ t:'Política e democracia', txt:[
 { h:'O que é política e a origem do poder', p:[
  'A palavra **política** vem de **pólis**, a cidade-Estado grega, e originalmente se refere a tudo o que diz respeito à vida coletiva da cidade. Para **Aristóteles**, o ser humano é um **animal político**, e só realiza plenamente sua natureza vivendo em comunidade. A política é a atividade de decidir, de modo coletivo, as regras e os rumos da vida em comum, o **bem comum**, e envolve a questão do **poder**: quem manda, com que legitimidade e com que limites. A Filosofia política analisa conceitos como justiça, liberdade, igualdade, Estado, soberania, direito, cidadania e democracia.',
  'O **poder** é a capacidade de determinar o comportamento de outros, que pode se basear na **força**, na **persuasão**, na **tradição** ou no **consentimento**. O sociólogo **Max Weber** distingue três formas de **dominação legítima**: a **tradicional** (fundada nos costumes, como a monarquia hereditária), a **carismática** (fundada na liderança excepcional de uma pessoa) e a **racional-legal** (fundada em regras impessoais e na burocracia, característica do Estado moderno). A pergunta da **legitimidade** é central: por que é justo obedecer? Diversas respostas foram dadas, do direito divino dos reis ao contrato social.',
  'O **Estado** moderno é a organização política que detém o **monopólio do uso legítimo da força** em um território, nas palavras de Weber, e exerce soberania sobre uma população. Distingue-se do **governo**, que é o grupo que administra o Estado temporariamente, e da **nação**, comunidade cultural. A Filosofia política pergunta qual é a melhor forma de Estado, quais são os limites do poder, quais direitos os indivíduos têm diante dele e como combinar a **ordem** com a **liberdade**. As respostas de Platão, Aristóteles, Maquiavel, Hobbes, Locke, Rousseau, Montesquieu, Marx e Arendt, entre outros, formam o repertório desse debate.'] },
 { h:'Formas de governo e regimes políticos', p:[
  'Desde a Antiguidade, os pensadores classificam as **formas de governo**. Aristóteles as distinguiu pelo número de governantes e pelo fim: a **monarquia** (governo de um), a **aristocracia** (de poucos) e a **politeia** (de muitos), que visam ao bem comum, e suas formas corrompidas, a **tirania**, a **oligarquia** e a **democracia** (no sentido de governo da massa em seu próprio interesse). Montesquieu distinguiu a república, a monarquia e o despotismo. Hoje, costuma-se contrastar **regimes democráticos** e **autoritários** ou **totalitários**, e as formas de Estado (unitário e federal) e de governo (presidencialismo e parlamentarismo).',
  'A **democracia** (do grego demos, "povo", e kratos, "poder") é o regime em que o poder pertence ao povo. Na democracia **direta**, como em Atenas, os cidadãos decidem diretamente nas assembleias, mas a cidadania era restrita a uma minoria (homens livres, adultos e nascidos na cidade). Nas democracias **representativas** modernas, o povo escolhe, pelo voto, representantes que decidem em seu nome. Há ainda mecanismos de **democracia participativa** (plebiscito, referendo, iniciativa popular, conselhos, orçamento participativo). Os regimes **autoritários** concentram o poder, limitam as liberdades e a participação, e os **totalitários** buscam o controle total da sociedade, como visto em Hannah Arendt.',
  'A ideia de democracia é complexa. Envolve eleições livres e periódicas, **pluralismo** político, **liberdade de expressão** e de imprensa, **direitos fundamentais**, **separação dos poderes**, **estado de direito**, proteção das minorias e controle do poder. Não se reduz ao voto da maioria, que pode oprimir as minorias (a "tirania da maioria", de Tocqueville e Mill). Por isso, a democracia liberal combina o princípio majoritário com os **direitos individuais** e as **instituições** que limitam o poder. Sua qualidade depende da educação, da informação e da participação dos cidadãos.'] },
 { h:'Liberalismo, socialismo, justiça e igualdade', p:[
  'As principais correntes políticas modernas se distinguem por sua visão de liberdade e de igualdade. O **liberalismo** (Locke, Montesquieu, Mill) defende a **liberdade individual**, os direitos naturais, o governo limitado, a propriedade privada, a livre-iniciativa e o Estado de direito. Seu lema é o de que o Estado deve garantir as liberdades e interferir pouco. O **socialismo** (Marx e outros) destaca a **igualdade** e a crítica às desigualdades geradas pelo capitalismo, defendendo a propriedade coletiva ou a regulação da economia. A **social-democracia** busca combinar a democracia liberal e o mercado com um Estado de bem-estar social, que garanta direitos sociais.',
  '**John Rawls**, em **Uma Teoria da Justiça** (1971), propôs uma concepção de justiça como **equidade**. Imagina a "**posição original**", uma situação hipotética em que pessoas, cobertas por um "**véu de ignorância**" (sem saber sua classe, sexo, raça, talentos e situação), escolheriam os princípios de justiça da sociedade. Elas escolheriam: 1) a **igual liberdade** básica para todos; 2) a desigualdade só seria aceitável se beneficiasse os menos favorecidos e se houvesse **igualdade de oportunidades**. Essa teoria fundamenta políticas de redistribuição e de proteção social, e é um dos principais debates da filosofia política contemporânea.',
  'A discussão sobre **igualdade** e **liberdade** também envolve o **conceito de cidadania**, que o sociólogo T. H. Marshall descreveu em três dimensões: **civil** (direitos individuais), **política** (participação) e **social** (educação, saúde, trabalho). A **justiça** pode ser entendida como a distribuição justa de bens e de ônus (justiça distributiva), a reparação de danos (justiça corretiva) e o respeito às regras (justiça processual). Debates atuais incluem as ações afirmativas, a renda mínima, a tributação dos mais ricos, o acesso à saúde e à educação, e os direitos das minorias. Cada posição reflete concepções distintas de justiça.'] },
 { h:'Democracia no Brasil, participação e desafios atuais', p:[
  'No Brasil, a **Constituição de 1988** instituiu o Estado Democrático de Direito, com eleições diretas, pluripartidarismo, direitos fundamentais, separação dos poderes e instrumentos de participação direta (plebiscito, referendo e iniciativa popular), além de conselhos e conferências de políticas públicas. O voto é obrigatório para a maioria, e facultativo para analfabetos, jovens de 16 e 17 anos e maiores de 70. A trajetória democrática foi interrompida por períodos autoritários (o Estado Novo e a Ditadura Militar), e a redemocratização trouxe avanços em direitos e instituições, mas persistem desafios, como a desigualdade, a corrupção e a violência política.',
  'Os **desafios da democracia** contemporânea são muitos: a **desconfiança** nas instituições e nos partidos, a **polarização**, a **desinformação** e as **fake news**, que corroem o debate público, o poder do dinheiro nas campanhas, a sub-representação de mulheres, negros e indígenas, a **abstenção** e a apatia, e o risco de líderes que enfraquecem as instituições, por dentro, em nome do povo, o **populismo**. A **participação** vai além do voto: envolve o acompanhamento dos representantes, a organização em associações, sindicatos e movimentos, a **desobediência civil** em casos extremos, e o uso de canais de transparência.',
  'A **educação política** e a **cultura democrática**, que incluem a tolerância, o respeito às diferenças e a disposição ao diálogo, são fundamentais. Para a **democracia deliberativa**, de Habermas, a legitimidade das decisões vem da discussão pública, em que todos podem apresentar argumentos. A tecnologia traz oportunidades (a participação digital) e riscos (a manipulação por algoritmos e a vigilância). Hannah Arendt lembra que a liberdade política só existe se houver espaço público e pluralidade. O estudante deve compreender que a democracia é uma construção contínua, que exige vigilância e participação, e não um dado garantido.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Política e democracia aparecem no ENEM em questões sobre cidadania, formas de governo, democracia direta e representativa, participação política, direitos, justiça e igualdade, com trechos de Aristóteles, Maquiavel, Rousseau, Locke, Montesquieu, Arendt, Rawls e outros, ou situações atuais (eleições, manifestações, abstenção, fake news e polarização). As perguntas pedem a identificação do conceito, a relação entre as concepções de poder e de democracia e a avaliação de práticas políticas. Esse tema se articula com a Sociologia (Estado, poder, cidadania) e com a História (Atenas, Revolução Francesa, ditaduras).',
  'Pontos de atenção: a política é a atividade da vida coletiva e do bem comum; a democracia envolve participação, direitos e limites ao poder; a democracia ateniense era direta, mas excludente; a democracia moderna é, em geral, representativa; liberalismo e socialismo ressaltam, respectivamente, a liberdade e a igualdade; a justiça como equidade, de Rawls, usa o véu de ignorância; a legitimidade do poder pode ser tradicional, carismática ou racional-legal (Weber). Cuide para não reduzir a democracia ao voto, nem confundir Estado com governo.',
  'Para revisar, monte um quadro com as formas de governo e os regimes, as correntes políticas (liberalismo, socialismo e social-democracia), os principais autores e uma frase de cada. Treine relacionar uma notícia atual a um conceito (por exemplo, a participação popular a Rousseau, a separação dos poderes a Montesquieu e a banalidade do mal a Arendt). Esse tema fecha a parte política da Filosofia e se conecta ao seguinte, a teoria do conhecimento, que trata de outra grande pergunta: o que é conhecer, e como saber se algo é verdadeiro?'] }
]},
{ t:'Teoria do conhecimento', txt:[
 { h:'O problema do conhecimento: o que é conhecer?', p:[
  'A **teoria do conhecimento** (ou **epistemologia**, do grego episteme, "conhecimento", e logos) é a área da Filosofia que investiga a **natureza**, a **origem**, os **limites** e a **validade** do conhecimento. Seus problemas básicos são: o que é conhecer? Como conhecemos? Quais são as fontes do saber (razão, experiência, intuição, testemunho)? É possível conhecer a realidade tal como é? Como distinguir o conhecimento da mera opinião, da crença e do erro? O problema do conhecimento está presente desde os pré-socráticos e Platão, mas ganhou centralidade na Filosofia moderna, em Descartes, Locke, Hume e Kant.',
  'Platão, no **Teeteto**, propôs a definição clássica do conhecimento como "**crença verdadeira justificada**": para saber algo, não basta acreditar, é preciso que a crença seja verdadeira e que tenhamos **boas razões** que a sustentem. Por exemplo, alguém que acerta o resultado de um jogo por pura sorte não "sabe" o resultado. Essa definição distingue o conhecimento da **opinião** (doxa) e da **superstição**. O que conta como uma boa justificativa, e quais são os critérios de verdade, são questões em debate, e diferentes teorias oferecem respostas.',
  'A **verdade** é uma noção central. A teoria da **correspondência** diz que um enunciado é verdadeiro quando corresponde aos fatos ("dizer do que é que é"). A teoria da **coerência** diz que uma crença é verdadeira se for coerente com um sistema de outras crenças. A teoria **pragmática** (William James, Peirce) considera verdadeiro o que funciona e produz bons resultados na prática. A teoria **consensual** vincula a verdade ao acordo racional entre as pessoas. Cada uma ilumina um aspecto, e juntas mostram que a questão da verdade é complexa, o que é importante em um tempo de "pós-verdade".'] },
 { h:'As correntes: dogmatismo, ceticismo, racionalismo, empirismo e criticismo', p:[
  'Quanto à **possibilidade** do conhecimento, o **dogmatismo** afirma que podemos conhecer a verdade com certeza, e que a razão ou os sentidos são confiáveis, sem questionar. O **ceticismo** duvida dessa possibilidade: como os sentidos e a razão podem nos enganar, e como cada argumento tem um contrário, devemos suspender o juízo. O ceticismo **radical** nega qualquer conhecimento, e o **moderado** reconhece graus de probabilidade e a necessidade de cautela. O **relativismo** afirma que a verdade depende do sujeito ou da cultura. O **criticismo** (Kant) examina os limites e as condições do conhecimento, antes de afirmar ou negar o que podemos saber.',
  'Quanto à **origem** do conhecimento, o **racionalismo** (Descartes, Espinosa, Leibniz) considera a **razão** a fonte principal, com ideias inatas e verdades universais e necessárias, como as da matemática. O **empirismo** (Bacon, Locke, Hume) afirma que todo o conhecimento vem da **experiência** sensível, e que a mente é uma tábula rasa. O **intelectualismo** busca conciliar ambos (Aristóteles e Tomás de Aquino): o conhecimento começa nos sentidos, mas o intelecto abstrai o universal. O **criticismo** de Kant sintetiza: o conhecimento começa com a experiência, mas depende das formas a priori da sensibilidade e das categorias do entendimento. O **pragmatismo** valoriza a utilidade prática.',
  'No século XX, a discussão se ampliou com a **fenomenologia** de Husserl, que estuda a consciência e a experiência vivida, a **hermenêutica** (Gadamer), que destaca a interpretação e a história, e a **filosofia da linguagem**, que analisa como a linguagem estrutura o pensamento. Também surgiu a **epistemologia social**, que estuda o papel do testemunho, das instituições e dos grupos na produção do conhecimento. As **epistemologias do Sul**, de Boaventura de Sousa Santos, defendem o reconhecimento de saberes de povos tradicionais e de grupos marginalizados, em diálogo com a ciência, ampliando a ideia de conhecimento. Essas abordagens dialogam com debates atuais sobre diversidade e decolonialidade.'] },
 { h:'A ciência e o método científico', p:[
  'A **ciência** é uma forma de conhecimento sistemática, baseada em **observação**, **hipóteses**, **experimentação**, **teorias** e **revisão** pelos pares. A **filosofia da ciência** investiga seu método e seus limites. O **método indutivo**, defendido por Bacon, parte de observações particulares para chegar a leis gerais. O **método hipotético-dedutivo** (usado por Galileu e Newton) formula hipóteses, deduz consequências e as testa por experimentos. **Karl Popper** (1902-1994) argumentou que o que distingue a ciência é a **falseabilidade**: uma teoria é científica se pode, em princípio, ser **refutada** por evidências. Teorias que explicam qualquer coisa (como a astrologia) não são científicas.',
  '**Thomas Kuhn**, em **A Estrutura das Revoluções Científicas** (1962), propôs que a ciência não avança de forma linear e cumulativa, mas por **paradigmas**: um conjunto de teorias, métodos e exemplos aceitos por uma comunidade científica, que orienta a pesquisa ("ciência normal"). Quando surgem **anomalias** que o paradigma não explica, ocorre uma **crise** e, depois, uma **revolução científica**, que substitui o paradigma (por exemplo, do geocentrismo ao heliocentrismo, da física newtoniana à relatividade). Para Kuhn, os paradigmas não são completamente comparáveis, e a escolha entre eles envolve fatores sociais. Essa visão destacou o caráter **histórico** e **social** da ciência.',
  'A ciência é a forma mais confiável que temos de conhecer a natureza, mas não é infalível nem neutra. Seus resultados são **provisórios** e passíveis de revisão, e a produção científica é afetada por interesses econômicos e políticos. Em debates como a vacinação, as mudanças climáticas e a evolução, o ceticismo ao negacionismo científico é diferente do **ceticismo saudável**, que exige provas. Distinguir **ciência** de **pseudociência** e de **senso comum** é uma habilidade importante. O pensamento científico, com sua exigência de evidências, a revisão por pares e a transparência dos métodos, é um aliado da democracia e da cidadania.'] },
 { h:'Verdade, opinião, ideologia e pós-verdade', p:[
  'Na vida cotidiana, nem tudo o que acreditamos foi verificado: grande parte do que sabemos vem do **testemunho** de outras pessoas e instituições. Por isso, é essencial avaliar a **confiabilidade das fontes**, checar informações e desconfiar de afirmações que apenas confirmam nossas crenças prévias (**viés de confirmação**). O **senso comum** é útil, mas pode conter preconceitos. A **opinião** é uma crença sem justificação rigorosa. A **ideologia**, no sentido crítico (Marx), é um conjunto de ideias que oculta os interesses de um grupo e apresenta como natural uma ordem social, o que também afeta o conhecimento.',
  'O termo **pós-verdade** designa a situação em que os fatos objetivos têm menos influência na formação da opinião pública do que os apelos à emoção e às crenças pessoais. As **fake news**, os algoritmos que criam "bolhas" de informação e a polarização dificultam o debate racional. A teoria do conhecimento fornece ferramentas para enfrentar esse cenário: a distinção entre fato e opinião, a exigência de justificação, o respeito às evidências, a atenção às falácias e o exame das fontes. O pensamento crítico, estimulado pela Filosofia, é um recurso de proteção.',
  'Também há debates sobre os **limites do conhecimento**. Alguns fenômenos, como a consciência, o início do universo e o sentido da vida, resistem às explicações. Kant mostrou que a razão tem limites e cai em contradições quando pretende ir além da experiência. Hoje, a inteligência artificial levanta novas perguntas: um sistema que gera textos "sabe" o que diz? O que significa compreender? Essas questões mostram a atualidade da epistemologia, e a importância de cultivar a **humildade intelectual**, a abertura para rever as próprias crenças, e a disposição para o diálogo.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A teoria do conhecimento aparece no ENEM em questões que trazem trechos de Descartes, Locke, Hume, Kant ou Popper, e pedem a identificação de posições (racionalismo, empirismo, ceticismo, criticismo), o método científico, o conceito de paradigma e a diferença entre ciência, senso comum e pseudociência. Também aparecem situações atuais, como fake news, negacionismo, pós-verdade e uso de dados, em que se exige a aplicação de critérios de avaliação de informações. A habilidade principal é analisar como se produz e se valida o conhecimento.',
  'Pontos de atenção: o conhecimento é crença verdadeira justificada; o racionalismo valoriza a razão e as ideias inatas, e o empirismo, a experiência; o ceticismo duvida e suspende o juízo; o criticismo de Kant examina os limites do conhecimento; Popper defende a falseabilidade como critério de ciência; Kuhn explica as mudanças de paradigma; o negacionismo científico confunde dúvida legítima com recusa de evidências. Evite tratar a ciência como verdade absoluta ou como mera opinião: ela é falível, mas é o método mais confiável para conhecer a realidade.',
  'Para revisar, monte um quadro com as correntes (dogmatismo, ceticismo, racionalismo, empirismo, criticismo), os autores e as ideias centrais, e um segundo com Bacon (indução), Popper (falseabilidade) e Kuhn (paradigmas). Treine a checagem de uma notícia: quem disse, qual a fonte, quais as evidências, há outras fontes? Esse tema se conecta à lógica e à argumentação, o último tema da matéria, e à Estética, que trata de outra forma de conhecer e de experimentar o mundo, a arte, que veremos a seguir.'] }
]}
];
