/* Filosofia: textos corridos, temas 4 a 6 */
module.exports = [
{ t:'Sócrates e os sofistas', txt:[
 { h:'Atenas, a democracia e a virada antropológica', p:[
  'No século V a.C., **Atenas** viveu seu apogeu político e cultural, sob a liderança de Péricles. A democracia ateniense exigia dos cidadãos a participação nas decisões da Assembleia, na ágora, e para isso era preciso saber **falar e argumentar em público**. A vida na cidade, com suas leis, seus conflitos e suas escolhas, passou a ocupar o centro das preocupações dos pensadores. A Filosofia deixou de se concentrar apenas na natureza (o cosmos) e voltou-se para o **ser humano**: a moral, a política, a linguagem, a educação e a virtude. Por isso, esse momento é chamado de **período antropológico** (ou humanista).',
  'Nesse contexto, surgiram os **sofistas**, educadores itinerantes, vindos de várias cidades, que ofereciam, em troca de pagamento, aulas de **retórica** (a arte de persuadir pelo discurso), de gramática, de política e de outras disciplinas, formando jovens para a vida pública. Entre os mais conhecidos estão **Protágoras de Abdera**, **Górgias de Leontini**, **Pródico** e **Hípias**. O termo "sofista", que significava "sábio", acabou adquirindo um sentido negativo, graças às críticas de Platão e de Aristóteles, e hoje "sofisma" designa um argumento aparentemente válido, mas enganoso.',
  '**Sócrates** (469-399 a.C.), ateniense, filho de um escultor e de uma parteira, é uma figura central. Não deixou nada escrito: conhecemos seu pensamento principalmente pelos diálogos de seu discípulo **Platão**, pelos escritos de Xenofonte e pela caricatura de Aristófanes, na comédia As Nuvens. Passava os dias na ágora, conversando com os atenienses, de todas as classes, sobre temas como a justiça, a coragem, a piedade e a virtude. Sua atitude combinava curiosidade, ironia e compromisso com a verdade, e ele é considerado o **fundador da Filosofia moral** e um marco que dividiu a Filosofia grega.'] },
 { h:'Os sofistas: relativismo, retórica e crítica', p:[
  'Os sofistas contribuíram para o pensamento ao colocar em questão as **tradições**, os costumes e as leis, e ao discutir a diferença entre **natureza** (physis) e **convenção** (nomos). Perceberam que cada cidade tinha leis, religiões e valores diferentes, e concluíram que muitos desses valores eram **convencionais**, e não naturais. A frase mais famosa de **Protágoras** é "o homem é a medida de todas as coisas, das que são, enquanto são, e das que não são, enquanto não são", que costuma ser interpretada como um **relativismo**: a verdade e o valor dependem da perspectiva de cada pessoa ou comunidade.',
  'A **retórica** era, para os sofistas, o instrumento central. Eles ensinavam a construir discursos persuasivos e a defender qualquer tese, bem como o seu contrário, o que dava poder aos que dominavam a palavra em uma democracia direta. **Górgias** sustentou que o discurso tem um poder semelhante ao de uma droga sobre a alma, capaz de convencer e de enganar. Essa ênfase na **eficácia** da persuasão, em vez de na busca da verdade, foi a principal crítica de Platão, que a acusava de fazer da linguagem uma arma, e dos sofistas "mercadores de saber", que vendiam um conhecimento de aparência.',
  'É importante, porém, reconhecer o aspecto **positivo** do movimento: os sofistas democratizaram o ensino, que antes era privilégio da aristocracia, desenvolveram a reflexão sobre a linguagem, a argumentação e a lógica, estimularam o **senso crítico** e a análise das leis, e levantaram problemas éticos e políticos que a Filosofia posterior enfrentou. Muitos pensadores atuais retomaram a questão do relativismo e do papel da linguagem. A distinção entre persuadir e **demonstrar a verdade** continua atual, em um mundo de publicidade, propaganda política e desinformação, em que o poder da retórica é imenso.'] },
 { h:'O método socrático: ironia e maiêutica', p:[
  'Sócrates também se dedicava a conversar e a discutir, mas com um propósito oposto ao dos sofistas: **buscar a verdade**, e não vencer o debate. Não cobrava pelas conversas, e afirmava nada saber. Em sua defesa, no julgamento, relatou que o oráculo de Delfos havia dito que ele era o mais sábio dos homens, e que concluiu que sua sabedoria consistia em **reconhecer a própria ignorância**: "só sei que nada sei". Esse reconhecimento, a "ignorância socrática", é o ponto de partida do saber verdadeiro, pois quem acredita já saber não procura. Outro lema de Sócrates, inscrito em Delfos, era "**conhece-te a ti mesmo**".',
  'Seu **método** tinha dois momentos. Na **ironia** (do grego eironeia, "perguntar fingindo ignorar"), Sócrates fazia perguntas aparentemente ingênuas a seu interlocutor, sobre um conceito, como "o que é a coragem?", e, a partir das respostas, mostrava as **contradições** e as insuficiências, levando-o a perceber que não sabia o que julgava saber. Esse momento é o da **refutação**, e costumava ser desconfortável, porque abalava as certezas. Na **maiêutica** (do grego maieutiké, "arte de partejar", em referência à profissão de sua mãe), ele ajudava o interlocutor a "dar à luz" as ideias que já tinha, conduzindo-o, por meio de perguntas, à **definição** correta e universal do conceito.',
  'Sócrates buscava a **definição universal** das virtudes: não exemplos de atos corajosos, mas a essência da coragem, válida para todos os casos. Para ele, a **virtude** (arete) é **conhecimento**: ninguém faz o mal voluntariamente, pois quem conhece o bem o pratica, e o mal resulta da **ignorância**. Esse **intelectualismo moral** sustenta que a educação e o diálogo podem tornar as pessoas melhores. A vida examinada, segundo ele, é a única que vale a pena ser vivida: "uma vida sem exame não vale a pena ser vivida". Esse ideal de uma vida guiada pela razão e pela busca da verdade marcou toda a tradição ocidental.'] },
 { h:'O julgamento e a morte de Sócrates', p:[
  'Sócrates incomodava. Questionava a autoridade dos políticos, dos poetas e dos artesãos, mostrando que não sabiam o que diziam saber, e isso lhe rendeu inimigos. Atenas vivia um período de crise, após a derrota na **Guerra do Peloponeso** (404 a.C.) e o governo dos "Trinta Tiranos", e a restauração democrática, em 403 a.C., estava marcada por desconfiança. Em 399 a.C., aos 70 anos, Sócrates foi acusado por Meleto, Ânito e Lícon de **não reconhecer os deuses da cidade**, de **introduzir novas divindades** (o seu "daimon", uma voz interior que o orientava) e de **corromper a juventude**, ao ensinar os jovens a duvidar das tradições.',
  'O julgamento, relatado na **Apologia de Sócrates**, de Platão, mostra um filósofo que se defende sem súplicas, e afirma que cumpria uma missão divina ao examinar os outros, "um moscardo" que desperta a cidade, como um cavalo preguiçoso. Foi condenado por uma pequena maioria, e, em vez de propor o exílio ou uma multa, sugeriu que merecia ser sustentado pela cidade. Condenado à morte, recusou fugir da prisão, como lhe propunha seu amigo Críton, pois considerava que deveria respeitar as leis da cidade, mesmo sendo injustas, o que mostra seu compromisso com a lei. Morreu bebendo **cicuta**, serenamente, com seus discípulos.',
  'A morte de Sócrates é um símbolo do **conflito entre o pensamento livre e o poder**, e do risco que o questionamento crítico pode trazer. Também revelou a tensão da própria democracia ateniense, que condenou o seu mais famoso filósofo. Para Platão, que ficou profundamente marcado, a experiência reforçou a desconfiança em relação à democracia e a busca por uma cidade governada pelos mais sábios. A figura de Sócrates inspirou a ideia do filósofo como **consciência crítica** da sociedade, e continua a ser invocada nos debates sobre a liberdade de expressão e o papel dos intelectuais.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, Sócrates e os sofistas aparecem em questões que trazem trechos de diálogos, da Apologia ou de textos sobre a maiêutica, e pedem para identificar o método socrático (perguntas, ironia e busca da definição), a diferença entre Sócrates e os sofistas (verdade versus persuasão, e relativismo versus busca de conceitos universais), ou a relação entre a Filosofia e a democracia. Também pode ser cobrada a frase "só sei que nada sei" e o sentido da ignorância socrática, ou ainda situações modernas que se pareçam com o método socrático ou com os sofismas.',
  'Pontos de atenção: a Filosofia deixa de se ocupar do cosmos para se ocupar do ser humano; os sofistas eram professores de retórica, e Protágoras defendia que o homem é a medida de todas as coisas (relativismo); Sócrates buscava a verdade e a definição universal, por meio da ironia e da maiêutica; para ele, a virtude é conhecimento e o mal é ignorância; foi condenado por impiedade e por corromper a juventude. Evite confundir a maiêutica (ajudar a produzir ideias) com a ironia (mostrar contradições), e lembre que Sócrates não escreveu.',
  'Para revisar, monte um quadro comparando Sócrates e os sofistas (objetivo, método, relação com a verdade, relação com o dinheiro e com a moral) e uma frase de cada autor. Releia a descrição da morte de Sócrates, e pense em por que ele a aceitou. Esse tema prepara o seguinte, Platão, discípulo de Sócrates, que transformou suas questões em um sistema filosófico, com a teoria das ideias, a alegoria da caverna e a proposta de uma cidade justa, governada por filósofos.'] }
]},
{ t:'Platão', txt:[
 { h:'Vida, obra e o pensamento de Platão', p:[
  '**Platão** (428/427-348/347 a.C.) nasceu em Atenas, em uma família aristocrática, e foi discípulo de Sócrates, cuja condenação à morte o marcou profundamente. Depois de viajar pelo Egito, pela Itália e por Siracusa, fundou, por volta de 387 a.C., a **Academia**, considerada a primeira escola de Filosofia organizada, que durou quase nove séculos e teve entre seus alunos **Aristóteles**. Escreveu **diálogos**, em que Sócrates é frequentemente o personagem principal, como a Apologia, o Fédon, O Banquete, a República, o Fedro, o Teeteto e as Leis. O diálogo é uma forma literária e filosófica que reflete a ideia de que a busca da verdade se faz pela conversa.',
  'O pensamento de Platão buscou superar o **relativismo** dos sofistas e o **fluxo** de Heráclito, mostrando que existe um conhecimento verdadeiro e estável, que não depende da opinião, nem das sensações. Para isso, ele desenvolveu a **teoria das ideias** (ou das formas), que explica o ser e o conhecer, e a filosofia política da **República**, que descreve uma cidade justa. Sua obra abrange metafísica, epistemologia, ética, política, estética e educação, e influenciou toda a tradição ocidental, a ponto de o filósofo Alfred North Whitehead dizer que a história da Filosofia ocidental é "uma série de notas de rodapé a Platão".',
  'Um ponto central é a distinção entre o **conhecimento** (episteme), universal, necessário e verdadeiro, e a **opinião** (doxa), variável, subjetiva e sujeita ao erro. Os sentidos nos dão apenas opiniões sobre um mundo em constante mudança, enquanto a razão pode alcançar conhecimento verdadeiro sobre realidades **imutáveis**. Esse **dualismo** entre o sensível e o inteligível organiza grande parte do pensamento platônico. A pergunta de Sócrates "o que é?" (o que é a justiça, o que é o belo) é respondida por Platão como a procura da **ideia** (eidos) ou forma de cada coisa.'] },
 { h:'A teoria das ideias e os dois mundos', p:[
  'Segundo Platão, a realidade se divide em dois planos ou "mundos". O **mundo sensível** (ou das aparências) é o mundo em que vivemos, percebido pelos sentidos, composto por coisas particulares e mutáveis, que nascem, mudam e morrem: um cavalo, uma flor, uma ação justa. Esse mundo é imperfeito e instável. O **mundo inteligível** (ou das ideias) é o mundo das **ideias** ou **formas**, essências universais, eternas e imutáveis, apreendidas apenas pela razão, como o Belo em si, o Bem em si, a Justiça em si e o Círculo em si. Essas ideias são o **modelo** (paradigma), e as coisas sensíveis são cópias imperfeitas deles, que "participam" da ideia.',
  'No topo da hierarquia das ideias está a **ideia do Bem**, que Platão compara ao Sol: assim como o Sol dá luz e vida às coisas visíveis, o Bem é a fonte da verdade, do ser e da inteligibilidade de todas as ideias. Conhecer o Bem é o objetivo máximo do filósofo. Para explicar como conhecemos as ideias, Platão formulou a teoria da **reminiscência**: a alma, antes de nascer, contemplou as ideias, e o conhecimento é uma **lembrança** (anamnese) provocada pelas experiências sensíveis. Aprender, portanto, é recordar, e o papel do mestre é, como em Sócrates, ajudar o discípulo a recordar.',
  'A concepção de Platão tem consequências para a **alma** e o **corpo**. A alma é imortal, de natureza semelhante às ideias, e está "presa" ao corpo, que é mortal. Em uma imagem do diálogo Fedro, a alma é como uma carruagem puxada por dois cavalos, um dócil (a vontade nobre) e um rebelde (os apetites), conduzida pela razão (o cocheiro). A **justiça** na alma é a harmonia das três partes: a razão (alma racional), o ímpeto (alma irascível) e o desejo (alma concupiscível). Essa estrutura da alma é a base da ética e da política de Platão, como se verá na República.'] },
 { h:'A alegoria da caverna', p:[
  'A **alegoria da caverna**, apresentada no Livro VII da **República**, é uma das imagens mais famosas da Filosofia e ilustra a teoria das ideias, a educação e a condição humana. Platão descreve prisioneiros que vivem, desde o nascimento, acorrentados no fundo de uma caverna, de costas para a entrada, só vendo as **sombras** projetadas na parede, produzidas por objetos que são carregados por pessoas atrás de uma fogueira. Como nunca viram outra coisa, os prisioneiros acreditam que as sombras são a realidade, e dão nomes a elas e disputam sobre elas.',
  'Um dos prisioneiros é libertado e obrigado a subir e a sair da caverna. A princípio, a luz o ofusca, e ele sofre, e quer voltar às sombras, que lhe parecem mais verdadeiras. Aos poucos, acostuma-se, e vê as coisas reais, e por fim o **Sol**, que representa a ideia do Bem. Compreende, então, que as sombras eram apenas imagens. Movido pela compaixão, volta à caverna para libertar os companheiros, mas, com os olhos acostumados à luz, move-se mal no escuro, e é ridicularizado. Os prisioneiros o consideram louco e perigoso, e se o conseguissem, o matariam, uma alusão ao destino de Sócrates.',
  'A alegoria tem várias leituras. A **caverna** é o mundo sensível, e as **sombras**, as opiniões e as aparências. A **saída** é o caminho da **educação** e da Filosofia, difícil e doloroso, que leva do mundo sensível ao inteligível. O **Sol** é a ideia do Bem. O **retorno** é o dever do filósofo de educar e de governar. A alegoria também pode ser lida como uma crítica à ignorância, ao conformismo e à manipulação, e, por isso, é usada para pensar situações atuais, como o poder dos meios de comunicação, as redes sociais, as bolhas de informação, a propaganda e a sociedade do espetáculo, que oferecem "sombras" de realidade.'] },
 { h:'A política em Platão: a cidade justa e o rei-filósofo', p:[
  'Na **República**, Platão discute a **justiça** e propõe a construção de uma cidade ideal, em que a justiça se realize. Como a alma, a cidade tem três partes, e a justiça consiste em cada uma cumprir sua função, em harmonia. Os **governantes** (filósofos), movidos pela razão, devem governar, com sabedoria; os **guardiões** (guerreiros), movidos pela coragem, defendem a cidade; e os **produtores** (agricultores, artesãos e comerciantes), movidos pelos desejos, sustentam materialmente a cidade. Cada um deve exercer a função para a qual tem aptidão, e a divisão social se justifica pela natureza de cada pessoa, e não pela origem familiar.',
  'Para Platão, quem deve governar é o **filósofo**, pois somente quem conhece o Bem pode orientar a cidade para o bem comum. Daí a célebre tese de que "enquanto os filósofos não forem reis, ou os reis não forem filósofos, não haverá fim para os males da cidade". O **rei-filósofo** é formado por uma longa educação, que passa pela ginástica, pela música, pela matemática, pela dialética, e que o leva a contemplar as ideias. Para evitar a corrupção, os guardiões e os governantes não teriam propriedade privada nem família, e viveriam em comum, o que expressa o ideal de uma elite dedicada ao bem público.',
  'Platão critica as formas degeneradas de governo: a **timocracia** (governo dos honrados e dos guerreiros), a **oligarquia** (dos ricos), a **democracia** (da multidão, que confunde liberdade e licenciosidade e é vulnerável a demagogos) e a **tirania** (a pior). Sua crítica à democracia, que condenara Sócrates, é muito discutida: é vista por alguns como elitista e autoritária, por defender uma hierarquia fundada no saber, e por outros como uma lembrança de que a política exige conhecimento e responsabilidade. Mesmo assim, a República inspirou a ideia de que a educação e a justiça são as bases da política, e o debate sobre os limites entre o saber e o poder.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Platão é um dos filósofos mais cobrados no ENEM. As questões trazem trechos da alegoria da caverna, da República ou do Fedro, e pedem a identificação do mundo sensível e do inteligível, da relação entre aparência e realidade, da função da educação, ou da concepção de política e de justiça. Também são frequentes as questões que fazem analogias com o mundo atual (a mídia, a internet, a alienação) e pedem para relacionar a caverna com a manipulação das informações ou com a falta de pensamento crítico.',
  'Pontos de atenção: o mundo das ideias é o verdadeiro, imutável e racional, e o sensível é aparência e cópia; o conhecimento verdadeiro (episteme) se distingue da opinião (doxa); a alegoria da caverna representa o caminho da educação e da Filosofia; a ideia do Bem é a mais alta; a justiça é a harmonia das partes da alma e da cidade; e o rei-filósofo governa pela sabedoria. Não confunda o idealismo platônico com "idealismo" no sentido de ser sonhador: aqui, "ideia" é a essência real das coisas. Atenção também ao contraste com Aristóteles, que veremos a seguir.',
  'Para revisar, desenhe a caverna, com os elementos (sombras, fogueira, prisioneiros, o mundo exterior e o Sol) e o que cada um representa. Faça um quadro com a alma, a cidade e as virtudes correspondentes: razão e sabedoria, ímpeto e coragem, desejos e temperança, e a justiça como harmonia. Treine relacionar a alegoria a situações atuais. Esse tema se completa com Aristóteles, discípulo de Platão, que criticou a separação entre dois mundos e propôs uma Filosofia mais ligada à experiência e à natureza.'] }
]},
{ t:'Aristóteles', txt:[
 { h:'Vida, obra e a crítica a Platão', p:[
  '**Aristóteles** (384-322 a.C.) nasceu em Estagira, na Macedônia, filho de um médico da corte, o que talvez explique seu interesse pela observação da natureza. Aos 17 anos, foi para Atenas e estudou por quase 20 anos na **Academia** de Platão, onde se destacou. Após a morte de Platão, passou um tempo viajando, e foi preceptor de **Alexandre, o Grande**, na Macedônia. Em 335 a.C., voltou a Atenas e fundou o **Liceu**, escola cujo nome vem do templo de Apolo Lício, também chamada de **peripatética**, porque se discutia caminhando (peripatein). Escreveu sobre quase todas as áreas do saber: lógica, física, biologia, metafísica, ética, política, retórica e poética.',
  'Embora discípulo de Platão, Aristóteles criticou a **teoria das ideias**. Para ele, não havia um mundo separado de formas ideais: a forma de uma coisa está **na própria coisa**, e não fora dela. Uma frase atribuída a ele é "amigo de Platão, mas ainda mais amigo da verdade". Platão, na imagem de Rafael, na Escola de Atenas, aponta o dedo para o alto, para as ideias, e Aristóteles estende a mão para a terra, para a experiência. Essa diferença simboliza dois caminhos: o do **racionalismo idealista** (Platão) e o do **empirismo realista** (Aristóteles), que valoriza a observação do mundo concreto, a classificação e a experiência.',
  'Aristóteles considerava que o conhecimento começa nos **sentidos**, na experiência das coisas particulares, mas não termina neles: a razão abstrai das coisas concretas o **universal**, a essência comum. Seu método combina observação, classificação e **raciocínio lógico**. Foi um grande sistematizador, e dividiu as ciências em **teóricas** (física, matemática e metafísica, cujo fim é o saber), **práticas** (ética e política, que tratam da ação) e **produtivas** (poética e técnica, que tratam da produção). A **lógica**, que ele chamou de "analítica", é o instrumento (órganon) de todas as ciências.'] },
 { h:'Metafísica: substância, matéria e forma, potência e ato', p:[
  'Para Aristóteles, a metafísica (ou "filosofia primeira") estuda o **ser enquanto ser**, e as causas e princípios mais gerais. A realidade fundamental é a **substância** (ousia), o ser individual concreto, como um cavalo ou uma pessoa. Cada substância é composta de **matéria** (aquilo de que é feita) e **forma** (a essência, o que ela é). Uma estátua é feita de bronze (matéria) e tem a forma do deus que representa. Em um ser vivo, a forma é a **alma**, que é o princípio de organização e de vida do corpo, e não uma entidade separada, como em Platão.',
  'Para explicar a mudança, problema deixado pelos pré-socráticos, Aristóteles criou os conceitos de **potência** e **ato**. A **potência** é a capacidade de vir a ser algo, e o **ato** é a realização dessa capacidade. A semente é uma árvore em potência, e a árvore é a semente em ato. A mudança é a passagem da potência ao ato, e permite conciliar o ser e o devir: algo permanece (a substância), enquanto muda (o que é em potência). Esse esquema serve para explicar o movimento, o crescimento e a atividade humana. O **ato** é anterior e superior à potência, pois nada passa da potência ao ato sem algo que já esteja em ato.',
  'Aristóteles propôs a doutrina das **quatro causas** para explicar qualquer coisa: a **causa material** (de que é feita), a **formal** (o que é, sua essência), a **eficiente** (o que a produziu) e a **final** (para que serve, a finalidade). A causa final é fundamental: a natureza é **teleológica**, ou seja, tudo tende a um fim. No topo, ele colocou o **Primeiro Motor Imóvel**, um ser puro em ato, sem matéria, que move todas as coisas como objeto de desejo e de amor, e é "pensamento do pensamento". Essa ideia influenciou a teologia medieval, que a identificou com Deus.'] },
 { h:'Lógica e teoria do conhecimento', p:[
  'Aristóteles é o fundador da **lógica** como disciplina: o estudo das formas do raciocínio válido. Seu principal conceito é o **silogismo**, um argumento com duas premissas e uma conclusão, em que a conclusão decorre necessariamente das premissas. O exemplo clássico: "Todo homem é mortal (premissa maior); Sócrates é homem (premissa menor); logo, Sócrates é mortal (conclusão)". A lógica aristotélica dominou o pensamento ocidental por mais de dois mil anos, e estabelece princípios básicos: o da **identidade** (A é A), o da **não contradição** (algo não pode ser e não ser ao mesmo tempo, no mesmo sentido) e o do **terceiro excluído** (ou A ou não A).',
  'Quanto ao conhecimento, ele reconhece diferentes graus: a **sensação**, que capta as qualidades das coisas particulares; a **memória** e a **experiência**; a **arte** (técnica), que conhece as causas do fazer; e a **ciência** (episteme), o conhecimento universal e necessário, das causas e princípios. O conhecimento científico procede por **indução** (do particular ao universal) e por **dedução** (do universal ao particular). A intuição intelectual (nous) apreende os princípios. Essa posição, que parte da experiência sensível para chegar ao universal, serviu de base ao empirismo posteriormente, e à ciência da natureza, que ele ajudou a fundar, em especial na biologia, com a classificação dos seres vivos.',
  'Em oposição aos sofistas e ao relativismo, Aristóteles defendia que a **verdade** é a correspondência entre o pensamento e a realidade: "dizer do que é que é, e do que não é que não é, é verdadeiro". A retórica, que ele estudou, é útil e legítima, desde que se apoie em argumentos sólidos e em ética. Por isso, na Retórica, ele analisa os meios de persuasão: o **ethos** (credibilidade do orador), o **pathos** (emoção da audiência) e o **logos** (a argumentação racional). Essas categorias são muito usadas para analisar discursos, textos publicitários e redações, e frequentemente aparecem no ENEM.'] },
 { h:'Ética e política aristotélicas', p:[
  'Na **Ética a Nicômaco**, Aristóteles propõe que todas as ações humanas visam a um fim, e que o fim último é a **felicidade** (eudaimonia), entendida não como prazer passageiro ou riqueza, mas como uma **vida boa**, realizada de acordo com a **virtude** (arete). A função própria do ser humano é a **razão**, e a felicidade consiste em exercer bem essa atividade. As virtudes são **intelectuais** (sabedoria, prudência), adquiridas pelo ensino, e **morais** (coragem, temperança, justiça, generosidade), adquiridas pelo **hábito**: tornamo-nos justos praticando atos justos. A virtude, portanto, é uma disposição estável, desenvolvida pela prática e pela educação.',
  'A virtude moral é um **meio-termo** (mesotes) entre dois extremos viciosos, o excesso e a falta, determinado pela razão e pela prudência (phronesis), e variável conforme as circunstâncias. A coragem é o meio-termo entre a covardia (falta) e a temeridade (excesso); a generosidade, entre a avareza e a prodigalidade. Não é uma média matemática, mas o ponto adequado em cada situação. Aristóteles também destaca a **justiça**, que pode ser **distributiva** (dar a cada um o que lhe cabe, segundo o mérito) e **corretiva** (reparar danos), e a **amizade** (philia), que considera essencial à vida feliz.',
  'Na **Política**, Aristóteles afirma que o ser humano é, por natureza, um **animal político** (zoon politikon): só realiza sua natureza vivendo em comunidade, na pólis, que existe para possibilitar a "vida boa". Ele classifica as formas de governo pelo número de governantes e pelo fim: as **retas** (monarquia, aristocracia e politeia), que visam ao bem comum, e as **degeneradas** (tirania, oligarquia e democracia, no sentido de governo da massa em seu próprio interesse). Defendeu a **politeia**, um governo misto, em que a classe média tem peso, como mais estável. Sua visão contém limitações de seu tempo: aceitava a escravidão e a inferioridade das mulheres, o que deve ser analisado criticamente.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Aristóteles aparece no ENEM em questões que apresentam trechos da Ética a Nicômaco ou da Política e pedem a identificação de conceitos, como o de felicidade (eudaimonia), de virtude como hábito e meio-termo, do ser humano como "animal político", ou da relação entre ética e política. Também pode ser cobrada a comparação com Platão (empirismo e idealismo, forma na coisa e forma separada), a lógica e o silogismo, ou as categorias da retórica (ethos, pathos e logos), usadas na análise de discursos.',
  'Pontos de atenção: a felicidade é o fim da vida humana e consiste na atividade segundo a virtude; a virtude moral se adquire pelo hábito e é um meio-termo entre extremos; o homem é um animal político e a pólis é natural; a forma está na coisa, e não em outro mundo; potência e ato explicam a mudança; o silogismo é um argumento dedutivo; e o conhecimento parte da experiência. Evite atribuir a Aristóteles a teoria das ideias de Platão, ou o contrário. Em questões de ética, pense: a virtude é hábito, e não um sentimento isolado, e o meio-termo depende da prudência.',
  'Para revisar, faça um quadro comparando Platão e Aristóteles (conhecimento, realidade, política e alma) e um esquema da ética aristotélica (felicidade, virtudes, meio-termo, hábito, prudência). Treine o silogismo com exemplos do cotidiano e identifique ethos, pathos e logos em um discurso. Esse tema encerra o período clássico da Filosofia grega, e abre caminho para as escolas helenísticas, que, em um mundo de incertezas, após a morte de Alexandre, voltaram a Filosofia para a busca da tranquilidade e da felicidade individual.'] }
]}
];
