/* Filosofia: textos corridos, temas 23 a 25 */
module.exports = [
{ t:'Estética e arte', txt:[
 { h:'O que é Estética e a questão do belo', p:[
  'A **Estética** é a área da Filosofia que reflete sobre a **arte**, o **belo** e a **experiência sensível**. A palavra vem do grego aisthesis, que significa "sensação", "percepção". Ela surgiu como disciplina autônoma no século XVIII, com **Alexander Baumgarten**, mas a reflexão sobre a arte e o belo é muito mais antiga. Seus problemas incluem: o que é o belo? A beleza é objetiva (está nas coisas) ou subjetiva (está no olhar de quem vê)? O que é arte? Qual é a função da arte? Existem critérios para julgar uma obra? Qual a relação entre a arte, a verdade, a moral e a sociedade?',
  'Na Antiguidade, a beleza era associada à **harmonia**, à **proporção** e à ordem. Para **Platão**, o belo é uma ideia (o Belo em si), de que as coisas belas participam, e a arte é **imitação** (mimese) do mundo sensível, que já é cópia das ideias, e por isso está "duas vezes afastada da verdade". Por isso, desconfiava dos poetas e dos artistas, capazes de despertar paixões e de enganar. **Aristóteles**, na **Poética**, valoriza a arte: a tragédia, ao imitar ações humanas, gera **catarse**, a purificação das emoções de piedade e de temor, e tem valor educativo. A imitação não é cópia, mas representação do possível e do universal.',
  'Na Idade Média, a beleza foi vinculada a Deus, e a arte, à religião, com os temas sacros e a arquitetura das catedrais. No **Renascimento**, ressurgiu o interesse pelo ser humano e pela natureza, com a perspectiva, a anatomia e a busca de proporções (Leonardo, Michelangelo). Na Filosofia moderna, discutiu-se se o belo é uma qualidade das coisas ou uma experiência do sujeito. **Hume** afirmou que "a beleza não é uma qualidade nas próprias coisas: existe somente na mente que as contempla". Essa discussão entre o **objetivismo** e o **subjetivismo** estético é fundamental para entender as teorias seguintes.'] },
 { h:'Kant e o juízo de gosto; Hegel e o belo artístico', p:[
  '**Kant**, na **Crítica do Juízo** (1790), propôs uma teoria influente. O **juízo estético** ("isto é belo") tem características paradoxais: é **subjetivo**, pois se baseia no sentimento de prazer do sujeito, e não em um conceito ou em uma regra; mas pretende ser **universal**, pois quem diz que algo é belo espera a concordância de todos. Para isso, o prazer estético deve ser **desinteressado**: não depende do desejo de possuir o objeto, de sua utilidade ou de seu valor moral, mas é uma contemplação livre. O belo provoca um **jogo livre** entre a imaginação e o entendimento, que produz prazer sem finalidade prática, uma "finalidade sem fim".',
  'Kant também descreveu o **sublime**, a experiência diante do que é imenso ou poderoso (uma tempestade, o oceano, o céu estrelado), que causa ao mesmo tempo espanto e prazer, e nos faz sentir a grandeza da nossa razão. Quanto à arte, o **gênio** é o talento natural que cria obras originais e exemplares, sem seguir regras. **Hegel**, em suas **Lições de Estética**, defende que o **belo artístico** é superior ao belo natural, por ser produto do espírito: a arte é a manifestação sensível da **Ideia**, e passa por formas históricas (simbólica, clássica e romântica). Para Hegel, a arte expressa a visão de mundo de cada época, e tem uma função ao lado da religião e da Filosofia.',
  '**Nietzsche**, em O Nascimento da Tragédia, valoriza a arte como afirmação da vida, e distingue o **apolíneo** (ordem, forma, medida) e o **dionisíaco** (êxtase, desmedida, música). Para ele, "só como fenômeno estético a existência e o mundo estão eternamente justificados". Essas visões mostram que a arte pode ser entendida como prazer desinteressado (Kant), expressão do espírito de uma época (Hegel) ou afirmação da vida (Nietzsche). A reflexão estética também interroga o **gosto**: ele é puramente pessoal ("gosto não se discute") ou há critérios (formação, comparação, experiência) que permitem avaliar e dialogar sobre as obras?'] },
 { h:'Arte, indústria cultural e arte contemporânea', p:[
  'No século XX, a arte passou por grandes transformações. As **vanguardas** (cubismo, futurismo, dadaísmo, surrealismo, expressionismo) romperam com a representação realista e com as tradições, e experimentaram novas linguagens. **Marcel Duchamp**, com seus **ready-mades**, como o urinol assinado "Fonte" (1917), provocou a pergunta: o que faz de um objeto uma obra de arte? A arte contemporânea ampliou a noção de arte, incluindo instalações, performances, arte conceitual e arte urbana, e valoriza a ideia, a crítica e a participação do público. A questão "o que é arte?" tornou-se aberta: para alguns, é o que o **contexto institucional** (museus, galerias, críticos) reconhece como arte (Arthur Danto, George Dickie).',
  '**Walter Benjamin**, em **A Obra de Arte na Era de sua Reprodutibilidade Técnica** (1936), argumentou que a fotografia e o cinema alteraram a arte: a obra original tem uma **aura** (autenticidade, unicidade, o "aqui e agora"), que se perde com a reprodução em massa. Por um lado, isso destrói o caráter ritual e distante da arte, e, por outro, **democratiza** o acesso e abre possibilidades políticas. **Adorno** e **Horkheimer**, por sua vez, criticaram a **indústria cultural**, que transforma a arte em mercadoria padronizada, voltada ao entretenimento e ao consumo, e esvazia seu potencial crítico. Para eles, a verdadeira arte, autônoma e difícil, resiste e revela as contradições da sociedade.',
  'Hoje, as **tecnologias digitais**, a internet, as redes sociais, a inteligência artificial e o streaming transformam a produção, a circulação e o consumo da arte. Surgem questões sobre a **autoria** (uma obra gerada por IA tem autor?), o **direito autoral**, o papel dos algoritmos na formação do gosto, a cultura de massa e a cultura **popular**, e a **valorização** de manifestações antes marginalizadas, como o funk, o hip hop, o grafite, as artes indígenas e afro-brasileiras. Essas discussões mostram que a Estética está ligada a questões políticas e sociais: quem decide o que é arte e o que merece ser valorizado? Quem tem acesso à cultura?'] },
 { h:'Funções da arte, arte no Brasil e fruição estética', p:[
  'A arte cumpre diversas **funções**: **estética** (proporcionar prazer e contemplação), **expressiva** (manifestar emoções e ideias), **social** (criar identidade, memória e coesão), **política** (denunciar injustiças, questionar o poder), **educativa**, **religiosa**, **comunicativa** e **terapêutica**. A arte pode alegrar, comover, incomodar e transformar. No contexto brasileiro, o **Modernismo** de 1922 procurou uma arte nacional, valorizando a cultura popular e indígena (**Antropofagia**, de Oswald de Andrade, que propunha "deglutir" as influências estrangeiras e produzir algo original). A música popular (samba, bossa nova, tropicália), o cinema novo, o teatro e a literatura expressam temas sociais e políticos.',
  'A **fruição estética** é a capacidade de apreciar a arte, e se desenvolve com a educação, a experiência e a abertura. Ela envolve a **percepção atenta**, a imaginação, a interpretação e o diálogo com a obra. A **educação do olhar** e do gosto é parte da formação cidadã, e o acesso à cultura é um **direito**, previsto na Constituição. Políticas públicas, como museus, bibliotecas, teatros, festivais e leis de incentivo, buscam democratizar esse acesso. O **patrimônio cultural**, material e imaterial (festas, saberes, ofícios), é protegido pelo IPHAN, e sua preservação envolve a memória e a identidade coletiva.',
  'Em síntese, a Estética mostra que a arte não é apenas decoração ou entretenimento, mas uma forma de **conhecimento** e de **experiência** do mundo, que nos permite perceber, sentir e pensar de outra maneira. A pergunta "o que é belo?" não tem resposta única, e depende de contextos históricos, culturais e individuais, mas isso não impede o diálogo e a crítica. Para o ENEM, é importante saber relacionar os conceitos estéticos às obras e aos movimentos, e à vida social, identificando como a arte reflete e questiona seu tempo, e como o consumo cultural é influenciado pela indústria e pela tecnologia.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Estética aparece no ENEM em questões com trechos de Kant (o juízo de gosto), de Benjamin (a aura e a reprodutibilidade técnica), de Adorno (a indústria cultural) ou de Nietzsche, e pedem a identificação de conceitos, a relação entre arte e sociedade, e a análise de obras e de manifestações culturais atuais. Também são comuns as questões que tratam da democratização da arte pela tecnologia, da arte urbana, do patrimônio cultural, do direito à cultura e da relação entre arte e política. Esse tema se articula com a área de Linguagens e com a Sociologia.',
  'Pontos de atenção: a Estética estuda a arte e a experiência do belo; para Platão, a arte é imitação; para Aristóteles, tem função catártica; para Kant, o juízo de gosto é subjetivo e universal, desinteressado; para Benjamin, a reprodução técnica destrói a aura e democratiza a arte; para Adorno, a indústria cultural padroniza a cultura; a arte contemporânea questiona o que é arte. Evite reduzir a arte a "gosto pessoal" sem análise, e lembre que a arte pode ter função crítica, e não apenas decorativa. Em obras e imagens, procure o contexto, os procedimentos e a mensagem.',
  'Para revisar, monte uma linha com os autores (Platão, Aristóteles, Kant, Hegel, Nietzsche, Benjamin e Adorno), a ideia de cada um sobre a arte e um exemplo atual. Reflita sobre sua experiência: que obra o emocionou? Que critérios usa para apreciá-la? Esse tema complementa a Teoria do Conhecimento (a arte como forma de conhecer) e a Ética (a relação entre a arte e os valores), e prepara os dois últimos temas: a Filosofia e a tecnologia, e a lógica e argumentação, instrumentos essenciais do pensamento crítico.'] }
]},
{ t:'Filosofia e tecnologia', txt:[
 { h:'O que é técnica e tecnologia e como a Filosofia as analisa', p:[
  'A **técnica** é o conjunto de procedimentos e de instrumentos pelos quais os seres humanos transformam a natureza e resolvem problemas práticos, e acompanha a humanidade desde o início: o fogo, a roda, a escrita, a agricultura. A **tecnologia** designa a técnica associada ao conhecimento científico, o saber aplicado à produção de instrumentos, de processos e de sistemas, como se desenvolveu a partir da Revolução Industrial. A **Filosofia da técnica** pergunta: o que é a técnica? Ela é neutra, um mero instrumento, ou transforma o ser humano e a sociedade? Quais são seus riscos e suas promessas? Como a tecnologia se relaciona com a ética e a política?',
  'Há duas visões extremas. O **instrumentalismo** (ou neutralidade da técnica) afirma que a tecnologia é um simples meio, e que o que importa é o uso que se faz dela: uma faca serve para cortar pão ou para ferir. O **determinismo tecnológico** sustenta que a tecnologia tem uma lógica própria, que molda a sociedade, independentemente das vontades. Entre as duas, muitos filósofos defendem que a tecnologia **não é neutra**: ela incorpora valores e escolhas, abre algumas possibilidades e fecha outras, e transforma a maneira como percebemos e agimos, como na célebre ideia de Marshall McLuhan de que "o meio é a mensagem".',
  'Desde a Antiguidade, a técnica foi objeto de reflexão. No mito de **Prometeu**, que rouba o fogo dos deuses para entregá-lo aos humanos, a técnica é um dom, mas também uma transgressão, que traz castigo. Para **Aristóteles**, a técnica (techne) é um saber produtivo, distinto da ciência teórica e da ação ética e política. A **modernidade** trouxe a ideia de **domínio da natureza**: Bacon afirmou "saber é poder", e Descartes propôs tornar os humanos "senhores e possuidores da natureza". A confiança no progresso técnico como caminho do progresso humano foi central, mas passou a ser questionada, sobretudo no século XX.'] },
 { h:'Críticas à técnica: Heidegger, Frankfurt e Hans Jonas', p:[
  '**Martin Heidegger**, em **A Questão da Técnica** (1953), argumenta que a essência da técnica moderna não é apenas instrumental: é uma forma de **desvelamento** do mundo, que ele chama de "**armação**" (Gestell), em que tudo, a natureza e os próprios humanos, é visto como **reserva disponível** (Bestand), um recurso a ser explorado e otimizado. Um rio, por exemplo, deixa de ser paisagem e passa a ser fonte de energia, e uma pessoa pode ser reduzida a "recurso humano". O perigo não está nas máquinas em si, mas nessa forma de ver, que esquece outras possibilidades de relação com o ser.',
  'A **Escola de Frankfurt** criticou a **razão instrumental** e a **racionalização** técnica da sociedade. Para Adorno e Horkheimer, o domínio da natureza se converte em domínio do homem pelo homem. **Marcuse**, em **O Homem Unidimensional**, mostra que a tecnologia se tornou uma forma de controle social, que integra os indivíduos ao sistema e eliminam a oposição. **Hannah Arendt** advertiu para os riscos de uma sociedade em que o pensamento seria substituído por cálculos técnicos, e que o trabalho automatizado liberaria os humanos sem que soubessem o que fazer da liberdade. **Günther Anders** falou do "desnível prometeico": os humanos produzem mais do que conseguem imaginar e responsabilizar.',
  '**Hans Jonas** (1903-1993), em **O Princípio Responsabilidade** (1979), considera que o poder da tecnologia, capaz de alterar a natureza e de ameaçar a sobrevivência da humanidade (armas nucleares, devastação ambiental, engenharia genética), exige uma **nova ética**. As éticas tradicionais, centradas nas relações imediatas entre pessoas, não bastam. Propõe um imperativo: "age de tal modo que os efeitos de tua ação sejam compatíveis com a permanência de uma vida humana autêntica sobre a Terra". Seu **princípio da precaução** recomenda dar prioridade ao pior cenário, quando há risco grave e irreversível. Essa ética da **responsabilidade** pelo futuro é base do debate ambiental e bioético.'] },
 { h:'Tecnologia, sociedade e trabalho', p:[
  'A tecnologia transformou profundamente o **trabalho**. A Revolução Industrial substituiu o trabalho artesanal pelas máquinas, e criou o operário assalariado, com disciplina de fábrica (Marx, Foucault). A **automação**, a robótica e a **inteligência artificial** levantam hoje a questão do **desemprego tecnológico**: quais funções serão substituídas, que novas surgirão, e quem se beneficiará? A "**uberização**" e o trabalho por plataformas trazem flexibilidade, mas também precariedade e perda de direitos. Há debates sobre a **redução da jornada**, a **renda básica** e a educação para as novas competências, e sobre a distribuição dos ganhos de produtividade.',
  'A tecnologia também modifica as **relações sociais** e a **percepção**. A **internet** e as redes sociais ampliaram o acesso à informação e à comunicação, e permitiram novas formas de organização e de participação política. Mas trazem problemas: a **desinformação**, a **polarização**, os "filtros-bolha" criados por algoritmos, o excesso de exposição, a dependência de telas, a **vigilância** e o uso de dados pessoais. Foucault e o conceito de panóptico são retomados para analisar a **sociedade de vigilância**. O filósofo **Byung-Chul Han** fala de uma "**sociedade do desempenho e do cansaço**", em que o excesso de estímulos e a autoexploração produzem esgotamento.',
  'A **inteligência artificial** (IA) suscita questões inéditas. Os sistemas aprendem a partir de dados, e podem reproduzir **vieses** e preconceitos (como nos algoritmos de reconhecimento facial e de seleção de candidatos). Há dúvidas sobre a **responsabilidade** pelas decisões automáticas, a **transparência** dos algoritmos, a **privacidade**, o **impacto no emprego** e a possibilidade de uma "inteligência" superior à humana. Perguntas filosóficas incluem se uma máquina pode pensar (o teste de Turing e o argumento do "quarto chinês", de Searle), ter consciência ou direitos. No Brasil, a **LGPD** (Lei Geral de Proteção de Dados) busca proteger a privacidade e regular o uso de dados.'] },
 { h:'Bioética, ambiente e responsabilidade', p:[
  'A **biotecnologia** e as ciências da vida colocam dilemas éticos novos. A **engenharia genética**, a edição de genes (CRISPR), a clonagem, as células-tronco, a reprodução assistida e os transplantes levantam questões sobre os limites da intervenção na vida humana: até onde podemos "projetar" seres humanos? Quem decide? A **bioética**, área que une Filosofia, Medicina e Direito, propõe princípios como a **autonomia** (respeito à decisão do paciente), a **beneficência** (fazer o bem), a **não maleficência** (não causar dano) e a **justiça** (distribuição equitativa de recursos). Os comitês de ética em pesquisa protegem as pessoas envolvidas em estudos científicos.',
  'A relação entre tecnologia e **meio ambiente** também é central. A mesma capacidade técnica que permitiu o conforto e a produção em larga escala gerou poluição, mudanças climáticas, perda de biodiversidade e esgotamento de recursos. A reflexão filosófica, de Hans Jonas e da **ética ambiental**, destaca a **responsabilidade** com as gerações futuras e com os demais seres vivos, e defende o **desenvolvimento sustentável** e o princípio da precaução. Questões como a energia nuclear, os transgênicos, os agrotóxicos e a geoengenharia exigem avaliações que considerem os riscos, as incertezas e a participação da sociedade nas decisões.',
  'Em síntese, a Filosofia convida a **não aceitar a tecnologia como destino nem rejeitá-la** por completo, mas a **pensar criticamente** sobre seus fins, seus efeitos e quem a controla. O progresso técnico não equivale automaticamente ao progresso humano e moral: depende de escolhas éticas e políticas. Uma sociedade democrática deve debater publicamente os rumos da tecnologia, com base em informações e em valores, incluindo a ciência, a ética, a participação e a justiça. Para o estudante, desenvolver uma postura crítica diante das tecnologias, de seus usos e de seus impactos é uma competência para a vida e para a redação.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Filosofia e tecnologia aparecem no ENEM em questões que apresentam textos sobre a técnica, o trabalho, a vigilância, as redes sociais, a inteligência artificial, a bioética e o meio ambiente, com autores como Heidegger, Marcuse, Adorno, Foucault, Hans Jonas, Han ou textos de jornais e de revistas, e pedem a identificação de ideias como a neutralidade ou não da tecnologia, a razão instrumental, a responsabilidade, a precaução e os impactos sociais. A habilidade é relacionar conceitos filosóficos a fenômenos tecnológicos atuais.',
  'Pontos de atenção: a técnica é anterior à ciência moderna, e a tecnologia une técnica e ciência; a tecnologia não é neutra, pois incorpora valores e transforma a sociedade; a razão instrumental, de Frankfurt, enfatiza os meios, e não os fins; Heidegger vê na técnica moderna uma forma de ver tudo como recurso; Jonas propõe o princípio da responsabilidade e da precaução; a bioética se orienta por princípios, como autonomia e justiça; e o uso de dados exige proteção da privacidade. Evite posições extremas: nem tecnofobia nem tecnofilia, e sim análise crítica.',
  'Para revisar, escreva cada conceito (instrumentalismo, determinismo, razão instrumental, armação, princípio da responsabilidade, bioética, vigilância) com um exemplo atual (algoritmos, IA, redes, manipulação genética, clima). Conecte o tema a Marx e à Escola de Frankfurt (trabalho e dominação), a Foucault (vigilância) e à Ética (responsabilidade), e prepare-se para o último tema da matéria, lógica e argumentação, que fornece as ferramentas para analisar e construir argumentos, indispensáveis na prova e na redação.'] }
]},
{ t:'Lógica e argumentação', txt:[
 { h:'O que é lógica e o que é um argumento', p:[
  'A **lógica** é a disciplina que estuda as **formas do raciocínio correto**, ou seja, as regras que permitem passar de certas afirmações a outras de modo válido, sem contradição. Foi sistematizada por **Aristóteles**, no **Órganon**, que a considerava o instrumento (órganon) de todo saber, e foi desenvolvida, ao longo da história, pelos estoicos, pelos escolásticos e, a partir do século XIX, pela lógica matemática (Frege, Russell). A lógica não trata de que algo é verdadeiro no mundo, mas de **como** se pode concluir corretamente a partir de certas premissas. Seu estudo ajuda a pensar com clareza, a argumentar e a detectar erros.',
  'A unidade básica da lógica é o **argumento**: um conjunto de afirmações, em que uma (a **conclusão**) é apresentada como decorrente das outras (as **premissas**). Por exemplo: "Todos os seres humanos são mortais (premissa 1); Sócrates é um ser humano (premissa 2); logo, Sócrates é mortal (conclusão)". Argumentar é apresentar razões que sustentam uma tese. Diferencia-se de **afirmar** (apenas dizer algo), de **explicar** (esclarecer por que algo ocorre) e de **ordenar**. Reconhecer a estrutura de um argumento, identificando a conclusão e as premissas, é a primeira habilidade, em textos filosóficos, em redações e no cotidiano.',
  'Os argumentos podem ser **dedutivos** ou **indutivos**. No **dedutivo**, a conclusão decorre **necessariamente** das premissas: se elas forem verdadeiras, a conclusão também será. É o caso do silogismo acima. No **indutivo**, as premissas oferecem **apoio provável** à conclusão, que vai além do que elas dizem: "Observei mil corvos e todos eram pretos; logo, todos os corvos são pretos". A conclusão indutiva é provável, mas pode ser falsa, se aparecer um corvo branco. A **analogia** e a **abdução** (inferência da melhor explicação) são outras formas. A ciência combina os diferentes tipos de raciocínio.'] },
 { h:'Validade, verdade, solidez e os princípios lógicos', p:[
  'É essencial distinguir **validade** e **verdade**. Um argumento dedutivo é **válido** quando a conclusão decorre necessariamente das premissas, ou seja, não é possível que as premissas sejam verdadeiras e a conclusão, falsa. Isso depende da **forma** do argumento, e não do conteúdo. Por exemplo: "Todos os peixes voam; as baleias são peixes; logo, as baleias voam" é válido (a conclusão segue das premissas), mas as premissas são falsas. Um argumento é **sólido** (ou correto) quando é válido e tem **premissas verdadeiras**. Assim, um argumento pode ser válido e não sólido, mas, se é sólido, a conclusão é verdadeira.',
  'A lógica aristotélica se baseia em alguns **princípios fundamentais**: o da **identidade** (todo ser é idêntico a si mesmo: A é A), o da **não contradição** (uma proposição não pode ser verdadeira e falsa ao mesmo tempo e no mesmo sentido) e o do **terceiro excluído** (uma proposição é verdadeira ou falsa, não existe uma terceira possibilidade). O **silogismo** é a forma típica do raciocínio dedutivo, com duas premissas e uma conclusão, e envolve termos (maior, menor e médio) e proposições universais ou particulares, afirmativas ou negativas. Há regras para determinar se um silogismo é válido, e as figuras e modos que ele pode assumir.',
  'A **lógica proposicional** (ou sentencial), desenvolvida no século XIX e XX, estuda os argumentos a partir de **proposições** e dos conectivos que as ligam: a **negação** (não), a **conjunção** (e), a **disjunção** (ou), a **condicional** (se..., então) e a **bicondicional** (se, e somente se). Uma forma válida muito usada é o **modus ponens**: "Se P, então Q; P; logo, Q" (por exemplo, "se chove, a rua molha; está chovendo; logo, a rua molha"). Outra é o **modus tollens**: "Se P, então Q; não Q; logo, não P". Já a falácia da "afirmação do consequente" ("se P, então Q; Q; logo P") é um erro comum. As tabelas-verdade ajudam a verificar a validade.'] },
 { h:'Falácias e erros de argumentação', p:[
  'As **falácias** são argumentos que parecem válidos, mas não são, e podem ser **formais** (erro na estrutura lógica) ou **informais** (erro de conteúdo, de linguagem ou de contexto). Reconhecê-las é fundamental no debate, na análise de discursos e na avaliação de textos. As falácias informais mais comuns incluem: o **ad hominem**, que ataca a pessoa que argumenta, e não seus argumentos ("não devemos ouvir o que ele diz, porque é um fracassado"); o **apelo à autoridade** (afirmar que algo é verdadeiro só porque uma autoridade disse, sem relação com sua especialidade); o **apelo à maioria** ou à popularidade ("todo mundo faz, logo está certo"); e o **apelo à emoção**, que substitui as razões por piedade, medo ou orgulho.',
  'Outras falácias frequentes são: o **espantalho** (distorcer a posição do adversário para atacá-la mais facilmente); a **generalização apressada** (tirar uma conclusão geral de poucos casos: "dois jovens pegaram o celular no ônibus; logo, jovens são distraídos"); a **falsa causa** ("depois disso, logo por causa disso", confundindo correlação e causalidade); a **falsa dicotomia** (apresentar apenas duas opções, quando há mais: "ou você está conosco, ou contra nós"); a **petição de princípio** (o argumento circular, que pressupõe a conclusão nas premissas); a **ladeira escorregadia** (alegar, sem provas, que um passo levará a uma sequência de desastres); e o **argumento do desconhecido** ("ninguém provou que não existe, logo existe").',
  'O **sofisma** é a falácia usada com a intenção de enganar, e o **paralogismo**, aquela cometida sem a intenção. A retórica pode ser usada para persuadir por argumentos sólidos ou por falácias. Aristóteles, na **Retórica**, distingue três modos de persuasão: o **ethos** (a credibilidade de quem fala), o **pathos** (a emoção despertada no público) e o **logos** (a argumentação racional). Um bom argumento combina esses recursos, mas se apoia no logos. A análise de discursos políticos, de anúncios publicitários, de redes sociais e de textos opinativos exige atenção às falácias e aos recursos persuasivos.'] },
 { h:'Como construir um bom argumento e uma boa dissertação', p:[
  'A **argumentação** é a arte de apresentar razões para defender uma tese e convencer, de forma racional, outras pessoas. Um bom argumento tem: uma **tese** clara (a posição defendida); **premissas** relevantes, verdadeiras ou plausíveis; uma **estrutura lógica** válida; e atenção a **objeções** e **contra-argumentos**, que devem ser considerados e respondidos. A argumentação envolve também a escolha de **exemplos**, de **dados** e de **citações** pertinentes, e a clareza da linguagem. Em um debate, o objetivo não é "vencer", mas buscar a verdade ou a melhor solução, em um diálogo respeitoso e aberto à correção, como no modelo socrático.',
  'Na **redação do ENEM**, a argumentação é fundamental. O texto dissertativo-argumentativo apresenta uma **tese** na introdução, **desenvolve** argumentos nos parágrafos seguintes, apoiados em **repertório sociocultural** (conhecimentos históricos, filosóficos, sociológicos, literários ou científicos) e conclui com uma **proposta de intervenção**, que decorre da argumentação. A coesão e a coerência garantem o encadeamento das ideias. Evitar falácias, como generalizações e apelos emocionais sem fundamento, melhora a qualidade do texto. A Filosofia fornece um repertório rico: citar Platão, Kant, Arendt ou Foucault, de forma pertinente, pode fortalecer a argumentação.',
  'No dia a dia, a lógica e a argumentação são ferramentas para **avaliar informações**, em um ambiente de excesso de dados e de desinformação. Perguntas úteis: qual é a tese? Quais são as razões? As premissas são verdadeiras? A conclusão decorre delas? Há falácias? Existem outras explicações possíveis? A fonte é confiável? Quais evidências existem? Essas perguntas ajudam a combater as **fake news**, a manipulação e o fanatismo, e a fortalecer a democracia, que depende de cidadãos capazes de debater com razões. A **ética do debate** envolve ouvir, reconhecer bons argumentos do outro e rever suas posições.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A lógica e a argumentação aparecem no ENEM de forma ampla, em todas as áreas e na redação. Em Filosofia, aparecem em questões que pedem a identificação da tese e dos argumentos de um texto, a validade de um raciocínio, o reconhecimento de falácias (ad hominem, apelo à autoridade, generalização apressada, falsa causa), a estrutura de um silogismo ou de uma inferência condicional (modus ponens), e a análise de recursos persuasivos (ethos, pathos e logos), em textos publicitários, políticos e jornalísticos. Também podem aparecer questões de raciocínio lógico em Matemática.',
  'Pontos de atenção: a validade depende da forma, e a verdade, do conteúdo; um argumento válido pode ter conclusão falsa, se uma premissa for falsa; o argumento dedutivo garante a conclusão, e o indutivo a torna provável; as falácias parecem argumentos, mas não são; o ad hominem ataca a pessoa, e o espantalho distorce a posição do outro; a falsa causa confunde correlação e causalidade; ethos, pathos e logos são modos de persuasão. Ao ler uma questão, identifique primeiro a conclusão e as premissas, e verifique se a conclusão decorre delas. Cuidado com alternativas que apelam ao senso comum.',
  'Para revisar, treine com três exercícios: identificar tese e argumentos em um editorial; reconhecer a falácia em frases do cotidiano; e construir um argumento dedutivo e outro indutivo sobre um tema à escolha. Monte uma lista das principais falácias com um exemplo cada. Com este tema, você conclui a revisão de Filosofia, que percorreu a Filosofia antiga, a medieval, a moderna e a contemporânea, e as áreas sistemáticas (ética, política, conhecimento, estética, tecnologia e lógica). Use esses conceitos como repertório, tanto para as questões de Ciências Humanas quanto para a redação.'] }
]}
];
