/* Filosofia: textos corridos, temas 1 a 3 */
module.exports = [
{ t:'O que é Filosofia', txt:[
 { h:'A origem da palavra e o espanto filosófico', p:[
  'A palavra **Filosofia** vem do grego e é formada por philos (amigo, amante) e sophia (sabedoria), significando "amor à sabedoria". Segundo a tradição, o termo foi criado por **Pitágoras**, que se recusava a ser chamado de "sábio" (sophos) e preferia se dizer "amigo da sabedoria", alguém que busca o saber, sem a pretensão de possuí-lo. Essa atitude humilde já mostra uma característica da Filosofia: ela é uma **busca**, e não um conjunto de verdades prontas. O filósofo é quem pergunta, investiga e questiona, e reconhece os limites do que sabe.',
  'Para os gregos, a Filosofia nasce do **espanto** (thaumazein), da admiração diante do mundo. Platão afirmou, no Teeteto, que "o espanto é a origem da Filosofia", e Aristóteles escreveu, na Metafísica, que os seres humanos começam a filosofar pela admiração diante das coisas, primeiro as mais simples, depois as mais complexas, como os movimentos dos astros e a origem do universo. Quem se espanta, percebe que não sabe, e é movido a procurar respostas. Essa disposição de estranhar o que parece familiar é o ponto de partida do pensamento crítico.',
  'A Filosofia surgiu na Grécia antiga, por volta do século VI a.C., nas cidades da Jônia, na Ásia Menor, como Mileto, e se desenvolveu em Atenas. Esse nascimento, a passagem do mito ao **logos** (razão, discurso racional), será estudado no próximo tema. O que importa agora é compreender que a Filosofia é uma forma de pensar que busca **explicações racionais**, fundamentadas em argumentos, para as questões mais gerais da existência, do conhecimento, da ação humana e da sociedade, e que submete suas próprias respostas a exame crítico.'] },
 { h:'Senso comum, ciência e Filosofia', p:[
  'Para entender o que é a Filosofia, vale compará-la com outras formas de saber. O **senso comum** é o conjunto de crenças, hábitos e opiniões que adquirimos no cotidiano, pela tradição, pela família e pela experiência, e que usamos sem questionar. Ele é útil para a vida prática, mas tende a ser **acrítico**, cheio de preconceitos, de generalizações e de ideias que se repetem sem exame. A Filosofia começa quando se desconfia do óbvio e se pergunta: "isso é mesmo assim? Por quê? Que razões temos para acreditar nisso?". Em suma, ela exige uma atitude de **reflexão crítica**.',
  'A **ciência** é um saber sistemático, que busca explicar os fenômenos por meio de métodos, de observação, de experimentação e de teorias, e se divide em áreas (Física, Biologia, Sociologia). A Filosofia se relaciona com ela de modos variados. Historicamente, as ciências nasceram da Filosofia e se separaram dela, à medida que ganharam método e objeto próprios. Hoje, a Filosofia continua a refletir sobre a própria ciência (filosofia da ciência, epistemologia) e sobre as implicações éticas e políticas das descobertas, como na bioética. Enquanto a ciência estuda aspectos específicos da realidade, a Filosofia pergunta pelos **fundamentos**, pelo **sentido** e pelos **pressupostos**.',
  'Outra diferença está no tipo de questão. Perguntas científicas podem ser respondidas por dados empíricos, como "qual a velocidade da luz?". Perguntas filosóficas, como "o que é a justiça?", "existe liberdade?" ou "o que é conhecer?", não se resolvem apenas com experimentos, e exigem **conceitos**, **argumentos** e **análise**. A Filosofia também se distingue da **religião**, que se baseia em dogmas e na fé, e da **arte**, que usa a sensibilidade e a imaginação. Isso não significa que esses saberes sejam incompatíveis: eles se complementam, e a Filosofia dialoga com todos eles, examinando suas pretensões de verdade.'] },
 { h:'As áreas e os problemas da Filosofia', p:[
  'Ao longo de sua história, a Filosofia se organizou em grandes áreas, que correspondem a perguntas fundamentais. A **Metafísica** (ou Ontologia) investiga a natureza da realidade e do ser: o que existe? O que é a substância? Há algo além do mundo físico? A **Epistemologia** (ou teoria do conhecimento) pergunta pelo conhecimento: o que podemos conhecer? Como sabemos que algo é verdadeiro? Qual o papel da razão e da experiência? A **Ética** estuda a ação moral: o que é o bem? Como devemos agir? O que é a liberdade e a responsabilidade? A **Política** investiga o poder, a justiça, a cidadania e as formas de governo.',
  'Outras áreas importantes são a **Lógica**, que estuda as regras do raciocínio correto e da argumentação, a **Estética**, que reflete sobre a arte, o belo e a experiência sensível, a **Filosofia da Linguagem**, a **Filosofia da Mente**, a **Filosofia da Ciência**, a **Filosofia da Religião** e a **Filosofia da História**. Essas divisões servem para organizar o estudo, mas as questões se entrelaçam: uma discussão sobre a liberdade, por exemplo, envolve ética, metafísica e política. O ENEM costuma trabalhar principalmente com a ética, a política e a teoria do conhecimento, e com a análise de textos de autores clássicos e contemporâneos.',
  'A história da Filosofia costuma ser dividida em grandes períodos: **Antiga** (Grécia e Roma, dos pré-socráticos ao helenismo), **Medieval** (a relação entre fé e razão, com Agostinho e Tomás de Aquino), **Moderna** (a partir do século XVI, com o racionalismo, o empirismo, o iluminismo e o idealismo) e **Contemporânea** (séculos XIX e XX, com Marx, Nietzsche, a fenomenologia, o existencialismo, a Escola de Frankfurt e a filosofia analítica). Cada período responde às questões de seu tempo, e dialoga com os anteriores, o que mostra que a Filosofia é uma conversa de séculos, e não um conjunto de sistemas isolados.'] },
 { h:'Para que serve a Filosofia: pensamento crítico e cidadania', p:[
  'Uma pergunta frequente é: "para que serve a Filosofia?". Ao contrário de saberes que produzem resultados práticos imediatos, a Filosofia não "serve" para fabricar objetos, e é por isso que, às vezes, é vista como inútil. Mas o seu valor está em outro lugar: ela desenvolve o **pensamento crítico**, a capacidade de analisar argumentos, de perceber contradições, de questionar preconceitos e de fundamentar as próprias opiniões. Essas habilidades são essenciais em qualquer área de atuação e na vida em sociedade. A filósofa **Marilena Chaui** afirma que a Filosofia "não serve para nada", no sentido de não ser um instrumento de dominação, mas é indispensável à liberdade.',
  'A Filosofia também é fundamental para a **cidadania** e para a **democracia**. Uma sociedade democrática exige cidadãos capazes de refletir sobre as leis, os direitos, a justiça e os valores, de dialogar e de discordar com argumentos. Sócrates, que passava a vida a questionar os atenienses na ágora, foi condenado à morte, o que mostra o incômodo que o pensamento livre provoca ao poder. Hoje, em um mundo de excesso de informações, de **fake news** e de discursos de ódio, a capacidade de avaliar fontes, de distinguir fatos de opiniões e de pensar de modo autônomo é mais necessária do que nunca.',
  'Além disso, a Filosofia ajuda cada pessoa a pensar sobre o **sentido da própria vida**: o que é uma vida boa, o que valorizamos, quais são nossos projetos e responsabilidades. Para os antigos, a Filosofia era um **modo de vida**, uma preparação para viver bem e para enfrentar a morte, o sofrimento e a incerteza. Na atualidade, ela dialoga com os dilemas da técnica, do meio ambiente, da inteligência artificial, da bioética e da desigualdade. Por isso, no ENEM, a Filosofia aparece integrada à análise de textos e de situações do mundo contemporâneo, exigindo que o estudante use conceitos filosóficos para pensar problemas reais.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em questões sobre o conceito de Filosofia, o ENEM costuma trazer um trecho de um autor, como Platão, Aristóteles, Marilena Chaui ou Kant, e pedir para identificar a concepção de Filosofia ou de pensamento crítico presente. Também podem aparecer questões que contrastam o senso comum e a reflexão filosófica, ou a Filosofia e a ciência, ou que perguntam qual atitude é característica de uma postura filosófica (questionar, argumentar, duvidar), em oposição a uma atitude dogmática ou conformista.',
  'Pontos de atenção: a palavra vem de philos e sophia; o espanto é a origem do filosofar; o filósofo busca o saber, e não afirma possuí-lo; o senso comum é acrítico e a Filosofia é crítica; a ciência estuda aspectos específicos e a Filosofia examina os fundamentos e o sentido; as grandes áreas são metafísica, epistemologia, ética, política, lógica e estética. Evite a ideia de que a Filosofia é apenas "opinião" ou "abstração sem utilidade": ela se baseia em **argumentos** e em **conceitos**, e tem papel importante na formação cidadã.',
  'Para revisar, escreva com suas palavras o que é Filosofia, a diferença para o senso comum e para a ciência, e cite um exemplo de pergunta de cada área. Treine também a leitura de pequenos textos filosóficos, procurando a tese (a ideia central) e os argumentos (as razões que a sustentam). Esse tema é a porta de entrada para os seguintes: a passagem do mito à Filosofia e os primeiros filósofos, que mostram como o pensamento racional surgiu na Grécia e como a busca por explicações naturais deu origem às ciências.'] }
]},
{ t:'Mito e Filosofia', txt:[
 { h:'O mito: explicação, tradição e função social', p:[
  'Antes da Filosofia, os gregos, como outros povos antigos, explicavam o mundo por meio de **mitos**, narrativas sobre deuses, heróis e forças sobrenaturais, que davam sentido à origem do universo, aos fenômenos naturais, à vida humana e às regras sociais. O mito (do grego mythos, "narrativa") não é uma simples mentira, como se diz no uso comum da palavra, mas uma forma de **explicação** e de **organização da experiência**. Na **Teogonia**, de **Hesíodo**, por exemplo, narra-se a origem dos deuses, a partir do Caos, e a vitória de Zeus, que estabelece a ordem do mundo. Os poemas de **Homero**, a Ilíada e a Odisseia, também formavam o ensino e a identidade dos gregos.',
  'Os mitos explicavam os **fenômenos naturais** pela ação dos deuses: o raio era a arma de Zeus, o mar era governado por Poseidon, e as estações do ano, pelo ciclo de Deméter e Perséfone. Davam sentido também à **vida social**, justificando as instituições, as hierarquias e os costumes, e orientavam a **conduta moral**, ao mostrar os destinos de quem desrespeitava os deuses (a hybris, o excesso). Eram transmitidos oralmente, de geração em geração, por poetas e rapsodos, e tinham uma função **religiosa** e **comunitária**: reforçavam a coesão do grupo, e conferiam segurança diante do desconhecido, do medo e da morte.',
  'Uma característica do pensamento mítico é que ele se apoia na **tradição** e na **autoridade**: a narrativa vale porque foi transmitida por ancestrais e pelos poetas inspirados pelas Musas, e não porque foi provada. Além disso, as explicações recorrem a **agentes sobrenaturais** e a vontades pessoais, que são imprevisíveis. As narrativas não precisam de coerência rigorosa, e podem ter versões diferentes, sem que isso seja um problema. Essas características contrastam com o pensamento filosófico, que exige **razões**, **coerência** e **abertura à crítica**, como veremos a seguir.'] },
 { h:'O nascimento da Filosofia: do mythos ao logos', p:[
  'A passagem do **mito** à **Filosofia** costuma ser chamada de passagem do **mythos** ao **logos**. O **logos** significa razão, discurso racional, argumento, e também proporção. A Filosofia surgiu quando alguns gregos, a partir do século VI a.C., começaram a buscar explicações para a natureza (a physis) sem recorrer à vontade dos deuses, mas a causas **naturais**, e a justificá-las com **argumentos** que podiam ser discutidos e criticados por todos. Esses primeiros pensadores, os **pré-socráticos**, procuraram o **princípio** (a arché) de todas as coisas. Tales de Mileto, por exemplo, afirmou que o princípio era a água.',
  'Vários fatores históricos ajudam a explicar esse surgimento. O **comércio marítimo** das cidades gregas, em contato com outros povos (egípcios, babilônios, fenícios), mostrou a diversidade de crenças e de costumes, e levou a questionar a validade absoluta das tradições. A invenção da **escrita alfabética** e da **moeda** estimulou a abstração e a medida. O surgimento da **pólis** e da **vida política**, com a isonomia (igualdade perante a lei) e o debate público na ágora, valorizou a **argumentação** e a persuasão, e o poder passou a se basear em razões discutidas em público, e não em segredos de sacerdotes. A Filosofia nasce, assim, ligada à **democracia** e à vida na cidade.',
  'É preciso, no entanto, evitar uma visão simplista, em que o mito seria totalmente superado pela razão. Muitos historiadores apontam que o **milagre grego** é, em parte, uma construção, pois os primeiros filósofos ainda usavam imagens e ideias míticas, e a Filosofia se desenvolveu em diálogo com a tradição e com os saberes do Oriente. A ruptura não foi súbita, e sim gradual. Mesmo assim, é inegável a novidade do **modo de pensar** que se estabeleceu: um discurso que pretende ser universal, justificado por argumentos, e aberto à crítica de qualquer pessoa, e não privilégio de uma casta de sacerdotes.'] },
 { h:'Diferenças entre mito e filosofia', p:[
  'Podemos comparar os dois modos de pensamento. O **mito** explica pela **narrativa**, e a Filosofia, pelo **argumento**. O mito se baseia na **tradição** e na **autoridade** de quem narra, e a Filosofia exige **justificativas** racionais, e se baseia no exame crítico. No mito, as causas são **sobrenaturais**, em geral ligadas à vontade dos deuses, e na Filosofia, são **naturais e racionais**, que podem ser investigadas por todos. O mito admite versões diferentes e contradições, e a Filosofia busca **coerência** e **universalidade**. O mito é aceito pela **fé** e pelo rito, e a Filosofia é submetida à **discussão** e pode ser refutada.',
  'Essas diferenças não significam que o mito seja inferior ou irracional. Ele cumpre uma função fundamental de dar **sentido** e **identidade** a uma comunidade, e é uma forma de expressão cultural valiosa, que sobrevive em religiões, em lendas e na arte, e até na política e na publicidade, com **mitos modernos** (como o do herói, do progresso e da meritocracia). A Filosofia, por sua vez, tem a tarefa de **analisar** esses mitos, de verificar suas pressuposições e de perguntar se são justificáveis. Em um sentido amplo, a atitude filosófica é uma forma de desmitificar crenças aceitas sem exame.',
  'Alguns pensadores reconhecem uma relação mais complexa. Platão, por exemplo, usava **mitos** em seus diálogos, como o da caverna e o de Er, como recursos pedagógicos e para expressar ideias que a argumentação puramente racional não alcança. O filósofo Theodor Adorno e Max Horkheimer, na **Dialética do Esclarecimento**, argumentam que o mito já é uma forma de esclarecimento, e que o esclarecimento, por sua vez, pode se converter em mito, quando a razão se torna dominação e cega à crítica. Essas reflexões ajudam a compreender que **razão e mito** se entrelaçam, e que a crítica é sempre necessária.'] },
 { h:'O legado e a atualidade da passagem do mito à razão', p:[
  'O surgimento do pensamento racional teve um enorme legado. Dele nasceram as **ciências**: a observação da natureza, a busca de leis gerais e a formulação de hipóteses, que se desenvolveram na Física, na Astronomia, na Matemática, na Medicina e em outras áreas. Nasceram também a **lógica**, a **política** como discussão pública sobre o bem comum, a **ética** como reflexão sobre a conduta, e a ideia de **educação** como formação do espírito crítico. A Filosofia grega estabeleceu os conceitos e os problemas que, durante séculos, orientaram o pensamento ocidental.',
  'A questão da relação entre **mito e razão** continua atual. Em nossa época, convivem a ciência e as narrativas míticas, religiosas e políticas, que continuam a dar sentido à vida. Surgem também as **pseudociências**, as teorias da conspiração e as **fake news**, que apelam à emoção e à crença e fogem da verificação. Aprender a distinguir um argumento fundamentado de uma narrativa sedutora é uma habilidade indispensável. A atitude filosófica, que pergunta por razões e evidências, é um antídoto contra o dogmatismo e o fanatismo, e contra a manipulação das massas.',
  'É importante, também, reconhecer a **diversidade dos saberes**. Muitas culturas, como as indígenas e as africanas, possuem mitos e sistemas de pensamento complexos, que organizam sua relação com a natureza e com a sociedade, e que não podem ser considerados "pré-filosóficos" ou inferiores, apenas por serem diferentes do modelo grego. Discussões atuais propõem uma **filosofia intercultural**, que dialogue com tradições africanas, indígenas, orientais e latino-americanas. O ENEM tem valorizado essa perspectiva, ao apresentar textos de diferentes tradições e ao pedir uma postura aberta e crítica.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O tema mito e Filosofia aparece em questões que pedem a identificação das características do pensamento mítico (explicação por forças sobrenaturais, tradição) e do filosófico (razão, argumento, crítica), a compreensão da passagem do mythos ao logos e a análise de textos de Hesíodo, de Homero ou de pré-socráticos. Também aparecem situações atuais, nas quais se pede para reconhecer crenças acríticas e mitos modernos, ou relacionar o pensamento mítico com outras formas de explicação, como a religião e a ciência.',
  'Pontos de atenção: o mito é uma narrativa que explica a origem e a ordem do mundo e não é, necessariamente, uma "mentira"; o logos significa razão e discurso; a Filosofia explica a natureza por causas naturais e por argumentos; o contexto da pólis (debate público, comércio, escrita) favoreceu a Filosofia; a passagem foi gradual; e o pensamento mítico não desapareceu. Ao analisar um texto, procure o tipo de explicação (sobrenatural ou racional) e o fundamento (tradição ou argumento). Evite concluir que o mito é "ignorância": ele tem função cultural e social.',
  'Para revisar, monte um quadro comparando mito e filosofia (forma, fundamento, causas, relação com a crítica), com exemplos. Releia o trecho da Teogonia e o de Tales e pense em como diferem na explicação do mundo. Esse tema prepara o seguinte, os pré-socráticos, os primeiros filósofos, que buscaram o princípio de todas as coisas na própria natureza e deram início à tradição racional que culminará em Sócrates, Platão e Aristóteles.'] }
]},
{ t:'Pré-socráticos', txt:[
 { h:'Quem foram os pré-socráticos e a busca pela arché', p:[
  'Os **pré-socráticos** são os primeiros filósofos gregos, que viveram entre os séculos VI e V a.C., antes de Sócrates ou contemporâneos a ele. O termo é convencional, e designa pensadores muito diferentes, que compartilham a preocupação com a **natureza** (a physis), e por isso também são chamados de **filósofos da natureza** ou naturalistas. Eles se perguntaram: de que é feito o mundo? Qual é a origem e o princípio de todas as coisas? Como se explicam as mudanças, o nascimento e a morte? O **princípio**, em grego, é a **arché**, a origem e o fundamento permanente, a partir do qual tudo se forma e ao qual tudo retorna.',
  'Suas obras se perderam quase totalmente, e conhecemos seus pensamentos por **fragmentos**, citados por autores posteriores, como Aristóteles. Ainda assim, deixaram uma contribuição fundamental: propuseram explicações **racionais** para a natureza, sem recorrer aos deuses, e por meio de argumentos sujeitos à crítica. Seu surgimento ocorreu em colônias gregas, na **Jônia** (Ásia Menor), onde estava a cidade de **Mileto**, e na Magna Grécia (sul da Itália). A região era um local de comércio e de contato com outras culturas, o que favorecia a reflexão.',
  'Costuma-se dividir os pré-socráticos em escolas, de acordo com a região e o tipo de problema. A **escola jônica** (Tales, Anaximandro e Anaximenes, de Mileto) procurou um elemento material como princípio. A **escola pitagórica** (Pitágoras) valorizou os números. A **escola eleática** (Parmênides e Zenão) discutiu o ser e a unidade. **Heráclito de Éfeso** destacou o devir e a mudança. Os **pluralistas** (Empédocles, Anaxágoras) e os **atomistas** (Leucipo e Demócrito) buscaram explicar a multiplicidade das coisas. Cada um deu uma resposta diferente à questão do princípio e da mudança.'] },
 { h:'Os filósofos de Mileto: Tales, Anaximandro e Anaximenes', p:[
  '**Tales de Mileto** (c. 624-546 a.C.) é considerado o **primeiro filósofo** da tradição ocidental. Propôs que o princípio de todas as coisas é a **água**, provavelmente por observar que a água está presente na vida, nos alimentos, nas sementes e nas mudanças de estado (líquido, sólido e gasoso). Tales também se destacou como matemático e astrônomo, e teria previsto um eclipse solar, em 585 a.C., e medido a altura das pirâmides pela sombra, o que mostra a ligação entre a Filosofia e a ciência. O mais importante é a **novidade da explicação**: ele buscou um princípio natural, observável e racional, e não mítico.',
  '**Anaximandro de Mileto** (c. 610-546 a.C.), discípulo de Tales, achava que o princípio não poderia ser um elemento específico, como a água, pois os elementos se opõem entre si (o quente e o frio, o seco e o úmido). Propôs que a arché é o **ápeiron**, o "ilimitado" ou "indeterminado", uma substância infinita, sem qualidades definidas, da qual tudo se origina e à qual tudo retorna, em um ciclo regido por uma justiça cósmica. Também desenhou um dos primeiros mapas do mundo e propôs que a Terra flutua livremente no espaço, e teria sugerido que os seres humanos descendem de outros animais, uma ideia precursora da evolução.',
  '**Anaximenes de Mileto** (c. 585-525 a.C.) propôs que o princípio é o **ar** (pneuma), infinito e em movimento. Por processos de **rarefação** (o ar se torna mais fino e quente, formando o fogo) e de **condensação** (o ar se torna mais denso e frio, formando o vento, as nuvens, a água, a terra e as pedras), o ar explicaria a diversidade dos seres. Com isso, ele introduziu um mecanismo **físico** para explicar a transformação, e não apenas um princípio. Os três pensadores de Mileto são exemplos do **pensamento naturalista**: procuraram a unidade por trás da diversidade e explicaram a mudança por processos naturais.'] },
 { h:'Pitágoras, Heráclito, Parmênides e os atomistas', p:[
  '**Pitágoras de Samos** (c. 570-495 a.C.), que fundou uma escola em Crotona, no sul da Itália, defendia que a essência de todas as coisas são os **números**. Observou que os intervalos musicais correspondem a razões numéricas simples, e concluiu que o universo é harmonia e ordem matemática. A escola pitagórica fez avanços na Matemática (o teorema de Pitágoras) e na Astronomia, e vivia em uma comunidade de caráter religioso e filosófico, com crença na transmigração das almas. A ideia de que a realidade pode ser descrita matematicamente influenciou Platão e a ciência moderna.',
  '**Heráclito de Éfeso** (c. 540-470 a.C.) é o filósofo do **devir**: tudo flui, tudo muda. Sua frase mais famosa afirma que "ninguém se banha duas vezes no mesmo rio", pois as águas e a própria pessoa mudam. Para ele, a realidade é um **conflito de opostos** (dia e noite, guerra e paz, vida e morte) que, no entanto, forma uma **harmonia**, regida pelo **logos**, a razão universal. O fogo é a arché, símbolo da transformação constante. Já **Parmênides de Eleia** (c. 515-450 a.C.) defendeu o oposto: o **ser é** e o **não ser não é**, e a verdadeira realidade é única, imutável e eterna, e a mudança é uma ilusão dos sentidos, que só a razão pode superar. Zenão de Eleia criou paradoxos para defender essa tese.',
  'A tensão entre Heráclito (mudança) e Parmênides (permanência) foi um dos grandes problemas da Filosofia antiga. Tentando conciliar as duas posições, **Empédocles** propôs quatro "raízes" (terra, água, ar e fogo), combinadas e separadas por duas forças, o **Amor** e a **Discórdia**; **Anaxágoras** falou de infinitas "sementes" ordenadas por um **intelecto** (nous); e os **atomistas**, **Leucipo** e **Demócrito** (c. 460-370 a.C.), afirmaram que o mundo é formado por **átomos** (partículas indivisíveis) e pelo **vazio**, e que os átomos, ao se combinar, formam todas as coisas. Essa teoria materialista antecipou a ideia moderna de átomo.'] },
 { h:'Legado dos pré-socráticos e a virada para o ser humano', p:[
  'Os pré-socráticos inauguraram o **pensamento racional**: procuraram explicar o mundo pela razão, com princípios naturais e discutíveis, e lançaram problemas que atravessaram toda a história da Filosofia e da ciência. Entre eles, a questão da **unidade e da multiplicidade** (como um único princípio explica a diversidade?), a do **ser e do devir** (o que permanece, e o que muda?), a da relação entre **sentidos e razão** (os sentidos nos enganam?) e a do papel da **matemática** na descrição do mundo. Esses temas foram retomados por Platão e Aristóteles, e pela ciência moderna.',
  'No século V a.C., a Filosofia passou por uma **virada**. Atenas se tornou o centro cultural, com o florescimento da democracia, e a atenção dos pensadores voltou-se do cosmos para o **ser humano** e a vida na cidade: a ética, a política, a linguagem e a educação. Os **sofistas** e **Sócrates** são os protagonistas dessa mudança, estudada no próximo tema. Por isso, a história da Filosofia grega é dividida em um **período cosmológico** (ou naturalista), dos pré-socráticos, e um **período antropológico**, a partir de Sócrates, ainda que não haja uma separação rígida.',
  'O legado dos pré-socráticos também é cultural: a imagem de Tales caindo em um poço, enquanto olhava as estrelas, mostra o filósofo "distraído" pelas grandes questões, e a de Heráclito, o "obscuro", é lembrada na cultura. Expressões como "tudo flui" ou "o conflito é o pai de todas as coisas" são usadas até hoje. A ciência moderna os reconhece como precursores: a ideia de átomo, a de evolução, a de que o universo é regido por leis, e a busca de uma explicação unificada da natureza. Ao estudar esses filósofos, vemos a Filosofia nascendo como investigação livre, curiosa e racional.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Os pré-socráticos aparecem no ENEM em questões que apresentam fragmentos, em geral de Heráclito ("ninguém se banha duas vezes no mesmo rio"), de Parmênides, de Tales ou de Demócrito, e pedem para identificar a ideia central (mudança, permanência, princípio material) ou relacioná-la com o surgimento da Filosofia e da ciência. Também pode ser cobrada a diferença entre a explicação mítica e a racional, e a relação entre a busca por uma explicação natural e o desenvolvimento do pensamento científico.',
  'Pontos de atenção: a arché é o princípio de todas as coisas; Tales (água), Anaximandro (ápeiron), Anaximenes (ar), Pitágoras (números), Heráclito (fogo e mudança), Parmênides (ser imutável), Demócrito (átomos); Heráclito e Parmênides representam posições opostas sobre a mudança; os atomistas anteciparam a ideia de átomo; e os pré-socráticos romperam com o mito, mas ainda usavam imagens. Para associar rapidamente: devir é Heráclito, ser é Parmênides, número é Pitágoras, átomo é Demócrito, água é Tales.',
  'Para revisar, monte uma tabela com cada filósofo, a escola, o princípio e a ideia central, e uma frase para memorizar. Em seguida, treine explicando, com suas palavras, por que a busca da arché marca o nascimento da Filosofia, e qual a diferença entre uma resposta mítica e a de Tales. Esse tema fecha o período cosmológico, e prepara o seguinte, Sócrates e os sofistas, em que o centro do pensamento passa a ser o ser humano, com suas virtudes, sua linguagem e sua vida em sociedade.'] }
]}
];
