/* Física: textos corridos, temas 4 a 6 */
module.exports = [
{ t:'Queda livre e lançamentos', txt:[
 { h:'A queda livre e a aceleração da gravidade', p:[
  'Quando um corpo é abandonado e cai sob a ação apenas da gravidade, dizemos que está em **queda livre**. Nesse movimento, desprezando a resistência do ar, todos os corpos caem com a mesma aceleração, independentemente da massa. É a aceleração da gravidade, g, cujo valor próximo à superfície da Terra é cerca de 9,8 m/s², arredondado para 10 m/s² nos problemas do ENEM. Uma pedra e uma pena, no vácuo, chegam juntas ao chão.',
  'Essa ideia contrariava a intuição antiga, segundo a qual corpos mais pesados caem mais rápido, defendida por Aristóteles. Foi Galileu quem mostrou, com experimentos e argumentos lógicos, que a diferença observada no ar vem da resistência do ar, e não do peso em si. Mais tarde, astronautas confirmaram na Lua: sem atmosfera, uma pena e um martelo caíram juntos. Esse episódio ilustra bem como a Física corrige impressões do senso comum.',
  'A queda livre é um caso particular do MUV, com aceleração constante g, dirigida para baixo. As equações são as mesmas do MUV: v = v₀ + gt, h = h₀ + v₀t + gt²/2 e v² = v₀² + 2gΔh, escolhendo o sentido positivo (para baixo, em geral, quando o corpo é solto). Se o corpo parte do repouso, v = gt e h = gt²/2. Em 3 s de queda, a velocidade é 30 m/s e a distância percorrida é 45 m.'] },
 { h:'Lançamento vertical', p:[
  'No **lançamento vertical**, o corpo é lançado para cima ou para baixo com velocidade inicial v₀. Na subida, a velocidade diminui 10 m/s a cada segundo até se anular no ponto mais alto; depois o corpo desce, ganhando 10 m/s por segundo. O movimento é MUV com aceleração constante de módulo g e sentido para baixo durante todo o percurso, inclusive na subida (em que o movimento é retardado).',
  'No ponto mais alto, a velocidade é nula, mas a aceleração continua valendo g. Essa é uma pegadinha comum: velocidade zero não significa aceleração zero. O tempo de subida é t = v₀/g, e a altura máxima é H = v₀²/(2g). O tempo de descida até o ponto de lançamento é igual ao de subida, e o corpo retorna com a mesma velocidade (em módulo) com que foi lançado, pela simetria do movimento.',
  'Exemplo: uma bola lançada para cima a 20 m/s sobe por 2 s e atinge H = 400/20 = 20 m. Depois, leva mais 2 s para voltar ao ponto de partida, totalizando 4 s de voo. Em problemas de lançamento de um ponto alto, como o topo de um prédio, aplique a equação da posição com o sentido positivo bem definido e resolva a equação do 2º grau, descartando raízes sem sentido físico.'] },
 { h:'Lançamento horizontal e oblíquo', p:[
  'Quando um corpo é lançado horizontalmente, ele realiza dois movimentos independentes: na **horizontal**, um movimento uniforme (sem aceleração, se desprezada a resistência do ar); na **vertical**, uma queda livre. Uma bola que rola e cai de uma mesa de 1,25 m de altura leva t = √(2h/g) = √(0,25) = 0,5 s para chegar ao chão, independentemente da velocidade horizontal. Se ela saiu a 4 m/s, o alcance é 4 × 0,5 = 2 m.',
  'O ponto-chave, enunciado por Galileu, é o **princípio da independência dos movimentos**: o tempo de queda depende só da altura; o alcance depende da velocidade horizontal e desse tempo. Um objeto solto e outro lançado horizontalmente da mesma altura chegam ao solo ao mesmo tempo, o que aparece em questões envolvendo, por exemplo, uma bala disparada horizontalmente e outra solta no mesmo instante.',
  'No **lançamento oblíquo**, a velocidade inicial forma um ângulo θ com a horizontal e é decomposta em v₀ₓ = v₀cosθ e v₀ᵧ = v₀senθ. Na horizontal, o movimento é uniforme com v₀ₓ; na vertical, é um lançamento vertical com v₀ᵧ. O alcance é máximo para θ = 45°, e ângulos complementares (como 30° e 60°) geram o mesmo alcance. A trajetória é uma parábola. Esses resultados explicam o arremesso de dardos, chutes de bola e saltos de atletas.'] },
 { h:'Resistência do ar e situações reais', p:[
  'Em situações reais, o ar exerce uma força de resistência que cresce com a velocidade. Um paraquedista, ao saltar, acelera inicialmente, mas a resistência aumenta até igualar o peso. Nesse instante, a força resultante é nula e a velocidade se torna constante, chamada de **velocidade terminal**. Com o paraquedas aberto, a área maior aumenta a resistência e reduz a velocidade terminal, permitindo um pouso seguro.',
  'Por isso, uma gota de chuva, que cairia de grandes alturas com enorme velocidade se a queda fosse livre, atinge o solo a poucos metros por segundo. A resistência do ar também explica por que uma folha cai mais devagar que uma pedra, e por que, em esportes como o ciclismo, a posição aerodinâmica é tão importante. Nas questões do ENEM, a menos que o enunciado mencione o ar, despreza-se a resistência.',
  'Ao analisar uma questão, pergunte-se: o enunciado fala em "desprezar a resistência do ar"? Se sim, use as equações da queda livre. Se não, e o objeto é leve ou a velocidade é alta, a resposta pode envolver o efeito da resistência de forma qualitativa. Em todos os casos, identificar o tipo de lançamento e decompor o movimento em horizontal e vertical é a rota mais segura.'] },
 { h:'Roteiro para resolver problemas', p:[
  'Para qualquer problema de queda ou lançamento, siga um roteiro. Primeiro, escolha o referencial e o sentido positivo. Segundo, identifique o tipo de movimento: queda livre, lançamento vertical, horizontal ou oblíquo. Terceiro, escreva as equações de cada direção. Quarto, resolva para a incógnita, sabendo que o tempo é a "ponte" entre os dois movimentos no lançamento oblíquo e no horizontal.',
  'Use o valor g = 10 m/s² quando o enunciado não especifica. Cuidado com sinais: se o sentido positivo é para cima, g é negativo nas equações. Verifique unidades e, ao final, se o resultado é plausível: uma queda de 5 m não pode levar 10 s. Em problemas com altura máxima e tempo total de voo, aproveite a simetria: o tempo de subida é igual ao de descida em um mesmo nível.',
  'Pratique com cenários do cotidiano: uma moeda caindo em um poço, uma bola de basquete, um salto de trampolim. Estimar o tempo de queda de uma altura de 20 m (2 s) e a velocidade de impacto (20 m/s, ou 72 km/h) ajuda a desenvolver uma noção física do problema. Esse é um dos temas mais clássicos da Mecânica, e quem domina o princípio da independência dos movimentos resolve a maioria das questões.'] }
]},

{ t:'Leis de Newton', txt:[
 { h:'Primeira lei: a inércia', p:[
  'A primeira lei de Newton, ou **lei da inércia**, afirma que um corpo permanece em repouso ou em movimento retilíneo uniforme enquanto a força resultante sobre ele for nula. Em outras palavras, os corpos "resistem" a mudanças no seu estado de movimento. É por isso que passageiros são lançados para frente quando o ônibus freia bruscamente: o corpo tende a manter a velocidade que tinha, enquanto o veículo diminui a sua.',
  'A **inércia** é a propriedade dos corpos de resistirem a variações de velocidade, e a **massa** é a medida dessa resistência. Quanto maior a massa, maior a inércia: é mais difícil empurrar um caminhão do que um carrinho de supermercado. O cinto de segurança existe para atuar como a força que muda o movimento do passageiro junto com o carro, evitando que ele prossiga para frente e atinja o painel ou o para-brisa.',
  'Essa lei desfez a ideia aristotélica de que é preciso uma força para manter um corpo em movimento. Na verdade, se não houvesse atrito, um objeto lançado continuaria em movimento indefinidamente. O que nos faz parar são forças, como o atrito e a resistência do ar. Compreender isso é essencial para evitar o erro comum de associar "movimento" a "força resultante": força resultante gera **aceleração**, e não velocidade.'] },
 { h:'Segunda lei: força e aceleração', p:[
  'A segunda lei de Newton é o princípio fundamental da Dinâmica: **F = m · a**. A força resultante sobre um corpo é igual ao produto de sua massa pela aceleração adquirida. A unidade de força no SI é o **newton (N)**, definido como a força que imprime aceleração de 1 m/s² a uma massa de 1 kg: 1 N = 1 kg·m/s². Uma força maior produz maior aceleração, e uma massa maior resulta em menor aceleração para a mesma força.',
  'A força e a aceleração são vetores e têm sempre a mesma direção e sentido. Por isso, para aplicar a lei, é necessário calcular a **força resultante**, que é a soma vetorial de todas as forças que atuam no corpo. Se um bloco de 5 kg é puxado com 30 N para a direita e sofre atrito de 10 N para a esquerda, a resultante é 20 N, e a aceleração é 20/5 = 4 m/s² para a direita.',
  'Também é importante distinguir **massa** de **peso**. A massa (em kg) é uma propriedade do corpo e não depende do local. O peso é a força com que a Terra atrai o corpo: P = m · g. Uma pessoa de 60 kg tem peso de 600 N na Terra (com g = 10 m/s²), e na Lua, onde g é cerca de 1,6 m/s², seu peso é de cerca de 96 N, embora sua massa continue 60 kg. Esse é um ponto clássico do ENEM.'] },
 { h:'Terceira lei: ação e reação', p:[
  'A terceira lei diz que, quando um corpo A exerce uma força sobre um corpo B, B exerce em A uma força de **mesmo módulo, mesma direção e sentido oposto**. Essas duas forças formam um par ação e reação. Elas atuam em **corpos diferentes**, e por isso nunca se anulam. Quando você empurra uma parede, a parede empurra você com a mesma intensidade; quando um nadador empurra a água para trás, a água o empurra para frente.',
  'Um erro muito comum é achar que ação e reação se cancelam. Elas não se cancelam, porque estão aplicadas em corpos distintos: o que importa para o movimento de um corpo são as forças que atuam **sobre ele**. O peso de um livro sobre a mesa e a força normal da mesa sobre o livro não formam par ação e reação; o par do peso é a atração do livro sobre a Terra, e o par da normal é a força do livro sobre a mesa.',
  'Muitas situações cotidianas ilustram a terceira lei: o recuo de uma arma ao disparar, o movimento de um foguete (que expele gases para trás e é impulsionado para frente), a caminhada (empurramos o chão para trás, e ele nos empurra para frente por atrito) e a propulsão de um barco a remo. Identificar quais são os dois corpos envolvidos em cada par é a chave para analisar corretamente esses casos.'] },
 { h:'Diagrama de forças e forças comuns', p:[
  'Para resolver problemas de Dinâmica, o primeiro passo é desenhar o **diagrama de corpo livre**, isolando o corpo e representando todas as forças que atuam sobre ele. As principais são: o **peso** (vertical, para baixo, exercido pela Terra); a **normal** (perpendicular à superfície de contato, exercida pelo apoio); o **atrito** (paralela à superfície, contrária ao movimento ou à tendência dele); a **tração** (exercida por fios e cordas, ao longo do fio); e a **força elástica** (de molas).',
  'Em um bloco em repouso sobre uma mesa horizontal, o peso e a normal têm o mesmo módulo e se equilibram. Em um elevador acelerando para cima, a normal sobre uma pessoa é maior que seu peso, e ela "se sente mais pesada"; ao acelerar para baixo, a normal é menor, e ela "se sente mais leve". Em queda livre, a normal é nula e há a sensação de ausência de peso, embora a gravidade continue atuando.',
  'Em sistemas de corpos ligados por fios, cada corpo tem seu diagrama e sua equação F = ma. A tração é a mesma ao longo de um fio ideal, e os corpos ligados têm a mesma aceleração (em módulo). Escrevendo as equações de cada corpo e resolvendo o sistema, determinam-se a aceleração e a tração. Esse método sistemático evita erros e resolve desde máquinas de Atwood até blocos puxados em planos.'] },
 { h:'Aplicações e dicas de prova', p:[
  'Nas provas, as leis de Newton aparecem de forma conceitual (explicar por que algo acontece) e quantitativa (calcular aceleração, força ou massa). Em questões conceituais, procure identificar se há força resultante: se a velocidade é constante, a resultante é nula; se há mudança de velocidade (em módulo ou direção), há resultante. Em curvas, por exemplo, mesmo com velocidade escalar constante, há aceleração centrípeta e, portanto, força resultante.',
  'Questões sobre segurança veicular usam a inércia e o impulso: cinto, airbag, encosto de cabeça. Questões sobre esportes usam a ação e reação: saltos, chutes, remo. Questões sobre elevadores e balanças exploram a diferença entre peso e peso aparente. Em todas, desenhe as forças, escreva a segunda lei e interprete o resultado no contexto.',
  'Algumas dicas finais: sempre converta a massa para quilogramas; use g = 10 m/s² quando indicado; atenção à direção das forças (decomponha em componentes se necessário); e lembre-se de que a normal nem sempre é igual ao peso (por exemplo, em planos inclinados ou com forças verticais adicionais). Com o diagrama de forças correto, a resolução é quase mecânica.'] }
]},

{ t:'Atrito e plano inclinado', txt:[
 { h:'O que é atrito e de onde vem', p:[
  'O atrito é a força de resistência que surge quando duas superfícies em contato tendem a deslizar (ou deslizam) uma sobre a outra. Ele nasce das irregularidades microscópicas das superfícies e das interações entre as moléculas. Está presente em quase tudo o que fazemos: é o atrito que permite caminhar, segurar objetos, frear um carro e apertar um parafuso. Sem ele, nem andar seria possível, e todas as superfícies seriam como gelo muito liso.',
  'A direção do atrito é sempre **paralela à superfície de contato**, e seu sentido é **contrário ao movimento relativo** (ou à tendência de movimento) entre as superfícies. Um bloco empurrado para a direita sofre atrito para a esquerda. Já para uma pessoa que caminha, o atrito do solo sobre o pé é para frente, pois o pé empurra o chão para trás: o atrito é, nesse caso, a força que impulsiona o movimento.',
  'O módulo da força de atrito depende da **força normal** (N) entre as superfícies e da natureza dos materiais, descrita por um coeficiente de atrito μ. Para o atrito cinético, Fat = μ_c · N; para o atrito estático máximo, Fat,máx = μ_e · N. Surpreendentemente, ele não depende, em primeira aproximação, da área de contato: um tijolo apoiado de lado ou de pé sofre o mesmo atrito, pois a normal é a mesma.'] },
 { h:'Atrito estático e cinético', p:[
  'O **atrito estático** atua enquanto não há deslizamento. Ele se ajusta à força aplicada: se você empurra um armário com pouca força e ele não se move, o atrito estático é igual à força aplicada, em sentido contrário. Só quando a força supera o valor máximo, μ_e · N, o armário começa a deslizar. Esse limite explica por que é mais difícil "dar o arranque" a um objeto pesado do que mantê-lo em movimento.',
  'O **atrito cinético** atua quando já há deslizamento e tem valor praticamente constante, μ_c · N, geralmente menor que o máximo do atrito estático (μ_c < μ_e). Por isso, depois que o armário começa a se mover, é preciso menos força para continuar movendo-o. O gráfico do atrito em função da força aplicada mostra uma reta crescente até o máximo estático, seguida de uma queda e de um patamar constante cinético.',
  'Em aplicações: o sistema ABS de freios evita que as rodas travem, mantendo o atrito estático (maior) em vez do cinético, o que reduz a distância de frenagem e preserva o controle do veículo. Pneus carecas e pistas molhadas diminuem o coeficiente de atrito, aumentando o risco de derrapagem. A diferença entre os dois tipos de atrito é um tema recorrente e vale compreendê-la bem.'] },
 { h:'Plano inclinado: decomposição do peso', p:[
  'Em um plano inclinado de ângulo θ com a horizontal, o peso do bloco (vertical, para baixo) não é paralelo nem perpendicular à superfície. A solução é decompô-lo em duas componentes: **Pₜ = P · senθ**, paralela ao plano e apontando ladeira abaixo, e **Pₙ = P · cosθ**, perpendicular ao plano. A normal equilibra a componente perpendicular: N = P · cosθ. É a componente paralela que tende a fazer o bloco descer.',
  'Sem atrito, a aceleração do bloco ao longo do plano é a = g · senθ, independente da massa. Em um plano de 30°, a = 10 × 0,5 = 5 m/s². Quanto maior o ângulo, maior a aceleração; em 90° (queda livre), a = g. Com atrito cinético, a aceleração é a = g(senθ − μ·cosθ). O bloco desce se senθ > μ_e·cosθ, ou seja, se tgθ > μ_e; caso contrário, fica parado pelo atrito estático.',
  'Esse resultado leva a uma ideia interessante: o ângulo máximo para que o bloco ainda permaneça em repouso é tal que tgθ = μ_e. Esse é o **ângulo de repouso**, usado em engenharia para projetar taludes, pilhas de grãos e rampas. Para determinar o coeficiente de atrito estático, basta inclinar gradualmente o plano até o corpo começar a escorregar e medir o ângulo.'] },
 { h:'Problemas típicos com atrito', p:[
  'Um bloco de 10 kg é puxado por uma força horizontal de 50 N sobre uma superfície com μ_c = 0,3. A normal é igual ao peso (100 N), e o atrito é 0,3 × 100 = 30 N. A resultante é 50 − 30 = 20 N, e a aceleração é 2 m/s². Se a força fosse de 25 N e μ_e = 0,4 (atrito máximo 40 N), o bloco não se moveria, e o atrito estático seria exatamente 25 N, igual à força aplicada. Atenção: nem sempre o atrito vale μ·N.',
  'Em sistemas com blocos ligados por fios e roldanas, em que um bloco apoiado sobre a mesa é puxado por outro suspenso, escreva a equação F = ma para cada bloco, considerando o atrito no bloco apoiado e a tração no fio. A aceleração é a mesma para ambos (fio inextensível) e a tração é a mesma em cada ponto do fio ideal. Resolvendo as duas equações, obtêm-se a aceleração e a tração.',
  'Em planos inclinados, lembre que o ângulo θ do plano é igual ao ângulo entre o peso e a normal. Um erro frequente é trocar seno e cosseno: a componente paralela usa o seno, e a perpendicular, o cosseno, quando θ é medido em relação à horizontal. Desenhe o triângulo para confirmar. Se θ = 0 (plano horizontal), a componente paralela é nula, o que é coerente com senθ = 0.'] },
 { h:'Atrito no cotidiano e no ENEM', p:[
  'O atrito é útil e prejudicial ao mesmo tempo. Útil: nos freios, pneus, calçados e na fixação de parafusos e pregos. Prejudicial: no desgaste de peças, no aquecimento de motores e na perda de energia em máquinas. Lubrificantes (óleos e graxas) reduzem o atrito entre peças móveis, e rolamentos substituem o deslizamento por rolamento, que gera menos atrito. Questões do ENEM exploram essas aplicações com textos sobre desgaste, segurança e eficiência.',
  'Outra aplicação é a **força de atrito em curvas**: um carro faz a curva porque o atrito entre os pneus e a pista fornece a força centrípeta. Se a pista está molhada ou o carro está muito rápido, o atrito máximo não é suficiente e o carro derrapa. Por isso, curvas de estradas costumam ser inclinadas (sopradas), de modo que a componente da normal ajude a fornecer a força centrípeta.',
  'Para revisar o tema, tenha em mente três conceitos: o atrito depende da normal, nunca é maior que o seu valor máximo, e tem sentido oposto ao movimento relativo. Pratique desenhando as forças em planos horizontais e inclinados e determinando se o corpo se move ou não. Uma verificação rápida do tipo "o atrito necessário é menor ou maior que o máximo possível?" resolve muitos problemas sem equações complicadas.'] }
]}
];
