/* Física: textos corridos, temas 22 a 25 */
module.exports = [
{ t:'Geração de energia elétrica', txt:[
 { h:'Do movimento à eletricidade', p:[
  'A energia elétrica não é "produzida do nada": ela é obtida pela **transformação** de outras formas de energia. Na maioria das usinas, o princípio é o mesmo: uma fonte de energia faz girar uma **turbina**, que está ligada a um **gerador**. O gerador, baseado na indução eletromagnética de Faraday, converte o movimento de rotação em energia elétrica, por meio de ímãs que giram dentro de bobinas. A diferença entre os tipos de usina está na fonte que faz a turbina girar: água, vapor, vento ou gases quentes.',
  'Nas **usinas hidrelétricas**, a água represada em uma barragem, com energia potencial gravitacional, desce por dutos e ganha energia cinética, que movimenta as turbinas. Nas **termelétricas**, a queima de combustíveis (carvão, gás natural, óleo, biomassa) produz calor, que gera vapor de água em alta pressão para girar a turbina. Nas **usinas nucleares**, o calor vem da fissão de núcleos de urânio. Nas **eólicas**, o vento gira as pás diretamente. Em todos os casos, a energia da fonte é convertida em eletricidade.',
  'Depois da geração, a tensão é elevada por transformadores para a transmissão em longas distâncias, com menores perdas por efeito Joule, e reduzida perto dos consumidores. O Brasil possui um grande sistema interligado, em que usinas de diferentes regiões se complementam, e a energia é transportada por milhares de quilômetros de linhas de transmissão. Isso permite compensar períodos de seca em uma região com a geração em outra.'] },
 { h:'Hidrelétricas e a matriz brasileira', p:[
  'A **energia hidráulica** é a principal fonte da matriz elétrica brasileira, respondendo por cerca de metade da eletricidade gerada (essa proporção variou ao longo dos anos). É renovável e de baixo custo de operação, e a barragem permite armazenar energia na forma de água. As grandes usinas, como Itaipu, Belo Monte e Tucuruí, estão entre as maiores do mundo. Vantagens: não emite gases de efeito estufa na operação, e permite controle de vazão e usos múltiplos da água (irrigação, navegação, lazer).',
  'Entre as desvantagens, estão os impactos ambientais e sociais: o alagamento de grandes áreas, a perda de vegetação e de fauna, a alteração do regime dos rios, a interferência na reprodução de peixes migratórios e o deslocamento de populações ribeirinhas e indígenas. Reservatórios podem emitir metano pela decomposição de matéria orgânica submersa. Além disso, a geração depende do regime de chuvas, e longos períodos de seca reduzem a capacidade das usinas.',
  'O conceito de **energia limpa** não significa ausência de impacto, e sim impacto menor em um aspecto específico (no caso, emissões). O ENEM costuma pedir análises comparativas entre fontes, avaliando custos, impactos, disponibilidade e adequação regional. Uma boa postura é comparar critérios (renovabilidade, emissões, área ocupada, confiabilidade, custo) em vez de procurar uma fonte perfeita.'] },
 { h:'Termelétricas, nuclear e biomassa', p:[
  'As **termelétricas** convertem energia térmica em elétrica e podem ser movidas por combustíveis fósseis (carvão mineral, petróleo, gás natural) ou renováveis (biomassa, como bagaço de cana). Têm a vantagem de poder ser instaladas perto dos centros consumidores e de funcionar de modo estável, complementando a energia hidráulica em períodos secos. A desvantagem principal é a emissão de gases de efeito estufa e poluentes, no caso dos fósseis, e o consumo de grandes quantidades de água para resfriamento.',
  'As **usinas nucleares** usam o calor liberado na fissão do urânio para gerar vapor. Uma pequena quantidade de combustível produz uma imensa quantidade de energia, sem emissão de CO₂ na operação. Porém, geram **rejeitos radioativos**, que precisam de armazenamento seguro por longos períodos, e há riscos de acidentes graves, como os de Chernobyl (1986) e Fukushima (2011). No Brasil, as usinas Angra 1 e Angra 2 fornecem uma pequena parte da eletricidade, e Angra 3 está em construção.',
  'A **biomassa** (bagaço de cana, lenha, resíduos agrícolas e florestais) tem a vantagem de reaproveitar resíduos e de ter um ciclo de carbono considerado quase neutro: o CO₂ emitido na queima é reabsorvido pelo crescimento das plantas seguintes. No Brasil, as usinas de açúcar e etanol geram eletricidade com o bagaço, vendendo o excedente à rede. É uma fonte renovável, mas exige áreas agrícolas, o que pode competir com a produção de alimentos e a preservação ambiental.'] },
 { h:'Fontes alternativas: eólica, solar e outras', p:[
  'A **energia eólica** usa aerogeradores, em que o vento gira as pás e movimenta um gerador. É limpa e renovável, e o Brasil, especialmente o Nordeste, tem ventos fortes e constantes, o que o torna um dos maiores produtores do mundo. As desvantagens são a intermitência (depende do vento), o ruído, o impacto visual e sobre aves e morcegos, e a necessidade de grandes áreas. Combina bem com a energia hidráulica: quando venta mais, as usinas hidráulicas armazenam água.',
  'A **energia solar** pode ser fotovoltaica (células de silício que convertem a luz diretamente em eletricidade, pelo efeito fotoelétrico) ou térmica (coletores que aquecem a água ou fluidos para gerar vapor). As placas fotovoltaicas têm crescido em telhados residenciais e comerciais ("geração distribuída"), permitindo que o consumidor gere sua energia e injete o excedente na rede. Limitações: dependência da luz do dia, custo inicial e necessidade de armazenamento (baterias) para uso noturno.',
  'Outras fontes incluem a **geotérmica** (calor do interior da Terra, usado em regiões vulcânicas), a **maremotriz** (energia das marés), das **ondas** e o **hidrogênio**, tratado como vetor energético. A **transição energética** global busca ampliar as renováveis e reduzir os combustíveis fósseis, para limitar o aquecimento global. O desafio é conciliar demanda crescente, segurança do suprimento, custo e impacto ambiental, e o ENEM costuma explorar justamente esses dilemas em textos de contexto.'] },
 { h:'Como analisar questões sobre geração de energia', p:[
  'Em questões de geração de energia, identifique a **sequência de transformações**: por exemplo, em uma hidrelétrica, energia potencial gravitacional → cinética da água → cinética de rotação da turbina → elétrica no gerador. Em uma termelétrica, energia química do combustível → térmica → cinética do vapor → mecânica da turbina → elétrica. Em painéis fotovoltaicos, energia luminosa → elétrica. Saber desenhar essa cadeia resolve boa parte das questões conceituais.',
  'Outra dica: lembre-se de que há sempre **perdas**, em geral na forma de calor, e que o rendimento total é o produto dos rendimentos de cada etapa. Questões de transmissão exploram o fato de que elevar a tensão reduz a corrente e, portanto, as perdas por efeito Joule. E questões ambientais comparam emissões, uso do solo e impactos sociais, devendo-se fundamentar a resposta nos dados fornecidos pelo texto.',
  'Por fim, desenvolva uma visão crítica: não existe fonte de energia sem custo ambiental. O que se busca é um conjunto equilibrado, a chamada **matriz diversificada**, que combine fontes complementares. A eficiência energética (usar menos energia para o mesmo serviço) é uma "fonte" adicional, muitas vezes a mais barata e limpa, e deve acompanhar qualquer política de expansão da geração.'] }
]},

{ t:'Ondas eletromagnéticas', txt:[
 { h:'Natureza das ondas eletromagnéticas', p:[
  'As **ondas eletromagnéticas** são perturbações formadas por um campo elétrico e um campo magnético oscilantes, perpendiculares entre si e à direção de propagação. Maxwell previu, no século XIX, que um campo elétrico variável gera um campo magnético variável, e vice-versa, de modo que essa perturbação pode se propagar sozinha pelo espaço. Hertz comprovou experimentalmente a existência dessas ondas, e hoje elas são a base das telecomunicações e de grande parte da tecnologia moderna.',
  'São ondas **transversais** e, ao contrário das ondas mecânicas, **não precisam de meio material**: propagam-se no vácuo, à velocidade c ≈ 3 × 10⁸ m/s. Essa velocidade é a mesma para todas, independentemente da frequência. A relação c = λ · f liga o comprimento de onda λ à frequência f: quanto maior a frequência, menor o comprimento de onda. Em meios materiais, a velocidade é menor, dependendo do índice de refração do meio.',
  'Essas ondas transportam energia, e a energia é proporcional à frequência (E = h·f, na descrição quântica). Por isso, as de **maior frequência** (raios X e gama) são mais energéticas e potencialmente perigosas para os seres vivos, enquanto as de menor frequência (rádio) carregam pouca energia por "pacote". Compreender essa relação entre frequência, comprimento de onda e energia é a chave para organizar o espectro eletromagnético.'] },
 { h:'O espectro eletromagnético', p:[
  'O **espectro eletromagnético** organiza as ondas por frequência (ou comprimento de onda). Em ordem crescente de frequência: **ondas de rádio**, **micro-ondas**, **infravermelho**, **luz visível**, **ultravioleta**, **raios X** e **raios gama**. A faixa visível é pequena, de cerca de 400 nm (violeta) a 700 nm (vermelho), e é a parte que o olho humano detecta. Todas as demais são invisíveis, mas têm efeitos e aplicações importantes.',
  'As **ondas de rádio** transportam sinais de rádio, TV e celulares, e podem ter comprimentos de onda de metros a quilômetros. As **micro-ondas** são usadas em fornos, radares, Wi-Fi e comunicações por satélite. O **infravermelho** é associado ao calor, usado em controles remotos, câmeras térmicas e sensores. A **luz visível** permite a visão e a fotossíntese. O **ultravioleta** provoca bronzeamento, queimaduras e esteriliza superfícies. Os **raios X** atravessam tecidos moles e são usados em radiografias, e os **raios gama** vêm de processos nucleares, usados em radioterapia.',
  'Uma forma de memorizar: quanto maior a frequência, maior a energia e maior o poder de penetração (em geral). Das ondas de rádio aos raios gama, a energia por fóton aumenta. Em questões do ENEM, é comum pedir para ordenar tipos de ondas por frequência ou comprimento, para associar uma onda à sua aplicação, ou para comparar a energia de duas radiações. Tenha a ordem do espectro na ponta da língua.'] },
 { h:'Luz visível, cores e interação com a matéria', p:[
  'A luz branca é uma mistura de todas as cores do espectro visível. Quando incide sobre um objeto, ela pode ser **absorvida**, **refletida** ou **transmitida**, e o que o objeto faz com cada cor define o que enxergamos. Um objeto azul reflete a luz azul e absorve as outras; um objeto transparente transmite a maior parte da luz; um espelho reflete quase toda. A cor percebida é a da luz que chega aos olhos.',
  'A atmosfera interage de modo diferente com cada faixa do espectro. É **transparente** à luz visível e a algumas ondas de rádio, o que permite a vida e as comunicações. Absorve a maior parte do ultravioleta (a camada de ozônio filtra a faixa mais danosa), do infravermelho (parte pelo vapor-d\'água e CO₂) e dos raios X e gama. O céu é azul porque o espalhamento da luz pelas moléculas do ar é mais intenso para comprimentos de onda menores (azul), e o pôr do sol é avermelhado porque, com a luz percorrendo uma distância maior na atmosfera, o azul é espalhado e resta o vermelho.',
  'Os materiais respondem às ondas de forma seletiva. O vidro é transparente à luz visível, mas bloqueia grande parte do ultravioleta; o chumbo absorve raios X; as paredes enfraquecem o sinal de Wi-Fi mais do que o de rádio FM; o corpo humano é transparente a certas ondas de rádio, mas absorve micro-ondas. Compreender essas interações explica por que cada tecnologia usa uma faixa específica do espectro.'] },
 { h:'Tecnologias e aplicações', p:[
  'As **telecomunicações** modernas dependem de ondas eletromagnéticas. A rádio AM e FM, a TV aberta, o celular, o GPS, o Wi-Fi, o Bluetooth e as redes de satélite usam ondas de rádio e micro-ondas, cada uma em uma faixa de frequências reservada por órgãos reguladores. A informação é codificada na onda por modulação (de amplitude ou de frequência, ou de forma digital) e recuperada pelo receptor. A sintonização de uma estação é um exemplo de ressonância: o circuito é ajustado à frequência da emissora.',
  'Na **medicina**, os raios X produzem radiografias e tomografias; os raios gama são usados em radioterapia contra câncer e em exames de medicina nuclear; o ultravioleta esteriliza instrumentos; o infravermelho é usado em termômetros e em fisioterapia; o laser (luz coerente) é empregado em cirurgias. Na **indústria** e **segurança**, usam-se infravermelho em sensores de presença e visão noturna, micro-ondas em radar e fornos, e raios X em inspeções de bagagens e soldas.',
  'No **cotidiano**, o forno de micro-ondas aquece alimentos porque as micro-ondas fazem as moléculas de água girarem e vibrarem, aumentando a temperatura. O controle remoto usa infravermelho. As lâmpadas de LED emitem luz visível de modo eficiente. O **código de barras** e o **leitor óptico** usam luz refletida. Painéis solares captam luz do Sol. Cada uma dessas aplicações escolhe a faixa do espectro mais adequada ao objetivo e ao material envolvido.'] },
 { h:'Riscos, proteção e questões de prova', p:[
  'Os efeitos das radiações sobre os seres vivos dependem da **energia** e da **dose**. As radiações **ionizantes** (ultravioleta mais energético, raios X e gama) têm energia suficiente para arrancar elétrons de átomos e moléculas, podendo danificar o DNA e causar mutações e câncer. As **não ionizantes** (rádio, micro-ondas, infravermelho, luz visível) não têm energia para isso, e seus efeitos principais são térmicos, em intensidades elevadas. Um telefone celular emite radiação não ionizante, de baixa potência.',
  'A **proteção** envolve distância, tempo de exposição e blindagem. Contra o ultravioleta, usam-se protetor solar, chapéus e óculos escuros; contra raios X, aventais e barreiras de chumbo. A **camada de ozônio**, na estratosfera, absorve grande parte do UV-B e UV-C; sua depleção por CFCs aumentou a preocupação com o câncer de pele e levou ao Protocolo de Montreal (1987), que restringiu essas substâncias. Esse é um dos exemplos de cooperação internacional bem-sucedida.',
  'Em questões do ENEM, esteja atento à ordem do espectro, às aplicações e aos riscos, e a gráficos ou tabelas com frequência e comprimento de onda. Lembre-se de que todas as ondas eletromagnéticas têm a mesma velocidade no vácuo, e que ao mudar de meio a frequência se mantém. Para calcular, use c = λ·f com unidades consistentes (metros, hertz). E, em contextos de saúde, diferencie radiação ionizante de não ionizante, evitando as confusões comuns sobre o que é perigoso e o que não é.'] }
]},

{ t:'Física moderna', txt:[
 { h:'Por que surgiu a Física moderna', p:[
  'No final do século XIX, muitos físicos acreditavam que a Física estava quase completa: a Mecânica de Newton e o Eletromagnetismo de Maxwell pareciam explicar tudo. Mas alguns fenômenos resistiam: a radiação emitida por corpos aquecidos, o efeito fotoelétrico, os espectros de emissão dos átomos e a velocidade constante da luz em todos os referenciais. A tentativa de explicá-los levou a duas grandes revoluções no início do século XX: a **teoria da relatividade** e a **mecânica quântica**.',
  'A **radiação do corpo negro** (a emissão de luz por um corpo aquecido) não podia ser explicada pela Física clássica, que previa energia infinita em altas frequências. Em 1900, Max Planck propôs que a energia é emitida em pacotes discretos, os **quanta**, de energia E = h·f, em que h é a constante de Planck (≈ 6,6 × 10⁻³⁴ J·s). A ideia, inicialmente tratada como artifício matemático, abriu caminho para toda a teoria quântica.',
  'A Física moderna descreve o muito pequeno (átomos, partículas) e o muito rápido ou massivo (velocidades próximas à da luz, campos gravitacionais intensos). Embora seus efeitos pareçam distantes do cotidiano, ela sustenta tecnologias que usamos todos os dias: computadores, celulares, lasers, GPS, painéis solares, ressonância magnética. O ENEM costuma cobrá-la de forma conceitual e contextualizada.'] },
 { h:'Efeito fotoelétrico e dualidade onda-partícula', p:[
  'O **efeito fotoelétrico** é a emissão de elétrons por uma superfície metálica quando atingida por luz. Observações mostraram que só há emissão se a frequência da luz for maior que um valor mínimo, característico do metal (a frequência de corte), independentemente da intensidade. Aumentar a intensidade da luz aumenta o **número** de elétrons emitidos, mas não sua energia. A teoria ondulatória clássica não explicava isso.',
  'Einstein, em 1905, explicou o efeito supondo que a luz é formada por **fótons**, pacotes de energia E = h·f. Um fóton só pode arrancar um elétron se sua energia for maior que a energia de ligação (função trabalho) do metal. A energia cinética máxima do elétron é E_c = h·f − φ. Se a frequência é baixa, nenhum fóton tem energia suficiente, mesmo que haja muitos deles. Por esse trabalho, Einstein recebeu o Nobel de Física de 1921.',
  'Surge assim a **dualidade onda-partícula**: a luz se comporta como onda (em fenômenos de interferência e difração) e como partícula (no efeito fotoelétrico). De Broglie propôs que a matéria também tem comportamento ondulatório, com comprimento de onda λ = h/(m·v), confirmado pela difração de elétrons. Nem onda nem partícula no sentido clássico, os objetos quânticos têm comportamento que depende de como são observados. Essa ideia está na base da mecânica quântica.'] },
 { h:'Modelo atômico de Bohr e níveis de energia', p:[
  'Os átomos emitem luz em cores específicas, formando **espectros de linhas**. O modelo de Bohr (1913) explicou isso: os elétrons ocupam **níveis de energia** quantizados, e só podem ter certas energias. Quando um elétron absorve energia, salta para um nível mais alto; ao retornar a um nível inferior, emite um fóton cuja energia é igual à diferença entre os níveis: h·f = E_alto − E_baixo. Assim, cada elemento tem um conjunto característico de cores, como uma "impressão digital".',
  'Essa ideia explica os **testes de chama** em Química (sódio, amarelo; cobre, verde) e as cores dos fogos de artifício, produzidas por sais metálicos diferentes. Também é a base da **espectroscopia**, técnica usada em Astronomia para determinar a composição de estrelas a partir da luz que elas emitem, e em análise de materiais. Lâmpadas de vapor de sódio, letreiros de neônio e lasers também aproveitam a emissão em níveis discretos.',
  'O modelo atual do átomo é o **quântico**, em que o elétron não tem trajetória definida, e sim uma probabilidade de ser encontrado em certa região (orbital). O **princípio da incerteza de Heisenberg** estabelece que não é possível conhecer, ao mesmo tempo e com precisão arbitrária, a posição e a velocidade de uma partícula. Essa limitação é fundamental, e não resulta de falhas dos instrumentos. Ela mostra que, no mundo quântico, a natureza é probabilística.'] },
 { h:'Relatividade restrita', p:[
  'A **teoria da relatividade restrita**, proposta por Einstein em 1905, baseia-se em dois postulados: as leis da Física são as mesmas em todos os referenciais inerciais, e a velocidade da luz no vácuo é a mesma para todos os observadores, independentemente do movimento da fonte ou do observador. Disso resultam consequências surpreendentes, que se tornam apreciáveis em velocidades próximas à da luz, e que foram confirmadas por experimentos.',
  'Entre elas, a **dilatação do tempo**: para um observador, o tempo passa mais devagar em um relógio em movimento; a **contração do comprimento**: objetos em movimento parecem mais curtos na direção do movimento; e a **relatividade da simultaneidade**: eventos simultâneos para um observador podem não ser para outro. Partículas chamadas múons, criadas na alta atmosfera, vivem tão pouco que não chegariam ao solo, mas, por causa da dilatação do tempo, chegam. Os relógios dos satélites GPS precisam de correções relativísticas para manter a precisão.',
  'A relação mais famosa é **E = m·c²**: massa e energia são equivalentes. Uma pequena massa corresponde a uma enorme quantidade de energia, pois c² é muito grande. Nas reações nucleares, parte da massa se converte em energia, o que explica o poder das usinas e das bombas atômicas e a energia das estrelas. A **relatividade geral** (1915) estende a teoria à gravitação: a massa curva o espaço-tempo, e a gravidade é a manifestação dessa curvatura, confirmada pela observação de ondas gravitacionais e de buracos negros.'] },
 { h:'Física nuclear e radioatividade', p:[
  'O núcleo atômico é formado por prótons e nêutrons, mantidos unidos pela força nuclear forte. Alguns núcleos são **instáveis** e se transformam emitindo radiação: é a **radioatividade**. As emissões principais são a **alfa** (α, dois prótons e dois nêutrons, pouco penetrante), a **beta** (β, elétrons ou pósitrons, penetração média) e a **gama** (γ, radiação eletromagnética de alta energia, muito penetrante). A **meia-vida** é o tempo necessário para que metade dos núcleos de uma amostra se desintegre, característica de cada isótopo.',
  'Na **fissão nuclear**, um núcleo pesado (urânio-235) se divide em núcleos menores ao absorver um nêutron, liberando energia e outros nêutrons, que podem provocar novas fissões, em uma **reação em cadeia**. É controlada nos reatores de usinas e descontrolada nas bombas. Na **fusão nuclear**, núcleos leves (hidrogênio) se unem para formar núcleos mais pesados (hélio), liberando uma energia enorme. É a fonte de energia do Sol e das estrelas. A fusão controlada na Terra ainda é um desafio tecnológico.',
  'As aplicações da radioatividade são numerosas: **datação** por carbono-14 (a meia-vida de cerca de 5.700 anos permite datar fósseis e objetos orgânicos); **medicina nuclear** e radioterapia; esterilização de materiais; irradiação de alimentos; rastreadores em pesquisas. Os riscos incluem a exposição à radiação ionizante, acidentes (Chernobyl, Fukushima, Goiânia, com o césio-137, em 1987) e o descarte de rejeitos. Questões do ENEM tratam desses benefícios e riscos e pedem interpretação de meia-vida.'] },
 { h:'Aplicações e como estudar', p:[
  'A Física moderna está presente em tecnologias do cotidiano. O **laser** (amplificação de luz por emissão estimulada) é usado em leitores de código de barras, cirurgias, comunicações por fibra óptica e corte industrial. Os **semicondutores**, entendidos pela mecânica quântica, deram origem ao transistor, ao LED, aos chips e aos computadores. As **células fotovoltaicas** aplicam o efeito fotoelétrico. A **ressonância magnética** utiliza propriedades quânticas dos núcleos de hidrogênio para formar imagens do corpo.',
  'Para estudar, organize o tema em quatro blocos: quantização e fótons (Planck, Einstein), modelo atômico (Bohr e níveis de energia), relatividade (dilatação do tempo e E = mc²) e física nuclear (radioatividade, fissão e fusão). Em cada bloco, memorize a ideia central e uma aplicação. As fórmulas cobradas são poucas: E = h·f, E = m·c² e a de meia-vida (a quantidade cai pela metade a cada período de meia-vida).',
  'Em questões, procure palavras-chave: "quanta" e "fóton" indicam efeito fotoelétrico; "níveis de energia" e "cores" indicam o modelo de Bohr; "tempo", "velocidade da luz" indicam relatividade; "meia-vida", "decaimento" indicam radioatividade. Para meia-vida, lembre: após n períodos, resta 1/2ⁿ da amostra. Uma abordagem calma e conceitual funciona melhor que decorar detalhes, pois o exame valoriza a compreensão e a relação com tecnologias e sociedade.'] }
]},

{ t:'Física no cotidiano e tecnologia', txt:[
 { h:'A Física está em tudo', p:[
  'A Física não é só um conjunto de fórmulas de livros, mas a linguagem que explica o funcionamento do mundo ao nosso redor. Ao acordar com o despertador, tomar banho em um chuveiro elétrico, andar de ônibus, usar o celular, cozinhar no micro-ondas e ver televisão, estamos usando princípios de eletricidade, calor, movimento, ondas e eletromagnetismo. O ENEM busca justamente verificar se o candidato consegue reconhecer esses princípios em situações reais, relacionando conceitos a fenômenos e a tecnologias.',
  'Por isso, as questões costumam trazer textos de divulgação científica, notícias, esquemas e dados de equipamentos. Raramente pedem uma fórmula "seca": pedem a interpretação de uma situação. Uma estratégia valiosa é desenvolver um "olhar físico" sobre o dia a dia: pergunte-se, por exemplo, por que o gelo flutua, por que o carro precisa de cinto, por que o micro-ondas aquece de dentro para fora, por que a geladeira esquenta atrás. Essas perguntas treinam a conexão entre teoria e prática.',
  'Este tema reúne conteúdos dos anteriores aplicados a contextos tecnológicos, de segurança, de saúde e de meio ambiente. Em cada um, o roteiro é: identificar o fenômeno físico, reconhecer a grandeza envolvida, aplicar a lei ou o princípio adequado e interpretar o resultado no contexto. Com treino, a leitura do texto se torna mais rápida, e o raciocínio, mais seguro.'] },
 { h:'Trânsito e segurança', p:[
  'Nos **veículos**, a Física explica a segurança. O **cinto de segurança** e o **encosto de cabeça** atuam pela inércia: em uma freada brusca, o corpo tende a continuar em movimento, e o cinto aplica uma força para pará-lo gradualmente. O **airbag** aumenta o tempo de parada, reduzindo a força média sobre o ocupante (impulso e quantidade de movimento). As **zonas de deformação** absorvem energia na colisão, e a cabine rígida protege os passageiros.',
  'A **distância de frenagem** cresce com o quadrado da velocidade: dobrar a velocidade quadruplica a distância necessária para parar. A isso soma-se a distância percorrida durante o tempo de reação do motorista, que aumenta com o cansaço, o álcool e o uso de celular. Em pista molhada, o atrito diminui, e a frenagem exige distâncias maiores. **ABS** e **controle de estabilidade** ajudam a manter o atrito estático e o controle. **Radares** medem a velocidade pelo efeito Doppler ou por sensores no pavimento.',
  'Em **curvas**, a força de atrito entre os pneus e a pista fornece a força centrípeta; se a velocidade é alta demais, o atrito não basta e o carro derrapa. As curvas de estradas costumam ser inclinadas para que a normal ajude. Em **motocicletas** e bicicletas, a inclinação do corpo contribui para o equilíbrio. Em todas essas situações, as questões do ENEM pedem relacionar leis de Newton, energia e atrito com medidas de segurança.'] },
 { h:'Casa, eletrodomésticos e energia', p:[
  'Os **eletrodomésticos** mostram a Física em ação. O **chuveiro** converte energia elétrica em calor por efeito Joule; a **geladeira** retira calor do interior e o rejeita na parte de trás, por um ciclo de compressão e expansão de um fluido; o **micro-ondas** aquece alimentos por radiação de micro-ondas, que agita as moléculas de água; o **ar-condicionado** funciona como uma geladeira para o ambiente; o **ferro de passar** e a **torradeira** usam resistores. Cada aparelho tem potência, tensão e consumo, em kWh, que determinam o custo.',
  'A **eficiência energética** é um aspecto central. Lâmpadas LED consomem muito menos que incandescentes para a mesma luminosidade; eletrodomésticos com selo Procel A são mais econômicos; evitar o stand-by, usar a luz natural e manter a vedação da geladeira reduzem o consumo. A **conta de luz** é calculada pelo consumo em kWh vezes a tarifa. Calcular quanto se economiza ao trocar um equipamento é uma questão clássica, que usa apenas P·Δt e multiplicações.',
  'Em **cozinha**, o calor se propaga por condução (panela), convecção (água fervendo, forno) e irradiação (grelha, forno elétrico). A **panela de pressão** cozinha mais rápido porque a pressão elevada aumenta a temperatura de ebulição. A **garrafa térmica** minimiza as três formas de troca de calor. A escolha de materiais (metais condutores nas panelas, cabos isolantes) aplica propriedades térmicas. Pensar assim torna a cozinha um laboratório de Física.'] },
 { h:'Comunicação, saúde e meio ambiente', p:[
  'Na **comunicação**, as ondas eletromagnéticas transportam a informação: rádio, TV, celular, Wi-Fi, Bluetooth, GPS e satélites. A **fibra óptica** transmite dados por pulsos de luz, usando a reflexão total interna. A **tela sensível ao toque**, a **câmera** do celular (lentes e sensores), os **alto-falantes** (ímãs e bobinas) e os **microfones** (conversão de ondas sonoras em sinais elétricos) mostram aplicações combinadas de óptica, acústica e eletromagnetismo.',
  'Na **saúde**, a Física é essencial: **raios X** e **tomografia** para imagens, **ressonância magnética** com campos intensos, **ultrassom** para gestações e diagnóstico, **radioterapia** para tumores, **lasers** em cirurgias oftalmológicas, **termômetros** infravermelhos, **oxímetros** (luz que atravessa o dedo para medir a saturação de oxigênio) e **eletrocardiograma** (registro de sinais elétricos do coração). Entender os princípios ajuda a avaliar benefícios e riscos dessas tecnologias.',
  'No **meio ambiente**, a Física ajuda a entender o efeito estufa (absorção de infravermelho por gases), o aquecimento global, a camada de ozônio (filtro de ultravioleta), as fontes de energia e seus impactos, a poluição sonora e a radioatividade. Soluções passam por **energias renováveis** (solar, eólica, hidráulica), **eficiência energética**, **reciclagem** e tecnologias de captura de carbono. Questões do ENEM costumam trazer dilemas, em que é preciso comparar benefícios e impactos com base em dados.'] },
 { h:'Estratégias para as questões de contexto', p:[
  'Diante de uma questão contextualizada, comece lendo a pergunta final, para saber o que se pede. Em seguida, leia o texto e destaque dados numéricos, unidades e palavras-chave. Identifique o tema físico (calor, eletricidade, ondas, mecânica...) e recorde as relações básicas. Elabore um esquema ou desenho, se ajudar. Só então faça as contas, convertendo as unidades. Por fim, avalie se o resultado é plausível.',
  'Muitas vezes, o que se pede é uma **interpretação** de gráfico, tabela ou texto, sem cálculo extenso. Treine ler gráficos de posição, velocidade, potência e temperatura e extrair as informações pedidas. Aprenda as ordens de grandeza: a velocidade do som (340 m/s), da luz (3 × 10⁸ m/s), a aceleração da gravidade (10 m/s²), a potência de um chuveiro (milhares de watts), de uma lâmpada LED (poucos watts), a densidade da água (1 g/cm³).',
  'Por fim, tenha uma visão crítica e ética: a Física produz tecnologias que beneficiam a sociedade e também riscos, como a energia nuclear, as radiações e o consumo elevado de energia. O exame valoriza a capacidade de argumentar com base em evidências, e de considerar custos e benefícios, o que vai além de aplicar fórmulas. Estudar este tema é, em última análise, aprender a olhar o mundo com curiosidade e responsabilidade.'] }
]}
];
