/* Física: textos corridos, temas 13 a 15 */
module.exports = [
{ t:'Termodinâmica', txt:[
 { h:'Gases e variáveis de estado', p:[
  'A **Termodinâmica** estuda as relações entre calor, trabalho e energia. Começamos pelos gases, cujo estado é descrito por três variáveis: **pressão** (p), **volume** (V) e **temperatura absoluta** (T, em kelvin). Em um gás ideal, as partículas são consideradas pontuais e sem interação entre si, exceto nas colisões. Embora seja um modelo, descreve muito bem gases reais em condições comuns, como o ar à pressão atmosférica e à temperatura ambiente.',
  'A **equação de estado** do gás ideal é p·V = n·R·T, em que n é o número de mols e R é a constante universal dos gases (cerca de 8,3 J/mol·K). Para uma massa fixa de gás, a relação p·V/T permanece constante entre dois estados: p₁V₁/T₁ = p₂V₂/T₂. Dessa relação nascem as transformações particulares: **isotérmica** (T constante: p·V = constante, lei de Boyle), **isobárica** (p constante: V/T constante, lei de Charles) e **isovolumétrica** ou isocórica (V constante: p/T constante, lei de Gay-Lussac).',
  'Exemplos práticos: ao apertar a ponta de uma seringa fechada, o volume diminui e a pressão aumenta (isotérmica). Um balão de festa deixado ao sol se expande conforme o gás esquenta (aproximadamente isobárica). Uma lata de spray fechada, ao ser aquecida, tem a pressão aumentada com o volume fixo (isovolumétrica), o que torna perigoso deixá-la em locais quentes. Lembre sempre de usar a temperatura em kelvin.'] },
 { h:'Energia interna e trabalho de um gás', p:[
  'A **energia interna** (U) de um gás ideal monoatômico é a soma das energias cinéticas de suas partículas e depende **apenas da temperatura**: U = (3/2)·n·R·T. Se a temperatura aumenta, a energia interna aumenta; se a temperatura é constante (transformação isotérmica), a energia interna não varia. Isso é fundamental para analisar as transformações: toda variação de U está ligada a uma variação de T.',
  'O **trabalho** realizado por um gás ao se expandir é positivo (o gás empurra o ambiente e cede energia), e quando é comprimido, o trabalho é negativo (o ambiente realiza trabalho sobre o gás). Em uma transformação isobárica, τ = p · ΔV. No gráfico **pressão × volume (p × V)**, o trabalho é numericamente igual à **área** sob a curva. Na expansão, a área é positiva; na compressão, negativa. Em um ciclo (transformação que retorna ao estado inicial), o trabalho total é a área interna do ciclo.',
  'Exemplo: um gás sofre expansão isobárica a 2 × 10⁵ Pa, passando de 1 L (10⁻³ m³) a 3 L (3 × 10⁻³ m³). O trabalho é τ = 2 × 10⁵ × 2 × 10⁻³ = 400 J. Em uma transformação isovolumétrica, não há trabalho (ΔV = 0), e a variação de energia interna é igual ao calor trocado. Essas leituras de área em gráficos p×V são muito comuns em questões.'] },
 { h:'A primeira lei da Termodinâmica', p:[
  'A **primeira lei** é a lei da conservação da energia aplicada aos sistemas térmicos: ΔU = Q − τ, em que Q é o calor recebido pelo sistema e τ é o trabalho realizado **pelo** sistema. A variação de energia interna é igual ao calor absorvido menos o trabalho realizado. Se o gás recebe calor (Q > 0), pode aumentar sua energia interna, realizar trabalho, ou ambos. Se realiza trabalho (τ > 0) sem receber calor, usa sua própria energia, e esfria.',
  'Aplicando a lei às transformações: na **isotérmica**, ΔU = 0, logo Q = τ: todo o calor recebido é convertido em trabalho. Na **isovolumétrica**, τ = 0, logo ΔU = Q. Na **isobárica**, Q = ΔU + p·ΔV. Na **adiabática**, não há troca de calor (Q = 0), e ΔU = −τ: se o gás se expande, esfria; se é comprimido, esquenta. Esse é o princípio da bomba de bicicleta, que esquenta ao bombear ar rapidamente, e das nuvens, que se formam quando o ar sobe, expande e esfria.',
  'Ao resolver, siga uma ordem: identifique o tipo de transformação, avalie o sinal de ΔT (e, portanto, de ΔU), calcule o trabalho (área no gráfico ou p·ΔV), e aplique ΔU = Q − τ para achar o calor. Cuidado com as convenções de sinais, que variam em alguns livros. Em provas, o enunciado costuma deixar claro se o trabalho é feito pelo gás ou sobre o gás.'] },
 { h:'Máquinas térmicas e a segunda lei', p:[
  'Uma **máquina térmica** converte calor em trabalho operando em ciclos entre uma fonte quente (temperatura T₁) e uma fonte fria (temperatura T₂). Ela retira calor Q₁ da fonte quente, converte parte em trabalho τ e rejeita o restante, Q₂, para a fonte fria: τ = Q₁ − Q₂. O **rendimento** é η = τ/Q₁ = 1 − Q₂/Q₁. Motores de carro, usinas termelétricas e turbinas a vapor são exemplos. Nenhuma máquina térmica real tem rendimento de 100%.',
  'A **segunda lei da Termodinâmica** formaliza essa limitação. Em uma de suas formas (Kelvin-Planck), diz que é impossível construir uma máquina que converta integralmente calor em trabalho operando em ciclo. Em outra (Clausius), diz que o calor flui espontaneamente do corpo quente para o frio, e nunca o contrário, sem que se realize trabalho externo. Ela dá o sentido dos processos naturais: um café quente esfria no ambiente, mas o ambiente nunca esquenta o café espontaneamente.',
  'O **ciclo de Carnot** é o ciclo ideal que fornece o maior rendimento possível entre duas temperaturas: η = 1 − T₂/T₁, com temperaturas em kelvin. Uma máquina operando entre 600 K e 300 K tem rendimento máximo de 50%. Para aumentar o rendimento, é preciso elevar a temperatura da fonte quente ou reduzir a da fonte fria, o que explica a busca por materiais que resistam a altas temperaturas em turbinas e motores. Um rendimento maior que o de Carnot viola a segunda lei.'] },
 { h:'Refrigeradores, entropia e irreversibilidade', p:[
  'O **refrigerador** (e o ar-condicionado) é uma máquina térmica operando "ao contrário": retira calor da fonte fria (o interior) e o despeja na fonte quente (a cozinha ou o ambiente externo), com o auxílio de trabalho realizado por um compressor. Por isso, a parte de trás da geladeira esquenta. A eficiência é medida pela razão entre o calor retirado e o trabalho gasto. Uma geladeira com a porta aberta não esfria a cozinha: ela a aquece, pois a energia elétrica gasta se converte em calor.',
  'A **entropia** é uma grandeza associada à desordem e à dispersão da energia. A segunda lei afirma que, em um sistema isolado, a entropia nunca diminui: os processos espontâneos tendem ao aumento da desordem. Por isso, um copo que cai no chão e quebra não se recompõe sozinho, e o calor não passa do frio para o quente. Muitas transformações são **irreversíveis**, e isso define a "seta do tempo". Os processos reversíveis são idealizações, como o ciclo de Carnot.',
  'Em termos de energia, isso significa que, embora ela se conserve, sua **qualidade** se degrada: a energia concentrada, como a química do combustível, se transforma em energia térmica dispersa, difícil de reaproveitar. Isso explica a importância da eficiência energética e do reaproveitamento de calor em usinas e indústrias. Também mostra por que um "moto-contínuo" é impossível: uma máquina que cria energia do nada contraria a primeira lei; uma que converte todo o calor em trabalho, a segunda.'] },
 { h:'Como esse tema cai na prova', p:[
  'O ENEM costuma abordar a Termodinâmica com textos sobre motores, usinas, refrigeradores e fenômenos atmosféricos. As perguntas são, muitas vezes, conceituais: "por que o rendimento de uma máquina não pode ser 100%?", "o que acontece com a temperatura de um gás que se expande rapidamente?", "por que a geladeira aquece a cozinha?". Compreender as duas leis e seus significados físicos resolve a maioria dessas questões sem cálculos extensos.',
  'Nas questões numéricas, os cálculos mais comuns são rendimento de máquinas térmicas (η = τ/Q₁), trabalho a partir de gráficos p×V, aplicação da primeira lei e uso da equação de estado. Sempre confira se a temperatura está em kelvin e se as unidades de pressão e volume estão no SI quando se pede trabalho em joules. Em gráficos, identifique primeiro o tipo de transformação (isobárica, isotérmica, isovolumétrica ou adiabática) para escolher o raciocínio.',
  'Para revisar, memorize as duas leis em linguagem simples: a energia se conserva (primeira); o calor flui do quente para o frio e a conversão em trabalho nunca é total (segunda). Treine desenhando ciclos em diagramas p×V e identificando onde o gás recebe calor, realiza trabalho e rejeita calor. Esse hábito de "ler" o ciclo dá segurança, e a conexão com problemas reais, como o consumo de combustível e o impacto ambiental, torna o tema mais interessante.'] }
]},

{ t:'Ondas', txt:[
 { h:'O que é uma onda', p:[
  'Uma **onda** é uma perturbação que se propaga em um meio (ou no vácuo), transportando **energia sem transportar matéria**. Quando uma pedra cai na água, as ondas se espalham em círculos, mas uma folha que boia apenas sobe e desce, sem acompanhar a onda. Esse é o ponto central: a perturbação avança, e as partículas do meio apenas oscilam em torno de suas posições de equilíbrio. A energia é transmitida de ponto a ponto.',
  'Quanto à natureza, as ondas podem ser **mecânicas** ou **eletromagnéticas**. As mecânicas (som, ondas na água, ondas em cordas, ondas sísmicas) precisam de um meio material para se propagar, e não existem no vácuo. As eletromagnéticas (luz, rádio, micro-ondas, raios X) são perturbações de campos elétricos e magnéticos e se propagam inclusive no vácuo, a 300.000 km/s. A diferença é decisiva: no espaço sideral, não ouvimos explosões, mas vemos a luz das estrelas.',
  'Quanto à direção da vibração, as ondas são **transversais** (a vibração é perpendicular à propagação, como em uma corda ou na luz) ou **longitudinais** (a vibração é paralela à propagação, como o som no ar, com compressões e rarefações). Algumas, como as ondas na superfície da água, combinam os dois tipos. Reconhecer a natureza e a direção de vibração de uma onda ajuda a prever seu comportamento.'] },
 { h:'Elementos de uma onda e equação fundamental', p:[
  'Os principais elementos de uma onda periódica são: a **amplitude** (A), o máximo afastamento da posição de equilíbrio, relacionada à energia transportada; o **comprimento de onda** (λ), a distância entre duas cristas (ou vales) consecutivas; o **período** (T), o tempo de uma oscilação completa; e a **frequência** (f), o número de oscilações por segundo, medida em hertz (Hz), com f = 1/T. A velocidade da onda é v = λ · f.',
  'Esta é a **equação fundamental da ondulatória**: v = λ·f. A velocidade da onda depende do **meio** de propagação, enquanto a frequência depende da **fonte** e não muda quando a onda passa de um meio para outro. Assim, quando a onda muda de meio, a velocidade e o comprimento de onda mudam, mas a frequência permanece. Por exemplo, o som do apito de um trem tem a mesma frequência no ar e na água, mas se propaga mais rápido na água, e seu comprimento de onda é maior.',
  'Exemplo: uma onda com frequência de 50 Hz e comprimento de onda de 2 m tem velocidade v = 100 m/s. Em uma corda, a velocidade depende da tração e da densidade linear: cordas mais tensas e mais leves transmitem ondas mais rápido, como nos instrumentos musicais. No ENEM, é comum fornecer o gráfico da onda e pedir para identificar amplitude e comprimento de onda, e depois aplicar a equação fundamental com os valores lidos.'] },
 { h:'Reflexão, refração e difração', p:[
  'Quando uma onda encontra a fronteira entre dois meios, ocorrem fenômenos importantes. Na **reflexão**, a onda retorna ao meio original. Vale a lei: o ângulo de incidência é igual ao ângulo de reflexão. É por isso que ouvimos o eco (reflexão do som em superfícies distantes) e que a luz forma imagens em espelhos. Na reflexão, a frequência e a velocidade não mudam, pois o meio é o mesmo.',
  'Na **refração**, a onda passa a outro meio e muda sua velocidade, o que, em incidência oblíqua, provoca mudança de direção. A frequência se mantém, e a velocidade e o comprimento de onda variam. A refração explica por que um lápis parcialmente dentro d\'água parece "quebrado", e por que o fundo de uma piscina parece mais raso do que é. Para o som, a velocidade é maior em meios mais rígidos e densos, como a água e o aço, do que no ar.',
  'A **difração** é a capacidade de uma onda contornar obstáculos ou passar por fendas, e é mais pronunciada quando o tamanho da abertura ou do obstáculo é comparável ao comprimento de onda. Por isso, ouvimos uma conversa atrás de uma parede, pois as ondas sonoras (de comprimento de onda da ordem de metros) contornam os obstáculos, mas não enxergamos através dela, pois a luz (de comprimento de onda da ordem de décimos de micrômetro) não é difratada de forma perceptível. Também explica por que as ondas de rádio de maior comprimento alcançam regiões atrás de morros.'] },
 { h:'Interferência, ressonância e ondas estacionárias', p:[
  'A **superposição** de ondas é o princípio pelo qual duas ou mais ondas que se encontram em um ponto somam seus efeitos, e depois seguem seus caminhos sem se alterar. Quando as cristas coincidem, a amplitude aumenta (**interferência construtiva**); quando uma crista encontra um vale, elas se atenuam ou se anulam (**interferência destrutiva**). Fones de ouvido com cancelamento de ruído exploram a interferência destrutiva, emitindo ondas que se opõem ao ruído do ambiente.',
  'A **ressonância** ocorre quando um sistema é excitado por uma frequência igual à sua frequência natural de vibração, o que produz grande amplitude de oscilação. Exemplos: o balanço empurrado no ritmo certo, o vidro que se quebra com um som em determinada frequência, o rádio que sintoniza uma estação (o circuito entra em ressonância com a frequência da emissora) e a ponte de Tacoma, destruída pela vibração do vento em 1940. A ressonância é útil em instrumentos e em rádios, e perigosa em estruturas.',
  'As **ondas estacionárias** surgem da superposição de ondas de mesma frequência que se propagam em sentidos opostos, como em uma corda presa nas duas extremidades. Formam-se pontos que não vibram (**nós**) e pontos de máxima vibração (**ventres**). As frequências possíveis são os **harmônicos**: em uma corda de comprimento L presa nas duas pontas, λ = 2L/n, com n = 1, 2, 3, ..., e as frequências são múltiplos da fundamental. É assim que violões, violinos e flautas produzem notas diferentes.'] },
 { h:'Ondas no cotidiano e dicas de prova', p:[
  'As ondas estão por toda parte: o som da voz e da música, a luz do Sol, as ondas do mar, os terremotos (ondas sísmicas), o sinal de celular e Wi-Fi, o ultrassom em exames médicos, o sonar dos navios e o radar de trânsito. Em cada caso, vale perguntar: a onda é mecânica ou eletromagnética? É transversal ou longitudinal? Qual é a velocidade, a frequência e o comprimento de onda? Esse roteiro organiza o raciocínio.',
  'No **efeito Doppler**, a frequência percebida por um observador muda quando há movimento relativo entre a fonte e o observador. Quando a fonte se aproxima, o som é mais agudo (maior frequência percebida); quando se afasta, mais grave. É a explicação para a sirene de ambulância que "muda de tom" ao passar por nós, e a base do radar de velocidade e de exames de ultrassom Doppler. A frequência da fonte não muda; o que muda é a frequência recebida.',
  'Em questões, atenção a algumas armadilhas: confundir frequência com velocidade; esquecer que a frequência não muda com a refração; achar que o som se propaga no vácuo; e trocar crista e vale. Em gráficos de onda no espaço (y × x), lê-se o comprimento de onda; em gráficos no tempo (y × t), lê-se o período. Identificar o tipo de gráfico evita a maior parte dos erros e permite usar a equação v = λ·f com segurança.'] }
]},

{ t:'Acústica (som)', txt:[
 { h:'O som como onda mecânica longitudinal', p:[
  'O **som** é uma onda mecânica longitudinal produzida pela vibração de um corpo, como as cordas vocais, o alto-falante ou a corda de um violão. A vibração comprime e rarefaz o meio, gerando regiões de maior e menor pressão que se propagam. O som precisa de um meio material (sólido, líquido ou gasoso) para se propagar e **não se propaga no vácuo**. Em filmes de ficção científica, as explosões no espaço não deveriam ter som algum.',
  'A **velocidade do som** depende do meio e da temperatura. No ar, a 20 °C, é de cerca de 340 m/s (1.224 km/h). Na água, é cerca de 1.500 m/s, e em sólidos como o aço, mais de 5.000 m/s. Em geral, o som é mais rápido em sólidos do que em líquidos, e nestes do que em gases, por causa da maior rigidez e da proximidade das partículas. No ar, a velocidade aumenta com a temperatura.',
  'Uma aplicação cotidiana: para estimar a distância de uma tempestade, conte os segundos entre o relâmpago e o trovão. A luz chega quase instantaneamente, e o som, a 340 m/s. Se o intervalo é de 3 s, a distância é de cerca de 1 km. Esse tipo de raciocínio aparece em questões que pedem para calcular distâncias a partir do tempo entre a emissão e a recepção do som, como no eco e no sonar.'] },
 { h:'Qualidades do som: altura, intensidade e timbre', p:[
  'O som tem três qualidades fisiológicas. A **altura** indica se o som é grave ou agudo e depende da **frequência**: sons de maior frequência são mais agudos, e os de menor, mais graves. Não confunda altura com volume. Uma voz masculina costuma ser mais grave que a feminina porque as cordas vocais vibram em frequência menor. O ouvido humano percebe frequências de aproximadamente 20 Hz a 20.000 Hz; abaixo, é o **infrassom**, e acima, o **ultrassom**.',
  'A **intensidade** (ou "volume") está relacionada à **amplitude** da onda e à energia transportada. É medida em watts por metro quadrado, mas, como o ouvido percebe de forma logarítmica, usa-se o **nível sonoro** em decibéis (dB). Uma conversa normal tem cerca de 60 dB, o trânsito intenso, cerca de 80 dB, e um show de rock, mais de 100 dB. Exposição prolongada a níveis acima de 85 dB pode causar perda auditiva. A cada aumento de 10 dB, a intensidade é multiplicada por 10.',
  'O **timbre** é a qualidade que permite distinguir dois sons de mesma altura e intensidade emitidos por fontes diferentes, como a mesma nota tocada em um piano e em um violino. Depende da forma da onda, determinada pela combinação de harmônicos que cada fonte produz. É o timbre que nos permite reconhecer a voz de uma pessoa ou o instrumento musical. Essas três qualidades são o roteiro clássico para questões de acústica.'] },
 { h:'Reflexão do som, eco e reverberação', p:[
  'Quando o som encontra um obstáculo, pode ser refletido. Se o obstáculo está a certa distância, o som refletido pode ser ouvido como **eco**. Para que o ouvido distinga o eco do som original, é necessário um intervalo de pelo menos 0,1 s entre eles, o que corresponde a uma distância mínima de cerca de 17 m do obstáculo (o som vai e volta, percorrendo 34 m em 0,1 s). Em distâncias menores, o som refletido se mistura ao original, e ocorre a **reverberação**, que prolonga o som e pode prejudicar a inteligibilidade.',
  'O **sonar** (e o ecobatímetro) usa o eco para medir profundidades e localizar objetos submersos: emite um pulso sonoro e mede o tempo que ele leva para voltar. Se o pulso retorna em 2 s e o som se propaga a 1.500 m/s na água, a distância total percorrida é 3.000 m, e a profundidade é 1.500 m (metade). Morcegos e golfinhos usam o mesmo princípio, a **ecolocalização**, para navegar e caçar. O ultrassom em medicina emprega a reflexão de ondas de alta frequência nos tecidos do corpo para formar imagens.',
  'A acústica de ambientes (teatros, estúdios, salas de aula) busca controlar a reflexão e a absorção do som. Materiais porosos, como espuma, cortinas e carpetes, absorvem o som e reduzem a reverberação; superfícies duras e lisas, como vidro e concreto, refletem. Em salas de concerto, o formato e os revestimentos são projetados para que o som chegue bem a todos. Em locais ruidosos, como fábricas, painéis absorventes protegem a audição dos trabalhadores.'] },
 { h:'Fontes sonoras, instrumentos e ressonância', p:[
  'Os instrumentos musicais produzem som por vibrações de cordas, colunas de ar ou membranas. Nos **instrumentos de corda**, a frequência fundamental depende do comprimento, da tração e da densidade da corda: cordas mais curtas, mais tensas e mais leves produzem sons mais agudos. É por isso que, ao pressionar a corda do violão em diferentes trastes, mudamos o comprimento vibrante e, portanto, a nota. Nos **instrumentos de sopro**, a coluna de ar vibra, e a frequência depende do comprimento do tubo: quanto mais longo, mais grave.',
  'Nos tubos sonoros, formam-se ondas estacionárias de som. Em um tubo aberto nas duas extremidades, o comprimento L abriga múltiplos de meio comprimento de onda (f = n·v/2L). Em um tubo fechado em uma extremidade, só ocorrem harmônicos ímpares (f = n·v/4L, com n ímpar). Essas diferenças explicam as variações de timbre entre instrumentos como flauta e clarinete, e como o tubo de órgão produz suas notas.',
  'A **ressonância** acústica ocorre quando uma fonte vibra na frequência natural de outro corpo, que passa a vibrar com grande amplitude. A caixa de ressonância de um violão amplifica o som das cordas, e uma taça de vidro pode se quebrar se for exposta a um som intenso na sua frequência natural. Também se aplica ao ouvido humano: a cóclea tem regiões que ressoam em frequências diferentes, permitindo distinguir os sons.'] },
 { h:'Efeito Doppler, poluição sonora e saúde', p:[
  'O **efeito Doppler** é a mudança da frequência percebida quando há movimento relativo entre fonte e observador. Se a fonte se aproxima, as ondas chegam mais "comprimidas", e o som parece mais agudo; se se afasta, as ondas chegam mais "esticadas", e o som parece mais grave. Quem já ouviu uma ambulância passar notou a queda do tom da sirene ao se afastar. Radares de velocidade e ultrassons médicos usam o efeito Doppler para medir velocidades, como a do fluxo sanguíneo.',
  'A **poluição sonora** é o excesso de ruído no ambiente, e constitui um problema de saúde pública, especialmente em grandes cidades. Níveis elevados e prolongados causam perda auditiva, estresse, dificuldade de concentração, distúrbios do sono e problemas cardiovasculares. A OMS recomenda limites de exposição, e muitas cidades têm legislação sobre ruído (a chamada "lei do silêncio"). O uso de fones de ouvido em volume muito alto é uma das principais causas de perda auditiva em jovens.',
  'Estratégias de redução incluem fontes mais silenciosas, barreiras acústicas, isolamento de edificações e urbanismo que afaste atividades ruidosas das áreas residenciais. Para proteção individual, existem protetores auriculares. Em questões do ENEM, textos sobre ruído urbano costumam pedir a identificação de qualidades do som (intensidade em dB), de fenômenos (reflexão, absorção) ou de medidas que mitiguem o problema, e o raciocínio é quase sempre qualitativo.'] }
]}
];
