/* Física: textos corridos, temas 19 a 21 */
module.exports = [
{ t:'Corrente elétrica e circuitos', txt:[
 { h:'Corrente, tensão e resistência', p:[
  'A **corrente elétrica** é o movimento ordenado de cargas elétricas. Nos metais, são os elétrons livres; em soluções, os íons positivos e negativos. Sua **intensidade** (i) é a quantidade de carga que atravessa a seção de um condutor por unidade de tempo: i = Q/Δt, medida em **ampères (A)**, equivalente a 1 C/s. Por convenção, o sentido da corrente é o do movimento das cargas positivas (do potencial maior para o menor), oposto ao dos elétrons.',
  'Para que haja corrente em um circuito, é necessária uma **diferença de potencial (ddp)**, também chamada de tensão, medida em **volts (V)**. A ddp é fornecida por geradores, como pilhas, baterias e tomadas. Pense em uma analogia hidráulica: a tensão é como a diferença de altura que faz a água escoar, e a corrente, como o fluxo de água. Sem ddp, não há fluxo contínuo de cargas, mesmo que o fio seja ótimo condutor.',
  'A **resistência elétrica** (R) mede a oposição do material à passagem da corrente, em **ohms (Ω)**. A **primeira lei de Ohm** diz que, para condutores ôhmicos, U = R · i: a tensão é proporcional à corrente. Se um resistor de 10 Ω é ligado a uma bateria de 12 V, a corrente é 1,2 A. Quanto maior a resistência, menor a corrente para a mesma tensão. O gráfico U × i de um condutor ôhmico é uma reta que passa pela origem, e sua inclinação é a resistência.'] },
 { h:'Segunda lei de Ohm e resistividade', p:[
  'A resistência de um fio depende de suas características: R = ρ · L/A, a **segunda lei de Ohm**. Aqui, ρ é a **resistividade** do material (em Ω·m), L é o comprimento e A é a área da seção transversal. A resistência é maior em fios **longos** e **finos**, e menor em fios **curtos** e **grossos**. Por isso, as extensões elétricas longas e de fio fino esquentam mais, e as instalações de alta potência usam cabos grossos.',
  'A resistividade depende do material e da temperatura. Os metais, como cobre e prata, têm baixa resistividade, e por isso são usados em fios. Em metais, a resistividade **aumenta** com a temperatura. Já os isolantes têm resistividade muito alta, e os semicondutores (silício, germânio) têm valores intermediários que diminuem com a temperatura e podem ser controlados por impurezas, base de toda a eletrônica moderna.',
  'Uma aplicação importante é o **chuveiro elétrico**: no inverno, seleciona-se a posição "inverno", que usa um trecho menor do resistor, com menor resistência, o que aumenta a corrente e a potência dissipada (P = U²/R), esquentando mais a água. Na posição "verão", o trecho é maior, com maior resistência e menor potência. Esse é um dos casos clássicos de aplicação da segunda lei de Ohm em questões do ENEM, e é bom saber o raciocínio sem decorar.'] },
 { h:'Associação de resistores', p:[
  'Resistores podem ser associados em **série** ou em **paralelo**. Em **série**, estão encadeados, de modo que a **mesma corrente** passa por todos. A resistência equivalente é a soma: R_eq = R₁ + R₂ + ... A tensão total se divide entre eles, proporcionalmente à resistência de cada um. Se um deles queima, o circuito se interrompe, como nas antigas lâmpadas de árvores de Natal: queimada uma, apagavam todas.',
  'Em **paralelo**, os resistores estão ligados aos mesmos dois pontos, de modo que todos ficam submetidos à **mesma tensão**. A corrente total se divide entre os ramos, e passa mais corrente no de menor resistência. O inverso da resistência equivalente é a soma dos inversos: 1/R_eq = 1/R₁ + 1/R₂ + ... Para dois resistores, R_eq = R₁·R₂/(R₁ + R₂). A resistência equivalente é **menor** que a menor das resistências, pois novos caminhos facilitam a passagem da corrente.',
  'As instalações domésticas são em **paralelo**: cada aparelho recebe a mesma tensão da rede (127 V ou 220 V) e funciona independentemente dos outros. Se uma lâmpada queima, as demais continuam acesas. Em associações mistas, resolve-se por partes: calcula-se o equivalente de cada trecho em série ou paralelo, simplificando o circuito até restar um único resistor. Vale desenhar o circuito a cada passo, redesenhando-o de forma mais simples.'] },
 { h:'Geradores, medidores e segurança', p:[
  'Um **gerador** (pilha, bateria) fornece energia às cargas elétricas. Um gerador real possui uma **força eletromotriz** (fem, ε), que é a tensão ideal que ele poderia fornecer, e uma **resistência interna** r, que causa uma queda de tensão. A tensão nos terminais é U = ε − r·i. Por isso, ao exigir muita corrente de uma bateria, sua tensão cai e ela esquenta. Pilhas velhas têm resistência interna maior, o que explica por que um aparelho que "não funciona" com uma pilha usada pode funcionar com uma nova.',
  'Os **medidores** são o **amperímetro**, que mede corrente e é ligado **em série** com o elemento, e o **voltímetro**, que mede tensão e é ligado **em paralelo** com o elemento. O amperímetro ideal tem resistência muito baixa, para não interferir; o voltímetro ideal tem resistência muito alta, para não desviar corrente. Questões costumam pedir para identificar a ligação correta dos instrumentos em um circuito desenhado.',
  'Quanto à **segurança**, a corrente elétrica pode ser perigosa para o corpo humano. Correntes de poucos miliampères já causam choques dolorosos, e valores acima de cerca de 30 mA podem levar a parada respiratória ou fibrilação cardíaca. A resistência do corpo diminui com a pele molhada, de modo que o risco aumenta em ambientes úmidos. Por isso, existem dispositivos de proteção: **fusíveis** e **disjuntores** (que cortam o circuito em caso de excesso de corrente, evitando incêndios) e o **fio terra** (que conduz correntes de fuga para a terra, protegendo as pessoas).'] },
 { h:'Efeito Joule e usos da corrente', p:[
  'Quando a corrente passa por um condutor, parte da energia elétrica é convertida em calor: é o **efeito Joule**. A potência dissipada em um resistor é P = R·i² = U·i = U²/R. Esse efeito é útil em chuveiros, ferros de passar, torradeiras, secadores e aquecedores, em que a conversão em calor é o objetivo. Em outros casos, é indesejável: fios esquentando, perdas em linhas de transmissão e aquecimento de equipamentos eletrônicos.',
  'Nas **lâmpadas incandescentes**, o filamento esquenta até incandescer, mas apenas cerca de 5% da energia vira luz; o resto é calor, o que torna essas lâmpadas ineficientes. As **lâmpadas fluorescentes** e as de **LED** convertem muito mais energia em luz, com menor dissipação, e por isso consomem bem menos para a mesma luminosidade. A troca de lâmpadas é uma das formas mais simples de reduzir o consumo de energia em residências.',
  'Os **fusíveis** aproveitam o efeito Joule para a proteção: um fio de baixo ponto de fusão se derrete quando a corrente ultrapassa um limite, abrindo o circuito. Também há a **corrente contínua** (sentido constante, como a de pilhas e baterias) e a **alternada** (sentido que se inverte periodicamente, como a da rede elétrica no Brasil, com frequência de 60 Hz). Os aparelhos eletrônicos geralmente convertem a alternada em contínua por fontes internas.'] },
 { h:'Como resolver problemas de circuitos', p:[
  'Siga um roteiro. Primeiro, identifique o que está em série e o que está em paralelo e redesenhe o circuito de forma simples. Segundo, calcule a resistência equivalente, por partes. Terceiro, use a lei de Ohm para a corrente total, U = R_eq · i. Quarto, volte aos ramos: em série, a corrente é a mesma e a tensão se divide; em paralelo, a tensão é a mesma e a corrente se divide. Por fim, calcule potências e confirme se a soma das potências dissipadas é igual à potência fornecida pelo gerador.',
  'Atenção às unidades: converta mA em A, kΩ em Ω e minutos em segundos, se necessário. Verifique a coerência: a resistência equivalente em paralelo é sempre menor que a menor das resistências; a corrente total é a soma das correntes nos ramos em paralelo; e a soma das tensões em série é igual à tensão da fonte. Se algum desses testes falha, algo está errado.',
  'Em questões conceituais, não confunda corrente com tensão: a tensão "empurra", a corrente "flui". Um pássaro pousado em um fio de alta tensão não leva choque porque as duas patas estão em pontos de mesmo potencial (não há ddp), e portanto não passa corrente pelo corpo. Já tocar em dois pontos de potenciais diferentes é perigoso. Esse raciocínio resolve diversas pegadinhas do ENEM sobre segurança elétrica.'] }
]},

{ t:'Potência elétrica e consumo', txt:[
 { h:'Potência elétrica e a conta de luz', p:[
  'A **potência elétrica** indica a rapidez com que a energia elétrica é transformada em outra forma (calor, luz, movimento). É calculada por P = U · i, e, combinando com a lei de Ohm, também por P = R·i² e P = U²/R. A unidade é o **watt (W)**, que corresponde a 1 J/s. Um chuveiro de 5.000 W converte 5.000 J de energia elétrica em calor a cada segundo; uma lâmpada de 10 W converte 10 J por segundo em luz e calor.',
  'A **energia elétrica consumida** é o produto da potência pelo tempo: E = P · Δt. A unidade do SI é o joule, mas, na conta de luz, usa-se o **quilowatt-hora (kWh)**, a energia consumida por um aparelho de 1 kW (1.000 W) ligado por 1 hora. Como 1 kW = 1.000 J/s e 1 h = 3.600 s, 1 kWh = 3,6 × 10⁶ J. Um chuveiro de 5 kW ligado durante 20 minutos (1/3 de hora) consome 5/3 ≈ 1,67 kWh.',
  'Para calcular o custo, multiplica-se o consumo em kWh pela **tarifa** (reais por kWh). Se a tarifa é R$ 0,80/kWh, o banho de 20 minutos custa cerca de R$ 1,33. Se uma família toma 4 banhos por dia, durante 30 dias, o gasto mensal com o chuveiro será de cerca de R$ 160. Essa estimativa, que aparece em muitos enunciados, é só uma sequência de multiplicações, e um bom hábito é organizar os cálculos em uma tabela com aparelhos, potência, tempo de uso e consumo.'] },
 { h:'Lendo rótulos e comparando aparelhos', p:[
  'Os rótulos dos aparelhos informam a **potência nominal** (em W) e a **tensão de funcionamento** (127 V ou 220 V). A potência nominal é a que o aparelho consome quando ligado à tensão especificada. Se um aparelho de 127 V for ligado em 220 V, a corrente e a potência aumentam muito, e ele queima; se um de 220 V for ligado em 127 V, funciona com potência bem menor (proporcional ao quadrado da tensão, no caso de resistores). Por isso, é essencial conferir a tensão antes de ligar um aparelho.',
  'Duas coisas diferentes: a **potência** diz o ritmo de consumo de energia; o **consumo** depende também do tempo. Um aparelho de baixa potência ligado por muito tempo pode consumir mais que um de alta potência ligado por pouco tempo. Uma geladeira de 150 W ligada 24 horas por dia (ciclando o compressor) consome mais que um chuveiro de 5.000 W usado 10 minutos. Por isso, é importante considerar o **tempo de uso** na hora de avaliar os gastos.',
  'O **selo Procel** e a **etiqueta de eficiência energética** (classes A a G) informam quais aparelhos consomem menos para realizar a mesma função. Um aparelho classe A consome menos energia que um classe C de mesma capacidade. Em questões do ENEM, é comum comparar o consumo de aparelhos de diferentes classes ou potências, e calcular a economia ao trocar lâmpadas e eletrodomésticos antigos por modelos eficientes.'] },
 { h:'Corrente, disjuntores e fios', p:[
  'A corrente que um aparelho puxa da rede é i = P/U. Um chuveiro de 5.500 W em 220 V consome 25 A; em 127 V, o mesmo chuveiro precisaria de cerca de 43 A, o que exigiria fios muito grossos. É por isso que chuveiros de alta potência são geralmente ligados em 220 V, onde a corrente é menor. A escolha da bitola do fio e do disjuntor depende da corrente máxima esperada: fios muito finos para uma corrente alta esquentam e podem causar incêndios.',
  'O **disjuntor** desarma quando a corrente ultrapassa seu valor nominal. Em uma instalação com disjuntor de 20 A em 127 V, a potência máxima simultânea é 20 × 127 = 2.540 W. Se ligamos ao mesmo tempo um ferro de 1.500 W e um micro-ondas de 1.200 W, a corrente total é 2.700/127 ≈ 21,3 A, e o disjuntor desarma. Esse tipo de problema, que combina potência, tensão e corrente, é típico do ENEM. Para resolver, some as potências, divida pela tensão e compare com o limite.',
  'O mesmo raciocínio vale para **extensões e benjamins** ("T"): ligar vários aparelhos de alta potência em um mesmo ponto sobrecarrega a fiação e pode causar aquecimento perigoso. O **fusível** de um aparelho protege o equipamento. A **tomada** e o **plugue** de três pinos incluem o terra, que oferece um caminho seguro em caso de fuga de corrente. Instalações bem dimensionadas e seguras são parte do conteúdo cobrado, em termos de interpretação.'] },
 { h:'Eficiência, perdas e transmissão', p:[
  'Nenhum aparelho converte toda a energia elétrica em energia útil. O **rendimento** é a razão entre a energia útil e a energia consumida. Um motor elétrico pode ter 80% a 90% de rendimento; uma lâmpada incandescente, cerca de 5% (em luz); uma lâmpada LED, 20% a 30%. A diferença é energia que se "perde" em forma de calor. Conhecer o rendimento ajuda a escolher aparelhos mais econômicos, e a entender por que as lâmpadas incandescentes esquentam tanto.',
  'Na **transmissão de energia** a longas distâncias, as perdas por efeito Joule nos fios (P = R·i²) são minimizadas elevando a **tensão** em subestações, com transformadores. Para uma mesma potência transmitida (P = U·i), uma tensão maior significa corrente menor, e as perdas, proporcionais ao quadrado da corrente, são muito reduzidas. Por isso, as linhas de transmissão operam em centenas de milhares de volts, e, perto dos consumidores, a tensão é reduzida novamente.',
  'Os **transformadores** só funcionam com corrente alternada e alteram a tensão na razão do número de espiras: U₁/U₂ = N₁/N₂. Em um transformador ideal, a potência se conserva: U₁·i₁ = U₂·i₂. Carregadores de celular têm transformadores (ou fontes chaveadas) que reduzem a tensão da rede para poucos volts. As perdas no transporte e a eficiência dos aparelhos mostram por que a economia de energia é importante, tanto para o orçamento quanto para o meio ambiente.'] },
 { h:'Energia, meio ambiente e hábitos', p:[
  'O uso consciente da energia elétrica reduz custos e impactos ambientais. A maior parte da eletricidade brasileira vem de hidrelétricas, o que traz impactos sobre rios e ecossistemas; termelétricas emitem gases de efeito estufa; fontes eólica e solar crescem, com impacto menor, mas dependem de condições climáticas. Cada kWh poupado evita a necessidade de gerar mais energia, e é, portanto, a forma mais limpa de "geração".',
  'Hábitos simples fazem diferença: usar lâmpadas LED, desligar aparelhos em espera (stand-by, que consomem energia mesmo "desligados"), aproveitar a luz natural, usar o chuveiro na posição verão sempre que possível, acumular roupa para usar a máquina com carga completa, manter a geladeira com a vedação em ordem e longe de fontes de calor. O horário de uso também importa: em muitas regiões, há tarifas diferenciadas, com preços mais altos no horário de pico (início da noite).',
  'Nas questões, é comum que um texto apresente uma situação, como a troca de aparelhos, e peça a economia mensal em kWh ou em reais. O procedimento é sempre o mesmo: calcular o consumo antes e depois (potência × tempo), obter a diferença e multiplicar pela tarifa. Mantenha atenção às unidades (W ou kW, minutos ou horas) e ao número de dias considerado. Com essa rotina, as questões de consumo se tornam das mais seguras da prova.'] }
]},

{ t:'Magnetismo e eletromagnetismo', txt:[
 { h:'Ímãs e campo magnético', p:[
  'Os **ímãs** são corpos que atraem materiais como ferro, níquel e cobalto. Têm dois polos, **norte** e **sul**, e polos de mesmo nome se repelem, enquanto polos de nomes diferentes se atraem. Uma propriedade essencial: os polos magnéticos são **inseparáveis**. Se quebrarmos um ímã ao meio, cada pedaço se torna um novo ímã, com seus próprios polos norte e sul. Ao contrário das cargas elétricas, não se encontram polos isolados.',
  'Em torno de um ímã existe um **campo magnético**, região em que outros ímãs e materiais magnéticos sofrem forças. É representado por **linhas de campo**, que saem do polo norte e entram no polo sul **fora** do ímã, e fecham-se por dentro dele. Onde as linhas são mais densas, o campo é mais intenso, como perto dos polos. Com limalha de ferro sobre uma folha de papel, as partículas se alinham ao longo das linhas, tornando o campo visível.',
  'A **Terra** se comporta como um grande ímã, com polos magnéticos próximos aos polos geográficos. O polo **sul** magnético está perto do polo norte geográfico, e por isso o polo norte da agulha de uma **bússola** aponta para o norte geográfico: ele é atraído pelo polo sul magnético da Terra. A bússola é usada na navegação desde séculos. O campo magnético terrestre também protege o planeta do vento solar, desviando partículas carregadas e originando as auroras polares.'] },
 { h:'Corrente elétrica e campo magnético', p:[
  'Em 1820, Oersted observou que a agulha de uma bússola se desviava ao ser colocada perto de um fio com corrente elétrica. Foi a primeira evidência de que **correntes elétricas geram campos magnéticos**, unificando eletricidade e magnetismo. Em um fio retilíneo, as linhas de campo são circunferências concêntricas ao fio, e o sentido é dado pela **regra da mão direita**: com o polegar no sentido da corrente, os dedos curvados indicam o sentido do campo.',
  'Em uma **espira circular**, o campo no centro é perpendicular ao plano da espira. Em um **solenoide** (bobina, fio enrolado em hélice), o campo no interior é praticamente uniforme e semelhante ao de um ímã: a extremidade por onde as linhas saem é o polo norte. Se o solenoide tem um núcleo de ferro, o campo é muito mais intenso, formando um **eletroímã**. O campo cresce com a corrente e com o número de espiras.',
  'Os eletroímãs têm a vantagem de poder ser ligados e desligados. São usados em guindastes que levantam sucata de ferro, campainhas, fechaduras eletromagnéticas, trens de levitação magnética (maglev), alto-falantes e relés. Em questões, costuma-se pedir para identificar polos de um eletroímã a partir do sentido da corrente, ou para comparar a intensidade do campo mudando a corrente ou o número de espiras.'] },
 { h:'Força magnética sobre cargas e correntes', p:[
  'Uma carga elétrica q que se move com velocidade v em um campo magnético B sofre uma **força magnética** de módulo F = q · v · B · sen θ, em que θ é o ângulo entre v e B. A direção da força é **perpendicular** tanto à velocidade quanto ao campo (regra da mão direita ou da mão esquerda, conforme o sentido da carga). Se a carga está parada, ou se se move paralelamente ao campo (θ = 0), não há força magnética.',
  'Como a força é sempre perpendicular à velocidade, ela **não realiza trabalho** e, portanto, **não altera o módulo da velocidade**, apenas muda sua direção. Em um campo uniforme, uma partícula lançada perpendicularmente ao campo descreve uma **circunferência**, de raio R = m·v/(q·B). Esse resultado é o princípio do espectrômetro de massa e dos aceleradores de partículas, que usam campos magnéticos para curvar as trajetórias.',
  'Um fio com corrente i e comprimento L, em um campo B, sofre força F = B · i · L · sen θ. É o princípio do **motor elétrico**: espiras com corrente em um campo magnético sofrem forças em lados opostos, que produzem um torque e giram o eixo. Com um comutador, o sentido da corrente se inverte a cada meia volta, mantendo o giro. O mesmo princípio está nos alto-falantes e nos medidores de ponteiro (galvanômetros).'] },
 { h:'Indução eletromagnética e lei de Faraday', p:[
  'Em 1831, Faraday descobriu que um campo magnético **variável** pode gerar corrente elétrica. É a **indução eletromagnética**. Ao aproximar ou afastar um ímã de uma bobina conectada a um galvanômetro, surge uma corrente enquanto há movimento; com o ímã parado, não há corrente. O que importa é a variação do **fluxo magnético** (o "número de linhas de campo" que atravessa a bobina). A **lei de Faraday** afirma que a tensão induzida é proporcional à rapidez dessa variação.',
  'A **lei de Lenz** dá o sentido da corrente induzida: ela é tal que seu campo se **opõe** à variação do fluxo que a produziu. É uma consequência da conservação de energia: se a corrente induzida reforçasse a variação, teríamos energia surgindo do nada. Por isso, ao aproximar o polo norte de um ímã de uma espira, a corrente induzida cria um polo norte na face da espira voltada ao ímã, repelindo-o.',
  'A indução é a base da **geração de energia elétrica**: nos geradores (dínamos e alternadores), um ímã ou eletroímã gira dentro de bobinas (ou o contrário), produzindo tensão alternada. Nas usinas, turbinas movidas por água, vapor ou vento fornecem o movimento. O mesmo princípio funciona em **transformadores**, **carregadores por indução** de celulares, **fogões de indução** (que aquecem a panela por correntes induzidas) e **freios eletromagnéticos**, e é uma das descobertas mais importantes da história da ciência.'] },
 { h:'Transformadores, aplicações e como estudar', p:[
  'Os **transformadores** são dispositivos que alteram a tensão alternada usando indução. Têm duas bobinas, **primária** e **secundária**, enroladas em um núcleo de ferro. A tensão se relaciona ao número de espiras: Up/Us = Np/Ns. Se o secundário tem mais espiras, a tensão aumenta (elevador); se tem menos, diminui (abaixador). Em um transformador ideal, a potência se conserva, então, ao elevar a tensão, a corrente diminui na mesma proporção. Só funcionam com corrente alternada, pois dependem da variação do fluxo.',
  'Em aplicações do dia a dia, o magnetismo está nos cartões com tarja magnética, nos HDs, nos alto-falantes, nas bússolas, nos trens de levitação, nas ressonâncias magnéticas hospitalares, nos fones de ouvido e na proteção contra raios cósmicos. Também há a **magnetita**, ímã natural encontrado em rochas, e a orientação de animais, como aves migratórias e tartarugas, que percebem o campo magnético da Terra.',
  'Para estudar, associe cada fenômeno à sua causa: **corrente gera campo** (Oersted); **campo variável gera corrente** (Faraday); **campo exerce força sobre cargas em movimento** (força magnética). Pratique a regra da mão direita com desenhos e use o raciocínio qualitativo: quem aumenta, quem diminui, qual a oposição de Lenz. Essas ideias, mais do que fórmulas, são as que o ENEM cobra, geralmente em contextos de geração de energia, equipamentos e segurança.'] }
]}
];
