/* Física: textos corridos, temas 1 a 3 */
module.exports = [
{ t:'Grandezas e unidades (SI)', txt:[
 { h:'Medir é comparar', p:[
  'A Física descreve a natureza por meio de grandezas, isto é, propriedades que podem ser medidas: comprimento, massa, tempo, temperatura, velocidade, força, energia. Medir uma grandeza é compará-la com um padrão, chamado **unidade**. Quando dizemos que uma mesa tem 2 metros, estamos afirmando que ela cabe duas vezes no comprimento definido como 1 metro. Sem unidade, um número em Física não tem significado: "10" pode ser 10 segundos, 10 quilos ou 10 graus.',
  'Para que cientistas de todo o mundo se entendam, existe o **Sistema Internacional de Unidades (SI)**. Suas unidades de base mais usadas são o metro (m) para comprimento, o quilograma (kg) para massa, o segundo (s) para tempo, o ampère (A) para corrente elétrica, o kelvin (K) para temperatura e o mol para quantidade de matéria. Todas as demais unidades, como newton, joule e watt, são **derivadas** dessas.',
  'Outras unidades continuam em uso no dia a dia, como o quilômetro por hora, o litro, a caloria e o quilowatt-hora. O ENEM costuma misturá-las em um mesmo enunciado, e cabe ao candidato converter com cuidado. Uma boa prática é transformar tudo para o SI antes de aplicar qualquer fórmula, pois as fórmulas da Física foram escritas, em geral, supondo unidades do SI.'] },
 { h:'Grandezas escalares e vetoriais', p:[
  'Algumas grandezas ficam completamente determinadas por um número e uma unidade. São as **escalares**: massa, tempo, temperatura, energia, volume. Dizer que a temperatura é 25 °C ou que a massa é 70 kg já informa tudo. Outras exigem também **direção e sentido**, e são chamadas de **vetoriais**: deslocamento, velocidade, aceleração, força. Afirmar que uma força vale 10 N não basta: é preciso dizer para onde ela aponta.',
  'Os vetores são representados por setas. O comprimento da seta indica o módulo (a intensidade), e a orientação indica direção e sentido. Duas forças de mesmo módulo, mas de sentidos opostos, se cancelam; se têm o mesmo sentido, somam-se. Em situações com direções diferentes, a soma vetorial depende do ângulo entre os vetores, e pode ser feita pela regra do paralelogramo ou pela decomposição em componentes.',
  'Esse tema parece abstrato, mas é essencial: confundir distância percorrida (escalar) com deslocamento (vetorial) é um erro comum. Quem dá uma volta completa em uma pista e retorna ao ponto de partida percorreu uma distância grande, mas seu deslocamento foi nulo. Do mesmo modo, a velocidade média vetorial pode ser zero mesmo após uma longa viagem de ida e volta. Reconhecer a natureza de cada grandeza é metade do caminho para resolver o problema.'] },
 { h:'Prefixos, conversões e notação científica', p:[
  'Os **prefixos** do SI permitem expressar valores muito grandes ou muito pequenos sem escrever muitos zeros: quilo (k, 10³), mega (M, 10⁶), giga (G, 10⁹), centi (c, 10⁻²), mili (m, 10⁻³), micro (µ, 10⁻⁶), nano (n, 10⁻⁹). Assim, 5 km são 5 × 10³ m, e 3 ms são 3 × 10⁻³ s. Conhecer essa lista é indispensável, pois rótulos de equipamentos, capacidades de memória e distâncias astronômicas usam esses prefixos.',
  'Algumas conversões merecem atenção especial. Para passar de km/h para m/s, divide-se por 3,6; para o caminho inverso, multiplica-se por 3,6. Assim, 90 km/h correspondem a 25 m/s. Para áreas e volumes, os fatores de conversão são elevados ao quadrado e ao cubo: 1 m² = 10⁴ cm², 1 m³ = 10⁶ cm³ = 1.000 L. Esquecer dessa potência é uma fonte frequente de erro.',
  'A **notação científica** escreve números como produto de um valor entre 1 e 10 por uma potência de 10. A massa da Terra, de cerca de 6 × 10²⁴ kg, e o raio de um átomo, da ordem de 10⁻¹⁰ m, são exemplos. Nas contas, multiplicam-se os coeficientes e somam-se os expoentes. Para comparar valores muito diferentes, a **ordem de grandeza** (a potência de 10 mais próxima) fornece uma noção rápida de quantas vezes um é maior que o outro.'] },
 { h:'Análise dimensional e algarismos significativos', p:[
  'A **análise dimensional** usa as unidades como ferramenta de verificação. Em uma equação correta, os dois lados têm a mesma dimensão. A velocidade é comprimento sobre tempo, então uma expressão como v = d/t é coerente, ao passo que v = d · t não seria. Quando você esquece uma fórmula, as unidades ajudam a reconstruí-la: se a unidade de força é kg·m/s², a força deve ser massa vezes aceleração. Ao final de uma conta, conferir se a unidade da resposta é a esperada evita erros graves.',
  'Todas as medidas têm **incerteza**, pois nenhum instrumento é perfeito. Os **algarismos significativos** indicam a precisão de uma medida: escrever 2,50 m diz que a medida foi feita até os centésimos, ao passo que 2,5 m indica precisão até os décimos. Ao fazer contas, o resultado não pode parecer mais preciso do que os dados. Em provas, geralmente basta arredondar de forma coerente, mas é importante entender que os números da Física são aproximações da realidade.',
  'Também há erros sistemáticos e acidentais. Um relógio adiantado gera erro sistemático, sempre no mesmo sentido; variações na leitura de uma régua geram erros acidentais, que se compensam em média. Repetir a medida várias vezes e calcular a média reduz o efeito dos erros acidentais. Essa noção, ligada à estatística, aparece em questões de procedimentos experimentais.'] },
 { h:'Como esse tema cai no ENEM', p:[
  'Quase toda questão de Física exige alguma conversão de unidades ou interpretação de grandezas. Por isso, esse é o tema mais "transversal" da disciplina. Questões comuns pedem para converter velocidades, calcular consumo de energia em quilowatt-hora, interpretar potências de dez em textos científicos, ou identificar quais grandezas são vetoriais em um enunciado. A dificuldade quase nunca está na conta, mas na atenção às unidades.',
  'Uma estratégia segura é anotar os dados com unidades, converter tudo para o SI, escolher a fórmula, calcular e verificar a unidade do resultado. Se a unidade final não for a esperada, algo está errado. Outra estratégia é estimar a ordem de grandeza: a resposta é da ordem de 10⁻³ ou de 10³? Muitas alternativas diferem justamente por fatores de 10, e uma estimativa elimina as absurdas.',
  'Treine com situações do cotidiano. Quantos segundos tem um dia? Quantos metros por segundo corre um atleta de 36 km/h? Qual a massa de um litro de água? Quantos kWh consome um chuveiro de 5.000 W em 20 minutos? Responder a perguntas assim, de cabeça ou com poucas contas, desenvolve a intuição física e deixa a prova mais leve.'] }
]},

{ t:'Movimento uniforme', txt:[
 { h:'Posição, deslocamento e velocidade', p:[
  'A **Cinemática** descreve os movimentos sem se preocupar com suas causas. Para isso, precisamos de um **referencial**: um ponto ou sistema em relação ao qual descrevemos a posição. Um passageiro sentado em um ônibus está em repouso em relação ao veículo, mas em movimento em relação à rua. Repouso e movimento são conceitos relativos, e toda descrição de movimento exige a escolha do referencial.',
  'A **posição** (s) indica onde o corpo está sobre uma trajetória, a partir de uma origem. O **deslocamento** (Δs) é a variação de posição, s_final − s_inicial. Já a **velocidade média** é o deslocamento dividido pelo intervalo de tempo: vm = Δs/Δt. Se um carro vai do km 20 ao km 140 em 2 h, sua velocidade média é 120/2 = 60 km/h. A velocidade média não diz o que aconteceu em cada instante, apenas o resultado global da viagem.',
  'A **velocidade escalar** pode ser positiva ou negativa, conforme o movimento ocorra no sentido positivo ou negativo da trajetória. Em uma estrada, andar no sentido crescente dos marcos quilométricos é velocidade positiva; voltar é velocidade negativa. O sinal indica o sentido, e o módulo indica a rapidez. Distinguir essas ideias evita erros em questões que fazem o corpo "ir e voltar".'] },
 { h:'O movimento uniforme (MU)', p:[
  'No movimento uniforme, a velocidade é **constante**: o corpo percorre distâncias iguais em intervalos de tempo iguais. A equação horária da posição é s = s₀ + v·t, em que s₀ é a posição inicial. Se um ciclista parte do km 0 a 20 km/h, após 3 horas estará no km 60. É a descrição de uma reta crescente no gráfico de posição por tempo, e o que há de mais simples em Cinemática.',
  'Os gráficos são parte importante do tema. No gráfico **s × t**, o movimento uniforme é uma reta, e a **inclinação** da reta é a velocidade: quanto mais inclinada, maior a velocidade. Uma reta ascendente indica velocidade positiva; descendente, negativa; horizontal, repouso. No gráfico **v × t**, o MU é uma reta horizontal, e a **área** sob ela é o deslocamento: área = v · Δt.',
  'Esses dois resultados (inclinação do gráfico s×t igual à velocidade; área do gráfico v×t igual ao deslocamento) são ferramentas gerais, que valem também para movimentos variados. Praticá-las no MU é a melhor forma de aprendê-las. Em questões, basta ler os valores no gráfico, calcular a razão ou a área e interpretar o resultado no contexto do enunciado.'] },
 { h:'Encontros, ultrapassagens e movimento relativo', p:[
  'Problemas de encontro envolvem dois móveis. Para saber quando e onde se encontram, escreve-se a equação horária de cada um e igualam-se as posições. Se um carro parte do km 0 a 80 km/h e outro parte do km 200, em sentido contrário, a 120 km/h, as equações são s₁ = 80t e s₂ = 200 − 120t. Igualando, 80t = 200 − 120t, o que dá t = 1 h, e o encontro ocorre no km 80.',
  'Na **ultrapassagem**, o móvel mais rápido alcança o mais lento. Aqui é útil usar a **velocidade relativa**: quando dois móveis se movem no mesmo sentido, a velocidade relativa é a diferença das velocidades; em sentidos contrários, é a soma. Um trem de 200 m que ultrapassa um outro de 100 m, com diferença de velocidade de 10 m/s, precisa percorrer 300 m (a soma dos comprimentos) em relação ao outro, o que leva 30 s.',
  'Ao tratar de veículos longos, como trens e caminhões, não esqueça o comprimento dos objetos: a ultrapassagem só termina quando a traseira do mais rápido passa a frente do mais lento. Nesses problemas, desenhar a situação inicial e a final, marcando as distâncias envolvidas, é o que garante a resposta certa. A escolha entre usar equações horárias ou velocidade relativa depende do enunciado, e ambas dão o mesmo resultado.'] },
 { h:'Velocidade média em trechos diferentes', p:[
  'Um erro clássico é calcular a velocidade média como a média das velocidades. Isso só vale se o tempo gasto em cada trecho for igual. Quando as distâncias é que são iguais, é preciso calcular o tempo total. Se um carro percorre 100 km a 50 km/h e outros 100 km a 100 km/h, o tempo é 2 h + 1 h = 3 h, e a velocidade média é 200/3 ≈ 66,7 km/h, e não 75 km/h. Esse resultado é a **média harmônica**.',
  'O raciocínio correto é sempre: velocidade média = distância total ÷ tempo total. Calcule o tempo de cada trecho pela relação t = d/v, some e divida. Quando o enunciado fala em "metade do tempo" em cada velocidade, aí sim a média simples serve. Ler com atenção o que está sendo igual (distância ou tempo) é a chave.',
  'Também há questões de trânsito: o tempo economizado por aumentar a velocidade em um trecho é, quase sempre, bem menor do que se imagina. Ir a 100 km/h em vez de 80 km/h em um percurso de 40 km economiza 6 minutos (de 30 min para 24 min). Essas contas ajudam a refletir sobre excesso de velocidade e segurança, e aparecem em questões contextualizadas do ENEM.'] },
 { h:'Movimento circular uniforme e outras situações', p:[
  'O **movimento circular uniforme (MCU)** é aquele em que o corpo percorre uma circunferência com velocidade escalar constante. O período T é o tempo de uma volta, e a frequência f é o número de voltas por segundo, com f = 1/T. A velocidade escalar é v = 2πR/T, e a velocidade angular é ω = 2π/T = 2πf. Embora o módulo da velocidade seja constante, a direção muda a todo instante, e por isso há aceleração (centrípeta).',
  'Exemplos: ponteiros de relógio, rodas de bicicleta e satélites em órbita. Em engrenagens ligadas por correia ou por contato, a velocidade escalar dos pontos periféricos é a mesma, e a frequência é inversamente proporcional ao raio. Já em engrenagens acopladas no mesmo eixo, é a velocidade angular que é igual. Esses conceitos aparecem em bicicletas de marchas e em máquinas.',
  'Para resolver problemas, identifique o que é igual e o que varia, escreva as relações e substitua. Mantenha as unidades do SI: período em segundos, raio em metros, velocidade em m/s. Em muitos casos, um simples esboço do movimento esclarece o que é pedido. A familiaridade com o MU e o MCU é o alicerce para todo o estudo da Mecânica.'] }
]},

{ t:'Movimento uniformemente variado', txt:[
 { h:'Aceleração: a rapidez da mudança de velocidade', p:[
  'Quando a velocidade de um corpo muda, dizemos que ele possui **aceleração**. A aceleração média é a variação da velocidade dividida pelo intervalo de tempo: a = Δv/Δt, em m/s². Um carro que passa de 0 a 20 m/s em 5 s tem aceleração média de 4 m/s², o que significa que sua velocidade aumenta 4 m/s a cada segundo. Aceleração, portanto, não é "o quanto se anda", mas "o quanto a velocidade muda".',
  'No **movimento uniformemente variado (MUV)**, a aceleração é **constante**. A velocidade varia de forma linear com o tempo, e as equações são: v = v₀ + a·t; s = s₀ + v₀·t + (a·t²)/2; e a equação de Torricelli, v² = v₀² + 2·a·Δs, que relaciona velocidade e deslocamento sem a necessidade do tempo. Cada uma é útil conforme os dados do problema: escolher a equação sem a variável desconhecida economiza etapas.',
  'O sinal da aceleração e o da velocidade juntos indicam o tipo de movimento. Se têm o mesmo sinal, o módulo da velocidade aumenta (movimento **acelerado**); se têm sinais opostos, diminui (movimento **retardado**). Um carro freando, com velocidade positiva e aceleração negativa, está em movimento retardado. Esse é um ponto de atenção: aceleração negativa não significa necessariamente "desacelerar".'] },
 { h:'Gráficos do MUV', p:[
  'No gráfico **v × t**, o MUV é uma reta inclinada. A inclinação é a aceleração, e a **área** sob a reta é o deslocamento. Se a reta cruza o eixo do tempo, o corpo inverte o sentido do movimento nesse instante. Calcular o deslocamento é somar áreas de triângulos e retângulos (ou trapézios), e atenção: áreas abaixo do eixo contam como deslocamento negativo, e o deslocamento total é a soma algébrica.',
  'No gráfico **s × t**, o MUV é uma **parábola**. Se a aceleração é positiva, a parábola é voltada para cima; se negativa, para baixo. O vértice corresponde ao instante em que a velocidade é nula (o corpo "para" e inverte o sentido). A inclinação da reta tangente em cada ponto é a velocidade naquele instante, de modo que a curva mostra a velocidade variando de forma contínua.',
  'No gráfico **a × t**, o MUV aparece como uma reta horizontal, e a área sob ela é a variação de velocidade (Δv = a · Δt). Saber ler os três gráficos e relacioná-los é uma habilidade-chave. Em questões, geralmente é dado um gráfico e pede-se outra grandeza. Siga o roteiro: inclinação para obter a grandeza "derivada" e área para obter a grandeza "acumulada".'] },
 { h:'Frenagem, distância de parada e segurança', p:[
  'Uma das aplicações mais relevantes do MUV é a **frenagem**. Pela equação de Torricelli, com velocidade final nula, a distância de frenagem é d = v₀²/(2|a|). Isso mostra que a distância é proporcional ao **quadrado** da velocidade: dobrar a velocidade multiplica por quatro a distância necessária para parar. Um carro a 120 km/h precisa de uma distância 4 vezes maior que a 60 km/h, supondo a mesma desaceleração.',
  'A distância total de parada inclui também a **distância de reação**, percorrida durante o tempo que o motorista leva para perceber o perigo e acionar o freio, em que o movimento é uniforme. Se o tempo de reação é de 1 s e a velocidade é 20 m/s, o carro percorre 20 m antes mesmo de começar a frear. Cansaço, álcool e uso de celular aumentam o tempo de reação, o que aumenta de forma crítica a distância total.',
  'Esse tipo de questão aparece com frequência no ENEM em contextos de trânsito, pedindo para comparar distâncias, justificar limites de velocidade ou analisar o efeito do piso molhado, que reduz a desaceleração máxima. Para resolver, divida o problema em duas etapas, MU (reação) e MUV (frenagem), e some as distâncias.'] },
 { h:'Estratégias para resolver problemas de MUV', p:[
  'Primeiro, defina o sentido positivo e a origem. Depois, liste os dados com sinais: posição inicial, velocidade inicial, aceleração, tempo, e o que se pede. Escolha a equação que contém os dados que você tem e a incógnita que procura. Se o tempo não é dado nem pedido, use Torricelli; se a posição não interessa, use v = v₀ + at; se a questão envolve a posição, use a equação horária.',
  'Em problemas com dois móveis, escreva a equação da posição de cada um e iguale para saber quando se encontram. Se um parte do repouso com aceleração constante e outro se move com velocidade constante, o encontro pode ocorrer mais de uma vez (ou nenhuma). Resolva a equação do 2º grau e interprete as raízes: tempos negativos devem ser descartados.',
  'Revise sempre a coerência física: a velocidade encontrada é plausível? O tempo é positivo? A distância de frenagem faz sentido para um veículo real? Se sim, a resposta tem boa chance de estar correta. Pratique com situações familiares, como a aceleração de um carro de 0 a 100 km/h em 10 s (cerca de 2,8 m/s²) e a frenagem de uma bicicleta, para criar sensibilidade para as ordens de grandeza.'] }
]}
];
