/* Física: textos corridos, temas 10 a 12 */
module.exports = [
{ t:'Hidrostática', txt:[
 { h:'Densidade e pressão', p:[
  'A **Hidrostática** estuda os fluidos (líquidos e gases) em repouso. O primeiro conceito é a **densidade**, que relaciona a massa ao volume: d = m/V. A água tem densidade de 1 g/cm³ (ou 1.000 kg/m³), o óleo de cozinha, cerca de 0,9 g/cm³, e o ferro, cerca de 7,8 g/cm³. Materiais menos densos que a água flutuam nela; mais densos, afundam. Não confunda densidade com massa: um grande bloco de isopor tem muita massa e pouca densidade se comparado a um pequeno bloco de chumbo.',
  'O segundo conceito é a **pressão**, definida como a força perpendicular por unidade de área: p = F/A. A unidade no SI é o pascal (Pa), equivalente a 1 N/m². A mesma força gera pressões muito diferentes conforme a área. Por isso, uma faca afiada corta com facilidade (pequena área, grande pressão), e raquetes de neve e esquis evitam o afundamento (grande área, pequena pressão). Pregos têm ponta fina, e esteiras de tratores são largas, pelos mesmos motivos.',
  'Outras unidades de pressão aparecem no cotidiano: a atmosfera (atm), equivalente a cerca de 1,0 × 10⁵ Pa, o milímetro de mercúrio (mmHg), usado em medições de pressão arterial, e a libra por polegada quadrada (psi), usada em pneus. Conhecer algumas equivalências, como 1 atm ≈ 760 mmHg ≈ 10⁵ Pa, ajuda a fazer conversões nas questões e a compreender o significado dos valores.'] },
 { h:'Pressão em um líquido e o teorema de Stevin', p:[
  'Em um líquido em equilíbrio, a pressão aumenta com a profundidade. O **teorema de Stevin** diz que a diferença de pressão entre dois pontos de um líquido é Δp = d · g · Δh, em que d é a densidade do líquido, g a gravidade e Δh a diferença de profundidade. Na superfície, atua a pressão atmosférica; a uma profundidade h, a pressão total é p = p_atm + d·g·h. Para a água, a pressão aumenta cerca de 1 atm a cada 10 m de profundidade.',
  'Duas consequências importantes: a pressão depende da **profundidade**, e não do formato do recipiente nem da quantidade de líquido. Pontos na mesma horizontal, dentro de um mesmo líquido em equilíbrio, têm a mesma pressão. É o princípio dos **vasos comunicantes**: em recipientes ligados contendo o mesmo líquido, o nível se iguala. Se há líquidos imiscíveis de densidades diferentes, as alturas se ajustam de forma inversamente proporcional às densidades.',
  'Aplicações: as represas têm paredes mais espessas na base, onde a pressão é maior; os mergulhadores sentem a pressão nos ouvidos ao descer; os submarinos têm cascos reforçados para resistir à pressão em grandes profundidades; as caixas-d\'água ficam no alto para fornecer pressão adequada às torneiras. A pressão em um ponto também é transmitida igualmente em todas as direções do fluido.'] },
 { h:'Pressão atmosférica e o experimento de Torricelli', p:[
  'O ar também é um fluido, e seu peso exerce **pressão atmosférica**. Ao nível do mar, ela vale cerca de 1 atm. Torricelli demonstrou isso enchendo um tubo de mercúrio e invertendo-o em uma cuba: a coluna de mercúrio se estabilizou em cerca de 76 cm. A pressão atmosférica equilibra o peso dessa coluna, e daí vem a equivalência de 1 atm com 760 mmHg. O espaço acima do mercúrio ficou praticamente vazio (vácuo torricelliano).',
  'A pressão atmosférica diminui com a **altitude**, pois há menos ar acima. No alto de uma montanha, ela é menor, e isso afeta o corpo humano (falta de ar, ouvidos "tapados") e a cozinha: a água ferve a uma temperatura menor, e os alimentos demoram mais a cozinhar. A panela de pressão faz o contrário: aumenta a pressão interna e eleva a temperatura de ebulição da água, acelerando o cozimento.',
  'O ato de beber com canudinho também tem a ver com a pressão atmosférica. Ao sugar, reduz-se a pressão dentro do canudo, e a pressão atmosférica, que atua sobre a superfície do líquido no copo, empurra o líquido para cima. Ventosas, seringas e aspiradores funcionam por princípios semelhantes: uma região de menor pressão e a pressão externa maior produzindo o efeito.'] },
 { h:'Princípio de Pascal e máquinas hidráulicas', p:[
  'O **princípio de Pascal** afirma que um acréscimo de pressão em um ponto de um fluido incompressível em equilíbrio se transmite integralmente a todos os pontos do fluido e às paredes do recipiente. É a base da **prensa hidráulica**: dois êmbolos de áreas diferentes, A₁ e A₂, ligados por um fluido. Como a pressão é a mesma, F₁/A₁ = F₂/A₂. Aplicando uma pequena força no êmbolo de pequena área, obtém-se uma grande força no de grande área.',
  'É assim que funcionam elevadores de automóveis em oficinas, freios hidráulicos de carros, cadeiras de dentista e macacos hidráulicos. Se A₂ é 100 vezes maior que A₁, a força de saída é 100 vezes maior que a de entrada. Mas não há "milagre": o êmbolo menor percorre uma distância 100 vezes maior que o maior, de modo que o trabalho (força × distância) é o mesmo. A conservação da energia continua valendo, e a máquina apenas troca força por deslocamento.',
  'Nos freios hidráulicos, a força exercida sobre o pedal é transmitida pelo fluido a cada roda, multiplicando-se pelo uso de êmbolos de áreas diferentes. Uma bolha de ar no sistema atrapalha, pois o ar é compressível e "absorve" parte da pressão. Essa é a razão da purga dos freios. Questões do ENEM costumam pedir a razão entre forças em função das áreas, e o raciocínio de proporcionalidade é suficiente.'] },
 { h:'Empuxo e o princípio de Arquimedes', p:[
  'Todo corpo mergulhado em um fluido sofre uma força vertical, para cima, chamada **empuxo**. Pelo **princípio de Arquimedes**, o empuxo tem módulo igual ao **peso do fluido deslocado** pelo corpo: E = d_fluido · V_deslocado · g. Se o corpo está totalmente submerso, V_deslocado é o volume do corpo; se flutua parcialmente, é só o volume da parte imersa. É por isso que nos sentimos mais leves dentro d\'água.',
  'A comparação entre o peso (P) e o empuxo (E) determina o comportamento. Se E > P, o corpo sobe e flutua; se E = P, fica em equilíbrio (flutuando ou submerso); se E < P, afunda. Para um corpo maciço, isso equivale a comparar densidades: afunda se for mais denso que o fluido, e flutua se for menos denso. Em equilíbrio flutuando, a fração submersa é a razão entre as densidades: d_corpo/d_fluido. Um bloco de gelo (0,92 g/cm³) flutua na água com 92% do volume submerso.',
  'Por que navios de aço flutuam? Porque seu casco é oco: a densidade média do conjunto (aço, ar e carga) é menor que a da água, e ele desloca um grande volume de água, gerando empuxo suficiente. Submarinos controlam a flutuação enchendo e esvaziando tanques de lastro com água e ar. Balões e dirigíveis flutuam no ar por conterem gás menos denso que o ar. A água do mar, mais densa, também produz maior empuxo, razão pela qual boiamos mais facilmente no mar do que em piscinas.'] },
 { h:'Estratégias para resolver problemas', p:[
  'Em questões de pressão, identifique se a pergunta é sobre pressão **manométrica** (apenas a do líquido) ou **absoluta** (incluindo a atmosfera). Converta unidades para o SI: g/cm³ para kg/m³ (multiplique por 1.000), cm para m, e atm para Pa. Use a fórmula de Stevin com cuidado ao identificar a profundidade (distância vertical até a superfície livre), e não o comprimento do trajeto.',
  'Em problemas de empuxo, desenhe as forças: peso para baixo e empuxo para cima, e, se houver, tração de fio ou outra força. Escreva a condição de equilíbrio e calcule. Se o corpo flutua, E = P; se está preso por um fio no fundo, E = P + T. Uma pergunta frequente é "o que acontece com o nível da água quando um gelo derrete?". Como o gelo flutuante desloca o seu próprio peso em água, o nível não muda quando ele derrete.',
  'Treine com situações do cotidiano: o ovo que flutua na água salgada e afunda na doce, o iceberg com 90% do volume submerso, o balão de gás, o peixe que ajusta a bexiga natatória, a boia de caixa-d\'água. Em cada uma, identifique as densidades envolvidas e o equilíbrio de forças. O raciocínio qualitativo ("é mais denso ou menos denso?") resolve muitas questões do ENEM sem nenhum cálculo.'] }
]},

{ t:'Temperatura e calor', txt:[
 { h:'Temperatura: o que ela mede', p:[
  'A **temperatura** é uma medida do grau de agitação das partículas (átomos e moléculas) de um corpo. Quanto mais agitadas, maior a temperatura. Ela indica se um corpo está "quente" ou "frio" em relação a outro, mas é uma grandeza distinta do calor. A temperatura é medida por termômetros, que usam alguma propriedade que varia regularmente com ela, como a dilatação do mercúrio ou do álcool, ou a resistência elétrica de certos materiais.',
  'As escalas mais usadas são a **Celsius** (°C), com 0 °C para o ponto de fusão do gelo e 100 °C para o de ebulição da água ao nível do mar; a **Kelvin** (K), a escala absoluta do SI, em que o zero (0 K) corresponde ao estado de mínima agitação térmica, equivalente a −273 °C; e a **Fahrenheit** (°F), usada nos Estados Unidos, em que a água congela a 32 °F e ferve a 212 °F. As conversões são T(K) = T(°C) + 273 e (°F − 32)/9 = °C/5.',
  'Uma observação importante: variações de temperatura em Celsius e em Kelvin são numericamente iguais (Δ°C = ΔK), e em Fahrenheit, a variação é 1,8 vez maior. Em fórmulas de gases, a temperatura deve estar sempre em kelvin. Essa é uma fonte frequente de erro, e é bom adotar o hábito de converter para kelvin antes de qualquer cálculo que envolva proporcionalidade com a temperatura.'] },
 { h:'Calor: energia em trânsito', p:[
  'O **calor** é a energia térmica transferida de um corpo para outro em razão de uma diferença de temperatura. Ele flui espontaneamente do corpo mais quente para o mais frio, até que as temperaturas se igualem, situação chamada de **equilíbrio térmico**. Corpos não "possuem" calor: possuem energia interna. Calor é a energia em trânsito. Quando dizemos que "uma pessoa está com calor", usamos a linguagem comum, mas a Física distingue as duas ideias.',
  'A unidade de calor no SI é o joule (J), mas a **caloria** (cal) continua popular: 1 cal ≈ 4,18 J, e é a quantidade de calor necessária para elevar em 1 °C a temperatura de 1 g de água. As "calorias" dos alimentos são, na verdade, quilocalorias (kcal), ou seja, 1.000 cal. Uma barra de chocolate de 250 kcal fornece cerca de 1.045 kJ de energia, que o corpo converte por metabolismo.',
  'Quando dois corpos em temperaturas diferentes são colocados em contato e isolados do ambiente, o calor cedido pelo mais quente é igual ao absorvido pelo mais frio. Em termos de balanço, a soma de todos os calores trocados é zero: ΣQ = 0. Esse princípio permite calcular a temperatura final de misturas, como água quente e fria, ou de um metal quente mergulhado em água, e é a base dos problemas de calorimetria.'] },
 { h:'Calor sensível e calor específico', p:[
  'O **calor sensível** é aquele que provoca variação de temperatura sem mudança de estado físico. Calcula-se por Q = m · c · ΔT, em que m é a massa, c é o **calor específico** da substância e ΔT é a variação de temperatura. O calor específico indica quanta energia é necessária para variar em 1 °C a temperatura de 1 g da substância. A água tem um valor alto, c = 1 cal/g·°C (4,18 J/g·K), o que significa que ela "demora" a esquentar e a esfriar.',
  'Essa propriedade explica fenômenos do cotidiano: a areia da praia esquenta rapidamente durante o dia e esfria rápido à noite, enquanto o mar muda de temperatura devagar; por isso, as cidades litorâneas têm menor amplitude térmica que as do interior, e surgem as brisas (a brisa marítima durante o dia e a terrestre à noite). A água também é usada como fluido refrigerante em motores e sistemas de aquecimento, justamente por absorver muito calor com pequena variação de temperatura.',
  'A **capacidade térmica** C = m · c indica quanta energia é necessária para variar em 1 °C a temperatura de um corpo inteiro. Dois corpos de mesma massa e materiais diferentes absorvem quantidades diferentes de calor para o mesmo aquecimento. Em problemas de misturas, escreva Q = m·c·ΔT para cada corpo, com o sinal correto (positivo para ganho, negativo para perda), some e iguale a zero para encontrar a temperatura de equilíbrio.'] },
 { h:'Calor latente e mudanças de estado', p:[
  'Durante uma **mudança de estado** (fusão, solidificação, vaporização, condensação), a substância absorve ou cede calor sem variar a temperatura. Esse é o **calor latente**: Q = m · L, em que L é o calor latente específico da transformação. Para a água, o calor latente de fusão é cerca de 80 cal/g, e o de vaporização, cerca de 540 cal/g. Para derreter 100 g de gelo a 0 °C, são necessárias 8.000 cal, sem que a temperatura mude durante o processo.',
  'No gráfico de temperatura em função do calor fornecido (ou do tempo, com fonte de potência constante), as mudanças de estado aparecem como **patamares** horizontais, e os trechos inclinados correspondem ao calor sensível em cada fase. A inclinação de cada trecho é menor quanto maior o calor específico. Interpretar esse gráfico é muito comum no ENEM: identificar em que trecho há mudança de estado e comparar calores específicos.',
  'Esse conceito explica por que o suor refresca: a evaporação absorve calor do corpo. Também explica por que um copo de gelo mantém a bebida gelada (o gelo absorve muito calor ao derreter) e por que queimaduras de vapor são mais graves que as de água quente na mesma temperatura (o vapor libera muito calor ao condensar). Geladeiras e ar-condicionados usam a vaporização de um fluido para retirar calor do ambiente interno.'] },
 { h:'Dilatação térmica', p:[
  'A maioria dos materiais **dilata** (aumenta de tamanho) quando aquecidos e contrai quando esfriados, pois o aumento da agitação das partículas as afasta umas das outras. Para sólidos, a **dilatação linear** é ΔL = L₀ · α · ΔT, em que α é o coeficiente de dilatação linear do material. A dilatação superficial e a volumétrica seguem leis semelhantes, com coeficientes de aproximadamente 2α e 3α. Metais dilatam mais que o vidro e a cerâmica, por exemplo.',
  'As aplicações e os cuidados são numerosos. Pontes e viadutos têm **juntas de dilatação** para que as estruturas possam se expandir sem rachar. Trilhos de trem são assentados com pequenos espaços. Fios elétricos são instalados com folga para que não se rompam no frio. O termostato bimetálico, formado por duas lâminas de metais com coeficientes distintos, se curva com o aquecimento e abre ou fecha circuitos em ferros de passar e geladeiras.',
  'A água tem um comportamento anômalo: entre 0 °C e 4 °C, ao ser aquecida, ela contrai, atingindo densidade máxima a 4 °C. Por isso, em lagos de regiões frias, o gelo se forma na superfície e a água mais densa (a 4 °C) fica no fundo, permitindo que a vida aquática sobreviva durante o inverno. É um caso clássico, frequente no ENEM, de como uma propriedade física tem consequências ecológicas.'] },
 { h:'Como resolver questões de calorimetria', p:[
  'Comece identificando os corpos envolvidos, as massas, as temperaturas iniciais e se há mudança de estado. Escreva o calor trocado em cada etapa: sensível (m·c·ΔT) e latente (m·L). Some todos os calores, considerando que a soma é zero se o sistema é isolado. Resolva a equação para a incógnita (geralmente a temperatura final, a massa ou o calor específico). Verifique se a temperatura final está entre as temperaturas iniciais, o que é um bom teste de coerência.',
  'Atenção a detalhes: o calor específico do gelo (cerca de 0,5 cal/g·°C) é diferente do da água líquida (1 cal/g·°C); a fusão do gelo ocorre a 0 °C e a ebulição da água, a 100 °C (ao nível do mar). Ao misturar gelo e água, verifique antes se todo o gelo derrete ou se parte dele permanece, o que define se a temperatura final é 0 °C ou maior.',
  'Em questões conceituais, não confunda calor e temperatura: um copo de água fervendo e uma piscina de água morna podem ter calor muito diferente, mas a temperatura mais alta é a do copo. Quem tem maior energia térmica total é a piscina, por ter muito mais massa. Esse tipo de pegadinha é frequente e se resolve ao lembrar que a temperatura mede a agitação média, e o calor é a energia transferida.'] }
]},

{ t:'Propagação do calor', txt:[
 { h:'Os três processos de propagação', p:[
  'O calor pode ser transmitido de três maneiras: **condução**, **convecção** e **irradiação**. Em muitas situações do cotidiano, os três ocorrem ao mesmo tempo, mas um deles costuma predominar. Entender qual é qual é fundamental para explicar desde o funcionamento de uma panela até o aquecimento do planeta, e os três aparecem repetidamente em questões do ENEM, geralmente em contextos práticos.',
  'Na **condução**, a energia é transferida de partícula a partícula, por agitação, sem que a matéria se desloque. Ocorre principalmente nos sólidos. Quando você coloca uma colher de metal em uma panela quente, a colher esquenta por condução. Os **metais** são bons condutores, pois possuem elétrons livres que carregam energia; **madeira**, **plástico**, **isopor** e **ar** são maus condutores, chamados **isolantes térmicos**. Por isso os cabos de panelas costumam ser de madeira ou plástico.',
  'Na **convecção**, a energia é transportada pelo próprio movimento do fluido (líquido ou gás). O fluido aquecido torna-se menos denso e sobe, enquanto o mais frio e denso desce, formando **correntes de convecção**. Ocorre em líquidos e gases, e não em sólidos. Já a **irradiação** é a transferência por ondas eletromagnéticas, principalmente infravermelhas, e **não precisa de meio material**. É assim que o calor do Sol chega à Terra através do vácuo.'] },
 { h:'Condução: lei de Fourier e isolantes', p:[
  'A quantidade de calor conduzida por um material em um intervalo de tempo depende da diferença de temperatura, da área, da espessura e da **condutividade térmica** k do material. Pela **lei de Fourier**, o fluxo de calor é Φ = k · A · ΔT/L. Quanto maior a área e a diferença de temperatura, maior o fluxo; quanto maior a espessura L, menor. Paredes grossas e de material isolante dificultam a passagem do calor, e é isso que se busca ao isolar casas e geladeiras.',
  'A sensação de "frio" ao tocar objetos é muitas vezes enganosa. Um piso de cerâmica parece mais frio que um tapete, mesmo na mesma temperatura, porque a cerâmica conduz melhor o calor e retira calor da mão mais rápido. O metal parece mais frio que a madeira pelo mesmo motivo. Nosso tato percebe a **taxa de troca de calor**, e não a temperatura em si. Esse é um exemplo clássico de questão conceitual do ENEM.',
  'Os isolantes funcionam bem principalmente por reter ar. A lã, as penas, o isopor e a espuma contêm muitas bolsas de ar parado, que é um mau condutor. Por isso, o agasalho de lã esquenta: não por produzir calor, mas por dificultar a saída do calor do corpo. Janelas de vidro duplo, com uma camada de ar ou gás entre os vidros, melhoram o isolamento térmico de ambientes, reduzindo o consumo de energia com aquecimento e refrigeração.'] },
 { h:'Convecção: correntes e brisas', p:[
  'A convecção explica por que os aparelhos de ar-condicionado são instalados na parte alta das paredes (o ar frio, mais denso, desce e resfria o ambiente) e os aquecedores ficam próximos ao chão (o ar quente sobe e aquece o ambiente). A geladeira tem o congelador na parte superior, pois o ar frio desce e resfria os alimentos abaixo. Na panela, a água do fundo, aquecida, sobe, e a água fria desce, o que homogeneíza a temperatura.',
  'Na natureza, a convecção é responsável pelos **ventos** e pelas **brisas**. Durante o dia, a terra aquece mais rápido que o mar (menor calor específico). O ar sobre a terra, aquecido, sobe, e o ar mais frio do mar vem ocupar seu lugar: é a **brisa marítima**. À noite, a terra esfria mais rápido, e a situação se inverte, com a **brisa terrestre**. As correntes marítimas e as grandes circulações atmosféricas também se devem a diferenças de temperatura e densidade.',
  'A convecção também aparece em fenômenos como a **inversão térmica**, em que uma camada de ar mais quente se instala sobre uma de ar mais frio, impedindo a subida do ar poluído e piorando a qualidade do ar nas cidades, e nas correntes do manto terrestre, que movem as placas tectônicas. Em todas essas situações, o raciocínio é o mesmo: o fluido mais quente é menos denso e sobe, o mais frio é mais denso e desce.'] },
 { h:'Irradiação, corpo negro e efeito estufa', p:[
  'Todo corpo com temperatura acima do zero absoluto emite energia por ondas eletromagnéticas, principalmente infravermelho. Quanto maior a temperatura, maior a intensidade irradiada. A irradiação não precisa de meio material e se propaga à velocidade da luz. Ao se aproximar de uma fogueira, a pessoa sente o calor mesmo que o ar ao redor esteja frio: parte do calor chega por irradiação.',
  'A forma como a radiação interage com a superfície depende da cor e do acabamento. Superfícies **escuras e foscas** absorvem mais radiação (e também emitem mais), enquanto as **claras e polidas** refletem mais. Por isso, roupas claras são preferidas em dias quentes, telhados brancos reduzem a temperatura interna, e a parte externa de caldeiras e painéis de aquecimento solar é escura. A **garrafa térmica** reduz as três formas de troca de calor: vácuo entre as paredes (sem condução nem convecção) e superfícies espelhadas (que refletem a irradiação).',
  'O **efeito estufa** é um fenômeno natural em que gases como o vapor-d\'água, o gás carbônico (CO₂) e o metano (CH₄) absorvem parte da radiação infravermelha emitida pela superfície terrestre e a reemitem, mantendo o planeta mais quente do que seria sem eles. Sem esse efeito, a temperatura média da Terra seria cerca de 33 °C menor. O problema é a **intensificação** desse efeito pela emissão excessiva de gases pelas atividades humanas, que contribui para o aquecimento global.'] },
 { h:'Aplicações no cotidiano e na tecnologia', p:[
  'Diversos equipamentos aplicam esses conceitos. A **estufa de plantas** funciona porque o vidro deixa passar a luz solar (visível) e retém parte do calor, evitando a saída do ar aquecido (supressão da convecção) e retendo a radiação infravermelha. O **aquecedor solar** usa tubos escuros para absorver radiação, e a água aquecida sobe por convecção ao reservatório. O **micro-ondas** aquece alimentos por radiação de micro-ondas, que faz as moléculas de água vibrarem, o que é um fenômeno diferente da irradiação térmica comum.',
  'Em construções, o conforto térmico depende de materiais isolantes, cores claras, ventilação cruzada e proteção contra o Sol. Em climas quentes, usam-se telhados refletivos e pátios internos para promover a convecção; em climas frios, isolamento reforçado e vidros duplos. Em vestuário, tecidos escuros no inverno absorvem mais radiação, e os claros no verão refletem mais. Todo esse conhecimento prático tem base nos três processos de propagação do calor.',
  'No corpo humano, o calor é perdido por condução (contato com superfícies), convecção (movimento do ar, o que explica a sensação térmica do vento), irradiação (principalmente infravermelho) e evaporação (suor). Em ambientes frios, o corpo reduz as perdas contraindo os vasos da pele e arrepiando os pelos; em ambientes quentes, aumenta o suor. Essa integração com a Biologia é comum em questões interdisciplinares do ENEM.'] },
 { h:'Como identificar o processo em uma questão', p:[
  'Para decidir qual processo de propagação está em jogo, faça três perguntas. Há contato direto entre sólidos, com o calor passando pelo material? Condução. Há um fluido (líquido ou gás) circulando por diferença de densidade? Convecção. O calor chega sem meio material, ou por ondas, ou há referência à cor e ao brilho das superfícies? Irradiação. Lembre-se de que, no vácuo, só a irradiação ocorre, e que, nos sólidos, só ocorre condução (e irradiação nas superfícies).',
  'Em questões que explicam o funcionamento de objetos (garrafa térmica, estufa, geladeira, fogão), analise cada componente e identifique qual processo ele busca minimizar ou maximizar. Se a questão pede para "reduzir a perda de calor", pense em isolantes, vácuo e superfícies refletoras. Se pede para "aumentar a troca de calor", pense em metais, superfícies escuras e grandes áreas, como nas aletas de um radiador.',
  'Um cuidado final é distinguir **calor** de **sensação térmica**, e **temperatura** de **condutividade**. A sensação de frio ou de calor depende da rapidez com que o corpo troca calor com o ambiente, e não apenas da temperatura. Com isso em mente, boa parte das questões de propagação do calor, que parecem difíceis pelo enunciado longo, se resolve com raciocínio qualitativo simples.'] }
]}
];
