/* Física: textos corridos, temas 7 a 9 */
module.exports = [
{ t:'Trabalho, energia e potência', txt:[
 { h:'Trabalho de uma força', p:[
  'Em Física, **trabalho** (τ) é a medida da energia transferida por uma força quando ela desloca um corpo. Não tem a ver com esforço no sentido cotidiano: segurar uma mala pesada parada, por exemplo, cansa os músculos, mas, para a Física, a força não realiza trabalho, pois não há deslocamento. A definição é τ = F · d · cosθ, em que F é a intensidade da força, d é o deslocamento e θ é o ângulo entre a força e o deslocamento. A unidade é o **joule (J)**, equivalente a 1 N·m.',
  'O sinal do trabalho informa o efeito: se a força tem componente no mesmo sentido do deslocamento (θ < 90°), o trabalho é **positivo** e a força fornece energia ao corpo; se a componente é contrária (θ > 90°), o trabalho é **negativo** e a força retira energia, como o atrito; se a força é perpendicular ao deslocamento (θ = 90°), o trabalho é **nulo**, como a normal em um piso horizontal ou a força centrípeta em um movimento circular.',
  'Quando a força não é constante, o trabalho é a **área** sob o gráfico da força em função da posição. Em uma mola, a força elástica varia de forma linear com a deformação (F = k·x), e o trabalho para esticá-la é a área de um triângulo: τ = k·x²/2. Esse resultado liga o conceito de trabalho à energia armazenada na mola, e é um dos casos de integração gráfica mais cobrados.'] },
 { h:'Energia cinética e potencial', p:[
  'A **energia** é a capacidade de realizar trabalho, e se apresenta de várias formas. A **energia cinética** é a energia associada ao movimento: Ec = m·v²/2. Ela depende da massa e do **quadrado** da velocidade. Dobrar a velocidade quadruplica a energia cinética, o que explica por que colisões em alta velocidade são tão mais destrutivas. O **teorema da energia cinética** afirma que o trabalho da força resultante é igual à variação da energia cinética: τ_res = ΔEc.',
  'A **energia potencial gravitacional** é a energia armazenada pela posição do corpo no campo gravitacional: Ep = m·g·h. Um objeto de 2 kg a 5 m de altura tem Ep = 2 × 10 × 5 = 100 J em relação ao solo. Já a **energia potencial elástica**, armazenada em molas e elásticos, vale Ep = k·x²/2. Ambas representam energia "guardada", que pode se converter em energia cinética quando o corpo é liberado.',
  'Essas formas de energia são chamadas de **mecânicas**, e sua soma é a energia mecânica: Em = Ec + Ep. A escolha do nível de referência para a energia potencial é arbitrária, mas deve ser mantida ao longo do problema, pois o que importa são as variações. Uma boa prática é adotar como referência o ponto mais baixo da trajetória, o que torna a energia potencial sempre não negativa.'] },
 { h:'Conservação da energia', p:[
  'Em sistemas em que apenas forças **conservativas** (como o peso e a força elástica) realizam trabalho, a energia mecânica se conserva: a soma de energia cinética e potencial permanece constante. Uma pedra lançada para cima converte energia cinética em potencial na subida, e o inverso na descida. No ponto mais alto, a energia cinética é mínima e a potencial é máxima. Em uma montanha-russa idealizada, a velocidade em qualquer ponto depende apenas da altura.',
  'Quando atuam forças **dissipativas**, como o atrito e a resistência do ar, parte da energia mecânica é transformada em energia térmica, sonora e deformação, e a energia mecânica diminui. Mas a **energia total** do universo continua conservada: a energia não se cria nem se destrói, apenas se transforma. O trabalho das forças dissipativas é igual à variação da energia mecânica: τ_atrito = Em,final − Em,inicial.',
  'Exemplo: um bloco de 2 kg é solto do alto de uma rampa de 5 m de altura e chega à base com velocidade de 8 m/s. Sem atrito, a velocidade seria √(2 × 10 × 5) = 10 m/s. A energia inicial era 100 J, e a final é 2 × 64/2 = 64 J. Os 36 J restantes foram dissipados por atrito. Raciocínios desse tipo são comuns em questões que comparam a energia antes e depois de um processo.'] },
 { h:'Potência e rendimento', p:[
  'A **potência** mede a rapidez com que a energia é transformada ou o trabalho é realizado: P = τ/Δt. A unidade é o **watt (W)**, igual a 1 J/s. Duas máquinas podem realizar o mesmo trabalho, mas a mais potente o faz em menos tempo. Um motor de 100 W realiza 100 J de trabalho a cada segundo. Também se usa o cavalo-vapor (cv), aproximadamente 735 W, e o horsepower (hp), cerca de 746 W, para motores.',
  'Quando uma força constante move um corpo com velocidade v, a potência instantânea é P = F · v. Isso explica por que carros precisam de mais potência para manter velocidades mais altas contra a resistência do ar: a força de resistência cresce com a velocidade, e a potência requerida cresce muito mais rápido. Também explica as marchas: em subidas, usa-se uma marcha baixa para obter maior força com menor velocidade.',
  'O **rendimento** η é a razão entre a energia útil e a energia total fornecida: η = E_útil/E_total. Nenhuma máquina tem rendimento de 100%, pois sempre há dissipação, principalmente em forma de calor. Um motor a combustão típico tem rendimento em torno de 25% a 30%, e um motor elétrico pode chegar a 90%. Questões do ENEM, ao tratar de eficiência energética, pedem para comparar equipamentos e interpretar rendimentos.'] },
 { h:'Energia no cotidiano e no ENEM', p:[
  'O tema aparece em contextos como usinas hidrelétricas (energia potencial da água convertida em cinética e depois em elétrica), alimentos (energia química convertida pelo corpo, medida em calorias, com 1 cal ≈ 4,2 J), veículos, ginástica e eletrodomésticos. Em geral, a questão pede para identificar as transformações de energia ou calcular quantidades simples, como a energia cinética de um carro ou a potência de um motor.',
  'Para resolver, identifique o sistema e as formas de energia no início e no fim. Se não há dissipação, iguale as energias mecânicas. Se há, use o trabalho do atrito. Escolha o nível de referência e calcule cada termo. Em questões de potência, converta o tempo para segundos e a energia para joules antes de calcular. Se a resposta pedida é em quilowatt-hora, lembre que 1 kWh = 3,6 × 10⁶ J.',
  'Cuidados importantes: lembre que a energia cinética depende do quadrado da velocidade; não confunda trabalho com força; atente ao sinal do trabalho; e não esqueça que, em uma transformação, a energia total se conserva, mas nem toda ela é útil. Essa noção de qualidade da energia é a base do estudo da eficiência energética e do uso consciente de recursos.'] }
]},

{ t:'Quantidade de movimento e impulso', txt:[
 { h:'Quantidade de movimento', p:[
  'A **quantidade de movimento** (ou momento linear) de um corpo é o produto de sua massa por sua velocidade: **Q = m · v**. É uma grandeza vetorial, com a mesma direção e sentido da velocidade, e sua unidade no SI é o kg·m/s. Ela mede o "tamanho" do movimento: um caminhão lento pode ter mais quantidade de movimento do que uma bala veloz, pois sua massa é muito maior. Quanto maior Q, mais difícil é parar o corpo.',
  'A segunda lei de Newton, em sua forma original, relaciona a força resultante à variação da quantidade de movimento: F = ΔQ/Δt. Essa forma é mais geral que F = ma e vale mesmo quando a massa varia, como em um foguete que queima combustível. Mostra também que, para mudar a quantidade de movimento de um corpo, é preciso aplicar uma força durante certo tempo.',
  'Como Q é vetorial, o sinal importa. Uma bola que chega à parede com 5 kg·m/s e volta com 4 kg·m/s no sentido oposto tem variação de Q igual a −4 − 5 = −9 kg·m/s (adotando o sentido de chegada como positivo). Atenção a esse cuidado com sinais: a variação de quantidade de movimento em colisões que invertem o sentido é a soma dos módulos, e não a diferença.'] },
 { h:'Impulso de uma força', p:[
  'O **impulso** (I) de uma força é o produto da força pelo intervalo de tempo em que ela atua: I = F · Δt, no caso de força constante. A unidade é o N·s, equivalente a kg·m/s. Quando a força varia com o tempo, o impulso é a **área** sob o gráfico da força em função do tempo. O impulso mede o efeito de uma força que age por certo tempo, e é um vetor com a direção e o sentido da força.',
  'O **teorema do impulso** afirma que o impulso da força resultante é igual à variação da quantidade de movimento: I = ΔQ. É uma consequência direta da segunda lei. Isso significa que, para provocar a mesma variação de Q, é possível aplicar uma força grande por pouco tempo ou uma força pequena por muito tempo. O produto F·Δt é o que importa.',
  'Essa ideia tem aplicações importantes em segurança. Em uma colisão, a variação de quantidade de movimento do passageiro é fixa (de v até 0). Se o tempo de parada aumenta, a força média diminui. Por isso existem airbags, cintos com certa elasticidade, para-choques deformáveis, capacetes com espuma e pisos de ginástica amortecedores: todos aumentam o tempo de interação e reduzem a força sobre o corpo, diminuindo o risco de lesões.'] },
 { h:'Conservação da quantidade de movimento', p:[
  'Em um **sistema isolado**, ou seja, quando a força resultante externa é nula (ou desprezível em relação às forças internas), a quantidade de movimento total se conserva: Q_antes = Q_depois. É um dos princípios mais fundamentais da Física. Em uma explosão, por exemplo, as forças internas fazem os fragmentos se separarem, mas a soma vetorial das quantidades de movimento permanece a mesma de antes.',
  'O recuo de uma arma ilustra o princípio. Antes do disparo, a arma e a bala estão em repouso, e Q = 0. Depois, a bala adquire quantidade de movimento para frente, e a arma, para trás, com a soma igual a zero: m_bala · v_bala = m_arma · v_arma. Como a massa da arma é muito maior, sua velocidade de recuo é pequena, mas sentida. O mesmo vale para um barco quando uma pessoa salta dele para a margem, e para o lançamento de foguetes, que expelem gases em alta velocidade.',
  'Para aplicar o princípio, escolha um sentido positivo, escreva a quantidade de movimento antes e depois, incluindo os sinais, e iguale. Verifique antes se o sistema pode ser considerado isolado: durante colisões muito rápidas, forças externas como o atrito costumam ser desprezíveis frente às forças de impacto. Esse é o procedimento padrão nas questões de colisões e explosões.'] },
 { h:'Colisões: elásticas, inelásticas e a energia', p:[
  'Nas **colisões**, a quantidade de movimento total se conserva, mas a energia cinética pode ou não se conservar. Em uma colisão **perfeitamente elástica**, a energia cinética também se conserva, e os corpos se separam com a mesma velocidade relativa com que se aproximaram. Em uma colisão **inelástica**, parte da energia cinética se transforma em calor, som e deformação. Em uma colisão **perfeitamente inelástica**, os corpos permanecem juntos após o choque, e a perda de energia é máxima.',
  'Exemplo: um vagão de 2.000 kg a 3 m/s colide com outro de 1.000 kg parado e se engata a ele. A quantidade de movimento antes é 6.000 kg·m/s. Depois, a massa total é 3.000 kg, e a velocidade comum é 2 m/s. A energia cinética inicial era 9.000 J e a final é 6.000 J: a diferença de 3.000 J foi dissipada. O resultado vale para qualquer colisão perfeitamente inelástica, e é a chave para muitos exercícios.',
  'Em colisões bidimensionais, como o choque oblíquo de bolas de bilhar, aplica-se a conservação separadamente para cada direção (eixo x e eixo y). Escrever a quantidade de movimento por componentes permite determinar velocidades desconhecidas. Nas questões do ENEM, os casos mais comuns envolvem colisões unidimensionais e conceitos qualitativos: qual dos corpos sofre maior variação de velocidade, quem recebe maior impulso etc.'] },
 { h:'Como esse tema aparece e como estudá-lo', p:[
  'Fique atento a contextos de trânsito, esportes e transporte. Um jogador que "amortece" a bola recuando a mão aumenta o tempo de contato e diminui a força. Um saltador que dobra os joelhos ao cair faz o mesmo. Um carro com zona de deformação programada absorve parte da energia da colisão, e o passageiro sofre menos. Em todos esses casos, o raciocínio é o mesmo: ΔQ fixo, então F·Δt fixo; aumentar Δt reduz F.',
  'Para resolver questões numéricas, use as relações I = F·Δt = ΔQ e a conservação de Q em sistemas isolados. Lembre-se de que Q e I são vetoriais, de modo que o sinal depende do referencial. Converta sempre as massas para kg e as velocidades para m/s. Se o enunciado fala de gráfico força × tempo, calcule o impulso pela área.',
  'Um bom exercício mental: compare a força de impacto em uma colisão de 0,01 s e de 0,1 s para o mesmo ΔQ. A força na primeira é 10 vezes maior. Essa conclusão qualitativa aparece com frequência nas provas. Se você dominar a relação entre tempo de interação e força, a maior parte das questões conceituais do tema será resolvida com poucas linhas de raciocínio.'] }
]},

{ t:'Gravitação universal', txt:[
 { h:'Da observação do céu à lei de Newton', p:[
  'Durante séculos, acreditou-se que a Terra era o centro do Universo (modelo geocêntrico de Ptolomeu). Copérnico propôs o modelo **heliocêntrico**, com o Sol no centro, e Galileu, com o telescópio, trouxe evidências observacionais, como as fases de Vênus e as luas de Júpiter. Kepler, analisando os dados precisos de Tycho Brahe, formulou as leis que descrevem os movimentos dos planetas. Newton, por fim, explicou por que os planetas se movem assim, unificando o céu e a Terra.',
  'A ideia de Newton foi que a força que faz a maçã cair é da mesma natureza da que mantém a Lua em órbita: a **gravidade**. Na **lei da gravitação universal**, dois corpos de massas m₁ e m₂, separados por uma distância d, se atraem com uma força F = G·m₁·m₂/d², em que G é a constante gravitacional, de valor muito pequeno (6,67 × 10⁻¹¹ N·m²/kg²). Por isso, a atração entre objetos comuns é imperceptível; só é notável quando pelo menos um dos corpos tem massa astronômica.',
  'A força gravitacional é sempre **atrativa**, é proporcional ao produto das massas e inversamente proporcional ao **quadrado da distância**. Se a distância dobra, a força cai a um quarto; se triplica, cai a um nono. Pela terceira lei de Newton, a força que a Terra exerce na Lua é igual, em módulo, à que a Lua exerce na Terra, embora seus efeitos sejam diferentes por causa das massas distintas.'] },
 { h:'Aceleração da gravidade e peso', p:[
  'A aceleração da gravidade na superfície de um astro de massa M e raio R é g = G·M/R². Ela depende da massa e do raio do astro, mas **não** da massa do corpo que cai. Na Terra, vale cerca de 9,8 m/s²; na Lua, cerca de 1,6 m/s²; em Júpiter, mais de 24 m/s². O peso de um corpo, P = m·g, depende do local, enquanto a massa não. Um astronauta de 80 kg pesa cerca de 800 N na Terra e 128 N na Lua.',
  'Com a altitude, g diminui, porque a distância ao centro da Terra aumenta: g = G·M/(R + h)². A 400 km de altura, onde orbita a Estação Espacial Internacional, g ainda vale cerca de 89% do valor na superfície. Portanto, os astronautas na estação **não** estão sem gravidade; eles "flutuam" porque estão em queda livre contínua junto com a estação, sem apoio que exerça normal sobre eles. Essa distinção é muito cobrada.',
  'Pequenas variações de g na superfície terrestre ocorrem por causa do achatamento da Terra, da altitude e da rotação. Ele é ligeiramente maior nos polos do que no equador. Embora essas diferenças sejam pequenas, são relevantes para medições precisas e para a geologia. Nos problemas do ENEM, costuma-se usar um valor único de g, a menos que o enunciado trate de outro astro.'] },
 { h:'Leis de Kepler', p:[
  'Kepler descreveu o movimento planetário em três leis. A **primeira** (lei das órbitas) diz que os planetas descrevem **elipses** em torno do Sol, que ocupa um dos focos. A **segunda** (lei das áreas) afirma que a linha que liga o planeta ao Sol varre áreas iguais em tempos iguais, o que implica que o planeta se move mais rápido quando está mais perto do Sol (periélio) e mais devagar quando está mais longe (afélio).',
  'A **terceira lei** (lei dos períodos) relaciona o período T de translação ao raio médio R da órbita: T²/R³ é constante para todos os planetas do mesmo sistema. Quanto mais distante do Sol, maior o período. Mercúrio, próximo, dá a volta em 88 dias; a Terra, em 365 dias; Netuno, em cerca de 165 anos. Se um planeta tem raio orbital 4 vezes maior que o da Terra, seu período é √(4³) = 8 anos.',
  'As leis de Kepler são consequências da gravitação de Newton, e valem também para satélites em torno da Terra e luas em torno de planetas. Elas explicam as estações do ano? Não: as estações vêm da inclinação do eixo terrestre, e não da distância ao Sol (a Terra está mais perto do Sol em janeiro, durante o verão no hemisfério sul, mas também durante o inverno no hemisfério norte). Esse tipo de equívoco é cobrado no ENEM.'] },
 { h:'Órbitas, satélites e ausência de peso', p:[
  'Um **satélite** em órbita circular está em movimento circular uniforme, e a força gravitacional é a força centrípeta: G·M·m/r² = m·v²/r. Disso resulta que a velocidade orbital é v = √(G·M/r), que **não depende da massa do satélite** e diminui com o raio da órbita. Satélites mais baixos são mais rápidos. A Estação Espacial, a 400 km, dá uma volta em cerca de 90 minutos, a quase 28.000 km/h.',
  'Os **satélites geoestacionários** têm período de 24 horas e giram no mesmo sentido da Terra, sobre a linha do Equador, de modo que parecem parados no céu em relação a um ponto da superfície. Estão a cerca de 36.000 km de altitude e são usados em telecomunicações e meteorologia. Já os satélites de órbita baixa, como os de observação e de internet via satélite, são mais rápidos e cobrem a superfície em faixas sucessivas.',
  'A sensação de "ausência de peso" em órbita ocorre porque o satélite e tudo dentro dele estão em queda livre: caem em direção à Terra, mas, por terem velocidade horizontal suficiente, "erram" a Terra continuamente. O mesmo efeito é sentido em elevadores em queda livre e em aviões em trajetória parabólica. A gravidade continua atuando; o que desaparece é a força normal, responsável pela sensação de peso.'] },
 { h:'Marés, escape e aplicações', p:[
  'As **marés** são consequência da atração gravitacional da Lua (e, em menor grau, do Sol) sobre a água dos oceanos. Como a força gravitacional diminui com a distância, o lado da Terra voltado para a Lua é atraído com mais intensidade que o centro, que por sua vez é atraído mais que o lado oposto, o que gera dois "inchaços" de água e duas marés altas por dia. Nas luas cheia e nova, Sol, Terra e Lua se alinham, e ocorrem as marés mais intensas (marés de sizígia).',
  'A **velocidade de escape** é a velocidade mínima necessária para um corpo escapar da atração gravitacional de um astro sem propulsão adicional. Na Terra, é cerca de 11,2 km/s. Foguetes não precisam atingi-la de uma vez, pois mantêm propulsão durante a subida, mas é um conceito importante para entender por que a Lua, com menor gravidade, não retém atmosfera, e por que os gases leves escapam facilmente de planetas pequenos.',
  'O ENEM costuma explorar a gravitação de forma qualitativa: comparar pesos em astros diferentes, explicar a ausência de peso em órbita, relacionar o período orbital ao raio, entender as marés e interpretar as leis de Kepler em contextos de satélites e astronomia. Um bom hábito é lembrar que a força gravitacional é inversamente proporcional ao quadrado da distância, e proporcional ao produto das massas. Com essa relação em mente, muitas respostas saem apenas por proporcionalidade, sem contas.'] }
]}
];
