/* Física: textos corridos, temas 16 a 18 */
module.exports = [
{ t:'Óptica geométrica', txt:[
 { h:'Luz, raios e princípios da óptica', p:[
  'A **óptica geométrica** estuda os fenômenos da luz por meio de **raios de luz**, linhas orientadas que indicam a direção e o sentido de propagação. Essa descrição é útil quando a luz interage com objetos grandes em comparação ao seu comprimento de onda, como espelhos, lentes e prismas. A luz visível é uma onda eletromagnética e, no vácuo, propaga-se a cerca de 300.000 km/s, a maior velocidade possível no Universo.',
  'Os corpos são classificados quanto à luz. Os **luminosos** emitem luz própria (Sol, lâmpada acesa, chama), e os **iluminados** apenas a refletem (Lua, livro, pessoas). Quanto à transparência, o meio pode ser **transparente** (permite a passagem nítida da luz, como o vidro comum), **translúcido** (deixa passar luz, mas sem nitidez, como o vidro fosco) ou **opaco** (não deixa passar a luz, como a madeira). A mesma substância pode ser transparente em pequena espessura e opaca em grande espessura.',
  'Três princípios regem a óptica geométrica. O da **propagação retilínea**: em um meio homogêneo e transparente, a luz se propaga em linha reta. O da **independência dos raios**: raios de luz que se cruzam não se alteram. E o da **reversibilidade**: o caminho de um raio é o mesmo se o sentido for invertido. O primeiro explica a formação de sombras e a câmara escura; o último, por exemplo, por que, se você vê os olhos de alguém em um espelho, essa pessoa também vê os seus.'] },
 { h:'Sombra, penumbra e eclipses', p:[
  'A propagação retilínea explica a formação de **sombras**. Quando uma fonte de luz pontual ilumina um objeto opaco, forma-se atrás dele uma região escura, a sombra. Se a fonte é **extensa**, aparece também uma região parcialmente iluminada, a **penumbra**. Quanto mais próxima a fonte do objeto, maior a sombra. Isso é usado na projeção de sombras em jogos de teatro e na determinação de alturas por comparação de sombras, em problemas de proporcionalidade com triângulos semelhantes.',
  'Os **eclipses** são aplicações em escala astronômica. No **eclipse solar**, a Lua passa entre o Sol e a Terra, projetando sombra e penumbra sobre a superfície terrestre; observadores na região de sombra veem o eclipse total, e na penumbra, o parcial. No **eclipse lunar**, a Terra fica entre o Sol e a Lua, que entra na sombra da Terra. O eclipse solar ocorre na fase de lua nova, e o lunar, na lua cheia. Eles não acontecem todo mês porque a órbita da Lua é inclinada em relação à da Terra.',
  'A **câmara escura de orifício** é uma caixa fechada com um pequeno furo em uma das faces, que forma na face oposta uma imagem **invertida** do objeto, por propagação retilínea da luz. Esse é o princípio das primeiras câmeras fotográficas e do funcionamento básico do olho. A altura da imagem é proporcional à do objeto e à razão das distâncias: i/o = d_imagem/d_objeto. Questões do ENEM podem pedir o tamanho da imagem ou a distância necessária para obtê-la.'] },
 { h:'Reflexão da luz e espelhos planos', p:[
  'A **reflexão** ocorre quando a luz incide sobre uma superfície e retorna ao meio de origem. As leis da reflexão afirmam que o raio incidente, o raio refletido e a normal à superfície estão no mesmo plano, e que o **ângulo de incidência é igual ao ângulo de reflexão**. Em superfícies lisas, a reflexão é **regular** (especular), formando imagens nítidas, como em espelhos. Em superfícies rugosas, ocorre a reflexão **difusa**, que espalha a luz em várias direções e nos permite ver os objetos de qualquer ângulo.',
  'No **espelho plano**, a imagem formada é **virtual** (formada pelo prolongamento dos raios refletidos, não pode ser projetada em um anteparo), **direita**, do **mesmo tamanho** do objeto e **simétrica** em relação ao plano do espelho: a imagem está à mesma distância atrás do espelho que o objeto está à frente. Por isso, você enxerga sua imagem a uma distância igual ao dobro da que está do espelho. A imagem é **enantiomorfa**: a mão direita da imagem corresponde à esquerda do objeto.',
  'Aplicações e problemas: se uma pessoa se afasta do espelho a 1 m/s, sua imagem se afasta dela a 2 m/s. O tamanho mínimo do espelho para que uma pessoa se veja de corpo inteiro é metade de sua altura, independentemente da distância. Dois espelhos planos formando um ângulo θ produzem N = 360°/θ − 1 imagens, como em caleidoscópios e em espelhos paralelos que geram imagens "infinitas". Em um relógio visto no espelho, o horário parece invertido.'] },
 { h:'Espelhos esféricos', p:[
  'Os **espelhos esféricos** são calotas de esferas com superfície refletora. O **côncavo** reflete na parte interna, e o **convexo**, na parte externa. Seus elementos são o centro de curvatura C, o raio R, o vértice V, o eixo principal e o **foco** F, ponto em que os raios paralelos ao eixo convergem (côncavo) ou parecem divergir (convexo), localizado à distância f = R/2 do vértice. No espelho côncavo, o foco é real; no convexo, é virtual.',
  'O espelho **côncavo** forma imagens diferentes conforme a posição do objeto. Se o objeto está além de C, a imagem é real, invertida e menor. Entre C e F, é real, invertida e maior. Entre F e V, é virtual, direita e maior (como em espelhos de maquiagem e de barbear, ou refletores de lanternas e faróis). O espelho **convexo**, para qualquer posição do objeto, produz imagem virtual, direita e menor, e tem amplo campo de visão, por isso é usado em retrovisores, em saídas de garagem e em cantos de lojas.',
  'Para determinar a posição e o tamanho da imagem, usa-se a **equação de Gauss**: 1/f = 1/p + 1/p\', em que p é a distância do objeto ao vértice e p\' é a da imagem. O aumento linear é A = i/o = −p\'/p. Convenções de sinais: distâncias de imagens e focos reais são positivas, e virtuais, negativas; i positivo é imagem direita, negativo, invertida. Memorizar o procedimento e as convenções é mais importante do que decorar tabelas de casos.'] },
 { h:'Cores, absorção e como estudar', p:[
  'A luz branca é a soma das cores do espectro visível (vermelho, laranja, amarelo, verde, azul, anil e violeta), o que Newton demonstrou com um prisma. A cor de um objeto iluminado depende da luz que ele **reflete**. Um objeto que parece vermelho reflete predominantemente a luz vermelha e absorve as demais; um objeto branco reflete todas as cores; um preto absorve quase toda a luz. Se um objeto vermelho é iluminado apenas por luz verde, parece preto, pois absorve a luz verde.',
  'As **cores primárias de luz** são vermelho, verde e azul (RGB), e sua soma em partes iguais produz o branco; as telas de TV, celulares e computadores formam todas as cores por meio desses três tipos de pontos luminosos. Já as **cores primárias de pigmento** (usadas em tintas e impressoras) são ciano, magenta e amarelo, que **subtraem** cores da luz branca. Essa diferença entre mistura aditiva (luz) e subtrativa (pigmentos) é um tópico frequente em questões.',
  'Para estudar o tema, treine desenhar raios: para o espelho plano, a simetria; para os esféricos, os raios notáveis (paralelo ao eixo, que passa pelo foco; o que passa pelo foco, que sai paralelo; o que passa pelo centro, que retorna sobre si mesmo). Em problemas de câmara escura e de sombras, use a semelhança de triângulos. E em questões de cores, pergunte sempre: que luz incide e que luz o objeto reflete? Essas quatro rotinas cobrem a maior parte do que o ENEM pergunta sobre óptica geométrica.'] }
]},

{ t:'Refração e lentes', txt:[
 { h:'O que é refração e o índice de refração', p:[
  'A **refração** é a mudança de velocidade que a luz sofre ao passar de um meio para outro. Quando a incidência é oblíqua, essa mudança de velocidade provoca uma **mudança de direção** do raio. A frequência da luz não se altera, mas sua velocidade e seu comprimento de onda sim. A luz é mais lenta em meios mais densos opticamente: na água, cerca de 225.000 km/s; no vidro comum, cerca de 200.000 km/s; no vácuo, 300.000 km/s.',
  'Para quantificar, define-se o **índice de refração absoluto** de um meio: n = c/v, em que c é a velocidade da luz no vácuo e v, a velocidade no meio. Como v ≤ c, n ≥ 1. Para o ar, n ≈ 1; para a água, n ≈ 1,33; para o vidro, n ≈ 1,5; para o diamante, n ≈ 2,4. Quanto maior o índice, mais lenta a luz e mais "refringente" o meio. Esse conceito permite comparar meios e prever o desvio da luz em cada situação.',
  'A **lei de Snell-Descartes** relaciona os ângulos: n₁ · sen θ₁ = n₂ · sen θ₂. Quando a luz vai de um meio menos refringente para outro mais refringente (do ar para a água), o raio se **aproxima da normal**; no sentido inverso, **afasta-se da normal**. Se a incidência é perpendicular (θ = 0°), não há desvio, mas a velocidade ainda muda. Essa regra qualitativa resolve a maior parte das questões do ENEM sobre desvio da luz.'] },
 { h:'Fenômenos cotidianos de refração', p:[
  'A refração está por trás de efeitos conhecidos. Um **canudo ou lápis** parcialmente mergulhado na água parece "quebrado" ou deslocado na interface, porque os raios que saem da parte submersa se desviam ao passar para o ar. Uma **piscina** parece mais rasa do que é, pois o olho interpreta os raios como se viessem de uma profundidade aparente menor. Por isso, os pescadores que arpoam peixes precisam mirar abaixo da posição aparente.',
  'A **dispersão da luz** ocorre quando a luz branca atravessa um prisma ou gotas de água. Como o índice de refração varia ligeiramente com a cor (maior para o violeta, menor para o vermelho), cada cor é desviada em um ângulo diferente, e o feixe se separa no espectro de cores. O **arco-íris** é formado por refração e reflexão da luz solar em gotículas de água, e é visto quando o Sol está atrás do observador e a chuva, à frente. O vermelho aparece na parte externa do arco, e o violeta, na interna.',
  'As **miragens** e o aspecto "molhado" do asfalto em dias quentes resultam da refração em camadas de ar com diferentes temperaturas e, portanto, diferentes índices de refração. A **cintilação das estrelas** ocorre porque a luz atravessa uma atmosfera turbulenta de densidade variável, e o **pôr do sol** é visto um pouco antes de o astro ter realmente descido abaixo do horizonte, por causa da refração atmosférica.'] },
 { h:'Reflexão total e fibras ópticas', p:[
  'Quando a luz passa de um meio mais refringente para um menos refringente (por exemplo, da água para o ar), o raio se afasta da normal. Aumentando o ângulo de incidência, chega-se ao **ângulo limite** (ou crítico), a partir do qual não há mais refração: toda a luz é refletida de volta ao meio original. É a **reflexão total interna**. O ângulo limite satisfaz sen L = n_menor/n_maior. Para a interface vidro-ar, L ≈ 42°.',
  'A reflexão total é a base das **fibras ópticas**, filamentos finíssimos de vidro ou plástico por onde a luz viaja por reflexões sucessivas, sem perder energia significativa. São usadas em telecomunicações (internet de alta velocidade e telefonia, que transmitem a informação por pulsos de luz) e em medicina (endoscopia, que permite ver o interior do corpo). O mesmo fenômeno faz os diamantes brilharem, pois seu alto índice de refração e suas faces lapidadas favorecem múltiplas reflexões totais internas.',
  'Para que haja reflexão total, duas condições são necessárias: a luz deve estar no meio mais refringente e o ângulo de incidência deve ser maior que o ângulo limite. Essa é uma pegadinha clássica: se qualquer uma não ocorre, não há reflexão total. Em questões, identifique os meios, compare os índices e verifique o ângulo. Os prismas de binóculos e periscópios também usam a reflexão total para inverter e redirecionar a luz.'] },
 { h:'Lentes esféricas e formação de imagens', p:[
  'As **lentes esféricas** são meios transparentes limitados por superfícies esféricas, que desviam a luz por refração. Existem dois tipos principais. As de **bordas finas**, ou convergentes, concentram os raios paralelos ao eixo em um ponto, o foco imagem. As de **bordas grossas**, ou divergentes, espalham os raios, que parecem sair de um foco virtual. Quando a lente é mais refringente do que o meio ao redor (como o vidro no ar), as de bordas finas são convergentes, e as de bordas grossas, divergentes.',
  'A **lente convergente** pode formar imagens reais (projetáveis) ou virtuais, conforme a posição do objeto. Objeto além do dobro da distância focal: imagem real, invertida e menor (como em câmeras). Entre f e 2f: real, invertida e maior (como em projetores). Entre o foco e a lente: virtual, direita e maior, como em uma **lupa**. Já a **lente divergente** forma, para qualquer posição, imagem virtual, direita e menor.',
  'A mesma equação de Gauss vale para lentes: 1/f = 1/p + 1/p\', e o aumento é A = −p\'/p. A **vergência** (ou "grau") da lente é V = 1/f, com f em metros, e é medida em **dioptrias** (di). Lentes convergentes têm vergência positiva, e divergentes, negativa. O "grau" dos óculos é a vergência: uma lente de +2 di tem foco a 0,5 m e converge a luz; uma de −3 di diverge, com f = −0,33 m.'] },
 { h:'O olho humano e os instrumentos ópticos', p:[
  'O **olho humano** funciona como uma câmera: a córnea e o cristalino formam, em conjunto, uma lente convergente que projeta na **retina** uma imagem real, invertida e menor, que o cérebro interpreta. Para focalizar objetos a diferentes distâncias, o cristalino muda de curvatura (acomodação visual). A pupila regula a quantidade de luz que entra. Quando a imagem não se forma exatamente sobre a retina, surgem os defeitos de visão.',
  'Na **miopia**, o olho é "longo" demais ou convergente demais: a imagem de objetos distantes se forma antes da retina, e a pessoa enxerga mal de longe. A correção usa lentes **divergentes**. Na **hipermetropia**, o olho é "curto" ou pouco convergente: a imagem se forma depois da retina, o que dificulta ver de perto, e a correção usa lentes **convergentes**. Na **presbiopia** ("vista cansada"), o cristalino perde elasticidade com a idade, dificultando a leitura, também corrigida com lentes convergentes. No **astigmatismo**, a córnea tem curvatura irregular, e usam-se lentes cilíndricas.',
  'Instrumentos ópticos aplicam lentes e espelhos: a **lupa** (uma lente convergente com o objeto entre o foco e a lente), a **câmera fotográfica**, o **microscópio** (duas lentes convergentes, objetiva e ocular, para ampliar objetos minúsculos), a **luneta** e o **telescópio** (para objetos distantes, usando lentes ou espelhos). Em questões, o raciocínio é qualitativo: qual lente corrige determinado defeito, o que ocorre com a imagem e quais características ela tem. Dominar essas associações garante a maioria dos pontos do tema.'] }
]},

{ t:'Eletrostática', txt:[
 { h:'Carga elétrica e eletrização', p:[
  'A **eletrostática** estuda as cargas elétricas em repouso. A matéria é formada por átomos, que têm prótons (carga positiva) no núcleo e elétrons (carga negativa) na eletrosfera. Normalmente, os corpos são **neutros**, pois têm o mesmo número de prótons e elétrons. Um corpo fica eletrizado quando ganha ou perde elétrons: com excesso de elétrons, fica **negativo**; com falta, **positivo**. Só os elétrons podem ser transferidos, pois os prótons estão presos aos núcleos.',
  'A unidade de carga no SI é o **coulomb (C)**. A menor carga encontrada livremente na natureza, a **carga elementar**, vale e = 1,6 × 10⁻¹⁹ C, e toda carga é múltipla inteira dela: Q = n · e (**quantização da carga**). A **conservação da carga elétrica** afirma que, em um sistema isolado, a soma algébrica das cargas permanece constante. Em qualquer processo de eletrização, a carga não é criada nem destruída, apenas transferida.',
  'Cargas de mesmo sinal se **repelem**, e cargas de sinais opostos se **atraem**. Corpos neutros também podem ser atraídos por corpos eletrizados, por causa da **polarização**: as cargas do corpo neutro se reorganizam, e a atração é maior que a repulsão por causa da menor distância. É por isso que um pente atritado atrai pedacinhos de papel e que um balão esfregado no cabelo gruda na parede.'] },
 { h:'Processos de eletrização e condutores', p:[
  'Há três processos principais de eletrização. No **atrito**, dois corpos de materiais diferentes são esfregados, e elétrons passam de um para o outro; ao final, os dois ficam com cargas de **sinais opostos** e módulos iguais. No **contato**, um corpo eletrizado toca um condutor neutro, e ambos ficam com cargas de **mesmo sinal**. Na **indução**, um corpo eletrizado é aproximado, sem tocar, de um condutor neutro, e este tem as cargas separadas; ligando-o à terra, é possível eletrizá-lo com carga de **sinal oposto** ao do indutor.',
  'Os materiais se classificam em **condutores**, que permitem a movimentação de cargas (metais, soluções iônicas, corpo humano), e **isolantes** ou dielétricos, em que as cargas ficam praticamente fixas (borracha, vidro, plástico, madeira seca). Em um condutor eletrizado isolado, as cargas se distribuem na **superfície externa**, e acumulam-se mais nas pontas (poder das pontas). Por isso, os para-raios têm ponta e as pontas de objetos metálicos favorecem descargas.',
  'A **blindagem eletrostática** (gaiola de Faraday) é a propriedade de que o campo elétrico no interior de um condutor oco em equilíbrio é nulo. É por isso que, dentro de um carro de lataria metálica durante uma tempestade, estamos relativamente protegidos de raios, e que equipamentos sensíveis são colocados em caixas metálicas. A **terra**, enorme e condutora, funciona como um reservatório que pode ceder ou receber elétrons sem alterar seu potencial de forma sensível.'] },
 { h:'Lei de Coulomb', p:[
  'A força de interação entre duas cargas puntiformes é dada pela **lei de Coulomb**: F = k · |Q₁| · |Q₂|/d², em que d é a distância entre as cargas e k é a constante eletrostática, que no vácuo vale cerca de 9 × 10⁹ N·m²/C². A força é **diretamente proporcional ao produto das cargas** e **inversamente proporcional ao quadrado da distância**. Dobrar a distância reduz a força a um quarto; dobrar uma das cargas dobra a força. Seu formato é semelhante ao da lei da gravitação universal.',
  'As forças elétricas entre duas cargas formam um par ação e reação: têm o mesmo módulo, mesma direção e sentidos opostos, mesmo que as cargas sejam diferentes. Em um sistema com mais de duas cargas, a força sobre uma delas é a **soma vetorial** das forças exercidas pelas demais (princípio da superposição). Em problemas, desenhe as forças com cuidado, definindo se são de atração ou repulsão, e componha por vetores.',
  'Para comparar a ordem de grandeza: em duas cargas de 1 µC (10⁻⁶ C) separadas por 1 m, a força é 9 × 10⁹ × 10⁻¹²/1 = 9 × 10⁻³ N, uma força pequena. Para ter forças significativas, são necessárias cargas bem maiores ou distâncias muito pequenas. Na escala atômica, as forças elétricas são enormes em comparação com as gravitacionais, e são elas que mantêm os átomos e as moléculas unidos, determinando as propriedades dos materiais.'] },
 { h:'Campo elétrico e potencial elétrico', p:[
  'O **campo elétrico** (E) é a região do espaço em que uma carga elétrica sofre uma força devido à presença de outras cargas. É definido por E = F/q, em que q é uma carga de prova, e é medido em N/C (ou V/m). É uma grandeza vetorial: para uma carga fonte **positiva**, as linhas de campo **saem** dela; para uma **negativa**, **chegam** a ela. O módulo do campo de uma carga puntiforme Q a uma distância d é E = k · |Q|/d², e diminui com o quadrado da distância.',
  'As **linhas de campo** são uma representação visual: a tangente à linha dá a direção do campo, e a densidade das linhas indica sua intensidade. Linhas nunca se cruzam. Entre duas placas paralelas carregadas com cargas opostas, o campo é **uniforme**: as linhas são paralelas e igualmente espaçadas. Uma carga positiva colocada em um campo sofre força no sentido do campo; uma carga negativa, no sentido contrário. Em um campo uniforme, F = q · E, o que permite calcular a aceleração de partículas carregadas.',
  'O **potencial elétrico** (V) é a energia potencial elétrica por unidade de carga, em volts (V = J/C). Para uma carga puntiforme, V = k · Q/d. A **diferença de potencial (ddp ou tensão)** entre dois pontos, U = V_A − V_B, mede a energia fornecida por unidade de carga ao deslocá-la entre eles. Em um campo uniforme, U = E · d. O trabalho da força elétrica para mover uma carga q entre dois pontos é τ = q · U. Cargas positivas tendem a ir espontaneamente de potenciais mais altos para mais baixos.'] },
 { h:'Aplicações e raios', p:[
  'A eletrostática tem inúmeras aplicações tecnológicas. As **impressoras a laser** e as **fotocopiadoras** usam cargas elétricas para atrair o pó (toner) a regiões do papel. Os **precipitadores eletrostáticos** removem partículas poluentes dos gases de chaminés, eletrizando-as e atraindo-as a placas coletoras. A **pintura eletrostática** faz com que as gotas de tinta, carregadas, sejam atraídas ao objeto, formando uma camada uniforme e reduzindo o desperdício. Os **capacitores** armazenam cargas e energia em circuitos eletrônicos.',
  'Os **raios** são descargas elétricas gigantescas entre nuvens e o solo, causadas pelo acúmulo de cargas na nuvem por atrito entre partículas de gelo e água. Quando a diferença de potencial é grande o bastante para ionizar o ar, ocorre a descarga, com correntes de dezenas de milhares de ampères. O trovão é a onda sonora provocada pelo aquecimento súbito e a expansão do ar. O **para-raios**, de Benjamin Franklin, é uma haste metálica pontiaguda, ligada à terra, que oferece um caminho seguro para a descarga.',
  'Cuidados práticos durante tempestades: evitar áreas abertas, topos de morros, árvores isoladas e superfícies de água; abrigar-se em edificações protegidas ou em veículos fechados; e afastar-se de aparelhos ligados à rede. A gaiola de Faraday ilustra por que o interior de um carro de lataria metálica protege. Esse é um dos temas de aplicação mais comuns do ENEM, porque se liga à segurança do cotidiano.'] },
 { h:'Como resolver questões de eletrostática', p:[
  'Em questões qualitativas, a primeira pergunta é: qual é o sinal das cargas? Cargas iguais se repelem; diferentes se atraem. Para os processos de eletrização, lembre: atrito (cargas opostas), contato (cargas iguais) e indução (indutor e induzido com cargas opostas, após ligação à terra). A conservação da carga permite calcular a carga final: no contato entre duas esferas idênticas, a carga total é dividida igualmente entre elas.',
  'Em questões quantitativas, converta unidades (µC em C, cm em m) e use as fórmulas: F = k·Q₁·Q₂/d², E = F/q, E = k·Q/d², U = E·d, τ = q·U. Cuidado com os sinais: use-os para determinar o sentido e use apenas os módulos para o cálculo do valor. Em problemas com várias cargas, faça a soma vetorial das forças ou dos campos.',
  'Por fim, desenvolva sensibilidade para as grandezas: uma força de 9 × 10⁻³ N entre duas cargas de 1 µC a 1 m, o campo de 3 × 10⁶ V/m (rigidez dielétrica do ar, a partir da qual há faísca), a carga do elétron de 1,6 × 10⁻¹⁹ C. Saber esses valores de referência ajuda a verificar se o resultado é plausível, e a escolher entre alternativas que diferem por potências de dez.'] }
]}
];
