/* Geografia: textos corridos, temas 4 a 6 */
module.exports = [
{ t:'Solos e erosão', txt:[
 { h:'Formação e composição dos solos', p:[
  'O **solo** é a camada superficial da crosta terrestre, formada pela decomposição das rochas e pela ação de organismos, e é a base da agricultura, da vegetação e de grande parte da vida terrestre. Sua formação é lenta: podem ser necessários centenas ou milhares de anos para formar poucos centímetros de solo fértil. O processo se chama **pedogênese**, e depende de cinco fatores principais: a **rocha de origem** (material parental), o **clima** (temperatura e chuvas), o **relevo**, os **organismos** (vegetação, fauna e microrganismos) e o **tempo**. Por isso, solos de lugares diferentes têm características muito diversas.',
  'O solo é formado por quatro componentes: a **fração mineral** (partículas de areia, silte e argila, vindas da rocha), a **matéria orgânica** (húmus, resultante da decomposição de plantas e animais), a **água** e o **ar**. A proporção entre areia, silte e argila define a **textura**: solos **arenosos** têm partículas grandes, são permeáveis e retêm pouca água e nutrientes; solos **argilosos** têm partículas finas, retêm muita água e nutrientes, mas drenam mal; e os **siltosos** são intermediários. Os solos mais férteis costumam ser os de textura média, ricos em húmus, que reúnem boa retenção e boa drenagem.',
  'O solo se organiza em camadas chamadas de **horizontes**, que formam o **perfil do solo**. O **horizonte O** (ou camada orgânica) é rico em matéria orgânica, o **A** é a camada superficial mineral, com húmus, a mais fértil e a mais afetada pela agricultura, o **B** acumula materiais lixiviados do horizonte superior, o **C** é a rocha em decomposição, e a **rocha-mãe** (R) é a rocha inalterada. Em regiões tropicais úmidas, o **intemperismo** químico é intenso e forma solos profundos, mas muitas vezes pobres em nutrientes, pois estes são lavados pela chuva (**lixiviação**). Já nas regiões temperadas, o solo é mais fértil, mas menos profundo.'] },
 { h:'Os principais tipos de solo do Brasil', p:[
  'Os solos brasileiros refletem a diversidade de clima, de rochas e de relevo. Predominam, nas regiões úmidas, os **latossolos**, solos velhos, profundos, bem drenados e de baixa fertilidade natural, mas que se tornam produtivos com **correção de acidez** (calagem) e **adubação**. Cobrem grande parte do território, inclusive o Cerrado, que foi ocupado pela agricultura moderna graças a essas técnicas. Os **argissolos** também são comuns, e têm acúmulo de argila no horizonte B, o que os torna mais suscetíveis à erosão, quando em relevo acidentado.',
  'Entre os solos mais férteis, estão o **massapê** (vertissolo), argiloso e rico em matéria orgânica, de grande importância histórica para o cultivo da cana-de-açúcar no litoral do Nordeste, e a **terra roxa** (nitossolo), originária da decomposição do basalto, rica em ferro e nutrientes, que sustenta a cafeicultura e outras lavouras no Sudeste e no Sul. Os solos **aluviais**, das várzeas dos rios, também são férteis, pois recebem sedimentos nas cheias. Já os **neossolos quartzarênicos** (arenosos) são pouco férteis e muito suscetíveis à erosão, e os solos **hidromórficos** estão em áreas alagadas, como as do Pantanal.',
  'Na região **semiárida** do Nordeste, predominam solos rasos e pedregosos, pouco intemperizados, e na **Amazônia**, solos antigos e pobres em nutrientes, em que a fertilidade está na biomassa e na **serrapilheira**, e não no solo. Por isso, o desmatamento provoca a perda rápida da fertilidade. As **terras pretas de índio**, solos escuros e férteis encontrados na Amazônia, resultaram do manejo dos povos indígenas, e mostram que o manejo adequado pode melhorar solos naturalmente pobres. Conhecer o tipo de solo é essencial para escolher culturas e práticas de manejo adequadas.'] },
 { h:'Erosão: causas, tipos e consequências', p:[
  'A **erosão** é o processo de desgaste e de remoção de partículas do solo e das rochas por agentes como a água, o vento, o gelo e os seres vivos. É um fenômeno natural, que esculpe o relevo, mas que se acelera de forma drástica com a **ação humana**: o desmatamento, a retirada da cobertura vegetal, a agricultura sem proteção do solo, a pecuária extensiva, as queimadas, a mineração, a urbanização desordenada e a impermeabilização. A vegetação protege o solo: as folhas amortecem o impacto da chuva, as raízes fixam as partículas e a serrapilheira retém a água.',
  'A **erosão hídrica** é a mais comum no Brasil, e se dá em estágios. Primeiro, a chuva provoca a **erosão laminar**, a remoção uniforme de uma fina camada superficial. Se a água se concentra, formam-se **sulcos** e, depois, **ravinas**, canais mais profundos e, por fim, as **voçorocas**, enormes buracos que podem atingir dezenas de metros e que são difíceis de recuperar. A **erosão eólica** ocorre em regiões áridas e semiáridas, com pouca vegetação, e o vento remove partículas leves. A **erosão marinha** atua nas costas, e a **erosão glacial**, nas regiões frias.',
  'As consequências da erosão acelerada são graves. Há perda da **fertilidade** e da produtividade agrícola, **assoreamento** de rios, lagos e represas (acúmulo de sedimentos no leito, que reduz a profundidade e a capacidade de armazenar água), aumento do risco de **enchentes**, contaminação das águas por sedimentos e agrotóxicos e, nos casos extremos, **desertificação**. A desertificação é a degradação das terras em áreas áridas, semiáridas e subúmidas secas, provocada por fatores climáticos e humanos. No Brasil, o fenômeno atinge áreas do Nordeste, como o Seridó, e do Rio Grande do Sul, as "areias" de Alegrete.'] },
 { h:'Conservação do solo e manejo sustentável', p:[
  'Diversas técnicas ajudam a **conservar o solo** e a evitar sua degradação. O **plantio em curvas de nível** consiste em arar e plantar acompanhando as curvas do terreno, em vez de seguir a declividade, o que reduz a velocidade da enxurrada. O **terraceamento** forma degraus em terrenos inclinados, para reter a água e o solo. A **rotação de culturas** alterna plantas diferentes em uma mesma área, o que ajuda a manter os nutrientes e a controlar as pragas. O **plantio direto** dispensa o revolvimento do solo, e mantém a palha sobre ele, o que reduz a erosão, preserva a umidade e aumenta a matéria orgânica.',
  'Outras práticas importantes são o uso de **cobertura vegetal** e de **adubação verde**, que protegem e enriquecem o solo, a **calagem**, que corrige a acidez, a **adubação orgânica**, a manutenção das **matas ciliares** (vegetação junto aos rios), que impede o assoreamento, a integração entre lavoura, pecuária e floresta (**sistemas agroflorestais**) e o controle do pastoreio. Em áreas urbanas, o planejamento do uso do solo, a manutenção de áreas permeáveis e a drenagem adequada previnem erosões e deslizamentos. A educação ambiental e a assistência técnica aos produtores são fundamentais.',
  'O uso intensivo do solo na **agricultura** provoca ainda outros problemas: a **compactação** pelo uso de máquinas pesadas, a **salinização** por irrigação inadequada em regiões áridas, a **contaminação** por agrotóxicos e fertilizantes e a perda da biodiversidade do solo, que abriga microrganismos essenciais. A **Política Nacional de Meio Ambiente** e o **Código Florestal** estabelecem normas de proteção, como as Áreas de Preservação Permanente (APPs). Em síntese, o solo é um recurso **finito e frágil**, e sua conservação é condição para a segurança alimentar e para o desenvolvimento sustentável.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, o tema dos solos aparece em questões sobre agricultura, desmatamento, erosão, desertificação, assoreamento e práticas de conservação. Os enunciados costumam descrever uma situação, como uma lavoura em terreno inclinado, uma voçoroca, um rio assoreado ou o uso do plantio direto, e pedem para identificar o processo e a medida adequada. Também podem tratar da relação entre solo, clima e vegetação, como a pobreza dos solos amazônicos, ou da importância histórica do massapê e da terra roxa.',
  'Dicas: associe cada tipo de erosão ao agente (água, vento) e às formas (laminar, sulcos, ravinas, voçorocas); lembre que o desmatamento expõe o solo, aumenta o escoamento e leva ao assoreamento; conecte a técnica de conservação ao problema (curvas de nível e terraços contra a enxurrada; plantio direto contra o revolvimento; matas ciliares contra o assoreamento). Cuidado com a ideia de que solos tropicais são "naturalmente férteis" por causa da vegetação exuberante: a fertilidade costuma estar na biomassa, não no solo.',
  'Para revisar, monte um quadro: fatores de formação do solo, horizontes, texturas, principais solos brasileiros (latossolo, massapê, terra roxa), tipos de erosão, consequências e práticas de manejo. Relacione o tema ao anterior (relevo e rochas) e ao seguinte (clima), pois a formação e a conservação dos solos dependem de ambos. Esse tema é essencial também para compreender as questões agrárias e ambientais que serão estudadas adiante, como a questão agrária brasileira e os impactos ambientais.'] }
]},
{ t:'Clima: fatores e elementos', txt:[
 { h:'Tempo e clima, a atmosfera e os elementos climáticos', p:[
  'É importante distinguir **tempo** e **clima**. O **tempo atmosférico** é o estado da atmosfera em um determinado lugar e momento, e muda de hora em hora, como "hoje está chovendo". O **clima** é o conjunto das condições médias da atmosfera de uma região, observadas por um longo período (pelo menos 30 anos), e representa o padrão habitual do tempo. A **Meteorologia** estuda o tempo e a **Climatologia**, o clima. Assim, dizer que o "clima do Nordeste é semiárido" refere-se a um padrão, enquanto "ontem choveu em Recife" se refere ao tempo.',
  'A **atmosfera** é a camada de gases que envolve a Terra, formada principalmente por nitrogênio (78%) e oxigênio (21%), com pequenas parcelas de argônio, gás carbônico e vapor de água. Ela se divide em camadas: **troposfera** (até cerca de 12 km, onde ocorrem os fenômenos meteorológicos e fica a maior parte do ar), **estratosfera** (onde está a camada de ozônio, que filtra a radiação ultravioleta), mesosfera, termosfera e exosfera. A atmosfera mantém a temperatura do planeta (efeito estufa natural), protege contra radiações e meteoros e permite a vida.',
  'Os **elementos do clima** são os atributos que se medem e que caracterizam o clima: a **temperatura** (grau de calor do ar), a **umidade** (quantidade de vapor de água), a **pressão atmosférica** (peso do ar sobre a superfície), os **ventos** (deslocamentos horizontais do ar), as **precipitações** (chuva, neve e granizo) e a **nebulosidade**. Eles se combinam e variam de lugar para lugar. Os instrumentos de medida incluem o termômetro, o barômetro, o higrômetro, o pluviômetro e o anemômetro, e as estações meteorológicas e os satélites coletam os dados usados nas previsões.'] },
 { h:'Os fatores do clima: latitude, altitude, continentalidade e outros', p:[
  'Os **fatores climáticos** são as condições que **modificam** os elementos do clima, e explicam por que ele varia de região para região. A **latitude** é o principal: define a incidência dos raios solares. Nas baixas latitudes (zona intertropical), os raios chegam mais perpendiculares e concentrados, e as temperaturas são mais altas; nas altas latitudes, os raios chegam inclinados, distribuídos por uma área maior, e as temperaturas são menores. Daí a divisão da Terra em zonas térmicas: tropical (quente), temperadas (amenas) e polares (frias).',
  'A **altitude** também influencia: a cada 100 metros de elevação, a temperatura do ar diminui, em média, cerca de 0,6 °C, pois o ar é mais rarefeito e retém menos calor refletido pela superfície. Por isso, cidades em serras, como Campos do Jordão, são mais frias do que as do litoral, na mesma latitude. A **continentalidade e a maritimidade** referem-se à distância do mar: a água demora a se aquecer e a se resfriar, por isso o **mar suaviza** as temperaturas, e as áreas litorâneas têm menor **amplitude térmica**, enquanto as do interior têm maior (verões mais quentes e invernos mais frios, ou dias quentes e noites frias).',
  'As **massas de ar**, grandes porções de ar com características homogêneas de temperatura e umidade, que se deslocam e influenciam o tempo (como a Massa Polar Atlântica, que traz frio ao Sul e ao Sudeste do Brasil); as **correntes marítimas**, que transportam calor e frio (a corrente do Golfo aquece o noroeste da Europa; a de Humboldt resfria o litoral do Peru e do Chile); o **relevo**, que barra os ventos úmidos e provoca chuvas de relevo (chuvas orográficas) na vertente que recebe o vento, e áreas secas na vertente oposta, a "sombra de chuva"; a **vegetação** e a **urbanização**, que criam microclimas, como as ilhas de calor, também são fatores.'] },
 { h:'Temperatura, pressão, ventos e umidade', p:[
  'A **temperatura** do ar varia ao longo do dia (mais alta à tarde, mais baixa de madrugada) e do ano, conforme a posição da Terra na órbita. A **amplitude térmica** é a diferença entre a maior e a menor temperatura em um período, e é maior em regiões áridas e continentais, onde há pouca umidade para reter o calor. A **pressão atmosférica** é a força exercida pelo peso do ar, e diminui com a altitude. Nas áreas de **alta pressão** (anticiclones), o ar desce, e o tempo é estável e seco; nas de **baixa pressão** (ciclones), o ar sobe, o que favorece a formação de nuvens e de chuvas.',
  'Os **ventos** são o deslocamento do ar das áreas de alta para as de baixa pressão. Os ventos **constantes** (alísios, que sopram dos trópicos para o Equador, e os de oeste) formam a circulação geral da atmosfera; os **periódicos**, como as monções, na Ásia, mudam de direção conforme a estação (úmidos no verão, secos no inverno); e os **locais**, como as brisas marítimas e terrestres, ocorrem por diferenças de aquecimento entre o continente e o mar. As **brisas** sopram do mar para a terra durante o dia, e da terra para o mar, à noite, e influenciam o clima do litoral.',
  'A **umidade** é a quantidade de vapor de água presente no ar. A **umidade relativa** expressa a razão entre a quantidade de vapor existente e a máxima que o ar pode conter na mesma temperatura: ar quente comporta mais vapor do que ar frio. Quando o ar atinge a saturação (100%), o vapor se condensa e forma nuvens, nevoeiro e orvalho. As **precipitações** se classificam, quanto à origem, em **convectivas** (de verão, pelo aquecimento intenso e pela subida do ar quente e úmido, chuvas fortes e rápidas), **orográficas** (de relevo, quando o ar sobe pela montanha) e **frontais** (quando massas de ar de temperaturas diferentes se encontram).'] },
 { h:'Zonas climáticas do planeta e tipos de clima', p:[
  'Combinando os fatores e os elementos, a Climatologia define os grandes **tipos climáticos**. Um dos sistemas de classificação mais usados é o de **Köppen**, que considera as médias de temperatura e de chuva. De modo simplificado, os climas do planeta podem ser agrupados por zonas. Na **zona intertropical**, estão o clima **equatorial** (quente e muito úmido o ano todo, como na Amazônia e no Congo), o **tropical** (quente, com duas estações: chuvosa no verão e seca no inverno), o **tropical de altitude**, o **semiárido** (quente e seco, com chuvas escassas e irregulares) e o **desértico**.',
  'Nas **zonas temperadas**, encontram-se o **subtropical** (chuvas bem distribuídas, verões quentes e invernos frios, como no Sul do Brasil), o **mediterrâneo** (verões secos e quentes, invernos chuvosos), o **oceânico** (úmido e ameno, sob influência do mar) e o **continental** (amplitude térmica elevada, no interior dos continentes). Nas **zonas frias**, o clima **polar** (temperaturas sempre baixas, com gelo permanente) e o de **montanha** (variação com a altitude). O **clima** influencia a vegetação, os solos, a hidrografia e a ocupação humana, e por isso é um dos temas centrais da Geografia física.',
  'Os fenômenos climáticos podem ter impacto direto sobre a vida humana e a economia. Fenômenos como o **El Niño** (aquecimento anormal das águas do Pacífico equatorial, que altera as chuvas em várias regiões do mundo, causando secas no Norte e no Nordeste do Brasil e chuvas fortes no Sul) e a **La Niña** (resfriamento dessas águas) são exemplos. Também são importantes os eventos extremos, como furacões e tornados, as secas prolongadas e as ondas de calor. Entender o clima é essencial para a agricultura, a gestão da água, o planejamento urbano e a prevenção de desastres, que o ENEM costuma relacionar.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em questões sobre clima, o ENEM costuma apresentar climogramas (gráficos que combinam temperatura e precipitação mensais), mapas de massas de ar e de zonas climáticas, textos sobre fenômenos como o El Niño, e situações do cotidiano (ilhas de calor, chuvas de verão). As perguntas pedem a identificação do clima a partir de dados, a explicação das diferenças de temperatura entre dois locais (latitude, altitude, maritimidade) e a relação entre clima, vegetação e atividades econômicas.',
  'Dicas: ao analisar um climograma, observe as barras (chuva) e a linha (temperatura): chuva alta e constante sugere clima equatorial; duas estações, uma seca e uma chuvosa, sugere clima tropical; temperaturas baixas no inverno e chuva bem distribuída, subtropical. Ao comparar localidades, identifique o fator que as diferencia: se a latitude é a mesma, pense na altitude ou na maritimidade. Lembre que o mar reduz a amplitude térmica e que as chuvas orográficas ocorrem na vertente que recebe os ventos úmidos.',
  'Para revisar, organize em quatro blocos: conceitos (tempo e clima), elementos (temperatura, pressão, ventos, umidade, chuvas), fatores (latitude, altitude, maritimidade, massas de ar, correntes marítimas, relevo) e tipos climáticos. Treine a leitura de climogramas e a identificação dos fatores nas situações descritas. Esse tema leva ao seguinte, que trata dos climas do Brasil e dos fenômenos climáticos específicos do país, e, em seguida, às mudanças climáticas globais, um dos assuntos mais frequentes das provas.'] }
]},
{ t:'Climas do Brasil e fenômenos climáticos', txt:[
 { h:'Os fatores que influenciam o clima do Brasil', p:[
  'O **clima do Brasil** é muito diverso, em razão da grande extensão territorial, da posição geográfica, do relevo e das massas de ar. Cerca de 90% do território está na **zona intertropical**, entre o Equador e o Trópico de Capricórnio, e por isso predominam os climas quentes, com temperaturas médias elevadas. Apenas o extremo sul do país, ao sul do Trópico de Capricórnio, está na zona temperada e tem clima subtropical. A **latitude** define, assim, o padrão geral, e a **altitude** (como nas serras do Sudeste), a **maritimidade** e o **relevo** criam variações locais.',
  'As **massas de ar** são decisivas para o regime de chuvas e as temperaturas. A **Massa Equatorial Atlântica** (quente e úmida) atua no litoral do Norte e do Nordeste, e a **Equatorial Continental**, na Amazônia, também é quente e úmida e responsável pelas chuvas da região. A **Tropical Atlântica** (quente e úmida) afeta o litoral e provoca chuvas de relevo na vertente leste do Nordeste e do Sudeste. A **Tropical Continental** (quente e seca) atua no centro do país, e a **Polar Atlântica**, fria e úmida, vem do sul e provoca quedas bruscas de temperatura no Sul e no Sudeste, chegando, no inverno, a todo o país.',
  'O **relevo** brasileiro, por ser de baixa altitude, não impede o deslocamento das massas de ar, o que permite que as massas polares cheguem a regiões tropicais, como no fenômeno da **friagem**, na Amazônia Ocidental, e que as massas equatoriais atinjam áreas mais ao sul. As **correntes marítimas** também têm papel: a **corrente do Brasil**, quente, passa pela costa leste, e a **das Malvinas**, fria, passa pelo sul. A **vegetação** influencia o clima local, por meio da evapotranspiração, e a Amazônia contribui para a formação dos "rios voadores", que levam umidade para o Centro-Sul.'] },
 { h:'Os principais tipos climáticos brasileiros', p:[
  'O clima **equatorial** predomina na Amazônia, com temperaturas elevadas o ano todo (média em torno de 25 a 27 °C), baixa amplitude térmica e chuvas abundantes e bem distribuídas (acima de 2.000 mm ao ano), com alta umidade. O clima **tropical** é o mais extenso, e abrange o Centro-Oeste, parte do Sudeste e do Nordeste e do Norte: é quente, com duas estações bem definidas, **verão chuvoso** e **inverno seco**. O **tropical de altitude** ocorre nas serras do Sudeste, com temperaturas mais amenas e chuvas de verão, e o **tropical atlântico (úmido)**, no litoral leste, tem chuvas bem distribuídas e abundantes no outono e no inverno em parte do Nordeste.',
  'O clima **semiárido** ocupa a maior parte do interior do Nordeste, o chamado **Sertão**, com temperaturas elevadas, grande evaporação e chuvas escassas (menos de 800 mm ao ano), mal distribuídas no tempo e no espaço, o que causa secas prolongadas. As chuvas são irregulares, e os rios são, em sua maioria, **intermitentes**, ou seja, secam em parte do ano. Esse clima sofre o efeito da **barreira de relevo** do Planalto da Borborema, que bloqueia a umidade vinda do litoral, e da atuação irregular das massas de ar e do fenômeno El Niño. O **clima subtropical** ocorre no Sul, com chuvas bem distribuídas, verões quentes e invernos frios, com geadas e, nas áreas mais altas, neve ocasional.',
  'Também se destacam os microclimas urbanos. Nas grandes cidades, o concreto, o asfalto e a falta de vegetação absorvem calor, formando as **ilhas de calor**, em que a temperatura é mais alta do que nas áreas rurais próximas. A impermeabilização do solo e a poluição do ar provocam alterações na circulação do ar e nas chuvas, e podem intensificar as chuvas fortes e as enchentes. A **inversão térmica**, em dias frios e secos, impede a dispersão dos poluentes, e piora a qualidade do ar, como em São Paulo no inverno. O planejamento urbano, com áreas verdes, ameniza esses efeitos.'] },
 { h:'Fenômenos climáticos: El Niño, La Niña, secas e eventos extremos', p:[
  'O **El Niño** é o aquecimento anormal das águas superficiais do oceano Pacífico equatorial, que modifica a circulação atmosférica global e altera o regime de chuvas e de temperaturas em várias regiões do mundo. No Brasil, costuma provocar **secas no Norte e no Nordeste** (e menos chuva na Amazônia) e **chuvas acima do normal no Sul**, além de temperaturas mais elevadas no Sudeste. A **La Niña** é o oposto: o resfriamento das mesmas águas, com efeitos inversos, como mais chuvas no Norte e no Nordeste e secas no Sul. Esses fenômenos ocorrem de forma irregular, a cada alguns anos, e afetam a agricultura e a geração de energia.',
  'As **secas** no Nordeste são um problema histórico, que atinge o Sertão, e geram migrações, perdas agrícolas e dificuldades no abastecimento de água. A seca não é apenas um fenômeno natural, mas também social, pois seus efeitos dependem da estrutura fundiária, da distribuição da água e das políticas públicas. Entre as respostas, estão a **transposição do Rio São Francisco**, as **cisternas** de captação de água da chuva, o programa Água para Todos e a adoção de técnicas de **convivência com o semiárido**, em vez do combate à seca. A "indústria da seca" é a expressão usada para criticar o uso político do problema.',
  'Outros fenômenos incluem as **chuvas intensas** de verão no Sudeste, associadas à **Zona de Convergência do Atlântico Sul** (ZCAS), que provoca enchentes e deslizamentos; as **geadas** no Sul e no Sudeste, com prejuízos às lavouras (como o café e a cana); as **frentes frias**; os **ciclones extratropicais** e, mais raramente, os **tornados** e o ciclone Catarina (2004), o primeiro furacão registrado no Atlântico Sul. Os **eventos extremos** têm se tornado mais frequentes e intensos, segundo cientistas, em razão das **mudanças climáticas**, o que exige sistemas de monitoramento, de alerta e de prevenção.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, os climas do Brasil aparecem em questões que pedem a associação entre dados de chuva e de temperatura (climogramas) e as regiões, a explicação do regime de chuvas, a atuação das massas de ar, e a influência do relevo e dos fenômenos El Niño e La Niña. Também há questões sobre a seca no Nordeste e as políticas de convivência com o semiárido, as ilhas de calor e a inversão térmica nas cidades, e os desastres naturais, como enchentes e deslizamentos, associados à ocupação do solo.',
  'Pontos de atenção: o Brasil é majoritariamente tropical; o clima equatorial é úmido o ano todo e o tropical tem duas estações; o semiárido tem chuvas escassas e irregulares, não só pouca chuva; as massas polares trazem frio e podem causar geadas; o El Niño causa seca no Nordeste e chuvas no Sul; e a ocupação desordenada aumenta o risco dos desastres. Evite dizer que a seca é uma "fatalidade" do clima: ela é agravada por fatores sociais e políticos, e é possível conviver com ela com tecnologias adequadas.',
  'Para revisar, esquematize: fatores (latitude, altitude, massas de ar, relevo, correntes) → climas (equatorial, tropical, tropical de altitude, semiárido, subtropical) → fenômenos (El Niño, La Niña, ZCAS, friagem, geadas, ilhas de calor) → impactos (seca, enchentes, agricultura) → respostas (cisternas, transposição, alertas). Esse tema se liga ao seguinte, as mudanças climáticas, que ampliam a frequência e a intensidade dos fenômenos extremos, e à hidrografia, que depende do regime de chuvas.'] }
]}
];
