/* Geografia: textos corridos, temas 13 a 15 */
module.exports = [
{ t:'Urbanização brasileira', txt:[
 { h:'O processo de urbanização: conceitos e etapas', p:[
  'A **urbanização** é o aumento da proporção da população que vive em cidades em relação à população rural. Não é a mesma coisa que o crescimento das cidades, pois ela é um processo que envolve também mudanças econômicas, sociais e culturais. O Brasil passou por uma urbanização **rápida e tardia**, comparada à dos países europeus. Em 1940, apenas cerca de 31% da população vivia em áreas urbanas; em 1970, passou a ser maioria; e hoje, mais de 85% dos brasileiros moram em cidades. Esse processo ocorreu em poucas décadas, o que gerou problemas de infraestrutura e de moradia.',
  'A urbanização brasileira esteve ligada à **industrialização**, principalmente a partir dos anos 1930 e 1950, e à **modernização do campo**. A mecanização agrícola, a concentração de terras e a falta de acesso à terra expulsaram milhões de pessoas para as cidades, no **êxodo rural**, enquanto a indústria e os serviços urbanos ofereciam empregos. As migrações do Nordeste para o Sudeste foram o principal fluxo, e as cidades de São Paulo e do Rio de Janeiro cresceram de forma explosiva. Também influenciaram a expansão dos serviços, do comércio e, mais tarde, a das fronteiras agrícolas, que levaram à criação de novas cidades.',
  'Esse crescimento ocorreu sem planejamento adequado, e a oferta de moradia, de transporte, de saneamento e de serviços não acompanhou a chegada de pessoas, o que levou à formação de **periferias** e **favelas**. O fenômeno é chamado de **urbanização acelerada e desordenada**, e se repete em muitos países em desenvolvimento. Ao mesmo tempo, a urbanização trouxe oportunidades de trabalho, de educação e de acesso a serviços, e mudou os hábitos e as relações sociais. A cidade é, assim, um espaço de contradições, que concentra riqueza e pobreza, inovação e desigualdade.'] },
 { h:'Metrópoles, regiões metropolitanas e conurbação', p:[
  'Ao longo do processo, formaram-se grandes aglomerações. A **metrópole** é uma grande cidade que exerce influência sobre outras, concentrando serviços, comércio, indústria e decisões. A **região metropolitana** é um conjunto de municípios vizinhos, integrados por fluxos econômicos, sociais e de transporte, com uma cidade principal, o **núcleo**, e as demais, chamadas de **periferia** ou cidades-dormitório, de onde muita gente vai trabalhar na metrópole diariamente (movimento pendular). São Paulo, Rio de Janeiro, Belo Horizonte, Porto Alegre, Recife, Salvador e Brasília são exemplos. A Grande São Paulo é uma das maiores aglomerações urbanas do mundo.',
  'A **conurbação** ocorre quando o crescimento de duas ou mais cidades vizinhas faz com que elas se unam fisicamente, formando uma mancha urbana contínua, como a de São Paulo com Guarulhos, Osasco, Santo André e outras. Quando a conurbação envolve grandes metrópoles, pode formar uma **megalópole**, como a que une São Paulo, Rio de Janeiro e as cidades do Vale do Paraíba, que se estende por um eixo industrial e de transporte, também chamado de Eixo Rio-São Paulo. A **metropolização** gera problemas: congestionamentos, poluição, custo elevado de moradia, violência e segregação, mas concentra a economia do país.',
  'A distribuição da urbanização é desigual. As regiões **Sudeste** e **Sul**, mais industrializadas, são as mais urbanizadas, e o **Centro-Oeste** também tem alta taxa de urbanização, ligada ao agronegócio e a Brasília. O **Nordeste** e o **Norte** têm mais população rural, embora estejam em rápida urbanização. Nas últimas décadas, as **cidades médias** (entre 100 mil e 500 mil habitantes) vêm crescendo mais do que as metrópoles, atraindo indústrias, serviços e migrantes, o que tem sido chamado de "interiorização" do desenvolvimento, e permite uma distribuição mais equilibrada da população.'] },
 { h:'Problemas urbanos: moradia, mobilidade, saneamento e segregação', p:[
  'O déficit de **moradia** é um dos maiores problemas. Sem acesso à terra urbanizada e com salários baixos, muitas pessoas ocupam áreas irregulares, como encostas, margens de rios e áreas de proteção ambiental, formando **favelas** (aglomerados subnormais) e loteamentos clandestinos, sem infraestrutura. Nessas áreas, os riscos de **deslizamentos** e de **enchentes** são altos. A **especulação imobiliária**, que mantém terrenos vazios à espera de valorização, e a concentração dos investimentos em áreas centrais empurram os mais pobres para a periferia. Programas como o Minha Casa Minha Vida procuraram enfrentar o problema.',
  'A **mobilidade urbana** é outro desafio. O modelo de cidade baseado no automóvel, a falta de investimentos em **transporte coletivo** (metrô, trens, corredores de ônibus), as longas distâncias entre a moradia e o trabalho e a baixa qualidade dos serviços causam **congestionamentos**, perda de tempo e poluição. O **saneamento básico** (água, esgoto, coleta de lixo e drenagem) ainda é precário em muitas áreas, e contribui para doenças e para a poluição dos rios. As **enchentes** nas grandes cidades se agravam pela impermeabilização do solo, pela ocupação de várzeas e pelo acúmulo de lixo nos canais.',
  'A **segregação socioespacial** se manifesta na divisão da cidade em áreas ricas, bem servidas de infraestrutura, e áreas pobres, carentes de serviços, com pouca mistura entre elas. Surgem os **condomínios fechados** e as favelas lado a lado, em um padrão de "fragmentação" urbana. A **violência urbana** e a sensação de insegurança relacionam-se à desigualdade e à pouca presença do poder público. O **Estatuto da Cidade** (2001) e os **Planos Diretores** estabelecem instrumentos, como a função social da propriedade e a participação popular, para promover o direito à cidade, mas sua aplicação enfrenta desafios.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A urbanização é cobrada no ENEM por meio de mapas, gráficos de população urbana e rural, imagens de favelas e de áreas centrais, textos sobre mobilidade, moradia, enchentes, segregação e planejamento. As questões costumam pedir que se relacione o crescimento urbano brasileiro ao êxodo rural e à industrialização, que se identifiquem os problemas das metrópoles e que se avaliem soluções, como o transporte coletivo, a regularização fundiária e o uso do Estatuto da Cidade. O tema se articula com Sociologia e com a redação.',
  'Pontos de atenção: a urbanização brasileira foi rápida e desordenada, ligada ao êxodo rural; conurbação é a junção física de cidades vizinhas; a região metropolitana é uma unidade de planejamento; a metrópole concentra serviços e decisões; a periferia e as favelas resultam do acesso desigual à terra e à moradia; o crescimento recente das cidades médias reduz a concentração nas metrópoles; e as soluções passam por políticas de moradia, de transporte e de saneamento. Evite culpar os pobres pela ocupação irregular, sem considerar a ausência de alternativas.',
  'Para revisar, monte um esquema: causas (êxodo rural, industrialização), características (rapidez, desordem, metropolização), problemas (moradia, transporte, saneamento, violência, segregação) e soluções (planejamento, Estatuto da Cidade, transporte público, regularização). Relacione com as migrações (tema anterior) e com a rede urbana (próximo tema), que mostra como as cidades se organizam em níveis e se relacionam entre si, e com a industrialização, que explica parte da concentração urbana no Sudeste.'] }
]},
{ t:'Rede e hierarquia urbana', txt:[
 { h:'O que é rede urbana e como as cidades se relacionam', p:[
  'A **rede urbana** é o conjunto de cidades de um território e as relações entre elas: fluxos de pessoas, mercadorias, informações, capitais e serviços. Cada cidade desempenha **funções** (comerciais, industriais, administrativas, turísticas, portuárias, universitárias, religiosas) e se liga às outras por **vias de transporte e de comunicação**. A rede se forma historicamente, e reflete o modelo de ocupação e de desenvolvimento do país. No Brasil, ela surgiu a partir do litoral, na colonização, com núcleos ligados à exportação, e foi se interiorizando com a mineração, o café, a pecuária, a industrialização e as fronteiras agrícolas.',
  'A organização da rede urbana segue a ideia de **hierarquia**: as cidades se distinguem pelo tamanho, pelo grau de influência e pela diversidade de bens e serviços que oferecem. Cidades pequenas atendem às necessidades básicas da população local (comércio simples, escolas, postos de saúde), e quem precisa de serviços mais especializados (hospitais de alta complexidade, universidades, grandes lojas, aeroportos internacionais) precisa se deslocar para cidades maiores. Assim, cada cidade exerce influência sobre as menores à sua volta, e é influenciada pelas maiores, formando uma **hierarquia** de níveis.',
  'A **teoria dos lugares centrais**, de Walter Christaller, explica que as cidades são "centros" que oferecem bens e serviços a uma área de influência, e que há uma relação entre o tamanho e a quantidade de funções. No Brasil, o **IBGE** estuda esse tema no estudo **Regiões de Influência das Cidades** (REGIC), que classifica as cidades em níveis: **metrópoles** (grandes e médias), **capitais regionais**, **centros sub-regionais**, **centros de zona** e **centros locais**. Essa classificação ajuda a planejar políticas públicas e a entender os fluxos entre as cidades.'] },
 { h:'A hierarquia urbana brasileira e as metrópoles', p:[
  'No topo da hierarquia urbana brasileira está **São Paulo**, classificada como a **grande metrópole nacional**, o principal centro financeiro, empresarial e de serviços especializados do país, e com influência sobre todo o território. Seguem-se o **Rio de Janeiro** e **Brasília**, classificados como metrópoles nacionais. O Rio, antiga capital, mantém grande peso cultural, turístico e de serviços, e Brasília é o centro político-administrativo. Em seguida, aparecem metrópoles regionais, como Belo Horizonte, Porto Alegre, Curitiba, Salvador, Recife, Fortaleza, Manaus, Belém e Goiânia, que lideram suas regiões.',
  'A influência de cada centro se estende por uma **região** própria. São Paulo concentra a sede das principais empresas e bancos, a Bolsa de Valores (B3), universidades, grandes hospitais, e aeroportos que conectam o Brasil ao mundo. Isso configura uma **cidade global** (ou mundial), integrada às redes de negócios internacionais. Manaus, Belém, Fortaleza e Recife são polos regionais, que organizam amplas áreas do Norte e do Nordeste, enquanto as cidades médias do interior (como Ribeirão Preto, Londrina, Campina Grande, Uberlândia, Maringá e Cuiabá) exercem influência em áreas ligadas ao agronegócio e aos serviços.',
  'A rede urbana brasileira é **desigual e concentrada**: o Sudeste e o Sul têm cidades mais numerosas e mais bem conectadas, enquanto na Amazônia, as cidades são mais distantes e dependem de rios, de estradas precárias e do transporte aéreo. Há ainda situações de **primazia urbana** em algumas regiões, em que uma única cidade domina uma região, como Manaus, no Amazonas. As mudanças recentes incluem o crescimento das cidades médias, a expansão do agronegócio, a interiorização da indústria e o aumento da conectividade digital, que tornam a rede mais complexa e menos centrada apenas nas metrópoles.'] },
 { h:'Funções das cidades, fluxos e a economia urbana', p:[
  'As cidades têm diferentes **funções**. Há cidades **industriais** (como as do ABC paulista), **portuárias** (Santos, Paranaguá), **turísticas** (Gramado, Fernando de Noronha, Foz do Iguaçu), **administrativas** (Brasília), **universitárias** (São Carlos, Campinas), **religiosas** (Aparecida, Juazeiro do Norte), **agroindustriais** (Ribeirão Preto, Cascavel), **mineradoras** (Parauapebas, Itabira) e **dormitórios**. Muitas combinam várias funções. A economia urbana se divide em atividades do **setor secundário** (indústria), do **terciário** (comércio e serviços) e, cada vez mais, do **quaternário**, ligado ao conhecimento e à tecnologia.',
  'Os **fluxos** entre as cidades são intensos: de pessoas (trabalho, estudo, saúde, lazer), de mercadorias (distribuição de produtos), de informações (mídia, internet) e de capitais (investimentos, bancos). A infraestrutura de **transportes** e de **comunicação** é essencial para esses fluxos: rodovias, ferrovias, portos, aeroportos e redes de telecomunicação. A **internet** e o comércio eletrônico reduziram o peso da distância, mas as cidades maiores continuam a concentrar os serviços mais sofisticados e os empregos de maior remuneração. A rede urbana é, portanto, um retrato da organização econômica do país.',
  'O setor **terciário** é o que mais emprega nas cidades, abrangendo desde o comércio e os serviços básicos até serviços sofisticados, como finanças, consultoria, tecnologia e saúde. A informalidade é grande: muitas pessoas trabalham como ambulantes, autônomos e prestadores de serviço sem vínculo formal, o que revela a desigualdade urbana. Nas últimas décadas, as **tecnologias digitais** mudaram o trabalho urbano, com os aplicativos de transporte e de entrega, e a "uberização", que gera flexibilidade, mas também precariedade. Esses aspectos aparecem nas provas, ligados à Sociologia do trabalho.'] },
 { h:'Planejamento urbano, cidades inteligentes e sustentáveis', p:[
  'Diante dos problemas urbanos, o **planejamento** é essencial. O **Plano Diretor**, obrigatório para cidades com mais de 20 mil habitantes, define como o município deve crescer, onde podem ficar as moradias, as indústrias e as áreas verdes, e deve ser elaborado com a participação da população. O **Estatuto da Cidade** (2001) prevê instrumentos, como o IPTU progressivo para terrenos ociosos, o direito de preempção e a regularização fundiária. A articulação entre as cidades de uma região metropolitana também exige **governança metropolitana**, para cuidar de temas comuns, como transporte, água, esgoto e lixo.',
  'O conceito de **cidade sustentável** envolve o uso eficiente de recursos, o transporte coletivo e não motorizado (bicicletas, caminhada), as áreas verdes, a gestão de resíduos, a moradia acessível e a redução das desigualdades. Experiências como o BRT de Curitiba, os corredores de ônibus, as ciclovias e a coleta seletiva são exemplos. As **cidades inteligentes** (smart cities) usam tecnologias de informação para gerir serviços, como o trânsito, a iluminação e a segurança, mas só são realmente inclusivas se contemplam toda a população, e não apenas as áreas mais ricas.',
  'Os **eventos de grande porte**, como a Copa do Mundo (2014) e as Olimpíadas (2016), e as grandes obras provocaram transformações urbanas, com benefícios e críticas, como as remoções de moradores e a gentrificação. A **gentrificação** é o processo em que áreas populares são valorizadas e passam a ser ocupadas por pessoas de maior renda, deslocando os antigos moradores. O **direito à cidade**, conceito proposto pelo sociólogo Henri Lefebvre, afirma que todos devem ter acesso aos benefícios da vida urbana e participar das decisões sobre o território, e orienta os debates atuais.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a rede e a hierarquia urbana aparecem em questões com mapas das regiões de influência, textos sobre metrópoles e cidades médias, funções urbanas e fluxos (de pessoas, mercadorias e informações), além de situações de planejamento urbano e mobilidade. A questão pode pedir para identificar a função de uma cidade a partir de uma descrição, ou explicar por que pessoas se deslocam de uma cidade menor para uma maior, ou ainda comentar o papel de São Paulo e do Rio de Janeiro na rede urbana.',
  'Pontos de atenção: a hierarquia depende da diversidade de funções e da influência, e não só do tamanho; São Paulo é a metrópole de maior influência e se conecta com o mundo; as cidades médias estão crescendo e têm papel de polo regional; os fluxos refletem as relações de dependência e de complementaridade; e o planejamento urbano deve ser participativo. Atenção à diferença entre a conurbação (união física) e a rede (relação funcional entre cidades, mesmo distantes). O ENEM valoriza a leitura de mapas e a interpretação de legendas.',
  'Para revisar, memorize os níveis da hierarquia (metrópoles, capitais regionais, centros sub-regionais, de zona e locais) e as funções urbanas. Relacione as cidades brasileiras mais importantes a suas funções e regiões de influência. Conecte o tema com a urbanização (anterior) e a industrialização (a seguir), que explicam por que a rede urbana é concentrada no Sudeste, e com os transportes e a logística, que sustentam os fluxos entre as cidades e entre elas e o campo.'] }
]},
{ t:'Industrialização brasileira', txt:[
 { h:'Das origens à industrialização por substituição de importações', p:[
  'A **industrialização brasileira** foi tardia em relação à dos países europeus e dos Estados Unidos. Durante o período colonial, a Coroa portuguesa proibiu a instalação de manufaturas, pelo pacto colonial (alvará de 1785). Só com a vinda da Corte, em 1808, o alvará foi revogado, mas a concorrência dos produtos ingleses, favorecida por tarifas baixas, limitou o desenvolvimento industrial. No século XIX, houve iniciativas isoladas, como as do Barão de Mauá, mas a economia continuava voltada à exportação de produtos primários (açúcar, algodão e, principalmente, café).',
  'O **café** teve papel importante. Os lucros acumulados pela cafeicultura, a infraestrutura de ferrovias e portos, a chegada de imigrantes (mão de obra livre e consumidores) e o crescimento das cidades criaram as condições para as primeiras indústrias, em geral, de bens de consumo não duráveis (tecidos, alimentos, calçados), em São Paulo e no Rio de Janeiro, no final do século XIX e início do XX. A **Primeira Guerra Mundial** reduziu as importações e estimulou a produção interna. Esse período é chamado de "industrialização restringida", pois a indústria dependia do setor cafeeiro.',
  'A **crise de 1929** e a queda das exportações de café mudaram o cenário. Com a crise, o governo Vargas adotou medidas de proteção e de incentivo à indústria, e iniciou o processo de **industrialização por substituição de importações**: a produção interna passou a substituir os produtos que antes eram importados. O Estado assumiu papel central, criando a **Companhia Siderúrgica Nacional** (CSN, 1941), a Vale do Rio Doce (1942), a Companhia Hidrelétrica do São Francisco e a CLT (1943). Era a fase da "industrialização pesada" e da formação da indústria de base (aço, energia), e da crescente urbanização e organização dos trabalhadores.'] },
 { h:'Do desenvolvimentismo ao capital estrangeiro e ao "milagre"', p:[
  'Nas décadas de 1950 e 1960, o **Plano de Metas** de Juscelino Kubitschek acelerou a industrialização, com a entrada de **capital estrangeiro** (empresas multinacionais) em setores de bens duráveis, em especial a **indústria automobilística** (Volkswagen, Ford, General Motors, Mercedes-Benz), instalada na região do ABC paulista, e de eletrodomésticos. O modelo, conhecido como "**tripé**" (Estado, capital nacional e capital estrangeiro), expandiu a produção industrial e as rodovias, mas aumentou a **dependência externa** e a concentração em São Paulo. Em 1953, foi criada a **Petrobras**, com o monopólio estatal do petróleo.',
  'Durante a **ditadura militar** (1964 a 1985), o Estado aprofundou a industrialização, com investimentos em infraestrutura (hidrelétricas, rodovias, telecomunicações), na indústria de base (siderurgia, petroquímica) e na indústria de bens de capital. O **"milagre econômico"** (1968 a 1973) provocou um crescimento muito alto, sustentado por crédito, arrocho salarial e empréstimos externos, e fortaleceu a **dívida externa**. Os **polos industriais** se espalharam, com a criação da Zona Franca de Manaus (1967), que atraiu indústrias eletrônicas e de motocicletas por meio de incentivos fiscais, e do polo petroquímico de Camaçari, na Bahia.',
  'Nos anos 1980, a crise da dívida externa e a **inflação** reduziram o crescimento, e a década ficou conhecida como a "década perdida". Nos anos 1990, a abertura comercial e as **privatizações** reconfiguraram a indústria: as empresas foram expostas à concorrência internacional, muitas se modernizaram e outras fecharam, e houve o fenômeno da **desindustrialização**, a redução do peso da indústria no PIB e no emprego. Setores como o automotivo e o de alimentos se mantiveram, e a **indústria de ponta** (aeronáutica, como a Embraer, e petróleo em águas profundas) se destacou.'] },
 { h:'A distribuição espacial da indústria e a desconcentração', p:[
  'A indústria brasileira se concentrou historicamente no **Sudeste**, em especial na região metropolitana de São Paulo, que reunia a maior parte da produção e do emprego industrial, em razão da proximidade da cafeicultura, do mercado consumidor, da infraestrutura (energia, portos, ferrovias), da mão de obra e do capital. Esse padrão formou o que alguns autores chamam de "**polígono industrial**", que vai de Belo Horizonte a Porto Alegre, passando por São Paulo, Rio de Janeiro e Curitiba. A concentração trouxe **deseconomias de aglomeração**: congestionamentos, poluição, custo da terra e dos salários, e conflitos com os sindicatos.',
  'A partir dos anos 1970 e 1980, ocorreu uma **desconcentração industrial**: indústrias se deslocaram da Grande São Paulo para o interior paulista (Campinas, São José dos Campos, Ribeirão Preto) e para outros estados, em busca de terrenos mais baratos, de incentivos fiscais e de mão de obra menos organizada, a chamada **"guerra fiscal"** entre estados. O Nordeste (Camaçari, Fortaleza, Suape), o Sul (Curitiba, Joinville, Caxias do Sul), Minas Gerais (Betim) e o Centro-Oeste (Goiás, com montadoras) atraíram fábricas. Em Manaus, a Zona Franca criou um polo industrial na Amazônia, mas dependente de insumos importados.',
  'Mesmo com a desconcentração, o **Sudeste** continua sendo o centro industrial, e **São Paulo** mantém a liderança em setores de maior valor agregado e em serviços avançados. As regiões que receberam indústrias nem sempre tiveram um desenvolvimento amplo: algumas ficaram com atividades de baixa tecnologia e dependentes de incentivos. O **agronegócio** gerou uma agroindústria importante no interior (processamento de soja, carnes, açúcar e etanol), ligando indústria e campo. As **cadeias produtivas** se tornaram mais complexas, com a divisão da produção entre várias regiões e países.'] },
 { h:'Desafios atuais: tecnologia, desindustrialização e sustentabilidade', p:[
  'A indústria brasileira enfrenta desafios. A **competitividade** é afetada pelo chamado "custo Brasil" (impostos, burocracia, logística cara e juros altos), pela baixa produtividade e por investimentos limitados em **pesquisa e inovação**. A concorrência de produtos importados, em especial da China, pressiona os setores de bens de consumo. O Brasil é forte na exportação de **commodities** (minério de ferro, soja, petróleo, carnes), que têm menor valor agregado do que os produtos industrializados e que tornam a economia mais vulnerável a oscilações de preços internacionais. O debate sobre a **reindustrialização** e a política industrial é constante.',
  'A **Quarta Revolução Industrial** traz novas tecnologias: automação, robótica, inteligência artificial, internet das coisas e impressão 3D. Elas aumentam a produtividade, mas também podem reduzir empregos e exigir novas qualificações, e o país precisa investir em **educação, ciência e tecnologia** para não ficar para trás. As **startups** e o setor de tecnologia crescem, em polos como São Paulo, Florianópolis, Recife (Porto Digital) e Belo Horizonte. A **energia** barata e limpa, a base agrícola e mineral e o mercado interno são vantagens para o crescimento.',
  'A questão **ambiental** também se impõe: a indústria é grande consumidora de energia e de água, e gera poluição e resíduos. A transição para uma **economia de baixo carbono**, com energias renováveis, eficiência energética, reciclagem e processos limpos, é uma exigência crescente, inclusive dos mercados internacionais. O exemplo do **etanol** e dos **biocombustíveis**, da **indústria de papel e celulose** e da **bioeconomia** mostra potenciais. A política industrial moderna procura aliar competitividade, inovação, empregos de qualidade e sustentabilidade, e é um tema frequente nos debates e nas questões do ENEM.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A industrialização brasileira aparece no ENEM em questões que pedem a explicação das fases (substituição de importações, entrada do capital estrangeiro, "milagre"), do papel do Estado (CSN, Petrobras), da concentração e da desconcentração espacial, da Zona Franca de Manaus, da guerra fiscal e dos efeitos da abertura econômica. Os enunciados trazem mapas das regiões industriais, gráficos do emprego e da produção, textos sobre empresas multinacionais e charges, e pedem para relacionar a industrialização com a urbanização e com as migrações.',
  'Pontos de atenção: a industrialização foi tardia e se apoiou no capital do café; a crise de 1929 e o governo Vargas inauguraram a substituição de importações; JK abriu a economia ao capital estrangeiro, em especial no setor automotivo; a ditadura expandiu a indústria com endividamento; a indústria se concentrou em São Paulo e depois se desconcentrou; a Zona Franca de Manaus é um polo incentivado; e a desindustrialização é a perda de peso da indústria no PIB. Desconfie de explicações que ignoram o papel do Estado e do capital estrangeiro.',
  'Para revisar, monte uma linha do tempo: 1808 (revogação do alvará), 1929 (crise), 1930 a 1945 (Vargas, CSN, CLT), 1956 a 1961 (JK), 1964 a 1985 (ditadura, milagre, Zona Franca), anos 1990 (abertura e privatizações), atualidade (inovação e desindustrialização). Relacione esse tema com a urbanização (anterior), a agropecuária e a questão agrária (próximo) e a energia e os transportes, que dão suporte à produção. Também serve de base para a Geografia econômica mundial, que estuda a globalização e a divisão internacional do trabalho.'] }
]}
];
