/* Geografia: textos corridos, temas 22 a 25 */
module.exports = [
{ t:'Regionalização do Brasil', txt:[
 { h:'O que é regionalizar e por que existem várias divisões do Brasil', p:[
  'A **regionalização** é a divisão de um território em partes, chamadas de regiões, que reúnem áreas com características comuns segundo algum critério: natural (clima, relevo, vegetação), econômico, social, cultural ou administrativo. Não existe uma única divisão correta: cada regionalização atende a um objetivo e a um contexto histórico. Uma região é uma construção, e seus limites podem mudar com o tempo. Por isso, o estudo da regionalização exige atenção ao critério usado e à finalidade da divisão, o que as provas costumam explorar.',
  'A divisão oficial mais conhecida é a do **IBGE**, usada para fins estatísticos e de planejamento, que separa o país em **cinco grandes regiões**: Norte, Nordeste, Centro-Oeste, Sudeste e Sul. Ela se baseia em critérios predominantemente naturais e políticos, e respeita os limites dos estados, o que facilita a coleta de dados. Foi proposta em 1970, e revista com a criação do estado de Tocantins (1988), que passou a integrar a Região Norte, e a do Mato Grosso do Sul (1977). Essa divisão, no entanto, agrupa áreas muito diferentes dentro de uma mesma região.',
  'Por isso, outras propostas procuram representar melhor a realidade econômica e social. A mais importante é a do geógrafo **Pedro Pinchas Geiger** (1967), que propõe as **três regiões geoeconômicas**, ou **complexos regionais**: a **Amazônia**, o **Nordeste** e o **Centro-Sul**. Os critérios são o processo histórico de formação, a organização econômica e a integração do espaço. Essa divisão atravessa os limites estaduais, ao contrário da do IBGE, e é muito usada nas análises econômicas e na compreensão das desigualdades regionais, aparecendo com frequência nas provas.'] },
 { h:'As cinco regiões do IBGE: características gerais', p:[
  'A **Região Norte** é a maior em extensão (cerca de 45% do território), tem a menor densidade demográfica e abrange a maior parte da Floresta Amazônica. É formada por sete estados (Acre, Amapá, Amazonas, Pará, Rondônia, Roraima e Tocantins). Tem economia baseada no extrativismo, na mineração (Carajás), na agropecuária e na indústria da Zona Franca de Manaus, e enfrenta desafios de desmatamento, de logística e de conflitos de terra. A população é concentrada nas capitais e ao longo dos rios, com forte presença de povos indígenas e de comunidades tradicionais.',
  'A **Região Nordeste** tem nove estados e é a região com a segunda maior população, com o litoral densamente povoado e o Sertão semiárido. Tem importância histórica, como berço da colonização, e uma economia que combina a cana-de-açúcar, o turismo, o petróleo, a fruticultura irrigada e a indústria. Concentra os piores indicadores sociais, mas tem melhorado. A **Região Centro-Oeste** (Goiás, Mato Grosso, Mato Grosso do Sul e Distrito Federal) é a fronteira agrícola do agronegócio (soja, milho, algodão e gado) e abriga Brasília, centro político do país.',
  'A **Região Sudeste** (São Paulo, Rio de Janeiro, Minas Gerais e Espírito Santo) é a mais populosa e a mais rica, e concentra a maior parte da indústria, dos serviços, das finanças e das universidades, e tem as maiores metrópoles do país. A **Região Sul** (Paraná, Santa Catarina e Rio Grande do Sul) tem forte tradição de imigração europeia, economia diversificada, com agropecuária moderna, indústria e turismo, e indicadores sociais em geral mais favoráveis. A distribuição desigual de riqueza entre as regiões é um dos traços marcantes do país, e uma das origens dos debates sobre as desigualdades regionais.'] },
 { h:'Os complexos regionais: Amazônia, Nordeste e Centro-Sul', p:[
  'Na regionalização de Geiger, a **Amazônia** inclui a maior parte da Região Norte e partes do Maranhão e do Mato Grosso. É a região menos povoada e a menos integrada ao restante do país, de ocupação histórica mais lenta, e hoje marcada pela expansão da fronteira agrícola e da mineração, e pelos conflitos de terra. O **Nordeste** inclui a Região Nordeste, exceto o oeste da Bahia e do Maranhão, e foi o centro econômico do período colonial, com a cana-de-açúcar. Mantém estrutura social desigual e economias diversas: Zona da Mata, Agreste, Sertão e Meio-Norte.',
  'O **Centro-Sul** é a região de maior integração econômica e de maior dinamismo, e abrange o Sudeste, o Sul, o Centro-Oeste e partes do Tocantins e da Bahia. Concentra a maior parte da indústria, dos serviços, da população e da produção agrícola moderna, e articula a rede urbana nacional. Sua formação está ligada ao ciclo do ouro, ao do café e à industrialização. A centralização econômica em São Paulo e a articulação entre indústria, agronegócio e serviços fazem do Centro-Sul o "coração" econômico do país, em relação ao qual as demais regiões se organizam, de forma complementar e dependente.',
  'Essa regionalização permite compreender as **desigualdades regionais**, que são históricas. O processo de ocupação do território seguiu ciclos econômicos que concentraram investimentos em áreas específicas, e as políticas de desenvolvimento regional (como a **SUDENE**, para o Nordeste, e a **SUDAM**, para a Amazônia, criadas na década de 1950 e 1960, e a **Zona Franca de Manaus**) buscaram reduzir os desequilíbrios, com resultados limitados. Mesmo com as mudanças recentes, como o crescimento do Centro-Oeste e do interior, e a desconcentração da indústria, as diferenças de renda, de infraestrutura e de acesso a serviços permanecem.'] },
 { h:'Desigualdades regionais, integração do território e novas regionalizações', p:[
  'As desigualdades regionais se manifestam em vários indicadores: renda per capita, IDH, mortalidade infantil, escolaridade, saneamento, acesso à saúde e emprego formal. O Sudeste e o Sul têm os melhores indicadores, e o Norte e o Nordeste, os mais baixos, embora com avanços nas últimas décadas, em razão das políticas de transferência de renda, do aumento do salário mínimo e da expansão do ensino superior. Dentro de cada região, também há grandes diferenças: entre o litoral e o Sertão, entre as capitais e o interior, entre áreas rurais e urbanas.',
  'A **integração do território** foi promovida pelo Estado, por meio de **rodovias**, **ferrovias**, **telecomunicações**, **energia** e da transferência da capital para **Brasília** (1960). A construção da Belém-Brasília e da Transamazônica, nos governos militares, e a ocupação do Centro-Oeste pela agropecuária, ligaram regiões antes isoladas. A expansão da rede de energia, com o Sistema Interligado Nacional, e da internet, também integra o território. O conceito de **"meio técnico-científico-informacional"**, do geógrafo Milton Santos, descreve áreas do território, em especial o Centro-Sul, onde a tecnologia, a ciência e a informação estão incorporadas ao espaço, e outras, menos.',
  'Propostas mais recentes de regionalização, do próprio IBGE, adotam as **Regiões Geográficas Imediatas e Intermediárias** (2017), que substituíram as mesorregiões e microrregiões, e se baseiam nos fluxos entre as cidades e na rede urbana. Também existem as **regiões metropolitanas**, as **bacias hidrográficas**, os **biomas** e os **domínios morfoclimáticos**, que são outras maneiras de olhar para o território. Cada recorte ilumina aspectos diferentes: o político e administrativo, o econômico, o natural e o cultural. Saber alternar entre esses recortes é uma competência importante em Geografia.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a regionalização aparece em questões que comparam a divisão do IBGE com a de Geiger, que pedem a identificação das características das regiões a partir de textos, mapas e dados, e que discutem as desigualdades regionais e as políticas para reduzi-las. Os enunciados podem trazer mapas dos complexos regionais, tabelas de indicadores sociais e econômicos e descrições de paisagens, e pedem o reconhecimento da região e a análise das relações entre ela e o resto do país. Também são cobrados os conceitos de região e de território.',
  'Pontos de atenção: a divisão do IBGE respeita os limites estaduais e tem finalidade estatística; a de Geiger se baseia na formação histórica e na integração econômica, e divide o país em Amazônia, Nordeste e Centro-Sul; o Centro-Sul é o mais integrado e dinâmico; o Nordeste e a Amazônia apresentam desafios específicos; as desigualdades regionais têm origem histórica; e as políticas de desenvolvimento regional tiveram resultados parciais. Evite tratar as regiões como blocos homogêneos: dentro de cada uma há contrastes importantes, como no Nordeste e no Sudeste.',
  'Para revisar, monte um quadro comparando as duas regionalizações (critério, regiões e usos), e outro com as cinco regiões do IBGE (estados, economia, população e problemas). Relacione o tema com a industrialização, com a urbanização e com a questão agrária, que explicam a concentração econômica no Centro-Sul. Os próximos temas, o Nordeste e o semiárido, a Amazônia e os povos tradicionais, aprofundam a análise de regiões e de populações com características e problemas específicos.'] }
]},
{ t:'Nordeste e semiárido', txt:[
 { h:'As sub-regiões do Nordeste', p:[
  'O **Nordeste** brasileiro, com nove estados, apresenta grande diversidade física e econômica, e costuma ser dividido em quatro **sub-regiões**: a **Zona da Mata**, o **Agreste**, o **Sertão** e o **Meio-Norte**. A **Zona da Mata** é a faixa litorânea, de clima tropical úmido, solo de massapê e de vegetação original de Mata Atlântica, hoje muito devastada. Foi o centro da economia açucareira e do povoamento colonial, e concentra grandes cidades, como Recife, Salvador e Maceió, e as maiores densidades demográficas. Ainda hoje, a cana-de-açúcar e o turismo litorâneo têm destaque.',
  'O **Agreste** é uma faixa de transição entre a Zona da Mata e o Sertão, com clima mais seco e relevo mais elevado (Planalto da Borborema). A agricultura é mais diversificada, com policultura e pecuária leiteira em pequenas propriedades, e há cidades médias dinâmicas, como Caruaru e Campina Grande, que são polos comerciais e de confecções. O **Sertão** é a região semiárida do interior, a maior em extensão, com clima quente e seco, vegetação de caatinga e pecuária extensiva, e agricultura de subsistência, e é a região mais afetada pelas secas. A irrigação criou polos de fruticultura, como Petrolina-Juazeiro.',
  'O **Meio-Norte** é uma zona de transição entre o Nordeste semiárido e a Amazônia, abrangendo o Maranhão e o Piauí, com clima mais úmido e a **Mata dos Cocais**, com babaçu e carnaúba. Tem importância no extrativismo e, recentemente, na expansão da soja no sul do Maranhão e do Piauí, no Matopiba, e é a sub-região de menor integração econômica. Além disso, o Nordeste possui economias específicas, como o polo petroquímico de Camaçari, o complexo portuário de Suape, o turismo e a produção de energia eólica, que se expandiu no litoral e no interior da região.'] },
 { h:'O semiárido: clima, vegetação e as secas', p:[
  'O **semiárido** é uma região de clima quente e seco, com chuvas escassas e muito irregulares (em geral, menos de 800 mm por ano), temperaturas elevadas e alta **evaporação**, que muitas vezes supera a precipitação. Ocupa cerca de 12% do território nacional e abriga mais de 25 milhões de pessoas, uma das áreas semiáridas mais povoadas do mundo. A vegetação típica é a **Caatinga**, adaptada à seca. Os **rios** são, em sua maioria, intermitentes, e secam na estiagem, com exceção do São Francisco e do Parnaíba, que são perenes, e atravessam a região, e os solos são rasos e pedregosos, em boa parte.',
  'As **secas** são recorrentes, e há registros históricos desde o período colonial, com grandes migrações, como as de 1877 e de 1915, retratadas por autores como Graciliano Ramos (Vidas Secas) e Rachel de Queiroz (O Quinze). As secas decorrem de fatores climáticos: a posição do semiárido, a atuação de massas de ar e de fenômenos, como o El Niño. Mas seu impacto social é consequência da **estrutura fundiária concentrada**, da pobreza, da falta de infraestrutura hídrica e do uso político da seca, a chamada "indústria da seca", em que obras e recursos beneficiavam, muitas vezes, os grandes proprietários, e não a população mais pobre.',
  'A visão tradicional, de **"combate à seca"**, com a construção de grandes açudes, poços e frentes de trabalho emergenciais, é criticada. Hoje, defende-se a **convivência com o semiárido**, com tecnologias adequadas ao clima: **cisternas** de captação da água da chuva (programa Um Milhão de Cisternas), barragens subterrâneas, manejo da caatinga, criação de animais adaptados (caprinos e ovinos), cultivos resistentes à seca e **agroecologia**. Experiências da sociedade civil, como as da Articulação do Semiárido (ASA), mostram que é possível viver bem no semiárido, com acesso à água e com políticas adequadas, e superar a imagem de região "inviável".'] },
 { h:'Água, transposição do São Francisco e desenvolvimento regional', p:[
  'O **rio São Francisco**, o "Velho Chico", nasce em Minas Gerais e atravessa o Nordeste. É fundamental para o abastecimento, a irrigação e a geração de energia (usinas de Três Marias, Sobradinho e Paulo Afonso). Sofre com o assoreamento, a poluição, o desmatamento das margens e a redução da vazão. O **Projeto de Integração do Rio São Francisco** (a transposição), iniciado em 2007, é uma grande obra que desvia parte das águas para bacias do semiárido do Nordeste Setentrional (Ceará, Paraíba, Rio Grande do Norte e Pernambuco), por canais, com o objetivo de abastecer cidades e áreas rurais. Seus eixos Norte e Leste somam mais de 700 km.',
  'A transposição é alvo de debate. Os defensores argumentam que ela leva água a milhões de pessoas e garante o abastecimento em regiões críticas. Os críticos apontam o alto custo, os atrasos, os impactos ambientais sobre o rio e as comunidades, a necessidade de revitalização da bacia, o risco de que a água beneficie, principalmente, grandes empreendimentos de irrigação e a dificuldade de manutenção dos canais. O ENEM costuma apresentar argumentos dos dois lados e pedir uma análise crítica. A **gestão da água** nas bacias, o uso eficiente e a participação da população são aspectos fundamentais.',
  'O **desenvolvimento regional** do Nordeste passou por várias fases. A **SUDENE** (1959), inspirada nas ideias de Celso Furtado, promoveu a industrialização por meio de incentivos fiscais, com polos como Camaçari (petroquímico), Suape (porto e indústria naval) e o de Fortaleza. Nas últimas décadas, crescem o **turismo**, a **fruticultura irrigada** (manga, uva), a **energia eólica e solar**, o agronegócio no oeste da Bahia e no Matopiba, a indústria e os serviços. Os programas de transferência de renda e o aumento do salário mínimo reduziram a pobreza e dinamizaram o consumo. Mesmo assim, a região mantém altas taxas de informalidade e de desigualdade, e menor acesso a serviços.'] },
 { h:'Cultura, migração e desafios sociais do Nordeste', p:[
  'O Nordeste é um dos principais **centros culturais** do país: a mistura de heranças indígenas, africanas e europeias deu origem a manifestações como o **forró**, o **frevo**, o **maracatu**, o **bumba meu boi**, o **cordel**, o **candomblé**, a **capoeira**, o **artesanato** e uma culinária marcante. Cidades históricas, como Salvador, Olinda, São Luís e Recife, têm patrimônio reconhecido. A literatura regional, de autores como Jorge Amado, Graciliano Ramos, Ariano Suassuna e João Cabral de Melo Neto, e a música de Luiz Gonzaga, Gilberto Gil e Caetano Veloso, são referências. Esse patrimônio é também fonte de turismo e de identidade.',
  'A **migração** é um traço marcante: durante o século XX, milhões de nordestinos, expulsos pela seca e pela concentração de terras, migraram para o Sudeste, o Centro-Oeste e a Amazônia, e foram essenciais para a industrialização e a construção de cidades como São Paulo e Brasília. Nos últimos anos, houve **migração de retorno**, atraída pelo crescimento econômico regional. Persistem, porém, problemas sociais: concentração de renda, pobreza em áreas rurais, **mortalidade infantil** acima da média, **analfabetismo** e baixa escolaridade, além da violência, em algumas áreas. A estrutura fundiária concentrada e a dependência de políticas públicas ainda marcam a região.',
  'O Nordeste também enfrenta o desafio da **sustentabilidade**: a desertificação em áreas do semiárido, o desmatamento da Caatinga, a poluição urbana, o crescimento desordenado das cidades litorâneas e os impactos do turismo e da especulação imobiliária. Ao mesmo tempo, tem grande **potencial**: energia solar e eólica, biodiversidade, cultura, turismo, fruticultura e posição geográfica privilegiada para o comércio com a Europa e a África. O estudante deve evitar estereótipos que reduzem a região à seca e à pobreza, e reconhecer sua diversidade, suas lutas e suas contribuições ao país, algo valorizado nas provas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O Nordeste e o semiárido são frequentes no ENEM, em textos literários (Vidas Secas, Morte e Vida Severina) e em questões que tratam da seca, da transposição do São Francisco, das cisternas e da convivência com o semiárido, da estrutura fundiária, da migração, do turismo, da energia eólica e do desenvolvimento regional. Os enunciados trazem mapas das sub-regiões, climogramas do Sertão, gráficos de indicadores sociais e imagens da paisagem, e pedem para relacionar as condições naturais com as sociais e políticas.',
  'Pontos de atenção: as quatro sub-regiões (Zona da Mata, Agreste, Sertão e Meio-Norte) têm características distintas; a seca é um fenômeno climático, mas seus efeitos são socialmente construídos; a "indústria da seca" refere-se ao uso político dos recursos; a convivência com o semiárido propõe tecnologias adaptadas, como as cisternas; a transposição é polêmica; e o Nordeste vive transformações econômicas (energia renovável, fruticultura, turismo). Evite estereótipos e valorize o olhar sobre a diversidade e as soluções locais.',
  'Para revisar, monte um quadro das sub-regiões (clima, vegetação, economia, cidades) e um esquema do problema da seca (causas naturais, causas sociais, soluções). Relacione o tema com a estrutura fundiária (questão agrária), as migrações, a hidrografia (São Francisco), a energia (eólica e solar) e os climas do Brasil. Em seguida, estude a Amazônia, outra região de grande importância ambiental e social, com desafios muito distintos, mas igualmente relacionados à ocupação do território e aos conflitos pela terra.'] }
]},
{ t:'Amazônia', txt:[
 { h:'Características naturais e importância da Amazônia', p:[
  'A **Amazônia** é a maior floresta tropical do mundo e abriga a maior biodiversidade do planeta. A **Amazônia Legal**, definida por lei para fins de planejamento, abrange cerca de 5 milhões de km² (cerca de 60% do território brasileiro), em nove estados (Acre, Amapá, Amazonas, Pará, Rondônia, Roraima, Tocantins, Mato Grosso e parte do Maranhão). Seu clima é **equatorial**, quente e úmido, com chuvas abundantes, e sua vegetação principal é a **Floresta Equatorial**, densa, perene, com árvores de grande porte e mais de 40 mil espécies de plantas, centenas de mamíferos e milhares de peixes e de aves.',
  'A **bacia Amazônica** é a maior bacia hidrográfica do mundo, com o rio **Amazonas**, o mais caudaloso, e centenas de afluentes (Negro, Solimões, Madeira, Tapajós, Xingu), que formam uma enorme rede de rios, importante para a navegação e para a vida das populações ribeirinhas. O relevo é de **planícies** e baixos planaltos, e os solos são, em geral, **pobres em nutrientes**, pois são antigos e lixiviados, e a fertilidade está na biomassa e na serrapilheira, e não no solo. Há áreas de **terra firme**, **várzea** (inundada sazonalmente por rios de águas brancas, férteis) e **igapó** (alagadas por rios de águas pretas).',
  'A Amazônia presta **serviços ambientais** essenciais: regula o clima regional e global, pois armazena enormes quantidades de carbono, e a evapotranspiração das árvores forma os "**rios voadores**", massas de vapor que levam umidade às regiões Centro-Oeste, Sudeste e Sul, importantes para a agricultura e o abastecimento; mantém a biodiversidade e o ciclo da água; e abriga populações tradicionais e povos indígenas. Seu desmatamento ameaça esses serviços e pode levar a um **ponto de não retorno**, em que a floresta se transformaria em savana degradada, com efeitos graves para o clima e para a economia.'] },
 { h:'A ocupação histórica e os grandes projetos', p:[
  'A ocupação da Amazônia pelos portugueses foi lenta e concentrada ao longo dos rios, com missões religiosas, fortes e a coleta de "drogas do sertão" (cravo, cacau, castanha). No final do século XIX e início do XX, o **ciclo da borracha** trouxe grande prosperidade a cidades como Manaus e Belém, e atraiu milhares de nordestinos para os seringais, onde viveram em regime de exploração. Com a concorrência da borracha asiática, o ciclo entrou em crise, e a região perdeu importância econômica, com um breve novo ciclo na Segunda Guerra, os "soldados da borracha".',
  'A partir dos anos 1960 e 1970, durante a ditadura militar, o governo adotou uma política de **integração e de ocupação** da Amazônia, com o lema "integrar para não entregar", fundada em razões geopolíticas e econômicas. Foram criadas a **SUDAM** e a **Zona Franca de Manaus** (1967), foram abertas rodovias, como a **Transamazônica** e a **Belém-Brasília**, e programas de colonização, que atraíram migrantes do Sul e do Nordeste, além de grandes projetos de mineração (**Carajás**, no Pará, de ferro) e de hidrelétricas (**Tucuruí**). Essas medidas dinamizaram a economia, mas trouxeram desmatamento, conflitos fundiários e impactos sobre os povos indígenas.',
  'Nas últimas décadas, a **fronteira agropecuária** avançou, com a pecuária, a soja e a exploração de madeira, formando o "**arco do desmatamento**", no sul e no leste da região. A construção de hidrelétricas, como as de **Santo Antônio** e **Jirau** (rio Madeira) e **Belo Monte** (rio Xingu), gerou polêmica pelos impactos sobre os rios, a fauna e as comunidades. O garimpo ilegal, o desmatamento ilegal, a grilagem de terras públicas e o avanço do crime organizado ameaçam a floresta e as populações. A urbanização também é intensa: a maioria da população amazônica vive em cidades, com problemas de saneamento e de moradia.'] },
 { h:'Populações, economia e o debate sobre o desenvolvimento', p:[
  'A Amazônia é habitada por **povos indígenas** (mais de 150 povos, na região), **comunidades tradicionais** (seringueiros, ribeirinhos, quilombolas, castanheiros e quebradeiras de coco), agricultores familiares, migrantes e população urbana. As **terras indígenas** e as **unidades de conservação** ocupam cerca de metade da região e atuam como barreiras ao desmatamento, segundo estudos. A defesa dos direitos territoriais desses povos é central, e o líder seringueiro **Chico Mendes**, assassinado em 1988, tornou-se símbolo da luta por uma forma de uso da floresta compatível com sua conservação, que originou as **reservas extrativistas**.',
  'A economia da Amazônia é diversificada e contraditória. Há **extrativismo vegetal** (açaí, castanha, borracha, madeira), **pecuária**, **agricultura**, **mineração** (ferro, bauxita, ouro, cassiterita e manganês), **indústria** (Zona Franca de Manaus, com eletroeletrônicos e motocicletas), **hidroeletricidade** e **turismo**. O **valor da floresta em pé** é cada vez mais reconhecido, com a **bioeconomia**, a produção de fitoterápicos e cosméticos, o manejo florestal sustentável, o ecoturismo e os mercados de carbono. O desafio é aliar renda, inclusão social e conservação, em um modelo diferente do baseado na derrubada da floresta.',
  'O debate sobre o **desenvolvimento** da Amazônia envolve interesses distintos. Para alguns, a região deve ser ocupada e explorada, com mais estradas, mineração e agropecuária, para gerar riquezas e empregos. Para outros, o modelo deve ser sustentável, com proteção da floresta e dos povos, valorização da biodiversidade e ciência. Há ainda a questão da **soberania** e da cobiça internacional: a Amazônia é território brasileiro e a internacionalização da floresta não tem fundamento legal, mas a comunidade internacional tem interesse em sua preservação, pelos efeitos globais, o que exige cooperação, como no Fundo Amazônia e nos acordos climáticos.'] },
 { h:'Desafios atuais: desmatamento, garimpo, conflitos e conservação', p:[
  'O **desmatamento** é monitorado por satélites do **INPE** (sistemas PRODES e DETER), e as taxas variam conforme as políticas públicas, a fiscalização e os preços das commodities. Suas principais causas são a pecuária extensiva, a grilagem, a exploração madeireira e a expansão agrícola. As **queimadas**, usadas para limpar áreas desmatadas, geram fumaça e emissões de carbono. O **garimpo** ilegal, em terras indígenas como a dos Yanomami, contamina rios com mercúrio e causa problemas de saúde e conflitos violentos. O crime organizado, o tráfico e a **violência no campo** também ameaçam ambientalistas e lideranças.',
  'As estratégias de **conservação** incluem a criação de Unidades de Conservação e a demarcação de terras indígenas, a fiscalização e o combate aos crimes ambientais, o uso de tecnologia de monitoramento, a regularização fundiária, a **rastreabilidade** da cadeia da carne e da soja, os acordos setoriais, como a Moratória da Soja, os incentivos econômicos à floresta em pé e o apoio às comunidades tradicionais. O **Fundo Amazônia**, com recursos de países como a Noruega e a Alemanha, financia projetos de combate ao desmatamento. A **COP30**, em Belém (2025), colocou a Amazônia no centro das discussões sobre o clima.',
  'A **população amazônica** enfrenta carências de infraestrutura, de saneamento, de saúde, de educação e de transporte, em função das longas distâncias e do isolamento, com muitas comunidades acessíveis apenas por barcos. A **conectividade** digital e a energia são desafios. Garantir direitos, serviços e oportunidades é fundamental, porque a conservação depende de que as pessoas que vivem na floresta tenham alternativas econômicas viáveis. O ENEM costuma valorizar o olhar que integra a dimensão ambiental, a social e a econômica, e reconhece o papel das populações locais como parte da solução.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Amazônia é um dos temas mais recorrentes do ENEM. As questões abordam o desmatamento e o "arco do desmatamento", as queimadas, o garimpo, as hidrelétricas (Belo Monte), a Zona Franca de Manaus, os rios voadores, a biodiversidade, as populações tradicionais e os povos indígenas, o extrativismo e a bioeconomia, a soberania e a cooperação internacional. Os enunciados trazem mapas, imagens de satélite, gráficos de desmatamento e reportagens, e pedem a análise de causas, consequências e propostas, valorizando a visão crítica e equilibrada.',
  'Pontos de atenção: a Amazônia tem solos pobres e a floresta se sustenta pela ciclagem de nutrientes; os rios voadores influenciam as chuvas do Centro-Sul; a ocupação teve ciclos (drogas do sertão, borracha, integração militar, agropecuária); o desmatamento se liga à pecuária, à grilagem e ao garimpo; as terras indígenas e as UCs ajudam a preservar a floresta; e as soluções envolvem a fiscalização, a bioeconomia e a participação das comunidades. Evite ideias simplistas, como a de que a preservação impede qualquer atividade econômica, ou o contrário.',
  'Para revisar, monte uma linha do tempo da ocupação (drogas do sertão, borracha, integração dos anos 1960 e 1970, projetos de mineração, arco do desmatamento, bioeconomia) e um quadro de problemas e soluções. Relacione o tema com as mudanças climáticas, com a questão ambiental, com a hidrografia, com a vegetação e com a questão agrária. Em seguida, o último tema da matéria, povos tradicionais e território, aprofunda a questão dos direitos territoriais de indígenas, quilombolas e comunidades que vivem na Amazônia e em outras regiões.'] }
]},
{ t:'Povos tradicionais e território', txt:[
 { h:'Quem são os povos e comunidades tradicionais', p:[
  'Os **povos e comunidades tradicionais** são grupos culturalmente diferenciados, que se reconhecem como tais, possuem formas próprias de organização social e ocupam e usam territórios e recursos naturais como condição para a reprodução cultural, social, religiosa e econômica, com conhecimentos transmitidos por gerações. No Brasil, entre eles estão os **povos indígenas**, os **quilombolas**, os **ribeirinhos**, os **seringueiros**, os **extrativistas**, os **caiçaras**, os **pescadores artesanais**, as **quebradeiras de coco babaçu**, os **povos de terreiro**, os **ciganos**, os **faxinalenses**, entre muitos outros. A diversidade cultural brasileira se deve, em grande parte, a eles.',
  'O conceito de **território** é central. Para esses grupos, o território não é apenas uma terra para produzir, mas um espaço de vida, de identidade, de memória e de espiritualidade. Há uma relação de **pertencimento**, em que a natureza é parte da cultura. Por isso, a perda do território significa a perda do modo de vida. Essa concepção contrasta com a visão da terra como mercadoria e bem de produção, que predomina no mercado. A diferença entre as duas ideias é fonte de muitos **conflitos**, especialmente com a expansão do agronegócio, da mineração, das hidrelétricas e da especulação imobiliária.',
  'Os **direitos** desses povos foram reconhecidos em documentos nacionais e internacionais. A **Constituição de 1988** reconheceu aos indígenas os direitos originários sobre as terras que tradicionalmente ocupam, e aos quilombolas, a propriedade definitiva das terras ocupadas. A **Convenção 169 da OIT** (1989), ratificada pelo Brasil, garante a consulta prévia, livre e informada sobre medidas que os afetem. A **Política Nacional de Desenvolvimento Sustentável dos Povos e Comunidades Tradicionais** (2007) reconhece seus direitos. Mesmo assim, a efetivação desses direitos é lenta e enfrenta resistências.'] },
 { h:'Os povos indígenas e a demarcação de terras', p:[
  'Segundo o **Censo 2022**, o Brasil tem cerca de **1,7 milhão de indígenas**, de mais de 300 povos e cerca de 270 línguas, presentes em todos os estados, em áreas rurais e urbanas. Antes da chegada dos europeus, a população era de milhões de pessoas, e a colonização provocou um enorme **genocídio**, por guerras, doenças e escravização. No século XX, a política indigenista visava à "integração" e à assimilação, e o **SPI** (1910) e, depois, a **FUNAI** (1967) foram criados para protegê-los, mas atuaram, em muitos casos, de modo tutelar e com violações. A partir da Constituição de 1988, o Estado reconhece a organização social, os costumes e as línguas.',
  'As **terras indígenas** são bens da União, e de uso exclusivo dos povos que as ocupam, com **posse permanente**. A **demarcação** é um processo administrativo, com etapas de estudo, delimitação, declaração, demarcação física e homologação, conduzido pela FUNAI. Cerca de 13% do território nacional é de terras indígenas, em sua maioria na Amazônia. A demarcação é muito debatida: de um lado, setores do agronegócio e da mineração a criticam; de outro, os indígenas e entidades de defesa dos direitos afirmam que a proteção do território é fundamental à sua sobrevivência, e estudos apontam que as terras indígenas são as que mais conservam a floresta.',
  'O debate sobre o chamado **marco temporal**, tese segundo a qual os indígenas só teriam direito às terras que ocupavam em 5 de outubro de 1988, é um dos temas mais atuais. O **Supremo Tribunal Federal** decidiu, em 2023, contra essa tese, entendendo que os direitos são originários e anteriores ao Estado, mas o tema continua em discussão no Congresso. Outros conflitos envolvem a invasão por garimpeiros e madeireiros, a violência contra lideranças, a falta de assistência à saúde e à educação, e a defesa da cultura. Os próprios povos indígenas se organizam em associações e em movimentos, como a **APIB**.'] },
 { h:'Quilombolas, ribeirinhos, extrativistas e outras comunidades', p:[
  'As **comunidades quilombolas** descendem de pessoas escravizadas que resistiram e se organizaram em quilombos, e mantêm tradições, vínculos com o território e modos de vida próprios. A Constituição (art. 68 do ADCT) garante a elas a **propriedade definitiva** das terras que ocupam, e o processo de **titulação**, conduzido pelo INCRA, é lento. Há milhares de comunidades, como as do Vale do Ribeira (SP), do Quilombo de Kalunga (GO) e de Oriximiná (PA), mas poucas receberam a titulação. Elas enfrentam conflitos fundiários, a pressão de grandes empreendimentos e a falta de políticas de saúde, educação e infraestrutura.',
  'Os **ribeirinhos** vivem às margens dos rios, sobretudo na Amazônia, com a pesca, o extrativismo e a agricultura de várzea, e organizam sua vida pelo regime das águas. Os **seringueiros**, após a luta de Chico Mendes, conquistaram as **reservas extrativistas**, áreas de uso sustentável da floresta, de propriedade pública e uso coletivo. As **quebradeiras de coco babaçu**, no Maranhão, Tocantins e Piauí, lutam pelo livre acesso aos babaçuais. Os **caiçaras** vivem no litoral do Sudeste e do Sul e dependem da pesca artesanal, e os **pescadores artesanais** enfrentam a degradação dos ambientes aquáticos e a competição com a pesca industrial.',
  'Esses grupos têm saberes sobre a biodiversidade, o manejo dos recursos, as plantas medicinais e os ciclos da natureza, que são importantes para a conservação e para a ciência, e reconhecidos como **patrimônio cultural imaterial**. O **conhecimento tradicional associado à biodiversidade** é protegido por lei, e a repartição de benefícios de seu uso, por exemplo, em medicamentos e cosméticos, deve contemplar as comunidades. Muitos desses povos vivem em áreas de grande valor ambiental, e atuam como **guardiões da floresta**. A sua presença é, portanto, parte da solução para os desafios ambientais, e não um obstáculo ao desenvolvimento.'] },
 { h:'Conflitos, justiça social e proteção dos territórios', p:[
  'Os **conflitos territoriais** envolvem a disputa entre diferentes concepções e interesses sobre o uso do território: de um lado, a lógica da terra como mercadoria e a expansão de atividades econômicas de larga escala; de outro, a lógica do território como espaço de vida e de cultura. As consequências incluem o desmatamento, a poluição de rios, a perda de territórios, o deslocamento forçado, a violência e o assassinato de lideranças. O Brasil é um dos países mais perigosos do mundo para os defensores do meio ambiente e dos direitos territoriais. A ausência de regularização fundiária e a impunidade agravam o problema.',
  'A noção de **justiça socioambiental** destaca que os grupos mais vulneráveis, como os povos tradicionais, suportam a maior parte dos impactos negativos do modelo de desenvolvimento, sem desfrutar dos benefícios. O reconhecimento da **diversidade cultural** e dos direitos desses povos faz parte de uma sociedade democrática. As políticas públicas incluem a demarcação e a titulação dos territórios, a proteção contra invasões, a consulta prévia, a educação escolar indígena e quilombola, o acesso à saúde diferenciada (os DSEI, distritos sanitários indígenas), a valorização das línguas e o apoio às economias sustentáveis.',
  'Também se discute a relação entre esses povos e o **Estado**, a **sociedade** e o **mercado**. A cidadania plena exige combater o **preconceito** e o racismo, ainda presentes, e a invisibilidade das culturas tradicionais. A participação política, como a eleição de indígenas e quilombolas para cargos, e a criação do Ministério dos Povos Indígenas (2023), são sinais de mudança. No plano internacional, a Declaração da ONU sobre os Direitos dos Povos Indígenas (2007) reafirma esses direitos. Compreender essa dimensão é essencial para uma visão de Brasil plural, que a Geografia e o ENEM valorizam.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM aborda os povos tradicionais e o território em questões sobre a demarcação das terras indígenas, o marco temporal, os quilombos e a titulação, os conflitos com o agronegócio, a mineração e as hidrelétricas, os saberes tradicionais, as reservas extrativistas, a cultura e a língua, e a violência contra lideranças. Os enunciados trazem mapas das terras indígenas, trechos da Constituição e de convenções, relatos de lideranças e reportagens. A habilidade principal é compreender o território como espaço de vida e de cultura, e discutir o direito à terra e à diferença.',
  'Pontos de atenção: a Constituição de 1988 reconheceu os direitos originários dos indígenas e a titulação das terras quilombolas; o território tem valor cultural, e não apenas econômico; as terras indígenas e as reservas extrativistas contribuem para a conservação ambiental; a demarcação é um processo administrativo e muitas vezes lento; os conflitos envolvem agronegócio, garimpo e grandes obras; e a consulta prévia, livre e informada é um direito. Atenção às expressões que tratam os povos como "obstáculo ao desenvolvimento": o ENEM valoriza a perspectiva dos direitos e da diversidade.',
  'Para revisar, monte um quadro: povo ou comunidade, território, modo de vida, direito constitucional e principais conflitos. Relacione o tema com a questão agrária, com a Amazônia, com a questão ambiental e com a história da escravidão e da colonização. Esse é o último tema de Geografia, e fecha um percurso que une natureza, sociedade, economia e política. Na revisão final, faça ligações entre os temas: o clima, a vegetação e a hidrografia explicam as paisagens; a população, a urbanização e a indústria, as dinâmicas sociais; a globalização e a geopolítica, o mundo atual.'] }
]}
];
