/* Geografia: textos corridos, temas 10 a 12 */
module.exports = [
{ t:'Questão ambiental no Brasil', txt:[
 { h:'Os problemas ambientais e suas origens históricas', p:[
  'A **questão ambiental** reúne os problemas decorrentes da relação entre a sociedade e a natureza: o uso dos recursos naturais, a poluição, a degradação dos ecossistemas e as consequências sociais desses processos. No Brasil, ela tem raízes históricas. Desde a colonização, a economia se baseou na **exploração intensiva** de recursos para a exportação: o pau-brasil, a cana-de-açúcar, o ouro, o café e, depois, a borracha, a soja e a pecuária. Esse modelo, de ocupação extensiva e baixa preocupação com a conservação, deixou marcas profundas, como a devastação da Mata Atlântica.',
  'No século XX, o **crescimento industrial e urbano** acelerado, sobretudo a partir dos anos 1950, trouxe novos problemas: poluição do ar, da água e do solo nas grandes cidades, geração de resíduos, ocupação de áreas de risco, e grandes obras de infraestrutura (hidrelétricas, rodovias) com impactos sobre ecossistemas e populações. Na ditadura militar, a política de integração da Amazônia, com a abertura de estradas (Transamazônica) e incentivos à ocupação, estimulou o desmatamento e provocou conflitos com povos indígenas e posseiros. A preocupação ambiental só ganhou força institucional a partir dos anos 1970 e 1980.',
  'Marcos importantes foram a criação da **Secretaria Especial do Meio Ambiente** (1973), a **Política Nacional do Meio Ambiente** (1981), que instituiu o licenciamento ambiental e o Sisnama, a **Constituição de 1988**, que dedicou um capítulo ao meio ambiente, a realização da **Rio-92** no Brasil, a **Lei de Crimes Ambientais** (1998), a criação do **IBAMA** (1989) e do **ICMBio** (2007) e o **Código Florestal**. Hoje, o país tem uma legislação ambiental ampla, mas a sua aplicação enfrenta desafios, como a falta de fiscalização, os conflitos de interesse e as pressões do setor agropecuário e minerador.'] },
 { h:'Desmatamento, queimadas e mineração na Amazônia e no Cerrado', p:[
  'O **desmatamento** é o principal problema ambiental do Brasil. Na **Amazônia**, concentra-se no chamado "**arco do desmatamento**", faixa que vai do leste do Pará ao Acre, passando por Mato Grosso e Rondônia. Suas causas são a **pecuária extensiva**, a expansão da **soja**, a extração ilegal de **madeira**, a **grilagem** (apropriação ilegal de terras públicas), a abertura de estradas e o **garimpo**. A derrubada de florestas reduz a biodiversidade, altera o regime de chuvas, emite carbono e prejudica povos indígenas e comunidades tradicionais. O monitoramento por satélite (como o PRODES e o DETER, do INPE) acompanha as taxas.',
  'As **queimadas** são usadas para limpar o terreno e renovar pastagens, mas, em períodos secos, escapam do controle e provocam **incêndios** de grandes proporções, como os que atingiram o **Pantanal** e a Amazônia nos últimos anos. Liberam gases de efeito estufa e fumaça, afetando a saúde da população e a qualidade do ar. O **Cerrado**, cuja expansão agrícola é recente, perdeu cerca de metade da vegetação nativa, e sofre com a perda de nascentes, já que abriga a origem de grandes bacias. A **Caatinga** e a **Mata Atlântica** também enfrentam desmatamento e fragmentação.',
  'A **mineração** é outra atividade de grande impacto. O **garimpo** ilegal, sobretudo de ouro, em terras indígenas e unidades de conservação, contamina os rios com **mercúrio**, e causa problemas graves de saúde nas populações, como no caso dos Yanomami. A mineração industrial, como a de ferro em Minas Gerais e no Pará, gera grandes volumes de rejeitos, e acidentes com barragens, como os de **Mariana** (2015) e **Brumadinho** (2019), causaram mortes e destruição ambiental, e revelaram falhas de fiscalização. Esses episódios são muito citados nas provas, como exemplos dos riscos de um modelo de exploração sem controle.'] },
 { h:'Poluição, resíduos, urbanização e conflitos socioambientais', p:[
  'Nas **cidades**, os principais problemas são a poluição do ar (veículos e indústrias), a **poluição da água** (esgoto sem tratamento, lixo e efluentes), a geração de resíduos sólidos, as ilhas de calor, a ocupação de encostas e várzeas e a falta de saneamento. Os **lixões** a céu aberto contaminam o solo e a água, e a **Política Nacional de Resíduos Sólidos** (2010) determinou o fim dos lixões, a coleta seletiva, a logística reversa e a responsabilidade compartilhada. A cobertura de esgoto tratado ainda é insuficiente em grande parte do país, e é um dos principais obstáculos à saúde pública e à qualidade dos rios.',
  'A **agropecuária** também causa impactos: o uso intensivo de **agrotóxicos** (o Brasil é um dos maiores consumidores do mundo) contamina o solo, a água e os alimentos, e afeta a saúde de trabalhadores e de populações rurais; a **monocultura** reduz a biodiversidade; e a **pecuária** é grande emissora de gases de efeito estufa. A **energia hidrelétrica**, apesar de renovável, alaga grandes áreas, altera os rios, afeta a fauna aquática e desloca populações, como nos casos de Balbina, Tucuruí e Belo Monte. Os **derramamentos de petróleo** no mar e na costa também preocupam.',
  'Esses problemas dão origem a **conflitos socioambientais**, que opõem grupos com interesses distintos pelo uso dos recursos: povos indígenas, quilombolas, ribeirinhos e seringueiros, de um lado, e fazendeiros, madeireiros, mineradoras e empreendimentos, de outro. O assassinato de líderes, como **Chico Mendes** (1988), da missionária **Dorothy Stang** (2005) e de lideranças indígenas, mostra a violência desses conflitos. O conceito de **injustiça ambiental** descreve a situação em que os mais pobres e vulneráveis sofrem a maior parte dos danos (lixões, áreas de risco, poluição), enquanto os benefícios se concentram em outros grupos.'] },
 { h:'Políticas ambientais e desenvolvimento sustentável', p:[
  'O **desenvolvimento sustentável** busca conciliar o crescimento econômico, a justiça social e a conservação ambiental. No Brasil, as principais ferramentas são as **Unidades de Conservação** (UCs), divididas em **proteção integral** (parques nacionais, reservas biológicas, estações ecológicas) e **uso sustentável** (florestas nacionais, reservas extrativistas, áreas de proteção ambiental), as **terras indígenas** e os territórios quilombolas, que cumprem papel decisivo na contenção do desmatamento, o **licenciamento ambiental** de obras e a **fiscalização** pelos órgãos ambientais. O **Fundo Amazônia**, financiado por outros países, apoia projetos de combate ao desmatamento.',
  'Outras estratégias incluem o **zoneamento ecológico-econômico**, que define os usos adequados de cada área, o **pagamento por serviços ambientais**, a certificação de produtos (como a madeira com selo FSC), a moratória da soja, a recuperação de áreas degradadas, o fomento à **agricultura de baixo carbono** e à integração lavoura-pecuária-floresta, e a ampliação das **energias renováveis**. A **educação ambiental** e a participação social, por meio de conselhos e comitês, são fundamentais. Também ganha espaço a ideia de **bioeconomia**, que valoriza os produtos da floresta em pé, como o açaí, a castanha e os fitoterápicos.',
  'O Brasil assumiu compromissos internacionais, como o **Acordo de Paris**, com metas de redução de emissões, e abriga conferências, como a Rio-92 e a Rio+20. Ainda assim, há tensões entre o discurso e a prática: a pressão por novas áreas agrícolas e minerais, a flexibilização de regras e a redução de fiscalização, em alguns períodos, aumentaram o desmatamento. Para o estudante, é importante compreender que a **questão ambiental é também social, econômica e política**: as soluções dependem de decisões coletivas, de ciência e de participação, e não apenas de ações individuais.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A questão ambiental brasileira é um dos temas mais frequentes do ENEM, e aparece em Geografia, Biologia, Química e Sociologia. As questões trazem reportagens sobre desmatamento, queimadas, garimpo, rompimento de barragens, poluição urbana, lixo, agrotóxicos e obras como Belo Monte, gráficos de desmatamento e mapas de Unidades de Conservação e de terras indígenas, e pedem a identificação das causas, dos impactos e das medidas mais adequadas. A lógica é articular os aspectos ambientais com os sociais e econômicos.',
  'Pontos de atenção: o desmatamento amazônico está ligado à pecuária, à soja, à grilagem e ao garimpo; as terras indígenas e as UCs ajudam a conter o desmatamento; os acidentes de Mariana e Brumadinho mostram falhas no licenciamento e na fiscalização; os resíduos exigem coleta seletiva e logística reversa; e as soluções precisam considerar as comunidades locais. Evite respostas que apresentem a preservação como oposta ao desenvolvimento: o ENEM costuma valorizar as soluções que combinam os dois, de forma sustentável.',
  'Para revisar, monte um quadro: problema, causa, consequência, exemplo e solução. Inclua desmatamento, queimadas, garimpo, barragens de rejeitos, poluição urbana, resíduos sólidos e agrotóxicos. Relacione o tema às mudanças climáticas, à vegetação e à hidrografia, vistas antes, e à agropecuária, à energia e à Amazônia, que virão em seguida. Esse conjunto de conteúdos também alimenta a redação, com repertório e propostas de intervenção sobre a preservação ambiental e o desenvolvimento sustentável.'] }
]},
{ t:'População: crescimento e estrutura', txt:[
 { h:'Conceitos básicos: população absoluta, densidade e crescimento', p:[
  'A **Demografia** é a ciência que estuda as populações humanas: seu tamanho, sua distribuição, sua composição e suas variações. A **população absoluta** é o número total de habitantes de um território, e a **população relativa** (ou densidade demográfica) é a razão entre a população e a área (habitantes por km²). A China e a Índia têm as maiores populações absolutas, com mais de 1,4 bilhão de habitantes cada, mas países pequenos e densamente povoados, como Mônaco e Singapura, têm as maiores densidades. A distribuição é desigual: cerca de 90% da população mundial vive no hemisfério Norte, em especial na Ásia.',
  'O **crescimento populacional** é a variação do número de habitantes em um período, resultado do **crescimento vegetativo** (diferença entre natalidade e mortalidade) e do **saldo migratório** (diferença entre imigração e emigração). A **taxa de natalidade** é o número de nascimentos por mil habitantes em um ano, e a de **mortalidade**, o de óbitos. A **taxa de fecundidade** é o número médio de filhos por mulher, e a **mortalidade infantil**, o número de mortes de crianças menores de 1 ano por mil nascidos vivos, um indicador importante da qualidade de vida. A **expectativa de vida** ao nascer mede a idade média esperada.',
  'A população mundial ultrapassou **8 bilhões** de pessoas em 2022. Cresceu lentamente até o século XVIII e, a partir da Revolução Industrial e dos avanços na medicina, na higiene e na produção de alimentos, passou por uma explosão: a queda da mortalidade, sem queda imediata da natalidade, aumentou o crescimento. Atualmente, o ritmo está diminuindo, com a queda da fecundidade na maioria dos países, e projeções indicam uma estabilização, ainda neste século. O crescimento é desigual: é maior em países pobres, principalmente na África Subsaariana, e menor, ou até negativo, em países ricos e em alguns da Europa Oriental e do Japão.'] },
 { h:'A transição demográfica', p:[
  'A **transição demográfica** descreve as mudanças nas taxas de natalidade e de mortalidade ao longo do desenvolvimento econômico e social, em quatro fases. Na **fase 1** (pré-transição), a natalidade e a mortalidade são altas, e o crescimento é baixo, como nas sociedades pré-industriais. Na **fase 2**, a mortalidade cai (por melhorias sanitárias e médicas), enquanto a natalidade permanece alta, e o crescimento é elevado. Na **fase 3**, a natalidade também começa a cair, em razão da urbanização, da educação, do trabalho feminino e do acesso a métodos contraceptivos, e o crescimento diminui. Na **fase 4**, as duas são baixas, e o crescimento é baixo ou nulo.',
  'Os países estão em diferentes estágios. Os **países desenvolvidos** (Europa, Japão e outros) completaram a transição, com baixa natalidade e envelhecimento populacional, e muitos têm taxas de fecundidade abaixo da necessária para a reposição (cerca de 2,1 filhos por mulher). Alguns países da **África Subsaariana** ainda estão nas fases iniciais, com alta natalidade e crescimento rápido. O **Brasil** passou por uma transição acelerada: a mortalidade caiu a partir da década de 1940 e a natalidade, a partir de 1960, e hoje a fecundidade está abaixo do nível de reposição, e a população deve começar a diminuir nas próximas décadas.',
  'As explicações para a queda da natalidade são múltiplas: **urbanização**, pois filhos custam mais na cidade e não contribuem para a renda; aumento da **escolaridade** e da **inserção da mulher no mercado de trabalho**; acesso a **métodos contraceptivos** e ao planejamento familiar; mudanças culturais e valorização da carreira; e redução da mortalidade infantil, que diminui a necessidade de ter muitos filhos. Essa interpretação se opõe à visão **malthusiana**, que previa que a população cresceria mais rápido do que os alimentos, e à **neomalthusiana**, que defende o controle de natalidade nos países pobres, criticada por ignorar a desigualdade e o papel do consumo dos países ricos.'] },
 { h:'Estrutura etária e pirâmides populacionais', p:[
  'A **estrutura da população** é descrita por faixas etárias (jovens, adultos e idosos) e pelo sexo, e representada pelas **pirâmides etárias**, gráficos em que a base indica os mais jovens e o topo, os mais velhos. Uma **pirâmide de base larga e topo estreito** (formato triangular) indica **alta natalidade** e baixa expectativa de vida, população jovem e crescimento rápido, típica de países pobres. Uma pirâmide de **base estreita e corpo largo** (formato de barril ou de urna) indica **baixa natalidade** e **envelhecimento**, típica de países desenvolvidos, e de países em transição avançada, como o Brasil de hoje.',
  'A população é dividida em **economicamente ativa** (PEA, aquela que trabalha ou procura emprego, em geral de 15 a 64 anos) e **dependente** (crianças e idosos). A **razão de dependência** é a relação entre os dependentes e os ativos. Quando a natalidade cai, e a proporção de adultos em idade ativa é grande em relação aos dependentes, ocorre o chamado **bônus demográfico**, uma janela de oportunidade para crescer, desde que haja emprego, educação e investimentos. O Brasil vive esse momento, que deve se encerrar nas próximas décadas, quando o aumento de idosos elevará a razão de dependência.',
  'O **envelhecimento da população** traz desafios: aumento dos gastos com **previdência social** e com **saúde**, necessidade de reformas e de cuidados com idosos, e redução da força de trabalho. Países como o Japão e a Itália já enfrentam o problema, e adotam políticas de incentivo à natalidade e à imigração. No Brasil, o número de idosos cresce rápido, e há debate sobre a reforma da previdência e a oferta de serviços. Já nos países de população jovem, o desafio é gerar empregos, escolas e serviços básicos para os jovens que chegam ao mercado de trabalho. Ler uma pirâmide etária é uma habilidade importante nas provas.'] },
 { h:'A população brasileira: distribuição, composição e indicadores', p:[
  'O Brasil tem cerca de **203 milhões** de habitantes (Censo 2022), e é o sétimo país mais populoso do mundo. A população se distribui de forma **desigual** pelo território: concentra-se no **litoral** e no **Sudeste** (cerca de 41%), refletindo a história da colonização e da industrialização, enquanto a Amazônia e o Centro-Oeste, de grande extensão, têm baixa densidade demográfica. A maior parte da população, cerca de 85%, vive em **cidades**. A **taxa de fecundidade** caiu de mais de 6 filhos por mulher, em 1960, para cerca de 1,6, hoje, abaixo do nível de reposição.',
  'Em relação à **composição**, a população brasileira é diversa, formada pela miscigenação de povos indígenas, europeus, africanos e, mais tarde, imigrantes de várias origens (italianos, alemães, japoneses, árabes e outros). Pelo critério da autodeclaração do IBGE, mais da metade da população se declara **parda ou preta**. A proporção de **mulheres** é ligeiramente maior que a de homens, principalmente nas faixas etárias mais altas, porque elas têm maior expectativa de vida. As desigualdades regionais, de raça e de renda aparecem nos indicadores de educação, saúde e trabalho.',
  'Os **indicadores sociais** ajudam a avaliar a qualidade de vida. O **IDH** (Índice de Desenvolvimento Humano) combina renda, educação e longevidade, e o Brasil tem valor alto, mas com forte desigualdade interna. A **mortalidade infantil** caiu muito, graças ao saneamento, à vacinação, ao pré-natal e ao aleitamento, mas continua mais alta nas regiões Norte e Nordeste. A **expectativa de vida** passou de cerca de 45 anos, em 1940, para mais de 75 anos. O **índice de Gini**, que mede a concentração de renda, mostra que o Brasil permanece entre os países mais desiguais do mundo, e o **IBGE** realiza o censo, a cada dez anos, para atualizar esses dados.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em questões de população, o ENEM costuma trazer pirâmides etárias, gráficos de natalidade e de mortalidade e tabelas de indicadores, e pede para identificar a fase da transição demográfica, relacionar a estrutura etária com os desafios sociais (educação para os jovens, previdência e saúde para os idosos) e interpretar a evolução da fecundidade. Também aparecem a discussão de Malthus e as políticas de controle de natalidade, como a política do filho único, da China, e o debate sobre o bônus demográfico no Brasil.',
  'Dicas: para ler a pirâmide, observe a **base** (natalidade), o **corpo** (população adulta) e o **topo** (idosos); lembre que base larga significa população jovem e alta natalidade, e base estreita com topo largo significa envelhecimento; ao ver a queda da natalidade, pense em urbanização, educação, trabalho feminino e contracepção; e relacione o envelhecimento com a previdência e a saúde. Atenção à diferença entre crescimento vegetativo (natalidade menos mortalidade) e crescimento total (que inclui as migrações).',
  'Para revisar, memorize os conceitos (população absoluta e relativa, natalidade, mortalidade, fecundidade, expectativa de vida, crescimento vegetativo), as fases da transição demográfica e os tipos de pirâmide. Treine a leitura de gráficos e de tabelas, e relacione os dados com políticas públicas. Esse tema se liga ao seguinte, as migrações, que completam a análise da dinâmica da população, e à urbanização brasileira, que explica a distribuição atual dos habitantes no território.'] }
]},
{ t:'Migrações', txt:[
 { h:'Conceitos e tipos de migração', p:[
  'A **migração** é o deslocamento de pessoas de um local para outro, com a intenção de mudar de residência, de forma temporária ou permanente. É um fenômeno tão antigo quanto a humanidade, e se intensificou com a industrialização, os transportes e a globalização. Quem sai de um local é **emigrante** e quem chega a outro é **imigrante**. O **saldo migratório** é a diferença entre os que chegam e os que saem. Os deslocamentos podem ocorrer dentro do país (migração **interna**) ou entre países (migração **externa** ou internacional), e podem ser voluntários ou forçados.',
  'Quanto à duração e ao padrão, a migração pode ser **permanente** (definitiva), **temporária** ou **sazonal** (como a dos trabalhadores que vão colher cana ou café em certos meses), e **pendular** (movimento diário entre a casa e o trabalho ou a escola, comum nas regiões metropolitanas, como entre as cidades da Grande São Paulo). O **êxodo rural** é a migração do campo para a cidade, e a **migração inter-regional** envolve regiões diferentes do país. As **migrações de retorno** ocorrem quando as pessoas voltam ao local de origem, como tem ocorrido, em parte, do Sudeste para o Nordeste.',
  'As migrações podem ser compreendidas pelos **fatores de repulsão** (que expulsam as pessoas do local de origem) e de **atração** (que as atraem ao destino). Entre os de repulsão, estão a pobreza, o desemprego, a concentração de terra, as secas, as guerras, as perseguições e os desastres. Entre os de atração, as oportunidades de emprego, os salários mais altos, os serviços de saúde e educação, a segurança e a liberdade. As **redes de apoio**, como parentes e conhecidos que já migraram, também influenciam as decisões. A migração é, em geral, resultado de uma combinação de fatores econômicos, políticos, ambientais e sociais.'] },
 { h:'As migrações internas no Brasil', p:[
  'O Brasil teve importantes ciclos de migração interna. Entre as décadas de 1950 e 1980, ocorreu um intenso **êxodo rural**, ligado à industrialização e à modernização da agricultura, com a concentração de terras, a mecanização e a perda de empregos no campo. Milhões de pessoas deixaram o campo e foram para as cidades, o que fez o país passar de predominantemente rural a urbano. O principal fluxo foi do **Nordeste para o Sudeste**, em especial para São Paulo e Rio de Janeiro, em busca de emprego na indústria e na construção civil, e motivado pelas secas e pela estrutura fundiária concentrada.',
  'Outros movimentos incluem a migração para a **fronteira agrícola** do Centro-Oeste e do Norte, nas décadas de 1970 e 1980, incentivada pelo governo (construção de Brasília, rodovias e projetos de colonização) e pela expansão da soja e da pecuária, com a chegada de migrantes sulistas e nordestinos, e o deslocamento para a **Amazônia**, atraído pela mineração e pela abertura de terras. A construção de **Brasília** (1960) atraiu os "candangos" de várias regiões. Esses processos tiveram consequências, como a pressão sobre as florestas e os conflitos com povos indígenas e posseiros.',
  'Mais recentemente, houve mudanças. O fluxo para o Sudeste diminuiu, com a desconcentração industrial, a crise e o desemprego, e cresceu a **migração de retorno** ao Nordeste, que passou a ter economia mais dinâmica, com programas de transferência de renda e investimentos. Ganhou força a migração entre cidades médias e para o interior, e a migração **pendular**, dentro das regiões metropolitanas, que revela a segregação espacial: muitos trabalham em uma cidade e moram em outra, mais distante e barata, o que gera longos deslocamentos e problemas de mobilidade.'] },
 { h:'Migrações internacionais, refugiados e imigração no Brasil', p:[
  'Nas migrações internacionais, o fluxo predominante vai de países pobres ou em conflito para os ricos, como Estados Unidos, Canadá, países da Europa Ocidental, do Golfo Pérsico e Austrália. Os motivos incluem a busca de trabalho, a reunião familiar e a fuga de guerras e perseguições. As **remessas** de dinheiro enviadas pelos imigrantes às famílias são fonte importante de renda para muitos países. Os países receptores, em geral, precisam de mão de obra, mas ao mesmo tempo, adotam **controles** de entrada, muros e restrições, e há grupos que alimentam a **xenofobia** e o racismo contra imigrantes.',
  'Os **refugiados** são pessoas que deixam seus países por temor fundado de perseguição por raça, religião, nacionalidade, opinião política ou grupo social, ou por conflitos armados e graves violações de direitos humanos, e são protegidos pelo direito internacional (Convenção de 1951), em especial pelo princípio de não devolução. Os maiores fluxos recentes vieram da Síria, do Afeganistão, da Venezuela, do Sudão do Sul e de Mianmar. A **Agência da ONU para Refugiados** (ACNUR) coordena a assistência. Os refugiados enfrentam travessias perigosas, como a do Mediterrâneo, e dificuldades de integração.',
  'O **Brasil** foi destino de grandes fluxos de imigrantes europeus, asiáticos e árabes, entre o final do século XIX e o início do XX, que trabalharam nas lavouras de café e nas indústrias, e foi o destino forçado de milhões de africanos escravizados, até 1850. Nos últimos anos, recebeu **haitianos**, **venezuelanos**, bolivianos, angolanos e sírios, entre outros. A **Lei de Migração** (2017) garante direitos aos migrantes e rejeita a discriminação. Ao mesmo tempo, o Brasil tem milhões de **emigrantes** vivendo no exterior, como os "dekasseguis" no Japão e muitos nos EUA e na Europa, em busca de melhores oportunidades.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O tema das migrações é muito presente no ENEM, por sua importância social e por permitir abordagens históricas, geográficas e sociológicas. As questões trazem mapas de fluxos migratórios, gráficos do saldo migratório por região, textos sobre refugiados e imigrantes (Síria, Venezuela, Haiti), notícias sobre muros, xenofobia e acolhida, e relatos de trabalhadores migrantes. A pergunta costuma ser sobre causas, consequências e implicações dos deslocamentos, para os locais de origem e de destino, e sobre os direitos dos migrantes.',
  'Pontos de atenção: o êxodo rural brasileiro foi impulsionado pela mecanização e pela concentração de terras; o fluxo Nordeste-Sudeste foi o mais importante do século XX, e hoje há migração de retorno; a migração pendular é típica de regiões metropolitanas; refugiados fogem de guerras e perseguições e têm proteção internacional; a imigração gera benefícios (mão de obra, diversidade, desenvolvimento) e desafios (integração, preconceito). Evite explicações simples demais, como a de que os imigrantes "tiram empregos": as questões costumam valorizar a análise crítica e os dados.',
  'Para revisar, esquematize: tipos de migração (interna e externa; permanente, temporária, sazonal e pendular), fatores de repulsão e de atração, principais fluxos brasileiros (campo-cidade, Nordeste-Sudeste, fronteira agrícola, retorno) e internacionais (refugiados, imigrantes no Brasil). Relacione o tema com a urbanização brasileira, que veremos a seguir, e com a questão agrária, que explica parte do êxodo rural. Esse conjunto de conteúdos também fornece repertório sociocultural para a redação, sobretudo em propostas sobre acolhida e direitos humanos.'] }
]}
];
