/* Geografia: textos corridos, temas 1 a 3 */
module.exports = [
{ t:'Cartografia: escalas e projeções', txt:[
 { h:'O que é Cartografia e como se lê um mapa', p:[
  'A **Cartografia** é a ciência e a técnica de representar a superfície da Terra em mapas, cartas e plantas. Como a Terra é aproximadamente esférica (um geoide), e o papel ou a tela são planos, toda representação envolve **simplificações** e **distorções**. Um mapa nunca é uma cópia neutra da realidade: ele seleciona o que mostrar, em que tamanho, com quais cores e símbolos, e esse conjunto de escolhas reflete interesses e pontos de vista. Aprender a ler mapas, portanto, é também aprender a interpretar mensagens e a perceber o que está em destaque e o que foi omitido.',
  'Um mapa completo traz alguns elementos essenciais. O **título** indica o tema e o recorte. A **legenda** explica os símbolos e as cores usados. A **escala** informa a relação entre as distâncias no mapa e na realidade. A **orientação** (rosa dos ventos ou seta do Norte) indica a direção. A **fonte** e a data mostram a origem dos dados. Os mapas podem ser **topográficos** (relevo e acidentes geográficos), **temáticos** (um assunto, como população, clima ou economia) e **políticos** (divisões territoriais). Os mapas temáticos usam diferentes recursos, como cores graduadas, símbolos e setas, para mostrar quantidades e fluxos.',
  'Hoje, a Cartografia conta com tecnologias que transformaram a produção e o uso dos mapas. O **sensoriamento remoto**, feito por satélites e aeronaves, captura imagens da superfície, e o **GPS** (Sistema de Posicionamento Global) determina localizações precisas. Os **SIG** (Sistemas de Informações Geográficas) permitem cruzar camadas de dados em um mesmo mapa digital, usados em planejamento urbano, agricultura, defesa civil e meio ambiente. Aplicativos de navegação e de mapas na internet popularizaram o uso cotidiano da Cartografia, o que torna ainda mais importante entender como esses mapas são construídos.'] },
 { h:'Escalas: numérica, gráfica e a relação com o detalhe', p:[
  'A **escala** é a razão entre a distância medida no mapa e a distância correspondente no terreno. Na **escala numérica**, é indicada por uma fração ou razão, como 1:100.000, que significa que 1 centímetro no mapa equivale a 100.000 centímetros na realidade, ou seja, 1 quilômetro. Na **escala gráfica**, é representada por uma barra dividida em segmentos, que mostram diretamente as distâncias reais. Esse segundo tipo tem a vantagem de se manter correto quando o mapa é ampliado ou reduzido, o que não ocorre com a escala numérica.',
  'Para calcular distâncias, mede-se a distância no mapa e multiplica-se pelo denominador da escala. Por exemplo, em um mapa de escala 1:500.000, dois pontos a 6 cm de distância estão a 6 × 500.000 = 3.000.000 cm, ou seja, 30 km. Convém sempre converter as unidades (centímetros para metros ou quilômetros) com cuidado. Questões do ENEM costumam fornecer a escala e uma distância medida, pedindo a distância real, ou o contrário, e a conversão correta de unidades é o ponto principal para não errar.',
  'Existe uma relação importante entre a escala e o **nível de detalhe**. Uma **escala grande** (como 1:1.000 ou 1:10.000, com denominador pequeno) representa uma **área pequena** com **muitos detalhes**, como a planta de uma casa ou de um bairro. Uma **escala pequena** (como 1:10.000.000, com denominador grande) representa uma **área grande** com **poucos detalhes**, como um mapa-múndi. Esse é um ponto que causa confusão: o "grande" e o "pequeno" se referem à fração, e não ao território. Quanto menor o denominador, maior a escala, e maior o grau de detalhamento.'] },
 { h:'Projeções cartográficas e suas distorções', p:[
  'A **projeção cartográfica** é o método matemático usado para transferir a superfície curva da Terra para um plano. Como não é possível fazer isso sem deformações, cada projeção privilegia certos aspectos e distorce outros. As projeções podem preservar os **ângulos e as formas** (**conformes**), as **áreas** (**equivalentes**), as **distâncias** (**equidistantes**) ou apenas buscar um compromisso (**afiláticas**). A escolha depende do uso: navegação, estudo da distribuição de populações ou ensino. Não existe uma projeção perfeita, e é essencial saber qual é o tipo de distorção de cada uma.',
  'Quanto à superfície de projeção, as projeções podem ser **cilíndricas** (como se um cilindro envolvesse a Terra), **cônicas** (um cone) e **planas** ou **azimutais** (um plano tangente a um ponto). A **projeção de Mercator** (1569) é cilíndrica e conforme: preserva os ângulos e as formas locais, o que a tornou ideal para a **navegação**, pois uma linha reta no mapa corresponde a uma direção constante. Em contrapartida, distorce muito as **áreas**, que crescem em direção aos polos: a Groenlândia parece do tamanho da África, embora a África seja cerca de 14 vezes maior, e a Europa parece maior em relação aos países tropicais.',
  'A **projeção de Peters** (ou Gall-Peters) é cilíndrica e **equivalente**: preserva as proporções entre as áreas, mas deforma as formas, que ficam alongadas nas regiões equatoriais e achatadas perto dos polos. Foi defendida por Arno Peters, em 1973, como alternativa mais justa, que mostraria o tamanho real dos países do Sul global. Outras projeções são a **Robinson**, de compromisso, usada em mapas-múndi escolares, e a **projeção azimutal**, usada em mapas centrados nos polos, como o emblema da ONU. A **UTM** é usada em mapeamento topográfico, em zonas de 6° de longitude, e preserva bem as formas.'] },
 { h:'Cartografia, poder e ideologia', p:[
  'Os mapas são também **instrumentos de poder**. A escolha do centro do mapa, do ponto de vista e da projeção expressa visões de mundo. Os mapas-múndi tradicionais colocam a Europa no centro, com o hemisfério Norte na parte de cima, o que reflete a centralidade histórica dos países europeus. Em outras partes do mundo, é comum ver mapas centrados na própria região, e o mapa invertido da América Latina, que coloca o Sul no topo, desafia essa convenção, lembrando que "norte" e "sul" são convenções, e não verdades naturais. A Cartografia política revela quem tem poder para definir fronteiras e nomes.',
  'Historicamente, os mapas foram usados para a **conquista e a administração** de territórios: os mapas das Grandes Navegações, as cartas coloniais, os mapas militares. Hoje, são usados para demarcar áreas de conservação e terras indígenas, para o planejamento das cidades, para a gestão de riscos, para o monitoramento do desmatamento e para o controle de fronteiras. Quem produz os dados e as imagens detém poder de decisão, e, por isso, há debates sobre o acesso à informação geográfica e sobre a necessidade de **cartografia participativa**, em que as comunidades produzem seus próprios mapas.',
  'A **anamorfose** é um tipo de representação em que o tamanho dos países ou das regiões é deformado de acordo com uma variável (população, PIB, emissões), em vez da área real. Ela é útil para mostrar desigualdades de forma clara: em um mapa de anamorfose da população, a Índia e a China ficam enormes, enquanto países extensos e pouco povoados, como o Canadá, encolhem. Esse tipo de mapa aparece em provas, e requer a leitura atenta do título e da legenda, para saber qual variável determina o tamanho. Isso ilustra a ideia de que os mapas são construções com finalidades específicas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Cartografia é um tema recorrente, quase sempre com mapas, gráficos e imagens de satélite. As questões pedem o cálculo de distâncias com escalas, a identificação da escala maior ou menor, a comparação entre projeções (distorção de áreas e formas), a leitura de legendas e a interpretação de mapas temáticos e de anamorfose. Também podem tratar das geotecnologias (GPS, sensoriamento remoto e SIG) e de suas aplicações no monitoramento ambiental, na agricultura de precisão e no planejamento urbano.',
  'Dicas: ao calcular uma distância, converta a unidade antes de concluir; lembre que escala grande significa mais detalhe e área menor; em Mercator, as áreas próximas dos polos aparecem exageradas, enquanto em Peters as áreas são proporcionais; leia sempre a legenda e o título, pois o mapa temático depende deles; e atenção às fontes e às datas. Em questões de crítica ao mapa, pergunte-se: o que foi destacado? O que foi omitido? A quem interessa essa representação?',
  'Para revisar, monte uma tabela com as projeções (Mercator, Peters, Robinson e azimutal), o tipo (conforme, equivalente, de compromisso), a distorção e o uso. Pratique três exercícios de cálculo de escala, convertendo as unidades, e observe a diferença entre mapas em escala grande e em escala pequena. Esse tema serve de base para os seguintes: coordenadas geográficas e fusos horários, em que a localização exata na superfície terrestre é feita com latitudes e longitudes, e depois para o estudo do relevo e do clima, que são representados em mapas temáticos.'] }
]},
{ t:'Coordenadas geográficas e fusos horários', txt:[
 { h:'Linhas imaginárias: paralelos e meridianos', p:[
  'Para localizar qualquer ponto na superfície da Terra, usam-se linhas imaginárias, que formam uma grade, e a posição é indicada por **coordenadas geográficas**: a **latitude** e a **longitude**. Os **paralelos** são círculos paralelos ao plano do Equador, que se dispõem no sentido leste-oeste, e permitem medir a latitude. O mais importante é a **Linha do Equador**, um círculo máximo que divide a Terra em dois hemisférios: **Norte** (setentrional) e **Sul** (meridional). Já os **meridianos** são semicírculos que ligam os polos Norte e Sul, e permitem medir a longitude.',
  'Entre os paralelos notáveis, estão o **Trópico de Câncer** (23°27\' N) e o **Trópico de Capricórnio** (23°27\' S), que delimitam a zona tropical, onde o Sol pode estar a pino em algum momento do ano, e o **Círculo Polar Ártico** (66°33\' N) e o **Círculo Polar Antártico** (66°33\' S), que delimitam as zonas polares. Entre os trópicos e os círculos polares, estão as zonas temperadas. Essa divisão se relaciona à inclinação do eixo da Terra (cerca de 23,5°) e à incidência dos raios solares, e é importante para entender a distribuição dos climas.',
  'O principal meridiano é o de **Greenwich**, que passa por Londres, escolhido por convenção internacional, em 1884, como a origem (0°) para medir a longitude. Ele divide a Terra nos hemisférios **Leste** (oriental) e **Oeste** (ocidental). O meridiano oposto, de 180°, corresponde aproximadamente à **Linha Internacional da Data**. O Brasil fica quase todo no hemisfério Sul e no hemisfério Ocidental, e é cortado pela Linha do Equador, ao norte (no Amapá, no Pará e em Roraima), e pelo Trópico de Capricórnio, ao sul (em São Paulo e no Paraná), de modo que a maior parte do território está na zona intertropical.'] },
 { h:'Latitude e longitude: como determinar a localização', p:[
  'A **latitude** é a distância angular, em graus, de um ponto em relação ao Equador, e varia de 0° (no Equador) a 90° (nos polos), para o norte ou para o sul. Por exemplo, uma cidade a 23° S está no hemisfério Sul. A **longitude** é a distância angular, em graus, de um ponto em relação ao meridiano de Greenwich, e varia de 0° a 180°, para leste ou oeste. Por exemplo, 46° W indica uma posição a oeste de Greenwich. A combinação das duas, como 23° S e 46° W (aproximadamente São Paulo), define a localização exata de um ponto.',
  'Para ler as coordenadas em um mapa, procure o paralelo e o meridiano que se cruzam no ponto, e informe o valor com o hemisfério (N/S, L/O ou E/W). Em questões do ENEM, é comum dar as coordenadas de uma cidade e pedir em que hemisfério ela se situa, ou comparar a posição de dois locais. Um erro frequente é inverter latitude e longitude: lembre que a **latitude** é a "distância ao Equador", e a **longitude** é a "distância a Greenwich". Cada grau é dividido em 60 minutos e cada minuto em 60 segundos.',
  'A **latitude** influencia o clima, pois define a quantidade de energia solar que o local recebe: quanto mais próxima do Equador, maior a incidência dos raios solares e mais quentes as temperaturas médias; quanto mais próxima dos polos, mais inclinados os raios e mais frio. Já a **longitude** é relevante para o **horário local**, pois a Terra gira em torno de seu eixo, de oeste para leste, e o Sol atinge locais diferentes em momentos diferentes. Esses dois fatores, latitude e longitude, estão na base da orientação, da navegação e da divisão do tempo no planeta.'] },
 { h:'Movimentos da Terra e a divisão dos fusos horários', p:[
  'A Terra realiza dois movimentos principais. A **rotação** é o giro em torno do próprio eixo, de oeste para leste, que dura cerca de 24 horas e provoca a alternância entre dia e noite e a diferença de horários. A **translação** é o movimento ao redor do Sol, que dura cerca de 365 dias e 6 horas (o que justifica o ano bissexto, a cada quatro anos), e, combinada com a inclinação do eixo, provoca as **estações do ano**. Como a Terra gira 360° em 24 horas, ela gira 15° a cada hora (360 ÷ 24), ou 1° a cada 4 minutos.',
  'Com base nisso, o planeta foi dividido em **24 fusos horários**, cada um com 15° de longitude, e a diferença entre fusos vizinhos é de uma hora. O fuso de referência é o de Greenwich (GMT/UTC), e, para **leste**, os horários **adiantam** (somam-se horas), enquanto, para **oeste**, **atrasam** (subtraem-se horas). Uma boa memorização é: "quem está a leste vê o Sol nascer primeiro, e por isso tem a hora mais avançada". Se em Londres (0°) são 12h, em um local a 45° W são 9h (3 fusos a oeste), e em um a 45° E são 15h.',
  'Para resolver cálculos, divide-se a diferença de longitude por 15 para obter a diferença de horas. Por exemplo, entre os meridianos 45° W e 120° E, a diferença é de 165°, ou seja, 11 horas, e o local mais a leste está 11 horas adiantado. É preciso cuidado com o hemisfério (somar as longitudes quando estão em lados opostos de Greenwich e subtrair quando estão do mesmo lado). Essa técnica é a que mais aparece nas provas, que costumam pedir a hora em um local, a partir de um horário e de coordenadas fornecidos, ou o horário de uma transmissão ao vivo.'] },
 { h:'Os fusos do Brasil, o horário de verão e a Linha Internacional da Data', p:[
  'Como o Brasil é extenso no sentido leste-oeste, ele abrange vários fusos. Atualmente, são **quatro fusos** horários: o de **Fernando de Noronha** e das ilhas oceânicas (UTC -2), o **horário de Brasília** (UTC -3), que vale para as regiões Sul, Sudeste, Nordeste, Centro-Oeste (parte), Norte (parte) e o Distrito Federal; o do **Amazonas** (UTC -4), que abrange partes do Norte e do Centro-Oeste, como Mato Grosso, Mato Grosso do Sul, Amazonas, Rondônia, Roraima e parte do Pará; e o **Acre** e o sudoeste do Amazonas (UTC -5). A diferença de horário entre os extremos do país é de três horas.',
  'O **horário de verão** era a prática de adiantar os relógios em uma hora durante o verão, em algumas regiões do país, para aproveitar mais a luz do dia e reduzir o consumo de energia elétrica no horário de pico. Foi adotado no Brasil por muitos anos e **extinto em 2019**, pois seus benefícios se tornaram menores com a mudança nos hábitos de consumo de energia. Em outros países, ele permanece. A adoção ou não do horário de verão e a definição dos fusos são decisões políticas, que levam em conta a economia, a saúde e a vida social, e que variam entre os países.',
  'A **Linha Internacional da Data**, que corresponde aproximadamente ao meridiano de 180°, no oceano Pacífico, é a linha em que se muda a data do calendário. Quem a atravessa de oeste para leste "atrasa" um dia, e quem a atravessa de leste para oeste "adianta" um dia. Alguns países têm fusos com diferenças de meia hora (como a Índia, com +5h30) ou adotam um único fuso para todo o território, como a China, que tem extensão para cinco fusos, mas usa o horário de Pequim. Esses exemplos mostram que o horário oficial é uma construção social, e não só um fato astronômico.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Nas provas, esse tema aparece em questões de cálculo de horários, a partir de coordenadas ou de uma lista de cidades, em contextos como a transmissão de eventos internacionais, o horário de voos e conexões, o horário de pregões em bolsas de valores e o contato entre pessoas em países diferentes. Também podem aparecer questões sobre as zonas térmicas, a relação entre a latitude e o clima, a localização do Brasil em relação ao Equador e aos Trópicos e as consequências do horário de verão.',
  'Roteiro de resolução: 1) Identifique as longitudes de cada local e os hemisférios; 2) Calcule a diferença em graus e divida por 15; 3) Lembre-se de que, para leste, o horário adianta; 4) Aplique a diferença ao horário dado e ajuste o dia se necessário; 5) Verifique se o resultado faz sentido (um local mais a leste tem horário mais tarde). Muitas questões fornecem a hora de partida de um voo e a duração, e pedem a hora de chegada no fuso local, somando ou subtraindo a diferença de fusos.',
  'Para revisar, memorize: paralelos (leste-oeste, latitude), meridianos (norte-sul, longitude), Equador, trópicos, círculos polares, Greenwich; 15° por hora; leste adianta, oeste atrasa; o Brasil tem quatro fusos. Treine com três exercícios de diferença de horário, em locais de diferentes hemisférios. Esse tema se conecta ao anterior (Cartografia) e ao seguinte, a estrutura geológica e o relevo, que tratam da formação e da dinâmica da superfície terrestre.'] }
]},
{ t:'Estrutura geológica e relevo', txt:[
 { h:'A estrutura interna da Terra e a tectônica de placas', p:[
  'A Terra é formada por camadas concêntricas. A **crosta** (ou litosfera, com parte do manto superior) é a camada externa, sólida e fina, onde vivemos. Abaixo, está o **manto**, uma camada espessa, de rochas muito quentes, com comportamento viscoso. No centro, está o **núcleo**, dividido em **externo** (líquido) e **interno** (sólido), formado principalmente por ferro e níquel. A temperatura aumenta com a profundidade, e o calor interno é a fonte da dinâmica geológica do planeta, responsável pelos vulcões, terremotos e pela formação das cadeias de montanhas.',
  'A **teoria da tectônica de placas** explica essa dinâmica. A litosfera é dividida em grandes blocos, as **placas tectônicas**, que flutuam sobre a astenosfera (parte mais plástica do manto) e se movem lentamente, alguns centímetros por ano, impulsionadas pelas correntes de convecção do manto. A ideia nasceu da **deriva continental**, proposta por Alfred Wegener, em 1912, que observou o encaixe das costas da América do Sul e da África e a semelhança de fósseis e rochas, e propôs que os continentes já estiveram unidos em um supercontinente, a **Pangeia**, que se fragmentou há cerca de 200 milhões de anos.',
  'Nas bordas, as placas interagem de três maneiras. Nos limites **divergentes**, as placas se afastam, e o magma emerge, formando nova crosta, como na Dorsal Mesoatlântica. Nos **convergentes**, as placas se chocam: se uma desliza sob a outra (**subducção**), formam-se fossas oceânicas, vulcões e terremotos, como na costa do Pacífico (o chamado **Círculo de Fogo**), e se as duas são continentais, formam-se grandes cadeias montanhosas dobradas, como o Himalaia. Nos limites **transformantes**, as placas deslizam lateralmente, como na falha de San Andreas, na Califórnia, o que provoca terremotos.'] },
 { h:'Terremotos, vulcões e as estruturas geológicas do Brasil', p:[
  'Os **terremotos** (ou sismos) são vibrações da crosta causadas pela liberação súbita de energia acumulada nas falhas, e ocorrem principalmente nas bordas das placas. O ponto onde se origina o abalo é o **hipocentro**, e sua projeção na superfície é o **epicentro**. A magnitude é medida pela **escala Richter** (ou de magnitude de momento), e a intensidade, pela escala Mercalli. Os terremotos no mar podem gerar **tsunamis**, grandes ondas, como o de 2004, no oceano Índico. Os **vulcões** são aberturas por onde o magma, as cinzas e os gases chegam à superfície, e se concentram nas zonas de subducção e nas dorsais.',
  'O território brasileiro está no interior da **Placa Sul-Americana**, longe das bordas, o que explica a **estabilidade tectônica** do país: não há vulcões ativos e os terremotos são raros e de baixa magnitude. A **estrutura geológica** do Brasil é muito antiga. Predominam os **escudos cristalinos** (ou maciços antigos), do pré-cambriano, formados por rochas ígneas e metamórficas, ricas em minerais metálicos (ferro, manganês, ouro), como o Quadrilátero Ferrífero, em Minas Gerais, e a Serra dos Carajás, no Pará. Há também as **bacias sedimentares**, de formação mais recente, com rochas sedimentares, onde se encontram combustíveis fósseis, como o petróleo e o carvão.',
  'As principais bacias sedimentares são a **Amazônica**, a do **Paraná**, a do **Parnaíba** e a do **São Francisco**. As **coberturas vulcânicas** do **derrame basáltico** da bacia do Paraná, formadas há mais de 100 milhões de anos, deram origem à **terra roxa**, solo fértil, muito usado na agricultura. Já as **bacias sedimentares recentes** (quaternárias), como as planícies do Pantanal e do litoral, são de formação recente. A **Bacia de Santos** e a de Campos guardam as reservas do **pré-sal**, em rochas sob uma espessa camada de sal, no fundo do oceano, o que tem grande importância econômica.'] },
 { h:'As formas do relevo: agentes internos e externos', p:[
  'O **relevo** é o conjunto das formas da superfície terrestre, resultado da ação de dois tipos de agentes. Os **agentes internos** (ou endógenos) são os movimentos tectônicos, o vulcanismo e os terremotos, que **constroem** o relevo, criando montanhas, planaltos e vales. Os **agentes externos** (ou exógenos) são o clima, a água, o vento, o gelo, os seres vivos e as atividades humanas, que **esculpem** o relevo, por meio de processos de **intemperismo** (decomposição e fragmentação das rochas), **erosão** (desgaste e remoção do material), **transporte** e **sedimentação** (deposição). A interação entre ambos explica a diversidade das paisagens.',
  'O intemperismo pode ser **físico** (mecânico), quando a rocha se fragmenta por variações de temperatura, pela ação da água congelada nas fendas ou pelas raízes, **químico**, quando minerais são alterados pela água e pelo ar (como na dissolução do calcário, que forma cavernas), e **biológico**, pela ação de organismos. Nas regiões tropicais úmidas, o intemperismo químico é muito intenso, e gera solos profundos. Na erosão, a água dos rios e da chuva é o principal agente, e o vento tem destaque em regiões áridas. Os glaciares esculpem vales em forma de U e transportam grandes volumes de sedimentos.',
  'As principais formas de relevo são as **montanhas** (grandes elevações, como os Andes e o Himalaia, com formação em dobramentos modernos), os **planaltos** (superfícies elevadas, em geral onde predomina a erosão), as **planícies** (áreas baixas e planas, onde predomina a sedimentação) e as **depressões** (áreas rebaixadas em relação ao entorno). O que diferencia o planalto da planície não é a altitude, mas o processo dominante: no planalto, a erosão **remove** o material, e na planície, o processo dominante é a **deposição**. Essa distinção é uma pegadinha clássica nas provas.'] },
 { h:'O relevo brasileiro e suas classificações', p:[
  'O relevo do Brasil é, em geral, de **baixas altitudes**, com predomínio de planaltos e de depressões, e poucas áreas acima de 1.200 metros. O ponto mais alto é o **Pico da Neblina** (cerca de 2.995 m), no Amazonas, na Serra do Imeri. Não há grandes cadeias de dobramentos modernos, pois o território é geologicamente antigo, e as formas atuais resultam de longos processos de erosão. As classificações do relevo, feitas por especialistas, como **Aroldo de Azevedo**, **Aziz Ab\'Sáber** e **Jurandyr Ross**, descrevem as grandes unidades, e a mais usada atualmente é a de Ross, que considera as formas e os processos.',
  'Segundo Jurandyr Ross (1989), as grandes unidades do relevo brasileiro são: os **planaltos** (da Amazônia Oriental, Ocidental, as Guianas, Maranhão-Piauí, Central, Atlântico Nordeste e Sudeste, Meridional, entre outros), as **planícies** (Amazônica, do Pantanal, do litoral e dos rios Araguaia e Guaporé) e as **depressões** (Amazônica, Sertaneja e do São Francisco, Periférica da borda leste da bacia do Paraná, e outras). Também se destacam as **serras** do litoral (Serra do Mar e Mantiqueira), que fazem parte dos planaltos atlânticos, onde a erosão esculpiu escarpas e áreas bem acidentadas.',
  'O relevo influencia a ocupação humana, a agricultura, os transportes e a vulnerabilidade a riscos. Em áreas de **encostas** íngremes e de solo exposto, os **deslizamentos** são frequentes, e se agravam com a ocupação desordenada, o desmatamento e as chuvas intensas, como nas regiões serranas do Rio de Janeiro. Nas **planícies de inundação**, as cheias dos rios são naturais, mas se tornam desastres quando há ocupação das várzeas. Os **planaltos** de topo plano, como os do Centro-Oeste, favorecem a mecanização agrícola. Compreender o relevo é, portanto, essencial para o planejamento urbano e ambiental.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Nas provas, esse tema aparece em questões sobre a tectônica de placas e os fenômenos associados (terremotos, vulcões e tsunamis), a estabilidade geológica do Brasil, as estruturas geológicas e os recursos minerais, a diferença entre agentes internos e externos, o intemperismo e a erosão, e os riscos associados ao relevo. Os enunciados trazem mapas das placas tectônicas, perfis topográficos, fotografias de paisagens e esquemas do relevo, e pedem a identificação dos processos e das consequências para a ocupação humana.',
  'Pontos de atenção: terremotos e vulcões se concentram nas bordas das placas, e o Brasil, no centro da Placa Sul-Americana, é estável; os escudos cristalinos têm minerais metálicos, e as bacias sedimentares, combustíveis fósseis; os agentes internos constroem o relevo e os externos o modelam; planalto é onde predomina a erosão e planície, onde predomina a sedimentação; e as ações humanas alteram os processos de erosão e deslizamento. Evite confundir "planalto" com "altitude elevada" e lembre que o relevo brasileiro é, em geral, de baixa altitude.',
  'Para revisar, esquematize: estrutura da Terra (crosta, manto, núcleo) → placas tectônicas (limites divergentes, convergentes e transformantes) → estrutura geológica do Brasil (escudos, bacias sedimentares, derrames basálticos) → agentes do relevo (internos e externos) → formas (montanhas, planaltos, planícies e depressões) → relevo brasileiro e riscos. Esse tema prepara o seguinte, o estudo dos solos e da erosão, que depende diretamente da rocha de origem, do clima e do relevo, e é importante para a agricultura e o meio ambiente.'] }
]}
];
