/* Geografia: textos corridos, temas 7 a 9 */
module.exports = [
{ t:'Mudanças climáticas', txt:[
 { h:'O efeito estufa natural e o aquecimento global', p:[
  'O **efeito estufa** é um fenômeno natural, essencial para a vida na Terra. Parte da radiação solar que chega ao planeta é absorvida pela superfície, que emite calor na forma de radiação infravermelha. Alguns gases da atmosfera, os **gases de efeito estufa** (GEE), retêm parte desse calor, mantendo a temperatura média global em cerca de 15 °C. Sem esse efeito, a média seria de aproximadamente -18 °C, e o planeta seria praticamente inabitável. Os principais GEE naturais são o vapor de água, o dióxido de carbono (CO2), o metano (CH4) e o óxido nitroso (N2O).',
  'O problema é a **intensificação** do efeito estufa pelas atividades humanas. Desde a **Revolução Industrial**, a queima de combustíveis fósseis (carvão, petróleo e gás natural), o desmatamento, a agropecuária e os processos industriais aumentaram as concentrações de GEE na atmosfera. A concentração de CO2, por exemplo, passou de cerca de 280 ppm, no período pré-industrial, para mais de 420 ppm atualmente, um nível sem precedentes nas últimas centenas de milhares de anos. Com mais gases, mais calor fica retido, e a temperatura média global sobe, o que se chama de **aquecimento global**.',
  'Os dados do **IPCC** (Painel Intergovernamental sobre Mudanças Climáticas), que reúne cientistas de vários países, indicam que a temperatura média da Terra já subiu cerca de 1,1 °C em relação ao período pré-industrial, e que a influência humana é inequívoca. Os efeitos observados incluem o recuo de geleiras, a diminuição do gelo do Ártico, o aumento do nível do mar, a mudança nos padrões de chuva e a ocorrência de eventos extremos. É importante distinguir **clima** de **tempo**: um inverno frio isolado não contradiz o aquecimento global, que se refere a tendências de longo prazo.'] },
 { h:'As causas: combustíveis fósseis, desmatamento e agropecuária', p:[
  'A principal causa das emissões é a **queima de combustíveis fósseis**, usada para gerar energia elétrica, mover veículos, aquecer ambientes e abastecer as indústrias. Cada tonelada de carvão, de petróleo ou de gás queimado libera CO2, que estava armazenado há milhões de anos. Os países mais industrializados, como os Estados Unidos e os da Europa, são historicamente os maiores responsáveis pelas emissões acumuladas, e a **China** é hoje a maior emissora anual, seguida pelos EUA e pela Índia. Em termos per capita, os países ricos e os produtores de petróleo emitem muito mais do que os pobres.',
  'O **desmatamento** e as **queimadas** reduzem a capacidade de absorção de carbono pela vegetação e liberam o carbono armazenado nas árvores. No Brasil, essa é a principal fonte de emissões, diferentemente dos países industrializados: a derrubada da Amazônia e do Cerrado para a pecuária e a agricultura responde por uma grande parcela do total. A **agropecuária** emite metano pela fermentação entérica do gado (o "arroto" dos bovinos), pelo manejo de dejetos e pelas lavouras alagadas de arroz, e óxido nitroso, pelo uso de fertilizantes nitrogenados. O lixo orgânico em lixões e aterros também gera metano.',
  'Cada gás tem um **potencial de aquecimento** diferente: o metano retém cerca de 25 vezes mais calor que o CO2 em um período de 100 anos, mas permanece menos tempo na atmosfera, e o óxido nitroso é ainda mais potente. Por isso, as emissões são medidas em **CO2 equivalente**. Os **aerossóis** e outras partículas podem, por outro lado, refletir a luz solar e causar resfriamento localizado. Também há fatores naturais, como as variações da órbita da Terra e da atividade solar e as erupções vulcânicas, mas o ritmo atual do aquecimento só é explicado quando se inclui a atividade humana.'] },
 { h:'As consequências: gelo, oceanos, clima e sociedade', p:[
  'Entre as consequências físicas, está o **derretimento** das geleiras e das calotas polares, que eleva o nível do mar, também por causa da dilatação térmica da água. A previsão é de que áreas costeiras baixas, ilhas do Pacífico (como Kiribati e Tuvalu) e grandes cidades litorâneas, como Miami, Jacarta e Santos, enfrentem inundações e salinização das águas. Os **oceanos** absorvem cerca de um quarto do CO2 emitido, o que causa **acidificação** e prejudica organismos com conchas e esqueletos de calcário, como os corais, que também sofrem **branqueamento** com o aquecimento.',
  'O clima se altera, e os **eventos extremos**, como ondas de calor, secas prolongadas, tempestades, furacões, enchentes e incêndios florestais, tornam-se mais frequentes e intensos. Há mudanças na distribuição das chuvas: algumas regiões ficam mais secas, outras mais úmidas. Os ecossistemas sofrem: espécies migram para latitudes ou altitudes maiores, outras não conseguem se adaptar, e aumenta o risco de **extinção**. Na Amazônia, estudos alertam para um possível ponto de não retorno, em que a floresta se converteria parcialmente em savana, com graves efeitos sobre o clima regional e global.',
  'Os impactos **sociais e econômicos** são amplos: perdas agrícolas, insegurança alimentar, escassez de água, prejuízos em infraestrutura, riscos à saúde (doenças tropicais em novas regiões, calor extremo, doenças respiratórias) e **migrações forçadas**, os "refugiados climáticos". Esses efeitos são desiguais: atingem mais os países pobres e as populações vulneráveis, que menos contribuíram para o problema e têm menos recursos para se adaptar, o que levanta a discussão de **justiça climática**. A mudança do clima é, assim, um problema ambiental, econômico, social e político, e exige respostas coletivas.'] },
 { h:'Acordos internacionais e soluções', p:[
  'A comunidade internacional discute o problema desde os anos 1990. A **Rio-92** (Conferência da ONU sobre Meio Ambiente e Desenvolvimento) criou a Convenção-Quadro sobre Mudanças Climáticas. O **Protocolo de Kyoto** (1997) estabeleceu metas obrigatórias de redução das emissões para os países desenvolvidos, mas os EUA não o ratificaram, e países emergentes não tinham metas, o que limitou seus resultados. O **Acordo de Paris** (2015) foi um marco: quase todos os países se comprometeram a limitar o aquecimento global bem abaixo de 2 °C, buscando 1,5 °C, por meio de metas voluntárias (as NDCs, contribuições nacionalmente determinadas) e de revisão periódica. As conferências do clima (COP) reúnem os países todo ano.',
  'As soluções se dividem em **mitigação**, que busca reduzir as emissões, e **adaptação**, que prepara as sociedades para os impactos. A mitigação inclui a **transição energética**, com a substituição dos combustíveis fósseis por fontes **renováveis** (solar, eólica, hidrelétrica, biomassa), o aumento da **eficiência energética**, o transporte coletivo e elétrico, o combate ao **desmatamento**, o **reflorestamento**, a agricultura de baixo carbono e a captura e armazenamento de carbono. O **mercado de carbono** e os **créditos de carbono** criam incentivos econômicos para reduzir as emissões, embora sejam debatidos quanto à eficácia e à justiça.',
  'A **adaptação** envolve obras de proteção costeira, sistemas de alerta e de defesa civil, planejamento urbano resiliente, uso eficiente da água, culturas resistentes à seca e ao calor e o apoio às comunidades vulneráveis. O Brasil tem papel central: abriga a maior floresta tropical do mundo, tem matriz elétrica relativamente limpa, com forte participação da hidrelétrica, e é protagonista nas negociações. Ao mesmo tempo, enfrenta o desafio de controlar o desmatamento e as queimadas, que são sua maior fonte de emissões. Mudanças individuais, como o consumo consciente, também importam, mas as mudanças estruturais, em energia, indústria e agricultura, são decisivas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'As mudanças climáticas estão entre os temas mais cobrados no ENEM, em Geografia, Biologia, Química e na redação. Os textos trazem gráficos de emissões por país ou por setor, de temperatura média global, de elevação do nível do mar, notícias sobre conferências do clima e descrições de eventos extremos. As questões pedem para identificar as causas (queima de combustíveis, desmatamento), as consequências (derretimento, eventos extremos, acidificação), os acordos internacionais e as soluções, avaliando benefícios e limitações de cada uma.',
  'Pontos de atenção: o efeito estufa é natural e necessário, o problema é sua intensificação; os principais gases são CO2, CH4 e N2O; no Brasil, o desmatamento é a maior fonte de emissões, ao contrário dos países industrializados, em que predomina a energia e a indústria; os países têm responsabilidades históricas e atuais diferentes; o Acordo de Paris estabelece metas voluntárias; e as soluções incluem mitigação e adaptação. Cuidado com afirmações absolutas e com a confusão entre aquecimento global e buraco na camada de ozônio, que são problemas distintos.',
  'Para revisar, organize em quatro blocos: o mecanismo (efeito estufa), as causas (fósseis, desmatamento, agropecuária), os efeitos (gelo, mar, clima, sociedade) e as respostas (acordos, mitigação e adaptação). Conecte o tema ao anterior (clima), ao ciclo do carbono (Biologia) e à matriz energética (próximo bloco de Geografia). Na redação, o tema permite argumentos sólidos, com dados, acordos e propostas de intervenção que envolvam o governo, as empresas e os cidadãos.'] }
]},
{ t:'Hidrografia', txt:[
 { h:'O ciclo da água e a distribuição da água no planeta', p:[
  'A **hidrografia** estuda as águas da superfície terrestre: oceanos, mares, rios, lagos e águas subterrâneas. Cerca de 71% da superfície da Terra é coberta por água, mas **97,5%** dessa água é salgada. Dos 2,5% de água doce, a maior parte (cerca de 69%) está congelada nas geleiras e calotas polares, e cerca de 30% é água subterrânea. A água dos rios e lagos, a mais acessível, representa menos de 1% da água doce. Isso mostra que a água doce disponível para o consumo humano é um recurso **limitado**, e que seu uso deve ser planejado.',
  'A água circula continuamente no **ciclo hidrológico**, movido pela energia solar e pela gravidade. A **evaporação** (dos oceanos, rios e lagos) e a **transpiração** das plantas levam o vapor para a atmosfera, onde ele se condensa em nuvens. A **precipitação** devolve a água à superfície. Parte escorre pela superfície (escoamento) e forma os rios, e parte se **infiltra** no solo, abastecendo os **aquíferos**, as reservas subterrâneas. A cobertura vegetal favorece a infiltração e reduz o escoamento, e o desmatamento e a impermeabilização urbana alteram esse equilíbrio, aumentando as enchentes e reduzindo a recarga dos aquíferos.',
  'A **distribuição** da água no mundo é desigual. Alguns países, como o Brasil, a Rússia, o Canadá e os Estados Unidos, concentram grandes volumes de água doce. Já regiões como o Oriente Médio e o norte da África têm escassez. O Brasil possui cerca de **12% da água doce superficial** do planeta, mas essa água é mal distribuída internamente: a Região Norte (bacia Amazônica) concentra cerca de 80% da água, para menos de 5% da população, enquanto o Sudeste e o Nordeste, mais populosos, dispõem de muito menos. Daí a importância da gestão e da conservação.'] },
 { h:'Rios, bacias hidrográficas e regimes fluviais', p:[
  'Uma **bacia hidrográfica** é a área drenada por um rio principal e seus afluentes, delimitada pelos pontos mais altos do relevo, chamados de **divisores de água**. É a unidade de planejamento e de gestão da água. O rio nasce na **nascente**, corre pelo **leito** entre as **margens** e termina na **foz**, que pode ser em **delta** (formação de ilhas e braços, quando há muito sedimento e pouca energia marinha, como o Nilo e o Mississippi) ou em **estuário** (foz alargada, em forma de funil, sem acúmulo de sedimentos, como o Amazonas e o Prata). Os **afluentes** são os rios menores que desaguam no principal.',
  'O **regime** de um rio é a variação de sua vazão ao longo do ano e depende da fonte de alimentação. Os rios **pluviais** são alimentados pela chuva, e suas cheias coincidem com a estação chuvosa (a maioria dos rios brasileiros). Os **nivais** são alimentados pelo derretimento da neve, e cheiam na primavera. Os **glaciais**, pelo derretimento das geleiras, no verão. Há os de regime **misto**, como o Amazonas, que recebe água da chuva e do derretimento de neve dos Andes. Os rios **perenes** correm o ano todo, e os **intermitentes** (ou temporários), típicos do semiárido, secam durante a estiagem.',
  'Quanto ao **uso**, os rios servem para o abastecimento, a irrigação, a geração de energia, a navegação, a pesca, o lazer e a diluição de efluentes. Os rios de planalto, com muitos desníveis, favorecem a geração de energia hidrelétrica, e os de planície, a navegação. Muitas vezes, esses usos entram em conflito: a construção de uma barragem pode prejudicar a pesca, alagar áreas e alterar o ciclo das cheias. A **gestão integrada** dos recursos hídricos busca equilibrar essas demandas, por meio de comitês de bacia, em que participam governos, usuários e a sociedade civil.'] },
 { h:'As bacias hidrográficas do Brasil', p:[
  'O Brasil tem uma das maiores redes hidrográficas do mundo. Predominam os **rios de planalto**, com boa capacidade de geração de energia, e os **rios de planície** na Amazônia e no Pantanal, navegáveis. A grande maioria dos rios é **perene**, com exceção dos rios do sertão nordestino, intermitentes. Quanto à foz, quase todos formam estuário, exceto o Parnaíba, que forma um delta. As principais bacias são: a **Amazônica**, a **do Tocantins-Araguaia**, a **do São Francisco**, a **do Paraná** (e seus afluentes, como o Tietê), a **do Paraguai** (que forma o Pantanal), a **do Uruguai**, as do **Atlântico Nordeste, Leste e Sudeste** e a do **Parnaíba**.',
  'A **bacia Amazônica** é a maior do mundo em volume de água, com extensão de cerca de 6 milhões de km², dos quais 4 milhões em território brasileiro. É formada por rios de planície, com grande potencial de navegação, e tem relevância ecológica e climática. Seu potencial hidrelétrico é grande, mas exige cuidado, pela biodiversidade e pelas populações da floresta, como mostra a polêmica da hidrelétrica de Belo Monte. A bacia do **São Francisco**, o "Rio da Integração Nacional", atravessa regiões do semiárido e tem grande importância para o abastecimento, a irrigação e a geração de energia (Sobradinho, Paulo Afonso), além da transposição para o Nordeste Setentrional.',
  'A bacia do **Paraná** é a mais usada para a geração de energia, com grandes usinas, como **Itaipu**, binacional entre Brasil e Paraguai, uma das maiores do mundo, e abastece a região mais populosa e industrializada do país, o que gera problemas de poluição e escassez. O rio **Tietê**, em São Paulo, é um símbolo da poluição urbana. A bacia do **Paraguai** inclui o **Pantanal**, planície alagável, e a hidrovia Paraguai-Paraná. A **bacia do Tocantins-Araguaia** é inteiramente brasileira, e a **do Uruguai** tem aproveitamento hidrelétrico e agrícola. O conjunto mostra a importância da água para a economia, mas também os riscos de uso inadequado.'] },
 { h:'Águas subterrâneas, uso da água e crise hídrica', p:[
  'As **águas subterrâneas** ficam armazenadas nos **aquíferos**, formações geológicas porosas e permeáveis, que retêm a água da infiltração. São uma importante reserva de água doce, protegida de parte da poluição e da evaporação. O **Aquífero Guarani**, um dos maiores reservatórios de água doce do mundo, ocupa partes do Brasil, da Argentina, do Paraguai e do Uruguai, e abastece muitas cidades do interior de São Paulo e do Sul. A exploração excessiva por poços, a contaminação por agrotóxicos, esgotos e vazamentos e a impermeabilização das áreas de recarga ameaçam esses recursos, que levam muito tempo para se renovar.',
  'O **consumo de água** no Brasil se divide, em grande parte, entre a **agricultura irrigada** (a maior usuária, cerca de metade da retirada total), o abastecimento humano, a indústria e a pecuária. Há desperdício, como as perdas nas redes de distribuição, que chegam a cerca de 40% em muitos locais, e a falta de **saneamento** compromete a qualidade das águas. A poluição dos rios por esgoto, lixo, agrotóxicos e resíduos industriais, e o **assoreamento**, agravam a escassez. A **escassez** pode ser física (falta de água) ou econômica e política (falta de infraestrutura e de acesso), e muitas regiões convivem com a abundância e a falta ao mesmo tempo.',
  'As **crises hídricas** são cada vez mais comuns. A seca de 2014 a 2016, no Sudeste, reduziu drasticamente os reservatórios do **Sistema Cantareira**, que abastece a Região Metropolitana de São Paulo, e levou a racionamentos. As causas incluíram a estiagem, a demanda elevada, o desmatamento e a falta de planejamento. Em escala global, a água é motivo de **tensões geopolíticas**, por exemplo, nas disputas pelo Nilo, pelos rios Tigre e Eufrates e pelo Jordão. A **Lei das Águas** (1997) estabelece a Política Nacional de Recursos Hídricos, que define a água como bem público, limitado e com valor econômico, e prioriza o consumo humano e a dessedentação de animais em situações de escassez.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a hidrografia aparece em questões sobre a distribuição da água, as bacias brasileiras e suas características (regime, aproveitamento hidrelétrico, navegação), os conflitos pelo uso da água, a crise hídrica, o saneamento e a poluição dos rios, e a gestão integrada. Os enunciados trazem mapas de bacias, gráficos de uso da água, notícias sobre secas e reportagens sobre grandes obras, como Itaipu e a transposição do São Francisco, e pedem para relacionar os dados aos impactos socioambientais.',
  'Pontos de atenção: a maior parte da água doce está congelada, e a acessível é muito pequena; o Brasil é rico em água, mas mal distribuída em relação à população; os rios de planalto favorecem a energia e os de planície, a navegação; o semiárido tem rios intermitentes; o Aquífero Guarani é uma importante reserva; a agricultura é a maior consumidora; e a gestão por bacias é a base da política nacional. Atenção às consequências das obras: as hidrelétricas geram energia renovável, mas alteram os ecossistemas e deslocam populações.',
  'Para revisar, monte um quadro das principais bacias (nome, localização, característica e uso) e um esquema do ciclo da água, com as ações humanas que o alteram. Pense em problemas e soluções: poluição e tratamento de esgoto; escassez e reúso e redução de perdas; assoreamento e proteção das matas ciliares; conflitos e comitês de bacia. Esse tema se conecta ao clima, que determina o regime dos rios, à vegetação e à questão ambiental, estudadas em seguida, e à energia, que será tratada mais adiante.'] }
]},
{ t:'Vegetação e domínios morfoclimáticos', txt:[
 { h:'Vegetação, formações vegetais e fatores que a determinam', p:[
  'A **vegetação** é o conjunto das plantas que cobrem uma região, e depende dos fatores do ambiente: o **clima** (temperatura e chuvas), o **solo**, o **relevo** e a ação dos seres vivos e dos humanos. As **formações vegetais** são tipos de vegetação com características semelhantes: as **florestas** (predomínio de árvores, com vegetação densa), as **savanas** (árvores esparsas em meio a gramíneas), as **campos** ou **estepes** (predomínio de gramíneas), os **desertos** (vegetação escassa e adaptada à seca) e a **tundra** (vegetação rasteira, em regiões frias). A forma das plantas revela sua adaptação ao ambiente.',
  'As **plantas** desenvolveram adaptações. Em ambientes secos, as **xerófitas** têm folhas reduzidas ou transformadas em espinhos (como os cactos), raízes profundas e tecidos que armazenam água. Em ambientes sujeitos ao fogo, como o Cerrado, os troncos têm casca grossa e as raízes são profundas. Nos manguezais, as plantas têm raízes aéreas, que facilitam a respiração em solo encharcado e salgado. Nas florestas tropicais úmidas, as árvores têm raízes tabulares e copas altas, que competem pela luz. Essas relações entre forma e ambiente são muito exploradas nas provas.',
  'A vegetação tem funções fundamentais: protege o solo da erosão, regula o ciclo da água e o clima, abriga a biodiversidade, absorve carbono e fornece recursos para os seres humanos. A sua distribuição no planeta segue, em linhas gerais, as zonas climáticas: florestas equatoriais e tropicais perto do Equador, savanas e desertos nas zonas de menor umidade, florestas temperadas e de coníferas em latitudes médias e altas, e tundra nas regiões polares. A destruição da vegetação, por desmatamento, queimadas e urbanização, é um dos principais problemas ambientais da atualidade.'] },
 { h:'Os domínios morfoclimáticos do Brasil segundo Aziz Ab\'Sáber', p:[
  'O geógrafo **Aziz Ab\'Sáber** propôs uma classificação do território brasileiro em **domínios morfoclimáticos**, áreas em que se combinam o relevo, o clima, o solo e a vegetação, formando paisagens características. São seis grandes domínios, e as faixas de transição entre eles. O conceito é diferente do de **bioma**, que enfatiza o conjunto de ecossistemas com vegetação e fauna próprias. Na prática, as duas classificações se parecem, e as questões do ENEM costumam usá-las de forma complementar, valorizando as características de cada paisagem.',
  'O **Domínio Amazônico** é a região das terras baixas, de clima equatorial quente e úmido, com a **Floresta Equatorial** (Hileia), densa e perene, com grande biodiversidade. O **Domínio dos Cerrados** ocupa os planaltos centrais, com clima tropical de estações definidas e vegetação de **cerrado** (árvores tortuosas e gramíneas). O **Domínio dos Mares de Morros**, no litoral do Sudeste e do Nordeste, com relevo de morros arredondados e clima tropical úmido, abriga a **Mata Atlântica**. O **Domínio das Caatingas** corresponde às depressões semiáridas do Nordeste, com vegetação xerófita e clima semiárido.',
  'O **Domínio das Araucárias** ocorre nos planaltos do Sul, de clima subtropical, com a **Floresta de Araucárias** (pinheiro-do-paraná), muito explorada, e hoje reduzida a pequenos remanescentes. O **Domínio das Pradarias** (Pampas), no sul do Rio Grande do Sul, tem relevo de coxilhas suavemente onduladas, clima subtropical e vegetação de campos. Entre eles, estão as **faixas de transição**, como o **Pantanal**, a **Mata dos Cocais** (com palmeiras de babaçu e carnaúba, entre a Amazônia e a Caatinga) e as zonas de contato. Cada domínio tem condições, potencialidades e fragilidades próprias.'] },
 { h:'Formações vegetais brasileiras: florestas, cerrado, caatinga, campos e vegetação litorânea', p:[
  'As **florestas** brasileiras incluem a **Amazônica** (equatorial, densa, com árvores de mais de 40 metros, e com grande biodiversidade, dividida em mata de terra firme, de várzea e de igapó, conforme a inundação); a **Mata Atlântica** (tropical, da costa leste, muito devastada); a **Mata de Araucárias** (subtropical) e a **Mata dos Cocais** (de transição, com babaçu e carnaúba, de grande importância econômica para comunidades extrativistas). As matas ciliares acompanham os rios e protegem as margens. O desmatamento reduziu muito as áreas originais, em especial da Mata Atlântica e da Mata de Araucárias.',
  'O **Cerrado** é a savana brasileira: tem estrato arbóreo-arbustivo de árvores de troncos tortuosos e cascas grossas, e estrato herbáceo de gramíneas. As adaptações ao fogo e à seca incluem raízes profundas e cascas espessas. É um dos ecossistemas mais ricos em biodiversidade do mundo e um hotspot, mas perde terreno para a agricultura de grãos e a pecuária. A **Caatinga** é uma vegetação de arbustos e árvores baixas, com folhas pequenas, espinhos, plantas que armazenam água e que perdem as folhas na estiagem, e é exclusiva do Brasil. Os **campos** (Pampas e campos de altitude) apresentam gramíneas e poucas árvores.',
  'A **vegetação litorânea** inclui os **manguezais** (em estuários, com raízes aéreas, berçário marinho), as **restingas** (areias do litoral, com vegetação de pequeno porte) e as **dunas**. O **Pantanal** apresenta uma vegetação mista, que muda conforme o ciclo de cheias e secas, com elementos do Cerrado, da Amazônia e da Mata Atlântica. A **Mata Atlântica** e o **Cerrado** são consideradas **hotspots** de biodiversidade, devido à riqueza de espécies endêmicas e ao alto grau de ameaça. Conhecer a vegetação é fundamental para planejar a ocupação do território e proteger os ecossistemas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, esse tema aparece em questões que apresentam mapas dos domínios e dos biomas, fotografias de paisagens e descrições de adaptações das plantas, e pedem a identificação do domínio, a explicação da relação entre clima e vegetação e a discussão dos impactos do desmatamento e da expansão agrícola. Também se cobra a importância da conservação, as unidades de conservação e o uso sustentável. A questão pode combinar conteúdos de Geografia e de Biologia, como as adaptações e os ecossistemas.',
  'Pontos de atenção: cada domínio tem uma combinação própria de relevo, clima, solo e vegetação; as plantas do Cerrado e da Caatinga têm adaptações à seca e ao fogo; a Mata Atlântica está muito reduzida; a Amazônia tem solos pobres e depende da ciclagem de nutrientes; o Pantanal e a Mata dos Cocais são transições; e o Cerrado e a Mata Atlântica são hotspots. Atenção à diferença entre "domínio morfoclimático", de Ab\'Sáber, e "bioma", embora as duas classificações coincidam em boa parte.',
  'Para revisar, monte um quadro com os seis domínios e as faixas de transição, indicando clima, relevo, solo, vegetação e ameaças. Treine reconhecer as paisagens a partir de descrições curtas (árvores tortuosas, mandacarus, araucárias, campos limpos, raízes aéreas). Esse tema se articula com o clima, com os solos e com o seguinte, a questão ambiental no Brasil, em que se discutem desmatamento, queimadas, mineração e as políticas de conservação.'] }
]}
];

/* quinto bloco do tema Vegetação e domínios morfoclimáticos */
{
  const vg = module.exports[2];
  const ult = vg.txt.pop();
  vg.txt.push({ h:'Devastação, conservação e uso sustentável da vegetação', p:[
    'A vegetação nativa brasileira sofre pressões históricas. A **Mata Atlântica**, que cobria cerca de 15% do território, foi reduzida a algo em torno de 12% da cobertura original, pela exploração do pau-brasil, pelos ciclos da cana e do café, pela industrialização e pela urbanização. O **Cerrado** perdeu quase metade de sua vegetação nativa, com a expansão da soja, do milho, do algodão e da pecuária. A **Amazônia** sofre com o desmatamento do chamado "arco do desmatamento", pela pecuária, pelo corte de madeira, pela grilagem de terras, pelo garimpo e pela abertura de estradas, e a **Caatinga**, com a retirada de lenha e a desertificação.',
    'O **Código Florestal** (Lei 12.651/2012) estabelece as regras de proteção: as **Áreas de Preservação Permanente** (APPs), como matas ciliares, topos de morro e encostas íngremes, que devem ser mantidas, e a **Reserva Legal**, a parcela de cada propriedade rural que deve preservar a vegetação nativa (80% na Amazônia, 35% no Cerrado amazônico e 20% nas demais regiões). Foram criadas **Unidades de Conservação** de proteção integral (parques, reservas biológicas) e de uso sustentável (reservas extrativistas, áreas de proteção ambiental). A fiscalização, o monitoramento por satélite e o Cadastro Ambiental Rural (CAR) são instrumentos de controle.',
    'O uso sustentável da vegetação inclui o **manejo florestal** (extração planejada de madeira), o **extrativismo** de produtos não madeireiros (castanha, açaí, borracha, babaçu), os **sistemas agroflorestais**, o **ecoturismo** e o **pagamento por serviços ambientais**. A **recuperação de áreas degradadas**, com o plantio de espécies nativas, e a criação de **corredores ecológicos** reconectam fragmentos de vegetação. O **Pacto pela Restauração da Mata Atlântica** é um exemplo. O desafio é conciliar a produção de alimentos e de energia com a conservação, e o ENEM valoriza respostas que combinem fiscalização, incentivos e participação das comunidades locais.'
  ]});
  vg.txt.push(ult);
}
