/* Geografia: textos corridos, temas 19 a 21 */
module.exports = [
{ t:'Globalização e economia mundial', txt:[
 { h:'O que é globalização e como ela se desenvolveu', p:[
  'A **globalização** é o processo de integração crescente das economias, das sociedades, das culturas e da política em escala mundial. Ela se manifesta na circulação de **mercadorias, capitais, informações, tecnologias e pessoas** por todo o planeta, e na interdependência entre os países. Embora o termo seja recente, as raízes do processo são antigas: as Grandes Navegações (século XV) já conectaram continentes, a Revolução Industrial e o imperialismo do século XIX integraram os mercados, e as comunicações do século XX aceleraram os fluxos. A globalização atual, porém, é muito mais intensa e rápida.',
  'Três fatores impulsionaram a globalização contemporânea. O primeiro é a **revolução técnico-científica e informacional**, a partir da década de 1970, com a informática, as telecomunicações, os satélites, a internet e os novos meios de transporte, que reduziram o tempo e o custo das comunicações e dos deslocamentos. O segundo é a **expansão do capitalismo** e das **empresas multinacionais**, que fragmentaram a produção em várias partes do mundo, em busca de custos menores e de novos mercados. O terceiro é a **abertura econômica**, a partir dos anos 1980 e 1990, com o neoliberalismo, e o fim da Guerra Fria, que ampliou o espaço do mercado.',
  'A noção de "**aldeia global**", criada por Marshall McLuhan, expressa a ideia de um mundo conectado pelas mídias. As cidades globais, como Nova York, Londres e Tóquio, tornaram-se centros de comando da economia, com bolsas de valores, bancos e sedes de empresas. Ao mesmo tempo, a globalização não alcança todos igualmente: vastas regiões e populações permanecem à margem. Por isso, falar em globalização significa considerar tanto a integração quanto a **desigualdade** que ela produz, um tema importante nas provas, que valorizam a análise crítica.'] },
 { h:'Empresas multinacionais, fluxos e divisão internacional do trabalho', p:[
  'As **empresas multinacionais** (ou transnacionais) são os principais agentes da globalização econômica. Têm sede em um país e filiais em muitos outros, e organizam a produção em escala mundial: o projeto e a marca ficam no país de origem, e a fabricação de peças e a montagem são distribuídas em regiões onde os custos de mão de obra, de impostos e de logística são favoráveis. Esse processo é chamado de **fragmentação** da produção, ou **cadeias globais de valor**. Um celular, por exemplo, pode ser projetado nos EUA, ter peças da Coreia, do Japão e da China, e ser montado na China ou no Vietnã.',
  'A **divisão internacional do trabalho** tradicional colocava os países industrializados como produtores de manufaturados e os periféricos como fornecedores de matérias-primas. Hoje, é mais complexa: há países **emergentes** que industrializam e exportam produtos de média e alta tecnologia, como a China, a Índia, o México e a Coreia do Sul, enquanto muitos países ricos concentram as atividades de pesquisa, serviços e finanças. Os países mais pobres continuam, em geral, exportando produtos primários, o que os torna vulneráveis às oscilações dos preços das **commodities**, como o petróleo, o minério, a soja e o café.',
  'Os **fluxos financeiros** são os mais rápidos e voláteis: os capitais circulam instantaneamente pelas bolsas de valores e pelos bancos, em busca de lucro, e podem entrar e sair dos países em poucas horas, o que causa instabilidade. O **capital especulativo** aumentou a vulnerabilidade a crises financeiras, que se espalham rapidamente, como a de 2008. Os **fluxos comerciais** foram ampliados pela redução de tarifas e pelo transporte em contêineres, e a **Organização Mundial do Comércio** (OMC) regula as regras. Os **fluxos de informação** e de cultura, pela internet e pelas redes sociais, conectam as pessoas, e produzem tanto a diversidade quanto a homogeneização.'] },
 { h:'Globalização cultural, desigualdade e crítica', p:[
  'A **globalização cultural** é a difusão de hábitos, de produtos, de idiomas e de valores em escala mundial, impulsionada pela mídia, pelo cinema, pela música, pela internet e pelas redes sociais. Pode levar à **homogeneização**, com a difusão de padrões associados aos países ricos, em especial os Estados Unidos (a chamada "americanização", com marcas como o McDonald\'s e a Coca-Cola), mas também gera **hibridismo**, a mistura de elementos locais e globais, e a valorização de culturas regionais. Fenômenos como o K-pop, os filmes indianos e os ritmos latinos mostram fluxos culturais em várias direções.',
  'A globalização trouxe **benefícios**: aumento do comércio, difusão de tecnologias e de conhecimentos, redução de preços, acesso a produtos e a informações e crescimento de países emergentes, que tiraram milhões de pessoas da pobreza, como a China. Mas também gerou **críticas**: concentração da riqueza, aumento das desigualdades dentro e entre os países, precarização do trabalho, perda de empregos industriais nos países ricos, pressão sobre direitos trabalhistas, impactos ambientais, perda de soberania dos Estados e risco de homogeneização cultural. Há quem defenda a "**antiglobalização**" e quem defenda uma globalização mais justa, com regulação.',
  'A **pandemia de covid-19** (2020 a 2022) revelou a interdependência global, com a rápida propagação do vírus pelo mundo e a ruptura de cadeias de produção, mas também as fragilidades da dependência de poucos fornecedores, e ressaltou a necessidade de cooperação. A crise financeira de 2008, a guerra na Ucrânia (2022) e as tensões entre os EUA e a China levaram ao debate sobre a "**desglobalização**" ou a regionalização das cadeias produtivas e sobre a segurança econômica. A globalização, portanto, não é um processo linear e inevitável: ela é resultado de decisões políticas e econômicas, e pode ser redirecionada.'] },
 { h:'O Brasil e a globalização', p:[
  'O Brasil se insere na economia global como um grande exportador de **commodities** agrícolas e minerais (soja, carne, café, açúcar, minério de ferro, petróleo), e como um mercado consumidor importante, que atrai multinacionais. Tem uma indústria diversificada, com setores competitivos (automotivo, aeronáutico, alimentos e celulose), mas enfrenta desafios de competitividade e de dependência tecnológica. A **China** é seu principal parceiro comercial, importando soja e minério, e exportando produtos industrializados. Essa relação reforça a especialização em produtos primários e aumenta o debate sobre desindustrialização e o papel do país nas cadeias globais.',
  'O país participa de organismos e de acordos, como a **OMC**, o **Mercosul** e os **BRICS**, e de negociações com blocos, como a União Europeia. A **abertura comercial** dos anos 1990, as privatizações e a entrada de capitais estrangeiros transformaram a economia, e as crises externas (como as de 1997, 1998 e 2008) mostraram a vulnerabilidade. O Brasil também é um país de **emigração** e **imigração**, com comunidades no exterior, e recebe refugiados. Na cultura, mistura influências globais e locais, e exporta música, futebol, telenovelas e gastronomia. A inserção internacional é um tema constante nas discussões sobre desenvolvimento.',
  'Do ponto de vista social, a globalização afetou o **trabalho**: a flexibilização, a terceirização, o trabalho por aplicativos e a informalidade aumentaram, com impactos na renda e nos direitos. As regiões brasileiras se integraram de modo desigual: o agronegócio do Centro-Oeste e o polo industrial do Sudeste estão muito conectados ao mercado mundial, enquanto áreas do Norte e do Nordeste permanecem menos integradas. A tecnologia digital permite novas oportunidades, mas exige educação e infraestrutura. Compreender essa inserção ajuda a analisar questões atuais e a pensar propostas para o país, tanto no ENEM quanto na redação.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A globalização é um tema transversal no ENEM. Aparece em questões sobre as empresas multinacionais e as cadeias globais, a divisão internacional do trabalho, os fluxos de capitais e de informações, a homogeneização e a diversidade cultural, a desigualdade, as crises financeiras, o papel da internet e das redes sociais e a inserção do Brasil. Os textos incluem charges, mapas de fluxos comerciais, gráficos das exportações e trechos de autores como Milton Santos, que fala de "globalização como fábula, como perversidade e como possibilidade".',
  'Pontos de atenção: a globalização é multidimensional (econômica, cultural, tecnológica e política); a fragmentação da produção explica o papel das multinacionais; a divisão internacional do trabalho continua desigual, apesar da ascensão de emergentes; os capitais financeiros são voláteis; a cultura global gera homogeneização e hibridismo; e a globalização não alcança todos igualmente. Evite visões extremas, que a tratam como totalmente benéfica ou totalmente prejudicial, e valorize respostas que apontem a complexidade e a necessidade de regulação e de inclusão.',
  'Para revisar, esquematize: fatores (tecnologia, expansão do capital, abertura), agentes (multinacionais, bancos, Estados, organismos), fluxos (mercadorias, capitais, informações e pessoas), efeitos (integração, desigualdade, homogeneização, crises) e respostas (blocos, regulação, movimentos sociais). Relacione ao tema seguinte, os blocos econômicos e as organizações internacionais, que são formas de organizar a integração, e ao de geopolítica, em que se analisam as relações de poder entre os países.'] }
]},
{ t:'Blocos econômicos e organizações', txt:[
 { h:'Por que se formam os blocos econômicos e quais são seus níveis', p:[
  'Os **blocos econômicos** são associações entre países, em geral vizinhos, que estabelecem acordos para facilitar o comércio e a cooperação entre eles. Surgiram no pós-guerra e se multiplicaram com a globalização, por vários motivos: ampliar mercados, reduzir tarifas e barreiras, atrair investimentos, aumentar a capacidade de negociação diante de outros países e blocos, e promover a segurança e o desenvolvimento. Ao se unirem, os países ganham escala, e suas empresas podem vender em um mercado maior. Mas também perdem parte da autonomia, pois precisam seguir as regras comuns.',
  'Os blocos são classificados em níveis crescentes de integração. A **zona de livre-comércio** elimina ou reduz as tarifas alfandegárias entre os membros, mas cada país mantém sua política comercial em relação aos de fora (como o NAFTA e sua sucessora, o USMCA). A **união aduaneira** acrescenta uma **tarifa externa comum** para as importações vindas de países de fora (como o Mercosul). O **mercado comum** permite, além disso, a livre circulação de capitais, de serviços e de pessoas. A **união econômica e monetária** inclui moeda e políticas econômicas comuns (como a zona do euro na União Europeia). O nível máximo seria a integração política.',
  'A **Organização Mundial do Comércio** (OMC, 1995) é a instituição que regula o comércio internacional, estabelece regras, e arbitra conflitos entre países, buscando a redução das barreiras. Os blocos regionais podem ser complementares às regras multilaterais, mas também podem criar discriminações em relação a quem fica de fora. Há ainda os acordos **bilaterais** entre dois países, e os **megablocos**, de grandes economias, como a Parceria Transpacífico e a Regional Comprehensive Economic Partnership (RCEP), da Ásia. O debate sobre regionalismo e multilateralismo é constante.'] },
 { h:'A União Europeia', p:[
  'A **União Europeia** (UE) é o bloco de maior grau de integração do mundo. Tem origem na **Comunidade Europeia do Carvão e do Aço** (1951), criada para integrar a produção de carvão e aço de seis países e evitar novos conflitos, depois da Segunda Guerra. Seguiram-se a **Comunidade Econômica Europeia** (1957, Tratado de Roma), o **Mercado Comum**, e o **Tratado de Maastricht** (1992), que criou a União Europeia, e previu a moeda única. Em 2002, o **euro** passou a circular, e hoje é adotado por 20 países, a chamada **zona do euro**. O bloco tem cerca de 27 membros, e se ampliou para o Leste europeu a partir de 2004.',
  'A UE tem instituições comuns: o **Parlamento Europeu**, eleito pelos cidadãos, a **Comissão Europeia**, que propõe as leis, o **Conselho** e o **Banco Central Europeu**. Seus princípios são as **quatro liberdades**: livre circulação de bens, serviços, capitais e pessoas. O **Espaço Schengen** eliminou os controles de fronteira entre muitos países, e os cidadãos podem viver e trabalhar em qualquer país da UE. O bloco também tem políticas comuns, em agricultura (PAC), meio ambiente e coesão regional, e investe nas regiões mais pobres. É a maior economia comercial do mundo, e influencia as normas globais.',
  'O bloco enfrenta desafios: a crise da dívida na zona do euro (2010 a 2012), que atingiu a Grécia, a Espanha, a Itália e Portugal; a pressão migratória e dos refugiados; o crescimento de partidos eurocéticos e nacionalistas; e o **Brexit**, a saída do Reino Unido, decidida por referendo em 2016 e concluída em 2020, que mostrou os limites da integração. As diferenças econômicas entre os países, a perda de soberania e a distância das instituições alimentam críticas. Ainda assim, a UE é vista como o exemplo mais avançado de integração regional, inspirando outros blocos.'] },
 { h:'Mercosul, USMCA e outros blocos', p:[
  'O **Mercosul** (Mercado Comum do Sul) foi criado em 1991, pelo Tratado de Assunção, por Brasil, Argentina, Paraguai e Uruguai, e aprofundado em 1994 (Protocolo de Ouro Preto), quando se tornou uma **união aduaneira** imperfeita, com tarifa externa comum, e se encaminhava para um mercado comum. A Venezuela foi admitida em 2012 e suspensa em 2016, e a Bolívia está em processo de adesão. O comércio entre os países cresceu, em especial de produtos industriais, como automóveis. O bloco enfrenta dificuldades, como as assimetrias entre as economias, as crises na Argentina e no Brasil, o protecionismo e as divergências políticas, e o acordo com a UE, negociado por décadas, ainda está pendente.',
  'O **USMCA** (Acordo Estados Unidos-México-Canadá), de 2020, substituiu o **NAFTA** (Tratado Norte-Americano de Livre Comércio, 1994), e é uma zona de livre-comércio entre as três economias da América do Norte. O NAFTA aumentou o comércio, mas também provocou debates sobre a perda de empregos industriais nos EUA e sobre a situação dos trabalhadores mexicanos. Outros blocos importantes são a **ASEAN** (Associação de Nações do Sudeste Asiático), a **APEC** (Cooperação Econômica Ásia-Pacífico), a **União Africana**, a **Comunidade Andina**, a **CELAC**, a **SADC** e a **CEDEAO** na África, além de iniciativas como a **Aliança do Pacífico**, na América Latina.',
  'Há também grupos políticos e econômicos, como o **G7** (as sete maiores economias avançadas), o **G20** (que reúne as maiores economias, desenvolvidas e emergentes), e os **BRICS** (Brasil, Rússia, Índia, China e África do Sul, expandido recentemente), que buscam coordenar posições e ampliar a influência dos países emergentes. A **OPEP** reúne os exportadores de petróleo. Esses agrupamentos não são blocos de integração comercial no mesmo sentido, mas expressam alianças de interesses. A formação de blocos reflete a tendência de **regionalização** da economia mundial, que convive com a globalização e a pode complementar ou limitar.'] },
 { h:'Organizações internacionais: ONU, FMI, Banco Mundial e OTAN', p:[
  'Além dos blocos econômicos, há organizações internacionais que atuam na política, na economia, na segurança e nos direitos. A **ONU** (Organização das Nações Unidas), criada em 1945, reúne quase todos os países, e tem como objetivos a manutenção da paz e da segurança, a cooperação e a defesa dos direitos humanos. Seus principais órgãos são a **Assembleia Geral**, em que todos os países têm voto, e o **Conselho de Segurança**, com cinco membros permanentes (EUA, Rússia, China, Reino Unido e França), com direito de veto. A ONU tem agências, como a OMS (saúde), a UNESCO (educação e cultura), a FAO (alimentação), o ACNUR e o PNUMA. As **forças de paz** atuam em áreas de conflito.',
  'O **FMI** (Fundo Monetário Internacional) e o **Banco Mundial** foram criados em 1944, em Bretton Woods, para organizar o sistema financeiro e apoiar a reconstrução e o desenvolvimento. O FMI empresta recursos a países com dificuldades no balanço de pagamentos, em geral com condições de ajustes fiscais, que são muito criticadas por aprofundar as dificuldades sociais. O Banco Mundial financia projetos de infraestrutura e de desenvolvimento. Os países ricos têm maior peso nas decisões, o que leva a críticas e a propostas de reforma. A **OMC** cuida do comércio, e a **OCDE** reúne países desenvolvidos para coordenar políticas econômicas.',
  'No campo militar, a **OTAN** (Organização do Tratado do Atlântico Norte, 1949) é uma aliança de defesa entre países da América do Norte e da Europa, criada na Guerra Fria, e que se ampliou para o Leste europeu após 1991, o que gera tensões com a Rússia. O Pacto de Varsóvia, de seu oponente soviético, foi dissolvido em 1991. Também existem organizações regionais, como a **OEA** (Organização dos Estados Americanos), a União Africana e a Liga Árabe. As organizações internacionais refletem a busca de cooperação e de regras comuns, mas esbarram nos interesses das grandes potências e nos limites da soberania dos Estados.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, os blocos econômicos aparecem em questões que pedem a identificação dos níveis de integração, as características da União Europeia (euro, Schengen e Brexit), do Mercosul e do USMCA, as vantagens e as desvantagens da integração e o papel das organizações, como a ONU, a OMC e o FMI. Os enunciados trazem mapas dos blocos, charges, tabelas do comércio e notícias, e pedem a relação entre a integração regional e a globalização, a soberania e o desenvolvimento. Os níveis de integração são um tema clássico.',
  'Pontos de atenção: zona de livre-comércio elimina tarifas internas; união aduaneira acrescenta a tarifa externa comum; mercado comum inclui circulação de pessoas, de capitais e de serviços; união econômica e monetária inclui moeda comum; o Mercosul é uma união aduaneira imperfeita; a UE é o bloco mais integrado, mas enfrenta crises; a ONU atua na paz e nos direitos, e seu Conselho de Segurança tem membros com veto; o FMI e o Banco Mundial surgiram em Bretton Woods. Evite confundir bloco econômico (comércio) com aliança militar (OTAN).',
  'Para revisar, monte um quadro com os principais blocos (data, membros, nível de integração e desafios) e outro com as organizações internacionais (finalidade e exemplos). Relacione o assunto com a globalização (anterior) e com a geopolítica (próximo tema), em que as organizações e os blocos aparecem como atores nas disputas de poder. Para a redação, os blocos oferecem repertório sobre cooperação internacional e a ideia de que problemas globais, como as mudanças climáticas, exigem ações coordenadas.'] }
]},
{ t:'Geopolítica e conflitos', txt:[
 { h:'Conceitos: geopolítica, Estado, território e fronteiras', p:[
  'A **geopolítica** é o estudo das relações entre o espaço geográfico e o poder, e analisa como os Estados disputam territórios, recursos e influência. O **Estado** é a organização política que exerce o poder sobre um **território** e uma **população**, com soberania. A **nação** é um grupo humano que compartilha identidade, história, língua e cultura, e nem sempre coincide com o Estado: há Estados multinacionais e nações sem Estado, como os curdos. As **fronteiras** são os limites políticos entre os Estados, e podem ser naturais (rios, montanhas) ou artificiais (linhas traçadas por acordos), e muitas delas foram definidas por potências coloniais, sem considerar a identidade dos povos.',
  'O **território** é o espaço apropriado e controlado por um poder, e é objeto de disputa pelos recursos que contém (petróleo, água, minérios, terras agrícolas) e por sua posição estratégica (rotas marítimas e canais, como o de Suez e o do Panamá, e estreitos, como Ormuz e Málaca). A **soberania** é a autoridade suprema do Estado sobre seu território. A globalização questiona essa ideia, pois fluxos de capital, de informações e de pessoas atravessam as fronteiras, e organizações supranacionais, como a UE, assumem parte das decisões. Mesmo assim, as fronteiras continuam importantes, e os muros e controles se multiplicam.',
  'Os Estados exercem **poder** por vários meios: o **militar** (hard power), o **econômico**, o **diplomático** e o **cultural** (soft power, a capacidade de influenciar pela atração da cultura, da ciência e dos valores). As potências disputam áreas de influência e recursos, e formam alianças. O mapa geopolítico muda ao longo do tempo: a ordem **bipolar** da Guerra Fria (EUA e URSS) deu lugar, após 1991, a uma ordem em que os EUA são a principal potência, mas com a ascensão de outros polos (China, UE, Rússia, Índia), o que muitos chamam de **multipolaridade**, ou uma fase de transição e de disputas.'] },
 { h:'A ordem mundial atual e as grandes potências', p:[
  'Os **Estados Unidos** mantêm a maior economia militar e financeira e uma ampla rede de alianças e de bases, e influenciam as normas internacionais, mas enfrentam o desgaste das guerras (Iraque e Afeganistão), a polarização interna e a competição chinesa. A **China**, que cresceu muito desde as reformas de 1978, é a segunda maior economia do mundo, a maior exportadora e uma potência tecnológica e militar emergente. Sua iniciativa **Nova Rota da Seda** (Belt and Road) financia infraestrutura em dezenas de países, ampliando sua influência na Ásia, na África e na América Latina. A rivalidade entre EUA e China, nos campos comercial, tecnológico e estratégico, é um dos eixos da geopolítica atual.',
  'A **Rússia**, herdeira da União Soviética, é uma potência nuclear, grande exportadora de energia (petróleo e gás) e busca recuperar influência, como mostram a anexação da Crimeia (2014) e a invasão da Ucrânia (2022), que provocou a maior guerra na Europa desde 1945, e sanções ocidentais. A **União Europeia** é uma potência econômica, mas com limitações políticas e militares. A **Índia**, a **Turquia**, o **Brasil**, a **África do Sul** e as potências regionais ganham peso. O **Japão** e a **Coreia do Sul** são grandes economias tecnológicas. O **Irã**, a **Arábia Saudita** e **Israel** disputam a hegemonia no Oriente Médio.',
  'O Brasil é uma potência regional, com a maior economia, o maior território e população da América do Sul, e papel destacado em fóruns como o G20 e os BRICS, e nas negociações ambientais. Sua posição é de **busca por autonomia**, com uma política externa que combina relações com os EUA, com a China e com os vizinhos. Tem interesses na **Amazônia**, no **Atlântico Sul** e na integração sul-americana, e disputa o pleito de um assento permanente no Conselho de Segurança da ONU. A defesa e a soberania sobre os recursos naturais, como a biodiversidade, a água e o pré-sal, também fazem parte dos debates estratégicos.'] },
 { h:'Conflitos contemporâneos: Oriente Médio, Europa Oriental, África e Ásia', p:[
  'O **Oriente Médio** concentra alguns dos principais conflitos. O **conflito israelo-palestino**, que remonta à criação do Estado de Israel (1948) e ao deslocamento de palestinos, envolve a disputa por território, por Jerusalém, pelos assentamentos e pela criação de um Estado palestino, com guerras e ciclos de violência, como a de Gaza. As guerras do **Iraque**, do **Afeganistão**, da **Síria** (desde 2011) e do **Iêmen** têm raízes em disputas políticas, étnicas, religiosas (sunitas e xiitas) e no interesse das potências em petróleo e na região. O surgimento do **Estado Islâmico** e do terrorismo agravou o quadro, com atentados em diversos países.',
  'Na **Europa Oriental**, a **guerra da Rússia contra a Ucrânia** (a partir de 2022) é um conflito entre o governo russo e o ucraniano, apoiado pelo Ocidente, que envolve a expansão da OTAN, a influência na região e a identidade. Nos **Bálcãs**, as guerras da década de 1990, após a desintegração da Iugoslávia, com limpeza étnica, como na Bósnia e em Kosovo, deixaram marcas. Na **África**, muitos conflitos têm origem em fronteiras artificiais herdadas da colonização, em disputas étnicas e por recursos (diamantes, petróleo, minerais), como em Ruanda (genocídio de 1994), no Congo, no Sudão, na Somália e no Sahel, onde atuam grupos extremistas.',
  'Na **Ásia**, as disputas incluem a questão da **Caxemira**, entre Índia e Paquistão (potências nucleares); a **península coreana**, dividida desde 1953, com o programa nuclear da Coreia do Norte; as tensões no **Mar do Sul da China**, em que a China reivindica ilhas e águas disputadas por Vietnã, Filipinas e outros; e a questão de **Taiwan**, considerada pela China como parte de seu território. Há ainda as **separatistas**, como os curdos, os tibetanos e os uigures. Na **América Latina**, a violência do crime organizado, o narcotráfico e as tensões políticas, como as da Venezuela, também são temas geopolíticos.'] },
 { h:'Terrorismo, armas nucleares e novos desafios', p:[
  'O **terrorismo** é o uso da violência contra civis, para provocar medo e alcançar objetivos políticos ou ideológicos. Após os atentados de **11 de setembro de 2001**, nos EUA, o tema ganhou destaque mundial, e levou à "guerra ao terror" e à invasão do Afeganistão e do Iraque. Há terrorismo de grupos religiosos extremistas (Al-Qaeda, Estado Islâmico), de grupos separatistas e de extrema direita ou esquerda. Os efeitos incluem a limitação de liberdades, a vigilância e a xenofobia. Especialistas enfatizam que o combate eficaz exige inteligência, cooperação e o enfrentamento das causas sociais e políticas, e não apenas a força.',
  'As **armas nucleares** continuam a ser uma ameaça. Os países que as possuem oficialmente são EUA, Rússia, Reino Unido, França e China (os cinco membros permanentes do Conselho de Segurança), além de Índia, Paquistão, Coreia do Norte e, supostamente, Israel. O **Tratado de Não Proliferação Nuclear** (TNP) busca impedir a disseminação, e o programa nuclear do **Irã** é motivo de tensões. A **dissuasão** nuclear, a ideia de que o risco de destruição mútua evita a guerra direta, ainda orienta a estratégia. Também preocupam as armas químicas e biológicas.',
  'Há **novos desafios** na geopolítica: a **guerra cibernética** e a disputa por tecnologias (5G, semicondutores e inteligência artificial); a **desinformação**; o controle de **recursos naturais**, como água, terras raras, lítio, petróleo e minerais críticos; o **Ártico**, que se abre com o derretimento do gelo, com novas rotas e reservas; as **mudanças climáticas** e as migrações forçadas, que podem gerar conflitos; e as pandemias. A cooperação internacional, por meio da ONU e de acordos, é fundamental. O estudante deve compreender que os conflitos têm causas históricas, econômicas, políticas e culturais múltiplas, e evitar explicações simplistas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A geopolítica e os conflitos aparecem no ENEM em questões sobre as fronteiras e os conflitos de origem colonial, o conflito israelo-palestino, as guerras no Oriente Médio, o terrorismo, o papel da ONU e da OTAN, a rivalidade entre as grandes potências, as disputas por recursos naturais e por rotas, os refugiados, as armas nucleares e a guerra da Ucrânia. Os enunciados trazem mapas, charges, notícias e trechos de discursos, e pedem uma leitura crítica, que relacione os acontecimentos atuais com sua história e com os interesses econômicos e políticos.',
  'Pontos de atenção: as fronteiras africanas e do Oriente Médio foram traçadas por potências coloniais, o que gerou conflitos; muitos conflitos estão ligados ao controle de recursos e de rotas; as divisões religiosas e étnicas são, muitas vezes, instrumentalizadas por interesses políticos; a ordem atual é multipolar, com a ascensão da China; a ONU e as organizações internacionais têm limites diante das grandes potências; e o terrorismo exige uma abordagem que combine segurança, justiça e cooperação. Evite explicações que reduzam um conflito a "ódios antigos" ou a uma única causa.',
  'Para revisar, monte um painel com as principais regiões de tensão (Oriente Médio, Europa Oriental, África, Ásia e América Latina), indicando as causas e os atores. Treine a leitura de mapas de fronteiras e de conflitos, e relacione-os aos temas anteriores: globalização, blocos e organizações. A seguir, o estudo da regionalização do Brasil e de suas regiões (Nordeste, Amazônia e povos tradicionais) mostrará como as questões de território, de poder e de recursos aparecem também na realidade brasileira.'] }
]}
];
