/* Geografia: textos corridos, temas 16 a 18 */
module.exports = [
{ t:'Agropecuária e questão agrária', txt:[
 { h:'Sistemas agrícolas, agronegócio e modernização do campo', p:[
  'A **agropecuária** é o conjunto das atividades de cultivo da terra (agricultura) e de criação de animais (pecuária). No mundo, existem sistemas muito diferentes. A **agricultura de subsistência**, voltada ao consumo da família, com técnicas tradicionais e pouca tecnologia, predomina em áreas pobres. A **agricultura comercial** produz para o mercado e usa insumos, máquinas e capital. Entre os sistemas intensivos, estão as **plantations**, grandes propriedades monocultoras, voltadas à exportação, com mão de obra numerosa, como a cana, o café e a laranja. A agricultura **familiar** utiliza a mão de obra da própria família e produz grande parte dos alimentos consumidos no país.',
  'Desde a década de 1960, o Brasil passou por uma intensa **modernização da agropecuária**, chamada de "Revolução Verde", com o uso de máquinas, de fertilizantes, de defensivos, de sementes selecionadas e de irrigação, apoiados por crédito rural, pesquisa (Embrapa, criada em 1973) e infraestrutura. A produtividade aumentou muito, e o país se tornou um dos maiores produtores e exportadores mundiais de **soja**, **milho**, **carne bovina e de frango**, **açúcar**, **café** e **suco de laranja**. O conjunto das atividades ligadas ao campo, que inclui insumos, produção, processamento, transporte e comércio, é chamado de **agronegócio**, e representa grande parte do PIB e das exportações.',
  'A expansão do agronegócio ocorreu, em especial, no **Centro-Oeste** e na região conhecida como **MATOPIBA** (Maranhão, Tocantins, Piauí e Bahia), no Cerrado, graças à correção dos solos, à mecanização e às variedades adaptadas. Ela trouxe crescimento econômico, mas também **impactos socioambientais**: desmatamento, uso intensivo de agrotóxicos, contaminação da água, concentração de terras, expulsão de populações tradicionais, conflitos fundiários e redução da biodiversidade. O modelo de monocultura em grandes propriedades contrasta com a agricultura familiar e com as práticas agroecológicas, que defendem a produção de alimentos com respeito ao ambiente.'] },
 { h:'A estrutura fundiária e a questão agrária brasileira', p:[
  'A **estrutura fundiária** é a forma como a terra está distribuída entre as propriedades. No Brasil, ela é historicamente **concentrada**: a colonização organizou a terra em grandes propriedades (sesmarias), voltadas à monocultura de exportação com mão de obra escrava, o latifúndio. A **Lei de Terras** (1850) transformou a terra em mercadoria, acessível a quem pudesse pagar, o que dificultou o acesso de imigrantes, de libertos e de pobres. Essa herança explica a elevada **concentração** atual: um pequeno número de grandes propriedades ocupa a maior parte da área agrícola, enquanto a maioria dos estabelecimentos é de pequeno porte e ocupa pouca terra.',
  'A **questão agrária** é o conjunto de problemas relacionados à posse, ao uso e à distribuição da terra: concentração fundiária, conflitos pela terra, trabalho análogo à escravidão, grilagem, violência no campo e desigualdade. Os principais agentes são os **latifundiários** e as empresas do agronegócio, os **pequenos agricultores** e **posseiros**, os **trabalhadores sem-terra**, os **povos indígenas**, os **quilombolas** e as comunidades tradicionais. A terra pode ser vista como **bem de produção**, o que orienta o agronegócio, ou como **bem de vida**, ligada à moradia, à cultura e à subsistência das comunidades, e essa diferença de concepção alimenta muitos conflitos.',
  'A **reforma agrária** é a redistribuição de terras, com a desapropriação de áreas improdutivas ou que não cumprem a função social, e o assentamento de famílias, com apoio técnico e financeiro. A **Constituição de 1988** prevê que a propriedade deve cumprir sua função social, e que as áreas improdutivas podem ser desapropriadas para fins de reforma agrária. O **INCRA** é o órgão responsável pelo processo. Apesar de milhares de assentamentos criados, a reforma agrária avançou pouco, e a concentração de terras continua elevada, o que leva a críticas e a mobilizações de movimentos sociais.'] },
 { h:'Movimentos sociais no campo e conflitos', p:[
  'A luta pela terra tem longa história no Brasil: Canudos e Contestado, as **Ligas Camponesas** (década de 1950), que, em Pernambuco, lutaram por direitos dos trabalhadores rurais, e os sindicatos rurais. Em 1984, foi fundado o **MST** (Movimento dos Trabalhadores Rurais Sem Terra), que organiza ocupações de terras improdutivas, acampamentos e assentamentos, e defende a reforma agrária e a agroecologia. Outros movimentos incluem a **Comissão Pastoral da Terra** (CPT), ligada à Igreja, que registra e denuncia os conflitos, e organizações de povos indígenas, quilombolas, seringueiros e ribeirinhos, que reivindicam o direito ao território.',
  'Os **conflitos no campo** envolvem disputas por terra, por água e por recursos, e estão frequentemente associados à violência: assassinatos de lideranças, como Chico Mendes e a irmã Dorothy Stang, e massacres, como os de Corumbiara (1995) e de **Eldorado dos Carajás** (1996), em que policiais mataram 19 sem-terra, são marcos da violência no campo. A **grilagem** (falsificação de títulos de terras públicas) e o **trabalho análogo à escravidão** são problemas recorrentes, sobretudo em áreas de fronteira agrícola, na Amazônia e no Cerrado. A falta de regularização fundiária e a impunidade favorecem a violência.',
  'A **agricultura familiar** tem um papel essencial, pois é responsável por grande parte dos alimentos que chegam à mesa dos brasileiros (mandioca, feijão, leite, hortaliças), apesar de ocupar uma área menor do que a das grandes propriedades. Políticas como o **PRONAF** (crédito para agricultores familiares) e o **PAA** e o **PNAE** (compras públicas da agricultura familiar para a alimentação escolar) a apoiam. O debate entre o modelo do agronegócio, voltado à exportação de commodities, e o da agricultura familiar e agroecológica, voltado ao abastecimento interno e à sustentabilidade, é constante e muito presente nas provas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a questão agrária aparece em questões sobre a concentração fundiária, a reforma agrária, o MST e outros movimentos sociais do campo, os conflitos de terra, a modernização da agropecuária, os impactos do agronegócio (desmatamento, agrotóxicos), a agricultura familiar e as novas fronteiras agrícolas. Os enunciados trazem gráficos da estrutura fundiária, mapas das áreas de expansão da soja e da pecuária, textos de reportagens e imagens, e pedem para relacionar a estrutura da propriedade com os problemas sociais e ambientais.',
  'Pontos de atenção: a concentração de terras vem da colonização e da Lei de Terras de 1850; a modernização aumentou a produtividade, mas não resolveu a desigualdade; o agronegócio é importante para as exportações, mas tem impactos socioambientais; a agricultura familiar produz grande parte dos alimentos do mercado interno; e a reforma agrária é prevista na Constituição, que exige que a propriedade cumpra sua função social. Evite apresentar o agronegócio e a agricultura familiar como excludentes sem análise: o ENEM costuma pedir uma avaliação equilibrada, com dados.',
  'Para revisar, monte um quadro comparando agronegócio e agricultura familiar (tamanho, finalidade, tecnologia, empregos, impactos), e uma linha do tempo com a história da questão agrária (sesmarias, Lei de Terras, Ligas Camponesas, Estatuto da Terra de 1964, MST, Constituição de 1988). Relacione o tema às migrações (êxodo rural), à urbanização e à questão ambiental, e prepare o estudo da energia e dos transportes, que dão suporte à produção agropecuária e à sua exportação.'] }
]},
{ t:'Energia', txt:[
 { h:'Fontes de energia: renováveis e não renováveis', p:[
  'A **energia** é essencial para as atividades humanas: indústria, transportes, agricultura, iluminação e comunicação. As **fontes de energia** são classificadas em **não renováveis**, que se esgotam com o uso por demorarem milhões de anos para se formar (petróleo, carvão mineral, gás natural e urânio), e **renováveis**, que se regeneram em escala humana ou são praticamente inesgotáveis (hidráulica, solar, eólica, biomassa, geotérmica e maremotriz). O petróleo é a principal fonte de energia primária do mundo, seguido pelo carvão e pelo gás, e os combustíveis fósseis respondem por cerca de 80% do consumo.',
  'Os **combustíveis fósseis** têm grande densidade energética e infraestrutura consolidada, mas liberam gases de efeito estufa e poluentes, e suas reservas são concentradas em poucos países, o que gera dependência e conflitos geopolíticos, como no Oriente Médio. O **petróleo** é a base dos transportes e da petroquímica, e seus preços influenciam a economia mundial; a **OPEP** reúne os principais países exportadores. O **carvão mineral** é muito usado na geração elétrica na China e na Índia, e é o mais poluente. O **gás natural** emite menos CO2 e é visto como combustível de transição. A **energia nuclear**, a partir do urânio, não emite gases de efeito estufa na operação, mas gera rejeitos radioativos e riscos de acidentes.',
  'As **fontes renováveis** crescem em importância, diante das mudanças climáticas. A **hidrelétrica** usa a força da água, é limpa na operação, mas exige grandes reservatórios, que alagam áreas e alteram os ecossistemas. A **solar** (fotovoltaica e térmica) e a **eólica** são limpas e de custo cada vez menor, mas são **intermitentes**, dependem do sol e do vento, e exigem armazenamento e complementação. A **biomassa** (bagaço de cana, lenha, resíduos) e os **biocombustíveis** (etanol, biodiesel) são renováveis, mas podem competir com a produção de alimentos e causar desmatamento. A **geotérmica** aproveita o calor da Terra, em regiões vulcânicas, como a Islândia.'] },
 { h:'A matriz energética e a matriz elétrica do Brasil', p:[
  'É preciso distinguir a **matriz energética** (conjunto de todas as fontes de energia usadas em um país, para transportes, indústria, residências e eletricidade) da **matriz elétrica** (apenas as fontes usadas para gerar eletricidade). No Brasil, a matriz energética tem cerca de 45% de fontes renováveis, uma proporção muito superior à média mundial (cerca de 15%), com destaque para a cana-de-açúcar (etanol e bagaço), a hidráulica e a lenha, mas ainda é muito dependente do **petróleo e dos derivados** nos transportes. A matriz elétrica é ainda mais renovável, com cerca de 85%.',
  'Na matriz elétrica, a **hidrelétrica** é a principal fonte, respondendo por mais da metade da geração, graças à abundância de rios de planalto. As maiores usinas são **Itaipu** (binacional com o Paraguai, no rio Paraná), **Belo Monte** (rio Xingu), **Tucuruí** (rio Tocantins) e as do rio São Francisco e do Madeira. A **eólica**, concentrada no Nordeste (Rio Grande do Norte, Bahia e Ceará), e a **solar** crescem rapidamente. As **termelétricas** (gás, óleo e carvão) funcionam como complemento, em períodos de seca, e a **nuclear**, com as usinas de **Angra dos Reis** (Angra 1 e 2), responde por uma pequena parte.',
  'Entre os **biocombustíveis**, o Brasil é pioneiro e um dos maiores produtores de **etanol** de cana-de-açúcar, a partir do Proálcool (1975), criado em resposta à crise do petróleo. Os carros **flex**, desde 2003, permitem o uso de etanol ou gasolina. O **biodiesel**, de óleos vegetais e gordura animal, é misturado ao diesel. Os biocombustíveis reduzem as emissões líquidas de carbono, pois o CO2 liberado na queima é reabsorvido pelas plantas, mas sua produção exige terra e água, e deve ser planejada para não afetar a produção de alimentos e a vegetação nativa. O **pré-sal**, reservas de petróleo em grande profundidade, tornou o Brasil um grande produtor de petróleo.'] },
 { h:'Impactos socioambientais, segurança energética e transição', p:[
  'Toda fonte de energia tem **impactos**. As hidrelétricas alagam áreas, deslocam populações (os "atingidos por barragens"), alteram a pesca e a fauna e emitem metano, em alguns casos. As termelétricas emitem poluentes. A exploração de petróleo oferece o risco de **derramamentos**, como o de óleo na costa nordestina em 2019. A mineração de carvão e de urânio causa danos ambientais. As energias eólica e solar ocupam áreas e podem alterar a paisagem e as comunidades locais, mas têm impactos menores. Por isso, é essencial avaliar os custos e benefícios de cada fonte, considerando os aspectos ambientais, econômicos e sociais.',
  'A **segurança energética** é a garantia de fornecimento de energia de forma contínua e a preços acessíveis. A dependência do petróleo importado torna os países vulneráveis a crises, como as de 1973 e 1979, que levaram a buscas por alternativas. No Brasil, as **crises de energia**, como o "apagão" de 2001, causado pela seca e pelo baixo nível dos reservatórios, e a crise hídrica de 2014 a 2016, mostraram os riscos da dependência da hidroeletricidade e levaram à diversificação da matriz, com mais termelétricas, eólicas e solares, e às linhas de transmissão que integram o **Sistema Interligado Nacional**.',
  'A **transição energética** é a substituição gradual de combustíveis fósseis por fontes de baixo carbono, com o objetivo de reduzir as emissões e combater as mudanças climáticas, como previsto no **Acordo de Paris**. Inclui a eletrificação dos transportes, a eficiência energética, o hidrogênio verde, o armazenamento por baterias e as redes inteligentes. A **geração distribuída**, em que os consumidores produzem sua própria energia, por exemplo com placas solares em telhados, está em expansão. O Brasil tem condições favoráveis (sol, vento, biomassa e hidrelétricas), mas precisa investir em tecnologia, em infraestrutura e em políticas públicas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Energia é um dos temas mais frequentes do ENEM, em Geografia, Física e Química. As questões trazem gráficos das matrizes energética e elétrica do Brasil e do mundo, mapas de usinas e de linhas de transmissão, textos sobre petróleo, pré-sal, etanol, energia nuclear e fontes alternativas, e pedem para comparar vantagens e desvantagens, relacionar a fonte ao impacto ambiental e ao contexto, e avaliar a coerência das propostas. É comum aparecer a comparação entre a matriz brasileira e a mundial.',
  'Pontos de atenção: matriz energética e elétrica são diferentes; o Brasil tem matriz relativamente renovável, mas usa muito petróleo nos transportes; as hidrelétricas dependem das chuvas e têm impacto socioambiental; as fontes eólica e solar são limpas, porém intermitentes; os biocombustíveis reduzem as emissões, mas exigem terras; a energia nuclear não emite CO2, mas gera rejeitos; e o pré-sal aumentou a produção de petróleo. Ao avaliar uma proposta, considere os custos, a escala, os impactos e a viabilidade, e evite as respostas que afirmam que uma fonte "não causa nenhum impacto".',
  'Para revisar, monte uma tabela com cada fonte (fóssil, nuclear, hidrelétrica, eólica, solar, biomassa), a classificação, as vantagens, as desvantagens e o exemplo brasileiro. Compare as matrizes do Brasil e do mundo e identifique as principais usinas. Relacione o tema com as mudanças climáticas, com a hidrografia (rios de planalto) e com os transportes e a logística, o tema seguinte, que depende fortemente da energia e dos combustíveis, e que organiza a circulação de pessoas e de mercadorias pelo território.'] }
]},
{ t:'Transportes e logística', txt:[
 { h:'Modais de transporte e a matriz brasileira', p:[
  'O **transporte** é o deslocamento de pessoas e de mercadorias, e a **logística** é o conjunto de atividades que planeja e organiza esse deslocamento: armazenamento, embalagem, distribuição e informação. Eles são fundamentais para a economia, pois conectam produtores, indústrias, consumidores e mercados. Os principais **modais** (modos de transporte) são o **rodoviário**, o **ferroviário**, o **hidroviário** (fluvial, lacustre e marítimo), o **aéreo** e o **dutoviário** (dutos, para petróleo, gás e minérios). Cada um tem custos, capacidade, velocidade e impactos diferentes.',
  'O **rodoviário** é flexível, permite o transporte "porta a porta" e é adequado a distâncias curtas e médias, mas tem alto custo para grandes volumes e longas distâncias, consome muita energia, emite muitos poluentes e sofre com acidentes. O **ferroviário** transporta grandes volumes de cargas pesadas (minérios, grãos, combustíveis) a baixo custo por tonelada, com menor consumo de energia por tonelada transportada, mas exige altos investimentos em infraestrutura. O **hidroviário** é o mais barato e o menos poluente para grandes volumes, mas é lento e depende das condições dos rios e dos portos. O **aéreo** é rápido e caro, adequado a cargas de alto valor e a viagens de longa distância.',
  'A **matriz de transportes do Brasil** é muito concentrada no **modal rodoviário**, que responde por cerca de 60% do transporte de cargas, enquanto a ferrovia fica com cerca de 20% e a hidrovia, com algo em torno de 5%. Essa concentração é resultado de decisões históricas, em particular a partir do governo de Juscelino Kubitschek (1956 a 1961), que priorizou a **indústria automobilística** e a construção de rodovias, em detrimento das ferrovias, que haviam sido importantes na época do café. O resultado é um sistema de custos elevados, com impactos ambientais e problemas de manutenção, o que o torna menos eficiente para um país de grandes dimensões.'] },
 { h:'Rodovias, ferrovias, hidrovias e portos brasileiros', p:[
  'A rede **rodoviária** brasileira é extensa, mas, em grande parte, não é pavimentada, e muitas estradas apresentam má conservação. As principais rodovias partem de Brasília, como no projeto de integração nacional, e ligam as regiões: a BR-116 (Rio-Bahia e Sul), a BR-101 (litoral), a BR-153 (Belém-Brasília), a BR-163 (Cuiabá-Santarém, importante para escoar a soja do Centro-Oeste pelo Norte) e a **Transamazônica** (BR-230). Há **concessões** a empresas privadas, que cobram pedágio e investem na manutenção. A dependência do caminhão torna o país vulnerável a greves, como a dos caminhoneiros em 2018.',
  'As **ferrovias** foram construídas, no século XIX e início do XX, para escoar produtos (como o café) até os portos, e formavam redes desconectadas, de bitolas diferentes. Hoje, as principais ligam as áreas de mineração aos portos, como a Estrada de Ferro **Carajás** (Pará-Maranhão) e a **Vitória-Minas**, e as de grãos, como a **Ferrovia Norte-Sul**. O Brasil tem poucos trens de passageiros, e o transporte metroferroviário urbano é concentrado nas grandes cidades. As **hidrovias** têm grande potencial, em razão da rede hidrográfica, e as principais são a **Tietê-Paraná**, a do **Madeira**, a do **Tocantins-Araguaia** e a do **Paraguai**, mas são subutilizadas por falta de investimentos e de obras (eclusas, dragagem).',
  'Os **portos** são essenciais ao comércio exterior, pois cerca de 90% das exportações brasileiras em volume saem por via marítima. Os mais importantes são **Santos** (SP), o maior da América Latina, **Paranaguá** (PR), exportador de grãos, **Itaguaí** e **Tubarão** (Vitória), de minério, **Rio Grande** (RS), **Itajaí** (SC) e, no Norte, **Itaqui** (MA), **Vila do Conde** e **Santarém** (PA), que têm crescido com o "Arco Norte" das exportações agrícolas. Os principais gargalos incluem filas de caminhões, falta de acesso ferroviário, burocracia e dragagem insuficiente. Os **aeroportos** também são importantes, com destaque para Guarulhos e Brasília.'] },
 { h:'Logística, custos e o "custo Brasil"', p:[
  'Uma logística eficiente reduz custos e aumenta a competitividade. No Brasil, os custos logísticos são elevados, cerca de 12 a 15% do PIB, o que é mais do que em países desenvolvidos, e fazem parte do chamado "**custo Brasil**". Os principais problemas são a concentração no modal rodoviário, a má conservação de estradas, a falta de integração entre os modais (a **intermodalidade**), os gargalos portuários, a burocracia e o roubo de cargas. Em regiões de fronteira agrícola, como o Mato Grosso, a distância até os portos encarece o frete e reduz a competitividade do produto.',
  'A **intermodalidade** (ou multimodalidade) é o uso combinado de diferentes modais, com o objetivo de aproveitar as vantagens de cada um: por exemplo, o caminhão para a coleta, a ferrovia para o trecho longo e o navio para a exportação. O uso de **contêineres**, que padronizam as cargas e facilitam a transferência entre os modais, revolucionou o comércio internacional. A **logística reversa** organiza o retorno de produtos e de embalagens, para reciclagem. O uso de tecnologia, como rastreamento por GPS, sistemas de gestão e automação dos portos, aumenta a eficiência. O **comércio eletrônico** impulsionou a entrega rápida e os centros de distribuição.',
  'O Brasil tem grandes **corredores de exportação**, que conectam as áreas produtoras aos portos. Os de soja do Centro-Oeste e Matopiba partem pelos portos do Sul e do Sudeste (Santos e Paranaguá) e, cada vez mais, pelos do Norte (Arco Norte). A ferrovia Norte-Sul e a Ferrogrão (projetada) buscam reduzir os custos. Os grandes projetos de infraestrutura geram debates, pois podem impulsionar a economia, mas também provocar desmatamento e conflitos com comunidades, como no caso da BR-163 e da Ferrogrão, que atravessam áreas de alto valor ambiental e territórios indígenas.'] },
 { h:'Mobilidade urbana, impactos ambientais e tendências', p:[
  'Nas cidades, o **transporte** envolve a **mobilidade urbana**, a facilidade de deslocamento das pessoas. A priorização do automóvel particular gerou **congestionamentos**, poluição e acidentes, e a falta de transporte coletivo de qualidade penaliza os mais pobres, que moram longe do trabalho. A **Política Nacional de Mobilidade Urbana** (2012) prioriza o transporte coletivo e não motorizado (a pé e de bicicleta). As soluções incluem metrôs, trens urbanos, corredores de ônibus (BRT), VLTs, ciclovias, integração tarifária, pedágios urbanos e restrição de veículos. A mobilidade está ligada à justiça social e à qualidade do ar.',
  'Os **impactos ambientais** do transporte são relevantes: o setor responde por grande parte das emissões de gases de efeito estufa e de poluentes locais. Para reduzi-los, defendem-se a **eletrificação** da frota, o uso de **biocombustíveis**, o transporte coletivo, o deslocamento ativo e a transferência de cargas para ferrovias e hidrovias, que são mais eficientes. A construção de **estradas** e portos pode causar desmatamento, fragmentação de habitats e atropelamentos de fauna, exigindo licenciamento e medidas de mitigação, como passagens de fauna. A infraestrutura de transportes é, assim, uma questão econômica, social e ambiental.',
  'Como **tendências**, destacam-se os **veículos elétricos** e autônomos, os aplicativos de transporte e de entrega, o crescimento do **comércio eletrônico**, a digitalização da logística, o uso de **drones** e a busca de combustíveis limpos para os aviões e navios. A infraestrutura de transportes, no Brasil, necessita de investimentos, de planejamento de longo prazo e de parcerias entre o poder público e a iniciativa privada (**concessões e PPPs**). Ao mesmo tempo, é preciso reduzir a dependência do rodoviário e melhorar a integração entre as regiões, o que ajudaria a reduzir desigualdades regionais e a favorecer o desenvolvimento sustentável.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, os transportes aparecem em questões que pedem a comparação entre os modais (custo, capacidade, impacto), a análise da matriz brasileira, concentrada na rodovia, o papel das ferrovias e hidrovias, a função dos portos, os gargalos logísticos e os problemas de mobilidade urbana. Os enunciados trazem mapas da rede de transportes, gráficos da matriz modal e textos sobre greves, obras e corredores de exportação, e pedem a relação entre a infraestrutura, a economia e o ambiente. A relação com o agronegócio e com a mineração é comum.',
  'Pontos de atenção: o modal rodoviário predomina por opção histórica, e é caro e poluente para grandes distâncias; ferrovias e hidrovias são mais eficientes para grandes volumes, mas pouco desenvolvidas; os portos são essenciais para as exportações; a intermodalidade e os contêineres aumentam a eficiência; e a mobilidade urbana exige priorizar o transporte coletivo e o não motorizado. Evite respostas que tratem uma obra de infraestrutura apenas como benefício, sem considerar os impactos sociais e ambientais, ou o contrário.',
  'Para revisar, monte um quadro dos modais (vantagens, desvantagens, uso no Brasil) e liste as principais obras e corredores (Carajás, Norte-Sul, Tietê-Paraná, BR-163, portos de Santos e Paranaguá). Relacione o tema com a industrialização (que escolheu a rodovia), com o agronegócio (que precisa de logística) e com a energia (combustíveis e emissões). A seguir, o estudo da globalização e da economia mundial mostrará como os fluxos de mercadorias, de capitais e de informações conectam o Brasil ao resto do planeta.'] }
]}
];

/* quinto bloco do tema Agropecuária e questão agrária */
{
  const ag = module.exports[0];
  const ult = ag.txt.pop();
  ag.txt.push({ h:'Pecuária, agrotóxicos e agricultura sustentável', p:[
    'A **pecuária** brasileira é uma das maiores do mundo, com o maior rebanho bovino comercial do planeta. Pode ser **extensiva**, em que o gado é criado solto em grandes áreas de pasto, com baixa produtividade e grande uso de terra, ou **intensiva**, com confinamento, melhoramento genético, suplementação alimentar e maior produtividade por hectare. A expansão da pecuária extensiva é uma das principais causas de desmatamento na Amazônia. Também crescem as criações de aves e de suínos, concentradas no Sul e no Centro-Oeste, integradas à agroindústria, e voltadas à exportação.',
    'O uso de **agrotóxicos** (defensivos agrícolas) aumentou muito com a modernização. Eles protegem as lavouras de pragas e doenças, mas podem contaminar o solo, a água, os alimentos e os trabalhadores, e afetar polinizadores e outros organismos. O Brasil está entre os maiores consumidores do mundo, e a regulamentação, os limites de resíduos e a fiscalização são objeto de debate. Os **transgênicos** (soja, milho e algodão geneticamente modificados) são amplamente cultivados, o que traz benefícios de produtividade, mas levanta discussões sobre dependência de sementes, de patentes e sobre efeitos ambientais.',
    'Como alternativas, ganham espaço as práticas **sustentáveis**: a **agricultura orgânica** e a **agroecologia**, que dispensam agrotóxicos sintéticos e valorizam a biodiversidade e o conhecimento local; o **plantio direto**; a **rotação de culturas**; o **manejo integrado de pragas**; a **integração lavoura-pecuária-floresta**; a **recuperação de pastagens degradadas**; e a **agricultura de baixo carbono**. A certificação socioambiental, a rastreabilidade e as exigências dos mercados consumidores, como as da União Europeia, também pressionam por produções que não causem desmatamento. Conciliar produtividade e conservação é o grande desafio do campo.'
  ]});
  ag.txt.push(ult);
}

/* quinto bloco do tema Energia */
{
  const en = module.exports[1];
  const ult = en.txt.pop();
  en.txt.push({ h:'A geopolítica da energia', p:[
    'A energia é um dos elementos centrais da **geopolítica** mundial. O **petróleo** está concentrado em poucos países, em especial no Oriente Médio (Arábia Saudita, Irã, Iraque, Kuwait e Emirados Árabes), mas também na Rússia, nos Estados Unidos (que se tornaram grandes produtores com o óleo de xisto), na Venezuela, no Canadá e no Brasil. A dependência de importações torna países como a China, o Japão, a Índia e os europeus vulneráveis, e as rotas marítimas, como o **estreito de Ormuz**, são estratégicas. As disputas por petróleo e gás estiveram envolvidas em guerras, como a do Golfo (1991) e a do Iraque (2003).',
    'A **OPEP** (Organização dos Países Exportadores de Petróleo), criada em 1960, coordena a produção e influencia os preços. Os **choques do petróleo** de 1973 e 1979, quando os preços dispararam, mostraram a força desses países e levaram os consumidores a buscar alternativas e eficiência, como o Proálcool no Brasil. O **gás natural** também tem peso geopolítico: a Rússia fornece gás à Europa por gasodutos, e a guerra na Ucrânia, a partir de 2022, escancarou os riscos dessa dependência e acelerou a busca por diversificação, incluindo o gás natural liquefeito e as energias renováveis.',
    'A **transição energética** também redesenha o mapa do poder. Países com muito sol e vento, e com reservas de minerais críticos, como o **lítio**, o cobalto e as terras raras, necessários para baterias, painéis e turbinas, ganham importância, e a China domina boa parte da cadeia de produção. O Brasil tem potencial, por suas fontes renováveis e suas reservas minerais. Ao mesmo tempo, o acesso à energia é desigual: bilhões de pessoas ainda cozinham com lenha e carvão, e milhões não têm eletricidade, principalmente na África Subsaariana. A pobreza energética é, assim, um desafio de desenvolvimento e de justiça social.'
  ]});
  en.txt.push(ult);
}
