/* História: textos corridos, temas 16 a 18 */
module.exports = [
{ t:'República Democrática (1945 a 1964)', txt:[
 { h:'A redemocratização e o governo Dutra', p:[
  'Com o fim da Era Vargas, em 1945, o Brasil iniciou um período de democracia, que se estendeu até 1964 e é chamado de **República Democrática**, **República Populista** ou Quarta República. Foram convocadas eleições, e o general **Eurico Gaspar Dutra**, apoiado por Vargas, foi eleito presidente. Os partidos políticos voltaram a funcionar, e os principais foram o **PSD** (Partido Social Democrático, ligado a antigos interventores e grandes proprietários), a **UDN** (União Democrática Nacional, antigetulista e liberal-conservadora) e o **PTB** (Partido Trabalhista Brasileiro, criado por Vargas, voltado aos trabalhadores urbanos e aos sindicatos).',
  'A **Constituição de 1946** restabeleceu as liberdades democráticas, o equilíbrio entre os poderes, a autonomia dos estados e municípios, o voto direto e secreto, e a anistia, mas manteve a exclusão dos analfabetos do voto, e conservou a estrutura sindical criada no Estado Novo. No contexto da **Guerra Fria**, o governo Dutra alinhou-se aos Estados Unidos, rompeu relações com a União Soviética e colocou na ilegalidade o **Partido Comunista do Brasil**, em 1947, cassando os mandatos de seus parlamentares. O anticomunismo marcou a política da época, e deu base a novas restrições.',
  'Na economia, Dutra adotou uma política liberal, com a abertura às importações, que consumiu as reservas cambiais acumuladas durante a guerra, e foi criticado. O **Plano SALTE** (saúde, alimentação, transporte e energia), lançado em 1948, previa investimentos em áreas fundamentais, mas teve pouca eficácia, por falta de recursos. O governo também combateu greves e interveio em sindicatos. Esse período mostrou a dificuldade de conciliar a democracia formal com as desigualdades sociais, e preparou a volta de Vargas, que se elegeu em 1950, com uma plataforma nacionalista e trabalhista.'] },
 { h:'O segundo governo Vargas e o suicídio', p:[
  'Getúlio Vargas voltou ao poder, em 1951, eleito pelo voto popular, com um programa de **nacionalismo econômico** e valorização dos trabalhadores. Defendeu a industrialização, com o controle estatal de setores estratégicos, e criou o **BNDE** (Banco Nacional de Desenvolvimento Econômico, 1952) e a **Petrobras** (1953), após uma campanha popular chamada "O petróleo é nosso", que garantiu o **monopólio estatal** da exploração e do refino do petróleo. Também propôs a criação da Eletrobras. Aumentou o salário mínimo em 100% (1954), o que provocou forte reação dos empresários e da oposição.',
  'O governo enfrentou grandes dificuldades: inflação, crise econômica, pressão dos Estados Unidos contra o nacionalismo e a oposição da **UDN** e de setores militares, que acusavam o governo de corrupção e de planejar uma "república sindicalista". O jornalista **Carlos Lacerda**, da UDN, liderou uma campanha contra Vargas, pelo jornal Tribuna da Imprensa. Em agosto de 1954, um atentado contra Lacerda, no qual morreu um major da Aeronáutica, foi atribuído a integrantes da guarda pessoal do presidente, o que ampliou a crise e levou os militares a exigir sua renúncia.',
  'Em **24 de agosto de 1954**, Vargas se suicidou com um tiro no peito, e deixou uma **Carta-Testamento**, em que se apresentava como vítima das forças contrárias ao povo e ao desenvolvimento nacional ("Saio da vida para entrar na História"). O gesto causou comoção nacional, com manifestações populares contra os adversários, e adiou o golpe que se desenhava. O vice, **Café Filho**, assumiu o poder. Vargas passou a ser visto, por muitos, como mártir do nacionalismo e do trabalhismo, o que manteve o getulismo influente e levou à vitória de aliados nas eleições seguintes.'] },
 { h:'JK, o desenvolvimentismo e Brasília', p:[
  'Em 1955, foi eleito **Juscelino Kubitschek** (JK), do PSD, apoiado pela aliança com o PTB, de João Goulart, que assumiu a vice-presidência. Ele tomou posse após uma crise, que envolveu tentativas de impedir sua posse e um movimento de militares, o "contragolpe preventivo" do general Henrique Lott. JK governou de 1956 a 1961, com o lema "**cinquenta anos em cinco**" e o **Plano de Metas**, um programa de desenvolvimento voltado à energia, aos transportes, à alimentação, à indústria de base e à educação, tendo como "meta-síntese" a construção da nova capital.',
  'O **desenvolvimentismo** de JK abriu a economia ao **capital estrangeiro**, com incentivos às multinacionais, em particular no setor automobilístico (Volkswagen, Ford, General Motors, Willys), e estimulou a construção de rodovias, em detrimento das ferrovias. A indústria cresceu, o país se urbanizou e a classe média se expandiu. Foi um período de otimismo, com a bossa nova, o cinema novo, a conquista da primeira Copa do Mundo (1958) e a construção de **Brasília**, inaugurada em **1960**, projetada por Lúcio Costa (plano piloto) e Oscar Niemeyer (arquitetura), com o objetivo de integrar o interior do país e interiorizar o desenvolvimento.',
  'O modelo teve custos. O financiamento do crescimento foi feito pela emissão de moeda e por empréstimos externos, o que aumentou a **inflação** e a **dívida externa**. As desigualdades regionais e sociais permaneceram, e a concentração de renda aumentou. A **Operação Pan-Americana** e a ruptura com o FMI, em 1959, marcaram a política externa. Os trabalhadores rurais continuavam sem direitos, e a questão da terra era um problema. Esses desequilíbrios aumentariam a instabilidade nos governos seguintes, e criariam as condições para o aprofundamento da crise política.'] },
 { h:'Jânio, Jango e a crise que levou ao golpe de 1964', p:[
  'Em 1960, foi eleito **Jânio Quadros**, com a promessa de combater a corrupção (símbolo: a vassoura) e de acabar com a inflação. Governou de forma personalista e controvertida: adotou medidas de austeridade, proibiu o uso de biquínis e as rinhas de galo, e conduziu uma **política externa independente**, que aproximou o Brasil de países socialistas e condecorou Che Guevara, o que desagradou aos setores conservadores e aos Estados Unidos. Em **agosto de 1961**, após sete meses, **renunciou** de forma inesperada, talvez esperando voltar com mais poderes, o que não ocorreu.',
  'O vice, **João Goulart** (Jango), do PTB, estava em viagem à China, e os ministros militares tentaram impedir sua posse, por considerá-lo ligado ao comunismo. Houve a **Campanha da Legalidade**, liderada por Leonel Brizola, governador do Rio Grande do Sul, que mobilizou a população em defesa da Constituição. Para evitar a guerra civil, foi aprovada uma emenda que instituiu o **parlamentarismo**, retirando poderes do presidente. Jango assumiu, e, em 1963, um plebiscito restabeleceu o presidencialismo, devolvendo-lhe os poderes.',
  'Jango propôs as **Reformas de Base**: reforma agrária, urbana, bancária, tributária, educacional e eleitoral, com o direito de voto aos analfabetos e aos militares de baixa patente. A radicalização política cresceu: de um lado, as Ligas Camponesas, os sindicatos e os movimentos estudantis; de outro, empresários, setores da Igreja, a grande imprensa, os militares, a classe média e os Estados Unidos, que, no contexto da Guerra Fria, temiam um "novo Cuba". Em 13 de março de 1964, o **Comício da Central do Brasil** anunciou as reformas, e a reação foi a **Marcha da Família com Deus pela Liberdade**. Em 31 de março, um golpe militar depôs Jango.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a República Democrática aparece em questões sobre o populismo (relação entre líderes e massas), a atuação de partidos (PSD, UDN e PTB), o nacionalismo econômico (Petrobras), o desenvolvimentismo de JK (entrada de capital estrangeiro, indústria automobilística, construção de Brasília), a política externa e a crise que levou ao golpe de 1964. Os enunciados trazem cartazes de campanha, trechos de discursos e da Carta-Testamento, e imagens de Brasília, e pedem a identificação do contexto.',
  'Pontos de atenção: o período teve democracia, mas com exclusão dos analfabetos do voto e forte influência militar; o populismo envolveu direitos e propaganda, e não se reduz a "manipulação"; JK promoveu crescimento acelerado, com o preço da inflação e da dívida; a Petrobras nasceu de uma ampla campanha nacionalista; as Reformas de Base de Jango foram contestadas por setores conservadores; e o golpe de 1964 teve apoio civil e militar, e de potências externas. Relacione o contexto interno com a Guerra Fria.',
  'Para revisar, monte uma linha do tempo: 1945 (redemocratização), 1946 (Constituição), 1951 (volta de Vargas), 1953 (Petrobras), 1954 (suicídio), 1956 a 1961 (JK), 1960 (Brasília), 1961 (renúncia de Jânio), 1961 a 1964 (Jango, Reformas de Base) e 1964 (golpe). Em seguida, estude a Ditadura Militar, que aprofundou o modelo econômico e restringiu as liberdades, com marcos como o AI-5, a censura e a luta pela redemocratização.'] }
]},
{ t:'Ditadura Militar (1964 a 1985)', txt:[
 { h:'O golpe de 1964 e os primeiros governos', p:[
  'Em **31 de março de 1964**, tropas lideradas pelo general Olímpio Mourão Filho saíram de Minas Gerais em direção ao Rio de Janeiro, e, com a adesão de militares e o apoio de governadores, empresários, setores da Igreja e da imprensa, derrubaram **João Goulart**, que deixou o país. Os golpistas se justificaram com o argumento do "perigo comunista" e da defesa da ordem. Os **Estados Unidos**, que temiam uma "nova Cuba", apoiaram o golpe, com a Operação Brother Sam. Foi o início de um regime que durou 21 anos, com cinco presidentes militares, todos eleitos indiretamente pelo Congresso.',
  'O primeiro ato institucional, o **AI-1**, cassou mandatos e direitos políticos, e deu poder ao Executivo. O marechal **Castelo Branco** assumiu o governo (1964 a 1967), e seus ministros formaram a "linha dura" e a "castelista" (mais moderada). Seu governo extinguiu os partidos existentes por meio do **AI-2** (1965) e instituiu o **bipartidarismo**: a **ARENA**, governista, e o **MDB**, de oposição consentida. As eleições para presidente e governadores passaram a ser indiretas. Foi criado o **SNI** (Serviço Nacional de Informações), órgão de espionagem política. A **Constituição de 1967** institucionalizou o regime e concentrou o poder no Executivo.',
  'Seu sucessor, **Costa e Silva** (1967 a 1969), enfrentou a oposição crescente: manifestações estudantis, como a **Passeata dos Cem Mil** (1968) no Rio de Janeiro, greves operárias, em Contagem e Osasco, e a atuação de artistas e intelectuais. A morte do estudante Edson Luís, pela polícia, intensificou os protestos. Em 1968, um discurso do deputado Márcio Moreira Alves, que sugeriu um boicote às festas militares, serviu de pretexto para o endurecimento. Em 13 de dezembro de 1968, o governo decretou o **AI-5**, o mais duro dos atos institucionais, que marcou o início dos "anos de chumbo".'] },
 { h:'Os anos de chumbo: AI-5, repressão e luta armada', p:[
  'O **AI-5** deu ao presidente poder para fechar o Congresso, cassar mandatos, suspender direitos políticos, decretar intervenção nos estados, demitir funcionários, censurar a imprensa e suspender o **habeas corpus** para crimes políticos. Na prática, instalou uma ditadura sem limites legais. A censura atingiu jornais, revistas, livros, peças de teatro, filmes e músicas, e muitos artistas e intelectuais, como Chico Buarque, Caetano Veloso e Gilberto Gil, foram perseguidos, presos ou exilados. A **tortura**, a prisão arbitrária, as mortes e os desaparecimentos políticos foram práticas sistemáticas do aparelho repressivo.',
  'O aparato repressivo incluía o **DOI-CODI** (Destacamento de Operações de Informações, Centro de Operações de Defesa Interna), o **DOPS**, e outros órgãos. Diante do fechamento do regime, parte da oposição de esquerda optou pela **luta armada**, com grupos como a ALN, de Carlos Marighella, e a VPR, que realizaram assaltos a bancos, sequestros de diplomatas e outras ações. Houve também a **Guerrilha do Araguaia** (1972 a 1974), organizada pelo PCdoB, no sul do Pará, que foi destruída pelas Forças Armadas. A repressão eliminou, em poucos anos, a maioria desses grupos, e deixou centenas de mortos e desaparecidos.',
  'Durante o governo de **Médici** (1969 a 1974), o mais repressivo, a censura e a tortura atingiram o auge, ao mesmo tempo em que a propaganda oficial exaltava o "Brasil Grande", com slogans como "Brasil, ame-o ou deixe-o". A conquista da Copa de 1970 foi explorada politicamente. O **Estado** usou a **Doutrina de Segurança Nacional**, que via os opositores como "inimigos internos", para justificar a violência. Esse período deixou marcas profundas, que a **Comissão Nacional da Verdade**, criada em 2011, investigou, concluindo que houve graves violações dos direitos humanos praticadas pelo Estado.'] },
 { h:'O "milagre econômico", a dívida e o modelo de desenvolvimento', p:[
  'Entre 1968 e 1973, a economia brasileira cresceu a taxas muito altas, de cerca de 10% ao ano, em um período chamado de **"milagre econômico"**. O crescimento foi sustentado por uma política de arrocho salarial, que contribuiu para a concentração de renda, de incentivos à indústria, de investimentos estatais em infraestrutura (como a Transamazônica, a ponte Rio-Niterói e usinas), do crédito ao consumo e da entrada de capitais estrangeiros. A **inflação** foi controlada, em parte, por meios artificiais, e a propaganda oficial fortaleceu o apoio de setores da classe média ao regime.',
  'O modelo trouxe também problemas. A **concentração de renda** aumentou: o ditado "é preciso esperar o bolo crescer para depois dividi-lo", atribuído ao ministro Delfim Netto, simbolizou a promessa que não se cumpriu. Aumentou a **dívida externa**, com empréstimos a juros baixos, que se tornaram um peso a partir da crise do petróleo (1973 e 1979), quando os juros e o custo da energia subiram. Os **impactos ambientais** e sociais dos grandes projetos, como a abertura da Amazônia, afetaram populações indígenas e ribeirinhas. A crise econômica do final da década enfraqueceu o regime.',
  'Na década de 1970, houve também incentivos à **colonização da Amazônia**, com programas como o Plano de Integração Nacional, que se justificava pela segurança nacional, e à agricultura de exportação. Cresceu o **êxodo rural** e a **urbanização**, com favelas e periferias nas grandes cidades. O regime buscou a legitimação por meio do desenvolvimento, mas a desigualdade e as dificuldades sociais ampliaram a insatisfação, e o **MDB** obteve vitórias nas eleições legislativas de 1974, sinalizando a perda de apoio da população e a necessidade de mudanças.'] },
 { h:'A abertura política e o fim da ditadura', p:[
  'A partir de 1974, o general **Ernesto Geisel** iniciou uma **abertura "lenta, gradual e segura"**, buscando controlar a transição para que o regime mantivesse o poder. Convivendo com a pressão da "linha dura", que resistia, e da sociedade, que reivindicava mudanças, o processo teve avanços e retrocessos. Em 1975, a morte do jornalista **Vladimir Herzog** nas dependências do DOI-CODI, em São Paulo, e a de outros opositores provocaram indignação e protestos. Em 1977, Geisel fechou o Congresso temporariamente e baixou o "Pacote de Abril", para garantir maioria governista. Em 1978, o **AI-5** foi revogado.',
  'O governo de **João Figueiredo** (1979 a 1985) deu continuidade à abertura. Em **1979**, foi aprovada a **Lei da Anistia**, que permitiu o retorno de exilados e a libertação de presos políticos, mas também perdoou os agentes do Estado acusados de crimes, o que gerou, e ainda gera, debates. O bipartidarismo foi extinto e surgiram novos partidos, como o PT, o PMDB, o PDS e o PDT. Ressurgiram os movimentos sociais: o **novo sindicalismo** do ABC paulista, com Lula, as greves de 1978 a 1980, os movimentos de bairros, a Igreja (CEBs) e a imprensa alternativa.',
  'A campanha das **Diretas Já** (1983 a 1984), que reuniu milhões de pessoas em comícios, exigia eleições diretas para presidente, mas a **Emenda Dante de Oliveira** foi rejeitada no Congresso. Em 1985, o Colégio Eleitoral elegeu indiretamente o oposicionista **Tancredo Neves**, que adoeceu e morreu antes de tomar posse. Assumiu o vice, **José Sarney**, e o país passou a ser governado por um civil, o que marcou o fim formal da ditadura militar. A redemocratização foi, assim, lenta, controlada e resultado de negociações e de mobilizações populares, o que explica muitas características da Nova República.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Ditadura Militar é um dos temas mais frequentes do ENEM. As questões trazem trechos dos atos institucionais, propagandas oficiais, letras de música de protesto (Chico Buarque, Geraldo Vandré), charges, depoimentos de presos políticos e documentos da Comissão da Verdade. Pedem a compreensão das características do regime (autoritarismo, censura, repressão, bipartidarismo, milagre econômico), das formas de resistência (movimento estudantil, luta armada, movimentos sociais, cultura) e do processo de abertura (Anistia, Diretas Já).',
  'Pontos de atenção: o regime foi uma **ditadura civil-militar**, com apoio de parte da sociedade; os atos institucionais sustentaram o regime, e o AI-5 foi o mais duro; o "milagre econômico" veio acompanhado de arrocho salarial, concentração de renda e endividamento; a censura e a tortura foram sistemáticas; a abertura foi "lenta, gradual e segura", controlada pelo governo; a Lei da Anistia foi ampla e recíproca; as Diretas Já foram derrotadas no Congresso, mas mobilizaram o país. Evite ideias que minimizem a violência do regime ou que o vejam como "só um governo forte".',
  'Para revisar, esquematize: 1964 (golpe) → AI-1, AI-2 e bipartidarismo → Constituição de 1967 → AI-5 (1968) → Médici (milagre e repressão) → Geisel (abertura lenta) → Figueiredo (Anistia, fim do bipartidarismo) → Diretas Já → 1985 (Tancredo e Sarney). Relacione ao tema anterior (crise de 1964) e ao seguinte (Nova República e Constituição de 1988), que estabelece direitos e instituições democráticas depois de um longo período de autoritarismo.'] }
]},
{ t:'Nova República e Constituição de 1988', txt:[
 { h:'A transição democrática e o governo Sarney', p:[
  'A **Nova República** começou em 1985, com a posse de **José Sarney**, após a morte de Tancredo Neves, e se mantém até hoje. Seus primeiros anos foram de transição democrática: foram revogadas as leis autoritárias, restabeleceram-se eleições diretas para prefeitos das capitais e foi concedido o voto aos analfabetos, por meio de emenda, em 1985. A legalização dos partidos de esquerda, como o PCB e o PCdoB, e a liberdade de imprensa e de organização marcaram a volta das liberdades políticas. Ainda assim, o governo dependia de forças conservadoras e enfrentava grandes desafios econômicos.',
  'Na economia, a década de 1980, a "década perdida", foi marcada por **hiperinflação**, estagnação, aumento da dívida externa e desemprego. O governo Sarney tentou controlá-la com planos econômicos heterodoxos: o **Plano Cruzado** (1986), que congelou preços e salários e criou nova moeda, trouxe alívio inicial e popularidade, mas fracassou por causa do desabastecimento e da volta da inflação; seguiram-se o Plano Bresser e o Plano Verão. A frustração com os resultados e as denúncias de corrupção enfraqueceram o governo, que terminou impopular, em meio a crise econômica.',
  'Em 1987, foi convocada a **Assembleia Nacional Constituinte**, formada pelos deputados e senadores eleitos em 1986, que redigiu uma nova Constituição, em um processo com grande participação popular, por meio de audiências públicas, emendas populares e mobilização de movimentos sociais, sindicatos, entidades de classe, de direitos humanos e de grupos indígenas. O processo foi marcado por disputas entre um bloco conservador, o "Centrão", e setores progressistas. O resultado foi uma Constituição extensa, que combinava avanços sociais com concessões a interesses tradicionais, e que ficou conhecida como a "**Constituição Cidadã**".'] },
 { h:'A Constituição de 1988: direitos e organização do Estado', p:[
  'Promulgada em **5 de outubro de 1988**, a **Constituição Federal** é considerada a mais democrática da história brasileira. Estabeleceu o **Estado Democrático de Direito**, fundado na soberania, na cidadania, na **dignidade da pessoa humana**, nos valores sociais do trabalho e no pluralismo político. Definiu os **direitos fundamentais**, entre eles a igualdade perante a lei, a liberdade de expressão, o direito de reunião e de associação, a proteção da privacidade e do acesso à informação, e o direito à vida. Também criou garantias, como o **habeas corpus**, o **habeas data** e o **mandado de segurança**, para proteger os cidadãos contra abusos.',
  'No campo dos **direitos sociais**, garantiu a educação, a saúde, o trabalho, a moradia, o lazer, a segurança, a previdência e a assistência social. Criou o **Sistema Único de Saúde** (SUS), universal e gratuito, ampliou a **seguridade social**, reconheceu o direito de greve e a liberdade sindical, e reduziu a jornada semanal para 44 horas. Estabeleceu o **voto facultativo** para analfabetos e jovens de 16 e 17 anos e para os maiores de 70, e o **voto obrigatório** para os demais cidadãos maiores de 18 anos. Definiu que o racismo é **crime inafiançável e imprescritível**, e que a tortura é crime inafiançável e insuscetível de graça ou anistia.',
  'A Constituição também reconheceu os direitos de **povos indígenas** (terras tradicionais, cultura e organização) e das **comunidades remanescentes de quilombos**, protegeu o **meio ambiente** como direito de todos, e incluiu princípios de proteção ao consumidor, à criança e ao adolescente (que originou o Estatuto da Criança e do Adolescente, de 1990) e aos idosos. Na organização do Estado, manteve a **República federativa e presidencialista**, com separação de poderes e autonomia dos estados e municípios. Em 1993, um plebiscito confirmou a escolha por República e presidencialismo, em vez de monarquia e parlamentarismo.'] },
 { h:'Os governos pós-1988: estabilização, alternância e desafios', p:[
  'Em 1989, ocorreu a primeira eleição direta para presidente em quase 30 anos, vencida por **Fernando Collor de Mello**, que adotou um plano de estabilização radical, com o confisco de poupanças (**Plano Collor**), e a abertura da economia às importações. Acusado de corrupção, sofreu um processo de **impeachment**, em 1992, após forte mobilização popular, como a dos "caras-pintadas", e renunciou. Assumiu o vice, **Itamar Franco**, e, em 1994, seu ministro da Fazenda, **Fernando Henrique Cardoso**, lançou o **Plano Real**, que estabilizou os preços e reduziu a inflação, o que lhe deu a vitória na eleição daquele ano.',
  'O governo de **Fernando Henrique** (1995 a 2002) promoveu **privatizações**, reformas, o equilíbrio fiscal e a ampliação de programas sociais, como o Bolsa Escola, e aprovou a emenda da **reeleição**. Em 2002, foi eleito **Luiz Inácio Lula da Silva** (PT), em uma alternância de poder marcante, e seu governo (2003 a 2010) ampliou programas de transferência de renda, como o **Bolsa Família**, aumentou o salário mínimo e a oferta de crédito, e apoiou a ascensão social de milhões de brasileiros, em um período de crescimento econômico. Seguiram-se os governos de **Dilma Rousseff** (2011 a 2016), que sofreu um processo de impeachment, em 2016, **Michel Temer**, **Jair Bolsonaro** e novamente Lula.',
  'A Nova República é marcada, assim, por conquistas e por desafios. Entre as conquistas, a estabilidade das instituições democráticas, a alternância de poder, a ampliação do acesso à educação e à saúde, a redução da pobreza e as conquistas de direitos de grupos historicamente excluídos. Entre os desafios, a **desigualdade social**, a **violência**, a **corrupção**, a polarização política, as crises econômicas e a necessidade de aprimorar a representação política. A participação popular, por meio de movimentos sociais e das manifestações, tem papel importante, como nas jornadas de junho de 2013.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Nova República e a Constituição de 1988 aparecem no ENEM em questões sobre cidadania e direitos, em que o enunciado traz artigos da Constituição e pede para relacionar com situações práticas (direito à saúde, à educação, igualdade racial, direitos indígenas, meio ambiente, voto). Também há questões sobre as Diretas Já, o impeachment de Collor, o Plano Real e o papel dos movimentos sociais. A habilidade principal é compreender os direitos como conquistas históricas, e perceber a distância entre a norma e a realidade.',
  'Pontos de atenção: a Constituição de 1988 foi elaborada com ampla participação popular e é chamada de "Cidadã"; ela define como cláusulas pétreas os direitos fundamentais; estabelece o SUS e a seguridade social; protege as terras indígenas e quilombolas; define o racismo como crime inafiançável e imprescritível; e mantém o voto obrigatório para a maioria e facultativo para os analfabetos, jovens de 16 e 17 anos e idosos. Atenção aos conceitos de cidadania civil, política e social, e à ideia de que direitos conquistados exigem vigilância.',
  'Para revisar, esquematize: 1985 (Sarney, fim da ditadura) → 1986 (Plano Cruzado) → 1987 a 1988 (Constituinte) → 1989 (eleição de Collor) → 1992 (impeachment) → 1994 (Plano Real) → 2002 (alternância) → programas sociais → desafios atuais. Relacione a Constituição aos temas de cidadania e direitos humanos, que reaparecem em Sociologia, Filosofia e na redação, e se prepare para o bloco seguinte, que trata da História Geral do século XX, começando pela Primeira Guerra Mundial.'] }
]}
];

/* quinto bloco do tema Nova República e Constituição de 1988 */
{
  const nr = module.exports[2];
  const ult = nr.txt.pop();
  nr.txt.push({ h:'Cidadania, participação e memória democrática', p:[
    'O conceito de **cidadania**, segundo o sociólogo T. H. Marshall, desenvolveu-se em três dimensões: os **direitos civis** (liberdade, propriedade, igualdade perante a lei), os **direitos políticos** (votar e ser votado, participar do poder) e os **direitos sociais** (educação, saúde, trabalho, previdência). No Brasil, essa sequência foi diferente: os direitos sociais foram concedidos no Estado Novo, em um regime autoritário, antes dos políticos e dos civis plenos, que só foram garantidos de modo mais amplo com a Constituição de 1988. O historiador José Murilo de Carvalho analisa essa "inversão" para explicar a cidadania incompleta do país.',
    'A Constituição criou instrumentos de **participação direta**, como o plebiscito, o referendo e a iniciativa popular de leis, além de conselhos e conferências de políticas públicas, em áreas como saúde e educação. Também fortaleceu o **Ministério Público** e a **Defensoria Pública**, que atuam na defesa de direitos coletivos e dos mais pobres. A liberdade de imprensa, a atuação de ONGs e dos movimentos sociais (como o MST, os movimentos negro, feminista e indígena, e o dos trabalhadores) ampliaram o espaço público, mas o acesso desigual à justiça e à informação ainda limita a efetivação dos direitos.',
    'A memória do período autoritário também faz parte da vida democrática. A **Comissão Nacional da Verdade** (2011 a 2014) investigou violações de direitos humanos cometidas entre 1946 e 1988, principalmente na ditadura, e recomendou a responsabilização e o reconhecimento das vítimas. O debate sobre a **Lei da Anistia**, sobre a abertura dos arquivos e sobre os lugares de memória mostra que conhecer o passado é uma condição para impedir que ele se repita. Para o ENEM, vale lembrar que a democracia é um processo, e que o exercício da cidadania inclui a participação, a fiscalização e a defesa dos direitos de todos.'
  ]});
  nr.txt.push(ult);
}
