/* História: textos corridos, temas 22 a 25 */
module.exports = [
{ t:'Guerra Fria', txt:[
 { h:'O mundo bipolar e as origens da Guerra Fria', p:[
  'A **Guerra Fria** (1947 a 1991) foi o período de rivalidade política, econômica, ideológica e militar entre os **Estados Unidos** e a **União Soviética**, as duas superpotências que saíram da Segunda Guerra Mundial. Foi chamada de "fria" porque nunca houve um confronto direto entre as duas, que tinham armas nucleares e sabiam que uma guerra aberta seria devastadora. O mundo ficou **bipolar**, dividido em dois blocos: o **capitalista**, liderado pelos EUA, com democracia liberal e economia de mercado, e o **socialista**, liderado pela URSS, com partido único e economia planificada.',
  'As origens do conflito estão na desconfiança mútua. Os EUA e os países ocidentais temiam a expansão do comunismo, e a URSS temia o cerco capitalista e queria garantir uma zona de proteção na Europa Oriental, onde instalou governos aliados, a chamada "**Cortina de Ferro**", expressão de Winston Churchill. Em 1947, o presidente Truman anunciou a **Doutrina Truman**, que prometia apoio a países ameaçados pelo comunismo, na política de **contenção**. O **Plano Marshall** (1947) ofereceu ajuda econômica à reconstrução da Europa Ocidental, o que também ampliava a influência americana e reduzia o risco de o comunismo avançar.',
  'A URSS respondeu com o **Kominform** e o **Comecon**, de cooperação econômica entre os países socialistas, e, em 1955, com o **Pacto de Varsóvia**, aliança militar oposta à **OTAN** (Organização do Tratado do Atlântico Norte, 1949), liderada pelos EUA. A **Alemanha**, dividida em zonas de ocupação, foi separada em República Federal da Alemanha (Ocidental) e República Democrática Alemã (Oriental), e Berlim, dentro da zona soviética, também foi dividida. Em 1961, foi construído o **Muro de Berlim**, para impedir a fuga de alemães orientais para o Ocidente, símbolo da divisão do mundo.'] },
 { h:'Crises e conflitos indiretos', p:[
  'Como as superpotências evitavam o confronto direto, a disputa se deu por meio de **conflitos indiretos**, em que cada uma apoiava um lado em guerras regionais. Na **Revolução Chinesa** (1949), os comunistas de Mao Tsé-Tung venceram e fundaram a República Popular da China. Na **Guerra da Coreia** (1950 a 1953), o país foi dividido no paralelo 38, entre a Coreia do Norte, apoiada por URSS e China, e a Coreia do Sul, apoiada pelos EUA. Na **Guerra do Vietnã** (1955 a 1975), os Estados Unidos intervieram para impedir a vitória comunista, mas, apesar de seu poder, foram derrotados pelas forças do Vietnã do Norte e pelos guerrilheiros vietcongues, e se retiraram em 1973.',
  'A **Revolução Cubana** (1959), liderada por Fidel Castro, derrubou o ditador Fulgencio Batista e levou Cuba ao socialismo, a poucos quilômetros dos EUA. Em 1961, a invasão da **Baía dos Porcos**, tentativa americana de derrubar Fidel, fracassou. Em 1962, a descoberta de mísseis soviéticos instalados em Cuba provocou a **Crise dos Mísseis**, o momento de maior risco de guerra nuclear: os EUA impuseram um bloqueio naval, e, depois de dias de tensão, a URSS retirou os mísseis, em troca da promessa americana de não invadir a ilha e de retirar seus mísseis da Turquia. O episódio levou à criação de uma linha direta entre Washington e Moscou.',
  'A disputa também envolveu a **corrida armamentista**, com o desenvolvimento de armas nucleares e de mísseis, e a **corrida espacial**, em que a URSS lançou o satélite Sputnik (1957) e enviou o primeiro homem ao espaço, Yuri Gagarin (1961), e os EUA levaram os astronautas à Lua, em 1969 (Apollo 11). Houve ainda a **propaganda**, a espionagem (CIA e KGB), o esporte (boicotes às Olimpíadas) e a cultura, com a exaltação dos modelos de vida de cada bloco. O **macarthismo**, nos EUA, perseguiu pessoas acusadas de simpatizar com o comunismo, em uma "caça às bruxas".'] },
 { h:'A Guerra Fria na América Latina e no Brasil', p:[
  'Na América Latina, a Guerra Fria teve forte impacto. Os Estados Unidos, que consideravam a região sua esfera de influência (Doutrina Monroe), combateram a possibilidade de novos governos de esquerda após a Revolução Cubana. Criaram a **Aliança para o Progresso** (1961), um programa de ajuda econômica para reduzir o risco de revoluções, e apoiaram **golpes militares** e ditaduras anticomunistas, como o do Brasil (1964), da Argentina (1966 e 1976), do Chile (1973, contra o presidente socialista Salvador Allende) e do Uruguai. Esses regimes adotaram a **Doutrina de Segurança Nacional** e a repressão aos opositores. A **Operação Condor** foi uma aliança entre as ditaduras do Cone Sul, para perseguir opositores.',
  'No Brasil, a Guerra Fria influenciou a política interna. O governo Dutra rompeu com a URSS e colocou o Partido Comunista na ilegalidade; o governo de Juscelino Kubitschek abriu a economia ao capital estrangeiro, e a **política externa independente** de Jânio e de Jango, que aproximava o Brasil de países socialistas e criticava o isolamento de Cuba, desagradou aos conservadores. O medo do comunismo foi um dos argumentos do golpe de 1964, que contou com o apoio dos EUA. Durante a ditadura, o anticomunismo justificou a perseguição aos opositores, considerados "inimigos internos".',
  'Em outras regiões, o conflito também teve efeitos: o Oriente Médio, com a disputa por petróleo e o apoio dos blocos a Israel (EUA) e aos países árabes (URSS); a África, em que a descolonização foi marcada pela rivalidade, como em Angola e no Congo; e o Afeganistão, onde a URSS invadiu em 1979, enfrentando uma guerrilha apoiada pelos EUA, em uma guerra longa e desgastante, que foi chamada de "Vietnã soviético". Na Europa, houve revoltas contra o domínio soviético, como na Hungria (1956) e na Tchecoslováquia (Primavera de Praga, 1968), reprimidas pelo Exército Vermelho.'] },
 { h:'Distensão, Terceiro Mundo e o fim da Guerra Fria', p:[
  'A partir da década de 1960, houve períodos de **distensão** (détente), com acordos de limitação de armas nucleares (SALT) e de aproximação, como a visita de Nixon à China, em 1972. Também surgiu o **Movimento dos Países Não Alinhados**, a partir da Conferência de Bandung (1955), que reuniu países da Ásia e da África recém-independentes, que buscavam uma posição independente das superpotências, o chamado **Terceiro Mundo**. A China rompeu com a URSS nos anos 1960, e a França, de De Gaulle, adotou uma política autônoma. Mesmo assim, a corrida armamentista continuou, e voltou a se intensificar nos anos 1980, com o presidente americano Ronald Reagan.',
  'A União Soviética entrou em crise econômica e política. A economia planificada sofria com a ineficiência, a burocracia, a baixa produtividade e os gastos militares, e a guerra do Afeganistão desgastou o país. Em 1985, **Mikhail Gorbachev** assumiu o poder e lançou reformas: a **Perestroika** (reestruturação econômica) e a **Glasnost** (transparência política), que abriram o regime ao debate, mas acabaram acelerando a crise. Em 1989, uma onda de revoluções pacíficas derrubou os regimes comunistas da Europa Oriental, e o **Muro de Berlim** caiu, em **9 de novembro de 1989**, o que levou à reunificação alemã, em 1990.',
  'Em 1991, após uma tentativa de golpe contra Gorbachev e a declaração de independência de várias repúblicas, a **União Soviética foi dissolvida**, e deu lugar à Comunidade de Estados Independentes e à Rússia, sob a presidência de Boris Ieltsin. O fim da Guerra Fria deixou os Estados Unidos como única superpotência, e o mundo passou a ser chamado de **unipolar**, ou multipolar, a depender do ponto de vista, com a ascensão de outros polos, como a União Europeia e a China. O socialismo real desapareceu em quase todos os países, e a China, Cuba, Vietnã e Coreia do Norte permaneceram, com diferenças entre eles.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a Guerra Fria aparece em questões sobre a bipolarização, a corrida armamentista e espacial, as crises (Berlim, Cuba) e os conflitos indiretos (Coreia, Vietnã, Afeganistão), os golpes na América Latina, a propaganda e o macarthismo, a queda do Muro de Berlim e a dissolução da URSS. Os enunciados trazem charges, cartazes de propaganda, fotografias do Muro e trechos de discursos e de tratados, e pedem a identificação de ideias e de posições de cada bloco, com a leitura crítica das fontes.',
  'Pontos de atenção: a Guerra Fria foi "fria" porque não houve confronto direto entre EUA e URSS; a contenção (Doutrina Truman e Plano Marshall) e a OTAN representaram o bloco capitalista, e o Comecon e o Pacto de Varsóvia, o socialista; os conflitos ocorreram em outros países; a Crise dos Mísseis foi o ponto mais crítico; a ditadura brasileira se inseriu na lógica do anticomunismo; e a Perestroika e a Glasnost antecederam o fim da URSS. Cuidado com leituras simplistas: o mundo não era dividido em apenas dois lados, e os Não Alinhados buscavam uma terceira via.',
  'Para revisar, esquematize: 1945 (fim da guerra) → 1947 (Truman e Marshall) → 1949 (OTAN, China comunista) → 1950 a 1953 (Coreia) → 1955 (Pacto de Varsóvia, Bandung) → 1959 (Cuba) → 1961 (Muro) → 1962 (mísseis) → 1975 (Vietnã) → 1979 (Afeganistão) → 1985 (Gorbachev) → 1989 (queda do Muro) → 1991 (fim da URSS). Esse tema se liga ao seguinte, a descolonização da África e da Ásia, que ocorreu em paralelo e foi marcada pela disputa de influência entre os dois blocos.'] }
]},
{ t:'Descolonização da África e da Ásia', txt:[
 { h:'O imperialismo e o colonialismo do século XIX', p:[
  'Para entender a descolonização, é preciso lembrar como a África e a Ásia foram colonizadas. No século XIX, as potências industriais europeias, em especial Inglaterra, França, Alemanha, Bélgica e Itália, buscavam matérias-primas, mercados consumidores e áreas para investir capitais. Esse processo, chamado de **imperialismo** (ou neocolonialismo), foi justificado por ideias de superioridade racial e por uma suposta "**missão civilizadora**", que apresentava a dominação como um benefício para os povos dominados. Na Conferência de Berlim (1884 e 1885), as potências estabeleceram regras para a partilha da África, sem consultar os povos africanos.',
  'As fronteiras traçadas pelos europeus ignoraram as **identidades étnicas, culturais e linguísticas** locais, agrupando povos diferentes, ou dividindo povos semelhantes, o que gerou tensões que duram até hoje. A economia colonial foi organizada em função da metrópole: produção de matérias-primas e de produtos agrícolas de exportação (borracha, algodão, cacau, minerais, petróleo), com mão de obra barata e muitas vezes forçada, e importação de manufaturados. Isso deixou as colônias dependentes e sem diversificação, o que afetou o desenvolvimento posterior. Na Ásia, a Índia era a "joia da Coroa" britânica, e a China foi forçada a abrir os portos pelas Guerras do Ópio.',
  'A dominação colonial foi sustentada pela violência, por sistemas de segregação e pela imposição da língua, da religião e dos costumes dos colonizadores. Contudo, houve resistência desde o início, por meio de revoltas, de movimentos religiosos e de lideranças locais. Ao longo do século XX, as elites africanas e asiáticas educadas nas metrópoles passaram a usar as ideias de liberdade, de igualdade e de autodeterminação, que aprenderam com os europeus, contra o próprio colonialismo, formando movimentos **nacionalistas**, que seriam decisivos no processo de independência.'] },
 { h:'Os fatores da descolonização após 1945', p:[
  'A maior parte das independências ocorreu após a **Segunda Guerra Mundial**, nas décadas de 1940 a 1970. Vários fatores se combinaram. A guerra **enfraqueceu as metrópoles europeias**, economicamente e militarmente, e tornou difícil manter o controle das colônias. A **ONU** (1945) reconheceu, em sua Carta, o princípio da **autodeterminação dos povos**, dando legitimidade internacional às reivindicações. As duas superpotências, EUA e URSS, embora com interesses próprios, criticavam o colonialismo europeu, e cada uma buscava ampliar sua influência nos novos países, o que também pressionava as metrópoles.',
  'O crescimento dos **movimentos nacionalistas** foi fundamental, com lideranças e partidos que mobilizaram as populações. A participação de soldados coloniais na guerra, ao lado dos europeus, mostrou a contradição de lutar pela liberdade na Europa, enquanto os povos coloniais eram dominados. A **Conferência de Bandung** (Indonésia, 1955) reuniu 29 países da Ásia e da África, e condenou o colonialismo e o racismo, defendendo a cooperação e a neutralidade diante da Guerra Fria, e deu origem ao movimento dos **Países Não Alinhados** e à ideia de **Terceiro Mundo**.',
  'O processo teve formas diferentes. Em alguns lugares, a independência foi **pacífica**, por negociação, como em parte das colônias britânicas. Em outros, foi precedida de **guerras longas e violentas**, quando as metrópoles se recusaram a abrir mão do domínio, como na Indochina Francesa e na Argélia. A forma da transição teve consequências duradouras: nos casos de conflitos, as sociedades ficaram marcadas por divisões e por violência, e os novos Estados enfrentaram o desafio de construir uma identidade nacional e instituições, em condições econômicas frágeis.'] },
 { h:'A descolonização da Ásia e do Oriente Médio', p:[
  'Na **Ásia**, o processo começou logo após a guerra. A **Índia**, a maior colônia britânica, conquistou a independência em **1947**, por meio de uma luta liderada por **Mahatma Gandhi**, que defendia a **resistência não violenta** (satyagraha) e a desobediência civil, como na Marcha do Sal, e por Jawaharlal Nehru. Por causa dos conflitos religiosos entre hindus e muçulmanos, o território foi dividido na **Índia** (hindu) e no **Paquistão** (muçulmano, que depois se separou, dando origem a Bangladesh), o que provocou migrações em massa e violência. Gandhi foi assassinado em 1948 por um extremista hindu.',
  'Na **Indochina**, o movimento liderado por **Ho Chi Minh** proclamou a independência do Vietnã, em 1945, e a França tentou retomar o controle, o que levou à guerra, e à derrota francesa na batalha de **Dien Bien Phu** (1954). O país foi dividido em Vietnã do Norte (comunista) e do Sul (apoiado pelos EUA), e o conflito levou à Guerra do Vietnã. A **Indonésia**, colônia holandesa, tornou-se independente em 1949, e as Filipinas, em 1946. Na **China**, a revolução comunista de 1949 criou um novo Estado, sem passar pela colonização formal, mas após um século de dominação estrangeira, e tornou-se uma referência para outros movimentos.',
  'No **Oriente Médio**, o desmembramento do Império Otomano após a Primeira Guerra deu origem a territórios sob mandato britânico e francês. A região da **Palestina**, sob mandato britânico, foi alvo de disputa entre judeus e árabes. Em 1947, a ONU aprovou o plano de **partilha**, e em 1948 foi criado o **Estado de Israel**, o que levou à guerra com os países árabes vizinhos e ao deslocamento de centenas de milhares de palestinos, os refugiados. O conflito árabe-israelense, que continua até hoje, está entre os mais prolongados, e é um tema frequente nas provas, que pedem uma abordagem equilibrada.'] },
 { h:'A descolonização da África e os desafios dos novos Estados', p:[
  'Na **África**, a descolonização ocorreu principalmente nas décadas de 1950 e 1960, e 1960 ficou conhecido como o "Ano da África", quando 17 países se tornaram independentes. Em Gana (1957), liderada por **Kwame Nkrumah**, a independência foi pacífica e inspirou outras. Na **Argélia**, os franceses resistiram, e a **Guerra da Argélia** (1954 a 1962), com a atuação da Frente de Libertação Nacional, foi marcada por violência, torturas e centenas de milhares de mortos, até a independência, em 1962. No **Quênia**, a rebelião Mau Mau foi duramente reprimida pelos britânicos. No **Congo Belga**, a independência (1960) foi seguida de crise, com a deposição e o assassinato de Patrice Lumumba.',
  'As colônias portuguesas, **Angola**, **Moçambique** e **Guiné-Bissau**, só conseguiram a independência em 1974 e 1975, após longas guerras de libertação e a **Revolução dos Cravos** em Portugal, que derrubou a ditadura e pôs fim à guerra colonial. Em Angola, houve uma guerra civil que durou décadas, com a interferência da Guerra Fria. Na **África do Sul**, o regime do **apartheid**, de segregação racial institucionalizada, manteve a minoria branca no poder até 1994, quando **Nelson Mandela**, preso por 27 anos, foi eleito presidente nas primeiras eleições multirraciais, simbolizando a luta contra o racismo.',
  'Os novos países enfrentaram muitos **desafios**: fronteiras artificiais e conflitos étnicos, economias dependentes da exportação de matérias-primas, pobreza, dívida externa, instabilidade política, golpes e ditaduras, pouca infraestrutura e carência de serviços básicos. O **neocolonialismo**, ou seja, a manutenção da dependência econômica e política em relação às antigas metrópoles e às grandes potências e empresas multinacionais, é um conceito frequentemente usado para explicar essas dificuldades. Ainda assim, a independência significou um grande avanço para a autodeterminação, e a cultura e a identidade africanas e asiáticas ganharam novo protagonismo.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a descolonização aparece em questões sobre o imperialismo e o neocolonialismo, as consequências das fronteiras traçadas pelos europeus, os conflitos étnicos, as lutas de libertação (Índia, Argélia, Angola, Moçambique), o apartheid e Mandela, a Conferência de Bandung e a relação com a Guerra Fria. Os enunciados incluem mapas da partilha da África, trechos de discursos de líderes, como Gandhi, Nkrumah e Mandela, e imagens, e pedem a relação entre o passado colonial e os problemas atuais.',
  'Pontos de atenção: o processo se intensificou após a Segunda Guerra, pela fragilidade das metrópoles e pela pressão internacional; algumas independências foram pacíficas e outras, violentas; a Índia foi dividida por razões religiosas; os países africanos herdaram fronteiras artificiais; a Guerra Fria interferiu em vários conflitos; e o fim do apartheid foi um marco. Evite a ideia de que a independência política significou, automaticamente, a autonomia econômica, pois a dependência se manteve em novas formas.',
  'Para revisar, monte um quadro: região, país, data aproximada, forma da independência e desafios. Por exemplo: Índia (1947, não violência, divisão), Indonésia (1949), Vietnã (1954, guerra), Gana (1957, pacífica), Argélia (1962, guerra), Angola e Moçambique (1975, guerra e Revolução dos Cravos), África do Sul (1994, fim do apartheid). Relacione com o tema anterior (Guerra Fria) e o seguinte (movimentos sociais e direitos no século XX), em que a luta por igualdade e por direitos se expressa em várias frentes.'] }
]},
{ t:'Movimentos sociais e direitos no século XX', txt:[
 { h:'Os direitos humanos e o contexto do pós-guerra', p:[
  'O século XX foi marcado por guerras e genocídios, mas também por grandes conquistas de direitos. Após as atrocidades da Segunda Guerra, a **ONU** aprovou, em 1948, a **Declaração Universal dos Direitos Humanos**, que afirma que todos os seres humanos nascem livres e iguais em dignidade e direitos, e estabelece direitos civis, políticos, econômicos, sociais e culturais. Embora não tenha força de lei, a Declaração se tornou uma referência para constituições e tratados, e inspirou a luta de movimentos sociais em todo o mundo. Outros documentos, como as convenções sobre racismo, mulheres e crianças, ampliaram essa proteção.',
  'A ideia de direitos foi disputada. No contexto da Guerra Fria, o bloco capitalista destacava as liberdades civis e políticas, enquanto o socialista enfatizava os direitos econômicos e sociais. Essa polarização limitou, por vezes, a aplicação dos princípios, pois ambos os lados cometeram violações. Mesmo assim, a pressão da sociedade civil, de organizações como a Anistia Internacional (1961) e das lutas por independência e por igualdade dentro de cada país produziu avanços. A noção de que os direitos são **universais**, **indivisíveis** e **interdependentes** foi se consolidando.',
  'O desenvolvimento da cidadania passou por etapas, descritas por T. H. Marshall: os direitos **civis** (liberdades individuais, no século XVIII), os **políticos** (participação no poder, no século XIX) e os **sociais** (educação, saúde, trabalho, no século XX). Nesse último, o **Estado de bem-estar social** na Europa foi um marco. Cada conquista resultou de lutas coletivas, de greves, passeatas, campanhas e mobilizações, e não de concessões espontâneas, o que mostra o papel dos movimentos sociais na ampliação da democracia e da cidadania.'] },
 { h:'O movimento feminista e a luta por direitos das mulheres', p:[
  'A luta das mulheres por direitos, o **feminismo**, tem uma longa história. No final do século XIX e início do XX, o movimento das **sufragistas**, na Inglaterra e nos Estados Unidos, reivindicou o **direito ao voto feminino**, com manifestações, greves de fome e prisões. A Nova Zelândia foi o primeiro país a conceder o voto às mulheres, em 1893, e o direito se estendeu, ao longo do século XX, para a maioria dos países. No Brasil, o voto feminino foi conquistado em **1932**, com o Código Eleitoral de Vargas, graças à luta de Bertha Lutz e de outras ativistas, e confirmado na Constituição de 1934.',
  'Nas décadas de 1960 e 1970, a chamada **segunda onda** do feminismo ampliou as reivindicações para a igualdade no trabalho, nos salários, na educação e na vida familiar, e para o controle do próprio corpo. Simone de Beauvoir, em O Segundo Sexo (1949), afirmou que "não se nasce mulher, torna-se mulher", discutindo o papel do social na construção do gênero. A **pílula anticoncepcional**, disponível a partir de 1960, mudou a vida das mulheres, ao permitir o planejamento familiar. A participação feminina no mercado de trabalho cresceu, com a Segunda Guerra, e depois, com a urbanização e a industrialização.',
  'As mulheres ainda enfrentam desigualdades: diferenças salariais, dupla jornada, sub-representação na política e violência. No Brasil, conquistas importantes incluem a **Lei Maria da Penha** (2006), que combate a violência doméstica, e a **Lei do Feminicídio** (2015). O feminismo se diversificou, e inclui o **feminismo negro**, que destaca a interseção entre gênero e raça, o feminismo comunitário e outras vertentes. Esse conjunto de lutas é um tema recorrente no ENEM, tanto em História quanto em Sociologia e em redação, em que se pede a discussão de desafios atuais.'] },
 { h:'A luta contra o racismo e os movimentos de direitos civis', p:[
  'A luta contra o **racismo** foi um dos grandes movimentos do século XX. Nos **Estados Unidos**, a segregação racial, legalizada nos estados do Sul pelas leis "Jim Crow", separava brancos e negros em escolas, transportes e espaços públicos. O **Movimento pelos Direitos Civis** (décadas de 1950 e 1960) reuniu manifestações, boicotes e marchas, como o boicote aos ônibus de Montgomery (1955), iniciado após a prisão de **Rosa Parks**, e a Marcha sobre Washington (1963), onde **Martin Luther King Jr.** fez o discurso "Eu tenho um sonho". Defendendo a não violência, King foi assassinado em 1968. As leis de 1964 e 1965 proibiram a discriminação e garantiram o direito de voto.',
  'Ao lado da luta não violenta, surgiram movimentos de afirmação da identidade e do poder negro, como o dos **Panteras Negras** e de **Malcolm X**, que defendiam a autodefesa e a valorização da cultura negra, com o lema "Black is beautiful". Na **África do Sul**, o regime do **apartheid** (1948 a 1994) institucionalizou a segregação, e a resistência, liderada pelo Congresso Nacional Africano e por Nelson Mandela, recebeu apoio internacional, por meio de boicotes e sanções. O fim do apartheid, em 1994, foi uma vitória simbólica da luta contra o racismo, com a eleição de Mandela.',
  'No **Brasil**, o movimento negro, com raízes na resistência à escravidão, organizou-se de várias formas no século XX: a Frente Negra Brasileira (1931), o Teatro Experimental do Negro (1944), de Abdias do Nascimento, e o Movimento Negro Unificado (1978), que denunciou o mito da democracia racial e reivindicou direitos. As conquistas incluíram a Lei Afonso Arinos (1951), a criminalização do racismo na Constituição de 1988, as leis de ensino de história afro-brasileira (2003) e as cotas raciais (2012). O combate ao racismo, no entanto, continua sendo um desafio, pois as desigualdades de renda, de violência e de acesso a direitos persistem.'] },
 { h:'Outros movimentos: juventude, contracultura, ambientalismo e povos indígenas', p:[
  'Nos anos 1960, a **juventude** se destacou como força social. A **contracultura** questionou os valores tradicionais, a sociedade de consumo, a guerra do Vietnã e o autoritarismo, com o movimento **hippie** ("paz e amor"), a música (rock, Woodstock), o cinema e a literatura. Em **maio de 1968**, os estudantes franceses, junto com os trabalhadores, protagonizaram uma grande onda de protestos, e movimentos semelhantes ocorreram nos EUA, no México, no Brasil e em outros países. Eles reivindicavam liberdade, reformas educacionais e questionavam a ordem estabelecida, deixando uma marca duradoura nos costumes, nas artes e na política.',
  'O **movimento ambientalista** ganhou força a partir dos anos 1960 e 1970, com o livro Primavera Silenciosa (Rachel Carson, 1962), a primeira Conferência da ONU sobre o Meio Ambiente (Estocolmo, 1972) e a criação de organizações como o Greenpeace. Desde então, a preocupação com a poluição, o desmatamento e as mudanças climáticas levou a acordos internacionais, como a Rio-92, o Protocolo de Kyoto e o Acordo de Paris. No Brasil, o líder seringueiro **Chico Mendes**, assassinado em 1988, tornou-se símbolo da luta pela floresta e pelas populações tradicionais.',
  'Os **movimentos indígenas**, os **LGBTQIA+** e outros também ganharam destaque, a partir da segunda metade do século XX. A **Revolta de Stonewall** (1969), em Nova York, é considerada um marco do movimento LGBTQIA+, que luta contra a discriminação e pelo reconhecimento de direitos. No Brasil, a Constituição de 1988 reconheceu os direitos territoriais dos indígenas, graças à mobilização desses povos. Os movimentos sociais rurais, como o **MST** (Movimento dos Trabalhadores Rurais Sem Terra, 1984), lutam pela reforma agrária. Em comum, esses movimentos mostram que a ampliação de direitos é um processo contínuo e disputado.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM dá grande destaque a esse tema, que une História, Sociologia e atualidades. As questões apresentam trechos de documentos (Declaração Universal dos Direitos Humanos, discursos de Martin Luther King e de Mandela), imagens de manifestações, cartazes e charges, e pedem a identificação do movimento, de suas reivindicações e de suas formas de luta, ou a relação entre as conquistas do passado e os desafios do presente, como a desigualdade de gênero, o racismo e a proteção ambiental.',
  'Pontos de atenção: os direitos foram conquistados por meio de lutas, e não concedidos; a não violência foi uma estratégia importante (Gandhi, King), mas houve outras formas de luta; o voto feminino no Brasil data de 1932; o apartheid vigorou na África do Sul até 1994; o movimento de 1968 foi global; e o ambientalismo e as lutas dos povos tradicionais se articulam. Ao analisar uma questão, pergunte-se: qual é o grupo, qual é o direito reivindicado, e qual é a resistência enfrentada? Essa abordagem ajuda a organizar a resposta.',
  'Para revisar, faça um quadro: movimento, período, lideranças, reivindicações e conquistas. Inclua o sufragismo e o feminismo, o movimento pelos direitos civis, o fim do apartheid, a contracultura e 1968, o ambientalismo e os movimentos indígenas, LGBTQIA+ e do campo. Esse quadro, além de revisar a História, serve de repertório sociocultural para a redação, que costuma exigir argumentos com base em fatos históricos. O próximo tema, o mundo contemporâneo, completa o estudo com a globalização e os desafios atuais.'] }
]},
{ t:'Mundo contemporâneo', txt:[
 { h:'A nova ordem mundial e a globalização', p:[
  'Com o fim da Guerra Fria, em 1991, o mundo passou por uma transformação na ordem internacional. Os Estados Unidos ficaram como a única superpotência militar, em um mundo chamado, por alguns, de **unipolar**, mas surgiram novos polos de poder, econômicos e políticos, e a ordem foi se tornando **multipolar**: a **União Europeia**, a **China**, o **Japão**, a **Rússia**, a **Índia** e os blocos regionais. Os conflitos deixaram de ser, principalmente, ideológicos, e passaram a ser motivados por disputas étnicas, religiosas, territoriais e econômicas, como nos Bálcãs (guerra da Iugoslávia, nos anos 1990) e em Ruanda (genocídio de 1994).',
  'A **globalização** é o processo de integração cada vez maior das economias, das sociedades e das culturas, em escala mundial, impulsionado pelos avanços nos **transportes** e nas **comunicações**, pela expansão do **capitalismo** e pela abertura dos mercados. Seus elementos são a circulação de capitais, de mercadorias, de informações e de pessoas, a atuação das **empresas multinacionais**, a fragmentação da produção em várias partes do mundo, e a influência dos meios de comunicação. A **internet**, popularizada nos anos 1990, tornou-se o principal vetor dessa integração, e transformou o trabalho, o consumo, a política e as relações pessoais.',
  'A globalização é vista de modo ambíguo. Seus defensores destacam o aumento do comércio, da produtividade, do acesso à informação e à tecnologia, e a redução da pobreza em alguns países. Seus críticos apontam a **concentração de riqueza**, a desigualdade entre países e dentro deles, a precarização do trabalho, a perda de soberania dos Estados, a **homogeneização cultural** e os impactos ambientais. Os países ricos controlam as finanças, a tecnologia e as regras, e os pobres tendem a ficar com o papel de fornecedores de matérias-primas e de mão de obra barata. Esses debates são constantes no ENEM.'] },
 { h:'Neoliberalismo, crises econômicas e as potências emergentes', p:[
  'Desde os anos 1980, predominou o **neoliberalismo**, política econômica que defende a redução do papel do Estado na economia, as **privatizações**, a abertura comercial, a desregulamentação dos mercados e a flexibilização das leis trabalhistas. Foi implementado por governos como os de Reagan, nos EUA, e Thatcher, na Inglaterra, e difundido por organismos como o FMI e o Banco Mundial, por meio do chamado **Consenso de Washington** (1989), um conjunto de recomendações para os países em desenvolvimento. O modelo trouxe crescimento em alguns casos, mas também desemprego, desigualdade e vulnerabilidade a crises financeiras.',
  'A integração dos mercados financeiros tornou as crises mais rápidas e mais amplas. A crise asiática (1997), a crise russa (1998), a Argentina (2001) e, sobretudo, a **crise financeira de 2008**, iniciada nos Estados Unidos com a bolha imobiliária (hipotecas subprime) e a falência do banco Lehman Brothers, espalharam-se pelo mundo, causando recessão, desemprego e dívidas públicas, especialmente na Europa. Os governos socorreram os bancos, e a resposta gerou protestos, como o Occupy Wall Street. A crise reabriu o debate sobre a regulação do sistema financeiro e sobre os limites do neoliberalismo.',
  'No cenário econômico, destaca-se a ascensão das **potências emergentes**, em particular os **BRICS** (Brasil, Rússia, Índia, China e África do Sul). A **China**, que desde 1978 combinou o controle político do Partido Comunista com a abertura econômica, tornou-se a segunda maior economia do mundo e a "fábrica do mundo", e disputa influência com os EUA, em um novo contexto de rivalidade, tecnológica e comercial. A Índia também cresce, e o eixo econômico se desloca do Atlântico para o Pacífico e a Ásia, mudando o mapa do poder mundial e as relações comerciais.'] },
 { h:'Conflitos, terrorismo, migrações e refugiados', p:[
  'O século XXI foi marcado por novos desafios de segurança. Os **atentados de 11 de setembro de 2001** contra as Torres Gêmeas, em Nova York, e o Pentágono, realizados pela organização Al-Qaeda, levaram os EUA a declarar uma "guerra ao terror": invadiram o **Afeganistão** (2001) e o **Iraque** (2003). A intervenção no Iraque, justificada pela alegação de que o país tinha armas de destruição em massa, que não foram encontradas, foi muito criticada. As guerras trouxeram instabilidade ao Oriente Médio, e favoreceram o surgimento de grupos extremistas, como o Estado Islâmico. O **terrorismo** passou a ser um problema global.',
  'A **Primavera Árabe** (a partir de 2010), onda de protestos contra governos autoritários no mundo árabe, derrubou regimes na Tunísia e no Egito, e provocou guerras civis, como na **Síria** (desde 2011) e na Líbia. A guerra na Síria gerou uma das maiores crises humanitárias, com milhões de **refugiados**. Há ainda o conflito **israelo-palestino**, a guerra no **Iêmen**, as tensões na **Coreia do Norte** e, mais recentemente, a **guerra da Rússia contra a Ucrânia** (iniciada em 2022), que reacendeu o temor de uma confrontação entre grandes potências e afetou os preços da energia e de alimentos.',
  'As **migrações internacionais** cresceram, motivadas pela busca de trabalho, pela fuga de guerras, de perseguições e de desastres ambientais. Os refugiados, na Europa e em outras regiões, enfrentam travessias perigosas e, muitas vezes, hostilidade, o que fortaleceu discursos **xenófobos** e movimentos nacionalistas e de extrema direita em vários países. O **Brexit** (a saída do Reino Unido da União Europeia, em 2016 a 2020) é um exemplo da tensão entre a integração e a soberania nacional. O Brasil recebeu muitos imigrantes, como haitianos e venezuelanos, e a **Lei de Migração** (2017) busca assegurar seus direitos.'] },
 { h:'Tecnologia, meio ambiente e desafios do presente', p:[
  'A **revolução tecnológica** contemporânea, com a internet, os smartphones, as redes sociais, a inteligência artificial e a automação, alterou o trabalho, a comunicação e a política. Trouxe benefícios, como o acesso a informações e a novas formas de participação, mas também riscos: a disseminação de **notícias falsas** (fake news), a manipulação de dados e a vigilância, a **polarização política**, os discursos de ódio e a dependência de grandes empresas de tecnologia. A chamada **Quarta Revolução Industrial** levanta dúvidas sobre o futuro do emprego e exige novas competências, além de regulamentações sobre dados e privacidade, como a Lei Geral de Proteção de Dados (LGPD) no Brasil.',
  'A questão **ambiental** tornou-se central. As **mudanças climáticas**, causadas principalmente pelas emissões de gases de efeito estufa, ameaçam ecossistemas e populações, e levaram a acordos internacionais, como o **Acordo de Paris** (2015), em que os países se comprometeram a limitar o aquecimento global. A **pandemia de covid-19** (2020 a 2022) mostrou a interdependência global, a importância da ciência e dos sistemas de saúde e as desigualdades no acesso a vacinas, e teve profundos efeitos econômicos e sociais. Também evidenciou o papel das informações falsas e da confiança nas instituições.',
  'Persistem a **desigualdade** e a **pobreza**, com a concentração de riqueza em poucas mãos, e os desafios de promover o **desenvolvimento sustentável**, como definem os **Objetivos de Desenvolvimento Sustentável** (ODS) da ONU, a Agenda 2030, que inclui erradicar a pobreza, promover a saúde, a educação, a igualdade de gênero e a ação climática. Os direitos humanos, a democracia e a defesa do multilateralismo enfrentam pressões em várias regiões. Para o estudante, compreender esse cenário é essencial para analisar notícias, formar opinião e construir argumentos, em especial na redação, que costuma abordar temas contemporâneos.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O mundo contemporâneo está sempre presente no ENEM, por meio de textos jornalísticos, gráficos e charges sobre globalização, neoliberalismo, terrorismo, refugiados, desigualdade, avanço da tecnologia, mudanças climáticas e conflitos internacionais. As questões pedem para interpretar a notícia à luz de conceitos aprendidos: soberania, globalização, multipolaridade, direitos humanos, xenofobia e desenvolvimento sustentável. Mesmo sem exigir datas, elas cobram a compreensão dos processos e das conexões entre economia, política e cultura.',
  'Pontos de atenção: a globalização é multidimensional (econômica, cultural e tecnológica) e produz efeitos desiguais; o neoliberalismo propõe menos Estado e mais mercado; a crise de 2008 revelou riscos da integração financeira; o terrorismo e os conflitos no Oriente Médio têm causas históricas complexas, e não podem ser reduzidos a explicações religiosas; os refugiados são pessoas protegidas por tratados internacionais; e a tecnologia traz oportunidades e riscos. Desconfie de respostas generalizantes e de visões simplistas, e procure a que considera vários fatores.',
  'Para revisar, monte um painel com cinco eixos: ordem mundial (unipolar e multipolar), economia (globalização, neoliberalismo, crises, emergentes), conflitos (terrorismo, guerras, migrações), tecnologia (internet, redes, inteligência artificial) e meio ambiente (clima, sustentabilidade, ODS). Acompanhe as notícias e relacione-as a esses eixos. Com esse tema, você conclui o estudo de História, que passa do mundo antigo à realidade atual: a boa compreensão dos processos históricos ajuda a entender o presente, e é o que as questões de Ciências Humanas esperam que você faça.'] }
]}
];
