/* História: textos corridos, temas 13 a 15 */
module.exports = [
{ t:'Abolição e pós-abolição', txt:[
 { h:'A escravidão no Brasil e a resistência dos escravizados', p:[
  'O Brasil foi o país que mais recebeu africanos escravizados nas Américas, estimando-se cerca de 4 milhões de pessoas, trazidas entre os séculos XVI e XIX, e foi o último país do continente a abolir a escravidão, em 1888. A escravidão estruturou a economia, a sociedade e a cultura brasileiras, sustentando as lavouras de cana, a mineração, o café e os serviços urbanos. As pessoas escravizadas eram tratadas como propriedade, sem direitos, submetidas a trabalho extenuante, castigos físicos e à separação de suas famílias, e a violência era um instrumento de controle.',
  'Os escravizados **resistiram** de muitas maneiras. Houve resistências cotidianas, como a lentidão no trabalho, a quebra de ferramentas, a manutenção de religiões e costumes africanos e a formação de laços familiares. Houve **fugas** e a formação de **quilombos**, comunidades de pessoas que escaparam, como o Quilombo dos Palmares, liderado por Zumbi. Houve **revoltas**, como a dos Malês, em Salvador, em 1835, e **negociações**, como a compra da **alforria**, a carta de liberdade, por meio de pecúlio acumulado. Também recorreram à Justiça, em ações de liberdade, em especial nas décadas finais.',
  'Não se pode, assim, descrever os escravizados como vítimas passivas. Eles foram sujeitos históricos, que lutaram e construíram espaços de autonomia, e deixaram contribuições fundamentais à cultura brasileira, na música, na religião, na culinária, na língua e nas técnicas de trabalho. Ao mesmo tempo, é preciso reconhecer a dimensão estrutural da violência escravista, que gerou desigualdades profundas e duradouras, e que continua a ter efeitos sobre as condições de vida da população negra no Brasil contemporâneo, como o ENEM frequentemente discute.'] },
 { h:'O processo gradual de abolição', p:[
  'A abolição foi um processo longo, resultado da combinação da pressão externa, da luta dos escravizados e dos abolicionistas e de mudanças econômicas. A Inglaterra, que buscava ampliar mercados de consumo, pressionou pelo fim do tráfico. Em 1850, a **Lei Eusébio de Queirós** proibiu o tráfico atlântico, embora o tráfico interno e o contrabando continuassem. Com o fim do tráfico, o preço dos escravizados subiu, e muitos foram vendidos do Nordeste para as lavouras cafeeiras do Sudeste, o que reforçou a concentração da escravidão nas áreas mais ricas e a busca por alternativas de mão de obra.',
  'Leis gradualistas foram aprovadas para suavizar a transição, sem romper com os interesses dos proprietários. A **Lei do Ventre Livre** (1871) declarou livres os filhos de escravas nascidos a partir daquela data, mas os manteve sob tutela do senhor até os 8 ou 21 anos, o que na prática perpetuava a exploração. A **Lei dos Sexagenários** (ou Saraiva-Cotegipe, 1885) libertou os maiores de 60 anos, muitos já sem condição de trabalhar, e que continuavam dependentes dos antigos senhores. Essas leis procuravam adiar a abolição, e foram criticadas pelos abolicionistas, que exigiam o fim imediato.',
  'O **movimento abolicionista** cresceu a partir da década de 1870, com a participação de intelectuais, jornalistas, advogados e lideranças negras, como **José do Patrocínio**, **Luís Gama**, **André Rebouças** e **Joaquim Nabuco**, além de associações e clubes. As fugas em massa e a recusa do Exército em perseguir os fugitivos aceleraram a desagregação do sistema. Em **13 de maio de 1888**, a **Lei Áurea**, assinada pela princesa Isabel, aboliu a escravidão sem nenhuma política de integração dos libertos, que ficaram sem terra, sem trabalho assegurado e sem acesso à educação. Os senhores também não foram indenizados, o que aumentou o descontentamento da elite escravista com a monarquia.'] },
 { h:'Pós-abolição: liberdade sem direitos', p:[
  'A abolição não foi acompanhada de políticas para garantir moradia, trabalho, educação ou terra aos libertos. A **Lei de Terras** (1850) já havia dificultado o acesso à terra, e a elite defendia a **imigração europeia** como solução para a mão de obra, com base também em teorias racistas que valorizavam o "branqueamento" da população. Muitos libertos permaneceram nas fazendas, em condições próximas às anteriores, ou migraram para as cidades, onde enfrentaram o desemprego, a informalidade, a precariedade da moradia e a discriminação. A liberdade formal não significou **cidadania plena**.',
  'As desigualdades raciais, assim, tiveram continuidade na República. Eram frequentes a **marginalização** dos negros, a criminalização de suas práticas culturais, como a capoeira e as religiões de matriz africana, e a exclusão da participação política, pois o voto era restrito aos alfabetizados, o que deixava de fora a maioria dos libertos. Nas cidades, formaram-se bairros populares, favelas e cortiços, como resultado da falta de acesso à moradia. A **reforma urbana** do Rio de Janeiro, no início do século XX, expulsou muitos deles do centro, revelando como o poder público tratava as populações pobres e negras.',
  'Apesar das dificuldades, a população negra criou formas de organização e de resistência: irmandades religiosas, associações de ajuda mútua, clubes, jornais da imprensa negra, escolas e, mais tarde, movimentos como a **Frente Negra Brasileira** (1931). O samba, o candomblé, a capoeira e outras manifestações foram espaços de afirmação cultural. Essa história mostra que a abolição foi um marco, mas a conquista de direitos efetivos exigiu, e ainda exige, lutas constantes, e inspira políticas de reparação e de promoção da igualdade racial na atualidade.'] },
 { h:'Racismo, memória e políticas de reparação', p:[
  'O **racismo** no Brasil se manifesta de forma estrutural: nas desigualdades de renda, de escolaridade, de acesso à saúde, de moradia e de violência. Durante muito tempo, difundiu-se a ideia de **democracia racial**, popularizada por Gilberto Freyre, segundo a qual o Brasil seria uma sociedade sem preconceito, resultado da mistura das raças. Essa ideia, hoje muito criticada, escondia a persistência do racismo e dificultava seu enfrentamento. Estudos de pesquisadores, como Florestan Fernandes, mostraram que a integração dos negros à sociedade de classes foi incompleta, e que as desigualdades se mantinham.',
  'O reconhecimento do racismo como problema, a partir da luta do **movimento negro**, levou a mudanças. A Constituição de 1988 definiu o racismo como **crime inafiançável e imprescritível**, e reconheceu o direito à terra das **comunidades remanescentes de quilombos**. A **Lei 10.639/2003** tornou obrigatório o ensino da história e da cultura afro-brasileira e africana nas escolas. A **Lei de Cotas** (2012) reservou vagas em universidades e institutos federais para estudantes de escolas públicas, negros, pardos e indígenas, e a Lei de Cotas em concursos públicos também foi adotada. As ações afirmativas buscam reduzir desigualdades históricas.',
  'A memória da escravidão também é um campo de disputas. A valorização de figuras como **Zumbi dos Palmares**, lembrado em 20 de novembro, o Dia da Consciência Negra, é uma forma de contrapor a ideia de que a liberdade foi uma "concessão" da princesa e de reconhecer a luta dos próprios negros. Há ainda o debate sobre monumentos, museus e lugares de memória ligados ao tráfico, como o Cais do Valongo, no Rio de Janeiro, reconhecido como Patrimônio Mundial. Esses assuntos aparecem com regularidade nas provas, que pedem uma visão crítica do passado e do presente.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a abolição e o pós-abolição aparecem em questões sobre o processo gradual de fim da escravidão, os interesses da Inglaterra, as leis do Ventre Livre e dos Sexagenários, o movimento abolicionista, as formas de resistência, a imigração e a marginalização dos libertos. Os textos mostram trechos de abolicionistas, relatos de ex-escravizados, imagens de Debret e de Rugendas, e dados sobre as desigualdades raciais, e pedem que se relacione o passado com as questões sociais de hoje, como as cotas e o racismo.',
  'Pontos de atenção: a abolição não foi uma "dádiva" da princesa, mas o resultado de lutas e de pressões econômicas e políticas; as leis do Ventre Livre e dos Sexagenários foram medidas parciais; a Lei Áurea não previu indenização aos libertos nem políticas de integração; a imigração europeia teve motivações ligadas ao branqueamento; e as desigualdades raciais atuais têm raízes históricas. Evite as interpretações que tratam o pós-abolição como uma simples continuação da história, sem considerar as lutas e conquistas da população negra.',
  'Para revisar, faça uma linha do tempo: 1850 (fim do tráfico), 1871 (Ventre Livre), 1885 (Sexagenários), 1888 (Lei Áurea), 1931 (Frente Negra), 1988 (racismo como crime), 2003 (Lei 10.639), 2012 (Lei de Cotas). Associe a cada um as lutas e os agentes envolvidos. Esse tema prepara o seguinte, a República Velha, em que as elites oligárquicas controlaram a política, e em que a população pobre e negra seguiu à margem da cidadania.'] }
]},
{ t:'República Velha (1889 a 1930)', txt:[
 { h:'A República da Espada e a Constituição de 1891', p:[
  'A **República Velha**, ou Primeira República (1889 a 1930), começou com o governo provisório do marechal **Deodoro da Fonseca** e a fase conhecida como **República da Espada** (1889 a 1894), em que os militares dominaram o poder. A **Constituição de 1891**, de inspiração norte-americana, estabeleceu a **República federativa**, o **presidencialismo**, a separação de poderes, a separação entre Estado e Igreja e o voto direto, mas restringiu o voto aos **homens alfabetizados** maiores de 21 anos, o que excluía mulheres, analfabetos, mendigos e soldados, a maioria da população. O voto era **aberto**, e não secreto.',
  'Os dois primeiros governos foram de Deodoro e **Floriano Peixoto**. Deodoro enfrentou um conflito com o Congresso, e renunciou, em 1891, e Floriano, seu vice, assumiu e enfrentou revoltas, como a **Revolta da Armada** e a **Revolução Federalista** (Rio Grande do Sul), reprimindo-as com dureza. Ficou conhecido como o "Marechal de Ferro". Em 1894, assumiu o primeiro presidente civil, **Prudente de Morais**, eleito pelos cafeicultores paulistas, o que marcou o início da **República Oligárquica**, em que as elites rurais, em especial as de São Paulo e Minas Gerais, controlaram o poder.',
  'Paralelamente, o governo provisório tratou da economia, com o **Encilhamento**, política de emissão de moeda e de crédito fácil, que provocou especulação e inflação, e com uma crise financeira. A nova República também precisou lidar com a **construção de símbolos**, como a bandeira e o hino, e de uma identidade, e com a oposição monarquista. Os republicanos positivistas, como Benjamin Constant, influenciaram a bandeira, com o lema "Ordem e Progresso". Essa fase inicial revela como o novo regime tentou se consolidar em meio a conflitos e à ausência de participação popular.'] },
 { h:'A política do café com leite e o coronelismo', p:[
  'A partir do governo de **Campos Sales** (1898 a 1902), consolidou-se a **política dos governadores**: o presidente apoiava os grupos dominantes nos estados, e em troca recebia o apoio dos deputados e senadores, assegurando a estabilidade. Na prática, formou-se a **política do café com leite**, em que as oligarquias de **São Paulo** (cafeicultores) e de **Minas Gerais** (pecuaristas e produtores de leite) se revezavam na presidência. Os demais estados ficavam em segundo plano, e as decisões favoreciam os interesses agroexportadores, em particular os do café, com políticas como o **Convênio de Taubaté** (1906), em que o governo comprava o excedente do produto para manter os preços.',
  'No interior, o poder local era exercido pelos **coronéis**, grandes proprietários que controlavam a vida política e econômica de sua região. O **coronelismo** se baseava em relações de dependência: o coronel garantia empregos, favores e proteção aos trabalhadores e agregados, e em troca recebia o voto, por meio do **voto de cabresto**. As eleições eram marcadas por fraude, como o voto "a bico de pena" (atas falsas), o "voto de defunto" e a **degola** (a não aprovação dos eleitos da oposição pela Comissão de Verificação de Poderes). Os governos estaduais e federal tinham no coronel um intermediário para a obtenção de votos.',
  'Esse sistema excluía a maioria da população da participação política. A República, portanto, foi uma forma de organização do poder pelas elites, com pouca democracia real, e manteve as desigualdades sociais e regionais. Mesmo assim, ele não ficou sem contestação. Já nos anos iniciais, e ao longo do período, surgiram movimentos populares, tenentismo e uma crescente oposição urbana, que revelaram as contradições do regime e prepararam a sua crise, a partir dos anos 1920, com as mudanças econômicas e sociais que o país vivia.'] },
 { h:'Os movimentos sociais e as revoltas da República Velha', p:[
  'Em reação à exclusão e às condições de vida, ocorreram movimentos populares. A **Guerra de Canudos** (1896 a 1897), no sertão da Bahia, reuniu milhares de sertanejos pobres em torno do líder religioso **Antônio Conselheiro**, em uma comunidade que praticava a propriedade coletiva da terra. Vista pelo governo e pelas elites como uma ameaça monarquista, foi destruída por tropas do Exército, em uma campanha de extrema violência, que a obra Os Sertões, de Euclides da Cunha, imortalizou. A **Guerra do Contestado** (1912 a 1916), em Santa Catarina e Paraná, teve origem em conflitos pela posse de terras, após a construção de uma ferrovia, e também envolveu camponeses e líderes religiosos.',
  'Na cidade do Rio de Janeiro, a **Revolta da Vacina** (1904) foi uma rebelião contra a campanha de vacinação obrigatória contra a varíola, conduzida por Oswaldo Cruz, durante a reforma urbana do prefeito Pereira Passos. A população pobre, expulsa do centro e alarmada com a vacina obrigatória, que era imposta de forma autoritária, protestou. Na **Revolta da Chibata** (1910), marinheiros, em sua maioria negros, liderados por João Cândido, protestaram contra os castigos físicos na Marinha. O **cangaço** e o **messianismo** também foram expressões sociais do período.',
  'O crescimento da **imigração** e da **indústria**, especialmente em São Paulo, deu origem a uma classe operária, que se organizou em sindicatos e fez greves, influenciada por ideias anarquistas e socialistas. A **Greve Geral de 1917**, em São Paulo, é a mais conhecida, e reivindicava melhores salários e redução da jornada. O governo reprimiu esses movimentos, como "questão de polícia". Em 1922, foi fundado o **Partido Comunista do Brasil**. A emergência de novos grupos sociais, como os operários e os setores médios urbanos, ampliava a pressão sobre o sistema oligárquico.'] },
 { h:'A crise e o fim da República Velha', p:[
  'A partir dos anos 1920, o sistema oligárquico entrou em crise. Os **tenentes**, jovens oficiais do Exército que criticavam a corrupção e as fraudes eleitorais, organizaram revoltas, como a dos **18 do Forte de Copacabana** (1922), a Revolta Paulista (1924) e a **Coluna Prestes** (1925 a 1927), que percorreu milhares de quilômetros pelo interior do país, divulgando as ideias de reforma política, voto secreto e justiça social. O **tenentismo** não era um movimento unificado, mas exprimia o descontentamento dos setores médios e militares com a política oligárquica e, embora derrotado militarmente, teve influência.',
  'Em 1922, a **Semana de Arte Moderna**, em São Paulo, marcou o início do modernismo, que criticava a cultura tradicional e buscava uma arte nacional, e simbolizou as transformações culturais do período. A **crise de 1929**, com a queda da Bolsa de Nova York, derrubou os preços do café, e arruinou os cafeicultores, que dependiam das exportações. Em 1930, o presidente **Washington Luís**, paulista, rompeu o acordo do café com leite ao indicar outro paulista, **Júlio Prestes**, para sucedê-lo, em vez de um mineiro. Minas Gerais, a Paraíba e o Rio Grande do Sul formaram a **Aliança Liberal**, com **Getúlio Vargas** como candidato.',
  'Júlio Prestes venceu as eleições de março de 1930, em um pleito considerado fraudado. O assassinato do vice de Vargas, **João Pessoa**, na Paraíba, serviu de estopim para a **Revolução de 1930**, movimento armado que depôs Washington Luís, impediu a posse de Júlio Prestes e levou **Getúlio Vargas** ao poder, em novembro. O movimento reuniu dissidentes das oligarquias, tenentes e setores urbanos. Encerrava-se a República Velha, e se iniciava uma nova fase, em que o Estado teria um papel mais intervencionista na economia e nas relações sociais, o que será analisado no tema da Era Vargas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A República Velha aparece no ENEM em questões sobre o coronelismo, o voto de cabresto, a política do café com leite, a exclusão política da maioria da população, e os movimentos sociais (Canudos, Contestado, Vacina, Chibata, greves operárias, tenentismo). Os enunciados incluem charges de época, trechos de Euclides da Cunha, imagens de eleições e dados sobre o eleitorado, e pedem que o estudante relacione as práticas políticas com as desigualdades econômicas e sociais.',
  'Pontos de atenção: a República foi proclamada por um golpe militar, sem participação popular; o regime era oligárquico, e o voto restrito e aberto favorecia a fraude; a "política dos governadores" e o "café com leite" garantiam o poder de poucos estados; o coronelismo se baseava na troca de favores e na dependência; os movimentos populares eram reprimidos com violência; e a crise de 1929 e a ruptura do acordo político levaram ao fim do regime. Evite a ideia de que a República Velha era democrática por ter eleições.',
  'Para revisar, monte um quadro: República da Espada (Deodoro e Floriano) → República Oligárquica (Prudente de Morais, Campos Sales, café com leite) → mecanismos (coronelismo, voto de cabresto, degola) → movimentos (Canudos, Contestado, Vacina, Chibata, greves, tenentismo) → crise (1922, 1929) → Revolução de 1930. Associe ao tema anterior (abolição e exclusão dos libertos) e ao seguinte (Era Vargas), em que a política e a economia brasileiras passaram por transformações profundas.'] }
]},
{ t:'Era Vargas (1930 a 1945)', txt:[
 { h:'O Governo Provisório e a Constituição de 1934', p:[
  'Com a **Revolução de 1930**, **Getúlio Vargas** assumiu o poder e chefiou um **Governo Provisório** (1930 a 1934). Dissolveu o Congresso e as assembleias estaduais, nomeou **interventores** nos estados, o que enfraqueceu as oligarquias regionais, e centralizou o poder. Criou o **Ministério do Trabalho, Indústria e Comércio** e o **Ministério da Educação e Saúde**, e adotou medidas para controlar os preços e os estoques do café. O Estado ganhou um papel mais ativo, e começou a regular a economia e as relações entre empregadores e empregados, em um modelo conhecido como **Estado intervencionista**.',
  'Os grupos paulistas, descontentes com a perda de poder e com a falta de uma constituição, organizaram a **Revolução Constitucionalista de 1932**, em São Paulo, que foi derrotada militarmente, mas conseguiu o compromisso de convocação de uma **Assembleia Constituinte**. A **Constituição de 1934** foi uma das mais avançadas do período: instituiu o **voto secreto** e o **voto feminino**, a Justiça Eleitoral, a Justiça do Trabalho e direitos trabalhistas, como o salário mínimo, a jornada de oito horas e o repouso semanal, além de princípios nacionalistas e de intervenção do Estado na economia. Vargas foi eleito, indiretamente, presidente constitucional.',
  'O período foi marcado por polarização política. De um lado, a **Ação Integralista Brasileira** (AIB), de Plínio Salgado, de inspiração fascista, com o lema "Deus, pátria e família". De outro, a **Aliança Nacional Libertadora** (ANL), de esquerda, que reuniu comunistas, socialistas e liberais, e tinha Luís Carlos Prestes como presidente de honra. Em 1935, a ANL promoveu uma insurreição, a **Intentona Comunista**, rapidamente reprimida, e que serviu de pretexto para a repressão política e o fortalecimento do governo, que decretou o estado de sítio e preparou o golpe que viria.'] },
 { h:'O Estado Novo (1937 a 1945)', p:[
  'Em novembro de 1937, Vargas, com o apoio das Forças Armadas, deu um **golpe de Estado** e instaurou o **Estado Novo**, uma ditadura. Alegou-se o risco de uma revolução comunista, com base no **Plano Cohen**, um documento falso, forjado por integrantes do governo. Foi outorgada a **Constituição de 1937**, conhecida como "**Polaca**", que dava amplos poderes ao presidente, fechava o Congresso, extinguia os partidos políticos e instituía a censura. O regime combinou o **autoritarismo**, o **nacionalismo**, o **centralismo** e o **populismo**, e se aproximou, em alguns aspectos, de modelos fascistas europeus.',
  'Para controlar a opinião pública, o governo criou o **DIP** (Departamento de Imprensa e Propaganda), responsável pela censura e pela propaganda oficial, que construiu a imagem de Vargas como "pai dos pobres" e exaltava o nacionalismo, com o uso do rádio e do cinema. A polícia política, sob o comando de Filinto Müller, perseguia opositores, com prisões, tortura e exílios, como no caso de Graciliano Ramos e Olga Benário. A repressão atingiu também os integralistas, que tentaram um golpe em 1938. Na educação, o governo incentivou a formação de uma identidade nacional, com a ênfase no civismo, no ensino de história pátria e no controle dos currículos.',
  'Na política externa, Vargas manteve inicialmente uma posição pendular entre os Estados Unidos e a Alemanha. Em 1942, depois de ataques alemães a navios brasileiros, o Brasil declarou guerra ao Eixo, e enviou a **Força Expedicionária Brasileira** (FEB) à Itália, em 1944. A contradição de lutar contra regimes totalitários, enquanto havia uma ditadura no país, contribuiu para a oposição ao regime. Em 1945, com a pressão pela redemocratização e o apoio dos militares, Vargas foi deposto por um golpe, e deixou o poder, o que encerrou a Era Vargas, mas deixou um legado muito marcante.'] },
 { h:'Economia, industrialização e legislação trabalhista', p:[
  'No campo econômico, o governo Vargas promoveu a **industrialização** por meio da **substituição de importações**: com a crise de 1929, que reduziu as importações e a renda do café, o país passou a produzir internamente o que antes comprava do exterior. O Estado apoiou a **indústria de base**, e criou a **Companhia Siderúrgica Nacional** (CSN), em Volta Redonda (1941), com apoio dos Estados Unidos, em troca da cooperação na guerra, a **Companhia Vale do Rio Doce** (1942) e, depois, a Petrobras (1953, no segundo governo). Foram criados também o Conselho Nacional do Petróleo e o Código de Minas, e a política nacionalista ganhou espaço.',
  'A **legislação trabalhista** foi um dos pilares do regime. Em 1943, foi aprovada a **Consolidação das Leis do Trabalho** (CLT), que reuniu normas sobre contratos, jornada, férias, salário mínimo (criado em 1940), carteira de trabalho e segurança no trabalho. Os sindicatos foram organizados sob controle do Estado, com a estrutura do **sindicato oficial** (atrelado ao Ministério do Trabalho), a cobrança do **imposto sindical** e a proibição da greve, o que limitava sua autonomia. Os direitos foram concedidos "de cima", e a imagem de Vargas como protetor dos trabalhadores, o "pai dos pobres", fortaleceu o **populismo**.',
  'Os direitos concedidos beneficiaram, sobretudo, os trabalhadores **urbanos**, e deixaram de fora os trabalhadores rurais, os domésticos e os informais, o que manteve a desigualdade no campo. Esse modelo, que combinava benefícios e controle, representava uma forma de integrar a classe operária ao sistema, ao mesmo tempo em que a mantinha sob tutela. A política econômica, ao fortalecer a indústria nacional e a infraestrutura, mudou a estrutura do país, que deixou de ser essencialmente agrário-exportador. Houve crescimento da urbanização e dos setores médios, e novas demandas políticas.'] },
 { h:'Cultura, nacionalismo e legado', p:[
  'A cultura foi um instrumento do projeto nacionalista. O governo valorizou o **samba**, o **carnaval** e o **futebol** como símbolos nacionais, e transformou manifestações antes marginalizadas em elementos da identidade brasileira, ao mesmo tempo em que as controlava, por meio do rádio, do DIP e das escolas de samba. Criou o **Serviço do Patrimônio Histórico e Artístico Nacional** (SPHAN, 1937), que protege bens culturais. O intelectual Gilberto Freyre popularizou a ideia de "democracia racial" nesse contexto, e a mestiçagem passou a ser vista como característica positiva, embora escondesse desigualdades. A cultura popular foi usada pelo regime para a construção de uma ideia de unidade nacional.',
  'O balanço da Era Vargas é complexo. De um lado, há avanços: a legislação trabalhista, a criação de instituições e de empresas estatais, a industrialização, o voto feminino e a Justiça Eleitoral. De outro, a **repressão**, a **censura**, a **centralização** e a limitação da liberdade, sobretudo no Estado Novo. Muitos historiadores destacam a relação entre **direitos sociais e restrição dos direitos políticos**, característica do período. Por isso, a imagem de Vargas é controversa: é lembrado como líder popular e como ditador, e o tema continua despertando debates.',
  'Em 1945, a derrota do fascismo na Europa e a redemocratização do mundo aumentaram a pressão por mudanças. Vargas tentou permanecer, com o movimento "queremista" ("Queremos Getúlio"), mas os militares o depuseram, em outubro. O poder passou a **José Linhares**, presidente do STF, e foram convocadas eleições, com a vitória do general **Eurico Gaspar Dutra**. Vargas voltaria à presidência pelo voto, em 1951, e se suicidaria em 1954, deixando a "Carta-Testamento". Esse desfecho marca a continuidade do getulismo e do trabalhismo na política brasileira, nos anos seguintes.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Era Vargas é um dos temas de História do Brasil mais cobrados no ENEM. Aparece em questões sobre o populismo, a legislação trabalhista (CLT) e o sindicalismo atrelado ao Estado, a propaganda do DIP, a censura, o Estado Novo, a política de industrialização e de nacionalismo econômico, e o uso da cultura popular. Os enunciados incluem cartazes, charges e discursos, e pedem para relacionar a imagem de Vargas com a construção do poder e com a ideia de "outorga" de direitos.',
  'Pontos de atenção: as fases (Governo Provisório, Constitucional e Estado Novo); a Constituição de 1934 (voto secreto e feminino, direitos trabalhistas) em comparação com a de 1937 (autoritária); o populismo como relação entre o líder e as massas, baseada em benefícios e propaganda; o caráter paternalista dos direitos trabalhistas, concedidos pelo Estado e controlados por ele; a industrialização por substituição de importações; e a combinação entre repressão e conquistas sociais. Evite avaliações simplistas, que só valorizam ou só condenam o período.',
  'Para revisar, esquematize: 1930 (Revolução) → Governo Provisório → 1932 (Constitucionalista) → 1934 (Constituição) → 1935 (Intentona) → 1937 (golpe e Polaca) → DIP, CLT, CSN, Vale → 1942 (guerra ao Eixo) → 1945 (queda). Relacione-o ao tema anterior (crise da República Velha) e ao seguinte (República Democrática de 1945 a 1964), em que os herdeiros do getulismo e as forças conservadoras disputaram o poder, até o golpe de 1964.'] }
]}
];
