/* História: textos corridos, temas 4 a 6 */
module.exports = [
{ t:'Renascimento e Reformas religiosas', txt:[
 { h:'As transformações da Baixa Idade Média e o Renascimento', p:[
  'A transição da Idade Média para a Idade Moderna foi marcada por mudanças profundas. O comércio e as cidades cresceram, uma nova classe, a **burguesia**, enriqueceu e passou a ter peso político, o poder dos reis se fortaleceu e as navegações abriram novos mundos. Nesse ambiente, surgiu na Itália, a partir do século XIV, o movimento cultural chamado de **Renascimento**, que se espalhou pela Europa nos séculos XV e XVI. O nome indica o "renascer" do interesse pelos valores da Antiguidade clássica, de Grécia e Roma, após o período medieval.',
  'A Itália foi o berço do movimento por vários motivos. Cidades como Florença, Veneza e Gênova eram ricas pelo comércio e pelas atividades bancárias, e famílias poderosas, como os **Médici**, atuavam como **mecenas**, financiando artistas e intelectuais. O território italiano guardava as ruínas e os textos da Roma antiga, e a queda de Constantinopla, em 1453, levou à Itália estudiosos bizantinos com manuscritos gregos. A invenção da **imprensa de tipos móveis** por Gutenberg, por volta de 1450, ampliou a circulação dos livros e das ideias, acelerando a difusão do movimento.',
  'O pensamento renascentista foi marcado pelo **humanismo**, que colocou o ser humano no centro das preocupações, em oposição ao teocentrismo medieval, em que Deus era o centro de tudo. Não significava abandonar a religião, mas valorizar a razão, a experiência, a liberdade e o potencial humano. Também se desenvolveu o **individualismo**, a valorização do talento e do mérito pessoais, o **racionalismo** e o **naturalismo**, a observação da natureza. Esses valores se alinhavam aos interesses da burguesia, que buscava uma visão de mundo que justificasse o lucro e a iniciativa individual.'] },
 { h:'Artes, ciências e pensamento político no Renascimento', p:[
  'Nas artes, o Renascimento trouxe a busca pelo **realismo**, pela **perspectiva**, pela proporção e pelo estudo da anatomia. **Leonardo da Vinci** (A Última Ceia, Mona Lisa) foi pintor, inventor e cientista, símbolo do "homem universal". **Michelangelo** esculpiu o Davi e a Pietà e pintou o teto da Capela Sistina. **Rafael** é conhecido por A Escola de Atenas, e **Botticelli**, por O Nascimento de Vênus. Na arquitetura, **Brunelleschi** projetou a cúpula da catedral de Florença. Os temas incluíam assuntos religiosos e mitológicos, além de retratos, que valorizavam a individualidade.',
  'Na literatura e no pensamento, destacaram-se **Dante Alighieri** (A Divina Comédia), **Petrarca** e **Boccaccio**, na Itália; **Thomas More** (Utopia), na Inglaterra; **Erasmo de Roterdã** (Elogio da Loucura), que criticou a corrupção da Igreja; **Shakespeare**, na Inglaterra; e **Cervantes**, na Espanha, autor de Dom Quixote. Na política, **Maquiavel**, em O Príncipe, analisou o poder de forma realista, separando-o da moral religiosa, e é considerado um dos fundadores da ciência política moderna. Na ciência, o espírito de observação levou a avanços na anatomia, na astronomia e na matemática.',
  'Na astronomia, **Nicolau Copérnico** propôs o **heliocentrismo**, segundo o qual a Terra gira em torno do Sol, contrariando a visão geocêntrica aceita pela Igreja. **Galileu Galilei**, com o telescópio, forneceu evidências a favor da teoria e foi processado pela Inquisição, tendo de renegá-la. **Kepler** descreveu as órbitas elípticas dos planetas. Esse conjunto de mudanças, conhecido como **Revolução Científica**, preparou o terreno para o racionalismo e para o Iluminismo, e mostra como a valorização da razão e da observação transformou a forma de produzir conhecimento.'] },
 { h:'A Reforma Protestante', p:[
  'No início do século XVI, a Igreja católica estava em crise: o luxo do alto clero, a venda de cargos eclesiásticos, a prática de venda de **indulgências** (documentos que prometiam o perdão dos pecados em troca de dinheiro) e a corrupção geravam críticas. Em 1517, o monge alemão **Martinho Lutero** publicou as **95 Teses** em Wittenberg, questionando as indulgências e defendendo que a salvação vinha da **fé** (justificação pela fé), e não de obras ou de pagamentos, e que a **Bíblia** era a autoridade máxima, devendo ser lida por todos, o que o levou a traduzi-la para o alemão. A imprensa difundiu rapidamente suas ideias.',
  'Lutero foi excomungado, mas contou com a proteção de príncipes alemães, que viram na ruptura uma chance de ganhar autonomia e confiscar bens da Igreja. O **luteranismo** se espalhou pela Alemanha e pela Escandinávia, e a luta entre protestantes e católicos levou a conflitos, resolvidos provisoriamente na Paz de Augsburgo (1555), que estabeleceu o princípio de que a religião do príncipe seria a de seus súditos. A Reforma teve também relação com os interesses econômicos e políticos da época, e não só religiosos, e com a insatisfação diante do poder da Igreja.',
  'Outros reformadores surgiram. **João Calvino**, na Suíça (Genebra), defendeu a **predestinação**: Deus já teria escolhido os salvos, e o sucesso no trabalho e a vida austera seriam sinais da eleição divina. Essa doutrina valorizava o trabalho, a poupança e o lucro, e se adaptava aos interesses da burguesia, daí a interpretação, feita pelo sociólogo Max Weber, de que o **calvinismo** teria contribuído para o espírito do capitalismo. Na Inglaterra, o rei **Henrique VIII** rompeu com Roma, em 1534, por motivos políticos e dinásticos (a anulação de seu casamento) e criou a **Igreja Anglicana**, da qual era o chefe.'] },
 { h:'A Contrarreforma e as consequências das reformas', p:[
  'A Igreja católica reagiu com a **Contrarreforma** (ou Reforma Católica), movimento de renovação interna e de combate ao protestantismo. O **Concílio de Trento** (1545 a 1563) reafirmou os dogmas católicos, como a salvação pela fé e pelas obras, os sete sacramentos e a autoridade do papa, proibiu a venda de indulgências e criou seminários para melhorar a formação dos padres. Foi restabelecido o **Tribunal do Santo Ofício** (Inquisição), que perseguia os considerados hereges, e foi criado o **Index**, a lista de livros proibidos. A censura procurava conter a difusão das ideias reformistas.',
  'Uma das principais ferramentas da Contrarreforma foi a **Companhia de Jesus**, ordem religiosa criada por **Inácio de Loyola**, em 1534, e aprovada em 1540. Os **jesuítas** atuavam na educação, fundando colégios, e na **catequese**, evangelizando povos nas colônias, como no Brasil, onde José de Anchieta e Manuel da Nóbrega tiveram papel destacado na conversão dos indígenas e na fundação de aldeamentos. A educação jesuítica, de caráter humanista e católico, formou gerações de elites coloniais. Assim, a Contrarreforma se ligou à expansão colonial e à expansão da fé católica em outros continentes.',
  'As consequências das reformas foram enormes: a **unidade religiosa** da Europa ocidental acabou, e surgiram igrejas protestantes diversas; houve **guerras religiosas**, como a Guerra dos Trinta Anos (1618 a 1648) e as guerras na França, entre católicos e huguenotes, com episódios como a Noite de São Bartolomeu (1572); a autoridade da Igreja se enfraqueceu e os Estados se fortaleceram, e a **alfabetização** aumentou, pela importância de ler a Bíblia. Também cresceu a ideia de **liberdade de consciência**, que mais tarde se tornou tolerância religiosa, base de direitos modernos.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, o Renascimento aparece em questões que pedem a relação entre as mudanças culturais e as transformações econômicas e sociais, como o crescimento da burguesia, o mecenato e o humanismo. Há também questões com obras de arte (pinturas e esculturas), a serem interpretadas quanto aos valores da época, como perspectiva, realismo e centralidade humana. A Reforma é cobrada a partir de trechos de Lutero e de Calvino, de charges e de gravuras da época, e pela relação com o capitalismo e com as monarquias.',
  'Pontos de atenção: o Renascimento **não** rejeitou a religião, mas deslocou o foco para o ser humano; o mecenato era financiado por famílias ricas e pela Igreja; o humanismo valorizava a razão e a experiência; a imprensa foi decisiva para difundir as ideias; as 95 Teses criticavam as indulgências; o calvinismo se associa à valorização do trabalho e da riqueza; e a Contrarreforma usou a Inquisição, o Index e os jesuítas. Atenção à diferença entre a Reforma Protestante e a Contrarreforma católica.',
  'Para revisar, monte dois quadros: no primeiro, as características do Renascimento (humanismo, racionalismo, individualismo, naturalismo) e seus principais nomes; no segundo, as principais Reformas (luterana, calvinista e anglicana), com a causa, a figura central e as consequências, e a resposta católica. Relacione-os às Grandes Navegações e ao Absolutismo, que formam um conjunto de transformações da Idade Moderna, e que você estudará nos próximos temas.'] }
]},
{ t:'Grandes Navegações e colonização', txt:[
 { h:'As causas da expansão marítima europeia', p:[
  'Entre os séculos XV e XVII, os europeus ampliaram seus horizontes ao navegar pelos oceanos, em um processo conhecido como **Grandes Navegações** ou expansão marítima. Várias causas se combinaram. O **comércio** com o Oriente, especialmente de especiarias (pimenta, cravo, canela), tinha grande valor, mas as rotas tradicionais, pelo Mediterrâneo, eram controladas por mercadores italianos e, após 1453, ficaram mais difíceis com a conquista de Constantinopla pelos turcos otomanos. Os reinos europeus queriam acesso direto às fontes, para reduzir os custos e ampliar os lucros.',
  'Também pesaram a **escassez de metais preciosos**, necessários às moedas e ao comércio, e a busca por ouro e prata, a **aliança entre a burguesia e os reis**, que financiavam as viagens, em troca de privilégios, e a vontade de **expandir a fé cristã**, com a evangelização. Os avanços técnicos tornaram a empreitada possível: a **caravela**, navio leve e veloz, a **bússola**, o **astrolábio** e o **quadrante**, instrumentos de orientação, e os mapas melhorados, os portulanos. A **Escola de Sagres**, associada ao Infante D. Henrique, simboliza o investimento português no conhecimento náutico.',
  'Portugal foi pioneiro por vários motivos: foi um dos primeiros Estados centralizados, com a **Revolução de Avis** (1383 a 1385), que uniu a burguesia mercantil e a monarquia; tinha uma posição geográfica favorável, voltada para o Atlântico; e tinha experiência marítima, com a pesca e o comércio. Em 1415, tomou Ceuta, no norte da África, e depois explorou a costa africana, até que Bartolomeu Dias contornou o Cabo da Boa Esperança (1488) e **Vasco da Gama** chegou à Índia (1498), abrindo uma rota direta para o Oriente.'] },
 { h:'Espanha, a chegada à América e a divisão do mundo', p:[
  'A Espanha se unificou mais tarde, com o casamento de Fernando de Aragão e Isabel de Castela, e a conclusão da **Reconquista** (expulsão dos mouros), em 1492. Nesse mesmo ano, a Coroa espanhola financiou a viagem do navegador genovês **Cristóvão Colombo**, que defendia a ideia de alcançar as Índias navegando para o ocidente. Em outubro de 1492, ele chegou a ilhas do Caribe, acreditando ter atingido o Oriente, e por isso os habitantes nativos foram chamados de "índios". Viagens posteriores, como a de **Américo Vespúcio**, mostraram que se tratava de um novo continente, a América.',
  'Para evitar disputas, Portugal e Espanha assinaram, em 1494, o **Tratado de Tordesilhas**, que dividiu as terras descobertas e por descobrir por uma linha imaginária a 370 léguas a oeste das ilhas de Cabo Verde: o que ficasse a leste seria de Portugal e a oeste, da Espanha. Esse tratado, que ignorava as demais potências europeias e os povos nativos, permitiu a Portugal reivindicar as terras do atual Brasil, alcançadas oficialmente por **Pedro Álvares Cabral**, em 1500. Em 1519, a expedição de **Fernão de Magalhães**, concluída por Elcano em 1522, realizou a primeira circum-navegação do globo.',
  'A expansão marítima foi acompanhada de uma nova visão sobre o mundo. Para os europeus, as terras eram "descobertas", expressão que ignora os povos que já viviam nelas, e que hoje se prefere chamar de "chegada" ou "invasão". Os encontros entre culturas foram marcados por violência e por trocas. O comércio se globalizou, formando uma economia que ligava Europa, África, Ásia e América, em uma primeira etapa da **globalização** moderna, que fortaleceu o capitalismo comercial e o acúmulo de riquezas pelos Estados europeus.'] },
 { h:'A conquista e a colonização da América', p:[
  'Na América espanhola, a conquista foi rápida e violenta. **Hernán Cortés** destruiu o Império **Asteca**, no México (1519 a 1521), e **Francisco Pizarro** conquistou o Império **Inca**, no Peru (1532 a 1533). A vitória dos espanhóis foi favorecida pela superioridade das armas de fogo e dos cavalos, pelas alianças com povos rivais dos impérios e, principalmente, pelas **doenças** trazidas da Europa, como a varíola e o sarampo, contra as quais os nativos não tinham imunidade, o que causou uma **catástrofe demográfica**: calcula-se que a população indígena diminuiu drasticamente em poucas décadas.',
  'A colonização espanhola se baseou na **exploração de metais preciosos**, sobretudo a prata, em minas como as de Potosí, na atual Bolívia, e na exploração de mão de obra indígena por meio de sistemas como a **encomienda** e a **mita**. A administração era controlada por órgãos como o Conselho das Índias e os vice-reinos (Nova Espanha e Peru). Já os ingleses e franceses, mais tarde, fundaram colônias na América do Norte, em formas distintas: as **colônias de povoamento**, no norte, com pequenos proprietários e trabalho livre, e as **colônias de exploração**, no sul, com grandes plantações e escravidão.',
  'Os efeitos para a Europa foram profundos. O afluxo de ouro e prata americanos causou a **Revolução dos Preços**, uma inflação que atingiu a economia europeia. O comércio atlântico enriqueceu a burguesia e fortaleceu o **mercantilismo**, política econômica que defendia o acúmulo de metais, a balança comercial favorável, o monopólio e o protecionismo. O **sistema colonial** se baseava no **pacto colonial**: a colônia produzia o que interessava à metrópole e só podia comerciar com ela. Assim, a colonização foi uma peça-chave na acumulação de capital que depois sustentou a Revolução Industrial.'] },
 { h:'O tráfico de escravos e o legado da colonização', p:[
  'A colonização da América dependeu fortemente do **trabalho escravo africano**. O tráfico de pessoas escravizadas, que já existia, intensificou-se, e entre os séculos XVI e XIX, milhões de africanos foram sequestrados e levados à América em condições desumanas nos navios negreiros. O tráfico era altamente lucrativo, envolvia mercadores europeus, reinos africanos e comerciantes na América, e foi um dos pilares do comércio atlântico. Os africanos tinham culturas, línguas e conhecimentos diversos, e resistiram de várias formas, como em fugas, revoltas e formação de quilombos.',
  'Para justificar a escravidão e a conquista, foram usados argumentos religiosos, que apelavam à "salvação das almas", e racistas, que consideravam os não europeus inferiores. Esses discursos produziram marcas duradouras de desigualdade e de racismo nas sociedades americanas. Por outro lado, a colonização também provocou **trocas culturais** e biológicas, conhecidas como "Intercâmbio Colombiano": produtos americanos, como o milho, a batata, o tomate, o cacau e o tabaco, passaram à Europa e à Ásia, e animais e plantas europeus, como o trigo, o cavalo e o gado, chegaram à América.',
  'O legado dessa fase é complexo. Há as **permanências**: a estrutura fundiária concentrada, a economia voltada à exportação de matérias-primas, as desigualdades sociais, o racismo e a presença de línguas europeias. E há as **resistências** e as **contribuições** dos povos indígenas e africanos, na língua, na culinária, na religião, na música e no trabalho, que formaram sociedades multiculturais. Entender a colonização como um processo de exploração e, ao mesmo tempo, de construção de novas culturas é essencial para interpretar as questões do ENEM sobre identidade e desigualdade.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, as Grandes Navegações aparecem em questões sobre as causas da expansão, o papel do Estado e da burguesia, o Tratado de Tordesilhas, o impacto da conquista sobre os povos indígenas e a relação com o mercantilismo e o capitalismo comercial. Também são frequentes os textos que discutem a visão eurocêntrica dos "descobrimentos", a catástrofe demográfica, o tráfico e os impactos culturais, e as imagens de mapas da época, que pedem a leitura crítica.',
  'Pontos de atenção: a expansão marítima foi motivada por fatores econômicos, políticos, religiosos e técnicos, e não apenas pela "curiosidade"; Portugal saiu na frente por sua centralização precoce e posição atlântica; o Tratado de Tordesilhas dividiu o mundo entre Portugal e Espanha; a morte de indígenas se deveu a doenças, à guerra e ao trabalho forçado; o mercantilismo associava metais preciosos, monopólio e pacto colonial. Evite a visão simplista de que os europeus "descobriram" terras vazias e atrasadas.',
  'Para revisar, faça uma linha do tempo: 1415 (Ceuta), 1488 (Cabo da Boa Esperança), 1492 (Colombo), 1494 (Tordesilhas), 1498 (Vasco da Gama), 1500 (Cabral) e 1519 (Magalhães). Em seguida, crie um quadro comparando a colonização espanhola e a portuguesa, a de exploração e a de povoamento, e liste os efeitos para a Europa, a África e a América. O tema seguinte, o Brasil Colônia, aplica essas ideias à realidade brasileira, com foco na economia açucareira.'] }
]},
{ t:'Brasil Colônia: economia açucareira', txt:[
 { h:'Os primeiros tempos e a administração colonial', p:[
  'Quando os portugueses chegaram à costa do Brasil, em 1500, a região era habitada por centenas de povos indígenas, de diferentes línguas e culturas, entre eles os tupis, que ocupavam grande parte do litoral. Nas primeiras décadas, o interesse da Coroa foi limitado, pois não se encontraram metais preciosos nem especiarias, como no Oriente. A atividade principal foi a extração do **pau-brasil**, madeira usada na fabricação de corantes, com o uso de mão de obra indígena, por meio do **escambo**, a troca de objetos por trabalho, e o território foi visitado por piratas, principalmente franceses.',
  'A ameaça de invasões estrangeiras e o desejo de garantir a posse da terra levaram Portugal a iniciar a colonização efetiva. Em 1534, adotou o sistema de **capitanias hereditárias**: o território foi dividido em faixas, entregues a donatários, que deviam povoar e explorar a terra com recursos próprios, em troca de direitos e privilégios. O sistema teve resultados desiguais: poucas capitanias prosperaram, como Pernambuco e São Vicente, e muitas fracassaram, pela falta de recursos, pela distância e pela resistência indígena. Em 1548, a Coroa criou o **Governo-Geral**, para centralizar a administração, e **Tomé de Sousa** foi o primeiro governador, com sede em Salvador.',
  'A administração colonial contava com os governadores-gerais, ouvidores (justiça), provedores (finanças), as **câmaras municipais**, dominadas pelos "homens bons", grandes proprietários, e a Igreja, que atuava no registro civil e na educação. Os **jesuítas**, que chegaram com Tomé de Sousa, evangelizaram os indígenas e fundaram colégios e aldeamentos, o que, ao mesmo tempo, os protegia da escravização pelos colonos e os submetia a um processo de aculturação. Assim, a colonização combinou exploração econômica, controle político e ação religiosa.'] },
 { h:'A economia açucareira e o engenho', p:[
  'A partir de meados do século XVI, a **produção de açúcar** tornou-se a principal atividade da colônia. Portugal já tinha experiência com o cultivo da cana nas ilhas atlânticas, como a Madeira, e o açúcar era um produto valioso na Europa. O Nordeste, em especial Pernambuco e Bahia, oferecia condições ideais: o solo fértil de **massapê**, o clima quente e úmido e a proximidade do litoral e dos portos. O financiamento vinha, em parte, de capitais holandeses, que também refinavam e distribuíam o açúcar na Europa. O Brasil se tornou o maior produtor mundial.',
  'A unidade produtiva era o **engenho**, formado pela casa-grande (moradia do senhor), pela senzala (alojamento dos escravizados), pela moenda, pela capela e pelos canaviais. A economia se baseava no tripé **latifúndio, monocultura e trabalho escravo**, e produzia para a **exportação**, de acordo com o **pacto colonial**, que garantia à metrópole o monopólio do comércio. Os **senhores de engenho** formavam a elite, com poder econômico e político, e a sociedade tinha **caráter patriarcal**, em torno da figura do senhor, que exercia autoridade sobre a família, os agregados e os escravos.',
  'Havia também os **lavradores de cana**, que cultivavam a cana em terras próprias ou arrendadas e a levavam para moer no engenho do senhor, e uma camada de trabalhadores livres, como feitores, artesãos e mestres de açúcar. A produção de açúcar envolvia etapas complexas: o corte da cana, a moagem, o cozimento do caldo em tachos, a purga e a secagem, para obter o açúcar branco e o mascavo. Outras atividades complementares eram a produção de alimentos, a criação de gado, que se interiorizou, e o cultivo do tabaco, usado no tráfico de escravos na África.'] },
 { h:'A escravidão indígena e africana', p:[
  'Inicialmente, os colonos recorreram à mão de obra indígena, por meio da escravização e da exploração, mas a resistência, as doenças e a oposição dos jesuítas, que defendiam a catequese, dificultaram essa solução. Houve guerras contra os povos nativos, como a Confederação dos Tamoios, e muitos foram mortos ou expulsos de suas terras. Os **bandeirantes**, paulistas, capturavam indígenas no interior para vendê-los como escravos. Com o tempo, a escravidão indígena diminuiu nas áreas açucareiras, e foi substituída pela de africanos, o que estava ligado à lucratividade do **tráfico negreiro**, que enriquecia a metrópole e os mercadores.',
  'A partir da segunda metade do século XVI, milhões de africanos, de regiões como Angola, Congo e Guiné, foram trazidos à força para o Brasil, e o país se tornou o maior destino do tráfico de escravos nas Américas. Submetidos a trabalho extenuante, castigos físicos e péssimas condições, os escravizados resistiram de várias formas: **fugas**, **revoltas**, sabotagens e a preservação de suas culturas e religiões. Os **quilombos**, comunidades de fugitivos, foram uma expressão central da resistência, e o maior deles, o **Quilombo dos Palmares**, na Serra da Barriga, na Capitania de Pernambuco, teve como grande líder **Zumbi**, morto em 1695.',
  'A escravidão marcou profundamente a sociedade brasileira, formada por uma enorme desigualdade social e pelo racismo estrutural. Os africanos e seus descendentes deram contribuições decisivas à cultura brasileira: na língua (muitas palavras de origem banto e iorubá), na culinária (o dendê, o vatapá, a feijoada), na música (o samba tem raízes africanas), na religião (o candomblé) e nas técnicas de trabalho. É essencial perceber que os escravizados não foram agentes passivos, mas sujeitos históricos que resistiram, negociaram e criaram formas próprias de vida e de cultura.'] },
 { h:'As invasões holandesas, a vida colonial e o legado açucareiro', p:[
  'O sucesso do açúcar atraiu a cobiça dos holandeses, que, durante a União Ibérica (1580 a 1640, quando Portugal esteve sob a coroa espanhola), foram proibidos de comerciar com a Espanha e perderam acesso ao produto. A **Companhia das Índias Ocidentais** invadiu a Bahia (1624) e, depois, Pernambuco (1630), onde permaneceu até 1654. O período mais marcante foi o governo de **Maurício de Nassau** (1637 a 1644), que modernizou o Recife, incentivou as artes e as ciências e adotou a tolerância religiosa. A reação dos senhores luso-brasileiros endividados levou à **Insurreição Pernambucana**, que expulsou os holandeses.',
  'A expulsão dos holandeses teve consequências econômicas: eles levaram o conhecimento do cultivo da cana às Antilhas (Caribe), onde passaram a produzir açúcar de modo mais barato e a competir com o Brasil, e a **crise do açúcar** se instalou a partir da segunda metade do século XVII, reduzindo a renda da colônia e abrindo espaço para outra atividade, a mineração. O Nordeste, antes o centro econômico, perdeu importância relativa. A produção de açúcar continuou, mas com menor peso, e o setor permaneceu como base de grande parte da economia agrária do Nordeste.',
  'A vida colonial girava em torno da fazenda e do engenho, e as cidades eram pouco desenvolvidas, com função administrativa e comercial. A sociedade era hierarquizada: no alto, os senhores; abaixo, os homens livres pobres e os artesãos; na base, os escravizados. A Igreja tinha enorme influência, e a cultura se expressava no **barroco** religioso. A herança desse período é duradoura: a concentração de terras, o modelo de exportação de produtos primários, a dependência externa e as desigualdades sociais, que marcam a história do Brasil até hoje e são retomadas em debates sobre reforma agrária e racismo.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a economia açucareira aparece em questões sobre o tripé latifúndio, monocultura e escravidão, as relações entre senhores e escravizados, as formas de resistência (quilombos), o pacto colonial e a sociedade patriarcal. Também são frequentes as imagens de engenhos (gravuras de Debret, Frans Post e Rugendas), os textos de cronistas, como Antonil, em Cultura e Opulência do Brasil, e a comparação com outras formas de trabalho e de exploração na América.',
  'Pontos de atenção: as capitanias hereditárias foram um sistema descentralizado, e o Governo-Geral buscou centralizar; o engenho era uma unidade complexa, não apenas uma fazenda de cana; a escravidão indígena foi substituída pela africana, também por interesses do tráfico; os quilombos eram espaços de resistência e organização, e não só de fuga; e a crise do açúcar se relaciona à concorrência antilhana. Cuidado com leituras que idealizam a "sociedade colonial", ignorando a violência e a desigualdade.',
  'Para revisar, esquematize: pau-brasil → capitanias → Governo-Geral → açúcar (engenho, latifúndio, escravidão) → invasões holandesas → crise do açúcar. Relacione ao pacto colonial e ao mercantilismo, estudados no tema anterior, e ao próximo, que trata da mineração e das revoltas coloniais, e que mostra como a economia e a sociedade colonial mudaram no século XVIII, deslocando o centro de gravidade da colônia para o Sudeste.'] }
]}
];
