/* História: textos corridos, temas 19 a 21 */
module.exports = [
{ t:'Primeira Guerra Mundial', txt:[
 { h:'As causas profundas da guerra', p:[
  'A **Primeira Guerra Mundial** (1914 a 1918) foi o maior conflito até então, e envolveu as principais potências europeias e outros países. Suas causas devem ser entendidas em um contexto de longo prazo, e não apenas pelo assassinato que serviu de estopim. A **Segunda Revolução Industrial** aumentou a competição entre os países industrializados por mercados consumidores, matérias-primas e territórios, e o **imperialismo** do século XIX, com a partilha da África e da Ásia (Conferência de Berlim, 1884 e 1885), gerou rivalidades coloniais, sobretudo entre Inglaterra, França e Alemanha.',
  'O **nacionalismo** exacerbado alimentou as tensões. A França desejava recuperar a **Alsácia-Lorena**, perdida para a Alemanha na guerra de 1870, em um sentimento conhecido como "revanchismo". Na região dos Bálcãs, o **pan-eslavismo**, apoiado pela Rússia, e o **pan-germanismo** disputavam influência, e povos sob domínio do Império Austro-Húngaro e do Otomano buscavam a independência. O **militarismo** impulsionou uma corrida armamentista, com o crescimento dos exércitos e das marinhas, em especial a rivalidade naval entre a Inglaterra e a Alemanha, e a ideia de que a guerra seria rápida e vantajosa.',
  'Esse quadro levou à formação de **alianças militares** opostas. A **Tríplice Aliança**, formada por Alemanha, Império Austro-Húngaro e Itália (que depois mudou de lado), e a **Tríplice Entente**, formada por França, Inglaterra e Rússia. O sistema de alianças, chamado de **paz armada**, tornou cada conflito local potencialmente um conflito geral, pois um ataque a um membro obrigava os outros a intervir. A região dos Bálcãs, conhecida como o "**barril de pólvora da Europa**", pela instabilidade, seria o local onde a faísca atingiria esse barril, em 1914.'] },
 { h:'O desenrolar do conflito: do atentado à guerra de trincheiras', p:[
  'Em **28 de junho de 1914**, o arquiduque **Francisco Ferdinando**, herdeiro do trono austro-húngaro, foi assassinado em Sarajevo, na Bósnia, por **Gavrilo Princip**, nacionalista sérvio. A Áustria-Hungria, com o apoio alemão, declarou guerra à Sérvia, a Rússia mobilizou seu exército em defesa dos sérvios, a Alemanha declarou guerra à Rússia e à França e invadiu a Bélgica, o que levou a Inglaterra a entrar no conflito. Em poucas semanas, as alianças arrastaram a Europa para a guerra. O Japão e, mais tarde, o Império Otomano e a Bulgária também entraram, e a guerra se estendeu a colônias e mares.',
  'Na frente ocidental, o avanço alemão foi detido na **Batalha do Marne** (1914), e a guerra se transformou em um conflito de **trincheiras**, linhas de fossos e arame farpado, em que os exércitos permaneciam por anos, quase imóveis, em condições desumanas, com lama, doenças e ratos. Batalhas como Verdun e Somme causaram centenas de milhares de mortes, sem grandes avanços. Foi uma **guerra total**, em que toda a economia e a sociedade foram mobilizadas, e em que se usaram armas modernas: metralhadoras, artilharia pesada, tanques, aviões, submarinos e **gases tóxicos**. As mulheres passaram a trabalhar nas fábricas, ocupando o lugar dos homens.',
  'Em 1917, dois fatos mudaram o rumo do conflito. Em abril, os **Estados Unidos** entraram na guerra, ao lado da Entente, após ataques de submarinos alemães a navios, entre eles os que transportavam cidadãos americanos, e por terem investimentos e empréstimos aos aliados. Em outubro, a **Revolução Russa** levou os bolcheviques ao poder, e a Rússia se retirou da guerra, em 1918, pelo **Tratado de Brest-Litovsk**, cedendo territórios à Alemanha. O apoio material e humano dos EUA fortaleceu a Entente, e a Alemanha, exausta, enfrentou revoltas internas e pediu o **armistício**, em novembro de 1918.'] },
 { h:'O fim da guerra e o Tratado de Versalhes', p:[
  'A guerra terminou com a vitória da **Entente** e a derrota das **Potências Centrais**. As consequências humanas foram enormes: cerca de 9 a 10 milhões de militares mortos e milhões de civis, além de feridos, mutilados e desaparecidos. A economia europeia ficou devastada, e as cidades e os campos foram destruídos. O continente perdeu a posição central na economia mundial, e os **Estados Unidos** passaram à condição de maior potência econômica e de credor das nações europeias. Essas perdas também marcaram a cultura e o pensamento do período, com o sentimento de desencanto com a ideia de progresso.',
  'Em 1919, as potências vencedoras assinaram o **Tratado de Versalhes**, que impôs à Alemanha condições duras: a **perda de territórios** (como a Alsácia-Lorena, devolvida à França, e áreas para a Polônia) e de todas as suas **colônias**, a **redução drástica do exército**, a **desmilitarização** da região da Renânia e o pagamento de pesadas **reparações de guerra**. A Alemanha foi obrigada a aceitar a "**cláusula da culpa**", que a considerava a única responsável pelo conflito. Essa humilhação gerou ressentimento e dificuldades econômicas, e foi um fator fundamental para a ascensão do nazismo.',
  'O mapa europeu foi redesenhado: desapareceram os impérios **Austro-Húngaro**, **Alemão**, **Russo** e **Otomano**, e surgiram novos países, como a Tchecoslováquia, a Iugoslávia, a Polônia e a Hungria, além da União Soviética. Os acordos de paz ignoraram, em muitos casos, as divisões étnicas e as aspirações dos povos, criando tensões futuras. Foi criada a **Liga das Nações** (1920), organização internacional para evitar novas guerras, mas ela foi pouco eficaz, pois os Estados Unidos não entraram nela e ela não tinha força militar para impor suas decisões.'] },
 { h:'A guerra e o Brasil, a Revolução Russa e o mundo do pós-guerra', p:[
  'O **Brasil** participou da guerra, depois de manter uma posição de neutralidade. Em 1917, após o afundamento de navios mercantes brasileiros por submarinos alemães, o governo declarou guerra à Alemanha. O envolvimento foi limitado: o país enviou uma missão médica, patrulhou o Atlântico e forneceu matérias-primas. A economia brasileira foi afetada pela queda das importações, o que estimulou a produção interna e a industrialização, e a demanda por produtos alimentícios e matérias-primas favoreceu certas exportações. A gripe espanhola (1918), que se espalhou com a guerra, matou milhares de brasileiros.',
  'A guerra estimulou a **Revolução Russa de 1917**. A participação na guerra gerou fome, mortes e insatisfação na Rússia. Em fevereiro (março, no calendário ocidental), uma revolução derrubou o czar Nicolau II. Em outubro (novembro), os **bolcheviques**, liderados por **Lênin**, tomaram o poder, instituíram um governo socialista e retiraram o país do conflito. O movimento inspirou revoltas e tentativas revolucionárias na Europa, e criou o temor, entre as potências capitalistas, de uma "revolução mundial", que moldou a política internacional entre as guerras e depois, durante a Guerra Fria.',
  'O pós-guerra foi um período de instabilidade. A Europa teve crise econômica, inflação, desemprego e agitações sociais, e a Alemanha, em especial, sofreu com a hiperinflação de 1923. Os **felizes anos 20** nos Estados Unidos, com consumo e prosperidade, terminariam com a crise de 1929. A insatisfação com os tratados de paz e a crise econômica favoreceram o crescimento de movimentos **autoritários** e **nacionalistas**, como o fascismo na Itália, o nazismo na Alemanha e outros regimes. Assim, a Primeira Guerra deixou problemas não resolvidos, que levaram a uma segunda guerra, duas décadas depois.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a Primeira Guerra Mundial aparece em questões sobre as causas (imperialismo, nacionalismo, militarismo e alianças), a guerra de trincheiras e o uso de novas tecnologias, a participação dos Estados Unidos, a Revolução Russa e o Tratado de Versalhes, relacionando-o com a ascensão do nazismo. Os enunciados incluem fotografias das trincheiras, cartazes de propaganda, trechos do Tratado e mapas da Europa antes e depois da guerra, e pedem a interpretação das mudanças territoriais e políticas.',
  'Pontos de atenção: o assassinato de Sarajevo foi o estopim, e não a causa; o sistema de alianças transformou um conflito regional em guerra mundial; a guerra foi total e envolveu a sociedade, com a presença das mulheres no trabalho; o Tratado de Versalhes humilhou a Alemanha e criou ressentimentos; os EUA saíram fortalecidos; e a Liga das Nações foi ineficaz. Muitas questões relacionam esse conflito com o surgimento de regimes totalitários, o que exige compreender a continuidade entre as duas guerras.',
  'Para revisar, esquematize: causas (imperialismo, nacionalismo, militarismo, alianças) → estopim (Sarajevo, 1914) → guerra de trincheiras → 1917 (entrada dos EUA e saída da Rússia) → 1918 (armistício) → 1919 (Versalhes) → consequências (novas fronteiras, crise econômica, Liga das Nações, Revolução Russa). Relacione o tema com o seguinte, a crise de 1929 e os totalitarismos, em que as consequências desse conflito ajudam a explicar a ascensão de regimes autoritários e o caminho para a Segunda Guerra Mundial.'] }
]},
{ t:'Crise de 1929 e totalitarismos', txt:[
 { h:'Os anos 20 nos Estados Unidos e a quebra da Bolsa', p:[
  'Após a Primeira Guerra Mundial, os **Estados Unidos** se tornaram a maior potência industrial e financeira. Na década de 1920, viveram um período de grande prosperidade, o American way of life, com produção em massa (fordismo), consumo de bens duráveis, como automóveis e eletrodomésticos, expansão do crédito e do mercado de ações. A economia crescia, e muitos acreditavam que a prosperidade seria permanente. Mas o crescimento escondia desequilíbrios: a **superprodução**, pois a indústria e a agricultura produziam mais do que o mercado podia consumir, em um contexto de concentração de renda e de queda do poder de compra da população.',
  'A Europa, em recuperação, passou a comprar menos dos EUA, e a produção se acumulou. Enquanto isso, a **especulação** na **Bolsa de Valores de Nova York** inflava o preço das ações, muitas compradas com crédito, na expectativa de lucros rápidos. Em **24 de outubro de 1929**, a "**quinta-feira negra**", os investidores começaram a vender as ações em massa, e em 29 de outubro, a Bolsa quebrou. Os preços despencaram, empresas e bancos faliram, e milhões de pessoas perderam seus investimentos e poupanças. A crise se espalhou, pois a economia mundial estava interligada, e os EUA retiraram os empréstimos concedidos à Europa.',
  'Os efeitos foram devastadores: a produção industrial caiu, o **desemprego** atingiu milhões, em alguns países, mais de um quarto da população ativa, a fome e a miséria aumentaram, os preços agrícolas desabaram e o comércio internacional diminuiu. Nos países produtores de matérias-primas, como o Brasil, a queda dos preços do café arruinou os produtores e gerou crise política. A **Grande Depressão** se estendeu pela década de 1930 e mostrou os limites do **liberalismo econômico**, que defendia a não intervenção do Estado na economia, e abriu espaço para novas ideias.'] },
 { h:'O New Deal e o keynesianismo', p:[
  'Para enfrentar a crise, o presidente **Franklin Delano Roosevelt**, eleito em 1932, lançou o **New Deal** ("novo acordo"), um conjunto de medidas de **intervenção do Estado** na economia. O governo regulamentou o sistema financeiro, e criou mecanismos de proteção dos depósitos bancários, estabeleceu o controle da produção agrícola e industrial, financiou **obras públicas**, como a de barragens e estradas, que geraram empregos, e criou direitos trabalhistas e **previdência social**, como o seguro-desemprego e a aposentadoria, e o salário mínimo. Esse programa procurou recuperar a economia e o consumo, e dar proteção social à população.',
  'Essas medidas se aproximavam das ideias do economista britânico **John Maynard Keynes**, que defendia que, em tempos de crise, o Estado deveria **estimular a demanda**, com investimentos e gastos públicos, para reativar a economia, em oposição à crença na capacidade de autorregulação do mercado. O **keynesianismo** orientou as políticas econômicas de muitos países nas décadas seguintes, e é a base do chamado **Estado de bem-estar social** (welfare state), que se consolidou, sobretudo na Europa, após a Segunda Guerra, com serviços públicos de saúde, educação e previdência.',
  'O New Deal teve resultados parciais: reduziu o desemprego e estabilizou o sistema bancário, mas a economia só se recuperou plenamente com a **produção de guerra**, a partir de 1939. Mesmo assim, deixou um legado duradouro: a ideia de que o Estado tem responsabilidade sobre a economia e o bem-estar social. Em outros países, a resposta à crise tomou rumos diferentes: na Inglaterra e na França, políticas de proteção; na Alemanha, na Itália e no Japão, regimes **autoritários** e militaristas ganharam força, o que se liga ao tema seguinte.'] },
 { h:'O fascismo na Itália e o nazismo na Alemanha', p:[
  'O **totalitarismo** é um regime em que o Estado busca controlar todos os aspectos da vida pública e privada, com partido único, líder carismático, propaganda de massas, censura, repressão policial e culto à nação. Surgiu na Itália, com o **fascismo**, liderado por **Benito Mussolini**. Após a Primeira Guerra, a Itália vivia crise econômica, desemprego e frustração por não ter recebido os territórios que esperava. Mussolini criou os Fasci di Combattimento e, em 1922, após a **Marcha sobre Roma**, tornou-se primeiro-ministro. Instaurou uma ditadura, com o culto ao **Duce**, o nacionalismo, o militarismo, o anticomunismo e o corporativismo.',
  'Na Alemanha, a derrota na guerra, as humilhações do Tratado de Versalhes, a hiperinflação de 1923 e o desemprego após 1929 criaram o ambiente para o **nazismo**, o Partido Nacional-Socialista dos Trabalhadores Alemães, liderado por **Adolf Hitler**. Em seu livro Mein Kampf ("Minha Luta"), Hitler defendeu o ódio aos judeus, o **antissemitismo**, a superioridade da "raça ariana", o **espaço vital** (Lebensraum) para a expansão e o anticomunismo. Em 1933, foi nomeado chanceler, e, após o incêndio do Reichstag, concentrou todos os poderes, extinguindo os demais partidos. Passou a ser chamado de **Führer** ("guia").',
  'O regime nazista impôs o controle total da sociedade: a polícia política (**Gestapo**) e as tropas **SS** perseguiam opositores, a propaganda de **Joseph Goebbels** manipulava a população, os livros considerados "degenerados" eram queimados, e a juventude era doutrinada. As **leis de Nuremberg** (1935) retiraram a cidadania dos judeus e proibiram o casamento entre judeus e "arianos", e a **Noite dos Cristais** (1938) foi um pogrom violento. A economia foi reorientada para o rearmamento. A Alemanha rompeu o Tratado de Versalhes, remilitarizou a Renânia, anexou a Áustria e os Sudetos, e preparou a guerra.'] },
 { h:'Stalinismo, militarismo japonês, franquismo e salazarismo', p:[
  'Na **União Soviética**, após a morte de Lênin (1924), **Josef Stálin** assumiu o poder e implantou um regime totalitário. Adotou **planos quinquenais** de industrialização acelerada, a **coletivização forçada** da agricultura, que causou fome e milhões de mortes (como na Ucrânia), a repressão política com os **Grandes Expurgos** (1936 a 1938), em que dirigentes e cidadãos comuns foram presos, exilados nos campos de trabalho (gulags) ou executados, e um forte culto à personalidade. A economia foi planificada e estatizada, e o país se tornou uma potência industrial e militar, mas a custo de enorme violência.',
  'No **Japão**, a crise de 1929 e a falta de recursos fortaleceram os **militares** e o nacionalismo expansionista, com o culto ao imperador. O país invadiu a **Manchúria** (1931) e a China (1937), buscando matérias-primas e mercados. Em 1936, assinou com a Alemanha o Pacto Anticomintern, que depois se transformou, com a Itália, no **Eixo** (Roma-Berlim-Tóquio). Na **Espanha**, a Guerra Civil (1936 a 1939) opôs os republicanos aos nacionalistas do general **Francisco Franco**, apoiados por Hitler e Mussolini, e terminou com a vitória de Franco, que governou o país até 1975. Em **Portugal**, o **Estado Novo** de **Salazar** foi um regime autoritário (1933 a 1974).',
  'Os regimes totalitários tinham, assim, características em comum: partido único, culto ao líder, propaganda e censura, repressão aos opositores, nacionalismo, controle da educação e da cultura, e uso da violência. Apresentavam diferenças ideológicas: o fascismo e o nazismo eram de **extrema direita**, anticomunistas e racistas (no caso nazista), enquanto o stalinismo era comunista, com economia estatal. O **liberalismo** e a **democracia** estavam em crise, e muitos buscaram nesses regimes uma saída diante da instabilidade, o que mostra como as crises econômicas e sociais podem favorecer o autoritarismo, uma lição frequentemente retomada.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM cobra a crise de 1929 e os totalitarismos com frequência, em questões que pedem a identificação das causas da crise (superprodução e especulação), seus efeitos globais (inclusive no Brasil, com a crise do café) e as soluções (New Deal e keynesianismo). Também cobra as características dos regimes totalitários, a propaganda, o antissemitismo e a perseguição, a ascensão de Hitler e a relação com o Tratado de Versalhes. Os enunciados trazem cartazes de propaganda, fotografias, charges e trechos de discursos e de livros.',
  'Pontos de atenção: a crise teve origem nos EUA, mas atingiu o mundo, pela interdependência econômica; o New Deal foi uma intervenção do Estado, que se inspirou em Keynes; o totalitarismo se baseia no controle total, com propaganda e terror; o nazismo uniu nacionalismo, racismo e antissemitismo; o fascismo italiano foi o primeiro regime desse tipo; o stalinismo foi totalitário, mas de esquerda; e a crise econômica ajudou a levar Hitler ao poder. Atenção à propaganda: as imagens oficiais não correspondem à realidade, e as questões costumam pedir uma leitura crítica.',
  'Para revisar, esquematize: anos 20 (prosperidade) → 1929 (quebra) → Grande Depressão → New Deal (EUA) → totalitarismos (Itália, Alemanha, URSS, Japão, Espanha, Portugal) → rearmamento e expansão → Segunda Guerra. Associe cada regime ao seu líder e às suas características, e relacione a crise de 1929 à de 1930 no Brasil, estudada na República Velha. Esse tema leva diretamente à Segunda Guerra Mundial, o conflito que decorreu da combinação entre a crise, os regimes autoritários e as tensões herdadas de 1918.'] }
]},
{ t:'Segunda Guerra Mundial', txt:[
 { h:'As causas e o início da guerra', p:[
  'A **Segunda Guerra Mundial** (1939 a 1945) foi o conflito mais devastador da história, com cerca de 60 milhões de mortos, entre militares e civis. Suas causas se ligam ao **Tratado de Versalhes**, que humilhou a Alemanha, à **crise de 1929**, à ascensão dos **regimes totalitários** (nazismo, fascismo e militarismo japonês), ao fracasso da **Liga das Nações** e à **política de apaziguamento** (appeasement) de Inglaterra e França, que cederam a Hitler para evitar a guerra. O expansionismo dos regimes do Eixo, com o rearmamento, as anexações e as invasões, foi minando a ordem estabelecida em 1919.',
  'Antes da guerra, a Alemanha remilitarizou a Renânia (1936), anexou a Áustria (**Anschluss**, 1938) e os Sudetos, território tcheco, com a concordância das potências na **Conferência de Munique** (1938), e ocupou o resto da Tchecoslováquia. A Itália invadiu a Etiópia (1935) e a Albânia. O Japão avançava sobre a China. Em agosto de 1939, a Alemanha e a União Soviética assinaram o **Pacto Germano-Soviético** (ou Molotov-Ribbentrop), de não agressão, que incluía um acordo secreto de divisão da Polônia, o que permitiu a Hitler atacar sem temer uma guerra em duas frentes.',
  'Em **1º de setembro de 1939**, a Alemanha invadiu a **Polônia**, com a tática da **guerra-relâmpago** (Blitzkrieg), que combinava o uso de tanques, aviação e infantaria motorizada. A Inglaterra e a França declararam guerra à Alemanha, e começou o conflito na Europa. Em 1940, os alemães ocuparam a Dinamarca, a Noruega, a Holanda, a Bélgica e a **França**, que se rendeu. A Inglaterra, sob o comando de **Winston Churchill**, resistiu aos bombardeios alemães na Batalha da Inglaterra. A Itália, de Mussolini, aliou-se à Alemanha, e o conflito se estendeu ao Mediterrâneo e à África.'] },
 { h:'A expansão da guerra e a virada aliada', p:[
  'Em junho de 1941, Hitler rompeu o pacto e invadiu a **União Soviética** (Operação Barbarossa), e abriu uma frente imensa. O exército alemão avançou rapidamente, mas foi detido no inverno, diante de Moscou, e sofreu a derrota decisiva em **Stalingrado** (1942 a 1943), que marcou o início da recuperação soviética. Em **dezembro de 1941**, o **Japão** atacou a base americana de **Pearl Harbor**, no Havaí, e os **Estados Unidos** entraram na guerra, ao lado dos **Aliados** (Inglaterra, URSS, EUA, França Livre, China e outros) contra o **Eixo** (Alemanha, Itália e Japão). A guerra se tornou realmente mundial, com frentes na Europa, no Pacífico, na Ásia e na África.',
  'A partir de 1942 e 1943, a situação mudou. Os aliados venceram a **Batalha de El Alamein** (norte da África), invadiram a Itália (1943), e Mussolini foi deposto. Em **6 de junho de 1944** (o **Dia D**), tropas aliadas desembarcaram na **Normandia**, na França, abrindo uma frente ocidental, e libertaram Paris. Pelo leste, o Exército Vermelho avançava sobre a Alemanha. A produção industrial dos EUA, que forneceu armas e suprimentos aos aliados, e a mobilização total de recursos foram decisivas. Em abril de 1945, Hitler se suicidou em Berlim, e a Alemanha se rendeu em **8 de maio de 1945**.',
  'No Pacífico, a guerra continuou contra o Japão. Os americanos venceram as batalhas navais de Midway e de Iwo Jima e Okinawa, e, para forçar a rendição japonesa, lançaram **bombas atômicas** sobre as cidades de **Hiroshima** (6 de agosto de 1945) e **Nagasaki** (9 de agosto), matando centenas de milhares de pessoas. O Japão se rendeu em **2 de setembro de 1945**, encerrando a guerra. O uso da bomba atômica, pela primeira e única vez em um conflito, inaugurou a **era nuclear** e permanece como tema de debate ético e histórico, entre os que o consideram necessário para encerrar a guerra e os que o consideram desnecessário e desumano.'] },
 { h:'O Holocausto e os crimes de guerra', p:[
  'Um dos aspectos mais graves da guerra foi o **Holocausto** (ou Shoá), o extermínio sistemático de cerca de **6 milhões de judeus** pelo regime nazista, além de milhões de outras vítimas, como ciganos (roma e sinti), pessoas com deficiência, homossexuais, opositores políticos, testemunhas de Jeová e prisioneiros de guerra soviéticos. A perseguição teve etapas: a discriminação legal, o confinamento em **guetos**, as execuções em massa por unidades móveis e, a partir de 1942, a chamada "**Solução Final**", com a deportação para **campos de concentração e de extermínio**, como Auschwitz-Birkenau, Treblinka e Sobibor, onde foram usadas câmaras de gás.',
  'O Holocausto foi planejado e executado com o uso da burocracia, da tecnologia e da propaganda do Estado, o que levou pensadores como **Hannah Arendt** a discutir a "**banalidade do mal**": pessoas comuns, ao cumprir ordens sem refletir, podiam participar de crimes gigantescos. Houve também resistência, como a revolta do Gueto de Varsóvia (1943), e atos de solidariedade de pessoas que esconderam judeus, os "justos entre as nações". Outros crimes marcaram a guerra: os massacres de civis, os trabalhos forçados, os bombardeios de cidades, como Dresden e Londres, e as atrocidades cometidas pelo Japão, como o Massacre de Nanquim.',
  'Após a guerra, os principais líderes nazistas foram julgados pelo **Tribunal de Nuremberg** (1945 a 1946), que estabeleceu o princípio de que indivíduos podem ser responsabilizados por **crimes contra a humanidade**, mesmo que cumpram ordens, criando bases do direito internacional penal. Em 1948, foi aprovada a **Declaração Universal dos Direitos Humanos**, pela recém-criada ONU, e a Convenção para a Prevenção e Repressão do Crime de Genocídio. A memória do Holocausto tornou-se um alerta contra o racismo, a intolerância e o autoritarismo, e é um tema recorrente nas provas, que valorizam o respeito aos direitos humanos.'] },
 { h:'As consequências: a ONU, a divisão do mundo e o Brasil na guerra', p:[
  'O fim da guerra transformou a ordem mundial. A Europa ficou devastada, e perdeu a posição central, e os **Estados Unidos** e a **União Soviética** emergiram como **superpotências**, rivais em um novo conflito, a **Guerra Fria**. Em 1945, foi fundada a **Organização das Nações Unidas** (ONU), para promover a paz, a segurança e a cooperação internacional, com o Conselho de Segurança, em que as potências vencedoras têm assento permanente e direito a veto. A Alemanha foi dividida em zonas de ocupação, e depois em duas partes (Ocidental e Oriental), e Berlim também foi dividida. O Japão foi ocupado pelos EUA.',
  'Houve também mudanças econômicas e políticas: os Estados Unidos financiaram a reconstrução da Europa Ocidental por meio do **Plano Marshall** (1947), o que também ampliou sua influência, e foram criados os acordos de **Bretton Woods** (1944), com o FMI e o Banco Mundial, que organizaram o sistema financeiro. O fim da guerra acelerou o **processo de descolonização** da Ásia e da África, pois as metrópoles europeias enfraquecidas não conseguiram manter seus domínios. Também se consolidou o **Estado de bem-estar social** na Europa, e a União Europeia tem origem nos esforços de integração do pós-guerra, para evitar novos conflitos.',
  'O **Brasil** participou da guerra ao lado dos aliados. Inicialmente neutro, e com Vargas negociando com os dois lados, declarou guerra ao Eixo em 1942, após os ataques alemães a navios brasileiros. Obteve dos Estados Unidos o financiamento para a **Companhia Siderúrgica Nacional**, em Volta Redonda, em troca da cessão de bases militares no Nordeste. Em 1944, enviou a **Força Expedicionária Brasileira** (FEB), com cerca de 25 mil soldados, à Itália, onde participou de batalhas como a de **Monte Castelo**. A contradição de lutar contra o fascismo, tendo uma ditadura no país, contribuiu para a queda de Vargas, em 1945.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Segunda Guerra Mundial é um tema recorrente no ENEM. As questões trazem fotografias dos campos de concentração, cartazes de propaganda, trechos de discursos e de documentos, mapas das fases do conflito e dados de mortos, e pedem a análise das causas (Versalhes, crise de 1929, totalitarismos, apaziguamento), do Holocausto, do uso das armas nucleares, das consequências (ONU, Guerra Fria, descolonização) e da participação do Brasil (FEB, CSN). Frequentemente, abordam a discussão sobre direitos humanos e a memória dos crimes.',
  'Pontos de atenção: a guerra começou em 1939, com a invasão da Polônia, e a participação de EUA e URSS mudou seu rumo; a vitória aliada dependeu do esforço soviético e da produção industrial americana; o Holocausto foi um genocídio planejado, com a participação do Estado; o Tribunal de Nuremberg criou o conceito de crimes contra a humanidade; a ONU e a Declaração Universal dos Direitos Humanos nasceram dessa experiência; e a guerra reorganizou o mundo em dois blocos. Evite explicações simplistas que atribuam a guerra a uma só pessoa, sem considerar as condições políticas e econômicas.',
  'Para revisar, esquematize: causas (Versalhes, crise, totalitarismos, apaziguamento) → 1939 (Polônia) → 1940 (França) → 1941 (URSS e Pearl Harbor) → 1943 (Stalingrado) → 1944 (Dia D, FEB) → 1945 (rendição alemã, Hiroshima e Nagasaki) → consequências (ONU, superpotências, Plano Marshall, descolonização). Esse tema se conecta à Guerra Fria, assunto do próximo, em que as duas superpotências disputaram a hegemonia mundial por décadas, sem se enfrentarem diretamente, mas com impactos em todos os continentes.'] }
]}
];
