/* História: textos corridos, temas 10 a 12 */
module.exports = [
{ t:'Revolução Industrial', txt:[
 { h:'As condições que tornaram possível a Revolução Industrial', p:[
  'A **Revolução Industrial** foi o processo de transformação econômica e social em que a produção, antes artesanal e manual, passou a ser realizada por **máquinas** em **fábricas**. Começou na **Inglaterra**, na segunda metade do século XVIII (por volta de 1760), e se espalhou, no século XIX, pela Europa, pelos Estados Unidos e pelo Japão. Não foi um acontecimento súbito, mas uma mudança gradual, com várias fases. Representou uma das maiores rupturas da história humana, comparável à Revolução Agrícola do Neolítico, por alterar o modo de produzir, de viver e de pensar.',
  'A Inglaterra reunia condições favoráveis. Havia **capital acumulado** pelo comércio colonial, pelo tráfico de escravos e pelo mercantilismo. Os **cercamentos** (enclosures) dos campos, que transformaram as terras comunais em propriedades privadas, expulsaram os camponeses, que migraram para as cidades e formaram uma abundante **mão de obra** disponível. Havia grandes reservas de **carvão e ferro**, fontes de energia e matéria-prima, e a posição insular, com bons portos, facilitava o comércio. Um mercado interno e externo amplo, o domínio dos mares e a estabilidade política, após a Revolução Gloriosa (1688), completavam o quadro.',
  'O ambiente intelectual também contribuiu: a Revolução Científica e o Iluminismo estimulavam a experimentação e a busca de inovações, e o liberalismo favorecia a livre iniciativa. A burguesia inglesa, com poder político, investia em novas técnicas, e as invenções se multiplicaram. Com a **Revolução Agrícola** (rotação de culturas, novas ferramentas), houve aumento da produção de alimentos e crescimento populacional. Esses elementos se combinaram, e explicam por que a industrialização começou ali, e não em outro lugar, uma pergunta típica de provas.'] },
 { h:'As fases e as inovações técnicas', p:[
  'A **Primeira Revolução Industrial** (1760 a 1850, aproximadamente) teve como base o **carvão**, o **ferro** e o **vapor**, e como setor principal a indústria **têxtil**. Entre as invenções, estão a **lançadeira volante** (John Kay), a **máquina de fiar** (spinning jenny, de Hargreaves) e o **tear mecânico** (Cartwright), que aumentaram muito a produtividade. O **motor a vapor**, aperfeiçoado por **James Watt**, fornecia energia constante às fábricas, sem depender de rios ou ventos. Também surgiram a **locomotiva** (Stephenson) e o **barco a vapor**, que revolucionaram os transportes e integraram os mercados.',
  'A **Segunda Revolução Industrial** (a partir da segunda metade do século XIX, até o início do XX) incorporou novas fontes de energia, como a **eletricidade** e o **petróleo**, novos materiais, como o **aço**, e novos setores: siderurgia, química, automobilística e elétrica. Foram criados o **motor a explosão**, o telégrafo e o telefone, a lâmpada elétrica e a produção em série. Passou a se desenvolver em outros países, como Alemanha, Estados Unidos e Japão, que disputaram a liderança com a Inglaterra. Surgiram grandes empresas, **monopólios** e **trustes**, e a união entre bancos e indústrias, o **capitalismo financeiro**.',
  'Alguns autores falam de uma **Terceira Revolução Industrial**, a partir de meados do século XX, marcada pela **eletrônica**, pela informática, pela automação, pelas telecomunicações e pela biotecnologia, e até de uma **Quarta**, ligada à inteligência artificial, à internet das coisas e à robótica. Em cada uma, as inovações alteram a forma de produzir e de trabalhar, ampliam a produtividade e geram novos desafios sociais e ambientais. Perceber essa continuidade ajuda a entender questões que comparam a Revolução Industrial com as transformações tecnológicas atuais.'] },
 { h:'Mudanças sociais: a classe operária, a urbanização e o movimento operário', p:[
  'A industrialização consolidou o **capitalismo industrial** e a divisão da sociedade em duas classes principais: a **burguesia industrial**, dona dos meios de produção (fábricas, máquinas, matérias-primas), e o **proletariado**, que vendia sua força de trabalho em troca de salário. As fábricas impuseram uma nova **disciplina**: horários rígidos, ritmo ditado pelas máquinas e divisão do trabalho, em que cada operário executava uma etapa, o que aumentou a produtividade, mas tirou do trabalhador o controle sobre o processo e o produto, e o tornou facilmente substituível.',
  'As condições de vida eram duras. A jornada podia chegar a 14 ou 16 horas, os salários eram baixos, os ambientes eram insalubres e perigosos, e o **trabalho infantil e feminino** era comum, pois a mão de obra era mais barata. As cidades industriais, como Manchester e Liverpool, cresceram rapidamente sem planejamento, com moradias precárias, falta de saneamento, doenças e poluição. A **urbanização** acelerada mudou os costumes, os hábitos e as relações sociais, e a oposição entre o campo e a cidade aumentou.',
  'Os trabalhadores reagiram. Primeiro, por meio do **ludismo** (1811 a 1812), movimento em que operários destruíam as máquinas, vistas como causa do desemprego, e depois, de modo mais organizado, por meio de **sindicatos** (trade unions), de greves e do movimento **cartista**, que reivindicava o voto universal masculino. Ao longo do século XIX, conquistaram leis que limitaram a jornada e o trabalho infantil. Surgiram também as ideias de **socialismo**: o socialismo utópico (Owen, Fourier, Saint-Simon) e o socialismo científico, de **Marx e Engels**, que analisaram o capitalismo e propuseram a revolução proletária.'] },
 { h:'Consequências econômicas, ambientais e globais', p:[
  'A Revolução Industrial transformou a economia mundial. A **produção em massa** reduziu os preços e ampliou o consumo, mas gerou a necessidade de **mercados consumidores e de matérias-primas**, o que impulsionou o **imperialismo** (ou neocolonialismo) do século XIX, com a partilha da África e da Ásia pelas potências industriais. A **divisão internacional do trabalho** passou a colocar alguns países como produtores de manufaturados e outros como fornecedores de matérias-primas e importadores, estrutura que marcou a América Latina, inclusive o Brasil, e que gerou dependência econômica.',
  'No plano **ambiental**, a queima de carvão, e depois de petróleo, aumentou a emissão de poluentes e de gases de efeito estufa, e a expansão das fábricas e das cidades degradou rios, solos e o ar. Os efeitos de longo prazo incluem as mudanças climáticas, que tornam essa revolução um marco do que alguns chamam de **Antropoceno**, a era em que a ação humana se tornou uma força geológica. A industrialização também aumentou o consumo de recursos naturais, exigindo hoje uma discussão sobre desenvolvimento sustentável.',
  'Também houve avanços: a produtividade cresceu, e com ela a riqueza, a expectativa de vida, a oferta de bens e os meios de transporte e de comunicação. A **educação**, a **saúde pública** e os direitos trabalhistas se ampliaram, em grande parte graças às lutas sociais. O impacto na Inglaterra foi seguido pelo mundo, e na América Latina, a industrialização foi tardia e dependente. A Revolução Industrial é, portanto, um processo ambíguo, que trouxe progresso material e, ao mesmo tempo, desigualdade, exploração e degradação ambiental, aspectos que o ENEM costuma explorar.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM aborda a Revolução Industrial em questões sobre as condições dos trabalhadores, a divisão do trabalho, a urbanização, o movimento operário, o ludismo, o imperialismo e os impactos ambientais. Os textos incluem relatos de operários, gravuras de fábricas, trechos de Engels (A Situação da Classe Trabalhadora na Inglaterra) e de Marx, charges e comparações com o trabalho atual, como a precarização, a automação e a uberização. A pergunta central costuma ser a relação entre transformações técnicas e mudanças sociais.',
  'Pontos de atenção: a Inglaterra foi a pioneira por reunir capital, mão de obra, carvão e mercado; a primeira fase foi do vapor e da indústria têxtil, e a segunda, de eletricidade e petróleo; a divisão do trabalho e a disciplina das fábricas mudaram a relação com o tempo; o ludismo foi uma reação às máquinas, e os sindicatos e o cartismo foram formas de organização; o imperialismo foi uma consequência da necessidade de mercados e matérias-primas. Ao comparar épocas, atente para as semelhanças (precarização, jornadas longas) e as diferenças (legislação trabalhista).',
  'Para revisar, esquematize: causas (cercamentos, capital, carvão, mercado) → inovações (lançadeira, tear, máquina a vapor, locomotiva) → novas classes (burguesia e proletariado) → problemas (jornadas longas, trabalho infantil, urbanização desordenada) → reações (ludismo, sindicatos, socialismo) → consequências (imperialismo, divisão internacional do trabalho, poluição). Esse tema conecta-se ao Iluminismo e à Revolução Francesa (as revoluções políticas e econômicas do período), e ao imperialismo e às guerras mundiais, assunto dos temas seguintes.'] }
]},
{ t:'Independência do Brasil', txt:[
 { h:'O Brasil Reino Unido e as tensões com Portugal', p:[
  'A transferência da Corte portuguesa para o Rio de Janeiro, em 1808, e a elevação do Brasil a **Reino Unido** a Portugal e Algarves, em 1815, mudaram o estatuto do país: a colônia deixou de ser apenas fornecedora de produtos para se tornar sede do governo. As medidas de D. João, como a abertura dos portos, a criação de instituições e a vinda de artistas e cientistas, favoreceram as elites do Centro-Sul, mas criaram também um custo: a manutenção da Corte exigia impostos altos, e muitos produtores de outras regiões, como o Nordeste, sentiam-se prejudicados.',
  'Em 1815, a queda de Napoleão terminou a ameaça que motivara a vinda da Corte, mas D. João permaneceu no Brasil. Em Portugal, a insatisfação era grande: o país estava arruinado pelas guerras, dominado pela presença inglesa e sem o rei, e os comerciantes portugueses sentiam falta do monopólio colonial. Em 1820, a **Revolução Liberal do Porto** exigiu o retorno do rei, a elaboração de uma constituição e a volta do Brasil à condição de colônia, o que significava recuperar o controle comercial. Em 1821, D. João VI voltou a Portugal, deixando seu filho **D. Pedro** como príncipe regente.',
  'As **Cortes de Lisboa**, a assembleia constituinte portuguesa, tomaram medidas que feriam os interesses brasileiros: exigiram o retorno de D. Pedro, subordinaram as províncias diretamente a Lisboa e tentaram restabelecer o monopólio comercial. Esses atos fortaleceram o movimento a favor da autonomia, em especial entre os grandes proprietários rurais e os comerciantes do Centro-Sul, que não queriam perder as vantagens obtidas desde 1808. As ideias liberais circulavam, e as elites brasileiras buscavam um caminho que garantisse a autonomia sem abalar a ordem social e a escravidão.'] },
 { h:'Do Dia do Fico ao Grito do Ipiranga', p:[
  'Pressionado a voltar para Portugal, D. Pedro decidiu permanecer. Em **9 de janeiro de 1822**, o **Dia do Fico**, declarou "se é para o bem de todos e felicidade geral da nação, diga ao povo que fico". O gesto foi apoiado pelas elites e desagradou às Cortes. Em seguida, D. Pedro formou um novo ministério, chefiado por **José Bonifácio de Andrada e Silva**, que se tornou a principal liderança política do processo, e determinou que as ordens de Lisboa só teriam validade com o seu "cumpra-se". Em junho, convocou uma **Assembleia Constituinte** para o Brasil.',
  'Em agosto de 1822, as Cortes declararam nulos os atos de D. Pedro e ameaçaram enviar tropas. O príncipe, que estava em viagem a São Paulo, recebeu as notícias às margens do riacho do **Ipiranga**, e proclamou a independência, em **7 de setembro de 1822**, no episódio conhecido como **Grito do Ipiranga**. Em 12 de outubro, foi aclamado imperador, com o título de **D. Pedro I**, e coroado em 1º de dezembro. O processo foi, portanto, conduzido por um membro da família real portuguesa, e as elites mantiveram a estrutura social.',
  'Esse caráter explica as características do processo brasileiro, que se diferenciou das independências hispano-americanas, que resultaram em repúblicas fragmentadas. No Brasil, a **monarquia** foi mantida, o território se manteve unificado e a **escravidão** continuou. Houve, em geral, **continuidade** em relação à ordem colonial, com mudanças na superfície, e não uma revolução social. Por isso muitos historiadores falam em uma independência "conservadora", construída "pelo alto", ainda que ela não tenha se dado sem conflito, como se verá a seguir.'] },
 { h:'As guerras de independência e o reconhecimento', p:[
  'Ao contrário do que sugere a imagem tradicional de uma independência "pacífica", houve **lutas armadas** para garantir a autonomia, principalmente nas províncias em que havia tropas portuguesas e interesses ligados a Portugal. Na **Bahia**, as lutas se estenderam por mais de um ano, e terminaram em 2 de julho de 1823, data comemorada até hoje na Bahia, com a expulsão das tropas portuguesas. Houve combates também no **Maranhão**, no **Piauí**, no **Pará** e na **Cisplatina**, e a participação popular foi significativa, inclusive de escravizados, índios e mulheres, como **Maria Quitéria** e **Joana Angélica**.',
  'A guerra foi possível graças a recursos e comandantes estrangeiros, como o almirante inglês **Lord Cochrane**, que comandou a esquadra brasileira, e à adesão de parte das elites. Para consolidar a independência, era preciso o **reconhecimento internacional**. Os Estados Unidos reconheceram o Brasil em 1824, e Portugal o fez em 1825, por meio de um tratado intermediado pela **Inglaterra**, em que o Brasil se comprometia a pagar uma **indenização** de 2 milhões de libras, em parte financiada por um empréstimo inglês, o que inaugurou a **dívida externa** brasileira.',
  'A Inglaterra obteve, em troca de seu apoio, vantagens econômicas, como a renovação dos tratados comerciais de 1810, que taxavam em 15% as mercadorias inglesas, e o compromisso brasileiro de acabar com o **tráfico de escravos** em prazo determinado, o que atendia aos interesses ingleses de ampliar o mercado de consumidores livres. O Brasil, assim, passou de uma situação de dependência de Portugal para uma de dependência da Inglaterra, o que mostra que a independência política não significou autonomia econômica. Essa leitura é importante para as questões que pedem a análise crítica do processo.'] },
 { h:'A Constituinte, o Primeiro Reinado e a Constituição de 1824', p:[
  'A **Assembleia Constituinte**, aberta em maio de 1823, reunia representantes das elites, divididos entre o "partido brasileiro", que defendia limites ao poder do imperador, e o "partido português", favorável a um poder forte. O projeto de Constituição, conhecido como "**Constituição da Mandioca**", porque o voto era vinculado à renda, calculada em alqueires de mandioca, previa a diminuição dos poderes do imperador e restringia o voto, e foi criticado por D. Pedro. Em novembro de 1823, o imperador **dissolveu a Constituinte**, em um ato autoritário (a "Noite da Agonia"), prendeu e exilou deputados, entre eles José Bonifácio.',
  'Em 1824, D. Pedro I **outorgou** uma Constituição elaborada por um Conselho de Estado de sua confiança, uma Carta imposta, e não discutida pelos representantes. Ela estabelecia uma **monarquia hereditária e unitária**, o **voto censitário** (por renda) e indireto, a religião católica como oficial e, o principal, o **Poder Moderador**, exclusivo do imperador, que lhe dava o direito de nomear senadores, dissolver a Câmara, convocar eleições e escolher ministros, e o colocava acima dos demais poderes. Esse poder foi o eixo do sistema político imperial e foi muito criticado pelos liberais.',
  'O autoritarismo de D. Pedro e a crise econômica geraram oposição. A reação mais forte foi a **Confederação do Equador** (1824), em Pernambuco, um movimento republicano e separatista, que também se opunha à Constituição outorgada e foi duramente reprimido, com a execução de líderes, como Frei Caneca. A perda da **Cisplatina**, na guerra contra as Províncias Unidas do Rio da Prata (1825 a 1828), que deu origem ao Uruguai, aumentou o desgaste. A morte de D. João VI, a questão da sucessão em Portugal e os conflitos com a elite levaram D. Pedro I a abdicar, em 1831, em favor do filho, ainda criança.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Independência do Brasil aparece no ENEM em questões que pedem a interpretação do processo: causas (vinda da Corte, Revolução do Porto, Cortes), características (conduzida por D. Pedro, com participação das elites, manutenção da monarquia e da escravidão), as lutas armadas e as relações com a Inglaterra. As questões podem trazer a pintura de Pedro Américo, "Independência ou Morte", e perguntar sobre a construção da memória e do mito do "herói", ou trechos da Constituição de 1824, com ênfase no Poder Moderador.',
  'Pontos de atenção: a independência foi um processo, e não um dia isolado; houve guerras, sobretudo na Bahia; o reconhecimento internacional teve custo (indenização e tratados comerciais com a Inglaterra); a Constituição de 1824 foi outorgada e criou o Poder Moderador; o voto era censitário e excluía a maioria da população; a escravidão foi mantida. Observe as expressões que mostram o caráter elitista e conservador do processo, e as que ressaltam a participação popular e as resistências.',
  'Para revisar, monte uma linha do tempo: 1808 (vinda da Corte), 1815 (Reino Unido), 1820 (Revolução do Porto), 1821 (volta de D. João), 9 de janeiro de 1822 (Fico), 7 de setembro de 1822 (independência), 1823 (dissolução da Constituinte), 1824 (Constituição e Confederação do Equador), 1825 (reconhecimento) e 1831 (abdicação). Em seguida, estude o Brasil Império, que mostra como o novo país se organizou, e os conflitos que marcaram o Período Regencial e o Segundo Reinado.'] }
]},
{ t:'Brasil Império', txt:[
 { h:'O Período Regencial e as revoltas provinciais', p:[
  'Com a abdicação de D. Pedro I, em 1831, seu filho, D. Pedro II, tinha apenas cinco anos, e o país foi governado por **regentes**, no período de 1831 a 1840, chamado de **Período Regencial**. Foi um momento de grande instabilidade, com disputas entre grupos políticos: os **liberais moderados**, que queriam descentralizar o poder; os **restauradores** (caramurus), que desejavam o retorno de D. Pedro I; e os **exaltados**, defensores de reformas mais radicais. Foram aprovados o **Código de Processo Criminal** (1832) e o **Ato Adicional** (1834), que criou as Assembleias Legislativas provinciais e deu mais autonomia às províncias.',
  'Nesse contexto ocorreram diversas **revoltas provinciais**, que expressavam o descontentamento com o centralismo e com a situação econômica e social. Na **Cabanagem** (Pará, 1835 a 1840), a população pobre, formada por índios, mestiços e negros, tomou o poder e sofreu forte repressão, com milhares de mortos. Na **Sabinada** (Bahia, 1837 a 1838), setores médios defenderam uma república provisória. Na **Balaiada** (Maranhão, 1838 a 1841), vaqueiros, camponeses e escravos se rebelaram contra a miséria. Na **Revolta dos Malês** (Bahia, 1835), escravizados muçulmanos tentaram uma insurreição, que foi reprimida.',
  'A mais longa foi a **Guerra dos Farrapos** (ou Revolução Farroupilha, Rio Grande do Sul, 1835 a 1845), liderada por estancieiros descontentes com a política de impostos sobre o charque, que proclamaram a República Rio-Grandense e a República Juliana, em Santa Catarina. O movimento terminou com a negociação, e os líderes obtiveram vantagens. O governo imperial conseguiu manter o território unido com a repressão militar e com acordos com as elites, e, em 1840, o **Golpe da Maioridade** antecipou a coroação de D. Pedro II, aos 14 anos, para estabilizar o sistema político.'] },
 { h:'O Segundo Reinado: política e parlamentarismo', p:[
  'O **Segundo Reinado** (1840 a 1889), sob D. Pedro II, foi um período de relativa estabilidade política, centralização do poder e crescimento econômico. O sistema político se baseava em dois partidos, o **Liberal** e o **Conservador**, que tinham pouca diferença de ideias e representavam elites semelhantes, e se alternavam no poder, conforme a vontade do imperador, que usava o **Poder Moderador** para dissolver a Câmara e chamar o partido adversário. Dizia-se, com ironia, que "nada se parecia mais com um **saquarema** (conservador) do que um **luzia** (liberal) no poder".',
  'Em 1847, foi criado o cargo de **presidente do Conselho de Ministros**, inaugurando um **parlamentarismo** peculiar, "às avessas", em que o chefe de governo era nomeado pelo imperador, e não pela maioria parlamentar. As eleições eram fraudadas pelo controle do voto, por meio do **coronelismo** e do "voto de cabresto", e o voto era censitário, o que restringia a participação a poucos. A **Lei Saraiva** (1881) introduziu a eleição direta, mas aumentou a exigência de renda e excluiu os analfabetos, reduzindo ainda mais o eleitorado. O regime mantinha a escravidão e a concentração de terras.',
  'A **Lei de Terras** (1850) determinou que as terras devolutas só poderiam ser adquiridas pela **compra**, e não mais pela posse, o que dificultava o acesso à terra dos pobres e dos futuros imigrantes e libertos, e fortaleceu o latifúndio. No mesmo ano, a **Lei Eusébio de Queirós** proibiu o tráfico atlântico de escravos, sob pressão inglesa, o que liberou capitais para outras atividades, e incentivou o investimento em ferrovias, bancos e indústrias, como mostra a atuação do Barão de Mauá. O Império também enfrentou as **Revoltas liberais** e a **Revolta Praieira** (Pernambuco, 1848).'] },
 { h:'A economia cafeeira, a imigração e a Guerra do Paraguai', p:[
  'O **café**, introduzido no Brasil no século XVIII, tornou-se o principal produto de exportação no século XIX, a partir do Vale do Paraíba, no Rio de Janeiro, e depois no **Oeste Paulista**, com solos de **terra roxa**, muito férteis. Os **barões do café** formaram uma nova elite, com grande poder econômico e político. No início, a produção usava mão de obra **escrava**; com o fim do tráfico e a decadência do Vale do Paraíba, os fazendeiros paulistas passaram a adotar o **trabalho livre**, por meio da **imigração**, em especial de italianos, que trabalhavam como colonos, no sistema de **parceria**, e depois de alemães, japoneses e outros povos.',
  'A expansão cafeeira estimulou a construção de **ferrovias**, a urbanização, o surgimento de bancos e de indústrias e a abertura de portos, como o de Santos. O Brasil era, então, o maior produtor mundial de café, e a economia dependia desse produto, o que a deixava vulnerável às oscilações do mercado externo. Outras atividades também tinham peso: o açúcar no Nordeste, a borracha na Amazônia (a partir do final do século) e o algodão. A presença do capital inglês, nos empréstimos, nas ferrovias e no comércio, mantinha a dependência externa, em continuidade com o período anterior.',
  'A **Guerra do Paraguai** (1864 a 1870), em que o Brasil, a Argentina e o Uruguai (Tríplice Aliança) enfrentaram o Paraguai, de Solano López, foi o maior conflito armado da América do Sul. Resultou na destruição do Paraguai, com perdas humanas enormes, e deixou o Brasil com grande **dívida**, mas com um **exército fortalecido**, que passou a ter peso político e a se queixar do tratamento dado pela monarquia. A participação de escravizados, libertados para lutar, mostrou a contradição entre a escravidão e o discurso de liberdade, e o episódio colaborou para a crise do regime.'] },
 { h:'A crise do Império e o fim da monarquia', p:[
  'A partir da década de 1870, a monarquia entrou em crise por vários motivos. A **Questão Militar**, conflitos entre o governo e o Exército, que se sentia desprestigiado, e pelo qual circulavam as ideias positivistas e republicanas, aproximou os militares dos republicanos. A **Questão Religiosa** (1872 a 1875), um choque entre o governo e a Igreja, por causa da punição de bispos que haviam condenado a maçonaria, afastou parte do clero do imperador. O **movimento republicano**, organizado a partir do Manifesto Republicano (1870), ganhou adeptos entre os fazendeiros do Oeste Paulista, que se sentiam sub-representados.',
  'O **movimento abolicionista**, com a participação de intelectuais e de lideranças negras, como José do Patrocínio, Luís Gama, André Rebouças e Joaquim Nabuco, pressionava o fim da escravidão, que ocorreu em 1888 sem indenização aos proprietários, o que retirou o apoio de muitos fazendeiros à monarquia. A **Lei Áurea** foi assinada pela princesa Isabel em 13 de maio de 1888. O império perdeu a base de sustentação da elite escravista, a Igreja e o Exército, e já não contava com a sustentação que o mantinha de pé.',
  'Em **15 de novembro de 1889**, um golpe militar, liderado pelo marechal **Deodoro da Fonseca**, depôs o gabinete e proclamou a **República**, sem participação popular significativa. O imperador e a família real foram enviados à Europa. Como disse o jornalista Aristides Lobo, o povo teria assistido "bestializado" à proclamação. A passagem do Império para a República, assim, foi feita pelas elites, com a presença do Exército e de setores cafeeiros, e manteve estruturas de desigualdade, abrindo caminho para o período da República Velha, estudado a seguir, em que as oligarquias dominaram a política.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O Brasil Império aparece no ENEM com frequência. Os temas mais cobrados são o Poder Moderador e o sistema político (partidos Liberal e Conservador, parlamentarismo às avessas, voto censitário), as revoltas regenciais, a economia do café e a imigração, a Lei de Terras e o fim do tráfico, a Guerra do Paraguai, o abolicionismo e a crise da monarquia. Os enunciados trazem textos da época, charges e pinturas que exigem a leitura do contexto histórico.',
  'Pontos de atenção: durante a Regência houve muitas revoltas, mas elas tinham motivos e composições sociais diferentes; o parlamentarismo do Império era "às avessas", pois o imperador escolhia o chefe de governo; a Lei de Terras (1850) tornou a terra uma mercadoria e restringiu o acesso a ela; a imigração foi uma resposta à escassez de mão de obra e a um projeto de "branqueamento"; a Guerra do Paraguai fortaleceu o Exército; e a república foi proclamada por um golpe militar. Observe o papel dos escravizados e dos libertos na história.',
  'Para revisar, esquematize: Regência (revoltas) → Golpe da Maioridade → Segundo Reinado (política, café, imigração, Lei de Terras, Guerra do Paraguai) → crises (Militar, Religiosa, abolição, república) → 1889. Associe o tema ao anterior (independência) e ao seguinte (abolição e pós-abolição), que trata de forma aprofundada do processo de fim da escravidão e das condições de vida dos libertos, questão central para a compreensão da sociedade brasileira.'] }
]}
];
