/* História: textos corridos, temas 7 a 9 */
module.exports = [
{ t:'Brasil Colônia: mineração e revoltas', txt:[
 { h:'A descoberta do ouro e a corrida para as Minas Gerais', p:[
  'Com a crise do açúcar e o desejo da Coroa de encontrar metais preciosos, as expedições ao interior ganharam importância. Os **bandeirantes** paulistas, que já percorriam o sertão em busca de indígenas para escravizar e de riquezas, encontraram ouro de aluvião na região das Minas Gerais, na década de 1690. A notícia provocou uma verdadeira **corrida do ouro**: milhares de pessoas, de Portugal e de diversas partes da colônia, migraram para a região, atraídas pela promessa de enriquecimento. Surgiram arraiais que se transformaram em vilas e cidades, como Vila Rica (atual Ouro Preto), Mariana e Sabará.',
  'Mais tarde, descobriram-se ouro e diamantes em Goiás, Mato Grosso e no Arraial do Tijuco (Diamantina). A exploração dos diamantes foi submetida a um controle ainda maior, com a criação do **Distrito Diamantino**. A atividade mineradora atraiu uma população numerosa e provocou conflitos, como a **Guerra dos Emboabas** (1707 a 1709), entre os paulistas, que se consideravam donos das minas pela descoberta, e os "emboabas", forasteiros, principalmente portugueses. Com a vitória dos emboabas, a Coroa reforçou o controle sobre a região e criou a Capitania de Minas Gerais.',
  'A mineração mudou o eixo econômico e demográfico da colônia. O Sudeste ganhou importância, e a capital foi transferida de Salvador para o **Rio de Janeiro**, em 1763, por ser o porto de escoamento do ouro. Houve um grande aumento da população, do comércio interno e da urbanização, e o abastecimento da região mineradora estimulou a pecuária no Sul e a produção agrícola em outras áreas, ligando regiões antes isoladas. A mão de obra era, em grande parte, de **africanos escravizados**, que trabalhavam em condições duras na extração do ouro, nos rios e nas minas.'] },
 { h:'O controle da Coroa: tributos e fiscalização', p:[
  'Para garantir sua parte nas riquezas, a Coroa portuguesa organizou uma administração rigorosa. Criou as **Intendências das Minas**, que fiscalizavam a extração e a cobrança de tributos. O principal imposto era o **quinto**, que correspondia a 20% de todo o ouro extraído, e devia ser pago nas **Casas de Fundição**, onde o ouro era transformado em barras e marcado com o selo real. O ouro em pó e as pepitas que circulassem sem esse selo eram considerados contrabando, e o comércio era vigiado para evitar o "ouro de contrabando", que escapava da cobrança.',
  'Quando a produção começou a cair, a partir da metade do século XVIII, e os pagamentos do quinto não atingiam a cota mínima de 100 arrobas anuais, a Coroa estabeleceu a **derrama**: a cobrança forçada dos impostos atrasados, com a apreensão de bens, de toda a população da região, para completar o valor. Também cobrava a **capitação** (imposto por escravo), as **entradas** (taxas sobre mercadorias que entravam em Minas) e os dízimos. O peso dos tributos e a rigidez da fiscalização geraram um enorme descontentamento entre os moradores, que se somou à crise da mineração.',
  'A sociedade mineradora tinha características diferentes da açucareira. Era mais **urbana**, **diversificada** e **móvel**, com uma camada intermediária de comerciantes, artesãos, tropeiros, funcionários, militares e profissionais liberais, e com maior possibilidade, ainda que limitada, de ascensão social. Os escravizados tinham, em alguns casos, a chance de comprar a **alforria** (a liberdade). A riqueza financiou o **barroco mineiro**, estilo artístico marcado pela suntuosidade das igrejas, com os trabalhos de **Aleijadinho** (Antônio Francisco Lisboa) e do pintor Mestre Ataíde, que se tornaram símbolos do patrimônio cultural brasileiro.'] },
 { h:'Revoltas coloniais: nativismo e emancipação', p:[
  'Ao longo do período colonial, ocorreram vários movimentos de contestação, que podem ser classificados em **nativistas**, que se opunham a abusos da metrópole ou a grupos específicos, sem propor a separação do Brasil, e **emancipacionistas** (ou separatistas), que propunham a independência. Entre os nativistas estão a **Revolta de Beckman** (Maranhão, 1684), contra o monopólio comercial e a atuação dos jesuítas; a **Guerra dos Mascates** (Pernambuco, 1710), entre os senhores de engenho de Olinda e os comerciantes portugueses do Recife; a **Revolta de Filipe dos Santos** (Vila Rica, 1720), contra as Casas de Fundição; e a **Guerra dos Emboabas**.',
  'Os movimentos emancipacionistas surgiram no final do século XVIII, influenciados pelo **Iluminismo**, pela independência dos Estados Unidos (1776) e pela crise do sistema colonial. A **Inconfidência Mineira** (1789), em Vila Rica, foi planejada por membros da elite local, como poetas, advogados, militares e proprietários, entre eles Tomás Antônio Gonzaga, Cláudio Manuel da Costa e **Joaquim José da Silva Xavier, o Tiradentes**, e se opunha à derrama e à dominação portuguesa, propondo uma república. A conspiração foi denunciada, os envolvidos foram presos, e Tiradentes, condenado à forca em 1792, tornou-se herói nacional.',
  'A **Conjuração Baiana** (ou Revolta dos Alfaiates, 1798), em Salvador, teve caráter mais popular: reuniu alfaiates, soldados, artesãos, ex-escravos e pessoas pobres, e defendia ideias avançadas, como o fim da escravidão, a igualdade racial, a república e a liberdade de comércio. Foi duramente reprimida, e os líderes de origem humilde, como Manuel Faustino e Lucas Dantas, foram executados, enquanto os de elite foram poupados. Comparar a Inconfidência Mineira (elitista, ligada aos impostos) e a Conjuração Baiana (popular, com pautas sociais) é um clássico das provas.'] },
 { h:'Reformas pombalinas, crise do sistema colonial e transferência da Corte', p:[
  'No século XVIII, Portugal estava em dificuldade econômica, e dependente da Inglaterra, e o ministro **Marquês de Pombal** (1750 a 1777), sob o reinado de D. José I, adotou reformas inspiradas no **despotismo esclarecido**. Buscou fortalecer o Estado e a economia: criou companhias de comércio, incentivou a agricultura e a manufatura, aumentou o controle fiscal, expulsou os jesuítas (1759) e reformou a educação, e transferiu a capital da colônia para o Rio de Janeiro. Também proibiu a escravização de indígenas e incentivou sua integração. Essas medidas aumentaram o controle sobre a colônia e acentuaram tensões.',
  'No final do século, com o esgotamento das minas, a economia da colônia entrou em declínio, ao mesmo tempo em que as ideias liberais se difundiam. A **Revolução Industrial** inglesa precisava de novos mercados, e o sistema colonial exclusivista, com monopólio comercial, tornava-se um obstáculo. A **Revolução Francesa** e as guerras napoleônicas agravaram a situação de Portugal. Em 1807, Napoleão decretou o **Bloqueio Continental**, proibindo os países europeus de comerciar com a Inglaterra, e Portugal, aliado inglês, ficou em posição difícil.',
  'Diante da ameaça de invasão francesa, o príncipe regente **D. João** decidiu transferir a **Corte portuguesa para o Brasil**, em 1807, com a proteção da marinha inglesa. A chegada ao Rio de Janeiro, em 1808, trouxe mudanças profundas: a **abertura dos portos às nações amigas**, que beneficiou principalmente a Inglaterra, a revogação da proibição de manufaturas, a criação do Banco do Brasil, da Imprensa Régia, da Biblioteca Real e da Academia Militar, entre outros. Em 1815, o Brasil foi elevado a **Reino Unido** de Portugal e Algarves, deixando de ser colônia, e preparando o terreno para a independência.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Mineração e revoltas coloniais aparecem no ENEM em questões sobre o controle fiscal da metrópole (quinto, derrama), a mudança do eixo econômico para o Sudeste, a sociedade mineradora e a arte barroca, e a distinção entre revoltas nativistas e emancipacionistas. Também são cobrados trechos de documentos da época, como os Autos da Devassa da Inconfidência, e imagens, como a do enforcamento de Tiradentes, que pedem a interpretação de como a memória nacional foi construída.',
  'Pontos de atenção: o quinto era 20% do ouro e a derrama era a cobrança forçada dos atrasados; a Inconfidência Mineira foi um movimento de elite, inspirado no Iluminismo e na independência dos EUA; a Conjuração Baiana teve forte participação popular e propôs o fim da escravidão; a vinda da Corte, em 1808, alterou o estatuto do Brasil; e a figura de Tiradentes foi valorizada pela República, que o transformou em herói. Atenção para não confundir revoltas nativistas, que não propunham independência, com as emancipacionistas.',
  'Para revisar, esquematize: ouro em Minas → Casas de Fundição, quinto e derrama → arte barroca e urbanização → revoltas (Emboabas, Beckman, Mascates, Filipe dos Santos) → Inconfidência Mineira e Conjuração Baiana → Pombal → Bloqueio Continental e vinda da Corte. Relacione o tema com o Iluminismo e a Revolução Francesa, que serão estudados em seguida, pois explicam as ideias que inspiraram os movimentos emancipacionistas e as independências americanas.'] }
]},
{ t:'Iluminismo', txt:[
 { h:'Contexto e características do Iluminismo', p:[
  'O **Iluminismo** (ou Ilustração) foi um movimento intelectual, científico e filosófico que se desenvolveu na Europa, sobretudo na França, ao longo do século XVIII, e por isso este é chamado de "Século das Luzes". Seus pensadores defendiam o uso da **razão** como instrumento de conhecimento e de transformação da sociedade, em oposição à tradição, à superstição e ao dogmatismo. O lema, formulado pelo filósofo Immanuel Kant, era "**Sapere aude**", ou seja, "ousa saber": ter coragem de usar o próprio entendimento, sem a tutela de outros.',
  'O movimento se apoiou na **Revolução Científica** do século XVII, de Galileu, Newton e outros, que mostrou que a natureza obedecia a leis que a razão podia descobrir. Também se inspirou no racionalismo de Descartes e no empirismo de Locke e Bacon. Em um contexto de crescimento da burguesia e de crise do Antigo Regime, em que a sociedade estamental, o absolutismo monárquico e os privilégios da nobreza e do clero eram questionados, o Iluminismo forneceu uma base teórica para a crítica social e política, e circulou em salões, cafés, jornais e livros.',
  'Entre as ideias centrais, estão a defesa da **liberdade individual**, da **igualdade perante a lei**, da **tolerância religiosa**, da **propriedade privada**, do **progresso** e da **educação** como meio de emancipação. Criticavam o **absolutismo**, o poder da Igreja, a escravidão (alguns), as desigualdades de nascimento e o mercantilismo. Cabe lembrar que os iluministas não formavam um grupo homogêneo: havia diferenças entre eles quanto à forma de governo, ao papel do Estado e à religião, e muitos defendiam reformas conduzidas por monarcas, e não revoluções.'] },
 { h:'Os principais pensadores políticos', p:[
  '**John Locke**, inglês, defendeu que os seres humanos têm **direitos naturais**: vida, liberdade e propriedade, e que o governo é um contrato e deve proteger esses direitos. Se o governante os violasse, o povo teria direito de resistir e de substituí-lo. Suas ideias inspiraram a Revolução Gloriosa inglesa (1688) e a independência dos Estados Unidos. **Montesquieu**, francês, autor de O Espírito das Leis, propôs a **separação dos poderes** em Executivo, Legislativo e Judiciário, que se equilibrariam para impedir o abuso, e esse princípio é a base de muitas constituições modernas.',
  '**Jean-Jacques Rousseau**, nascido em Genebra, em O Contrato Social, defendeu a **soberania popular**: o poder pertence ao povo, e o governo deve expressar a "vontade geral". Criticou a propriedade privada como fonte de desigualdade, e inspirou os setores mais radicais da Revolução Francesa. **Voltaire**, francês, lutou pela **liberdade de pensamento e de expressão** e pela tolerância religiosa, criticando o fanatismo e os privilégios da Igreja. A ele é atribuída a ideia de defender o direito de expressão mesmo de quem discordasse de suas opiniões, embora a frase famosa seja de outro autor.',
  'Outros nomes importantes foram **Denis Diderot** e **D\'Alembert**, organizadores da **Enciclopédia** (1751 a 1772), obra que reuniu conhecimentos de várias áreas e difundiu as ideias iluministas. **Adam Smith**, escocês, em A Riqueza das Nações (1776), defendeu o **liberalismo econômico**: a economia funcionaria melhor com a liberdade de mercado, regulada pela "mão invisível", com pouca intervenção do Estado, em oposição ao mercantilismo. **Cesare Beccaria** criticou a tortura e a pena de morte e defendeu penas proporcionais, e **Kant** discutiu a autonomia da razão e da moral.'] },
 { h:'Despotismo esclarecido e a difusão das ideias', p:[
  'Alguns monarcas absolutistas adotaram ideias iluministas para modernizar seus Estados sem abrir mão do poder, em um modelo chamado de **despotismo esclarecido**, resumido na fórmula "tudo para o povo, nada pelo povo". Entre eles, estão **Frederico II**, da Prússia, **Catarina II**, da Rússia, **José II**, da Áustria, e, em Portugal, o Marquês de Pombal. Esses governantes incentivaram reformas administrativas, educacionais, econômicas e jurídicas, reduziram o poder da Igreja e promoveram a tolerância, mas mantiveram as hierarquias sociais e a monarquia absoluta.',
  'As ideias iluministas circularam amplamente, graças à imprensa, às sociedades literárias, às academias e aos salões, e atravessaram o Atlântico. Influenciaram a **independência dos Estados Unidos** (1776), com a Declaração de Independência, de Thomas Jefferson, que proclama a vida, a liberdade e a busca da felicidade como direitos inalienáveis; a **Revolução Francesa** (1789), com a Declaração dos Direitos do Homem e do Cidadão; e as independências da América Latina, nas quais líderes como Simón Bolívar se inspiraram nos ideais de liberdade, igualdade e soberania popular.',
  'No Brasil, o Iluminismo chegou principalmente por meio dos estudantes que frequentavam universidades europeias, como Coimbra, e dos livros que circulavam clandestinamente, e inspirou movimentos como a **Inconfidência Mineira**. A tensão entre o ideal de **liberdade** e a manutenção da **escravidão** nas colônias é uma contradição frequentemente analisada: muitos defensores da liberdade conviviam com a escravidão, e foram os próprios escravizados, como no Haiti, que levaram as ideias de liberdade e de igualdade às últimas consequências, em uma revolução bem-sucedida, em 1791 a 1804.'] },
 { h:'Legado e críticas ao Iluminismo', p:[
  'O legado do Iluminismo é central para o mundo contemporâneo. A noção de **direitos humanos**, a separação dos poderes, a democracia representativa, a liberdade de expressão, a laicidade do Estado, a tolerância religiosa e a ideia de **progresso** têm origem nesse movimento. A Constituição brasileira de 1988 e as constituições de outros países trazem esses princípios. A valorização da ciência, da educação pública e do pensamento crítico também são heranças iluministas, e muitos debates atuais sobre liberdade, igualdade e justiça se baseiam nele.',
  'Contudo, o Iluminismo recebeu **críticas**. Alguns apontam seu caráter **eurocêntrico**, pois tomava a Europa como modelo de civilização, e serviu para justificar o colonialismo e a dominação de outros povos, em nome do "progresso" e da "civilização". Outros criticam a confiança excessiva na razão, que ignoraria as dimensões emocionais e culturais. Pensadores da **Escola de Frankfurt**, como Adorno e Horkheimer, argumentaram que a razão instrumental, voltada à dominação da natureza e dos seres humanos, pode levar a novas formas de barbárie. Essas discussões aparecem em provas de Filosofia e Sociologia.',
  'Também se criticou o fato de que os direitos proclamados eram, na prática, **restritos**: as mulheres, os escravizados e os pobres muitas vezes ficaram de fora da cidadania. A pensadora **Olympe de Gouges** escreveu a Declaração dos Direitos da Mulher e da Cidadã (1791), mostrando que a igualdade proclamada não incluía as mulheres. Assim, o Iluminismo é, ao mesmo tempo, **fonte de ideais universais** e **objeto de crítica** por suas limitações, e é importante analisá-lo nessa dupla perspectiva, como o ENEM costuma fazer.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O Iluminismo é um tema frequente no ENEM, por sua ligação com a cidadania e os direitos. As questões trazem trechos de Locke, Montesquieu, Rousseau, Voltaire e Kant, e pedem para identificar a ideia central (separação dos poderes, contrato social, soberania popular, tolerância, liberdade de expressão). Também cobram a relação entre o Iluminismo, as revoluções e as independências, a crítica ao absolutismo e ao mercantilismo, e a atualidade desses princípios.',
  'Para identificar o autor, observe a ideia: **direitos naturais e governo como contrato** (Locke); **separação dos poderes** (Montesquieu); **vontade geral e soberania popular** (Rousseau); **tolerância e liberdade de expressão** (Voltaire); **liberalismo econômico** (Adam Smith); **razão e autonomia** (Kant). Atenção: o despotismo esclarecido adotou ideias iluministas sem abolir a monarquia absoluta. E lembre-se de que o Iluminismo inspirou tanto os que queriam reformas moderadas quanto os que queriam revoluções.',
  'Para revisar, faça um quadro com autor, país, obra e ideia principal. Associe cada ideia a uma instituição atual: separação dos poderes e Constituição; soberania popular e eleições; liberdade de expressão e imprensa; tolerância e laicidade; e livre mercado e economia capitalista. Esse tema prepara diretamente o próximo, a Revolução Francesa, que colocou em prática, de forma intensa e radical, muitos dos ideais iluministas, e é um dos assuntos mais recorrentes das provas.'] }
]},
{ t:'Revolução Francesa', txt:[
 { h:'A crise do Antigo Regime na França', p:[
  'No final do século XVIII, a França vivia sob o **Antigo Regime**, caracterizado pelo absolutismo monárquico, pela sociedade estamental e pelo mercantilismo. A população se dividia em três **estados**: o **Primeiro Estado** (clero) e o **Segundo Estado** (nobreza), que somavam cerca de 3% da população, mas possuíam privilégios, como isenção de impostos e acesso aos cargos mais altos; e o **Terceiro Estado**, que reunia cerca de 97% dos habitantes: burgueses, camponeses, artesãos e trabalhadores urbanos, sobre quem recaía o peso dos impostos. A burguesia, mesmo rica e instruída, não tinha poder político proporcional à sua importância.',
  'A situação se agravou com uma **crise econômica e financeira**. A monarquia, sob Luís XVI, gastava muito com a corte luxuosa e com as guerras, entre elas o apoio à independência dos Estados Unidos, e acumulava dívidas. Más colheitas elevaram o preço do pão e aumentaram a fome nas cidades e no campo. As tentativas de reforma tributária esbarraram na resistência dos nobres e do clero. As ideias iluministas, que criticavam os privilégios e o absolutismo, circulavam entre a burguesia e os intelectuais, e alimentavam a insatisfação com a ordem vigente.',
  'Em 1789, para tentar resolver a crise, o rei convocou os **Estados Gerais**, assembleia que não se reunia desde 1614. A disputa sobre a forma de votação (por estado, que garantia a maioria aos privilegiados, ou por cabeça, que favorecia o Terceiro Estado) levou os representantes do Terceiro Estado a se declarar **Assembleia Nacional**, em junho, e a jurar redigir uma constituição (Juramento da Quadra de Tênis). O rei reagiu mobilizando tropas, e o povo de Paris, temendo um golpe, tomou a **Bastilha**, prisão símbolo do absolutismo, em **14 de julho de 1789**, marco inicial da Revolução.'] },
 { h:'A fase da Monarquia Constitucional e a Declaração dos Direitos', p:[
  'Após a Bastilha, a revolta se espalhou pelo campo (o "Grande Medo") e levou à abolição dos privilégios feudais e senhoriais, na noite de 4 de agosto de 1789. Em 26 de agosto, a Assembleia aprovou a **Declaração dos Direitos do Homem e do Cidadão**, documento que proclamou **liberdade, igualdade e fraternidade**, e afirmou que os homens nascem e permanecem livres e iguais em direitos, e que a soberania pertence à nação. Foi um marco na história dos direitos humanos, inspirado no Iluminismo e na independência americana, embora tenha deixado de fora as mulheres e os escravizados das colônias.',
  'A **Assembleia Nacional Constituinte** (1789 a 1791) fez reformas importantes: dividiu o território em departamentos, confiscou bens da Igreja e aprovou a **Constituição Civil do Clero**, que submetia os padres ao Estado, o que gerou conflito com os católicos. A **Constituição de 1791** estabeleceu uma **monarquia constitucional**, com a separação dos poderes e o voto **censitário**, restrito aos mais ricos, o que excluía grande parte da população. O rei, porém, tentou fugir em 1791, mas foi capturado em Varennes, o que desgastou sua imagem e fortaleceu os grupos que defendiam a república.',
  'Em seguida, a **Assembleia Legislativa** (1791 a 1792) esteve dividida entre diversos grupos: os **girondinos**, representantes da alta burguesia, moderados, e os **jacobinos**, da pequena burguesia e dos setores populares, mais radicais. A guerra contra a Áustria e a Prússia, que temiam a expansão da Revolução, e a pressão popular dos **sans-culottes** (artesãos e trabalhadores de Paris) radicalizaram o processo. Em agosto de 1792, o palácio real foi invadido, a monarquia foi suspensa e, em setembro, foi proclamada a **República**, inaugurando a fase da Convenção.'] },
 { h:'A Convenção, o Terror e o Diretório', p:[
  'A **Convenção Nacional** (1792 a 1795) abriu a fase mais radical. O rei **Luís XVI** foi julgado e guilhotinado, em janeiro de 1793, e a guerra com as monarquias europeias aumentou. Os jacobinos, liderados por **Robespierre**, **Danton** e **Marat**, assumiram o poder, e adotaram medidas como o **tabelamento de preços** (lei do máximo), o fim da escravidão nas colônias (1794), a educação pública e a Constituição de 1793, que previa o voto universal masculino. Para defender a Revolução dos inimigos internos e externos, foi criado o **Comitê de Salvação Pública**, que concentrou poderes.',
  'Esse período, de 1793 a 1794, ficou conhecido como **Terror**: milhares de pessoas, acusadas de serem contrarrevolucionárias, foram julgadas por tribunais revolucionários e executadas na guilhotina, entre elas a rainha Maria Antonieta. A violência atingiu também antigos aliados, como Danton, e levou ao desgaste do regime. Em julho de 1794 (o **Golpe de 9 Termidor**), Robespierre foi derrubado e executado, e o poder passou aos setores moderados da burguesia, no episódio chamado de **Reação Termidoriana**, que pôs fim à fase radical da Revolução.',
  'Em 1795, uma nova Constituição criou o **Diretório**, um governo de cinco diretores, que expressava os interesses da alta burguesia, restabeleceu o voto censitário e enfrentou instabilidade política, problemas econômicos e a ameaça de grupos realistas e jacobinos. Para manter a ordem, o Diretório dependia cada vez mais do exército, e de generais vitoriosos nas guerras, como **Napoleão Bonaparte**. Em 1799, o **Golpe de 18 Brumário** derrubou o Diretório e instalou o Consulado, com Napoleão como primeiro-cônsul, encerrando o ciclo revolucionário e abrindo a Era Napoleônica.'] },
 { h:'A Era Napoleônica e o legado da Revolução', p:[
  'Napoleão Bonaparte consolidou o poder, tornando-se cônsul vitalício e, em 1804, **Imperador dos Franceses**. Seu governo preservou conquistas burguesas da Revolução, como a igualdade civil e o fim dos privilégios feudais, mas restringiu liberdades políticas. Criou o **Código Napoleônico** (1804), que garantiu a propriedade privada, a igualdade perante a lei e a liberdade de contrato, e influenciou legislações de muitos países, inclusive o direito civil brasileiro. Reorganizou a administração e a educação, e fundou o Banco da França. A França expandiu seus domínios por meio das guerras, e levou, junto, ideias revolucionárias.',
  'A derrota na campanha da Rússia (1812) e a resistência de outras potências levaram ao declínio de Napoleão, que foi derrotado em **Waterloo** (1815) e exilado na ilha de Santa Helena. O **Congresso de Viena** (1814 a 1815), dominado por potências conservadoras, tentou restaurar a ordem anterior à Revolução, com base nos princípios da **legitimidade** (retorno das dinastias), do **equilíbrio** entre as potências e da **repressão** a movimentos liberais, e a Santa Aliança reforçou esse esforço. Mas as ideias de liberdade e de nacionalismo continuaram a se espalhar e provocaram novas revoluções no século XIX.',
  'O **legado da Revolução Francesa** é imenso. Ela extinguiu o Antigo Regime na França e inspirou lutas por liberdade e igualdade em todo o mundo. Estabeleceu o conceito moderno de **cidadania**, a ideia de soberania popular e os direitos universais do homem. Também deu origem ao vocabulário político da modernidade: direita e esquerda (pela disposição dos deputados na Assembleia), república e nação. Para a burguesia, representou a conquista do poder político; para as camadas populares, mostrou que a participação coletiva pode mudar a ordem, mas também deixou o debate sobre os limites da violência política.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Revolução Francesa é um dos temas mais frequentes de História no ENEM. Aparece em questões que pedem para identificar as causas (crise do Antigo Regime e do Terceiro Estado), as fases (Assembleia, Convenção, Terror, Diretório e Napoleão), os grupos políticos (girondinos, jacobinos e sans-culottes), os símbolos (Bastilha, guilhotina), a Declaração dos Direitos do Homem e do Cidadão e os ideais de liberdade, igualdade e fraternidade. Também há questões sobre sua influência em outros movimentos, inclusive as independências da América Latina.',
  'Pontos de atenção: a Revolução não foi um evento único, mas um processo com fases diferentes e conflitos entre grupos; a burguesia liderou a primeira fase e os setores populares ganharam força na segunda; o Terror foi uma resposta à guerra e às ameaças internas, e é debatido quanto à violência; Napoleão preservou parte das conquistas, mas concentrou poder. Em questões com imagens (A Liberdade guiando o povo, de Delacroix), identifique os símbolos e o contexto. Atenção também à exclusão de mulheres e escravizados.',
  'Para revisar, esquematize: crise do Antigo Regime → Estados Gerais → Assembleia Nacional → Bastilha (1789) → Declaração dos Direitos → Monarquia Constitucional → República e Convenção (Terror) → Diretório → Golpe de 18 Brumário e Napoleão → Congresso de Viena. Relacione-a ao Iluminismo (ideias), à independência dos EUA (influência) e à Revolução Industrial (a revolução econômica que acompanhou a política), tema que será estudado a seguir.'] }
]}
];
