/* História: textos corridos, temas 1 a 3 */
module.exports = [
{ t:'Antiguidade: Grécia', txt:[
 { h:'A formação da Grécia antiga e as cidades-Estado', p:[
  'A civilização grega se desenvolveu na região do mar Egeu, ao redor da península balcânica, das ilhas e do litoral da Ásia Menor. O território montanhoso e o litoral recortado dificultavam a unificação política e favoreciam a formação de comunidades isoladas, que se organizaram em **cidades-Estado**, as **póleis**. Cada pólis tinha governo, leis, exército e moeda próprios, mas todas compartilhavam a mesma língua, a mesma religião e os mesmos jogos, como as Olimpíadas, e se identificavam como "helenas", em oposição aos "bárbaros", os que não falavam grego.',
  'A história grega costuma ser dividida em períodos. No **Período Homérico** (séculos XII a VIII a.C.), a sociedade se organizava em comunidades gentílicas, os **genos**, em torno de um chefe, e as principais fontes são os poemas Ilíada e Odisseia, atribuídos a Homero. No **Período Arcaico** (séculos VIII a VI a.C.), a concentração de terras nas mãos de aristocratas e o crescimento populacional provocaram crises sociais e a **colonização** do Mediterrâneo, com a fundação de colônias na Itália, na Sicília e no mar Negro, o que difundiu a cultura grega e estimulou o comércio.',
  'No **Período Clássico** (séculos V e IV a.C.), a Grécia viveu seu auge cultural e político, com o desenvolvimento da democracia ateniense, da filosofia, do teatro e das artes. Esse momento foi marcado pelas **Guerras Médicas**, em que as cidades gregas, lideradas por Atenas e Esparta, enfrentaram o Império Persa e saíram vitoriosas, em batalhas como Maratona e Salamina. A vitória reforçou a posição de Atenas, que formou a **Liga de Delos**, uma aliança militar e comercial que, com o tempo, passou a funcionar como um instrumento de seu domínio sobre outras cidades.'] },
 { h:'Atenas: a democracia e seus limites', p:[
  'Atenas começou com um governo aristocrático e passou por reformas que ampliaram a participação política. **Sólon** aboliu a escravidão por dívidas e dividiu os cidadãos por renda; **Psístrato** governou como tirano apoiando os pequenos proprietários; e **Clístenes**, no fim do século VI a.C., reorganizou a cidade em unidades territoriais, os **demos**, e é considerado o criador da democracia. No século V a.C., sob a liderança de **Péricles**, a democracia chegou a seu ápice, com o pagamento a cidadãos que exerciam funções públicas, o que permitiu que os mais pobres participassem da política.',
  'O poder se exercia de forma **direta**: os cidadãos reuniam-se na **Assembleia** (Ekklesía), na ágora, para discutir e votar as leis e as decisões, como a guerra e a paz. Havia também o **Conselho dos Quinhentos** (Boulé), que preparava as propostas, e magistrados sorteados ou eleitos para cargos temporários, o que evitava a concentração de poder. Para proteger a democracia, existia o **ostracismo**, uma votação em que um cidadão considerado ameaça à ordem podia ser exilado por dez anos. Essa experiência influenciou profundamente as ideias políticas ocidentais.',
  'Contudo, a democracia ateniense tinha **limites** importantes. Eram considerados cidadãos apenas os homens livres, maiores de 18 anos e filhos de pai e mãe atenienses. Ficavam excluídos as **mulheres**, os **estrangeiros** (metecos) e os **escravos**, que formavam uma grande parte da população e sustentavam a economia, trabalhando na agricultura, nas minas e no serviço doméstico. Portanto, tratava-se de uma democracia para uma minoria. Ao comparar com as democracias atuais, o ENEM costuma explorar essas diferenças, como a participação direta versus a representativa e o alcance da cidadania.'] },
 { h:'Esparta e a Guerra do Peloponeso', p:[
  'Esparta, na região da Lacônia, no Peloponeso, desenvolveu um modelo muito diferente do ateniense. Era uma sociedade **militarista e aristocrática**, que dominou povos vizinhos e os transformou em servos, os **hilotas**, que trabalhavam a terra e eram vigiados com violência. A população se dividia em **espartanos** (cidadãos plenos, guerreiros), **periecos** (livres, dedicados ao comércio e ao artesanato, sem direitos políticos) e **hilotas**. O governo combinava dois reis, um conselho de anciãos (a Gerúsia) e a Assembleia, mas o poder real estava nas mãos de poucos.',
  'A educação espartana, chamada de **agogé**, era controlada pelo Estado: aos sete anos, os meninos eram retirados das famílias e submetidos a um treinamento militar rigoroso, voltado à disciplina, à resistência e à obediência. As mulheres espartanas tinham mais liberdade e prestígio que as atenienses, pois deviam gerar guerreiros fortes. Esparta valorizava a austeridade e desprezava o comércio e as artes, e por isso pouco legou à cultura. A comparação entre Atenas (democracia, comércio, artes) e Esparta (militarismo, disciplina, agricultura) é um clássico de provas.',
  'A rivalidade entre as duas cidades e seus aliados levou à **Guerra do Peloponeso** (431 a 404 a.C.), entre a Liga de Delos, liderada por Atenas, e a Liga do Peloponeso, liderada por Esparta. A guerra, longa e desgastante, terminou com a vitória espartana e o enfraquecimento de toda a Grécia. Esparta tentou impor sua hegemonia, mas também se esgotou. A divisão e as guerras internas deixaram as póleis vulneráveis à expansão da **Macedônia**, reino do norte, que, sob Filipe II, dominou a Grécia, abrindo caminho para o império de seu filho.'] },
 { h:'Alexandre, o helenismo e o legado cultural', p:[
  'Filipe II, rei da Macedônia, conquistou as cidades gregas em 338 a.C., na Batalha de Queroneia. Seu filho, **Alexandre, o Grande**, assumiu o trono aos 20 anos, e em pouco mais de uma década conquistou o Império Persa, o Egito e chegou até o noroeste da Índia, construindo um dos maiores impérios da Antiguidade. Com sua morte precoce, em 323 a.C., o império foi dividido entre seus generais. Alexandre fundou cidades, como Alexandria, no Egito, que se tornou um grande centro cultural, com sua famosa biblioteca.',
  'A fusão entre elementos gregos e orientais (persas, egípcios e indianos) formou a cultura **helenística**, que se estendeu do século IV ao I a.C. O grego tornou-se língua de comunicação internacional, e se difundiram a ciência, a filosofia e a arte gregas. Nesse período, destacaram-se **Euclides** (geometria), **Arquimedes** (física e matemática) e **Eratóstenes**, que calculou a circunferência da Terra. Em filosofia, surgiram correntes como o estoicismo e o epicurismo, voltadas à busca da tranquilidade diante das incertezas. O helenismo influenciou Roma e, depois, o cristianismo e o mundo islâmico.',
  'O **legado cultural grego** é enorme. Na política, a ideia de democracia e de cidadania. Na filosofia, as obras de Sócrates, Platão e Aristóteles, que fundaram o pensamento ocidental. Na literatura e no teatro, a tragédia (Ésquilo, Sófocles, Eurípides) e a comédia (Aristófanes). Na história, os relatos de Heródoto e Tucídides. Nas artes, a escultura e a arquitetura, com templos como o Partenon, símbolo da arquitetura clássica. Na ciência, a medicina de Hipócrates e a geometria. Nos esportes, os Jogos Olímpicos, retomados na era moderna. É por isso que a Grécia é considerada o "berço" da cultura ocidental.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Nas provas, a Grécia antiga aparece, em geral, em comparações entre a democracia ateniense e a atual, em questões sobre cidadania, em textos de filósofos e historiadores, e na discussão sobre o legado cultural. Também podem ser pedidas características da pólis, a diferença entre Atenas e Esparta e o impacto das conquistas de Alexandre. Muitas vezes, o enunciado traz um trecho de Péricles ou de Aristóteles, e pede para identificar a concepção de política ou de cidadania nele expressa.',
  'Atenção aos pontos mais cobrados: o conceito de **democracia direta** e quem era considerado cidadão; a exclusão de mulheres, estrangeiros e escravos; a função da ágora e da Assembleia; o papel do ostracismo; a diferença entre uma sociedade comercial e artística (Atenas) e uma militarista (Esparta); e o conceito de helenismo, como fusão de culturas. Evite o erro de dizer que a democracia grega era "para todos": era restrita e convivia com a escravidão.',
  'Para revisar, monte uma linha do tempo com os períodos (Homérico, Arcaico, Clássico e Helenístico) e associe a cada um um fato-chave: genos, colonização, democracia e Guerras Médicas, e Alexandre. Em seguida, compare Atenas e Esparta em um quadro, considerando governo, economia, educação e sociedade. Esse é um dos temas de História mais fáceis de estudar, pois combina poucos conceitos com muitos exemplos, e prepara o estudo de Roma, que herdou e transformou muito da cultura grega.'] }
]},
{ t:'Antiguidade: Roma', txt:[
 { h:'Da fundação à República', p:[
  'Segundo a lenda, Roma foi fundada em 753 a.C. por Rômulo, às margens do rio Tibre, na península Itálica. Os historiadores explicam que a cidade surgiu da união de povos latinos, sabinos e etruscos, e que a localização favoreceu o comércio e a defesa. No início, vigorou a **Monarquia** (753 a 509 a.C.), com reis que acumulavam poderes políticos, militares e religiosos, auxiliados por um Senado de anciãos. Os últimos reis eram de origem etrusca, e sua expulsão, em 509 a.C., deu início à República.',
  'Na **República** (509 a 27 a.C.), o poder passou a ser exercido por magistrados eleitos por mandato limitado, como os **cônsules** (dois, com poder executivo e militar), os pretores, os questores e os edis. O **Senado**, formado por aristocratas, tornou-se o centro do poder, e as assembleias reuniam os cidadãos. A sociedade era dividida em **patrícios** (aristocratas, proprietários de terras, com direitos políticos plenos), **plebeus** (livres, comerciantes e artesãos, que no início tinham poucos direitos), **clientes** (dependentes de patrícios) e **escravos**, sem direitos.',
  'Os plebeus lutaram por direitos e conquistaram, ao longo dos séculos, o **Tribunato da Plebe**, magistrados com direito de veto, a **Lei das Doze Tábuas** (primeira codificação escrita das leis, de 450 a.C.) e o acesso aos cargos públicos e ao casamento com patrícios. Essas conquistas mostram como a pressão social levou à ampliação da participação política. As leis escritas reduziram a arbitrariedade dos magistrados, e a ideia de que a lei vale para todos influenciou fortemente o direito moderno.'] },
 { h:'Expansão territorial e consequências sociais', p:[
  'A partir do século IV a.C., Roma iniciou uma expansão que a levou a dominar a península Itálica e, depois, todo o Mediterrâneo. As **Guerras Púnicas** (264 a 146 a.C.), contra Cartago, cidade fenícia do norte da África, foram decisivas: após três conflitos, em que se destacou o general cartaginês Aníbal, que atravessou os Alpes, Roma venceu e destruiu Cartago, tornando-se a maior potência da região. Seguiram-se conquistas na Grécia, na Macedônia, na Ásia Menor, no Egito e na Gália, e o Mediterrâneo passou a ser chamado de **Mare Nostrum** ("nosso mar").',
  'A expansão trouxe **riqueza**, com saques, tributos e terras, e uma enorme quantidade de **escravos**, prisioneiros de guerra, que passaram a trabalhar nos latifúndios, nas minas e nas casas. Mas também gerou problemas: os pequenos camponeses, que serviam no exército e voltavam endividados, perdiam suas terras para grandes proprietários e migravam para as cidades, formando uma massa de desempregados dependentes do Estado. A política do "**pão e circo**", a distribuição de alimentos e espetáculos, buscava aplacar essa população, que era manipulada por políticos.',
  'As tensões sociais geraram conflitos. Os irmãos **Tibério e Caio Graco**, tribunos da plebe, propuseram reformas agrárias para redistribuir terras aos camponeses, mas foram assassinados pela aristocracia. Surgiram então generais poderosos, como **Mário** e **Sila**, que usavam o exército para disputar o poder. A República entrou em crise, com guerras civis, escravos rebeldes (como a revolta liderada por **Espártaco**, em 73 a.C.) e a ascensão de líderes militares com grande influência, o que preparou o caminho para o fim do regime republicano.'] },
 { h:'Do Império à crise do século III', p:[
  'Em meio às guerras civis, **Júlio César**, general vitorioso na Gália, tomou o poder e governou como ditador, com reformas como o calendário juliano. Foi assassinado em 44 a.C. por senadores que temiam o fim da República. Seu sobrinho e herdeiro, **Otávio**, venceu os rivais e, em 27 a.C., recebeu do Senado o título de **Augusto**, tornando-se o primeiro imperador e inaugurando o **Império**. Na prática, Augusto concentrou o poder, mantendo as aparências da República, e inaugurou um longo período de estabilidade, a **Pax Romana** (paz romana), que durou cerca de dois séculos.',
  'Durante o Império, Roma atingiu sua maior extensão no século II, sob o imperador Trajano, abrangendo a Europa Ocidental, o norte da África e o Oriente Médio. A administração se apoiava em **províncias**, governadas por representantes do imperador, em um **exército** profissional, em uma rede de **estradas** e em um sistema jurídico unificado. A romanização difundiu o latim, o direito, a arquitetura e os costumes, e a cidadania romana foi ampliada, até ser estendida a todos os homens livres em 212, pelo imperador Caracala. As cidades tinham aquedutos, termas, anfiteatros e fóruns.',
  'A economia se baseava na **escravidão**, que sustentava os latifúndios e a produção. À medida que as conquistas cessaram, a oferta de novos escravos diminuiu e o sistema entrou em crise, o que levou os grandes proprietários a utilizar o **colonato**, em que camponeses livres, os colonos, trabalhavam a terra em troca de proteção e de parte da produção, uma forma que antecipa a servidão medieval. No século III, o Império enfrentou uma crise com instabilidade política, guerras civis, ataques de povos estrangeiros, inflação e queda do comércio, levando muitos habitantes a abandonar as cidades.'] },
 { h:'O cristianismo, a divisão do Império e a queda do Ocidente', p:[
  'O **cristianismo** nasceu na Palestina, província romana, a partir da pregação de Jesus de Nazaré, no século I. Difundiu-se entre os pobres e escravos, pela mensagem de igualdade e esperança, e foi perseguido por recusar a adoração ao imperador. Mesmo assim, espalhou-se pelo Império. Em 313, o imperador **Constantino** assinou o **Édito de Milão**, que concedeu liberdade de culto aos cristãos, e em 380, no reinado de **Teodósio**, o cristianismo tornou-se a religião oficial. A Igreja passou a ter grande poder político e cultural, e a preservar parte do saber da Antiguidade.',
  'Para facilitar a administração, o imperador Teodósio dividiu o Império, em 395, em **Império Romano do Ocidente**, com capital em Roma (depois Ravena), e **Império Romano do Oriente** (Bizantino), com capital em Constantinopla. O Ocidente, mais agrário e fragilizado, sofreu cada vez mais com as **invasões de povos germânicos**, chamados pelos romanos de "bárbaros", como visigodos, vândalos, ostrogodos e francos. Em 476, o último imperador, **Rômulo Augústulo**, foi deposto por Odoacro, líder germânico, data que marca o fim do Império Romano do Ocidente e da Idade Antiga.',
  'O Império do Oriente sobreviveu por quase mil anos, até a conquista de Constantinopla pelos turcos otomanos, em 1453, e preservou o direito romano, na compilação conhecida como **Código de Justiniano**. A queda do Ocidente não foi um evento súbito, mas o resultado de um longo processo de crise econômica, política, social e militar. O legado romano, entretanto, permaneceu: o direito, o latim (origem das línguas românicas, como o português), a organização administrativa, a engenharia e a Igreja católica estruturada à semelhança do Império.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Roma costuma aparecer no ENEM por meio de seu legado: o **direito romano** e a ideia de que a lei é igual para todos, a **cidadania**, a **língua latina**, a engenharia (estradas, aquedutos) e a administração do Império. Também são cobrados os conflitos entre patrícios e plebeus, a política de "pão e circo", a escravidão e as razões da crise do Império. O enunciado pode trazer uma imagem de um monumento, um texto de historiador antigo ou um mapa da expansão romana.',
  'Pontos de atenção: a diferença entre as três fases (Monarquia, República e Império) e o que distingue cada uma; o fato de os plebeus terem conquistado direitos por meio de pressão; a associação entre expansão e escravidão em larga escala; o papel do cristianismo na transformação do Império; e a ideia de que a "queda" de 476 foi um processo, e não um acontecimento isolado. É comum o ENEM comparar a cidadania romana com a grega, e com a atual, valorizando o raciocínio crítico.',
  'Para revisar, faça um quadro com as três fases de Roma e o tipo de governo, os principais grupos sociais e as principais mudanças. Em seguida, relacione a crise do escravismo ao colonato e à formação do feudalismo, que será estudado a seguir. Esse encadeamento mostra como a Antiguidade se conecta à Idade Média e ajuda a entender a continuidade histórica, uma habilidade importante nas provas de História.'] }
]},
{ t:'Idade Média e feudalismo', txt:[
 { h:'Do fim do Império ao início do feudalismo', p:[
  'A **Idade Média**, período que vai da queda do Império Romano do Ocidente (476) à queda de Constantinopla (1453), costuma ser dividida em Alta Idade Média (séculos V ao X) e Baixa Idade Média (séculos XI ao XV). Com as invasões germânicas e o desaparecimento de um poder central forte, a Europa ocidental passou por um processo de **ruralização**: as cidades perderam importância, o comércio e o uso da moeda diminuíram, e a vida se concentrou no campo. Os povos germânicos formaram reinos, como o dos francos, que se tornou o mais poderoso.',
  'O reino franco, sob a dinastia carolíngia, chegou a seu auge com **Carlos Magno**, coroado imperador pelo papa em 800. Seu império reuniu grande parte da Europa ocidental, apoiado na aliança com a Igreja, e incentivou a cultura, em um movimento conhecido como renascimento carolíngio. Após sua morte, o império foi dividido entre os netos, no Tratado de Verdun (843). Ao mesmo tempo, a Europa enfrentava novas invasões, de vikings (do norte), magiares (do leste) e sarracenos (do sul), o que aumentou a insegurança e a necessidade de proteção local.',
  'Nesse contexto, os camponeses buscavam a proteção de grandes proprietários de terras, e estes, a de senhores mais poderosos, em uma rede de lealdades pessoais. Consolidou-se o **feudalismo**, sistema político, econômico e social que predominou na Europa ocidental, em especial entre os séculos IX e XIII. O poder se fragmentou nas mãos de senhores locais, e o rei tinha pouco controle efetivo. O feudalismo se originou da combinação de elementos romanos, como o colonato e o latifúndio, e germânicos, como os laços de fidelidade entre o chefe e seus guerreiros.'] },
 { h:'A sociedade feudal e as relações de produção', p:[
  'A sociedade feudal era **estamental**, ou seja, dividida em grupos com direitos e funções definidos pelo nascimento, e com pouca mobilidade. O **clero** (os que oravam) cuidava da vida espiritual, e possuía grande poder e riqueza, com terras e dízimos. A **nobreza** (os que guerreavam) era formada por senhores feudais, que possuíam terras e eram responsáveis pela defesa. E os **servos** e camponeses (os que trabalhavam) produziam o alimento, sustentando os outros dois grupos. A ideia de que a posição social era determinada por Deus justificava a desigualdade.',
  'As relações entre os nobres eram baseadas na **suserania e vassalagem**. O suserano doava um **feudo** (terra) a um vassalo, que, em troca, lhe devia fidelidade, auxílio militar e conselho. Um vassalo podia ser, ao mesmo tempo, suserano de outros, formando uma rede. Os servos, por sua vez, estavam presos à terra e ao senhor pela **servidão**: não eram escravos, pois não podiam ser vendidos como mercadorias, mas não eram livres para sair do feudo. Deviam obrigações como a **corveia** (trabalho gratuito nas terras do senhor, em alguns dias da semana), a **talha** (parte da produção) e as **banalidades** (taxas pelo uso do moinho, do forno e do lagar).',
  'A unidade econômica era o **feudo**, ou senhorio, que incluía o castelo, as terras cultivadas, as terras comunais (pastos e florestas) e a reserva senhorial, e era uma economia **autossuficiente**, voltada ao consumo local, com baixo uso da moeda e do comércio. A agricultura era rudimentar, de baixa produtividade, usando a técnica da **rotação trienal** (divisão da terra em três partes, com uma em descanso) e, mais tarde, o arado de ferro e o moinho. A vida do camponês era dura, marcada pela fome, pelas doenças e pelo trabalho constante, e dependia das estações do ano.'] },
 { h:'A Igreja, a cultura e a crise do feudalismo', p:[
  'A **Igreja católica** foi a principal instituição da Idade Média. Era a maior proprietária de terras, detinha o monopólio do saber, pois os mosteiros preservavam e copiavam os manuscritos antigos, e influenciava a política, a economia e o cotidiano. A **Teologia** dominava o pensamento, e a escolástica, de Tomás de Aquino, procurou conciliar a fé com a razão, com base em Aristóteles. A arte medieval foi principalmente religiosa, com as arquiteturas **românica** e **gótica** (catedrais com vitrais e arcos). A Igreja punia os considerados hereges, com a Inquisição, e promoveu as **Cruzadas**, expedições militares para retomar Jerusalém dos muçulmanos.',
  'As **Cruzadas** (séculos XI ao XIII) tiveram motivações religiosas, mas também econômicas e políticas: o desejo de expandir a influência da Igreja, de obter terras e de abrir rotas de comércio. Embora não tenham alcançado o objetivo de manter Jerusalém, tiveram grande efeito: reabriram o Mediterrâneo ao comércio, aproximaram o Ocidente do mundo oriental e do saber muçulmano e estimularam o **renascimento comercial e urbano**. Surgiram, então, as **cidades** (burgos) e uma nova classe, os **burgueses**, comerciantes e artesãos, organizados em corporações de ofício, e as feiras.',
  'A partir do século XIV, o feudalismo entrou em **crise**. O crescimento do comércio e das cidades enfraqueceu a economia fechada dos feudos; a **fome** do início do século, resultado de mudanças climáticas, e a **Peste Negra** (1347 a 1351), epidemia que matou um terço da população europeia, causaram uma escassez de mão de obra, que fortaleceu a posição dos camponeses; ocorreram **revoltas camponesas** (as Jacqueries); e a **Guerra dos Cem Anos** (França e Inglaterra) esgotou a nobreza. Os reis aproveitaram para centralizar o poder, formando as monarquias nacionais, e abrindo caminho para a Idade Moderna.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Idade Média e feudalismo aparecem no ENEM em questões que pedem a caracterização da sociedade estamental, das relações de suserania e vassalagem e da servidão, a compreensão do papel da Igreja, a interpretação de imagens medievais, e a análise das causas da crise do feudalismo e do renascimento comercial. Os textos podem incluir relatos de cronistas, trechos de contratos de vassalagem ou imagens de iluminuras. Outra abordagem é a comparação entre o feudalismo e as formas atuais de trabalho e de poder.',
  'Pontos de atenção: servo **não é** escravo, mas está preso à terra; vassalagem é uma relação entre nobres, e servidão é entre senhor e camponês; o feudalismo é um sistema descentralizado e rural, com economia de subsistência; a Igreja era uma instituição de grande poder, e o clero fazia parte do primeiro estamento; e as Cruzadas e a Peste Negra tiveram papel na transição para a Idade Moderna. É útil lembrar que a "Idade das Trevas" é uma expressão que simplifica o período, que teve avanços culturais e técnicos.',
  'Para revisar, esquematize: três ordens (clero, nobreza, servos); suserano e vassalo; feudo; corveia, talha e banalidades; economia fechada; papel da Igreja; Cruzadas, renascimento comercial e urbano; e crise do século XIV (fome, peste, guerra, revoltas). Associe essa estrutura à anterior, a crise do escravismo romano e o colonato, e à seguinte, o Renascimento e a formação dos Estados modernos. Entender o encadeamento ajuda a ver a História como processo, e não como uma lista de datas isoladas.'] }
]}
];
