/* Matemática: textos corridos, temas 1 a 3 */
module.exports = [
{ t:'Conjuntos numéricos e operações', txt:[
 { h:'Como os números foram ganhando espaço', p:[
  'Os conjuntos numéricos nasceram de necessidades práticas. Os **números naturais** (0, 1, 2, 3, ...) surgiram para contar: ovelhas, dias, pessoas. Com o tempo apareceu a ideia de dívida e de temperaturas abaixo de zero, e os naturais deixaram de bastar. Nasceram então os **números inteiros**, que incluem os negativos (..., −2, −1, 0, 1, 2, ...). Saber que o inteiro negativo representa uma falta, uma perda ou uma posição abaixo de um ponto de referência ajuda a interpretar muitos enunciados do ENEM.',
  'Quando foi preciso dividir uma pizza em partes iguais ou medir um terreno, os inteiros também ficaram pequenos. Surgiram os **números racionais**, aqueles que podem ser escritos como fração de dois inteiros, com denominador diferente de zero. Dentro dos racionais estão as frações, os decimais exatos (0,75) e as dízimas periódicas (0,333...). Todo inteiro é racional, pois 5 pode ser escrito como 5/1.',
  'Existem ainda números que não podem ser escritos como fração, como a raiz quadrada de 2 e o número π. São os **irracionais**: seus decimais continuam para sempre sem formar um período que se repete. Juntando racionais e irracionais, chegamos aos **números reais**, que preenchem toda a reta numérica. A relação de inclusão é simples de lembrar: naturais estão dentro dos inteiros, que estão dentro dos racionais, que estão dentro dos reais.'] },
 { h:'A ordem das operações e os sinais', p:[
  'Uma das fontes de erro mais comuns é a ordem em que as operações são feitas. A regra é: primeiro o que está entre **parênteses, colchetes e chaves** (de dentro para fora), depois **potências e raízes**, depois **multiplicações e divisões** (da esquerda para a direita) e, por último, **somas e subtrações**. Em 2 + 3 × 4 a resposta é 14, e não 20, porque a multiplicação vem antes da soma. Pode parecer detalhe, mas é nesse ponto que muitos candidatos perdem questões que já sabiam resolver.',
  'Os sinais seguem uma lógica própria. Somar dois números negativos resulta em um número ainda mais negativo: (−3) + (−4) = −7. Subtrair um negativo equivale a somar o seu oposto: 5 − (−2) = 7. Na multiplicação e na divisão, sinais iguais dão resultado positivo e sinais diferentes dão resultado negativo. Assim, (−2) × (−6) = 12 e (−12) ÷ 4 = −3. Uma dica prática é contar quantos sinais negativos existem em uma multiplicação: se o número for par, o resultado é positivo; se for ímpar, é negativo.',
  'Ao trabalhar com situações reais, o sinal costuma ter significado. Em um extrato bancário, créditos são positivos e débitos são negativos. Em um mapa de altitudes, acima do nível do mar é positivo e abaixo é negativo. Antes de operar, vale perguntar o que cada sinal representa no contexto da questão, porque isso ajuda a perceber se o resultado final faz sentido.'] },
 { h:'Múltiplos, divisores, MMC e MDC', p:[
  'Dizemos que um número é **múltiplo** de outro quando ele pode ser obtido multiplicando o segundo por um inteiro. Os múltiplos de 6 são 0, 6, 12, 18, 24 e assim por diante. Já os **divisores** de um número são aqueles que o dividem sem deixar resto: os divisores de 12 são 1, 2, 3, 4, 6 e 12. Um número com apenas dois divisores, o 1 e ele mesmo, é chamado de **primo**. O número 2 é o único primo par, e o 1 não é considerado primo.',
  'Decompor um número em fatores primos é uma ferramenta poderosa. O número 60, por exemplo, é 2 × 2 × 3 × 5, ou seja, 2² × 3 × 5. A partir da fatoração dá para calcular o **MMC** (mínimo múltiplo comum) e o **MDC** (máximo divisor comum). O MMC reúne todos os fatores primos, com o maior expoente de cada um, e serve para saber quando dois eventos que se repetem em ciclos diferentes voltam a coincidir. O MDC reúne apenas os fatores comuns, com o menor expoente, e serve para dividir algo em partes iguais e as maiores possíveis.',
  'Um exemplo clássico: dois ônibus saem do terminal juntos, um a cada 12 minutos e outro a cada 18 minutos. Eles voltam a sair juntos no MMC de 12 e 18, que é 36 minutos. Outro exemplo: uma tira de 60 cm e outra de 48 cm devem ser cortadas em pedaços iguais, os maiores possíveis, sem sobras. O tamanho de cada pedaço é o MDC de 60 e 48, que é 12 cm. Reconhecer a pergunta (quando coincidem? ou qual o maior tamanho?) é o primeiro passo para escolher entre MMC e MDC.'] },
 { h:'Potências, raízes e intervalos na reta', p:[
  'Uma potência é uma multiplicação repetida: 2⁵ = 2 × 2 × 2 × 2 × 2 = 32. Qualquer número (diferente de zero) elevado a zero vale 1, e expoente negativo indica inverso: 2⁻³ = 1/8. Ao multiplicar potências de mesma base, somam-se os expoentes; ao dividir, subtraem-se; ao elevar uma potência a outra, multiplicam-se. A raiz é a operação inversa: a raiz quadrada de 49 é 7 porque 7² = 49. Raízes de números negativos, no caso da raiz quadrada, não existem entre os reais.',
  'Os números reais podem ser representados na reta numérica, e os **intervalos** descrevem trechos dela. Escrever 2 ≤ x < 5 significa que x pode ser qualquer número a partir de 2, incluindo o 2, e menor que 5, sem incluir o 5. Em gráficos e em problemas de condição (por exemplo, "idade mínima de 18 anos"), o intervalo traduz regras do cotidiano. Bolinha fechada indica que o extremo está incluído; bolinha aberta indica que não está.',
  'Comparar números é outra habilidade frequente. Entre dois negativos, o maior é o que está mais próximo de zero: −2 é maior que −5. Entre frações de mesmo numerador, é maior a que tem menor denominador. Para frações diferentes, uma saída é transformar em decimais ou reduzir ao mesmo denominador. Treinar essas comparações rápidas economiza tempo na prova.'] },
 { h:'Como esse tema aparece no ENEM', p:[
  'Em geral, o tema não vem com cara de teoria. Ele aparece disfarçado em situações do dia a dia: uma conta com dívidas e créditos, um problema de calendário, a divisão de materiais em lotes, uma comparação entre temperaturas. Quase sempre a dificuldade não está na conta em si, e sim em entender o que o enunciado pede. Por isso, a primeira etapa é reescrever o problema com as suas palavras e identificar quais números são dados e qual é a incógnita.',
  'Algumas estratégias ajudam bastante. Faça uma estimativa antes de calcular, para ter noção da ordem de grandeza da resposta. Teste as alternativas quando a conta for longa, substituindo os valores. Desconfie de respostas com sinais invertidos: se o enunciado fala em perda e a resposta é positiva, algo está errado. E, sempre que possível, volte ao contexto: o resultado precisa fazer sentido no mundo real.',
  'Por fim, lembre-se de que os conjuntos numéricos servem de base para todos os outros temas de Matemática. Quem domina frações, sinais, potências e decomposição em fatores primos tem muito mais facilidade em porcentagem, razão, equações e funções. Vale dedicar um tempo extra para deixar esses fundamentos bem firmes, porque o ganho se repete em quase todas as questões da prova.'] }
]},

{ t:'Frações, decimais e arredondamento', txt:[
 { h:'O que uma fração realmente representa', p:[
  'Uma fração expressa uma parte de um todo dividido em partes iguais. Em 3/4, o denominador (4) diz em quantas partes iguais o inteiro foi dividido e o numerador (3) diz quantas delas foram tomadas. A fração também pode ser lida como divisão: 3/4 é o mesmo que 3 ÷ 4 = 0,75. Essa dupla leitura, como parte de um todo e como divisão, é útil porque permite alternar entre fração, decimal e porcentagem conforme a conveniência.',
  'Há três tipos principais. As frações **próprias** têm numerador menor que o denominador e valem menos que 1 (2/5). As **impróprias** têm numerador maior ou igual ao denominador e valem 1 ou mais (7/4). Os **números mistos** juntam uma parte inteira e uma fração, como 1 3/4, que equivale a 7/4. Saber converter entre essas formas evita erros em contas e leituras de receitas, medidas e tempo.',
  'Frações equivalentes representam o mesmo valor: 1/2, 2/4 e 50/100 são iguais. Para obter uma fração equivalente, multiplica-se ou divide-se numerador e denominador pelo mesmo número. Simplificar uma fração é dividir os dois termos pelo maior divisor comum, até chegar à forma irredutível. Fazer isso antes de multiplicar costuma reduzir bastante o trabalho de cálculo.'] },
 { h:'Operações com frações, passo a passo', p:[
  'Para **somar ou subtrair** frações com denominadores iguais, basta operar os numeradores e manter o denominador: 2/7 + 3/7 = 5/7. Quando os denominadores são diferentes, é preciso antes reduzi-las a um denominador comum, geralmente o MMC dos denominadores. Assim, 1/3 + 1/4 vira 4/12 + 3/12 = 7/12. Um erro frequente é somar numeradores e denominadores separadamente, o que nunca é correto.',
  'Na **multiplicação**, multiplicam-se numeradores entre si e denominadores entre si: 2/3 × 3/5 = 6/15 = 2/5. Dá para simplificar na diagonal antes de multiplicar, cortando fatores comuns. Na **divisão**, mantém-se a primeira fração e multiplica-se pelo inverso da segunda: 3/4 ÷ 2/5 = 3/4 × 5/2 = 15/8. Lembrar que "dividir por uma fração é multiplicar pelo inverso" resolve a grande maioria dos casos.',
  'Também é comum calcular "uma fração de uma quantidade". Para saber quanto é 3/5 de 200, divide-se 200 por 5 (obtendo 40) e multiplica-se por 3 (obtendo 120). Em problemas com partes sucessivas, como "gastou 1/3 do salário e depois 1/4 do que restou", é essencial acompanhar sobre qual base cada fração incide. Desenhar uma barra dividida em partes ajuda a visualizar.'] },
 { h:'Números decimais e dízimas periódicas', p:[
  'O sistema decimal organiza os números em casas: unidades, dezenas, centenas, e, depois da vírgula, décimos, centésimos e milésimos. Entender a posição de cada algarismo é o que permite comparar números como 0,5 e 0,45. Ainda que 45 seja maior que 5, 0,5 vale mais que 0,45, porque 0,5 equivale a 0,50. Uma boa prática é igualar o número de casas decimais antes de comparar.',
  'Para somar e subtrair decimais, alinhe a vírgula. Na multiplicação, ignora-se a vírgula, multiplica-se normalmente e, no fim, conta-se o total de casas decimais dos fatores para posicionar a vírgula no resultado. Na divisão, pode-se multiplicar dividendo e divisor por potências de 10 até que o divisor seja inteiro. Multiplicar por 10, 100 ou 1000 desloca a vírgula para a direita; dividir desloca para a esquerda.',
  'Nem todo decimal termina. Quando a divisão de dois inteiros gera um padrão que se repete indefinidamente, temos uma **dízima periódica**, como 0,333... (que é 1/3) ou 0,1666.... Toda dízima periódica tem uma fração geratriz. Para 0,333..., chamamos x = 0,333..., multiplicamos por 10 e subtraímos: 10x − x = 3, logo x = 3/9 = 1/3. Esse truque aparece em questões que pedem para transformar dízimas em frações.'] },
 { h:'Arredondamento e aproximações', p:[
  'Arredondar é substituir um número por outro mais simples e próximo. A regra básica diz que, ao arredondar para determinada casa, observamos o algarismo seguinte: se ele for 5 ou maior, aumentamos em uma unidade o algarismo da casa desejada; se for menor que 5, mantemos. Assim, 3,476 arredondado para duas casas decimais é 3,48, e 3,474 vira 3,47. Em contextos de dinheiro, o arredondamento a duas casas é o padrão.',
  'O arredondamento introduz um pequeno erro, e é importante saber quando ele pode se acumular. Se uma questão pede para arredondar apenas o resultado final, não se deve arredondar etapas intermediárias, para não propagar imprecisões. Já em situações práticas, como comprar ladrilhos para cobrir um piso, o arredondamento é feito sempre "para cima", pois não se compra fração de peça. Em outras situações, como contar quantos ônibus completos são necessários, também se arredonda para cima, mesmo que o decimal seja pequeno.',
  'Também é útil estimar usando números "redondos". Para calcular 49,8 × 20,1, você pode pensar 50 × 20 = 1000 e já saber que a resposta fica próxima disso. Em questões com alternativas bem distintas, a estimativa permite acertar sem fazer a conta exata, economizando tempo valioso.'] },
 { h:'Frações, decimais e porcentagens: a mesma ideia em três formas', p:[
  'Uma metade pode ser escrita como 1/2, 0,5 ou 50%. A habilidade de transitar entre essas formas é uma das mais cobradas em Matemática básica do ENEM. Para passar de fração a decimal, divide-se o numerador pelo denominador. Para passar de decimal a porcentagem, multiplica-se por 100. Para voltar, o caminho é o inverso. Decorar algumas equivalências ajuda muito: 1/4 = 0,25 = 25%; 1/5 = 0,2 = 20%; 1/8 = 0,125 = 12,5%; 3/4 = 0,75 = 75%.',
  'A escolha da forma mais conveniente depende da conta. Calcular 25% de 80 é mais rápido pensando em 1/4 de 80, que é 20. Já comparar descontos de 1/3 e 0,35 é mais fácil convertendo os dois para decimal (0,333... e 0,35). O que importa é ter flexibilidade e não ficar preso a uma representação.',
  'Nos enunciados, atenção à linguagem: "dois terços", "0,6 do total" e "60%" podem aparecer lado a lado. Reescrever todos na mesma forma antes de operar evita confusões. Esse cuidado simples costuma ser a diferença entre acertar e errar uma questão aparentemente fácil.'] },
 { h:'Problemas típicos e armadilhas', p:[
  'Um problema muito comum é o de receitas e medidas: "uma receita usa 2/3 de xícara de açúcar; para fazer metade da receita, quanto é necessário?" A resposta é 1/2 × 2/3 = 1/3 de xícara. Outro tipo é o de partilha: "três irmãos recebem frações diferentes de uma herança; que fração sobra?". Para resolver, soma-se o que foi distribuído e subtrai-se de 1 (o todo).',
  'As armadilhas mais frequentes são somar denominadores, esquecer de simplificar no final, confundir "dividir por 2" com "multiplicar por 2" quando a fração é invertida e arredondar na hora errada. Outra armadilha é interpretar "1/3 a mais" como se fosse "1/3 do total", quando na verdade o acréscimo incide sobre o valor original. Reler o enunciado com calma é o melhor antídoto.',
  'Para treinar, escolha situações do seu cotidiano e traduza em frações: a fração do dia que você dedica a estudar, a fração do orçamento gasta com transporte, a fração de páginas já lidas de um livro. Quanto mais você relaciona o conceito ao concreto, mais natural ele se torna, e menos mecânico é o raciocínio durante a prova.'] }
]},

{ t:'Razão e proporção', txt:[
 { h:'O que é razão e como lê-la', p:[
  'Razão é a comparação entre duas grandezas por meio de uma divisão. Dizer que "a razão entre A e B é de 3 para 5" significa A/B = 3/5. A ordem importa: a razão de A para B não é a mesma que a de B para A. Quando as grandezas têm unidades diferentes, a razão ganha unidade própria, como a velocidade média (km/h) e a densidade demográfica (habitantes por km²).',
  'As razões estão por toda parte. A escala de um mapa é uma razão entre a distância no desenho e a distância real. A concentração de um remédio é uma razão entre massa e volume. A relação candidato/vaga em um concurso compara quantidade de pessoas e de vagas. Entender que "razão" é só uma divisão com um significado específico simplifica bastante o tema.',
  'Duas razões podem ser equivalentes, e é isso que a proporção expressa. Quando duas razões são iguais, dizemos que as quatro grandezas formam uma **proporção**: a/b = c/d. A propriedade fundamental das proporções afirma que o produto dos meios é igual ao produto dos extremos: a × d = b × c. Essa é a ferramenta que resolve a maioria dos problemas, pois permite descobrir um valor desconhecido por meio do chamado "produto cruzado".'] },
 { h:'Grandezas diretamente proporcionais', p:[
  'Duas grandezas são **diretamente proporcionais** quando, ao aumentar uma, a outra aumenta na mesma proporção. Se o preço de 1 kg de arroz é fixo, dobrar a quantidade comprada dobra o valor pago. O quociente entre as duas grandezas permanece constante: é a chamada **constante de proporcionalidade**. No exemplo do arroz, essa constante é o preço por quilo.',
  'No gráfico, a proporcionalidade direta aparece como uma reta que passa pela origem. Em uma tabela, basta dividir cada valor da segunda coluna pelo da primeira: se todos os quocientes forem iguais, as grandezas são diretamente proporcionais. Esse teste simples é útil para verificar se uma relação descrita no enunciado realmente obedece a esse padrão, evitando aplicar regra de três onde ela não vale.',
  'Para resolver, monte a proporção alinhando as grandezas de mesma natureza. Se 5 canetas custam R$ 12,50, quanto custam 8 canetas? Armamos 5/8 = 12,50/x. O produto cruzado dá 5x = 100, logo x = R$ 20,00. Sempre confira o sentido: mais canetas, mais dinheiro, o que está coerente com a proporcionalidade direta.'] },
 { h:'Grandezas inversamente proporcionais', p:[
  'Duas grandezas são **inversamente proporcionais** quando, ao aumentar uma, a outra diminui na mesma proporção. Se 4 pedreiros constroem um muro em 6 dias, 8 pedreiros (o dobro) levariam 3 dias (a metade), mantendo-se o mesmo ritmo de trabalho. Aqui, o que permanece constante é o **produto** entre as grandezas: 4 × 6 = 8 × 3 = 24.',
  'Para montar a proporção, inverte-se uma das razões. No exemplo, escrevemos 4/8 = x/6, com a razão dos dias invertida, ou resolvemos diretamente pela constância do produto: 4 × 6 = 8 × x, e então x = 3. Reconhecer quando a relação é inversa é essencial: velocidade e tempo gastos em um mesmo percurso, número de torneiras e tempo para encher um tanque e número de operários e tempo de obra são exemplos clássicos.',
  'Um bom teste mental é perguntar: "se uma grandeza dobra, a outra dobra ou cai pela metade?". Se dobra, é direta. Se cai pela metade, é inversa. Se não acontece nenhuma das duas, a relação pode não ser proporcional, e outras ferramentas serão necessárias. Esse hábito de "testar o dobro" evita a maior parte dos erros de interpretação.'] },
 { h:'Divisão proporcional e escalas', p:[
  'A divisão em partes proporcionais aparece em situações de partilha. Se três sócios investiram R$ 2.000, R$ 3.000 e R$ 5.000 e vão dividir um lucro de R$ 20.000 proporcionalmente ao investimento, o total de partes é 2 + 3 + 5 = 10, cada parte vale R$ 2.000 e os sócios recebem R$ 4.000, R$ 6.000 e R$ 10.000. O raciocínio geral é somar as partes, descobrir o valor de uma parte e multiplicá-la pelo número de partes de cada um.',
  'Quando a divisão é inversamente proporcional, trabalha-se com os inversos dos números dados. Dividir um prêmio entre pessoas de forma inversamente proporcional às suas faltas, por exemplo, significa que quem faltou menos recebe mais. Basta trocar cada número pelo seu inverso e seguir o mesmo procedimento anterior.',
  'As escalas também são aplicações diretas das razões. Em um mapa de escala 1:50.000, cada centímetro no papel representa 50.000 cm na realidade, ou seja, 500 m. Para converter, multiplique a medida do mapa pela escala e passe para uma unidade conveniente. Cuidado com as unidades: é comum errar ao converter centímetros em quilômetros. Lembre que 1 km = 100.000 cm.'] },
 { h:'Como esse tema cai na prova', p:[
  'Razão e proporção estão entre os temas mais frequentes de Matemática do ENEM, geralmente com contexto social ou científico: densidade populacional, consumo de combustível, concentração de substâncias, relação entre escalas, receitas culinárias, produtividade e rendimento. A matemática em si costuma ser simples, mas o enunciado traz muitas informações e é preciso saber quais usar.',
  'Uma boa estratégia é organizar os dados em uma tabela, com as grandezas nas colunas e os valores nas linhas, marcando o valor desconhecido com x. Em seguida, decida se a relação é direta ou inversa, monte a proporção e resolva. Por fim, faça a verificação de coerência: o resultado faz sentido diante da situação? Por exemplo, mais pessoas trabalhando não pode resultar em mais tempo para terminar uma tarefa.',
  'Alguns cuidados extras: converta unidades antes de montar a proporção, mantenha a mesma ordem das grandezas dos dois lados da igualdade e não se esqueça de que razões entre grandezas de mesma unidade não têm unidade (são números puros). Dominando esses pontos, você terá uma ferramenta que também sustenta regra de três, porcentagem, escalas e muitos problemas de física e química.'] }
]}
];
