/* Matemática: textos corridos, temas 4 a 6 */
module.exports = [
{ t:'Regra de três', txt:[
 { h:'A ideia por trás da regra de três', p:[
  'A regra de três é um método para descobrir um valor desconhecido quando se conhecem três valores relacionados por proporcionalidade. O nome vem justamente disso: três dados conhecidos e um quarto a descobrir. Ela só funciona quando as grandezas envolvidas são proporcionais, direta ou inversamente. Por isso, antes de montar qualquer conta, a pergunta essencial é: o que acontece com uma grandeza quando a outra aumenta?',
  'Imagine que um carro percorre 150 km com 10 litros de combustível. Quantos litros serão necessários para percorrer 360 km? Quanto mais distância, mais combustível: a relação é direta. Organizamos os dados em duas colunas, uma para os quilômetros e outra para os litros, deixando um espaço para o x. A seguir, montamos a proporção 150/360 = 10/x e resolvemos pelo produto cruzado: 150x = 3.600, logo x = 24 litros.',
  'Um cuidado importante é manter as grandezas na mesma ordem nos dois lados da igualdade. Se a primeira coluna lista a distância e a segunda lista o combustível, a proporção deve comparar distância com distância e combustível com combustível. Misturar a ordem leva a resultados errados mesmo quando as contas estão corretas, e esse é um dos deslizes mais comuns dos candidatos.'] },
 { h:'Regra de três simples: direta e inversa', p:[
  'Na regra de três **direta**, as grandezas crescem juntas: mais produtos, mais dinheiro; mais tempo de trabalho, mais peças produzidas; mais quilômetros, mais combustível. Montamos a proporção mantendo a ordem natural e resolvemos por produto cruzado. Se 5 kg de farinha rendem 40 pães, 8 kg rendem x pães: 5/8 = 40/x, e então x = 64 pães.',
  'Na regra de três **inversa**, uma grandeza cresce enquanto a outra diminui. Mais operários, menos dias; maior velocidade, menor tempo; mais torneiras, menos tempo para encher o tanque. Aqui, invertemos uma das razões antes de igualar. Se 6 operários terminam uma obra em 20 dias, quantos dias levarão 15 operários? Como mais gente reduz o prazo, a relação é inversa: 6/15 = x/20, ou, pela constância do produto, 6 × 20 = 15 × x, resultando em x = 8 dias.',
  'Para decidir se a relação é direta ou inversa, use o teste do dobro: se uma grandeza dobrar, a outra dobra (direta) ou cai pela metade (inversa)? Outra forma é verificar a plausibilidade do resultado. Se você calcula que mais operários levarão mais dias, algo está errado e é hora de rever a classificação. Esse rápido teste de bom senso poupa muitas questões.'] },
 { h:'Regra de três composta', p:[
  'A regra de três composta aparece quando uma grandeza depende de duas ou mais outras ao mesmo tempo. Um exemplo clássico: 8 máquinas produzem 1.200 peças em 5 dias. Quantas peças 10 máquinas produzirão em 6 dias? Aqui, a produção depende do número de máquinas e do número de dias, e ambas são diretamente proporcionais à produção.',
  'O procedimento tem etapas. Primeiro, organize uma tabela com todas as grandezas. Em seguida, tome a grandeza que contém o x como referência e compare, uma de cada vez, com as demais: a relação é direta ou inversa? Se for direta, a razão fica como está; se for inversa, ela é invertida. Por fim, iguale a razão da incógnita ao produto das outras razões. No exemplo, 1.200/x = (8/10) × (5/6), de onde x = 1.800 peças.',
  'Em problemas compostos, a tabela é a melhor amiga. Ela evita que informações se percam e deixa claro o sentido de cada relação. Uma boa prática é analisar cada par separadamente, como se as demais grandezas estivessem fixas, pois a proporcionalidade é sempre avaliada "mantendo o resto constante". Treine com poucos exemplos, mas refaça-os até que o procedimento fique automático.'] },
 { h:'Armadilhas e boas práticas', p:[
  'A principal armadilha é aplicar regra de três onde não há proporcionalidade. Idade e altura de uma criança, por exemplo, não crescem de modo proporcional, e salário e tempo de serviço em carreiras com tabelas especiais também não. Antes de usar o método, confirme que a relação é realmente proporcional, e que o enunciado não esconde um valor fixo (como uma taxa de entrega ou um custo inicial) que quebra a proporcionalidade.',
  'Outro erro frequente é misturar unidades. Se uma grandeza está em horas e a outra em minutos, converta antes de montar a proporção. O mesmo vale para metros e centímetros, litros e mililitros, reais e centavos. Dedique alguns segundos a padronizar as unidades: é um investimento que evita erros bobos.',
  'Por fim, aprenda a simplificar. Antes de multiplicar em cruz, simplifique as frações sempre que possível. Isso reduz as contas e a chance de erro. E, ao terminar, substitua o valor encontrado na proporção original para conferir se a igualdade se mantém. Em questões do ENEM, a conferência rápida costuma ser a diferença entre acertar com segurança e acertar com dúvida.'] },
 { h:'Regra de três no cotidiano e no ENEM', p:[
  'Na prova, a regra de três aparece em contextos como receitas, consumo de energia, rendimento de combustível, produtividade, preços e dosagens de medicamentos. Muitas vezes o enunciado traz informações supérfluas, e a habilidade central é separar o que importa. Leia a pergunta final primeiro, identifique a grandeza desconhecida e só então procure os dados relevantes no texto.',
  'Também é comum que a regra de três seja combinada com outros temas, como porcentagem e escalas. Uma questão pode pedir, por exemplo, o aumento no consumo de água após a instalação de uma nova torneira, ou quanto tempo uma impressora levará para imprimir um certo número de páginas se o ritmo mudar. Nesses casos, resolva por etapas: calcule primeiro a taxa unitária e depois use-a para responder à pergunta.',
  'Uma estratégia valiosa é o método da **unidade**, que consiste em descobrir quanto vale "uma unidade" e depois multiplicar. Se 12 canetas custam R$ 30, uma caneta custa R$ 2,50 e 20 canetas custam R$ 50. Para muitas pessoas esse caminho é mais intuitivo que o produto cruzado, e dá o mesmo resultado. Use o método que lhe der mais segurança, e treine ambos.'] }
]},

{ t:'Porcentagem', txt:[
 { h:'O que significa "por cento"', p:[
  'A palavra porcentagem vem de "por cento", ou seja, de cada cem. Dizer que 30% dos alunos de uma escola vão à pé significa que, em cada 100 alunos, 30 vão à pé. É uma forma de comparar partes de totais diferentes usando sempre a mesma base, o que torna as comparações justas. Matematicamente, 30% é igual à fração 30/100, ao decimal 0,30 e à razão 3 para 10.',
  'Calcular a porcentagem de um valor é multiplicar o valor pela taxa em forma decimal. Para achar 15% de 400, calcula-se 0,15 × 400 = 60. Também dá para pensar por partes: 10% de 400 é 40, 5% é a metade disso, ou 20, e 15% é 40 + 20 = 60. Esse cálculo mental por blocos de 10% e 1% é um dos recursos mais úteis para ganhar tempo na prova.',
  'Para o caminho inverso, descobrir qual porcentagem uma parte representa de um total, divide-se a parte pelo total e multiplica-se por 100. Se 45 dos 180 convidados faltaram, a taxa de faltas foi 45/180 = 0,25, ou 25%. É importante deixar claro qual é o "todo" de referência, pois a mesma parte pode representar porcentagens diferentes dependendo da base escolhida.'] },
 { h:'Aumentos e descontos', p:[
  'Aumentar um valor em uma porcentagem equivale a multiplicá-lo por (1 + taxa). Um aumento de 20% é o mesmo que multiplicar por 1,20; um desconto de 15% é multiplicar por 0,85, pois 1 − 0,15 = 0,85. Esses números são chamados de **fatores de correção** e simplificam bastante as contas, principalmente quando há mais de uma variação seguida.',
  'Um produto de R$ 200 com 10% de desconto custa 200 × 0,90 = R$ 180. Se, depois, o preço for aumentado em 10%, o novo preço é 180 × 1,10 = R$ 198, e não os R$ 200 originais. A razão é que cada porcentagem incide sobre uma base diferente: o desconto incidiu sobre 200 e o aumento incidiu sobre 180. Esse é um dos pontos que mais confundem candidatos e que mais aparece nas provas.',
  'Para saber a variação percentual entre um valor inicial e um final, usa-se (final − inicial) / inicial. Se um salário passou de R$ 2.000 para R$ 2.300, a variação foi 300/2.000 = 0,15, ou seja, aumento de 15%. Se o resultado for negativo, trata-se de redução. A base da conta sempre é o valor inicial, e nunca o final.'] },
 { h:'Variações sucessivas', p:[
  'Quando ocorrem vários aumentos ou descontos em sequência, as porcentagens não se somam, elas se **multiplicam** pelos fatores. Dois aumentos de 10% seguidos equivalem a 1,10 × 1,10 = 1,21, ou seja, 21% de aumento acumulado, e não 20%. Um aumento de 50% seguido de um desconto de 50% leva a 1,5 × 0,5 = 0,75: o valor final é 25% menor que o inicial.',
  'Essa lógica explica por que "ganhar 20% e perder 20%" não devolve o valor original. Também explica o crescimento de investimentos e de populações, em que a taxa incide sobre um valor que já foi modificado. Para resolver problemas desse tipo, multiplique todos os fatores e depois converta o resultado em variação percentual, subtraindo 1 e multiplicando por 100.',
  'Se uma questão perguntar qual desconto único equivale a dois descontos consecutivos, calcule o fator total e subtraia de 1. Dois descontos sucessivos de 20% e 10% dão 0,80 × 0,90 = 0,72, o que corresponde a 28% de desconto total, e não 30%. Essa diferença pode ser decisiva na hora de escolher a alternativa correta.'] },
 { h:'Porcentagem em contextos reais', p:[
  'O tema está presente em notícias, pesquisas eleitorais, rótulos de alimentos, impostos, inflação, taxas de desemprego e de crescimento econômico. Ao interpretar números percentuais, atente para a base de comparação. Um aumento de 100% significa dobrar; uma queda de 100% significa chegar a zero. Já uma queda de 50% seguida de um aumento de 50% não restaura o valor inicial, como vimos.',
  'Também é essencial distinguir **pontos percentuais** de **porcentagem**. Se a taxa de desemprego passa de 8% para 10%, a variação é de 2 pontos percentuais, mas o aumento relativo é de 25%. Textos jornalísticos e questões do ENEM exploram essa diferença com frequência, e confundi-los leva a interpretações equivocadas.',
  'Em pesquisas, a porcentagem costuma vir acompanhada de uma margem de erro. Dizer que um candidato tem 40% das intenções de voto, com margem de erro de 2 pontos para mais ou para menos, significa que o valor real provavelmente está entre 38% e 42%. Saber ler esses números com espírito crítico faz parte da formação cidadã que o exame deseja avaliar.'] },
 { h:'Estratégias para resolver rápido', p:[
  'Algumas estratégias economizam tempo. Calcule 10% movendo a vírgula uma casa à esquerda, e a partir daí obtenha 20%, 5% ou 1%. Use frações conhecidas: 50% é a metade, 25% é um quarto, 20% é um quinto, 75% são três quartos. Em questões com alternativas, estime a resposta antes de calcular para eliminar opções claramente erradas.',
  'Na hora de montar o problema, identifique qual é o valor de referência (100%) e escreva-o explicitamente. Muitos erros nascem de confundir a base: o desconto incide sobre o preço original, o imposto sobre o valor da mercadoria, o lucro pode ser calculado sobre o custo ou sobre a venda. Escreva a frase do enunciado em forma de equação, mesmo que simples.',
  'Para praticar, tente calcular mentalmente porcentagens do seu dia a dia: a gorjeta de 10% em uma conta, o desconto em uma promoção, a parcela do salário que vai para o transporte. A familiaridade com esses cálculos torna o raciocínio mais ágil e confiante, o que ajuda na prova e na vida cotidiana.'] }
]},

{ t:'Juros simples e compostos', txt:[
 { h:'O que são juros', p:[
  'Juros são o preço do dinheiro no tempo. Quem empresta dinheiro cobra uma remuneração por abrir mão de usá-lo durante certo período, e quem toma emprestado paga essa remuneração. O mesmo vale para investimentos: ao aplicar dinheiro, você "empresta" ao banco e recebe juros em troca. Compreender esse mecanismo é fundamental para tomar boas decisões financeiras e é cobrado com frequência no ENEM.',
  'Os elementos básicos são: o **capital** (C), valor inicial emprestado ou aplicado; a **taxa** (i), que indica quanto se cobra em cada período, geralmente em porcentagem ao mês ou ao ano; o **tempo** (t), número de períodos; os **juros** (J), o valor pago pelo uso do dinheiro; e o **montante** (M), soma do capital com os juros. Sempre vale M = C + J.',
  'Um cuidado essencial é manter a taxa e o tempo na mesma unidade. Se a taxa é de 2% ao mês, o tempo deve estar em meses; se for 12% ao ano, o tempo deve estar em anos. Quando as unidades não coincidem, converta o tempo (ou a taxa, nos juros simples) antes de aplicar qualquer fórmula.'] },
 { h:'Juros simples', p:[
  'No regime de juros simples, os juros de cada período incidem sempre sobre o capital inicial. A fórmula é J = C · i · t, e o montante é M = C · (1 + i · t). Se você aplica R$ 1.000 a 2% ao mês durante 6 meses, os juros são 1.000 × 0,02 × 6 = R$ 120, e o montante é R$ 1.120. O valor cresce de forma linear: a cada mês, são acrescentados os mesmos R$ 20.',
  'No gráfico, o montante em função do tempo é uma reta, o que remete à função afim. A taxa de crescimento é constante, e cada período adiciona o mesmo valor. Por isso, os juros simples são mais fáceis de calcular e comparar, e aparecem em situações de curto prazo ou em exercícios didáticos, como multas por atraso em que a taxa é aplicada sobre o valor original.',
  'Ao resolver problemas, identifique o que o enunciado pede: juros, montante, capital, taxa ou tempo. Em seguida, isole a variável desejada na fórmula. Por exemplo, para descobrir o tempo necessário para que um capital de R$ 500 renda R$ 90 de juros a 3% ao mês, usa-se 90 = 500 × 0,03 × t, o que dá t = 6 meses. A prática de isolar variáveis é muito útil.'] },
 { h:'Juros compostos', p:[
  'Nos juros compostos, os juros de cada período são calculados sobre o montante acumulado até o período anterior, ou seja, "juros sobre juros". A fórmula é M = C · (1 + i)ᵗ. Para R$ 1.000 a 2% ao mês durante 6 meses, o montante é 1.000 × 1,02⁶ ≈ R$ 1.126,16. Repare que o ganho foi um pouco maior que no regime simples (R$ 1.120), e a diferença cresce com o tempo.',
  'O crescimento é exponencial: o gráfico do montante é uma curva que sobe cada vez mais rápido. Esse comportamento aparece nos investimentos de longo prazo, nas dívidas de cartão de crédito e cheque especial (em que o custo "explode" quando a dívida não é paga) e em fenômenos como crescimento populacional e propagação de doenças, que seguem o mesmo padrão.',
  'Em problemas de prova, as potências costumam ser fornecidas ou os valores são escolhidos para facilitar a conta, como 1,1², 1,05³ ou 1,02⁶. Se precisar calcular uma potência pequena, faça por multiplicações sucessivas. Para prazos maiores, o enunciado normalmente apresenta uma tabela ou uma aproximação, e o candidato deve apenas aplicar a fórmula corretamente.'] },
 { h:'Comparando simples e composto', p:[
  'Para um mesmo capital e a mesma taxa, os juros compostos rendem mais que os simples quando o tempo é maior que um período. No primeiro período, os dois regimes dão o mesmo resultado. A partir do segundo, os compostos passam a incidir sobre os juros já acumulados e se distanciam. Para tempos menores que um período, a relação se inverte, pois os juros simples tendem a superar os compostos.',
  'Essa comparação explica por que investir cedo e por longo tempo é vantajoso: o efeito dos juros compostos é pequeno no início e grande ao final. Também explica por que dívidas com juros compostos podem se tornar impagáveis. Uma dívida de R$ 1.000 a 10% ao mês dobra em pouco mais de 7 meses, e em um ano chega a mais de R$ 3.100.',
  'Ao ler uma questão, procure palavras-chave. "Juros simples" ou "taxa sobre o capital inicial" indicam regime linear. "Juros compostos", "juros sobre juros" ou "capitalização mensal" indicam regime exponencial. Se o enunciado não especificar, o contexto bancário usual indica juros compostos, mas o texto costuma deixar claro qual regime aplicar.'] },
 { h:'Taxas, parcelamentos e decisões', p:[
  'Duas taxas são **equivalentes** quando, aplicadas ao mesmo capital durante o mesmo tempo, geram o mesmo montante. No regime composto, 1% ao mês não equivale a 12% ao ano, e sim a (1,01)¹² − 1 ≈ 12,68% ao ano. Em juros simples, as taxas proporcionais são também equivalentes, e 1% ao mês corresponde a 12% ao ano. Essa distinção é uma pegadinha clássica.',
  'No dia a dia, vale comparar as alternativas de pagamento. Comprar à vista com desconto ou parcelar "sem juros"? O preço à vista com desconto de 10% corresponde a pagar 90% do valor, e isso pode ser melhor que parcelar, pois o dinheiro tem valor no tempo. Para comparar, leve todos os valores para uma mesma data, usando a taxa de juros que você conseguiria em uma aplicação, e escolha a alternativa com menor valor presente.',
  'Também é importante entender o custo efetivo de financiamentos e cartões. Parcelas aparentemente pequenas podem esconder taxas altas. Calcule o total pago e compare com o valor à vista. A diferença entre os dois mostra o custo dos juros. Desenvolver esse olhar crítico é um dos objetivos de educação financeira, e é cada vez mais cobrado em questões contextualizadas.'] },
 { h:'Dicas para a prova', p:[
  'Antes de calcular, identifique o regime e as unidades de taxa e tempo. Escreva os dados conhecidos: C, i, t e o que se pede. Se a questão envolver parcelas, desenhe uma linha do tempo marcando as datas e os valores, o que ajuda a perceber quando cada pagamento ocorre. Se houver aproximações dadas no enunciado, utilize-as sem refazer a conta por conta própria.',
  'Uma estratégia útil é testar as alternativas, principalmente em problemas de juros compostos com expoentes. Substitua os valores nas fórmulas e veja qual alternativa satisfaz as condições do enunciado. Isso costuma ser mais rápido do que isolar variáveis em equações exponenciais, sobretudo quando o tempo é a incógnita.',
  'Lembre-se de que o ENEM valoriza a interpretação. Em muitas questões, o cálculo é simples e o desafio é reconhecer a situação e escolher o modelo certo. Treine lendo notícias sobre inflação, taxa Selic, financiamentos e investimentos e perguntando-se: qual regime está em jogo? Qual é a taxa? Qual o período? Esse hábito torna o tema bem mais acessível.'] }
]}
];
