/* Matemática: textos corridos, temas 22 a 25 */
module.exports = [
{ t:'Estatística: média, moda e mediana', txt:[
 { h:'Por que a estatística importa', p:[
  'A estatística é o ramo da Matemática que coleta, organiza, resume e interpreta dados. Ela está presente em pesquisas eleitorais, índices de inflação, resultados esportivos, estudos de saúde e relatórios de empresas. Aprender estatística é aprender a ler o mundo com mais senso crítico, percebendo quando um número é representativo e quando pode enganar. Por isso, é um dos temas mais valorizados no ENEM.',
  'Alguns conceitos básicos: a **população** é o conjunto de todos os elementos estudados, e a **amostra** é uma parte dela, escolhida para representar o todo. Uma boa amostra deve ser aleatória e representativa. As **variáveis** podem ser qualitativas (cor, opinião, profissão) ou quantitativas (idade, altura, renda), discretas (contagens) ou contínuas (medidas). Os dados são organizados em **tabelas de frequência**, que mostram quantas vezes cada valor aparece.',
  'A **frequência absoluta** é o número de ocorrências de um valor, e a **frequência relativa** é a proporção em relação ao total, geralmente em porcentagem. Se 12 de 40 alunos têm 17 anos, a frequência relativa é 12/40 = 30%. Para resumir um conjunto de dados em um único número, usam-se as **medidas de tendência central**: média, moda e mediana.'] },
 { h:'Média aritmética, simples e ponderada', p:[
  'A **média aritmética** é a soma dos valores dividida pela quantidade deles. Se as notas de um aluno são 6, 7, 8 e 9, a média é 30/4 = 7,5. Ela representa o valor que cada elemento teria se todos fossem iguais e a soma fosse mantida. É sensível a valores extremos: uma nota muito baixa ou muito alta puxa a média. Por isso, em conjuntos com valores muito discrepantes, a média pode ser enganosa.',
  'Na **média ponderada**, cada valor tem um peso, que indica sua importância. A fórmula é a soma dos produtos valor × peso, dividida pela soma dos pesos. Se uma prova tem peso 3 e um trabalho tem peso 2, e as notas foram 8 e 5, a média é (8·3 + 5·2)/5 = 34/5 = 6,8. O ENEM usa muito essa ideia em critérios de seleção, em que redação, linguagens e matemática têm pesos diferentes.',
  'Em tabelas de frequência, a média é uma média ponderada em que os pesos são as frequências. Se 10 alunos tiraram 5, 20 tiraram 7 e 10 tiraram 9, a média é (5·10 + 7·20 + 9·10)/40 = 280/40 = 7. Também é possível calcular o valor de uma nova observação necessária para atingir certa média. Se a média de 4 provas é 6 e se deseja média 7 em 5 provas, a nota da quinta é 7·5 − 6·4 = 11, o que é impossível em uma escala de 0 a 10.'] },
 { h:'Moda e mediana', p:[
  'A **moda** é o valor que mais se repete em um conjunto de dados. Em 2, 3, 3, 5, 7, 3, a moda é 3. Um conjunto pode ter uma moda (unimodal), duas (bimodal) ou nenhuma, se todos os valores aparecerem com a mesma frequência. É a única medida de tendência central que se aplica a dados qualitativos: a cor mais vendida, o sabor mais pedido, o time com mais torcedores. Em pesquisas de mercado, a moda indica a preferência dominante.',
  'A **mediana** é o valor central do conjunto ordenado. Se o número de elementos é ímpar, é o termo do meio; se é par, é a média dos dois termos centrais. Em 3, 5, 8, 12, 20, a mediana é 8. Em 3, 5, 8, 12, a mediana é (5 + 8)/2 = 6,5. A mediana divide os dados em duas metades iguais e **não é afetada por valores extremos**, o que a torna mais adequada para descrever rendas, preços de imóveis e outros dados com grandes discrepâncias.',
  'Um exemplo: os salários de uma pequena empresa são R$ 2.000, 2.200, 2.300, 2.500 e 20.000. A média é R$ 5.800, mas quase ninguém ganha isso. A mediana é R$ 2.300, que representa melhor o salário típico. Esse tipo de situação é muito explorado em questões, que perguntam qual medida é mais adequada para descrever um conjunto com valores atípicos. Na maior parte dos casos assimétricos, a resposta é a mediana.'] },
 { h:'Medidas de dispersão: variância e desvio padrão', p:[
  'Duas turmas podem ter a mesma média e comportamentos muito diferentes: em uma, todos tiram notas próximas de 7; na outra, metade tira 10 e metade tira 4. As **medidas de dispersão** mostram o quanto os dados se afastam do centro. A mais simples é a **amplitude**, a diferença entre o maior e o menor valor. Ela é fácil de calcular, mas depende apenas dos extremos.',
  'A **variância** é a média dos quadrados dos desvios em relação à média: para cada valor, calcula-se a diferença para a média, eleva-se ao quadrado, e tira-se a média desses quadrados. O **desvio padrão** é a raiz quadrada da variância, e tem a mesma unidade dos dados. Quanto **menor** o desvio padrão, mais concentrados estão os dados em torno da média; quanto maior, mais espalhados. Entre dois conjuntos de mesma média, o de menor desvio é mais regular e consistente.',
  'No ENEM, raramente se exige calcular o desvio padrão para muitos dados, mas é comum pedir qual conjunto tem **maior ou menor desvio padrão** a partir do gráfico ou da tabela, e interpretar o resultado. Por exemplo, ao comparar dois atletas com a mesma média de pontos, o de menor desvio padrão é o mais regular. Saber essa interpretação é mais importante que a conta em si.'] },
 { h:'Interpretação e armadilhas', p:[
  'Ao interpretar estatísticas, pergunte-se: qual medida está sendo usada e por quê? A média foi calculada sobre quem? A amostra é representativa? Dados apresentados com escalas truncadas ou apenas com a média podem dar impressões enganosas. Em notícias, observe se a margem de erro foi informada, e se a pesquisa trata de intenção de voto, de renda ou de outro tema.',
  'Alguns erros comuns: achar que média e mediana são sempre iguais; calcular mediana sem ordenar os dados; considerar a moda como o maior valor; ignorar os pesos em médias ponderadas; e confundir frequência absoluta com relativa. Também é frequente interpretar de forma equivocada o conceito de "média" em enunciados, como imaginar que uma média de 2 filhos por família significa que toda família tem 2 filhos.',
  'Treine com dados do seu cotidiano: notas, gastos mensais, tempo de deslocamento. Calcule média, moda e mediana, e observe como mudam se você inclui um valor extremo. Esse hábito melhora sua intuição, e ajuda a escolher a medida certa na prova. Lembre-se de que a pergunta costuma dizer qual medida usar, ou pedir a mais adequada ao contexto.'] }
]},

{ t:'Gráficos, tabelas e dispersão', txt:[
 { h:'Tabelas: organizar e ler dados', p:[
  'Uma tabela organiza informações em linhas e colunas e é o ponto de partida de qualquer análise de dados. Ao ler uma tabela, observe o título, a unidade de medida, a fonte e o período. Atente para o que cada linha e cada coluna representam, e para se os valores estão em números absolutos, em porcentagens ou em índices. Misturar essas formas é uma das principais causas de erro em interpretação.',
  'Tabelas de **dupla entrada** cruzam duas variáveis, como idade e preferência de lazer. Elas permitem calcular totais por linha e por coluna e porcentagens condicionais. Por exemplo, a porcentagem de homens que preferem esporte é calculada sobre o total de homens, e não sobre o total geral. Identificar a base correta de cálculo é uma habilidade essencial e muito cobrada.',
  'Também é comum que a tabela traga dados de vários períodos. Para analisar a evolução, calcule variações absolutas (diferença) e relativas (porcentagem em relação ao valor inicial). Uma alta de 10 para 15 é um aumento de 5 unidades, ou de 50%. Dependendo da pergunta, uma ou outra forma é a adequada, e é preciso ler com cuidado para saber qual é pedida.'] },
 { h:'Tipos de gráficos e quando usar cada um', p:[
  'O **gráfico de barras ou colunas** compara valores entre categorias, como vendas por produto. O **gráfico de linhas** mostra a evolução de uma grandeza ao longo do tempo, como a temperatura mensal. O **gráfico de setores (pizza)** mostra a participação de cada parte no total, e a soma das fatias é 100%. O **histograma** representa a distribuição de uma variável quantitativa agrupada em intervalos, com barras coladas. Cada tipo é adequado a um objetivo.',
  'Na leitura, comece pelos eixos: quais variáveis, quais unidades, onde começa a escala. Gráficos com eixos que não começam em zero podem exagerar diferenças pequenas, e escalas diferentes entre dois gráficos dificultam a comparação visual. Também observe a legenda, as cores e as anotações. Muitas questões exploram a percepção distorcida, perguntando o que se pode concluir com segurança.',
  'Em gráficos de setores, lembre que o ângulo é proporcional ao valor: 25% corresponde a 90°. Se o gráfico informa o ângulo e não a porcentagem, converta antes de calcular. Em gráficos de linhas, observe os trechos de crescimento, de queda e de estabilidade, e identifique os pontos de máximo e mínimo. Em histogramas, a área das barras (e não só a altura) é proporcional à frequência quando os intervalos têm larguras diferentes.'] },
 { h:'Gráficos de dispersão e correlação', p:[
  'O **gráfico de dispersão** (ou diagrama de dispersão) representa cada observação por um ponto, com uma variável no eixo horizontal e outra no vertical. Ele serve para investigar se existe relação entre duas variáveis, como horas de estudo e nota, ou altura e peso. Se os pontos se alinham em uma tendência crescente, há **correlação positiva**; se a tendência é decrescente, há **correlação negativa**; se os pontos estão espalhados sem padrão, não há correlação aparente.',
  'A **linha de tendência** (ou reta de regressão) resume a relação entre as variáveis e pode ser usada para fazer previsões dentro do intervalo observado. Se a reta indica que, a cada hora a mais de estudo, a nota sobe em média 0,5 ponto, essa é uma interpretação possível, desde que se tenha cuidado: a reta descreve a tendência média, e não garante o resultado para cada indivíduo. Extrapolar muito além dos dados observados também é arriscado.',
  'Uma advertência essencial: **correlação não implica causalidade**. Dois fenômenos podem variar juntos sem que um cause o outro, seja por coincidência, seja porque ambos dependem de um terceiro fator. O consumo de sorvete e o número de afogamentos crescem no verão, mas o sorvete não causa afogamentos; ambos dependem do calor. O ENEM valoriza muito essa leitura crítica, e questões frequentemente perguntam qual conclusão é permitida pelos dados.'] },
 { h:'Distribuições, quartis e box plot', p:[
  'Além de média e mediana, é útil conhecer os **quartis**. O primeiro quartil (Q1) separa os 25% menores valores, a mediana (Q2) separa metade, e o terceiro quartil (Q3) separa os 75% menores. A diferença Q3 − Q1 é a **amplitude interquartil**, que mede a dispersão da parte central dos dados e é menos sensível a valores extremos. Valores muito distantes dos quartis são considerados atípicos (outliers).',
  'O **gráfico de caixa** (box plot) resume essas informações: a caixa vai de Q1 a Q3, com uma linha na mediana, e as "hastes" mostram o alcance dos demais valores. Ao comparar dois box plots, observe a posição das medianas, o tamanho das caixas (dispersão) e a presença de pontos isolados. Uma caixa mais estreita indica dados mais concentrados; uma mediana deslocada para um lado indica assimetria.',
  'Em questões de interpretação, a pergunta costuma ser algo como "em qual dos grupos há maior variabilidade?" ou "qual dos conjuntos tem o maior valor mediano?". Responda comparando os elementos do gráfico, sem calcular. Treine reconhecer a assimetria: se a mediana está mais perto de Q1 e a haste superior é longa, a distribuição tem cauda à direita, com poucos valores muito altos.'] },
 { h:'Como resolver questões de leitura de dados', p:[
  'Adote um roteiro: leia o título e as legendas; identifique as variáveis e as unidades; observe a escala; leia a pergunta com atenção para saber se pede valores absolutos, variações ou porcentagens; extraia os números necessários; calcule; e revise a coerência. Questões com muitos dados costumam pedir apenas uma comparação simples, e o excesso de informação serve para distrair.',
  'Cuidado com armadilhas clássicas: comparar porcentagens de bases diferentes; confundir pontos percentuais com variação percentual; tirar conclusões sobre indivíduos a partir de médias; supor causalidade; ler errado a escala de um eixo (em milhares, em milhões); e desconsiderar valores de anos específicos. Se uma alternativa apresentar conclusão mais forte do que os dados permitem, desconfie.',
  'Por fim, desenvolva o hábito de ler gráficos de jornais e relatórios, perguntando o que se pode ou não concluir. Essa prática aprimora a leitura crítica e transforma o tema, que parece apenas "contas", em uma habilidade de cidadania: a capacidade de questionar números, identificar manipulações e tomar decisões com base em evidências.'] }
]},

{ t:'Análise combinatória', txt:[
 { h:'O princípio fundamental da contagem', p:[
  'A análise combinatória ensina a contar possibilidades sem precisar listá-las. O alicerce é o **princípio multiplicativo**: se uma escolha pode ser feita de m maneiras e, para cada uma, uma segunda escolha pode ser feita de n maneiras, o total de maneiras de fazer as duas escolhas em sequência é m × n. Uma pessoa com 3 camisas e 4 calças tem 12 combinações de roupa. Para escolhas sucessivas, basta multiplicar o número de opções de cada etapa.',
  'Já o **princípio aditivo** vale quando as escolhas são alternativas, isto é, quando se faz uma coisa **ou** outra, e não as duas. Se é possível ir a um destino de ônibus (3 linhas) ou de metrô (2 linhas), há 3 + 2 = 5 formas de chegar. A regra prática é: "e" costuma indicar multiplicação, e "ou" costuma indicar soma, desde que os casos sejam excludentes (não se sobreponham).',
  'Muitos problemas se resolvem apenas com essas duas ideias, desenhando um esquema de "casas" a preencher. Para formar senhas de 3 dígitos distintos com os algarismos de 0 a 9, há 10 opções para a 1ª casa, 9 para a 2ª e 8 para a 3ª, o que dá 720 senhas. Atenção às restrições: se a primeira casa não pode ser zero, comece pela casa mais restrita, para não se confundir.'] },
 { h:'Fatorial, permutações e arranjos', p:[
  'O **fatorial** de n, escrito n!, é o produto dos números de 1 até n: 5! = 5 · 4 · 3 · 2 · 1 = 120. Por convenção, 0! = 1. Ele aparece na contagem de ordenações. Quantas filas diferentes podem ser formadas por 5 pessoas? São 5! = 120, pois há 5 opções para o 1º lugar, 4 para o 2º e assim por diante. A essa contagem de ordenações de todos os elementos damos o nome de **permutação simples**.',
  'Quando há elementos repetidos, a **permutação com repetição** divide por fatoriais: o número de anagramas de MATEMATICA, com 10 letras e repetições (M ×2, A ×3, T ×2), é 10!/(2! · 3! · 2!). Em permutações circulares, em que importa a posição relativa e não a absoluta, o número de maneiras de sentar n pessoas em uma mesa redonda é (n − 1)!, pois girar a mesa não gera um arranjo novo.',
  'Os **arranjos** contam a escolha de p elementos entre n, **quando a ordem importa**: A(n, p) = n!/(n − p)!. Por exemplo, o número de podiums (1º, 2º e 3º lugares) em uma corrida com 8 atletas é A(8, 3) = 8 · 7 · 6 = 336. A ordem importa porque 1º, 2º e 3º lugares são diferentes. Perguntar "a ordem importa?" é a primeira pergunta ao analisar um problema de contagem.'] },
 { h:'Combinações', p:[
  'A **combinação** conta a escolha de p elementos entre n **quando a ordem não importa**: C(n, p) = n!/[p! · (n − p)!]. O número de comissões de 3 pessoas escolhidas entre 8 é C(8, 3) = 56, pois a comissão {Ana, Bia, Caio} é a mesma que {Caio, Ana, Bia}. A diferença em relação aos arranjos é que cada grupo é contado uma única vez, sem distinção da ordem, o que justifica a divisão por p!.',
  'Propriedades úteis: C(n, p) = C(n, n − p), de modo que escolher quem entra é o mesmo que escolher quem fica de fora; C(n, 0) = C(n, n) = 1; e C(n, 1) = n. Com isso, simplificam-se muitas contas. Em problemas, é comum calcular por complemento: o número de grupos com pelo menos uma mulher é o total menos os grupos só com homens. Isso evita somar muitos casos separados.',
  'Exemplos clássicos: números de jogos em um campeonato de pontos corridos (cada par de times se enfrenta uma vez, C(n, 2) jogos), apertos de mão em uma reunião, diagonais de um polígono, combinações de sabores de sorvete e duplas de vôlei. Em cada situação, a pergunta chave é a mesma: a ordem faz diferença? Se não faz, é combinação; se faz, é arranjo ou permutação.'] },
 { h:'Problemas com restrições e estratégias', p:[
  'Problemas com restrições exigem organização. Quando algumas pessoas devem ficar juntas, trate-as como um bloco e permute o bloco internamente. Se duas pessoas não podem ficar juntas, calcule o total e subtraia os casos em que ficam juntas. Se uma posição é reservada a certo elemento, preencha-a primeiro. Em cada caso, a decisão é qual contagem é mais simples: direta ou por complemento.',
  'Exemplo: de quantas maneiras 5 pessoas podem formar uma fila se duas delas, A e B, devem ficar juntas? Tratando AB como bloco, temos 4 elementos (o bloco e as outras 3 pessoas), o que dá 4! = 24 arranjos, e o bloco pode estar em duas ordens (AB ou BA), totalizando 48. Se A e B não podem ficar juntas, são 120 − 48 = 72 maneiras. A estratégia por complemento economiza esforço.',
  'Algumas dicas finais: leia o problema duas vezes para identificar quando a ordem importa; liste um exemplo concreto de uma possibilidade, para compreender o que está sendo contado; use esquemas de casas; evite fórmulas "no automático"; e confira se o resultado é plausível. Combinatória é um tema de raciocínio, e a prática com diferentes tipos de problemas vale mais que a memorização das fórmulas.'] }
]},

{ t:'Probabilidade', txt:[
 { h:'A linguagem da probabilidade', p:[
  'A probabilidade mede a chance de um evento ocorrer, em uma escala de 0 a 1 (ou de 0% a 100%). Um evento impossível tem probabilidade 0, e um evento certo tem probabilidade 1. Em experimentos aleatórios, não sabemos o resultado de antemão, mas conhecemos os resultados possíveis. O conjunto de todos os resultados possíveis é o **espaço amostral**, e um **evento** é um subconjunto dele, como "sair um número par" no lançamento de um dado.',
  'Quando os resultados são **equiprováveis**, isto é, igualmente prováveis, a probabilidade de um evento é o número de casos favoráveis dividido pelo número de casos possíveis: P(A) = n(A)/n(Ω). No lançamento de um dado, a probabilidade de sair um número maior que 4 é 2/6 = 1/3, pois há dois casos favoráveis (5 e 6) entre seis possíveis. Essa definição clássica é a mais usada nas questões do ENEM.',
  'Para aplicar a fórmula, conte corretamente os casos favoráveis e os possíveis, e confirme que os resultados são equiprováveis. Se um dado é viciado ou se as bolas de uma urna têm tamanhos diferentes e uma é mais fácil de ser pega, a definição clássica não vale diretamente. Em problemas de contagem mais difíceis, a análise combinatória fornece as ferramentas para contar casos favoráveis e possíveis.'] },
 { h:'Eventos complementares, união e interseção', p:[
  'O **evento complementar** de A é o conjunto dos resultados em que A não ocorre, e sua probabilidade é P(Aᶜ) = 1 − P(A). Em muitos problemas, é mais fácil calcular a chance do complementar. A probabilidade de "pelo menos uma cara" em 3 lançamentos de moeda é 1 − P(nenhuma cara) = 1 − 1/8 = 7/8. A expressão "pelo menos um" quase sempre indica que o complementar é o caminho mais curto.',
  'Para a **união** de eventos (ocorrer A **ou** B), vale P(A ∪ B) = P(A) + P(B) − P(A ∩ B). Subtrai-se a interseção para não contá-la duas vezes. Se A e B são **mutuamente exclusivos** (não podem ocorrer juntos), a interseção é vazia e a probabilidade da união é a soma simples. A chance de sair 2 ou 5 em um dado é 1/6 + 1/6 = 1/3.',
  'Na **interseção** (ocorrer A **e** B), se os eventos são **independentes**, P(A ∩ B) = P(A) · P(B). A probabilidade de obter duas caras seguidas em dois lançamentos é 1/2 × 1/2 = 1/4. Dois eventos são independentes quando a ocorrência de um não altera a probabilidade do outro, como lançamentos sucessivos de uma moeda ou sorteios com reposição.'] },
 { h:'Probabilidade condicional e eventos dependentes', p:[
  'A probabilidade **condicional** de A dado B, escrita P(A|B), é a probabilidade de A ocorrer sabendo que B ocorreu: P(A|B) = P(A ∩ B)/P(B). Ela surge quando uma informação adicional reduz o espaço amostral. Em uma urna com 3 bolas brancas e 2 pretas, a chance de tirar uma branca na segunda retirada, sem reposição, depende do que saiu na primeira: se saiu branca, restam 2 brancas e 2 pretas, e a chance é 2/4.',
  'Para eventos dependentes, a regra do produto é P(A ∩ B) = P(A) · P(B|A). A probabilidade de tirar duas bolas brancas seguidas, sem reposição, é 3/5 × 2/4 = 3/10. Já com reposição, os eventos são independentes e a probabilidade seria 3/5 × 3/5 = 9/25. A diferença entre "com reposição" e "sem reposição" é um detalhe de leitura que muda a resposta, e é preciso prestar atenção a ele.',
  'Os **diagramas de árvore** ajudam a organizar problemas com vários passos: cada ramo representa uma possibilidade com sua probabilidade, e a probabilidade de um caminho é o produto das probabilidades ao longo dele. A probabilidade de um evento que pode ocorrer por vários caminhos é a soma das probabilidades dos caminhos correspondentes. Esse esquema visual evita erros em questões longas, como as que envolvem exames médicos, com falsos positivos e negativos.'] },
 { h:'Probabilidade e áreas, genética e jogos', p:[
  'Em problemas geométricos, a probabilidade é a razão entre áreas (ou comprimentos, volumes). A chance de um dardo lançado aleatoriamente em um alvo atingir a região central é a área da região central dividida pela área total. Esse tipo de problema une a probabilidade com o cálculo de áreas de círculos e polígonos, e exige que o ponto seja escolhido uniformemente no alvo.',
  'Na **genética**, a probabilidade determina o resultado de cruzamentos. Um casal em que ambos são portadores de um gene recessivo (Aa × Aa) tem 1/4 de chance de ter um filho aa, 1/2 de ter um filho Aa e 1/4 de ter um filho AA. Em questões que unem Matemática e Biologia, usam-se a regra do produto e o princípio da independência para calcular a chance de características combinadas.',
  'Em **jogos** como loterias, a chance de acertar é calculada com combinações: na Mega-Sena simples, a probabilidade de acertar a sena com um jogo de 6 dezenas é 1/C(60, 6) = 1/50.063.860, aproximadamente 2 em 100 milhões. Perceber a ordem de grandeza dessas chances ajuda a avaliar riscos e decisões. Também aparecem questões sobre expectativa e jogos justos, em que a pergunta é se um jogo favorece ou não o apostador.'] },
 { h:'Estratégias, armadilhas e uso no cotidiano', p:[
  'Para resolver questões de probabilidade, escreva o espaço amostral (ou o método de contagem), identifique o evento, verifique se é caso de união, interseção, complementar ou condicional e aplique a regra. Se o problema tem várias etapas, monte a árvore. Se há expressões como "pelo menos", considere o complementar. Se há "com ou sem reposição", ajuste os valores a cada etapa.',
  'Entre as armadilhas, destacam-se: somar probabilidades de eventos que não são mutuamente exclusivos sem subtrair a interseção; multiplicar probabilidades de eventos dependentes como se fossem independentes; tratar como equiprováveis resultados que não o são (como a soma de dois dados, em que 7 é mais provável que 2); e esquecer que a probabilidade total deve somar 1. Também é comum confundir P(A|B) com P(B|A).',
  'A probabilidade é uma ferramenta fundamental para decidir sob incerteza: avaliar riscos, interpretar previsões do tempo ("70% de chance de chuva" não significa que choverá em 70% da cidade), exames de saúde e seguros. Ter noção de probabilidade protege contra intuições erradas, como a "falácia do apostador", a ideia de que, após uma sequência de caras, a coroa "precisa" aparecer. Lançamentos independentes não têm memória, e isso é o mais importante a lembrar.'] }
]}
];
