/* Matemática: textos corridos, temas 16 a 18 */
module.exports = [
{ t:'Progressões: PA e PG', txt:[
 { h:'Sequências e padrões', p:[
  'Uma sequência é uma lista ordenada de números, como 2, 4, 6, 8, ... ou 3, 6, 12, 24, .... Cada número ocupa uma posição, e identificar a regra que liga os termos permite prever os próximos e calcular termos distantes sem listar tudo. Entre as sequências mais estudadas estão as **progressões**, em que a passagem de um termo ao seguinte segue um padrão constante: somar sempre o mesmo valor (progressão aritmética) ou multiplicar sempre pelo mesmo fator (progressão geométrica).',
  'Os termos são representados por a₁, a₂, a₃, ..., aₙ, em que o índice indica a posição. Para trabalhar com problemas, é essencial distinguir **posição** de **valor**: o 5º termo é a₅, e seu valor pode ser qualquer número. Muitas questões pedem, por exemplo, "o valor do 20º termo" ou "a posição do termo que vale 100". Ter clareza dessa diferença evita confusões e ajuda a montar as equações corretamente.',
  'Reconhecer o padrão é o primeiro passo. Se a diferença entre termos consecutivos é constante, trata-se de PA. Se a razão entre eles é constante, é uma PG. Se nenhuma das duas ocorre, outra regra está em jogo. Em situações do cotidiano, a PA modela crescimentos lineares (poupar sempre o mesmo valor por mês), e a PG modela crescimentos proporcionais (juros compostos, populações).'] },
 { h:'Progressão aritmética (PA)', p:[
  'Na PA, cada termo é obtido somando uma constante r, chamada **razão**, ao termo anterior: aₙ₊₁ = aₙ + r. Se r > 0, a PA é crescente; se r < 0, decrescente; se r = 0, constante. A sequência 5, 8, 11, 14 é uma PA de razão 3. O **termo geral** é aₙ = a₁ + (n − 1) · r, que permite calcular qualquer termo diretamente. O 20º termo dessa PA é 5 + 19 × 3 = 62.',
  'Uma propriedade útil: em uma PA, cada termo (exceto os extremos) é a **média aritmética** dos vizinhos, e a soma de termos equidistantes dos extremos é constante. Isso leva à fórmula da **soma dos n primeiros termos**: Sₙ = (a₁ + aₙ) · n / 2. Foi com esse raciocínio que o jovem Gauss, segundo a história, somou rapidamente os números de 1 a 100: 50 pares de soma 101, resultando em 5.050.',
  'Aplicações comuns: um atleta que aumenta a distância treinada em 2 km por semana, uma escada cujos degraus têm alturas crescentes, uma fileira de cadeiras em um auditório em que cada fileira tem mais lugares que a anterior. Nesses problemas, identifique a razão, o primeiro termo e o número de termos, e use as fórmulas. Pergunte-se se o enunciado quer um termo específico ou uma soma.'] },
 { h:'Progressão geométrica (PG)', p:[
  'Na PG, cada termo é obtido multiplicando o anterior por uma constante q, a **razão**: aₙ₊₁ = aₙ · q. A sequência 3, 6, 12, 24 é uma PG de razão 2. O termo geral é aₙ = a₁ · qⁿ⁻¹. Assim, o 8º termo é 3 · 2⁷ = 384. Se q > 1 e a₁ > 0, a PG é crescente e cresce cada vez mais rápido; se 0 < q < 1, é decrescente e tende a zero; se q < 0, os sinais se alternam.',
  'A **soma dos n primeiros termos** é Sₙ = a₁ · (qⁿ − 1)/(q − 1), para q diferente de 1. Para PG com 0 < q < 1 e infinitos termos, a soma converge para S = a₁/(1 − q). Por exemplo, 1 + 1/2 + 1/4 + 1/8 + ... tem soma 2. Esse resultado aparece em problemas de movimentos que se repetem com redução, como uma bola que quica e sobe a cada vez uma fração da altura anterior.',
  'O **termo médio** de uma PG de três termos consecutivos a, b, c satisfaz b² = a · c, ou seja, b é a média geométrica dos extremos. Essa propriedade resolve problemas em que se pede o valor que falta em uma sequência de três termos em PG. Lembre que o produto de termos equidistantes dos extremos também é constante, ao passo que a soma é constante na PA.'] },
 { h:'Relações com outras funções e aplicações', p:[
  'A PA é a versão discreta da função afim: aₙ = a₁ + (n − 1)r é uma função afim de n, definida apenas para valores inteiros. Os pontos (n, aₙ) estão alinhados sobre uma reta. A PG é a versão discreta da função exponencial: aₙ = a₁ · qⁿ⁻¹, e seus pontos acompanham uma curva exponencial. Essa relação ajuda a decidir qual modelo usar em um problema: variação constante leva à PA; variação proporcional leva à PG.',
  'Em finanças, juros simples geram PA (montante cresce em quantia fixa) e juros compostos geram PG (montante cresce em fator fixo). Em demografia e biologia, populações com crescimento proporcional seguem PG. Em planejamento de treinos, estacionamentos escalonados e pagamentos com acréscimo fixo, a PA é a ferramenta natural. Reconhecer essas situações é o ponto mais valioso do tema.',
  'Um problema típico: uma pessoa deposita R$ 100 no primeiro mês e aumenta o depósito em R$ 20 a cada mês. Quanto terá depositado em 12 meses? Trata-se de PA com a₁ = 100, r = 20 e n = 12. O último termo é a₁₂ = 100 + 11 × 20 = 320, e a soma é (100 + 320) × 12/2 = 2.520. Fazer uma tabela com os primeiros termos ajuda a confirmar que a sequência está sendo interpretada corretamente.'] },
 { h:'Estratégias e cuidados', p:[
  'Antes de aplicar uma fórmula, escreva os três ou quatro primeiros termos e confirme se a diferença ou a razão é constante. Em seguida, anote os dados: a₁, r (ou q), n e o que se pede. Muitos erros nascem de contar mal o número de termos: de 5 a 20 existem 16 termos, e não 15. Use a fórmula n = (aₙ − a₁)/r + 1 para obter n em uma PA quando conhecidos o primeiro e o último termos.',
  'Em problemas com sequências que se repetem (calendário, ciclos, andares), pense em **periodicidade** e use o resto da divisão. Se uma sequência de cores se repete a cada 4 posições, a cor da posição 50 é a mesma da posição 2, pois 50 deixa resto 2 na divisão por 4. Esse raciocínio aparece em questões de padrões e pode ser resolvido sem fórmulas de PA ou PG.',
  'Por fim, valide o resultado com a realidade: se a PG fornece uma população de milhões a partir de poucas unidades em poucas gerações, confira se o crescimento é plausível. E treine a transição entre linguagem verbal e simbólica: "a cada ano, 10% a mais" é PG de razão 1,1; "a cada mês, R$ 50 a mais" é PA de razão 50. Com isso, o tema se torna previsível e seguro.'] }
]},

{ t:'Ângulos, triângulos e polígonos', txt:[
 { h:'Ângulos: conceitos e relações', p:[
  'Um ângulo é a abertura entre duas semirretas que partem de um mesmo ponto, o vértice. É medido em **graus**, em que uma volta completa tem 360°. Um ângulo reto mede 90°, um ângulo raso mede 180°, ângulos menores que 90° são **agudos** e os maiores que 90° e menores que 180° são **obtusos**. Dois ângulos são **complementares** quando somam 90° e **suplementares** quando somam 180°.',
  'Há relações importantes que aparecem com frequência. Ângulos **opostos pelo vértice**, formados quando duas retas se cruzam, são iguais. Quando uma reta transversal corta duas retas paralelas, formam-se pares de ângulos **correspondentes** (iguais), **alternos internos** (iguais) e **colaterais internos** (suplementares). Esses pares permitem descobrir medidas desconhecidas em figuras com retas paralelas, e são a base de muitas questões de geometria plana.',
  'Também é comum converter entre graus, minutos e segundos (1° = 60′ e 1′ = 60″) ou lidar com horários em relógios. O ângulo entre os ponteiros de um relógio é um exemplo clássico: o ponteiro das horas anda 30° por hora, e o dos minutos anda 6° por minuto. Às 3h, o ângulo é 90°; às 6h, é 180°. Para horários intermediários, lembre que o ponteiro das horas também se desloca.'] },
 { h:'Triângulos: classificação e propriedades', p:[
  'O triângulo é o polígono mais simples e mais importante da geometria. Quanto aos lados, pode ser **equilátero** (três lados iguais), **isósceles** (dois lados iguais) ou **escaleno** (três lados diferentes). Quanto aos ângulos, é **acutângulo** (três ângulos agudos), **retângulo** (um ângulo reto) ou **obtusângulo** (um ângulo obtuso). Reconhecer o tipo ajuda a escolher as relações e fórmulas adequadas.',
  'A propriedade mais conhecida é que a **soma dos ângulos internos** de um triângulo é 180°. Além disso, o **ângulo externo** é igual à soma dos dois ângulos internos não adjacentes a ele. Em um triângulo isósceles, os ângulos da base são iguais; no equilátero, todos os ângulos medem 60°. Esses fatos permitem resolver problemas de "descubra o ângulo" combinando várias etapas.',
  'Outra propriedade essencial é a **desigualdade triangular**: em qualquer triângulo, cada lado é menor que a soma dos outros dois e maior que a diferença entre eles. Com ela se decide se três medidas podem formar um triângulo: 3, 4 e 8 não formam, pois 3 + 4 < 8. Em questões práticas, como determinar o comprimento possível de um terceiro lado de uma cerca triangular, essa regra delimita o intervalo de valores aceitáveis.'] },
 { h:'Pontos notáveis e linhas do triângulo', p:[
  'Em todo triângulo existem quatro pontos notáveis. O **baricentro** é o encontro das medianas (segmentos do vértice ao ponto médio do lado oposto) e é o centro de gravidade; ele divide cada mediana na razão 2 para 1. O **incentro** é o encontro das bissetrizes e é o centro da circunferência inscrita. O **circuncentro** é o encontro das mediatrizes e é o centro da circunferência circunscrita. O **ortocentro** é o encontro das alturas.',
  'No ENEM, esses pontos aparecem em contextos de aplicação: onde posicionar uma torre de forma equidistante de três cidades (circuncentro), onde apoiar uma placa triangular para que fique em equilíbrio (baricentro), onde instalar um posto de modo a ficar equidistante de três ruas que formam um triângulo (incentro). Associar o conceito geométrico à situação prática é a chave para acertar sem decorar definições.',
  'Para triângulos retângulos, vale lembrar que o circuncentro está no ponto médio da hipotenusa. A mediana relativa à hipotenusa mede metade da hipotenusa. Essas propriedades simplificam problemas com distâncias e raios. Já a **altura** é essencial no cálculo da área: A = base × altura / 2, que será retomada no estudo de áreas e perímetros.'] },
 { h:'Polígonos: ângulos e diagonais', p:[
  'Polígonos são figuras planas fechadas formadas por segmentos de reta. São **regulares** quando têm todos os lados e todos os ângulos iguais (quadrado, triângulo equilátero, hexágono regular). A soma dos ângulos internos de um polígono convexo de n lados é S = (n − 2) × 180°. Assim, um quadrilátero soma 360°, um pentágono, 540°, e um hexágono, 720°. A soma dos ângulos **externos** de qualquer polígono convexo é sempre 360°.',
  'Em um polígono regular, cada ângulo interno mede (n − 2) × 180° / n e cada ângulo externo mede 360°/n. O hexágono regular tem ângulo interno de 120°, o que explica por que ladrilhos hexagonais encaixam em grupos de três nos vértices (3 × 120° = 360°) e formam favos de mel sem deixar vão. Quadrados (4 × 90°) e triângulos equiláteros (6 × 60°) também preenchem o plano. Pentágonos regulares não, pois 108° não divide 360°.',
  'O número de **diagonais** de um polígono de n lados é d = n(n − 3)/2. Para um hexágono, d = 6 × 3/2 = 9. Essa fórmula vem do fato de cada vértice se ligar a n − 3 outros (não conta ele mesmo nem os dois vizinhos) e de cada diagonal ser contada duas vezes. Problemas de torneios, apertos de mão e ligações entre pontos usam raciocínios parecidos, em combinatória.'] },
 { h:'Quadriláteros e aplicações práticas', p:[
  'Entre os quadriláteros, destacam-se o **paralelogramo** (lados opostos paralelos), o **retângulo** (paralelogramo com ângulos retos), o **losango** (paralelogramo com lados iguais), o **quadrado** (retângulo e losango ao mesmo tempo) e o **trapézio** (apenas um par de lados paralelos). Cada um tem propriedades próprias: nas diagonais do paralelogramo, o ponto de encontro é o ponto médio de ambas; no losango, as diagonais são perpendiculares; no retângulo, as diagonais são iguais.',
  'Essas propriedades aparecem em situações concretas: estruturas de telhados e pontes, que usam triângulos pela rigidez; pisos e azulejos que encaixam em padrões; mosaicos e tangram. Saber que o triângulo é a única figura rígida (não se deforma sem alterar os lados) explica por que treliças de aço são formadas por triângulos. Esses contextos são típicos das questões que ligam geometria à arquitetura e à engenharia.',
  'Para resolver, desenhe sempre a figura, marque os dados e deduza o que for possível. Em problemas com muitos ângulos, nomeie-os com letras e escreva as equações a partir das relações conhecidas (soma de 180° em triângulos, 360° em quadriláteros, ângulos de retas paralelas). Resolver o sistema resultante dá as medidas procuradas. A calma para organizar a figura vale mais do que a pressa para calcular.'] }
]},

{ t:'Áreas e perímetros', txt:[
 { h:'Perímetro e área: duas ideias diferentes', p:[
  'O **perímetro** é a medida do contorno de uma figura, a soma dos comprimentos dos seus lados. Ele responde perguntas como "quanto de cerca é necessário?" ou "quanto rodapé comprar?". A **área** mede a superfície interna, o espaço ocupado pela figura. Responde perguntas como "quanto de piso comprar?" ou "quanta tinta usar?". Confundir as duas é um dos erros mais comuns do tema, e a pergunta do enunciado deve ser lida com atenção.',
  'O perímetro é medido em unidades de comprimento (m, cm), e a área, em unidades de comprimento ao quadrado (m², cm²). É possível ter figuras de mesmo perímetro e áreas diferentes: um retângulo de 4 por 6 e um quadrado de 5 por 5 têm perímetro 20, mas áreas 24 e 25. Figuras de mesma área também podem ter perímetros distintos. Entre os retângulos de mesmo perímetro, o quadrado é o de maior área.',
  'Antes de calcular, verifique as unidades. Se um lado está em metros e outro em centímetros, converta antes de multiplicar. Ao converter áreas, lembre que o fator é elevado ao quadrado: 1 m² = 10.000 cm². Em problemas de compra de material, considere também a perda e o arredondamento para cima, pois não se compra metade de uma caixa de piso ou lata de tinta.'] },
 { h:'Fórmulas das principais figuras', p:[
  'Retângulo: A = base × altura. Quadrado: A = lado². Paralelogramo: A = base × altura (altura é a distância perpendicular entre as bases, e não o lado inclinado). Triângulo: A = base × altura / 2. Trapézio: A = (base maior + base menor) × altura / 2. Losango: A = (diagonal maior × diagonal menor)/2. Círculo: A = πr², e a circunferência (perímetro do círculo) é C = 2πr.',
  'Triângulos equiláteros de lado l têm altura h = l√3/2 e área A = l²√3/4. Para triângulos quaisquer com dois lados a e b e ângulo θ entre eles, A = (a · b · senθ)/2. A **fórmula de Herão** calcula a área quando só os três lados são conhecidos, mas aparece raramente. Em polígonos regulares, a área é metade do perímetro vezes o **apótema** (distância do centro ao lado).',
  'Para figuras irregulares, a estratégia é **decompor** em figuras conhecidas (retângulos, triângulos, trapézios), calcular cada área e somar, ou **completar** a figura a um retângulo maior e subtrair o que sobra. Esse método de decomposição resolve a maioria das questões de áreas compostas, como plantas de casas com recortes e terrenos com formas diferentes.'] },
 { h:'Circunferência, círculo, setores e coroas', p:[
  'A circunferência é o conjunto dos pontos que estão a uma mesma distância (o raio) de um centro. Seu comprimento é C = 2πr, e a área do círculo é A = πr². O número π é aproximadamente 3,14 (em muitas questões se usa 3). Um erro frequente é trocar as fórmulas: lembre que comprimento tem dimensão 1 (r), e área tem dimensão 2 (r²).',
  'Um **setor circular** é uma "fatia de pizza". Sua área é proporcional ao ângulo central: A = (θ/360°) × πr², e o comprimento do arco é L = (θ/360°) × 2πr. Quando o ângulo é 90°, o setor é um quarto do círculo; quando é 180°, é metade. Já a **coroa circular** é a região entre duas circunferências concêntricas, com área A = π(R² − r²), em que R é o raio maior e r, o raio menor.',
  'Aplicações são frequentes: jardins circulares, rodas, pistas de atletismo, pizzas e relógios. Para comparar duas pizzas, lembre que, se o diâmetro dobra, a área quadruplica, pois depende do quadrado do raio. Assim, uma pizza de 40 cm rende o quádruplo de uma de 20 cm, e nem sempre o preço acompanha. Esse raciocínio de proporcionalidade ao quadrado é uma habilidade valiosa.'] },
 { h:'Comparações, variações e proporcionalidade', p:[
  'Se todas as medidas lineares de uma figura são multiplicadas por k, o perímetro é multiplicado por k, mas a área é multiplicada por k². Um terreno ampliado com lados duas vezes maiores terá o dobro do perímetro e o quádruplo da área. Essa relação explica fenômenos como o fato de que animais pequenos perdem calor mais rapidamente do que os grandes (maior razão superfície/volume).',
  'Em problemas de variação percentual, converta para fatores. Se o lado de um quadrado aumenta 10%, o novo lado é 1,1l e a nova área é (1,1)²l² = 1,21l², isto é, 21% maior que a original. Não é um aumento de 10%. Essa conta com fatores de correção é bastante cobrada: o aumento percentual da área é diferente do aumento percentual dos lados.',
  'Também aparecem problemas de otimização com áreas, como o já comentado do retângulo de maior área com perímetro fixo. A solução é quase sempre o quadrado, o que pode ser demonstrado com funções quadráticas. Em contextos de cercas e piscinas, a ideia ajuda a escolher dimensões que utilizam melhor o material disponível, o que dá sentido prático ao estudo.'] },
 { h:'Como resolver questões de área', p:[
  'Um bom roteiro: leia o enunciado e identifique se o pedido é área ou perímetro; desenhe a figura e marque as medidas; verifique se é preciso decompor; converta unidades; aplique as fórmulas; confira o resultado. Em questões com figuras no enunciado, observe com atenção a legenda e se a figura está ou não em escala. Muitas vezes, uma medida está indicada no desenho e não no texto.',
  'Em problemas de revestimento, calcule a área total e divida pela área de cada peça (azulejo, piso). Em questões de tinta, divida a área pela cobertura por litro e arredonde para cima. Em problemas de terrenos, converta para hectares quando necessário (1 ha = 10.000 m²). Lembre-se de somar a perda de material quando o texto mencionar.',
  'Treine decompondo figuras do cotidiano: a planta do seu quarto, a quadra de uma escola, um jardim. Estime medidas e calcule áreas aproximadas. Esse treino conecta a Matemática ao mundo real, desenvolve noção de grandeza e deixa você mais confortável com as questões que usam contextos práticos, que são a grande maioria na prova.'] }
]}
];
