/* Matemática: textos corridos, temas 13 a 15 */
module.exports = [
{ t:'Função afim (1º grau)', txt:[
 { h:'A função afim e o seu significado', p:[
  'A função afim tem a forma f(x) = ax + b, em que a e b são números reais e a é diferente de zero. Ela descreve situações em que uma grandeza varia **em quantidade constante**: a cada unidade a mais de x, o valor de y aumenta (ou diminui) sempre o mesmo tanto. É o modelo da corrida de táxi (bandeirada mais valor por quilômetro), do plano de celular com franquia fixa, do salário com parte fixa mais comissão e do tanque que esvazia com vazão constante.',
  'Os dois números têm papéis bem definidos. O coeficiente **b** é o valor inicial, ou seja, o valor de y quando x = 0, e corresponde ao ponto em que a reta corta o eixo vertical. O coeficiente **a** é a **taxa de variação**: indica quanto y muda para cada aumento de 1 unidade em x. No exemplo do táxi com bandeirada de R$ 5 e R$ 2 por quilômetro, temos f(x) = 2x + 5, com a = 2 e b = 5.',
  'Quando b = 0, a função é chamada de **linear** e representa proporcionalidade direta: f(x) = ax. Seu gráfico passa pela origem. Já a função afim com b diferente de zero tem gráfico deslocado verticalmente. Reconhecer se existe um valor inicial no problema é o que permite distinguir um modelo linear de um afim, e saber qual dos dois escolher é uma habilidade importante em questões de modelagem.'] },
 { h:'O gráfico e o que cada elemento revela', p:[
  'O gráfico de uma função afim é sempre uma **reta**. Para traçá-la, bastam dois pontos. Costuma-se usar o ponto em que x = 0, que é (0, b), e o ponto em que y = 0, que é (−b/a, 0), a raiz da função. A raiz indica o valor de x em que a grandeza se anula: o instante em que um tanque esvazia, a quantidade vendida em que o lucro é zero ou a temperatura em que um líquido muda de comportamento.',
  'O sinal de **a** determina a direção da reta. Se a > 0, a função é crescente: ao aumentar x, y aumenta, e a reta sobe da esquerda para a direita. Se a < 0, a função é decrescente: a reta desce. Quanto maior o valor absoluto de a, mais inclinada é a reta, o que significa variação mais rápida. Se a fosse zero, teríamos uma função constante, com reta horizontal, que não é considerada afim propriamente dita.',
  'A partir do gráfico, é possível reconstruir a lei da função. Se a reta passa por (0, 3) e (2, 11), o coeficiente b é 3 e a taxa é (11 − 3)/(2 − 0) = 4, logo f(x) = 4x + 3. Em geral, a = (y₂ − y₁)/(x₂ − x₁), a razão entre a variação vertical e a variação horizontal. Esse cálculo da taxa de variação é um dos procedimentos mais cobrados nas questões do tema.'] },
 { h:'Como encontrar a lei de uma função afim', p:[
  'Em muitos problemas, o enunciado fornece informações em palavras ou em uma tabela, e é preciso escrever a lei. Se há um valor fixo e um valor por unidade, a lei sai direto: "R$ 30 de assinatura mais R$ 0,25 por mensagem" resulta em f(x) = 0,25x + 30. Se são dados dois pares de valores, calcule a taxa a pela razão das variações e depois use um dos pares para achar b.',
  'Por exemplo, uma loja informa que 10 unidades custam R$ 70 e 25 unidades custam R$ 145. A taxa é (145 − 70)/(25 − 10) = 75/15 = 5 reais por unidade. Substituindo no primeiro ponto, 70 = 5 · 10 + b, logo b = 20. A lei é f(x) = 5x + 20, em que 20 é um custo fixo e 5 é o preço unitário. Interpretar os coeficientes dessa forma ajuda a verificar se o resultado é plausível.',
  'Em tabelas, verifique se a diferença entre valores consecutivos de y é constante quando x aumenta em passos iguais. Se for, a função é afim e essa diferença é a taxa a. Esse teste rápido ajuda a decidir se o modelo afim é adequado ou se se trata de outro tipo de função, como exponencial ou quadrática, em que as diferenças não são constantes.'] },
 { h:'Aplicações: comparações e pontos de equilíbrio', p:[
  'Uma das aplicações mais comuns é comparar duas opções de preço. Dois planos de academia, por exemplo: o plano A custa R$ 100 de matrícula mais R$ 50 por mês, e o plano B custa R$ 0 de matrícula mais R$ 70 por mês. As funções são A(x) = 50x + 100 e B(x) = 70x. Igualando as duas, 50x + 100 = 70x, obtemos x = 5. Até 5 meses, o plano B é mais barato; depois disso, o plano A compensa. O ponto de interseção das retas é o ponto de equilíbrio.',
  'Outro uso é determinar quando uma grandeza atinge determinado valor. Se um reservatório com 800 litros perde 20 litros por minuto, o volume é V(t) = 800 − 20t, e ele esvazia quando V = 0, isto é, em t = 40 minutos. Se a pergunta for "quando restarão 300 litros?", resolve-se 800 − 20t = 300, o que dá t = 25 minutos. Reconhecer a pergunta e traduzi-la em uma equação simples é o essencial.',
  'Também é comum calcular lucro como diferença entre receita e custo. Se a receita é R(x) = 12x e o custo é C(x) = 7x + 600, o lucro é L(x) = 5x − 600, que só se torna positivo para x maior que 120 unidades. Chamar esse ponto de "ponto de equilíbrio" ajuda a entender o significado econômico: é o número mínimo de vendas necessário para que a empresa deixe de ter prejuízo.'] },
 { h:'Armadilhas e dicas de prova', p:[
  'As armadilhas mais comuns envolvem a interpretação dos coeficientes. É frequente confundir a taxa a com o valor inicial b, ou esquecer de que a taxa precisa ter unidade (reais por quilômetro, litros por minuto). Em questões que apresentam gráficos, observe se os eixos começam em zero e se as escalas são iguais; uma escala distorcida pode dar a falsa impressão de que a reta é mais ou menos inclinada.',
  'Outro erro é aplicar o modelo afim fora do intervalo em que é válido. Um tanque não pode ter volume negativo, e uma produção não pode ser fracionária. Avalie sempre o domínio: valores de x que não fazem sentido na situação devem ser descartados, mesmo que a fórmula permita calculá-los. Se o enunciado diz que a taxa é constante "até" certo limite, o modelo deve ser usado só até ele.',
  'Para resolver rapidamente, estime o comportamento da reta. Se a é positivo e grande, o valor sobe rápido; se b é grande, o ponto de partida é alto. Ao testar alternativas em questões de múltipla escolha, substitua x = 0 para checar b e outro valor para checar a. Com essa prática, a função afim, que é a base de todo o estudo de funções, se torna uma das partes mais seguras da prova.'] }
]},

{ t:'Função quadrática', txt:[
 { h:'A função quadrática e sua parábola', p:[
  'A função quadrática tem a forma f(x) = ax² + bx + c, com a diferente de zero. Seu gráfico é uma **parábola**, uma curva simétrica que lembra o desenho de um arco. Diferentemente da função afim, a variação aqui não é constante: a grandeza cresce devagar, acelera, atinge um ponto extremo e depois inverte o comportamento. Por isso, a quadrática descreve bem fenômenos que têm um "melhor momento", como o lançamento de uma bola ou o lucro em função do preço.',
  'O sinal do coeficiente a define a **concavidade**. Se a > 0, a parábola é voltada para cima, e o vértice é o ponto de **mínimo**. Se a < 0, é voltada para baixo, e o vértice é o ponto de **máximo**. O coeficiente c indica onde a curva corta o eixo y (quando x = 0), pois f(0) = c. Já o coeficiente b influencia a posição horizontal do vértice, em conjunto com a.',
  'A parábola é simétrica em relação a uma reta vertical que passa pelo vértice, chamada de eixo de simetria. Isso significa que, para dois valores de x equidistantes do eixo, a função tem o mesmo valor. Essa propriedade ajuda em questões que fornecem dois pontos de mesma altura e pedem o vértice, pois a coordenada x do vértice fica exatamente no meio entre eles.'] },
 { h:'Raízes, vértice e os principais cálculos', p:[
  'As **raízes** (ou zeros) da função são os valores de x em que f(x) = 0, encontradas pela fórmula de Bhaskara: x = (−b ± √Δ)/2a, com Δ = b² − 4ac. Graficamente, são os pontos em que a parábola cruza o eixo x. Se Δ > 0, há duas raízes e a curva cruza o eixo em dois pontos; se Δ = 0, a parábola toca o eixo em um ponto (o vértice); se Δ < 0, não há raízes reais e a curva não toca o eixo.',
  'O **vértice** tem coordenadas xᵥ = −b/(2a) e yᵥ = −Δ/(4a). O xᵥ também é a média das raízes, quando elas existem. O yᵥ é o valor máximo ou mínimo da função. Em um problema de otimização, esses são os números que respondem à pergunta "qual o valor de x que maximiza (ou minimiza) a grandeza?" e "qual é esse valor máximo (ou mínimo)?". Decorar essas duas fórmulas poupa muito tempo.',
  'Por exemplo, em f(x) = −x² + 6x − 5, temos a = −1, b = 6 e c = −5. O vértice tem xᵥ = −6/(−2) = 3 e yᵥ = f(3) = −9 + 18 − 5 = 4. A concavidade é para baixo, então 4 é o valor máximo. As raízes são x = 1 e x = 5, simétricas em relação a x = 3. Nessa função, o gráfico sobe de x = 1 até x = 3, atinge o pico de altura 4 e desce até x = 5.'] },
 { h:'Problemas de máximo e mínimo', p:[
  'Os problemas de otimização estão entre os mais cobrados. Um exemplo: um fazendeiro quer cercar um terreno retangular usando 100 m de cerca. Se um lado mede x, o outro mede 50 − x, e a área é A(x) = x(50 − x) = −x² + 50x. O máximo ocorre em xᵥ = 25, e a área máxima é 25 × 25 = 625 m². A conclusão, que o quadrado é o retângulo de maior área para um perímetro fixo, é um resultado clássico.',
  'Em problemas de lucro, a receita costuma ser o produto do preço pelo número de vendas, e este diminui quando o preço sobe. Se R(p) = p(200 − 4p) = −4p² + 200p, o preço que maximiza a receita é pᵥ = 200/8 = 25, e a receita máxima é R(25) = 25 × 100 = 2.500. Esse tipo de modelo representa bem o dilema entre cobrar mais por unidade e vender menos unidades.',
  'Para resolver, siga três passos: escreva a grandeza a otimizar em função de uma única variável, identifique os coeficientes da quadrática e use a fórmula do vértice. Depois, interprete a resposta: o valor de x que maximiza e o valor máximo são coisas diferentes, e a pergunta do enunciado indica qual delas é pedida. Verifique também se o x encontrado pertence ao domínio permitido pelo problema.'] },
 { h:'Lançamentos e movimento', p:[
  'Na Física, a altura de um objeto lançado verticalmente é uma função quadrática do tempo: h(t) = h₀ + v₀t − (g/2)t², onde g é a aceleração da gravidade. Aqui, as raízes dão o momento em que o objeto toca o solo, e o vértice indica o instante e a altura do ponto mais alto. Questões do ENEM costumam fornecer a lei da função e pedir a altura máxima, o tempo de subida ou o instante em que o objeto volta ao nível inicial.',
  'Por exemplo, h(t) = −5t² + 20t. As raízes são t = 0 e t = 4, indicando que o objeto sai do chão e retorna após 4 segundos. O vértice está em t = 2, quando h = −20 + 40 = 20, ou seja, 20 metros. A simetria da parábola mostra que o tempo de subida (2 s) é igual ao de descida (2 s), um resultado coerente com o movimento real, sem resistência do ar.',
  'Também se usam parábolas em antenas parabólicas, faróis de carro, pontes suspensas e arcos arquitetônicos. Em cada caso, a lei é fornecida, ou o gráfico é descrito, e as perguntas giram em torno de alturas, larguras e pontos particulares. Reconhecer a forma da parábola e saber ler vértice e raízes dá conta de grande parte dessas questões.'] },
 { h:'Análise de sinais e estratégias', p:[
  'Estudar o **sinal** da função significa saber para quais valores de x ela é positiva, negativa ou nula. Para a > 0 e duas raízes x₁ < x₂, a função é negativa entre as raízes e positiva fora delas. Para a < 0, ocorre o contrário. Essa análise resolve inequações do 2º grau, como x² − 5x + 6 < 0, cuja solução é 2 < x < 3. Desenhar um esboço rápido da parábola facilita bastante a leitura.',
  'Algumas dicas para a prova: identifique logo o sinal de a, que diz se a resposta é um máximo ou um mínimo; calcule o vértice antes de qualquer outra coisa quando o enunciado fala em "maior", "menor" ou "melhor"; use as raízes quando o problema pergunta "quando a grandeza se anula"; e verifique sempre a coerência física e o domínio da resposta.',
  'Evite erros comuns, como esquecer o sinal de b ao calcular −b/(2a), usar Δ no lugar do valor do vértice ou trocar a coordenada x com a y. Se tiver dúvida, teste um ou dois valores na função para ver se o comportamento descrito faz sentido. Uma boa familiaridade com a parábola é essencial, e ela aparece em Matemática, Física e Química, o que torna o tema um investimento de alto retorno.'] }
]},

{ t:'Função exponencial e logaritmo', txt:[
 { h:'Crescimento exponencial: a ideia central', p:[
  'Na função exponencial, a variável aparece no expoente: f(x) = a · bˣ, com b positivo e diferente de 1. Ela descreve fenômenos em que a grandeza **cresce (ou decresce) proporcionalmente ao seu próprio tamanho**, isto é, a cada intervalo de tempo fixo é multiplicada pelo mesmo fator. É o modelo dos juros compostos, do crescimento de populações de bactérias, da propagação de boatos e doenças e do decaimento radioativo.',
  'O número a é o valor inicial (em x = 0) e b é o fator de crescimento por unidade de x. Se b > 1, a função é crescente, e o crescimento fica cada vez mais rápido; se 0 < b < 1, a função é decrescente, e a grandeza vai diminuindo cada vez mais devagar, aproximando-se de zero sem nunca chegar a ele. O gráfico tem uma curva característica, sempre acima do eixo x, e corta o eixo y no ponto (0, a).',
  'Um exemplo: uma cultura de bactérias começa com 500 organismos e dobra a cada hora. Após t horas, N(t) = 500 · 2ᵗ. Em 3 horas, são 500 × 8 = 4.000; em 10 horas, 500 × 1.024 = 512.000. O crescimento parece lento no início e espantoso no final. Essa característica explica por que epidemias, dívidas e investimentos com juros compostos mudam tão depressa depois de certo ponto.'] },
 { h:'Propriedades e equações exponenciais', p:[
  'As propriedades das potências são a base do tema: aᵐ · aⁿ = aᵐ⁺ⁿ, aᵐ/aⁿ = aᵐ⁻ⁿ, (aᵐ)ⁿ = aᵐⁿ e a⁻ⁿ = 1/aⁿ. Para resolver uma **equação exponencial**, o objetivo é reduzir os dois lados à mesma base, para então igualar os expoentes. Em 2ˣ = 32, escrevemos 32 = 2⁵ e concluímos que x = 5. Em 9ˣ = 27, escrevemos 3²ˣ = 3³, logo 2x = 3 e x = 3/2.',
  'Quando as bases não podem ser igualadas diretamente, é possível usar o logaritmo, que veremos a seguir. Mas, em provas de ensino médio, os números costumam ser escolhidos para que a redução à mesma base seja possível, ou o enunciado fornece valores aproximados de logaritmos. Treine a decomposição em fatores primos, que ajuda a reconhecer bases comuns, como 4, 8 e 16 (potências de 2) ou 9 e 27 (potências de 3).',
  'Outro tipo de problema é a **inequação exponencial**, como 2ˣ > 8. Como a base é maior que 1, a função é crescente, então o sentido da desigualdade é mantido ao comparar expoentes: x > 3. Se a base estivesse entre 0 e 1, o sentido seria invertido. Essa observação é um ponto de atenção frequente, pois muitos candidatos esquecem de verificar se a base é maior ou menor que 1.'] },
 { h:'Logaritmo: a operação inversa', p:[
  'O logaritmo responde à pergunta: "a que expoente devo elevar a base para obter determinado número?". Escreve-se log_b(a) = x quando bˣ = a. Assim, log₂(8) = 3, pois 2³ = 8, e log₁₀(1.000) = 3, pois 10³ = 1.000. O logaritmo é a operação **inversa** da exponencial, assim como a raiz é a inversa da potência, e serve para "descobrir expoentes" desconhecidos.',
  'As principais propriedades são: log(a · b) = log a + log b; log(a/b) = log a − log b; log(aⁿ) = n · log a; log_b(1) = 0 e log_b(b) = 1. Elas transformam multiplicações em somas e potências em produtos, o que facilita contas e explica a invenção dos logaritmos como ferramenta de cálculo. Em questões do ENEM, os valores como log 2 ≈ 0,30 e log 3 ≈ 0,48 costumam ser fornecidos para que o candidato aplique as propriedades.',
  'A base mais usada no cotidiano é 10, chamada de logaritmo decimal. Na ciência, também aparece a base natural e (aproximadamente 2,718). O logaritmo só é definido para números positivos, e a base deve ser positiva e diferente de 1. Esses cuidados definem o domínio da função logarítmica, e erros por ignorá-los são comuns em equações logarítmicas.'] },
 { h:'Aplicações no mundo real', p:[
  'Muitas escalas científicas são logarítmicas. A **escala Richter**, que mede a magnitude de terremotos, aumenta 1 unidade quando a energia liberada aumenta cerca de 32 vezes: um terremoto de magnitude 7 é muito mais intenso que um de magnitude 6. O **pH** mede a acidez com base em −log[H⁺]: cada unidade de pH corresponde a uma variação de 10 vezes na concentração de íons. O **decibel**, para o som, também é logarítmico.',
  'O uso de escalas logarítmicas permite representar valores que variam em ordens de grandeza muito diferentes em um mesmo gráfico. Também modelam a sensação humana: percebemos aumentos de intensidade luminosa e sonora de forma proporcional ao logaritmo, e não à quantidade absoluta. Isso explica por que o tema aparece em questões interdisciplinares de Química, Física e Biologia.',
  'No decaimento radioativo e em processos como a meia-vida de medicamentos, a quantidade restante é N(t) = N₀ · (1/2)^(t/T), em que T é a meia-vida. Para saber em quanto tempo a quantidade cai para determinado valor, usa-se o logaritmo, ou, quando os números são favoráveis, a redução à mesma base. Em ambos os casos, a ideia é descobrir o expoente (o tempo), o que é exatamente a missão do logaritmo.'] },
 { h:'Como estudar e resolver', p:[
  'Comece pela interpretação: a grandeza multiplica-se por um fator a cada período? Se sim, é exponencial, e o fator é a base. Identifique o valor inicial, o fator e o tempo, escreva a função e substitua. Se a pergunta é "quanto tempo leva para...?", o expoente é a incógnita, e a resolução envolve igualar bases ou usar logaritmo.',
  'Treine a conversão entre as formas exponencial e logarítmica: 5² = 25 equivale a log₅(25) = 2. Faça isso até ser automático, pois é a base de qualquer exercício. Aprenda também as propriedades dos logaritmos com exemplos numéricos simples, como log₂(32) = log₂(4 · 8) = 2 + 3 = 5, e verifique cada regra com números pequenos antes de usá-las em problemas.',
  'Cuidado com as armadilhas: log(a + b) não é log a + log b, e (a · b)ⁿ não é aⁿ + bⁿ. Em equações logarítmicas, verifique sempre se as soluções encontradas satisfazem as condições de existência (logaritmando positivo), pois soluções que anulam ou tornam negativo o logaritmando devem ser descartadas. Com atenção a esses detalhes, o tema é bastante acessível.'] }
]}
];
