/* Matemática: textos corridos, temas 10 a 12 */
module.exports = [
{ t:'Equações do 1º e do 2º grau', txt:[
 { h:'O que é uma equação e como resolvê-la', p:[
  'Uma equação é uma igualdade com pelo menos uma incógnita, isto é, um valor desconhecido representado por uma letra. Resolver a equação é descobrir qual valor, colocado no lugar da incógnita, torna a igualdade verdadeira. O princípio básico é a **balança**: o que se faz de um lado da igualdade deve ser feito do outro. Se somamos 5 de um lado, somamos 5 do outro; se dividimos por 2, dividimos os dois lados.',
  'Na **equação do 1º grau**, a incógnita aparece com expoente 1. Para resolver 3x + 7 = 22, subtrai-se 7 dos dois lados, obtendo 3x = 15, e depois divide-se por 3, chegando a x = 5. Uma forma de verificar é substituir o valor encontrado na equação original: 3 · 5 + 7 = 22. Essa verificação é rápida e elimina muitos erros. Quando há parênteses ou frações, elimina-se primeiro o que atrapalha: distribui-se o fator dos parênteses e multiplica-se tudo pelo MMC dos denominadores.',
  'O grande desafio do ENEM não está em resolver a equação, e sim em **montá-la** a partir de um texto. Traduza a linguagem comum para a matemática: "o dobro de um número" é 2x, "três a mais" é x + 3, "a metade" é x/2, "o quadrado" é x². Se um táxi cobra uma taxa fixa de R$ 5 mais R$ 2 por quilômetro e a corrida custou R$ 31, a equação é 5 + 2x = 31, e a distância é x = 13 km.'] },
 { h:'Problemas que viram equações', p:[
  'Muitos problemas de enunciado envolvem idades, dinheiro, medidas e quantidades. A estratégia é a mesma: escolher a incógnita, escrever as relações do texto e resolver. Por exemplo: "a soma de dois números consecutivos é 41". Chamando o primeiro de x, o seguinte é x + 1, e a equação é x + (x + 1) = 41, o que dá x = 20 e os números são 20 e 21. Em problemas de idade, defina a idade atual e expresse as idades passadas ou futuras como x − k ou x + k.',
  'Em situações de comparação de planos, as equações permitem descobrir o ponto de equilíbrio. Um plano A cobra R$ 40 fixos mais R$ 0,50 por minuto, e um plano B cobra R$ 20 fixos mais R$ 1,00 por minuto. Para qual tempo os custos se igualam? A equação é 40 + 0,5x = 20 + x, que resulta em x = 40 minutos. Antes disso, o plano B é mais barato; depois, o plano A compensa. Esse tipo de raciocínio está por trás de muitas decisões de consumo.',
  'Quando as equações envolvem frações, é útil usar o MMC. Para resolver x/2 + x/3 = 10, multiplica-se tudo por 6: 3x + 2x = 60, logo x = 12. Também é comum a presença de percentuais: "aumentou 20% e chegou a 360". A equação é 1,2x = 360, e x = 300. Escrever a relação em forma de equação evita atalhos mentais que podem levar ao erro.'] },
 { h:'Equação do 2º grau e a fórmula de Bhaskara', p:[
  'A equação do 2º grau tem a forma ax² + bx + c = 0, com a diferente de zero. Suas soluções, chamadas de **raízes**, são os valores de x que anulam a expressão. A fórmula resolutiva é x = (−b ± √Δ) / 2a, em que **Δ = b² − 4ac** é o discriminante. Ele dá informação sobre as raízes: se Δ > 0, há duas raízes reais distintas; se Δ = 0, há uma raiz real dupla; se Δ < 0, não há raízes reais.',
  'Exemplo: x² − 5x + 6 = 0. Temos a = 1, b = −5, c = 6, e Δ = 25 − 24 = 1. As raízes são x = (5 ± 1)/2, ou seja, x = 3 e x = 2. Os casos incompletos têm atalhos. Se b = 0 (ax² + c = 0), isola-se x²; se c = 0 (ax² + bx = 0), coloca-se x em evidência e obtêm-se x = 0 e x = −b/a. Resolver por esses atalhos é mais rápido do que aplicar a fórmula completa.',
  'Também é possível resolver por **soma e produto**: se as raízes são x₁ e x₂, então x₁ + x₂ = −b/a e x₁ · x₂ = c/a. No exemplo anterior, a soma é 5 e o produto é 6, então as raízes são 2 e 3, o que dá para ver de cabeça. Em provas, esse método economiza tempo quando os coeficientes são pequenos e as raízes são inteiras.'] },
 { h:'Aplicações do 2º grau', p:[
  'As equações do 2º grau aparecem em problemas de área, movimento e otimização. Um retângulo cuja medida do comprimento excede a da largura em 3 m e cuja área é 40 m² leva a x(x + 3) = 40, isto é, x² + 3x − 40 = 0, cuja raiz positiva é x = 5. Atenção: em contextos reais, descartam-se as raízes negativas para medidas, e é preciso interpretar o resultado conforme o enunciado.',
  'No lançamento de um objeto, a altura em função do tempo costuma ser uma função quadrática, e a equação do 2º grau dá o instante em que o objeto atinge o solo ou determinada altura. Em problemas financeiros, a receita em função do preço também pode ser quadrática, e a equação permite achar pontos de equilíbrio. Esses usos serão retomados no estudo da função quadrática.',
  'Um cuidado importante: nem toda solução matemática serve ao problema. Se a equação gera duas raízes, verifique qual atende às condições do texto (valores positivos, inteiros, dentro de um intervalo). Responder com a raiz errada é um deslize muito comum. Ao final, volte ao enunciado e confirme se a resposta tem sentido.'] },
 { h:'Erros comuns e estratégias', p:[
  'Os erros mais frequentes nas equações do 1º grau são trocar sinais ao passar termos para o outro lado, esquecer de distribuir o sinal negativo diante dos parênteses e dividir apenas alguns termos por um número. Nas do 2º grau, são comuns os erros no cálculo do discriminante (principalmente com b negativo, em que (−b)² é positivo) e esquecer do sinal ± na fórmula.',
  'Como estratégia, escreva cada passo em uma linha, mantendo o sinal de igual alinhado. Use a verificação por substituição sempre que possível, sobretudo se o resultado parecer estranho. Em questões de múltipla escolha, substitua as alternativas na equação para ver qual a satisfaz, quando isso for mais rápido do que resolver.',
  'Por fim, treine a tradução de enunciados. Pegue frases do dia a dia e escreva em linguagem algébrica: "a conta do restaurante, com 10% de gorjeta, foi R$ 55", "o triplo de uma quantidade menos 4 dá 20". Com o tempo, essa tradução fica automática, e as equações deixam de ser um obstáculo para virar uma ferramenta simples de raciocínio.'] }
]},

{ t:'Sistemas de equações', txt:[
 { h:'Quando um problema pede duas equações', p:[
  'Um sistema de equações é um conjunto de duas ou mais equações que devem ser satisfeitas ao mesmo tempo. Eles surgem quando há mais de uma incógnita e mais de uma informação relacionando-as. Por exemplo: "em uma lanchonete, 2 sanduíches e 1 suco custam R$ 22; 1 sanduíche e 2 sucos custam R$ 17". Chamando o preço do sanduíche de x e o do suco de y, o sistema é 2x + y = 22 e x + 2y = 17.',
  'A solução de um sistema é o par (ou conjunto) de valores que torna todas as equações verdadeiras. Em sistemas de duas equações com duas incógnitas, geometricamente cada equação do 1º grau representa uma reta, e a solução é o ponto onde elas se cruzam. Se as retas são paralelas, não há solução (sistema impossível); se coincidem, há infinitas soluções (sistema possível e indeterminado).',
  'A etapa mais importante é a modelagem: definir bem as incógnitas, anotar o que cada letra representa e traduzir cada frase do enunciado em uma equação. Evite usar a mesma letra para duas coisas diferentes. Escrever "x = preço do sanduíche" e "y = preço do suco" no começo da resolução evita confusões, principalmente em problemas longos.'] },
 { h:'Método da substituição', p:[
  'No método da **substituição**, isola-se uma incógnita em uma das equações e substitui-se a expressão obtida na outra. No sistema x + y = 10 e 2x − y = 5, isolamos y na primeira (y = 10 − x) e substituímos na segunda: 2x − (10 − x) = 5, o que dá 3x = 15 e x = 5. Depois voltamos a y = 10 − 5 = 5. A solução é (5, 5).',
  'Esse método é especialmente cômodo quando uma das equações já traz uma incógnita isolada ou com coeficiente 1. Ele também funciona bem em sistemas em que uma equação é do 2º grau e a outra é do 1º grau, pois a substituição transforma o problema em uma equação do 2º grau com uma incógnita. Cuidado com sinais ao substituir expressões com subtração, pois é preciso colocá-las entre parênteses.',
  'Depois de achar todos os valores, confira nas duas equações originais. Uma solução que satisfaz apenas uma das equações não é solução do sistema. Essa verificação final é rápida e dá segurança, principalmente em provas com tempo limitado. Também vale conferir se as soluções fazem sentido no contexto (por exemplo, preços ou quantidades negativos indicam erro).'] },
 { h:'Método da adição (eliminação)', p:[
  'No método da **adição**, somam-se ou subtraem-se as equações para eliminar uma das incógnitas. Em x + y = 10 e x − y = 2, somando termo a termo obtém-se 2x = 12, então x = 6 e y = 4. Quando os coeficientes não são opostos, multiplicam-se as equações por números convenientes para tornar uma incógnita simétrica. Em 2x + 3y = 12 e 3x + 2y = 13, multiplicamos a primeira por 3 e a segunda por −2, e somando eliminamos x.',
  'Esse método costuma ser mais rápido que a substituição quando as duas equações têm a mesma estrutura. Em sistemas com três incógnitas, a lógica se repete: elimina-se uma incógnita entre pares de equações, reduzindo o problema a um sistema 2 por 2. A organização é fundamental para não perder termos: escreva as equações alinhadas, com as incógnitas em colunas.',
  'Escolher o método certo economiza tempo. Se há uma incógnita com coeficiente 1 ou −1, a substituição é direta. Se os coeficientes são simétricos ou fáceis de igualar, a adição é a melhor. Também é possível usar a comparação, isolando a mesma incógnita nas duas equações e igualando as expressões. Com treino, a escolha é quase intuitiva.'] },
 { h:'Problemas clássicos e interpretação', p:[
  'Alguns tipos de problema aparecem repetidamente. Os de **compras** envolvem preços e quantidades de produtos, os de **idades** relacionam a idade de duas pessoas em momentos diferentes, os de **mistura** relacionam quantidades e concentrações, os de **cédulas e moedas** pedem o número de cada tipo dado o valor total e a quantidade de itens. Em todos eles, identificar o que é desconhecido e quantas relações existem é o primeiro passo.',
  'Por exemplo, em um estacionamento há carros (4 rodas) e motos (2 rodas). Há 30 veículos e 90 rodas. Chamando de c os carros e m as motos, temos c + m = 30 e 4c + 2m = 90. Substituindo m = 30 − c, obtemos 4c + 60 − 2c = 90, 2c = 30, c = 15, m = 15. Há 15 carros e 15 motos. Verifique: 15 × 4 + 15 × 2 = 90.',
  'O ENEM também apresenta sistemas em contexto de escolha entre planos, comparação de custos e interpretação de gráficos de retas. Nesses casos, a solução é o ponto de interseção das retas e tem significado prático: o momento em que dois custos se igualam ou o ponto de equilíbrio entre receita e despesa. Interpretar a resposta, e não apenas calcular, é o que a prova avalia.'] },
 { h:'Sistemas impossíveis, indeterminados e dicas', p:[
  'Nem todo sistema tem solução única. O sistema x + y = 5 e x + y = 8 é **impossível**, pois a soma não pode ser 5 e 8 ao mesmo tempo. Já o sistema x + y = 5 e 2x + 2y = 10 é **indeterminado**: a segunda equação é o dobro da primeira, então qualquer par que some 5 serve. Ao aplicar os métodos, esses casos aparecem como contradições (0 = 3) ou identidades (0 = 0).',
  'Uma dica útil é perceber a relação entre os coeficientes. Se as razões a₁/a₂, b₁/b₂ e c₁/c₂ são todas iguais, o sistema é indeterminado; se as duas primeiras são iguais e a terceira é diferente, é impossível; se as duas primeiras são diferentes, há solução única. Esse teste rápido evita cálculos longos em questões de classificação.',
  'Na prova, escreva claramente as incógnitas, monte o sistema e escolha o método. Use a verificação na leitura final do enunciado: a resposta é um valor monetário, um número de pessoas, uma idade? Isso orienta se a solução faz sentido. Com prática, sistemas de equações se tornam um dos tópicos mais seguros da prova, porque seguem passos bem definidos.'] }
]},

{ t:'Funções: como ler e interpretar', txt:[
 { h:'A ideia de função', p:[
  'Uma função é uma relação em que cada valor de uma grandeza (a variável independente, geralmente x) corresponde a exatamente um valor de outra grandeza (a variável dependente, geralmente y). Em linguagem do cotidiano, a função expressa dependência: o valor da conta de energia depende do consumo, a distância percorrida depende do tempo, o preço pago em uma corrida depende dos quilômetros rodados. Escreve-se y = f(x), lido como "y é função de x".',
  'Os conjuntos envolvidos recebem nomes. O **domínio** é o conjunto de valores permitidos para x, o **contradomínio** é o conjunto onde y pode estar e a **imagem** é o conjunto dos valores que de fato aparecem. Em contextos reais, o domínio é limitado pela situação: não faz sentido um tempo negativo ou um número de produtos fracionário. Identificar o domínio correto é parte da interpretação do problema.',
  'Para saber se uma relação é função, basta verificar se cada x tem um único y. Graficamente, isso se verifica com o **teste da reta vertical**: se uma reta vertical corta o gráfico em mais de um ponto, a relação não é função. Uma circunferência, por exemplo, não é gráfico de função, mas uma parábola com eixo vertical é.'] },
 { h:'Leitura de gráficos', p:[
  'O ENEM raramente pede a "fórmula" de uma função, mas pede com frequência a **leitura de gráficos**. Para interpretar, comece pelos eixos: o que representa cada um e quais são as unidades? Depois, observe o comportamento: o gráfico sobe (função crescente) ou desce (decrescente)? Há valores máximos ou mínimos? Em que ponto cruza os eixos? Cada uma dessas características tem significado no contexto do problema.',
  'O ponto em que o gráfico cruza o eixo y (quando x = 0) indica o valor inicial, como uma taxa fixa ou o estoque no começo. Os pontos em que cruza o eixo x (y = 0) são as **raízes** ou zeros da função, e indicam quando a grandeza se anula. Os trechos em que o gráfico está acima do eixo x correspondem a valores positivos, e os abaixo, a valores negativos, o que ajuda a interpretar lucros e prejuízos, temperaturas e saldos.',
  'Também é importante ler a **inclinação**. Um gráfico mais inclinado indica variação mais rápida. Um trecho horizontal indica que a grandeza não mudou naquele intervalo. Em gráficos de velocidade ou crescimento, a inclinação mostra a rapidez da mudança. Interpretar essas diferenças, sem precisar de contas, é uma habilidade central em questões de leitura de gráficos.'] },
 { h:'Crescimento, decrescimento e extremos', p:[
  'Uma função é **crescente** em um intervalo se, ao aumentar x, o valor de y também aumenta; é **decrescente** se, ao aumentar x, y diminui; e é **constante** se y não muda. Um gráfico pode ter trechos de naturezas diferentes. Em uma série temporal da produção de uma fábrica, por exemplo, pode haver meses de crescimento, de estabilidade e de queda, e a pergunta da questão costuma indicar qual trecho observar.',
  'Os **máximos e mínimos** são os pontos mais altos e mais baixos do gráfico, em um intervalo ou globalmente. Em problemas, representam o maior lucro, a menor temperatura, o momento de maior vazão. Para identificá-los, procure as "cristas" e os "vales" da curva. Em funções quadráticas, o vértice da parábola é o ponto de máximo ou mínimo.',
  'A leitura também envolve **comparar funções**: qual de dois planos de celular é mais barato a partir de certo consumo? Qual de dois investimentos rende mais depois de dez anos? Para responder, observe onde os gráficos se cruzam e qual está acima ou abaixo em cada intervalo. O ponto de cruzamento é o instante em que os valores se igualam, e antes e depois dele a conveniência se inverte.'] },
 { h:'Função como modelo do mundo real', p:[
  'Modelar é escolher uma função que descreva uma situação. Se uma grandeza cresce em quantidade constante, o modelo é afim. Se cresce proporcionalmente ao que já existe, é exponencial. Se há um valor ótimo, com crescimento seguido de queda, pode ser quadrática. Reconhecer qual modelo se encaixa em um texto ou tabela é uma habilidade importante, e muitas questões pedem apenas isso, sem exigir cálculo.',
  'Em uma tabela, compare a variação de y a cada passo de x. Se a diferença é constante, trata-se de uma função afim. Se a razão entre valores consecutivos é constante, é exponencial. Se a diferença das diferenças é constante, é quadrática. Esse teste prático é uma forma de decidir sem ver o gráfico, e funciona bem em questões com dados de pesquisas, de produção e de saldos.',
  'Também vale lembrar que modelos têm limites. Uma função que descreve bem o crescimento de uma população em um período curto pode não valer para períodos longos. O texto do enunciado costuma informar o intervalo em que o modelo é válido, e é preciso respeitá-lo. Avaliar a razoabilidade do resultado é parte essencial do raciocínio matemático.'] },
 { h:'Estratégias para a prova', p:[
  'Ao ver um gráfico, faça uma leitura em etapas: título e eixos, unidades, comportamento geral, pontos especiais e só então leia a pergunta. Muitas questões trazem gráficos com escalas inusitadas ou com eixos que não começam em zero, o que pode distorcer a percepção. Verifique a escala antes de tirar conclusões visuais.',
  'Se a função é dada por uma fórmula, calcule alguns valores para visualizar o comportamento. Para y = 2x + 3, em x = 0 temos y = 3, em x = 1 temos y = 5. Para descobrir quando y atinge um valor específico, resolva a equação correspondente. Substituir é o caminho mais seguro para evitar enganos de interpretação.',
  'Por fim, relacione sempre o gráfico à situação real. Pergunte-se: o que significa o ponto onde a curva cruza o eixo? O que significa o trecho descendente? Essa tradução entre matemática e contexto é o coração da competência de modelagem, e é o que diferencia quem só calcula de quem entende o que está calculando.'] }
]}
];
