/* Matemática: textos corridos, temas 7 a 9 */
module.exports = [
{ t:'Unidades de medida e conversões', txt:[
 { h:'Por que padronizar as medidas', p:[
  'Medir é comparar uma grandeza com um padrão. Para que pessoas de lugares diferentes se entendam, foi criado o **Sistema Internacional de Unidades (SI)**, adotado pela maior parte dos países. No SI, a unidade de comprimento é o metro, a de massa é o quilograma, a de tempo é o segundo e a de temperatura é o kelvin (embora no dia a dia usemos o grau Celsius). Compreender as unidades e saber converter entre elas é uma habilidade básica que aparece em questões de todas as áreas.',
  'A conversão de unidades é muito mais simples quando se conhece a lógica dos **prefixos**. Quilo (k) significa mil, hecto (h) cem, deca (da) dez, deci (d) um décimo, centi (c) um centésimo e mili (m) um milésimo. Assim, 1 km = 1.000 m, 1 cm = 0,01 m e 1 mm = 0,001 m. Para passar de uma unidade maior para uma menor, multiplica-se; no sentido inverso, divide-se. Uma dica prática é imaginar a "escada" das unidades: cada degrau vale 10 vezes o anterior.',
  'Um erro frequente é converter na direção errada. Antes de calcular, faça uma estimativa: 5 km são muitos ou poucos metros? Claramente, são muitos, então o número deve crescer ao passar para metros (5.000). Esse teste simples impede muitos equívocos, e pode ser aplicado a qualquer conversão.'] },
 { h:'Comprimento, massa e capacidade', p:[
  'Na **medida de comprimento**, as conversões seguem a escada de base 10: 1 m = 100 cm = 1.000 mm, e 1 km = 1.000 m. Distâncias em estradas usam quilômetros, medidas de móveis usam metros e centímetros, e peças de precisão usam milímetros. Também é comum encontrar unidades do sistema inglês em textos do ENEM, como polegada (aproximadamente 2,54 cm), pé (cerca de 30,5 cm) e milha (cerca de 1,6 km); o enunciado costuma fornecer a equivalência.',
  'Na **massa**, 1 kg = 1.000 g, 1 g = 1.000 mg e 1 tonelada = 1.000 kg. Em rótulos de alimentos e medicamentos, as quantidades aparecem em gramas e miligramas, e é fundamental cuidar da conversão para evitar doses erradas. Na **capacidade (volume de líquidos)**, 1 L = 1.000 mL, e 1 L equivale a 1 dm³, assim como 1 mL equivale a 1 cm³. Essa última equivalência liga capacidade a volume e é muito explorada em problemas.',
  'Uma relação especialmente útil: 1 m³ equivale a 1.000 litros. Uma caixa d\'água de 2 m³ comporta 2.000 litros. Já 1 litro de água tem massa de aproximadamente 1 kg, o que permite passar de volume para massa em problemas com água. Guardar esses fatos reduz o número de passos de cálculo e a chance de erro.'] },
 { h:'Áreas, volumes e tempo', p:[
  'Ao converter **áreas**, o fator de conversão é elevado ao quadrado, pois a área envolve duas dimensões. Como 1 m = 100 cm, temos 1 m² = 100 × 100 = 10.000 cm². Da mesma forma, 1 km² = 1.000.000 m². Já nos **volumes**, o fator é elevado ao cubo: 1 m³ = 1.000.000 cm³. Esquecer-se de elevar o fator ao quadrado ou ao cubo é um dos erros mais comuns do tema.',
  'Em terrenos rurais, é usual a unidade **hectare** (ha), que equivale a 10.000 m², ou seja, um quadrado de 100 m por 100 m. Em áreas maiores aparece o quilômetro quadrado. Em imóveis, usa-se o metro quadrado. Compreender essas unidades facilita comparações, como estimar quantas vezes um terreno de 5 hectares é maior que um de 2.500 m² (são 20 vezes).',
  'Para o **tempo**, a conversão não é decimal: 1 h = 60 min = 3.600 s, e 1 dia = 24 h. Por isso, 1,5 h equivale a 1 h 30 min, e não 1 h 50 min. Esse deslize é muito comum quando se trabalha com decimais de hora. Para converter minutos em horas decimais, divida por 60: 45 min são 0,75 h. Em problemas de velocidade média, essa conversão correta é decisiva.'] },
 { h:'Velocidade, densidade e grandezas compostas', p:[
  'Algumas unidades são formadas pela combinação de outras. A **velocidade** é uma razão entre distância e tempo (km/h, m/s). Para converter km/h em m/s, divide-se por 3,6, e para o caminho inverso multiplica-se por 3,6. Assim, 72 km/h equivalem a 20 m/s. Esse fator vem de 1 km = 1.000 m e 1 h = 3.600 s, e vale a pena guardá-lo, pois aparece em questões de Física e de Matemática.',
  'A **densidade** relaciona massa e volume (g/cm³ ou kg/m³), e a vazão de uma torneira relaciona volume e tempo (L/min, m³/h). Para a energia elétrica, o consumo é medido em quilowatt-hora (kWh), que é potência multiplicada por tempo: um aparelho de 1.000 W ligado por 2 horas consome 2 kWh. Entender o que cada unidade composta representa evita ficar preso a decorar fórmulas.',
  'Uma técnica excelente para essas conversões é a **análise dimensional**: escreva as unidades junto aos números e deixe que elas se cancelem como se fossem frações. Para converter 90 km/h em m/s, escreva 90 km/h × (1.000 m/1 km) × (1 h/3.600 s) e veja que km e h se cancelam, restando m/s. Se a unidade final saiu correta, a conta provavelmente também está.'] },
 { h:'Notação científica, estimativas e ordens de grandeza', p:[
  'Quando os números são muito grandes ou muito pequenos, usa-se a **notação científica**, que escreve o número como um valor entre 1 e 10 multiplicado por uma potência de 10. A distância da Terra ao Sol, cerca de 150 milhões de km, é 1,5 × 10⁸ km. O diâmetro de um vírus, da ordem de 0,0000001 m, é 1 × 10⁻⁷ m. Essa forma facilita comparações e cálculos, pois bastam as regras de potências.',
  'A **ordem de grandeza** é a potência de 10 mais próxima do número. Serve para comparar valores de escalas muito diferentes e para fazer estimativas rápidas. Questões do ENEM costumam perguntar quantas vezes um valor é maior que outro, e a resposta vem da divisão das potências de 10. Em estimativas, arredonde os números para facilitar a conta e verifique se a resposta é plausível.',
  'Ao lidar com unidades em provas, adote uma rotina: leia as unidades do enunciado, identifique a unidade pedida na resposta, converta tudo para uma mesma unidade antes de calcular e confira o resultado ao final. Embora pareça trabalhoso, essa rotina é rápida com prática e evita erros que custam questões. Muitos problemas de Matemática, Física e Química se resolvem apenas organizando bem as unidades.'] }
]},

{ t:'Escalas', txt:[
 { h:'O que é escala', p:[
  'Escala é a razão entre uma medida no desenho (mapa, planta, maquete) e a medida correspondente na realidade. Quando se escreve 1:500, lê-se "um para quinhentos", e isso significa que 1 unidade no desenho representa 500 dessas mesmas unidades no real. Assim, 1 cm no papel equivale a 500 cm, ou 5 m, no terreno. A escala permite reduzir objetos grandes (cidades, prédios) ou ampliar objetos pequenos (células, peças de relógio) para representá-los em papel.',
  'A escala é um número puro, porque compara grandezas de mesma unidade. Por isso, 1:500 vale em centímetros, metros, polegadas ou qualquer unidade, desde que a mesma seja usada nos dois lados. O erro mais comum é esquecer de converter as unidades depois do cálculo: se o desenho mede 4 cm e a escala é 1:25.000, a distância real é 4 × 25.000 = 100.000 cm, ou seja, 1 km.',
  'Existem dois formatos principais: a **escala numérica** (1:100.000) e a **escala gráfica**, uma barrinha dividida em trechos que indica quantos quilômetros ou metros cada segmento representa. A escala gráfica tem a vantagem de continuar válida se o mapa for ampliado ou reduzido, pois a barra muda de tamanho junto com o desenho. Já a numérica perde o sentido se a imagem for redimensionada.'] },
 { h:'Como calcular distâncias e dimensões', p:[
  'A fórmula básica é E = d/D, em que E é a escala, d a medida no desenho e D a medida real. A partir dela, calculamos qualquer dos três valores. Para encontrar D, multiplique d pelo denominador da escala. Para encontrar d, divida D pelo denominador. Para descobrir a escala, divida d por D, convertendo antes para a mesma unidade.',
  'Um exemplo: em um mapa, duas cidades estão a 6 cm uma da outra. A distância real é de 120 km. Qual é a escala? Convertendo 120 km para centímetros, temos 12.000.000 cm. A escala é 6/12.000.000 = 1/2.000.000, ou seja, 1:2.000.000. Observe que o resultado é expresso sempre na forma 1:n, simplificando a fração até que o numerador seja 1.',
  'Outro tipo de problema pede para calcular o tamanho de uma planta: uma sala de 5 m por 4 m, desenhada na escala 1:50, terá no papel 5/50 = 0,1 m = 10 cm por 4/50 = 0,08 m = 8 cm. Para áreas, lembre que a relação é quadrática: na escala 1:50, a área real é 50² = 2.500 vezes maior que a área desenhada. Esse detalhe costuma ser esquecido, e é uma armadilha clássica.'] },
 { h:'Escalas grandes e pequenas', p:[
  'Uma confusão frequente é chamar de "escala grande" a que tem número grande no denominador. É o contrário. Uma escala **grande** (como 1:100) representa uma área pequena com muitos detalhes, porque a redução é pequena. Uma escala **pequena** (como 1:10.000.000) representa uma grande área com poucos detalhes, porque a redução é enorme. Pense na fração: 1/100 é maior que 1/10.000.000.',
  'Plantas de casas usam escalas como 1:50 ou 1:100, nas quais se veem portas, janelas e móveis. Mapas de cidades usam 1:10.000 ou 1:25.000, em que aparecem ruas e quadras. Mapas de países ou continentes usam escalas como 1:5.000.000 ou menores, mostrando apenas contornos, rios e grandes cidades. Saber escolher a escala adequada ao objetivo é parte da leitura cartográfica.',
  'Quando um mapa é ampliado ou reduzido em fotocópia, a escala numérica muda. Se um mapa na escala 1:100.000 é ampliado em 200%, as medidas no papel dobram, e a escala passa a ser 1:50.000. Ao contrário, reduzir à metade leva a 1:200.000. Questões do ENEM exploram esse raciocínio, perguntando qual será a nova escala ou a nova medida após a ampliação.'] },
 { h:'Escalas em maquetes, plantas e ampliações', p:[
  'Em maquetes, a lógica é a mesma. Se um edifício de 60 m de altura é representado por uma maquete de 30 cm, a escala é 30/6.000 = 1/200. Em ampliações, como em imagens microscópicas, a escala é maior que 1: uma imagem na escala 100:1 significa que um objeto de 1 mm aparece com 100 mm. Em ambos os casos, o procedimento é igual, apenas com o desenho maior ou menor que o objeto real.',
  'Também aparecem situações em que a escala está implícita. Uma foto de satélite com legenda "1 cm representa 200 m" é, na verdade, uma escala de 1:20.000. Uma planta com um segmento rotulado "10 m" permite descobrir a escala medindo o segmento com a régua. Saber extrair a escala dos dados fornecidos é uma habilidade que o ENEM valoriza.',
  'Em construção civil, a leitura de plantas depende de escalas. O arquiteto desenha em escala; o engenheiro e o pedreiro leem as medidas e as transformam em dimensões reais. Esse uso profissional mostra que a escala é muito mais do que um tópico de prova: é uma ferramenta de comunicação técnica, e entender sua lógica ajuda a interpretar projetos, mapas e modelos no cotidiano.'] },
 { h:'Dicas e armadilhas', p:[
  'Passo a passo para resolver: identifique o que é dado (escala, medida no desenho ou medida real), converta as unidades para que sejam iguais, aplique a razão e converta o resultado para a unidade pedida. Anote os valores com as unidades para não se perder. Se o enunciado trouxer figuras, use a régua mentalmente, pois muitas vezes o texto fornece as medidas do desenho.',
  'As armadilhas mais comuns são: esquecer de converter cm para km (divida por 100.000), confundir escala grande com pequena, tratar áreas como se fossem proporcionais à escala linear e usar a fórmula invertida (dividir quando se deve multiplicar). Uma verificação rápida é a de plausibilidade: um mapa que mostra um país inteiro não pode ter uma distância real de poucos metros entre duas cidades.',
  'Treine com situações do cotidiano: calcule a distância real entre dois pontos de um mapa do seu bairro, compare com o caminho percorrido de carro e veja o quanto a estimativa se aproxima. Esse tipo de prática conecta a Matemática à geografia e à vida real, e fixa a ideia de que a escala é uma razão simples, mas muito poderosa.'] }
]},

{ t:'Potências, raízes e notação científica', txt:[
 { h:'Potenciação: ideia e propriedades', p:[
  'A potenciação é uma multiplicação de fatores iguais. Em aⁿ, a é a **base** e n é o **expoente**: a⁴ = a · a · a · a. Todo número elevado a 1 é ele mesmo, e todo número (diferente de zero) elevado a 0 vale 1. Expoentes negativos indicam o inverso: a⁻ⁿ = 1/aⁿ. Assim, 2⁻³ = 1/8 = 0,125. Também vale lembrar que base negativa com expoente par dá resultado positivo, e com expoente ímpar dá resultado negativo.',
  'As **propriedades** facilitam muito as contas. Multiplicação de potências de mesma base: somam-se os expoentes (aᵐ · aⁿ = aᵐ⁺ⁿ). Divisão: subtraem-se (aᵐ / aⁿ = aᵐ⁻ⁿ). Potência de potência: multiplicam-se (aᵐ)ⁿ = aᵐ·ⁿ. Potência de um produto: distribui-se pelos fatores ((ab)ⁿ = aⁿ · bⁿ). Essas regras permitem simplificar expressões grandes sem precisar calcular cada potência.',
  'Um erro típico é achar que (a + b)² = a² + b². Isso não é verdade: (a + b)² = a² + 2ab + b². Outro erro é confundir −3² com (−3)². O primeiro é −9 (o sinal fica fora da potência), e o segundo é +9. Atenção aos parênteses faz toda a diferença nas questões de simplificação.'] },
 { h:'Raízes e radicais', p:[
  'A raiz é a operação inversa da potência. A raiz quadrada de 25 é 5, porque 5² = 25. A raiz cúbica de 27 é 3, porque 3³ = 27. De modo geral, ⁿ√a = b significa bⁿ = a. As raízes podem ser escritas como potências de expoente fracionário: √a = a^(1/2), e ∛a = a^(1/3). Essa equivalência é útil para aplicar as propriedades de potência também às raízes.',
  'Algumas propriedades dos radicais: √(a · b) = √a · √b, e √(a/b) = √a/√b (com b diferente de zero). Para simplificar, fatore o número dentro da raiz: √72 = √(36 · 2) = 6√2. Isso permite somar radicais semelhantes: 3√2 + 5√2 = 8√2. Mas atenção, √(a + b) não é igual a √a + √b: por exemplo, √(9 + 16) = 5, e não 3 + 4 = 7.',
  'Quando um radical aparece no denominador, costuma-se **racionalizar**, multiplicando numerador e denominador por um fator que elimine a raiz do denominador. Por exemplo, 1/√2 = √2/2. No ENEM, isso aparece mais como habilidade de simplificação e de estimativa: saber que √2 ≈ 1,41 e √3 ≈ 1,73 já ajuda a calcular valores aproximados em problemas de geometria e trigonometria.'] },
 { h:'Notação científica na prática', p:[
  'A notação científica escreve qualquer número como a · 10ⁿ, com a entre 1 e 10 (sem incluir o 10) e n inteiro. O número 45.000 é 4,5 × 10⁴; o número 0,00032 é 3,2 × 10⁻⁴. Para converter, conte quantas casas a vírgula precisa andar: para a esquerda, o expoente é positivo; para a direita, é negativo. Essa forma é padrão em ciências para trabalhar com escalas extremas.',
  'Operar com notação científica é simples. Na multiplicação, multiplicam-se os coeficientes e somam-se os expoentes: (2 × 10³) · (3 × 10⁴) = 6 × 10⁷. Na divisão, dividem-se os coeficientes e subtraem-se os expoentes. Na soma e subtração, é preciso igualar os expoentes antes de operar. Se o coeficiente final sair fora do intervalo de 1 a 10, ajuste-o e corrija o expoente.',
  'O ENEM utiliza esse recurso em temas como astronomia, microbiologia, química e finanças públicas. Um exemplo: o diâmetro de uma bactéria é cerca de 2 × 10⁻⁶ m e o de uma célula humana é cerca de 2 × 10⁻⁵ m. Para saber quantas vezes uma é maior que a outra, divide-se: 2 × 10⁻⁵ / 2 × 10⁻⁶ = 10. Comparar potências de 10 permite perceber diferenças de escala sem fazer contas complicadas.'] },
 { h:'Ordens de grandeza e comparações', p:[
  'A **ordem de grandeza** de um número é a potência de 10 mais próxima dele. Para escrever em notação científica a · 10ⁿ, usa-se 10ⁿ se a for menor que cerca de 3,16 (raiz de 10) e 10ⁿ⁺¹ se for maior. Por exemplo, 4,2 × 10⁶ tem ordem de grandeza 10⁷, e 2,5 × 10⁶ tem ordem 10⁶. Essa regra é um critério prático adotado em muitos materiais didáticos.',
  'Comparar ordens de grandeza permite saber o quanto um valor é maior ou menor que outro. Se a população de uma cidade é da ordem de 10⁶ e a de outra é de 10⁴, a primeira é cerca de 100 vezes maior. Em problemas de estimativa, como "quantos grãos de arroz há em uma tonelada?", basta aproximar com números redondos e multiplicar potências de 10.',
  'Aprender a estimar é uma habilidade valiosa. Em vez de buscar a resposta exata, procure o valor aproximado e verifique se ele é plausível. Isso é especialmente útil em questões de múltipla escolha, em que as alternativas costumam ter ordens de grandeza diferentes. Uma estimativa bem feita pode eliminar três ou quatro alternativas de uma vez.'] },
 { h:'Aplicações e cuidados', p:[
  'Potências aparecem em juros compostos, crescimento populacional, decaimento radioativo, intensidade de terremotos e acidez de soluções, entre outros. Em muitos desses casos, o modelo é exponencial: uma grandeza multiplica-se pelo mesmo fator a cada intervalo de tempo. Compreender potências é o primeiro passo para entender funções exponenciais e logaritmos, que vêm a seguir no conteúdo.',
  'Cuidados importantes: converter corretamente unidades antes de usar potências de 10 (um erro de conversão se multiplica pelo expoente); distinguir 10⁻² (0,01) de −10² (−100); lembrar que 10⁰ = 1; e escrever números muito grandes com atenção ao número de zeros. Ao usar a calculadora do celular ou do computador na vida real, confira se o formato "e+6" ou "E−3" corresponde ao expoente de 10.',
  'Para fixar, escolha algumas quantidades do mundo real e escreva-as em notação científica: a população do Brasil (cerca de 2 × 10⁸ habitantes), a distância da Terra à Lua (cerca de 3,8 × 10⁵ km), a massa de um próton (cerca de 1,7 × 10⁻²⁷ kg). Esse exercício ajuda a sentir a magnitude dos números e a manipulá-los com mais segurança.'] }
]}
];
