/* Matemática: textos corridos, temas 19 a 21 */
module.exports = [
{ t:'Teorema de Pitágoras e semelhança', txt:[
 { h:'O Teorema de Pitágoras', p:[
  'O teorema de Pitágoras vale para todo triângulo **retângulo**, aquele que tem um ângulo de 90°. Nele, os lados que formam o ângulo reto são os **catetos**, e o lado oposto ao ângulo reto, o maior de todos, é a **hipotenusa**. O teorema afirma que o quadrado da hipotenusa é igual à soma dos quadrados dos catetos: a² = b² + c². Se os catetos medem 3 e 4, a hipotenusa mede √(9 + 16) = 5.',
  'As ternas de números inteiros que satisfazem a relação são chamadas de **ternas pitagóricas**. As mais conhecidas são (3, 4, 5), (5, 12, 13), (8, 15, 17) e seus múltiplos, como (6, 8, 10). Reconhecê-las economiza tempo, pois evita calcular raízes. O pedreiro que confere o esquadro de uma parede usando medidas de 3, 4 e 5 (ou 30, 40 e 50 cm) está aplicando o teorema na prática.',
  'A recíproca também vale: se três lados de um triângulo satisfazem a² = b² + c², o triângulo é retângulo. Se a² for maior que b² + c², o triângulo é obtusângulo, e se for menor, é acutângulo. Essa comparação permite classificar triângulos a partir das medidas dos lados, algo que aparece em questões de verificação de projetos e construção.'] },
 { h:'Aplicações do teorema', p:[
  'Muitos problemas do dia a dia são, na essência, triângulos retângulos escondidos. A escada apoiada em uma parede forma um triângulo cujos catetos são a altura alcançada e a distância da base à parede, e cuja hipotenusa é a escada. A diagonal de uma tela, de um campo ou de uma porta é a hipotenusa de um triângulo cujos catetos são a largura e a altura. O caminho mais curto entre dois pontos de uma malha quadriculada em linha reta também é calculado com Pitágoras.',
  'Exemplo: uma escada de 5 m está apoiada em uma parede, com a base a 3 m dela. A altura atingida é √(25 − 9) = 4 m. Outro exemplo: a diagonal de um quadrado de lado l é l√2, e a diagonal de um retângulo de 6 por 8 é 10. A altura de um triângulo equilátero de lado l é l√3/2, obtida aplicando Pitágoras à metade do triângulo. Esses resultados aparecem em tantas questões que vale decorá-los.',
  'Em geometria espacial, Pitágoras também ajuda: a diagonal de um paralelepípedo de arestas a, b e c é √(a² + b² + c²). Para uma caixa de 3 × 4 × 12, a diagonal é √(9 + 16 + 144) = 13. Esse resultado responde, por exemplo, se um objeto longo cabe dentro de uma caixa. A ideia é aplicar o teorema duas vezes: primeiro na base e depois no triângulo formado pela diagonal da base e a altura.'] },
 { h:'Semelhança de triângulos', p:[
  'Duas figuras são **semelhantes** quando têm a mesma forma, mas não necessariamente o mesmo tamanho. Para triângulos, isso significa que os ângulos correspondentes são iguais e os lados correspondentes são proporcionais. A razão entre lados correspondentes é chamada de **razão de semelhança** k. Se um triângulo tem lados 3, 4 e 5 e outro tem 6, 8 e 10, a razão é 2, e eles são semelhantes.',
  'Os **casos de semelhança** permitem concluir sem verificar tudo: AA (dois ângulos iguais, já que o terceiro é consequência), LAL (dois lados proporcionais e o ângulo entre eles igual) e LLL (três lados proporcionais). O caso AA é o mais usado em questões. Uma reta paralela a um dos lados de um triângulo, cortando os outros dois, forma um triângulo menor semelhante ao original. É a base do chamado **Teorema de Tales**.',
  'Em figuras semelhantes, as razões entre perímetros são iguais à razão de semelhança k, enquanto as razões entre áreas são k², e entre volumes, k³. Assim, se uma maquete tem escala 1:100, a área real é 10.000 vezes maior que a da maquete, e o volume é 1.000.000 de vezes maior. Esse resultado liga semelhança, escalas e proporcionalidade, e é um tópico muito explorado em provas.'] },
 { h:'Sombras, alturas e medidas indiretas', p:[
  'Uma das aplicações mais clássicas da semelhança é a medição indireta de alturas. Um poste de altura desconhecida projeta uma sombra de 6 m no mesmo instante em que uma estaca de 1,5 m projeta uma sombra de 0,5 m. Como os raios do Sol são paralelos, os triângulos formados são semelhantes: h/6 = 1,5/0,5, logo h = 18 m. A condição é que os dois objetos estejam na posição vertical e a medição seja feita no mesmo momento.',
  'Do mesmo modo, calcula-se a largura de um rio, a altura de um prédio ou a distância a um ponto inacessível usando triângulos semelhantes e medidas feitas apenas em terra firme. Na topografia e na astronomia antiga, essa técnica foi fundamental para medir o mundo sem precisar chegar até os pontos de interesse. O que importa é identificar dois triângulos com ângulos iguais e organizar a proporção com os lados correspondentes.',
  'Para evitar erros, desenhe os triângulos separadamente, nomeie os vértices e liste os lados correspondentes na mesma ordem. Os lados correspondentes são os opostos a ângulos iguais. Confundir os correspondentes é a principal fonte de erro. Em seguida, monte a proporção, simplifique e resolva. Conferir se o resultado é plausível (por exemplo, um poste não pode ter 180 m) também é recomendável.'] },
 { h:'Relações métricas no triângulo retângulo e teorema de Tales', p:[
  'Ao traçar a altura relativa à hipotenusa de um triângulo retângulo, formam-se dois triângulos menores semelhantes ao original. Desse fato nascem relações importantes: h² = m · n (a altura ao quadrado é o produto das projeções dos catetos na hipotenusa), b² = a · n e c² = a · m (cada cateto ao quadrado é a hipotenusa vezes sua projeção) e a · h = b · c. Elas simplificam problemas em que a altura é dada ou pedida.',
  'O **Teorema de Tales** diz que um feixe de retas paralelas cortado por duas transversais determina segmentos proporcionais. Se três retas paralelas cortam duas transversais, os segmentos correspondentes mantêm a mesma razão: AB/BC = A\'B\'/B\'C\'. É o resultado usado, por exemplo, para dividir um segmento em partes iguais ou para calcular medidas de lotes de terreno cortados por ruas paralelas.',
  'Questões práticas incluem lotes com frentes para uma rua e fundos em outra, rampas de acesso, escadas e telhados. Nesses cenários, a ideia é a mesma: reconhecer o paralelismo, identificar as transversais, montar a proporção e resolver. Praticar com desenhos feitos por você mesmo ajuda a perceber os padrões e a ganhar velocidade na prova.'] },
 { h:'Como se preparar para este tema', p:[
  'Comece decorando o teorema de Pitágoras e as ternas mais comuns, e depois pratique reconhecer triângulos retângulos em situações práticas. Nem sempre o enunciado diz "triângulo retângulo": às vezes, descreve escadas, diagonais e distâncias, e cabe a você traduzir o texto em figura. Desenhar é a primeira habilidade a desenvolver, e isso resolve grande parte dos problemas.',
  'Em semelhança, treine a escrita das proporções. Escolha sempre uma convenção, como "pequeno sobre grande" em todas as razões, para evitar inverter. Mantenha a mesma ordem dos vértices ao listar os lados correspondentes. Em problemas com áreas e volumes, lembre do quadrado e do cubo da razão, e não da própria razão.',
  'Por fim, revise os temas conectados: raciocínio proporcional, escalas, trigonometria e áreas. Pitágoras e semelhança são a base para seno, cosseno e tangente, e para boa parte da geometria espacial. Quanto mais firme a base, mais fácil o restante do conteúdo de geometria, e menos tempo você gasta na prova para decidir qual ferramenta usar.'] }
]},

{ t:'Trigonometria', txt:[
 { h:'Razões trigonométricas no triângulo retângulo', p:[
  'A trigonometria estuda as relações entre ângulos e lados dos triângulos. No triângulo retângulo, para um ângulo agudo θ, definem-se três razões. O **seno** é o cateto oposto dividido pela hipotenusa. O **cosseno** é o cateto adjacente dividido pela hipotenusa. A **tangente** é o cateto oposto dividido pelo cateto adjacente. Uma forma de memorizar é "SOH CAH TOA": Seno = Oposto/Hipotenusa, Cosseno = Adjacente/Hipotenusa, Tangente = Oposto/Adjacente.',
  'Essas razões dependem apenas do ângulo, e não do tamanho do triângulo, pois triângulos retângulos com o mesmo ângulo agudo são semelhantes. Por isso podemos tabelar seus valores. Os ângulos notáveis são 30°, 45° e 60°: sen 30° = 1/2, cos 30° = √3/2, tg 30° = √3/3; sen 45° = cos 45° = √2/2, tg 45° = 1; sen 60° = √3/2, cos 60° = 1/2, tg 60° = √3. No ENEM, esses valores costumam ser fornecidos em uma tabela, mas conhecê-los acelera.',
  'Para resolver um problema, desenhe o triângulo retângulo, marque o ângulo e os lados envolvidos (oposto, adjacente, hipotenusa em relação a esse ângulo) e escolha a razão que relaciona o dado conhecido com o desconhecido. Se conhecemos a hipotenusa e queremos o cateto oposto, usamos o seno. Se conhecemos os dois catetos e queremos o ângulo, usamos a tangente e consultamos a tabela.'] },
 { h:'Aplicações: alturas, distâncias e rampas', p:[
  'A trigonometria é a ferramenta clássica para medir o que não se alcança. Se, a 50 m da base de uma torre, o ângulo de visão do topo é 60°, a altura da torre é h = 50 · tg 60° = 50√3 ≈ 86,6 m. Não é preciso subir para medir. Da mesma forma, calcula-se a altura de um prédio, a largura de um rio ou a altura de uma árvore usando um ângulo e uma distância fáceis de medir.',
  'Em rampas e telhados, a inclinação é associada ao ângulo e à razão entre altura e comprimento horizontal. Uma rampa que sobe 1 m a cada 12 m na horizontal tem tg θ = 1/12 ≈ 0,083, o que corresponde a cerca de 4,8°. Normas de acessibilidade estabelecem inclinações máximas expressas em porcentagem, que é exatamente a tangente multiplicada por 100. Assim, 8,33% equivale a 1:12.',
  'Na navegação e na aviação, ângulos de elevação e depressão determinam rotas e altitudes. O ângulo de elevação é medido a partir da horizontal para cima (como ao olhar um avião), e o de depressão, para baixo (como ao olhar um barco do alto de um farol). Em ambos os casos, a horizontal é a referência. Desenhar a linha horizontal e o triângulo formado é o caminho para não errar.'] },
 { h:'Relações fundamentais e ciclo trigonométrico', p:[
  'A relação fundamental da trigonometria afirma que sen²θ + cos²θ = 1. Ela vem de Pitágoras aplicado ao triângulo retângulo de hipotenusa 1. A partir dela, e da definição tgθ = senθ/cosθ, obtêm-se outros resultados. Se senθ = 3/5, então cos²θ = 1 − 9/25 = 16/25 e cosθ = 4/5 (para ângulo agudo). Essa identidade permite calcular uma razão a partir da outra.',
  'Para ângulos maiores que 90°, usa-se o **ciclo trigonométrico**, uma circunferência de raio 1 em que o ângulo é medido a partir do eixo horizontal no sentido anti-horário. O cosseno é a coordenada horizontal do ponto e o seno é a coordenada vertical. Assim, o seno é positivo no 1º e 2º quadrantes, e o cosseno é positivo no 1º e 4º. Ângulos podem ser medidos em radianos, sendo 180° = π rad.',
  'Os valores de seno e cosseno variam entre −1 e 1 e se repetem a cada 360° (2π). Essa **periodicidade** faz dessas funções os modelos ideais de fenômenos cíclicos: marés, estações do ano, ondas sonoras, corrente alternada e batimentos cardíacos. Questões do ENEM costumam apresentar funções como f(t) = A·sen(ωt) + C e perguntar o valor máximo, o mínimo e o período, que se leem diretamente da fórmula.'] },
 { h:'Funções seno e cosseno em fenômenos periódicos', p:[
  'Em uma função do tipo y = a + b·sen(cx + d), o termo **a** desloca o gráfico verticalmente e indica o valor médio; o módulo de **b** é a amplitude (metade da distância entre máximo e mínimo); **c** controla o período, dado por 2π/|c|; e **d** desloca o gráfico horizontalmente. O valor máximo é a + |b|, e o mínimo, a − |b|. Com esses elementos, interpretam-se questões sobre temperaturas, marés e populações cíclicas.',
  'Por exemplo, a altura da maré em um porto pode ser modelada por h(t) = 3 + 2·sen(πt/6), com t em horas. A altura média é 3 m, a amplitude é 2 m, e a altura varia entre 1 m e 5 m. O período é 2π/(π/6) = 12 horas, o que indica a repetição do ciclo a cada 12 horas. Responder perguntas como "qual a altura máxima?" ou "de quanto em quanto tempo a maré se repete?" é só questão de interpretar os parâmetros.',
  'Se o enunciado pede o instante em que a altura atinge determinado valor, resolva a equação trigonométrica correspondente usando o ciclo e os ângulos notáveis. Atenção ao fato de que, dentro de um período, existem em geral duas soluções (por exemplo, sen x = 1/2 tem x = 30° e x = 150°). Escolha as que estão no intervalo pedido, e use a periodicidade para encontrar as demais.'] },
 { h:'Lei dos senos e dos cossenos', p:[
  'Para triângulos quaisquer, não necessariamente retângulos, existem duas leis. A **lei dos senos** diz que a/senA = b/senB = c/senC = 2R, onde R é o raio da circunferência circunscrita. Ela é útil quando se conhecem dois ângulos e um lado, ou dois lados e um ângulo oposto a um deles. A **lei dos cossenos** diz que a² = b² + c² − 2bc·cosA, e é uma generalização do teorema de Pitágoras (se A = 90°, cos A = 0 e voltamos a Pitágoras).',
  'A lei dos cossenos é usada quando se conhecem dois lados e o ângulo entre eles (para achar o terceiro lado) ou os três lados (para achar um ângulo). Em problemas de navegação, topografia e engenharia, essas leis permitem calcular distâncias entre pontos sem acesso direto. Por exemplo, a distância entre dois navios, dados suas distâncias a um farol e o ângulo entre as direções, vem da lei dos cossenos.',
  'Na prova, verifique primeiro se o triângulo é retângulo: se for, as razões simples bastam. Caso contrário, escolha a lei adequada ao dado disponível. Atenção aos sinais: cos 120° = −1/2, de modo que a lei dos cossenos para um ângulo obtuso aumenta o lado oposto. Treinar com poucos exercícios, com triângulos bem desenhados, é suficiente para dominar o tema.'] }
]},

{ t:'Geometria espacial: volumes', txt:[
 { h:'Sólidos geométricos e suas características', p:[
  'A geometria espacial estuda figuras com três dimensões: comprimento, largura e altura. Os **poliedros** são sólidos limitados por polígonos, como cubos, paralelepípedos, prismas e pirâmides. Os **corpos redondos** têm superfícies curvas, como cilindro, cone e esfera. Cada sólido tem faces, arestas e vértices (no caso dos poliedros), e a relação de Euler, V − A + F = 2, vale para poliedros convexos: o cubo, com 8 vértices, 12 arestas e 6 faces, a satisfaz (8 − 12 + 6 = 2).',
  'O **volume** mede o espaço ocupado pelo sólido e é expresso em unidades cúbicas (m³, cm³). A **área da superfície** soma as áreas de todas as faces. A **capacidade** é o volume interno que um recipiente comporta, geralmente em litros, com 1 L = 1 dm³ = 1.000 cm³. Compreender essas diferenças evita erros como calcular a superfície quando se pede o volume, o que ocorre com frequência em questões de embalagens.',
  'A estratégia geral é identificar o sólido (ou a combinação de sólidos), encontrar as medidas necessárias (raio, altura, arestas) e aplicar a fórmula adequada. Em muitos casos, o enunciado fornece figuras, e as medidas aparecem nelas. Uma leitura atenta da figura evita erros, pois, às vezes, a altura é diferente da aresta lateral (como no cone e na pirâmide).'] },
 { h:'Prismas, cilindros e o princípio de Cavalieri', p:[
  'O volume de um **prisma** é o produto da área da base pela altura: V = Ab · h. Para o cubo de aresta a, V = a³; para o paralelepípedo de arestas a, b e c, V = a · b · c. O **cilindro** segue a mesma regra: V = πr²h, e a área lateral é 2πrh. A ideia comum é "empilhar" camadas iguais à base ao longo da altura. Esse raciocínio é válido mesmo para prismas e cilindros inclinados, pelo **princípio de Cavalieri**: dois sólidos com mesma altura e áreas iguais em cada seção paralela à base têm o mesmo volume.',
  'Por exemplo, uma caixa-d\'água em forma de cilindro com raio de 1 m e altura de 2 m comporta V = π · 1² · 2 ≈ 6,28 m³, ou seja, cerca de 6.280 litros. Uma piscina retangular de 8 m por 4 m por 1,5 m de profundidade tem V = 48 m³, equivalente a 48.000 litros. Essas conversões entre m³ e litros são recorrentes em problemas de reservatórios, piscinas e tanques.',
  'Problemas de preenchimento e esvaziamento combinam volume com vazão. Se uma torneira despeja 20 L por minuto, o tempo para encher um reservatório de 6.000 litros é 6.000/20 = 300 minutos, ou 5 horas. Fazer o raciocínio por etapas (calcular o volume, converter a unidade, dividir pela vazão) é a abordagem mais segura.'] },
 { h:'Pirâmides, cones e esferas', p:[
  'A **pirâmide** e o **cone** têm volume igual a um terço do volume do prisma ou cilindro de mesma base e altura: V = (Ab · h)/3 para a pirâmide e V = (πr²h)/3 para o cone. Esse fator 1/3 é um dos pontos mais cobrados: um cone com a mesma base e altura de um cilindro comporta exatamente um terço do volume. Também se pode lembrar disso pensando que três cones cheios enchem um cilindro de mesma base e altura.',
  'No cone, a **geratriz** g (o lado inclinado) relaciona-se ao raio e à altura por Pitágoras: g² = r² + h². A área lateral é πrg. Na pirâmide regular, a altura da face lateral (apótema da pirâmide) também se relaciona à altura e ao apótema da base por Pitágoras. Saber extrair triângulos retângulos dentro dos sólidos é uma das habilidades mais importantes do tema.',
  'A **esfera** tem volume V = (4/3)πr³ e área de superfície A = 4πr². Um aumento de 10% no raio aumenta o volume em cerca de 33% (1,1³ ≈ 1,331), e a área em 21%. Esse tipo de variação é cobrado em questões sobre bolas, bolhas, gotas e planetas. Se o raio dobra, o volume é multiplicado por 8 e a área por 4.'] },
 { h:'Sólidos compostos, troncos e proporcionalidade', p:[
  'Muitos objetos reais são combinações de sólidos: um silo (cilindro com cone), uma casa (prisma com pirâmide ou prisma triangular no telhado), uma cápsula de remédio (cilindro com duas semiesferas). Para calcular o volume, decomponha o objeto, calcule cada parte e some (ou subtraia, se houver um espaço vazio). Atente para não somar duas vezes a parte comum às duas formas.',
  'O **tronco de cone** ou de pirâmide aparece quando se corta o sólido por um plano paralelo à base. O volume do tronco é a diferença entre o volume do sólido original e o da parte superior removida, que é semelhante ao original. Aqui entra a semelhança: se a razão linear é k, a razão dos volumes é k³. Por exemplo, se a ponta removida tem metade da altura, seu volume é 1/8 do volume total, e o tronco corresponde a 7/8.',
  'Em problemas de proporcionalidade, lembre que volumes crescem com o cubo das dimensões lineares e áreas, com o quadrado. Uma embalagem com todas as dimensões 20% maiores tem capacidade 1,2³ ≈ 1,728 vez maior, isto é, cerca de 73% a mais. A quantidade de material, que depende da área, cresce 44%. Questões de comparação de embalagens e de custo-benefício exploram essas diferenças.'] },
 { h:'Estratégias, conversões e aplicações', p:[
  'Comece sempre identificando o sólido e os dados disponíveis. Se a figura traz a altura e o diâmetro (e não o raio), cuidado: o raio é metade do diâmetro. Converta todas as medidas para a mesma unidade antes de calcular, e, no final, converta o volume para a unidade pedida (litros, m³). Escreva as fórmulas antes de substituir os valores, pois isso reduz erros de lembrança.',
  'Questões de imersão envolvem o princípio de que um corpo mergulhado em um líquido desloca um volume igual ao seu. Se uma pedra é colocada em um recipiente cilíndrico e o nível sobe 2 cm, o volume da pedra é a área da base do recipiente vezes 2 cm. Esse tipo de raciocínio aparece em situações de laboratório e de uso cotidiano, e é resolvido com a fórmula do volume do cilindro.',
  'Para revisar, monte uma folha com as fórmulas dos principais sólidos e as relações entre eles (1/3 para pirâmide e cone, 4/3 para esfera, cubo da razão para semelhança). Depois, pratique desenhando os sólidos e marcando as medidas. A visualização espacial melhora com a prática e é uma das habilidades mais valorizadas pelo exame, que privilegia problemas contextualizados de capacidade, embalagem e armazenamento.'] }
]}
];
