/* Química: textos corridos, temas 1 a 3 */
module.exports = [
{ t:'Matéria e suas propriedades', txt:[
 { h:'O que é matéria e como a Química a estuda', p:[
  'Chamamos de **matéria** tudo o que tem massa e ocupa lugar no espaço. O ar que respiramos, a água, uma pedra, o corpo humano e as estrelas são exemplos. A Química é a ciência que estuda a matéria, suas propriedades, suas transformações e as energias envolvidas nesses processos. Para organizar o estudo, a Química distingue três ideias: **corpo**, uma porção limitada de matéria (um pedaço de ferro); **objeto**, um corpo fabricado para uma finalidade (uma chave); e **substância**, um tipo de matéria com composição e propriedades definidas (a água, o ferro).',
  'A matéria é formada por átomos e moléculas, partículas extremamente pequenas que estão em constante movimento. Esse modelo, chamado de **modelo cinético-molecular**, ajuda a explicar por que a matéria se apresenta em diferentes estados e por que ela muda de estado quando recebe ou perde energia. Quanto maior a temperatura, mais agitadas ficam as partículas, e isso tem consequências diretas no volume, na densidade e no estado físico dos materiais.',
  'Conhecer a matéria é, em essência, conhecer suas **propriedades**: características que permitem descrevê-la, compará-la e identificá-la. Elas se dividem em gerais (comuns a toda matéria), específicas (próprias de cada substância) e organolépticas (percebidas pelos sentidos). Entender essas categorias é o primeiro passo para resolver questões que pedem, por exemplo, para identificar uma substância desconhecida a partir de dados experimentais, como o ponto de fusão e a densidade.'] },
 { h:'Propriedades gerais e específicas', p:[
  'As **propriedades gerais** são aquelas que qualquer porção de matéria apresenta, independentemente de qual substância seja. Entre elas estão a **massa** (quantidade de matéria), o **volume** (espaço ocupado), a **inércia** (tendência de manter o estado de movimento), a **impenetrabilidade** (dois corpos não ocupam o mesmo lugar ao mesmo tempo), a **divisibilidade**, a **compressibilidade** e a **elasticidade**. Como todas as substâncias as têm, essas propriedades não servem para identificar uma substância específica.',
  'As **propriedades específicas** são próprias de cada substância, e por isso funcionam como uma "impressão digital". As **físicas** incluem a densidade, o ponto de fusão (PF), o ponto de ebulição (PE), a solubilidade, a condutibilidade elétrica e térmica, a dureza e o brilho. As **químicas** descrevem a capacidade de reagir, como a inflamabilidade do álcool, a oxidação do ferro e a acidez do limão. Uma substância pura tem PF e PE bem definidos e constantes, o que é muito útil para testar sua pureza.',
  'As **propriedades organolépticas** são as que percebemos pelos sentidos: cor, odor, sabor, textura. Em laboratório, não é seguro provar ou cheirar substâncias desconhecidas, então se usam as demais propriedades. Já no cotidiano, a cor, o cheiro e o sabor são indicadores úteis, como no caso de um alimento estragado. Em questões, o mais frequente é fornecer uma tabela com as propriedades de várias substâncias e pedir que o candidato identifique qual delas corresponde a uma amostra descrita.'] },
 { h:'Estados físicos da matéria e mudanças de estado', p:[
  'A matéria se apresenta, em condições comuns, em três estados. No estado **sólido**, as partículas estão muito próximas e organizadas, vibrando em posições fixas; o corpo tem forma e volume definidos. No estado **líquido**, as partículas estão próximas, mas se movem umas em relação às outras; o volume é definido, e a forma é a do recipiente. No **gasoso**, as partículas estão muito afastadas e se movem livremente; o gás não tem forma nem volume próprios e ocupa todo o recipiente, sendo muito compressível.',
  'As **mudanças de estado** têm nomes específicos: **fusão** (sólido para líquido), **solidificação** (líquido para sólido), **vaporização** (líquido para gás, que pode ocorrer por evaporação, ebulição ou calefação), **condensação** ou liquefação (gás para líquido) e **sublimação** (sólido para gás, e também o inverso, chamado de ressublimação ou cristalização). A sublimação ocorre, por exemplo, com a naftalina e o gelo-seco (CO₂ sólido). Cada mudança envolve absorção ou liberação de calor: a fusão e a vaporização absorvem calor (processos endotérmicos), e as inversas liberam.',
  'Em uma substância pura, durante a mudança de estado, a temperatura **permanece constante**: o calor fornecido é usado para romper ou formar interações entre as partículas, e não para aumentar a agitação. Por isso, a água ferve a 100 °C ao nível do mar e continua a 100 °C enquanto houver líquido, mesmo com fogo alto. Já a pressão influencia: em locais altos, onde a pressão atmosférica é menor, a água ferve a uma temperatura mais baixa, e na panela de pressão ferve a uma temperatura mais alta.'] },
 { h:'Densidade, fenômenos físicos e químicos', p:[
  'A **densidade** relaciona a massa de um material ao seu volume: d = m/V, geralmente em g/cm³ ou kg/m³. É uma propriedade específica, pois cada substância tem seu valor característico: a água, 1 g/cm³; o óleo, cerca de 0,9; o ferro, cerca de 7,9; o ouro, cerca de 19,3. Materiais menos densos flutuam nos mais densos (se não se misturarem), o que explica por que o óleo fica sobre a água. A densidade varia com a temperatura, pois o volume dos materiais muda ao serem aquecidos ou resfriados.',
  'Um **fenômeno físico** é aquele em que não há formação de novas substâncias: a água que congela, o vidro que quebra, o açúcar que se dissolve. Um **fenômeno químico** (ou reação química) é aquele em que novas substâncias se formam, com propriedades diferentes das originais: a queima de papel, o enferrujamento de um prego, a digestão de alimentos, a fermentação. A mudança de estado é sempre um fenômeno físico, pois a substância continua a mesma.',
  'Como saber se ocorreu uma reação química? Alguns **indícios** ajudam: mudança de cor, liberação de gás (efervescência), formação de um sólido (precipitado), liberação de luz ou calor, mudança de odor. Mas atenção: nem todo indício confirma uma reação, e algumas reações não os apresentam de modo visível. Em questões, geralmente se pede a classificação de situações cotidianas em fenômenos físicos ou químicos, e vale perguntar sempre: a substância continua sendo a mesma?'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Embora pareça básico, este tema é a base para tudo o que vem a seguir: substâncias e misturas, separação, estudo dos gases, termoquímica. No ENEM, costuma aparecer em contextos como identificação de substâncias por propriedades, análise de gráficos de aquecimento, interpretação de rótulos e situações do cotidiano (por que a panela de pressão cozinha mais rápido, por que o gelo flutua, por que o óleo não se mistura com a água).',
  'Algumas estratégias: leia com atenção as propriedades fornecidas e compare-as com os valores conhecidos (densidade da água, PF e PE); lembre-se de que, em substâncias puras, os pontos de fusão e de ebulição são constantes, e em misturas variam; nos gráficos de temperatura em função do tempo, os patamares horizontais indicam mudanças de estado; e, em questões de densidade, converta as unidades antes de comparar.',
  'Para fixar, faça uma lista das mudanças de estado e identifique, para cada uma, se é endotérmica ou exotérmica. Treine relacionar fenômenos do dia a dia a categorias: o suor que evapora (vaporização, endotérmica, resfria o corpo), a roupa que seca (evaporação), a formação de orvalho (condensação), a neve (solidificação do vapor, ressublimação). Esse exercício torna o assunto concreto e ajuda a responder rapidamente a questões conceituais.'] }
]},

{ t:'Substâncias e misturas', txt:[
 { h:'Substâncias puras: simples e compostas', p:[
  'Uma **substância pura** é um material de composição fixa e propriedades constantes, como a água, o sal de cozinha e o ouro. Ela se divide em dois grupos. As **substâncias simples** são formadas por átomos de um único elemento químico: o gás oxigênio (O₂), o ferro (Fe), o ozônio (O₃) e o diamante (C). As **substâncias compostas** são formadas por átomos de dois ou mais elementos diferentes, ligados em proporção fixa: a água (H₂O), o gás carbônico (CO₂) e o sal de cozinha (NaCl).',
  'Um elemento químico pode formar mais de uma substância simples, fenômeno chamado de **alotropia**. O carbono ocorre como diamante, grafite, fulereno e grafeno, com propriedades muito diferentes (o diamante é transparente e muito duro; o grafite é escuro, macio e conduz eletricidade). O oxigênio forma o O₂, que respiramos, e o O₃ (ozônio), que protege da radiação ultravioleta. Em questões, é comum pedir para distinguir a substância simples do elemento, e identificar casos de alotropia.',
  'As substâncias puras têm pontos de fusão e de ebulição bem definidos, e densidade constante, o que permite testar sua pureza. Quando se aquece uma substância pura, o gráfico da temperatura em função do tempo apresenta **patamares** nas mudanças de estado: a temperatura fica constante enquanto a fusão ou a ebulição ocorre. Esse é um critério importante para diferenciar uma substância pura de uma mistura, em que a temperatura varia durante as mudanças de estado.'] },
 { h:'Misturas homogêneas e heterogêneas', p:[
  'Uma **mistura** é formada por duas ou mais substâncias, que mantêm suas identidades e podem ser separadas por processos físicos. Suas propriedades (como PF, PE e densidade) não são fixas, pois dependem da composição. A mistura pode ser **homogênea**, quando apresenta uma única fase (aspecto uniforme), ou **heterogênea**, quando apresenta duas ou mais fases (aspecto não uniforme). As misturas homogêneas são também chamadas de **soluções**.',
  'Exemplos de mistura homogênea: água com sal dissolvido, ar atmosférico filtrado (sem poeira), o álcool hidratado (etanol e água), ligas metálicas como o aço e o latão. Exemplos de mistura heterogênea: água e óleo, água e areia, granito (quartzo, feldspato e mica), leite com pedaços de cereal. Para classificar, conte as **fases**: uma fase, homogênea; duas ou mais, heterogênea. Uma fase é cada porção uniforme do sistema, que pode ser vista a olho nu ou com um microscópio comum.',
  'Atenção: o número de fases não é o mesmo que o número de componentes. Água com gelo tem duas fases (líquida e sólida), mas um só componente (água), e é uma substância pura. Já água com sal dissolvido tem uma fase e dois componentes. Misturas de gases são sempre homogêneas, pois os gases se misturam em qualquer proporção. Esses detalhes são explorados em questões de classificação de sistemas, em que se pedem fases e componentes.'] },
 { h:'Casos especiais: coloides, ligas, azeótropos e eutéticos', p:[
  'Entre as soluções e as misturas heterogêneas, existem os **coloides**, em que as partículas dispersas são maiores que as de uma solução e menores que as de uma suspensão. Parecem homogêneos a olho nu, mas ao microscópio ou ao serem atravessados por um feixe de luz (efeito Tyndall) revelam-se heterogêneos. Leite, gelatina, maionese, neblina, fumaça e espuma são coloides. Por isso, o feixe de luz de uma lanterna é visível na fumaça ou em um ambiente com poeira.',
  'As **ligas metálicas** são misturas homogêneas de metais (ou de metais com outros elementos), com propriedades superiores às dos componentes. O aço é ferro com carbono; o latão, cobre e zinco; o bronze, cobre e estanho; o ouro 18 quilates, ouro com cobre e prata. Ligas são usadas para melhorar a dureza, a resistência à corrosão ou o aspecto. A diferença para uma substância pura é que sua composição pode variar.',
  'Há misturas com comportamento particular. A **mistura azeotrópica** ferve a temperatura constante, como uma substância pura, em uma composição específica (a mistura de 96% de etanol com 4% de água ferve a 78,2 °C, o que impede obter álcool totalmente puro por simples destilação). A **mistura eutética** funde a temperatura constante. No gráfico de aquecimento, a mistura comum não apresenta patamares; a azeotrópica apresenta patamar na ebulição, e a eutética, na fusão. Esses casos costumam ser mencionados em questões de gráficos de mudança de estado.'] },
 { h:'Representação das substâncias: elementos, símbolos e fórmulas', p:[
  'Um **elemento químico** é o conjunto de átomos de mesmo número atômico (número de prótons). Cada elemento tem um **símbolo**: uma ou duas letras, a primeira maiúscula. Alguns vêm do nome em latim: Na (natrium, sódio), K (kalium, potássio), Fe (ferrum, ferro), Cu (cuprum, cobre), Ag (argentum, prata), Au (aurum, ouro). Os símbolos são universais e permitem a comunicação entre cientistas de qualquer idioma.',
  'As substâncias são representadas por **fórmulas**, que indicam os elementos e as quantidades de átomos. Em H₂O, há dois átomos de hidrogênio e um de oxigênio; em C₆H₁₂O₆ (glicose), seis de carbono, doze de hidrogênio e seis de oxigênio. O número escrito abaixo e à direita do símbolo é o **índice**, e o número escrito antes da fórmula é o **coeficiente**, que indica a quantidade de moléculas ou de unidades: 3 H₂O significa três moléculas de água, cada uma com dois H e um O, totalizando seis H e três O.',
  'Quanto à classificação, uma substância simples é aquela cuja fórmula contém um único elemento (O₂, N₂, Fe, P₄), e uma composta, dois ou mais (CO₂, NH₃, NaCl). Uma fórmula como O₂ mostra uma molécula formada por dois átomos do mesmo elemento: é uma substância simples, e não um composto. Saber ler fórmulas e identificar o tipo de substância é uma habilidade básica cobrada com frequência.'] },
 { h:'Como resolver questões sobre substâncias e misturas', p:[
  'Diante de uma questão, identifique primeiro se o sistema é uma substância pura ou uma mistura. Indícios de substância pura: PF e PE constantes, patamares nos gráficos, fórmula única. Indícios de mistura: temperatura variando durante a mudança de estado, composição variável, mais de uma substância mencionada. Depois, se for mistura, conte as fases para classificar em homogênea ou heterogênea.',
  'Em questões de gráfico de aquecimento, observe os patamares: se há patamar na fusão e na ebulição, é substância pura; se há patamar somente em um deles, pode ser mistura eutética ou azeotrópica; se não há patamar, é uma mistura comum. Também é útil identificar o estado físico em cada trecho e os pontos de fusão e ebulição, comparando-os com os valores conhecidos de substâncias comuns.',
  'Em situações do cotidiano, treine o reconhecimento: o ar limpo é mistura homogênea de gases (nitrogênio, oxigênio e outros); a água do mar, mistura homogênea de água e sais; o petróleo, mistura complexa de hidrocarbonetos; o sangue, um coloide; a água destilada, uma substância composta. Reconhecer esses exemplos o ajuda a responder de forma rápida e correta nas provas, e prepara a compreensão dos métodos de separação, que é o tema seguinte.'] }
]},

{ t:'Separação de misturas', txt:[
 { h:'Por que e como separar', p:[
  'Separar os componentes de uma mistura é uma necessidade frequente: para obter água potável, produzir combustíveis, purificar medicamentos, reciclar materiais ou extrair metais de minérios. A escolha do método depende do **tipo de mistura** (homogênea ou heterogênea) e das **propriedades** que diferenciam os componentes: tamanho das partículas, densidade, solubilidade, ponto de ebulição, magnetismo. A ideia geral é explorar uma diferença de propriedades entre os componentes.',
  'Nos processos de separação, as substâncias não são transformadas quimicamente: apenas separadas. Por isso, são processos **físicos**. Em geral, o procedimento mais simples e barato possível é o escolhido, começando pelos métodos mecânicos para misturas heterogêneas e passando aos que exigem mudança de estado (evaporação, destilação) para as homogêneas. Em questões, é comum apresentar uma mistura e pedir a sequência correta de métodos para separar todos os componentes.',
  'Uma dica prática é classificar a mistura de início. Se for heterogênea, procure uma característica visível ou física (tamanho, densidade, magnetismo). Se for homogênea, olhe para o estado dos componentes: sólido e líquido, líquido e líquido, gás e gás. Esse raciocínio guia a escolha entre filtração, decantação, destilação e outros métodos, e evita o erro de aplicar um método que não funcionaria no caso.'] },
 { h:'Métodos para misturas heterogêneas', p:[
  'A **catação** é a separação manual de fragmentos sólidos, como a escolha do feijão antes do cozimento. A **peneiração** (ou tamisação) separa sólidos de tamanhos diferentes com uma peneira, como na obtenção de farinha fina ou na separação de areia e cascalho. A **filtração** separa um sólido de um líquido ou gás usando um filtro, como o coador de café, o filtro de água e o filtro de ar. A **levigação** usa um fluxo de água para arrastar o material mais leve, técnica usada pelos garimpeiros na separação do ouro da areia.',
  'A **decantação** utiliza a diferença de densidade: deixa-se a mistura em repouso e o componente mais denso se deposita no fundo. Para sólido e líquido, retira-se o líquido; para dois líquidos imiscíveis (água e óleo), usa-se o **funil de decantação** (ou de bromo), que permite escoar o líquido mais denso pela parte inferior. A **centrifugação** acelera a decantação por rotação, e é usada em laboratórios de análises clínicas, na separação do plasma e das células do sangue.',
  'A **separação magnética** usa um ímã para retirar materiais que são atraídos, como o ferro misturado à areia, e é usada em reciclagem e em mineração. A **flotação** aproveita a diferença de densidade em relação a um líquido: ao adicionar água a uma mistura de areia e serragem, a serragem flutua e é retirada. A **dissolução fracionada** usa um solvente que dissolve apenas um dos componentes, como a água na mistura de sal e areia: o sal se dissolve, e a areia é separada por filtração. A **ventilação** separa grãos de cascas pela diferença de peso, soprando ar.'] },
 { h:'Métodos para misturas homogêneas', p:[
  'Para misturas homogêneas de **sólido e líquido** (como água e sal), podem-se usar a **evaporação** (deixa-se o líquido evaporar, e o sólido permanece, como nas salinas, onde a água do mar evapora e o sal cristaliza), a **cristalização** (resfria-se ou evapora-se parte da solução, formando cristais do sólido) e a **destilação simples** (aquece-se a mistura, vaporiza-se o líquido, condensa-se o vapor e coleta-se o líquido puro, enquanto o sólido permanece no balão). A destilação simples permite recuperar o líquido, ao contrário da evaporação.',
  'Para misturas de **líquidos miscíveis**, com pontos de ebulição diferentes (como etanol e água), usa-se a **destilação fracionada**: aquece-se a mistura, e o componente de menor ponto de ebulição vaporiza primeiro, passando por uma coluna de fracionamento, em que há condensação e vaporização sucessivas, o que melhora a separação. É o método usado na separação das frações do **petróleo** (gás, gasolina, querosene, diesel, óleos lubrificantes, asfalto) e na produção de bebidas destiladas.',
  'Para misturas de **gases**, como o ar, usa-se a **liquefação fracionada**: o ar é resfriado e comprimido até se liquefazer, e depois aquecido lentamente, separando nitrogênio (PE −196 °C), argônio e oxigênio (PE −183 °C) conforme cada um vaporiza. Outros métodos são a **cromatografia**, que separa componentes pela diferença de afinidade com uma fase móvel e uma fixa (usada em análises de pigmentos, doping e alimentos), e a **sublimação**, para separar um sólido que sublima (iodo, naftalina) de um que não sublima.'] },
 { h:'Tratamento de água e esgoto', p:[
  'Um dos exemplos mais completos de combinação de métodos é o **tratamento de água** para abastecimento. A água captada em rios passa pelo **gradeamento**, que retém objetos grandes; pela **pré-cloração** e adição de sulfato de alumínio e cal, que provoca a **floculação** (formação de flocos que aglutinam as impurezas); pela **decantação**, em que os flocos se depositam; e pela **filtração**, com camadas de areia e carvão, que retém as partículas menores. Depois vêm a **desinfecção** (cloro) para eliminar microrganismos, a **correção do pH** e a **fluoretação**.',
  'O **tratamento de esgoto** inclui o tratamento preliminar (grades e caixas de areia), o primário (decantação do material sólido), o secundário (microrganismos que degradam a matéria orgânica) e, às vezes, o terciário (remoção de nutrientes e desinfecção). O lodo gerado pode ser tratado e aproveitado. A falta de saneamento básico é uma das principais causas de doenças de veiculação hídrica, como diarreias, leptospirose e hepatite A, e investimentos em saneamento têm grande retorno em saúde pública.',
  'A **dessalinização** da água do mar, por destilação ou por osmose reversa, é usada em regiões áridas e com escassez de água doce. A **reciclagem** também usa processos de separação: separação magnética de metais ferrosos, flotação de plásticos, decantação e filtração. Em questões do ENEM, é comum pedir a identificação de cada etapa de tratamento e do princípio físico envolvido, e relacionar saneamento e saúde.'] },
 { h:'Estratégias para a prova', p:[
  'Uma boa estratégia é montar um pequeno "mapa" mental: heterogênea sólido-sólido (catação, peneiração, separação magnética, flotação, dissolução fracionada); heterogênea sólido-líquido (filtração, decantação, centrifugação); heterogênea líquido-líquido (decantação com funil); homogênea sólido-líquido (evaporação, destilação simples, cristalização); homogênea líquido-líquido (destilação fracionada); homogênea gás-gás (liquefação fracionada).',
  'Em enunciados com sequência de etapas, determine qual propriedade permite cada separação, e ordene as etapas de modo que a anterior não prejudique a seguinte. Por exemplo, para separar sal, areia e limalha de ferro: primeiro o ímã (retira o ferro), depois a adição de água (dissolve o sal), a filtração (retém a areia) e a evaporação da água (recupera o sal). Notar que cada passo isola um componente por uma propriedade distinta ajuda muito.',
  'Atenção aos detalhes: a evaporação perde o solvente, e a destilação simples o recupera; a decantação separa líquidos imiscíveis, e a destilação fracionada, líquidos miscíveis; a filtração não separa componentes dissolvidos. Em desenhos de aparelhagem (balão, condensador, funil, béquer), identifique o equipamento e o processo. Praticar com exemplos do dia a dia (café coado, água com óleo, salinas) fixa o conteúdo de forma duradoura.'] }
]}
];
