/* Química: textos corridos, temas 4 a 6 */
module.exports = [
{ t:'Modelos atômicos', txt:[
 { h:'A ideia de átomo e o modelo de Dalton', p:[
  'A palavra átomo vem do grego e significa "indivisível". A ideia de que a matéria é formada por partículas minúsculas e indivisíveis surgiu na Grécia antiga, com Leucipo e Demócrito, mas era apenas filosófica. Só no início do século XIX, John Dalton propôs uma teoria científica baseada em experimentos sobre as proporções das reações. Segundo ele, a matéria é formada por átomos **maciços, esféricos, indivisíveis e indestrutíveis**, e os átomos de um mesmo elemento são idênticos entre si, diferindo dos de outros elementos.',
  'Dalton explicou as leis das reações químicas conhecidas na época. A **lei de Lavoisier** (conservação da massa) é explicada porque, em uma reação, os átomos apenas se rearranjam, sem serem criados nem destruídos. A **lei de Proust** (proporções constantes) é explicada porque os compostos são formados por átomos combinados em proporções fixas. O modelo ficou conhecido como "bola de bilhar", por representar o átomo como uma esfera sólida e sem estrutura interna.',
  'O modelo de Dalton tinha limitações: não explicava a eletricidade da matéria, nem a existência de partículas menores que o átomo. Hoje sabemos que o átomo é divisível em partículas subatômicas, e que os átomos de um mesmo elemento podem ter massas diferentes (isótopos). Mas o modelo foi um marco, pois estabeleceu a base da Química moderna: a matéria é descontínua e formada por átomos que se combinam em proporções definidas.'] },
 { h:'Thomson e a descoberta do elétron', p:[
  'No final do século XIX, experimentos com **tubos de raios catódicos** (tubos de vidro com gás a baixa pressão e dois eletrodos, submetidos a alta tensão) mostraram a emissão de raios que se desviavam em campos elétricos e magnéticos e eram atraídos pela placa positiva. J. J. Thomson, em 1897, concluiu que esses raios eram formados por partículas de carga **negativa**, os **elétrons**, presentes em qualquer material usado como eletrodo. Isso mostrava que o átomo não era indivisível.',
  'Para explicar a neutralidade elétrica da matéria, Thomson propôs o modelo do "**pudim de passas**": o átomo seria uma esfera de carga positiva, na qual estariam incrustados os elétrons de carga negativa, como passas em um pudim, de modo que as cargas se compensavam. Era um avanço importante, pois incluía partículas subatômicas e explicava a eletrização, mas não dava conta de alguns resultados experimentais posteriores.',
  'A descoberta do elétron mostra como os modelos científicos evoluem: um novo experimento revela fatos que o modelo anterior não explica, e surge uma proposta mais completa. Essa visão da ciência como construção provisória é frequentemente explorada em questões, que pedem para relacionar cada experimento a um modelo ou a uma conclusão. Associar "raios catódicos" a Thomson e "elétron" é um ponto básico.'] },
 { h:'Rutherford e o átomo nucleado', p:[
  'Em 1911, Ernest Rutherford e colaboradores bombardearam uma fina lâmina de ouro com partículas alfa (positivas), emitidas por um material radioativo, e observaram a trajetória das partículas com uma tela fluorescente. A maioria atravessou a lâmina sem desvio; algumas sofreram pequenos desvios; e pouquíssimas (cerca de 1 em 10.000) voltaram. Pelo modelo de Thomson, esperava-se que todas atravessassem com desvios pequenos, e o resultado surpreendeu: nas palavras dele, foi como disparar um projétil contra uma folha de papel e ele voltar.',
  'Rutherford interpretou os resultados assim: o átomo é, em sua maior parte, **espaço vazio** (por isso a maioria das partículas passa direto); há um **núcleo** minúsculo, denso e **positivo**, no qual se concentra praticamente toda a massa (as partículas que passam perto dele são desviadas, e as poucas que o atingem de frente voltam); e os **elétrons** giram ao redor do núcleo, na região chamada de **eletrosfera**, como planetas em torno do Sol. Por isso, o modelo é chamado de **planetário**.',
  'O modelo de Rutherford tinha uma falha: pela Física clássica, um elétron em movimento acelerado ao redor do núcleo emitiria energia e acabaria "caindo" no núcleo, o que tornaria os átomos instáveis. Além disso, não explicava os espectros de linhas dos elementos. A proporção entre os tamanhos é notável: se o núcleo tivesse o tamanho de uma bola de gude, o átomo teria o tamanho de um estádio de futebol. Esse tipo de comparação é útil para entender a ideia de espaço vazio.'] },
 { h:'Bohr e o modelo quântico', p:[
  'Niels Bohr (1913) aperfeiçoou o modelo de Rutherford incorporando a ideia de quantização da energia. Ele propôs que os elétrons se movem em **órbitas circulares** de energias definidas, os **níveis de energia** (camadas K, L, M, N, ...), sem emitir radiação enquanto permanecem em uma órbita (estados estacionários). O elétron só pode **saltar** de um nível a outro absorvendo ou emitindo energia exatamente igual à diferença entre os níveis.',
  'Ao absorver energia (por aquecimento, descarga elétrica ou luz), o elétron salta para um nível mais externo (estado excitado). Ao retornar a um nível mais interno, emite a energia na forma de **luz** de cor característica. Como os níveis de cada elemento são diferentes, cada elemento emite um conjunto próprio de cores, seu **espectro de linhas**. Isso explica o **teste da chama**: sais de sódio dão chama amarela; de cobre, verde-azulada; de potássio, violeta; de lítio, vermelha; e as cores dos fogos de artifício.',
  'O **modelo atual**, da mecânica quântica, é o do **orbital**: não se pode saber com exatidão a posição e a velocidade do elétron ao mesmo tempo (princípio da incerteza de Heisenberg), mas calcula-se a probabilidade de encontrá-lo em uma região do espaço, o orbital. O elétron tem comportamento de onda e de partícula (dualidade onda-partícula, de De Broglie). O modelo de Bohr ainda é útil pela simplicidade para explicar espectros e a organização em camadas.'] },
 { h:'Partículas subatômicas e como responder questões', p:[
  'Hoje sabemos que o átomo é formado por **prótons** (carga positiva, no núcleo), **nêutrons** (sem carga, no núcleo) e **elétrons** (carga negativa, na eletrosfera). A massa do próton e do nêutron é praticamente a mesma, e a do elétron é cerca de 1.836 vezes menor; assim, quase toda a massa do átomo está no núcleo. No átomo neutro, o número de prótons é igual ao de elétrons. A descoberta do nêutron, por Chadwick (1932), completou o quadro e permitiu explicar os isótopos.',
  'Nas questões sobre modelos atômicos, o raciocínio costuma ser: qual experimento ou observação? Que conclusão? Que modelo? Raios catódicos levam a Thomson e ao elétron; bombardeamento de lâmina de ouro leva a Rutherford, ao núcleo e ao espaço vazio; espectros de linhas e testes de chama levam a Bohr e aos níveis de energia. Cada modelo é uma resposta a uma limitação do anterior, e as questões pedem justamente a relação entre eles.',
  'Atenção a alguns erros comuns: atribuir o núcleo a Thomson (é de Rutherford); atribuir a descoberta do elétron a Rutherford (é de Thomson); confundir o modelo de Dalton (esfera maciça) com o de Thomson (esfera com elétrons); esquecer que os modelos são provisórios, e que o atual não é mais o de Bohr. Para memorizar, associe cada cientista a uma imagem: bola de bilhar, pudim de passas, sistema solar, camadas com saltos de energia.'] }
]},

{ t:'Estrutura atômica e tabela periódica', txt:[
 { h:'Número atômico, número de massa e íons', p:[
  'O **número atômico** (Z) é o número de prótons no núcleo e identifica o elemento químico: todos os átomos com Z = 6 são de carbono. O **número de massa** (A) é a soma dos prótons e nêutrons (A = Z + N), e dá a ideia da massa do átomo. Assim, o número de nêutrons é N = A − Z. Em um átomo neutro, o número de elétrons é igual ao de prótons. Para representar, escreve-se o símbolo com Z embaixo e A em cima, como ¹²₆C: 6 prótons, 6 nêutrons e 6 elétrons.',
  'Um átomo pode ganhar ou perder elétrons e se transformar em um **íon**. Quando perde elétrons, fica com excesso de carga positiva e é um **cátion** (Na⁺, Ca²⁺); quando ganha, fica negativo e é um **ânion** (Cl⁻, O²⁻). O número de prótons não muda na formação do íon. Por exemplo, o íon Mg²⁺ tem 12 prótons e 10 elétrons. Em questões, é comum pedir quantas partículas tem um íon, e o raciocínio é sempre o de contar prótons (Z), nêutrons (A − Z) e elétrons (Z menos a carga).',
  'A massa de um átomo é muito pequena para as unidades comuns, então se usa a **unidade de massa atômica (u)**, definida como 1/12 da massa do carbono-12. A massa atômica de um elemento, mostrada na tabela periódica, é a **média ponderada** das massas dos seus isótopos naturais, razão pela qual não é um número inteiro (o cloro, por exemplo, tem massa atômica de cerca de 35,5 u, pois ocorre como cloro-35 e cloro-37 em proporções diferentes).'] },
 { h:'Isótopos, isóbaros e isótonos', p:[
  'Átomos com o mesmo número atômico (mesmo elemento) e diferentes números de massa são **isótopos**. Eles diferem no número de nêutrons e têm propriedades químicas praticamente iguais, pois essas dependem dos elétrons. O hidrogênio tem três isótopos: o prótio (¹H, o mais comum), o deutério (²H) e o trítio (³H, radioativo). O carbono tem os isótopos ¹²C, ¹³C e ¹⁴C, sendo o último radioativo e usado na datação de fósseis.',
  'Átomos com o mesmo número de massa e diferentes números atômicos são **isóbaros**, e têm propriedades químicas diferentes (¹⁴C e ¹⁴N). Átomos com o mesmo número de nêutrons, mas números atômicos e de massa diferentes, são **isótonos**. Por fim, espécies com o mesmo número de elétrons são **isoeletrônicas** (por exemplo, Na⁺, Ne e F⁻, todas com 10 elétrons). Saber nomear esses casos é frequente em questões de classificação.',
  'Os isótopos têm aplicações importantes: o carbono-14 na datação; o iodo-131 e o tecnécio-99m em medicina nuclear; o urânio-235 em reatores nucleares; o deutério em estudos de reações. Isótopos radioativos (radioisótopos) emitem radiação ao se desintegrar, e são usados com cuidado. Em questões, pode ser pedida a composição de um isótopo específico, ou a razão entre isótopos em amostras, e o essencial é a contagem de prótons e nêutrons.'] },
 { h:'Distribuição eletrônica e camada de valência', p:[
  'Os elétrons se distribuem em **camadas** (ou níveis de energia), numeradas de 1 a 7 (K, L, M, N, O, P, Q), e cada camada tem **subníveis**: s, p, d e f, que comportam no máximo 2, 6, 10 e 14 elétrons, respectivamente. O **diagrama de Pauling** mostra a ordem crescente de energia dos subníveis: 1s, 2s, 2p, 3s, 3p, 4s, 3d, 4p, 5s, 4d, 5p, 6s, 4f, 5d, 6p, 7s, 5f, 6d, 7p. Preenchendo os subníveis nessa ordem, obtém-se a **distribuição eletrônica** do elemento. O ferro (Z = 26), por exemplo: 1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶.',
  'A última camada ocupada é a **camada de valência**, e seus elétrons (elétrons de valência) são os responsáveis pelas ligações químicas e pela maior parte das propriedades de cada elemento. Os elementos do mesmo grupo da tabela têm o mesmo número de elétrons de valência, e por isso comportamentos semelhantes. Os metais alcalinos (grupo 1) têm 1 elétron de valência; os halogênios (grupo 17), 7; os gases nobres (grupo 18), 8 (exceto o hélio, com 2).',
  'A **regra do octeto** afirma que os átomos tendem a ganhar, perder ou compartilhar elétrons até ficar com 8 elétrons na camada de valência (como os gases nobres). Isso explica a formação de íons (o sódio perde 1 elétron e vira Na⁺; o cloro ganha 1 e vira Cl⁻) e de ligações covalentes. Embora haja exceções, a regra é muito útil para prever fórmulas e cargas de íons: elementos do grupo 2 formam íons 2+; do grupo 16, íons 2−; do grupo 17, íons 1−.'] },
 { h:'Organização da tabela periódica', p:[
  'A **tabela periódica** organiza os elementos em ordem crescente de número atômico, em **7 períodos** (linhas horizontais) e **18 grupos** (colunas verticais). O número do período indica a quantidade de camadas eletrônicas; o grupo, nos elementos representativos, indica o número de elétrons de valência (grupos 1, 2 e 13 a 18). Os elementos do mesmo grupo (família) têm propriedades químicas semelhantes: alcalinos (grupo 1), alcalinoterrosos (2), calcogênios (16), halogênios (17) e gases nobres (18). Os grupos 3 a 12 reúnem os metais de transição.',
  'Os elementos se dividem em **metais** (maioria; brilho, condutibilidade elétrica e térmica, maleabilidade e ductilidade, tendência a perder elétrons), **ametais** ou não metais (carbono, nitrogênio, oxigênio, enxofre, halogênios; tendência a ganhar elétrons), **semimetais** (silício, germânio; propriedades intermediárias, usados em eletrônica) e **gases nobres** (estáveis, muito pouco reativos). O hidrogênio é um caso à parte: ocupa o grupo 1, mas não é metal.',
  'Dois conjuntos aparecem em linhas separadas: os **lantanídeos** e os **actinídeos** (elementos de transição interna). Muitos dos elementos de números atômicos altos são artificiais, produzidos em laboratórios e instáveis. A tabela é a "ferramenta" mais útil da Química, pois, a partir da posição de um elemento, é possível deduzir muito sobre ele: sua distribuição eletrônica, o tipo de íon que forma, sua reatividade e as ligações que faz.'] },
 { h:'Propriedades periódicas e como usá-las', p:[
  'As **propriedades periódicas** variam de forma regular com o número atômico. O **raio atômico** (tamanho do átomo) **aumenta** de cima para baixo em um grupo (mais camadas) e **diminui** da esquerda para a direita em um período (maior carga nuclear atraindo os elétrons). A **eletronegatividade**, a tendência de atrair elétrons em uma ligação, **aumenta** da esquerda para a direita e de baixo para cima; o flúor é o mais eletronegativo, e os gases nobres não são considerados. A **energia de ionização**, energia para retirar um elétron do átomo, segue a mesma tendência da eletronegatividade.',
  'Já a **eletropositividade** (caráter metálico) tem a tendência oposta: é maior nos metais alcalinos e aumenta de cima para baixo e da direita para a esquerda; o césio e o frâncio são os mais eletropositivos. A **afinidade eletrônica** (energia liberada ao receber um elétron) é alta nos halogênios. A **reatividade** dos metais cresce de cima para baixo (potássio é mais reativo que sódio), e a dos ametais, de baixo para cima (flúor é o mais reativo).',
  'Em questões, o raciocínio é comparar posições na tabela: "qual tem maior raio atômico?" (o mais abaixo e à esquerda); "qual tem maior eletronegatividade?" (o mais acima e à direita); "qual tem menor energia de ionização?" (o mais abaixo e à esquerda). Também são frequentes comparações entre íons: o raio do cátion é menor que o do átomo neutro (menos elétrons, mesma carga nuclear), e o do ânion é maior. Em íons isoeletrônicos, quanto maior o número atômico, menor o raio.'] }
]},

{ t:'Ligações químicas', txt:[
 { h:'Por que os átomos se ligam', p:[
  'Os átomos de quase todos os elementos, com exceção dos gases nobres, não ficam isolados na natureza: formam ligações químicas entre si. A explicação central é a **estabilidade**: ao se ligar, o sistema atinge um estado de menor energia, mais estável. Segundo a regra do octeto, os átomos tendem a completar a camada de valência com 8 elétrons (2, no caso do hidrogênio e do hélio), assumindo a configuração de um gás nobre. Para isso, podem **transferir** elétrons de um átomo a outro ou **compartilhá-los**.',
  'O tipo de ligação depende de quão fortemente cada átomo atrai os elétrons, ou seja, da **eletronegatividade**. Se a diferença de eletronegatividade é grande, como entre um metal e um ametal, há transferência de elétrons e formação de íons (ligação iônica). Se os dois átomos são ametais, com eletronegatividades próximas, os elétrons são compartilhados (ligação covalente). Entre metais, os elétrons de valência ficam livres em uma "nuvem" que mantém os átomos unidos (ligação metálica).',
  'As propriedades de uma substância (ponto de fusão, solubilidade, condutibilidade elétrica, dureza) dependem do tipo de ligação e da estrutura formada. Por isso, entender as ligações permite prever o comportamento dos materiais e explicar fenômenos do cotidiano. Em questões do ENEM, é comum fornecer propriedades de uma substância e pedir para deduzir o tipo de ligação, ou o contrário: dado o tipo de ligação, prever propriedades.'] },
 { h:'Ligação iônica', p:[
  'A **ligação iônica** ocorre entre um **metal** (baixa eletronegatividade, tendência a perder elétrons) e um **ametal** ou o hidrogênio (alta eletronegatividade, tendência a ganhar elétrons). O metal cede elétrons e vira um cátion; o ametal recebe e vira um ânion; os íons de cargas opostas se atraem por forças **eletrostáticas** intensas. Exemplo: o sódio (grupo 1) perde 1 elétron e vira Na⁺; o cloro (grupo 17) ganha 1 e vira Cl⁻; juntos formam o cloreto de sódio, NaCl.',
  'Os compostos iônicos não formam moléculas isoladas, e sim um **retículo cristalino**, uma estrutura tridimensional em que cada íon é cercado por íons de carga oposta. A fórmula indica apenas a proporção entre os íons (fórmula iônica ou fórmula mínima). Para obter a fórmula, equilibram-se as cargas: o cálcio (Ca²⁺) com o cloro (Cl⁻) forma CaCl₂, pois são necessários dois Cl⁻ para neutralizar um Ca²⁺; o alumínio (Al³⁺) com o oxigênio (O²⁻) forma Al₂O₃.',
  'As **propriedades** dos compostos iônicos decorrem da forte atração entre os íons: são **sólidos** à temperatura ambiente, com **altos pontos de fusão e ebulição**, duros e **quebradiços** (o deslocamento de camadas aproxima íons de mesma carga, que se repelem e quebram o cristal). **Não conduzem eletricidade no estado sólido** (íons presos), mas **conduzem fundidos ou dissolvidos em água**, quando os íons ficam livres. Muitos são solúveis em água. Essas características permitem identificar uma substância iônica em questões.'] },
 { h:'Ligação covalente', p:[
  'A **ligação covalente** ocorre entre **ametais** e hidrogênio, pelo **compartilhamento de pares de elétrons**, de modo que cada átomo complete seu octeto. Em H₂, cada hidrogênio compartilha um elétron, formando um par. Em O₂, são compartilhados dois pares (ligação dupla); em N₂, três pares (ligação tripla). Na água, o oxigênio compartilha um par com cada hidrogênio. Na **ligação covalente dativa (coordenada)**, o par compartilhado é fornecido por apenas um dos átomos, como no íon amônio (NH₄⁺) e no ozônio.',
  'Os compostos covalentes podem formar **moléculas** (água, gás carbônico, amônia, metano, glicose), com geometria definida, ou **sólidos covalentes (redes)**, como o diamante, o grafite e o quartzo (SiO₂), em que os átomos formam uma rede gigante, resultando em altíssima dureza e alto ponto de fusão. As substâncias moleculares têm, em geral, **baixos pontos de fusão e ebulição**, e muitas são líquidas ou gasosas à temperatura ambiente, pois as forças entre as moléculas (intermoleculares) são fracas.',
  'A maioria das substâncias moleculares **não conduz** eletricidade no estado puro, pois não há íons nem elétrons livres, mas algumas (ácidos, por exemplo) conduzem em solução aquosa porque reagem com a água formando íons. O grafite é uma exceção entre as redes covalentes: conduz eletricidade graças aos elétrons deslocalizados entre suas camadas. Em questões, é importante saber distinguir o comportamento de substâncias iônicas e covalentes em diferentes estados físicos.'] },
 { h:'Ligação metálica e geometria molecular', p:[
  'Na **ligação metálica**, que ocorre entre átomos de metais, os elétrons de valência ficam **deslocalizados**, formando uma "nuvem" ou "mar" de elétrons que envolve os cátions metálicos. Essa estrutura explica as propriedades dos metais: **brilho** metálico (os elétrons livres refletem a luz), **condutibilidade** elétrica e térmica (elétrons livres se movem), **maleabilidade** (podem ser transformados em lâminas) e **ductilidade** (podem ser transformados em fios), pois as camadas de cátions deslizam sem romper a ligação. As **ligas metálicas** combinam metais para melhorar propriedades.',
  'A **geometria molecular** é a disposição espacial dos átomos em uma molécula, determinada pela repulsão entre os pares de elétrons ao redor do átomo central. Moléculas com dois átomos são sempre **lineares** (H₂, HCl). Entre moléculas de três átomos, o CO₂ é **linear** (180°), enquanto a água é **angular** (cerca de 104,5°), por causa dos dois pares de elétrons livres no oxigênio. A amônia (NH₃) é **piramidal**, e o metano (CH₄), **tetraédrico** (109,5°). O BF₃ é trigonal plano.',
  'A geometria é essencial para determinar a **polaridade** da molécula, e assim as forças intermoleculares, a solubilidade e muitas propriedades físicas. Por isso, é um dos pontos que mais aparece em questões: duas moléculas com ligações polares podem ser apolares (se a geometria for simétrica e os dipolos se anularem, como no CO₂) ou polares (se não houver anulação, como na água). O raciocínio é: identificar a geometria, ver se os vetores dipolo se cancelam e concluir a polaridade.'] },
 { h:'Estratégias para a prova', p:[
  'Para identificar o tipo de ligação, observe os elementos: metal + ametal → iônica; ametal + ametal (ou hidrogênio) → covalente; metal + metal → metálica. Depois, relacione às propriedades: alto PF e conduz fundido ou dissolvido → iônica; baixo PF e não conduz no estado puro → molecular; conduz no estado sólido e é maleável → metálica; muito duro, alto PF e não conduz → covalente em rede (diamante).',
  'Ao escrever fórmulas de compostos iônicos, balanceie as cargas, lembrando que os metais dos grupos 1, 2 e 13 formam cátions de carga +1, +2 e +3, e os ametais dos grupos 15, 16 e 17, ânions de carga −3, −2 e −1. Em fórmulas de compostos moleculares, use o número de ligações típicas de cada elemento: hidrogênio e halogênios (1), oxigênio (2), nitrogênio (3), carbono (4). Esse "mapa de valências" simplifica a escrita de fórmulas e estruturas.',
  'Treine desenhando as **fórmulas eletrônicas (de Lewis)** e **estruturais** de moléculas simples (H₂O, CO₂, NH₃, CH₄, HCl, N₂), e identificando a geometria e a polaridade. Faça também comparações do tipo "qual tem maior ponto de fusão: NaCl ou HCl?" (NaCl, iônico) e "qual conduz eletricidade quando dissolvido?" (os iônicos e os ácidos). Com essas rotinas, as questões de ligações químicas se tornam um bloco seguro de pontos.'] }
]}
];
