/* Química: textos corridos, temas 22 a 25 */
module.exports = [
{ t:'Isomeria', txt:[
 { h:'O que é isomeria e os tipos de isomeria plana', p:[
  'Dois compostos são **isômeros** quando têm a mesma fórmula molecular, ou seja, os mesmos átomos nas mesmas quantidades, mas fórmulas estruturais diferentes e, por isso, propriedades diferentes. O termo vem do grego e significa "mesmas partes". Esse fenômeno explica, em parte, a enorme diversidade da Química Orgânica: com poucos elementos é possível montar moléculas distintas, com propriedades e usos muito diferentes. Um exemplo clássico é o par etanol e éter dimetílico, ambos com fórmula C2H6O, mas um é líquido e o outro é gasoso.',
  'A **isomeria plana** (ou constitucional) é identificada comparando as fórmulas estruturais planas, e se divide em cinco casos. Na **isomeria de cadeia**, os isômeros pertencem à mesma função, mas têm cadeias diferentes, como o butano (linear) e o metilpropano (ramificado). Na **de posição**, mudam a posição de uma insaturação, de um grupo funcional ou de uma ramificação, como o propan-1-ol e o propan-2-ol. Na **de função**, as funções são diferentes, como o álcool e o éter, ou o aldeído e a cetona.',
  'Há ainda a **metameria** (ou isomeria de compensação), em que muda a posição do heteroátomo na cadeia, como em éteres e aminas diferentes que têm o mesmo número de carbonos. E há a **tautomeria**, um caso especial de isomeria de função em equilíbrio dinâmico, como o equilíbrio entre aldeído e enol. Nas provas, a isomeria de cadeia, de posição e de função são as mais frequentes. Para identificar, compare as estruturas e verifique, em ordem, se a função, a cadeia ou a posição mudou.'] },
 { h:'Isomeria geométrica (cis-trans)', p:[
  'A **isomeria espacial** (ou estereoisomeria) ocorre quando os isômeros têm a mesma fórmula estrutural plana, mas diferem na **disposição dos átomos no espaço**. Um de seus tipos é a **isomeria geométrica**, também chamada de cis-trans. Ela ocorre quando há impedimento à rotação livre da cadeia, o que acontece em compostos com **ligação dupla** entre carbonos ou em **cadeias cíclicas**. Sem a possibilidade de girar, os grupos ligados a cada carbono ficam fixos em lados definidos.',
  'Para haver isomeria geométrica em um alceno, cada carbono da dupla deve ter **dois ligantes diferentes** entre si. Se os dois grupos iguais ficam do mesmo lado do plano da dupla, o isômero é chamado de **cis**; se ficam em lados opostos, é o **trans**. No 2-buteno, por exemplo, existem o cis-but-2-eno e o trans-but-2-eno, com pontos de ebulição e outras propriedades físicas diferentes. O propeno e o eteno, por outro lado, não têm isômeros geométricos, pois um dos carbonos da dupla tem dois ligantes iguais.',
  'Um caso de grande importância é o das **gorduras trans**. Nos óleos vegetais, as ligações duplas dos ácidos graxos insaturados têm configuração **cis**, que "dobra" a cadeia e mantém o óleo líquido. No processo de hidrogenação parcial, usado para produzir margarinas e gorduras vegetais sólidas, parte das duplas se converte à configuração **trans**, mais linear e que se empacota melhor, formando sólidos. As gorduras trans estão associadas ao aumento do risco de doenças cardiovasculares, e por isso é obrigatório informar sua quantidade nos rótulos.'] },
 { h:'Isomeria óptica e carbono quiral', p:[
  'A **isomeria óptica** é outro tipo de isomeria espacial, em que os isômeros desviam o plano da **luz polarizada** em sentidos opostos. Ela ocorre em moléculas que possuem **carbono quiral** (ou assimétrico), isto é, um carbono ligado a **quatro grupos diferentes**. Uma molécula com um carbono quiral é como uma mão: tem uma imagem no espelho que não se sobrepõe à original. Os dois isômeros, chamados de **enantiômeros** ou antípodas ópticos, são imagem especular um do outro.',
  'Os enantiômeros têm as mesmas propriedades físicas (pontos de fusão e ebulição, densidade), exceto pelo sentido do desvio da luz polarizada: um é **dextrogiro** (desvia para a direita, indicado por +) e o outro é **levogiro** (desvia para a esquerda, indicado por -). Uma mistura em partes iguais dos dois, chamada de **mistura racêmica**, não desvia a luz, pois os efeitos se anulam. O número de isômeros ópticos ativos de uma molécula com n carbonos quirais diferentes é 2^n, e o de misturas racêmicas é 2^(n-1).',
  'A isomeria óptica é crucial na biologia, porque os seres vivos distinguem os enantiômeros. Quase todos os aminoácidos que formam as proteínas e os açúcares do organismo ocorrem em apenas uma das formas. A mesma molécula, em formas diferentes, pode ter efeitos distintos: o limoneno tem cheiro de laranja em uma forma e de limão na outra. Um caso trágico foi o da talidomida, nos anos 1960, em que uma forma era sedativa e a outra provocava malformações em bebês, o que reforçou a importância de testar cada enantiômero.'] },
 { h:'Isomeria e propriedades: do cotidiano aos medicamentos', p:[
  'Como os isômeros têm estruturas diferentes, eles possuem **propriedades diferentes**, que variam em grau conforme o tipo de isomeria. Isômeros de função, como etanol e éter dimetílico, apresentam grande diferença de ponto de ebulição, pois o primeiro faz ligação de hidrogênio e o segundo não. Isômeros de cadeia, como o pentano e o dimetilpropano, diferem de forma mais sutil: o ramificado tem menor superfície de contato e, portanto, menor ponto de ebulição. Isômeros ópticos diferem principalmente na interação com outras substâncias quirais, como as enzimas.',
  'Essa diferença na interação com moléculas biológicas explica por que a **indústria farmacêutica** investe em sintetizar apenas o enantiômero ativo de muitos medicamentos, evitando efeitos colaterais e reduzindo a dose. Receptores e enzimas do organismo são quirais e reconhecem a molécula pelo ajuste espacial, como uma chave e uma fechadura. Assim, um enantiômero encaixa e o outro não. Esse mesmo princípio explica por que algumas substâncias têm sabores, odores e efeitos diferentes em suas formas isoméricas.',
  'Outros exemplos do cotidiano incluem a glicose e a frutose (ambas C6H12O6, a primeira é um aldeído e a segunda é uma cetona, isômeros de função), o ácido cis-butenodioico (maleico) e o trans (fumárico), com propriedades bem distintas, e a conformação dos ácidos graxos nas gorduras saturadas e insaturadas. Reconhecer a isomeria ajuda a compreender por que moléculas aparentemente "iguais", com a mesma fórmula molecular, comportam-se de maneira tão diferente nos organismos e nos materiais.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a isomeria aparece principalmente por meio de contextos como gorduras trans, medicamentos, aromas, feromônios e carboidratos. As questões pedem que o estudante identifique o tipo de isomeria entre duas estruturas, reconheça um carbono quiral em uma fórmula ou relacione a diferença de propriedades com a diferença de estrutura. A leitura cuidadosa das fórmulas em bastão é essencial, para não confundir um grupo com outro.',
  'Para identificar rapidamente: se a fórmula molecular é a mesma e a função é diferente, é isomeria de função; se a função é a mesma e a cadeia é diferente, é de cadeia; se só muda a posição de um grupo, é de posição. Se a dupla ligação tem ligantes diferentes em cada carbono, há possibilidade de cis-trans. Se existe um carbono ligado a quatro grupos diferentes, ele é quiral e a molécula tem isômeros ópticos. Treine localizar o carbono quiral marcando cada carbono com quatro ligantes e comparando-os.',
  'Para a revisão: isômeros têm a mesma fórmula molecular e estruturas diferentes; a isomeria plana inclui cadeia, posição, função, metameria e tautomeria; a espacial inclui geométrica (cis-trans) e óptica (carbono quiral); a gordura trans vem da hidrogenação parcial e tem efeito negativo sobre a saúde; e os enantiômeros podem ter efeitos biológicos distintos. Esse tema se conecta às reações orgânicas, pois a estrutura determina a reatividade, assunto do tema seguinte.'] }
]},
{ t:'Reações orgânicas', txt:[
 { h:'Reações de substituição', p:[
  'As reações orgânicas são classificadas conforme o que acontece com os átomos da molécula. Na **substituição**, um átomo ou grupo de átomos de uma molécula é trocado por outro. Ela é típica dos **alcanos**, que, por terem apenas ligações simples e serem pouco reativos, reagem em condições mais fortes, como na presença de luz ou calor. Por exemplo, o metano reage com o cloro sob luz ultravioleta, formando clorometano e HCl. A substituição no alcano ocorre preferencialmente no carbono terciário, depois no secundário e por último no primário.',
  'Os **hidrocarbonetos aromáticos**, como o benzeno, também sofrem substituição, e não adição, pois a estabilidade do anel é mantida. As principais substituições aromáticas são a halogenação (introdução de Cl ou Br), a nitração (introdução do grupo NO2, usada para produzir explosivos como o TNT) e a sulfonação (introdução do grupo SO3H, usada para fazer detergentes). A **alquilação** de Friedel-Crafts introduz um radical alquila. Em anéis que já têm um substituinte, este direciona a posição do próximo (orto, meta ou para), conforme seja ativante ou desativante.',
  'Outro tipo de substituição importante é a que ocorre em **haletos orgânicos** e em **álcoois**, em que o halogênio ou a hidroxila é trocado por outro grupo. A reação do haleto com uma base forte pode formar um álcool. A **esterificação**, em que um ácido carboxílico reage com um álcool formando éster e água, é também considerada uma substituição (da hidroxila do ácido pelo grupo alcoxila do álcool), e é uma das reações mais conhecidas da Química Orgânica, usada na produção de aromas artificiais e do biodiesel.'] },
 { h:'Reações de adição', p:[
  'Na **adição**, duas ou mais moléculas se combinam para formar uma só, com o rompimento de uma ligação **pi** (π) de uma insaturação. É típica dos **alcenos** e dos **alcinos**, que têm ligações duplas e triplas e são mais reativos que os alcanos. Os principais tipos são a **hidrogenação** (adição de H2, com catalisador de níquel ou platina, que transforma um alceno em alcano), a **halogenação** (adição de Cl2 ou Br2), a **hidro-halogenação** (adição de HCl, HBr) e a **hidratação** (adição de água, em meio ácido, que forma álcool).',
  'Quando o reagente é assimétrico (HX ou H2O) e o alceno também, aplica-se a **regra de Markovnikov**: o hidrogênio se liga ao carbono mais hidrogenado da dupla, e o outro grupo (X ou OH) se liga ao carbono menos hidrogenado. Assim, a adição de água ao propeno produz majoritariamente o propan-2-ol, e não o propan-1-ol. A adição de bromo ao alceno é usada em laboratório como teste para identificar insaturações, já que a solução de bromo, avermelhada, **descora** ao reagir.',
  'A adição tem aplicações importantes. A **hidrogenação de óleos vegetais** transforma as ligações duplas em simples e dá origem às gorduras sólidas (margarinas), mas também pode formar gorduras trans. A **hidratação do eteno** é uma forma industrial de obter etanol. A **polimerização por adição**, em que moléculas de alcenos se unem em cadeias longas, é a base de plásticos como o polietileno e o PVC. Em todos os casos, o ponto central é a quebra da ligação pi e a formação de novas ligações simples.'] },
 { h:'Reações de eliminação, oxidação e combustão', p:[
  'A **eliminação** é o inverso da adição: uma molécula perde átomos ou grupos, formando uma ligação dupla ou tripla. A **desidratação de álcoois**, por exemplo, ocorre em meio ácido e com aquecimento: em temperaturas mais altas (cerca de 170 °C), o etanol perde água e forma eteno; em temperaturas mais baixas (cerca de 140 °C), duas moléculas de etanol perdem uma molécula de água e formam éter dietílico. Já a eliminação de HX em haletos, com base forte, também forma alcenos.',
  'As **reações de oxidação** envolvem o aumento do número de oxidação do carbono, em geral pela adição de oxigênio. Os **álcoois primários** são oxidados a aldeídos e depois a ácidos carboxílicos; os **álcoois secundários**, a cetonas; e os terciários, em condições brandas, não se oxidam. Os alcenos sofrem oxidação que quebra a ligação dupla. O etanol, no organismo, é oxidado a acetaldeído e depois a ácido acético, e o acúmulo do acetaldeído é um dos fatores da ressaca. Na fermentação do vinho, o álcool oxidado forma vinagre.',
  'A **combustão** é um caso de oxidação total. A combustão completa de compostos orgânicos forma CO2 e H2O, e a incompleta forma CO e fuligem. É a reação que fornece energia em motores e em usinas termelétricas, e a base do uso da gasolina, do etanol e do gás de cozinha. A **saponificação** é a reação de um éster (óleo ou gordura) com uma base forte, como o NaOH, que forma glicerol e sal de ácido graxo, que é o **sabão**. Já a **hidrólise do éster**, em meio ácido, é o inverso da esterificação.'] },
 { h:'Reações importantes no cotidiano e na indústria', p:[
  'Muitas reações orgânicas fazem parte de processos que usamos todo dia. A **fermentação alcoólica** transforma a glicose em etanol e CO2 pela ação de leveduras, produzindo bebidas, etanol combustível e fazendo o pão crescer. A **fermentação lática** converte o açúcar do leite em ácido lático, formando iogurtes e queijos. A **fermentação acética** transforma o etanol em ácido acético, produzindo vinagre. A **fotossíntese** e a **respiração celular** também são conjuntos de reações orgânicas que sustentam a vida e a energia dos seres vivos.',
  'A produção de **biodiesel** ocorre pela **transesterificação**: um óleo vegetal ou gordura animal (triglicerídeo) reage com um álcool (metanol ou etanol), na presença de um catalisador, e forma ésteres de ácidos graxos (o biodiesel) e glicerol, que é um subproduto aproveitado na indústria de cosméticos. A **produção de sabão** (saponificação) e os **processos de refino** do petróleo, como o craqueamento, que quebra cadeias grandes em menores, para aumentar a produção de gasolina, também são exemplos de transformações em larga escala.',
  'Na indústria farmacêutica e de alimentos, as reações orgânicas permitem sintetizar medicamentos, aromas, corantes e conservantes. A produção da aspirina, por exemplo, é feita pela esterificação do ácido salicílico com anidrido acético. A fabricação de plásticos envolve reações de polimerização. Todos esses processos dependem de controlar condições (temperatura, catalisador, concentrações) para obter o produto desejado com bom rendimento e com o menor impacto ambiental possível, o que se liga aos princípios da química verde.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, as reações orgânicas costumam aparecer contextualizadas: produção de biodiesel, fabricação de sabão, fermentação, hidrogenação de óleos, combustão de combustíveis, síntese de aromas e de medicamentos e processos de refino do petróleo. A questão pode fornecer a equação e pedir para classificar a reação, identificar o produto ou comparar impactos ambientais. Reconhecer a reação-chave de cada processo é o principal recurso para resolver.',
  'Associações úteis: substituição é típica de alcanos e aromáticos; adição é típica de alcenos e alcinos; eliminação forma insaturações, como na desidratação de álcoois; oxidação de álcool primário forma aldeído e depois ácido; esterificação forma éster e água; saponificação forma sabão e glicerol; transesterificação forma biodiesel e glicerol; fermentação transforma açúcares em etanol e CO2. Memorizar esses pares "processo e reação" resolve a maior parte das questões do tema.',
  'Para a revisão, associe o tipo de reação ao tipo de ligação: ligações simples (alcanos) sofrem substituição, e ligações pi (alcenos e alcinos) sofrem adição. Lembre que o benzeno é a exceção, que sofre substituição para preservar o anel. Pratique escrever as reações principais e identificar o que é consumido e o que é formado. No próximo tema, os polímeros, aplicaremos essas ideias às reações de adição e de condensação, que formam plásticos, fibras e borrachas.'] }
]},
{ t:'Polímeros', txt:[
 { h:'O que são polímeros e como se formam', p:[
  'Os **polímeros** são macromoléculas, ou seja, moléculas muito grandes, formadas pela repetição de unidades menores chamadas de **monômeros**. O nome vem do grego e significa "muitas partes". Uma cadeia de polímero pode ter milhares de monômeros ligados. O processo de formação é a **polimerização**. Existem polímeros naturais, como a celulose, o amido, as proteínas, a borracha natural e o DNA, e polímeros sintéticos, como o polietileno, o PVC, o náilon e o poliéster, produzidos pela indústria a partir de derivados do petróleo.',
  'Há dois tipos principais de polimerização. Na **polimerização por adição**, os monômeros, que possuem ligações duplas, se unem pela abertura da ligação pi, sem perda de átomos, e a massa do polímero é a soma das massas dos monômeros. O polietileno, formado a partir do eteno, é o exemplo mais simples. Na **polimerização por condensação**, os monômeros se unem com a eliminação de uma molécula pequena, geralmente água, e exigem que cada monômero tenha pelo menos dois grupos funcionais capazes de reagir.',
  'Exemplos de adição são o polietileno (sacolas, garrafas e brinquedos), o polipropileno (embalagens e utensílios), o PVC (policloreto de vinila, usado em tubulações e em revestimentos), o poliestireno (isopor e copos descartáveis) e o teflon. Exemplos de condensação são o náilon (uma poliamida, formada de diamina e ácido dicarboxílico) e o PET (poliéster feito de ácido tereftálico e etilenoglicol). A natureza usa a condensação para formar proteínas, em que os aminoácidos se ligam por ligações peptídicas, e os polissacarídeos.'] },
 { h:'Propriedades e classificação dos polímeros', p:[
  'As propriedades dos polímeros dependem do monômero, do comprimento das cadeias e de como elas estão organizadas. Quanto ao comportamento ao calor, os **termoplásticos** amolecem ao serem aquecidos e endurecem ao esfriar, podendo ser **moldados e reciclados** repetidas vezes, como o polietileno, o PET e o PVC. Os **termofixos** (ou termorrígidos), como a baquelite, endurecem com o calor de modo irreversível, pois formam ligações cruzadas entre as cadeias, e não podem ser refundidos. Os **elastômeros**, como a borracha, são capazes de se deformar e voltar à forma original.',
  'A **vulcanização** é o processo em que se aquece a borracha natural com enxofre, formando pontes de enxofre entre as cadeias, o que torna o material mais resistente, elástico e menos pegajoso. Foi desenvolvida por Charles Goodyear e foi decisiva para a produção de pneus. Já o **náilon** é resistente e usado em tecidos, cordas e peças; o **Kevlar** é usado em coletes à prova de balas; o **teflon** é antiaderente, graças às ligações carbono-flúor muito fortes; e o **PET** é transparente, leve e muito usado em garrafas.',
  'A estrutura das cadeias também influencia as propriedades. Cadeias lineares e organizadas, que se aproximam bem, formam polímeros mais rígidos e densos, como o polietileno de alta densidade. Cadeias ramificadas, que não se empacotam bem, formam materiais mais flexíveis, como o polietileno de baixa densidade, das sacolas e dos filmes. Os polímeros costumam ter baixa condutividade térmica e elétrica, o que os torna ótimos isolantes, mas há polímeros condutores especiais, que renderam um Prêmio Nobel de Química em 2000.'] },
 { h:'Polímeros naturais e biopolímeros', p:[
  'Os polímeros naturais são fundamentais para a vida. As **proteínas** são polímeros de aminoácidos, e desempenham funções estruturais, enzimáticas e de defesa. Os **polissacarídeos**, como o amido (reserva de energia das plantas), a celulose (componente estrutural das paredes celulares, presente na madeira e no algodão) e o glicogênio (reserva dos animais), são polímeros da glicose, diferindo no tipo de ligação e na ramificação. Os **ácidos nucleicos**, DNA e RNA, são polímeros de nucleotídeos que armazenam e transmitem a informação genética.',
  'A **borracha natural**, extraída do látex da seringueira, é um polímero do isopreno, e foi um produto de grande importância econômica para o Brasil, no ciclo da borracha. A **seda** e a **lã** são proteínas, e o **algodão** é celulose. Muitos materiais naturais são aproveitados diretamente pelo ser humano, e a celulose, por exemplo, é a matéria-prima do papel. A diferença básica em relação aos sintéticos é que os polímeros naturais costumam ser **biodegradáveis**, ou seja, decompostos por microrganismos, enquanto os sintéticos, em geral, persistem por muito tempo.',
  'Os **biopolímeros** e os **plásticos biodegradáveis** buscam reduzir o impacto ambiental. O **PLA** (ácido polilático) é produzido a partir de amido de milho ou de cana-de-açúcar, e o **plástico verde**, ou polietileno de origem vegetal, é feito a partir do eteno obtido do etanol da cana. Esse último não é biodegradável, mas é de fonte renovável, e sua produção captura CO2 da atmosfera durante o crescimento da cana. É importante diferenciar "biobased" (de origem renovável) de "biodegradável" (que se decompõe), pois nem todo plástico de origem vegetal se degrada rapidamente.'] },
 { h:'Impactos ambientais, reciclagem e descarte', p:[
  'O grande problema dos plásticos é a sua **persistência no ambiente**. Por serem resistentes e pouco reativos, os polímeros sintéticos levam décadas ou séculos para se degradar. Muitos acabam em lixões e no mar, formando ilhas de lixo e sendo ingeridos por animais marinhos. Ao se fragmentarem, produzem **microplásticos**, que contaminam águas, solos e organismos e entram na cadeia alimentar. A queima de plásticos, por sua vez, pode liberar gases tóxicos, como dioxinas, no caso do PVC, e contribuir para o efeito estufa.',
  'A **reciclagem** é uma das alternativas. Os termoplásticos podem ser fundidos e reaproveitados, e a **reciclagem mecânica** (trituração e refusão) é a mais comum. A **reciclagem química** decompõe o polímero em monômeros ou em outros produtos para serem reaproveitados, e a **reciclagem energética** queima o resíduo para gerar energia. O **símbolo da reciclagem** e o número dentro do triângulo identificam o tipo de resina (1 para PET, 2 para polietileno de alta densidade, 3 para PVC e assim por diante), o que ajuda na coleta seletiva.',
  'A política dos **3 Rs** (reduzir, reutilizar e reciclar) se aplica diretamente: reduzir o consumo de plásticos de uso único, reutilizar embalagens e reciclar o que for possível. Há ainda o conceito de **economia circular**, em que os materiais circulam em ciclos fechados, sem gerar resíduo. Para que a reciclagem seja eficaz, é necessário haver coleta seletiva, separação adequada e mercado para o material reciclado. As legislações, como a Política Nacional de Resíduos Sólidos, buscam responsabilizar fabricantes, comerciantes e consumidores pelo ciclo completo dos produtos.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM cobra polímeros em contextos ambientais e tecnológicos: plásticos descartados, reciclagem, biodegradabilidade, microplásticos, borracha e vulcanização, embalagens, tecidos sintéticos e materiais biodegradáveis. As questões pedem para interpretar a estrutura de um monômero e do polímero, diferenciar adição e condensação, relacionar propriedades às ligações ou avaliar vantagens e desvantagens de diferentes materiais e de processos de reciclagem.',
  'Dicas de resolução: para reconhecer a polimerização por adição, procure uma ligação dupla no monômero; para a condensação, procure dois grupos funcionais reativos por monômero e a liberação de água ou outra molécula pequena. Termoplástico pode ser reciclado por fusão; termofixo, não. Lembre que "biodegradável" depende de microrganismos conseguirem decompor o material, e que "de fonte renovável" se refere à origem. Na hora de comparar materiais, avalie durabilidade, custo, reciclabilidade e impacto ambiental.',
  'Para revisar: polímeros são formados por monômeros; adição abre ligações pi e condensação libera molécula pequena; termoplásticos são recicláveis, termofixos não; a vulcanização une cadeias de borracha com enxofre; proteínas, polissacarídeos e ácidos nucleicos são polímeros naturais; e plásticos persistem no ambiente, formando microplásticos. Esse tema une a Química Orgânica ao último da matéria, a química ambiental, em que a gestão de resíduos e a poluição são discutidas em uma visão mais ampla.'] }
]},
{ t:'Química ambiental', txt:[
 { h:'Poluição do ar, efeito estufa e aquecimento global', p:[
  'A **atmosfera** é formada principalmente por nitrogênio (cerca de 78%) e oxigênio (cerca de 21%), com pequenas quantidades de argônio, CO2 e vapor de água. A **poluição atmosférica** ocorre quando substâncias emitidas pelas atividades humanas alteram essa composição de forma prejudicial. Os principais poluentes são o monóxido de carbono (CO, da combustão incompleta), os óxidos de enxofre (SOx, da queima de carvão e petróleo), os óxidos de nitrogênio (NOx, de motores de combustão), os hidrocarbonetos não queimados e o material particulado.',
  'O **efeito estufa** é um fenômeno natural em que certos gases da atmosfera, como o CO2, o CH4 (metano), o N2O e o vapor de água, retêm parte do calor emitido pela superfície terrestre, mantendo a temperatura média do planeta em cerca de 15 °C, em vez de -18 °C. O problema é o **aumento da concentração** desses gases pelas atividades humanas, principalmente a queima de combustíveis fósseis, o desmatamento e a pecuária, que intensifica o efeito e provoca o **aquecimento global**, com derretimento de geleiras, elevação do nível do mar e eventos climáticos extremos.',
  'A **chuva ácida** resulta da reação dos óxidos de enxofre e de nitrogênio com a água da atmosfera, formando os ácidos sulfúrico e nítrico, e causa a acidificação de lagos e solos, a corrosão de monumentos de mármore e prejuízo às plantas. Já a **inversão térmica** impede a dispersão dos poluentes nas grandes cidades, em dias frios e secos. O **smog fotoquímico** é a névoa formada pela ação da luz solar sobre os óxidos de nitrogênio e os hidrocarbonetos, gerando o ozônio troposférico, que é nocivo à respiração.'] },
 { h:'Camada de ozônio e os CFCs', p:[
  'O **ozônio** (O3) é um gás formado por três átomos de oxigênio. Na **estratosfera**, a cerca de 20 a 30 km de altitude, forma a chamada **camada de ozônio**, que absorve a maior parte da radiação **ultravioleta** (UV) do Sol, protegendo os seres vivos de problemas como o câncer de pele, a catarata e danos ao DNA. Já o ozônio **troposférico**, próximo ao solo, é um poluente nocivo, pois irrita as vias respiratórias. Portanto, o mesmo gás é benéfico ou prejudicial conforme a altitude em que está.',
  'Na década de 1980, descobriu-se um "buraco" na camada de ozônio sobre a Antártida, causado principalmente pelos **CFCs** (clorofluorcarbonos), gases usados em refrigeradores, aerossóis e espumas. Na estratosfera, a radiação UV quebra as moléculas de CFC e libera átomos de cloro, que atuam como catalisadores na decomposição do ozônio, de modo que um único átomo de cloro pode destruir milhares de moléculas de O3. A reação resumida é O3 + Cl → O2 + ClO, seguida da regeneração do cloro.',
  'O **Protocolo de Montreal** (1987) é um exemplo de sucesso de cooperação internacional: os países se comprometeram a eliminar a produção de CFCs, e a camada de ozônio começou a se recuperar. Os CFCs foram substituídos por outros gases, como os HFCs, que não afetam o ozônio, mas são gases de efeito estufa, e por isso também passaram a ser regulados. Esse caso é muito citado no ENEM como exemplo de como o conhecimento científico, aliado a decisões políticas, pode resolver um problema ambiental global.'] },
 { h:'Poluição da água, eutrofização e tratamento', p:[
  'A **poluição da água** pode ter origem doméstica (esgoto), industrial (metais pesados, solventes, óleos), agrícola (fertilizantes e agrotóxicos) e acidental (derramamento de petróleo). O esgoto sem tratamento leva matéria orgânica e microrganismos, causando doenças como a cólera, a hepatite, a leptospirose e as verminoses. A medida da poluição por matéria orgânica é a **DBO** (demanda bioquímica de oxigênio): quanto maior a quantidade de matéria orgânica, mais oxigênio os microrganismos consomem para decompô-la, e menos sobra para os peixes.',
  'A **eutrofização** é o enriquecimento excessivo da água com nutrientes, principalmente compostos de nitrogênio e fósforo, vindos de esgotos e de fertilizantes. Esses nutrientes provocam uma proliferação intensa de algas, que bloqueiam a luz; ao morrerem, são decompostas por bactérias aeróbicas, que consomem o oxigênio dissolvido. O resultado é a morte de peixes e outros organismos e o mau cheiro. Os **metais pesados**, como mercúrio, chumbo e cádmio, são outro problema, pois são tóxicos e se acumulam na cadeia alimentar, num processo chamado de **bioacumulação**.',
  'O **tratamento da água** para consumo envolve etapas: a captação, a **coagulação** (adição de sulfato de alumínio, que forma flocos que agregam as impurezas), a **floculação**, a **decantação**, a **filtração**, a **desinfecção** com cloro e a correção do pH e a fluoretação. O **tratamento de esgoto** inclui o tratamento primário (remoção de sólidos), o secundário (degradação biológica da matéria orgânica por microrganismos) e, às vezes, o terciário (remoção de nutrientes). O saneamento básico é uma questão de saúde pública, e a falta dele está entre as principais causas de doenças.'] },
 { h:'Resíduos sólidos, solo, agrotóxicos e energia', p:[
  'Os **resíduos sólidos** (lixo) são um grande desafio. Os **lixões** a céu aberto contaminam o solo e as águas, pela produção de **chorume**, líquido escuro e tóxico originado da decomposição do lixo. Os **aterros sanitários** são projetados com impermeabilização do solo, drenagem do chorume e captação do biogás (metano), que pode ser usado para gerar energia. A **incineração** reduz o volume, mas exige filtros para evitar a emissão de poluentes. A **compostagem** transforma os resíduos orgânicos em adubo, e a **reciclagem** recupera materiais como vidro, metais, papel e plásticos.',
  'O solo também sofre poluição. O uso excessivo de **fertilizantes** e **agrotóxicos** contamina o solo e as águas subterrâneas, e os agrotóxicos persistentes se acumulam nos organismos, ao longo da cadeia alimentar. A **acidez do solo**, que prejudica algumas culturas, é corrigida pela calagem (adição de calcário). A **erosão** e o desmatamento degradam a terra, e a **salinização**, causada por irrigação inadequada, torna áreas inférteis. O descarte inadequado de pilhas, baterias e lâmpadas contamina o ambiente com metais pesados, e por isso exige coleta específica.',
  'Na área de energia, a **Química Verde** propõe processos que reduzam ou eliminem o uso e a geração de substâncias perigosas, priorizando matérias-primas renováveis, catalisadores e menor consumo de energia. As **fontes renováveis**, como a solar, a eólica, a hidrelétrica e os biocombustíveis (etanol e biodiesel), ajudam a reduzir as emissões de carbono. O **balanço de carbono** do etanol é mais favorável que o da gasolina, pois o CO2 liberado na queima é em grande parte reabsorvido pelo crescimento da cana. Já o **hidrogênio verde** e a energia nuclear aparecem em debates sobre transição energética.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A Química ambiental é um dos temas mais frequentes do ENEM, pois conecta o conteúdo a problemas reais. Aparecem questões sobre aquecimento global, chuva ácida, camada de ozônio, eutrofização, tratamento de água e esgoto, derramamento de petróleo, lixo e reciclagem, agrotóxicos, bioacumulação, biocombustíveis e fontes de energia. O texto-base costuma ser uma reportagem, um gráfico ou um esquema, e a pergunta pede a causa, a consequência ou uma medida de mitigação coerente.',
  'Algumas associações são recorrentes: CO2 e CH4 estão ligados ao efeito estufa; SO2 e NO2, à chuva ácida; CFCs, à destruição da camada de ozônio; excesso de nitrogênio e fósforo, à eutrofização; metais pesados, à bioacumulação; chorume, aos lixões; e CO, à combustão incompleta. Ao avaliar uma proposta de solução, considere os impactos de cada alternativa, o custo, a escala e as consequências indiretas, e evite as respostas absolutas, como as que prometem eliminar totalmente um problema.',
  'Para revisar, monte um quadro com cinco colunas: problema, causa química, consequência, exemplo e solução. Por exemplo, "aquecimento global, aumento de CO2 e CH4 por queima de combustíveis e desmatamento, derretimento de geleiras, e redução de emissões e uso de energias renováveis". Ao final dos 25 temas de Química, é fundamental revisar as conexões entre eles: o pH e as funções inorgânicas explicam a chuva ácida, a termoquímica explica a energia dos combustíveis e a Química Orgânica explica os polímeros e o petróleo.'] }
]}
];
