/* Química: textos corridos, temas 10 a 12 */
module.exports = [
{ t:'Reações químicas', txt:[
 { h:'O que é uma reação química e como reconhecê-la', p:[
  'Uma **reação química** é a transformação de uma ou mais substâncias, chamadas de **reagentes**, em outras substâncias diferentes, chamadas de **produtos**. Durante a reação, as ligações entre os átomos dos reagentes são rompidas e novas ligações se formam, o que dá origem a substâncias com propriedades diferentes. Os átomos, porém, não desaparecem nem surgem do nada: eles apenas se rearranjam. Por isso, a massa total e o número de átomos de cada elemento se conservam.',
  'Algumas evidências ajudam a perceber que uma reação ocorreu: mudança de cor, liberação de gás (efervescência), formação de um sólido que se separa da solução (precipitado), liberação ou absorção de calor e de luz, e mudança de odor. Essas evidências sugerem a reação, mas não a comprovam sozinhas, já que uma mudança de estado, como a ebulição da água, também libera bolhas e é um fenômeno físico. O que caracteriza a reação é a formação de novas substâncias.',
  'As reações são representadas por **equações químicas**, que mostram reagentes à esquerda, produtos à direita e uma seta entre eles. Os números colocados antes das fórmulas, chamados de **coeficientes estequiométricos**, indicam a proporção em que as substâncias participam. Os índices, escritos depois dos símbolos, fazem parte da fórmula e não podem ser alterados. Também se indicam os estados físicos: (s) sólido, (l) líquido, (g) gasoso e (aq) em solução aquosa.'] },
 { h:'Balanceamento e leis das reações', p:[
  'Balancear uma equação é ajustar os coeficientes para que o número de átomos de cada elemento seja igual nos dois lados. Isso é uma consequência da **lei de Lavoisier**, ou lei da conservação das massas: em um sistema fechado, a massa total dos reagentes é igual à massa total dos produtos. Um método prático começa pelos elementos que aparecem em apenas uma substância de cada lado, deixa por último o hidrogênio e o oxigênio, e confere o resultado ao final, contando átomo por átomo.',
  'Por exemplo, na combustão do metano, CH4 + O2 → CO2 + H2O, equilibra-se primeiro o carbono (1 de cada lado), depois o hidrogênio (colocando 2 antes da água) e, por fim, o oxigênio (4 átomos no lado dos produtos, então 2 antes do O2). A equação balanceada fica CH4 + 2 O2 → CO2 + 2 H2O. A conferência é simples: 1 C, 4 H e 4 O em cada lado. Esse mesmo raciocínio vale para qualquer equação, por mais longa que seja.',
  'A **lei de Proust** (das proporções constantes) afirma que uma substância composta sempre apresenta a mesma proporção em massa entre os elementos que a formam, independentemente da origem. A água, por exemplo, tem sempre cerca de 1 parte de hidrogênio para 8 partes de oxigênio, em massa. As duas leis, de Lavoisier e de Proust, são a base dos cálculos de massa e permitem prever quanto de produto se forma a partir de certa quantidade de reagente.'] },
 { h:'Tipos de reação e reatividade', p:[
  'As reações costumam ser classificadas em quatro grandes grupos. **Síntese** (ou adição) é a união de substâncias simples para formar uma mais complexa, como 2 H2 + O2 → 2 H2O. **Decomposição** (ou análise) é o inverso, quando uma substância se divide em outras mais simples, como a decomposição da água oxigenada em água e oxigênio. **Simples troca** (ou deslocamento) ocorre quando uma substância simples desloca um elemento de uma composta, como Zn + CuSO4 → ZnSO4 + Cu. **Dupla troca** ocorre entre dois compostos que trocam seus componentes, como em AgNO3 + NaCl → AgCl + NaNO3.',
  'Nas reações de simples troca, só ocorre o deslocamento se o elemento que entra for **mais reativo** do que o que sai. Entre os metais, a reatividade decresce na ordem aproximada K, Na, Ca, Mg, Al, Zn, Fe, Pb, H, Cu, Ag, Au. Assim, o zinco desloca o cobre de uma solução, mas o cobre não desloca o zinco. Entre os não metais, o flúor e o cloro são os mais reativos. Essa fila é a base para explicar por que o ouro e a prata não enferrujam, enquanto o ferro corrói.',
  'As reações de dupla troca são importantes porque ocorrem de forma efetiva quando há formação de um produto **pouco solúvel** (precipitado), de um gás ou de uma substância pouco ionizada, como a água. A neutralização entre ácido e base é o exemplo mais conhecido. Outras situações do dia a dia incluem a formação de calcário em canos pela reação entre cálcio e carbonato da água dura, e a reação do vinagre com bicarbonato, que libera CO2 e forma efervescência.'] },
 { h:'Reações de combustão, oxirredução e energia', p:[
  'A **combustão** é a reação de uma substância (o combustível) com o oxigênio (o comburente), liberando energia na forma de calor e luz. Na **combustão completa** de compostos de carbono, hidrogênio e oxigênio, os produtos são CO2 e H2O. Na **combustão incompleta**, há pouco oxigênio disponível, e formam-se CO (monóxido de carbono, gás tóxico e inodoro) e fuligem (carbono). Por isso é perigoso usar aquecedores ou fogões em ambientes fechados, e por isso a fumaça preta indica combustão incompleta.',
  'Muitas reações são de **oxirredução**: há transferência de elétrons entre as espécies, de modo que uma perde elétrons (se oxida) e outra ganha elétrons (se reduz). A oxidação do ferro, que forma a ferrugem, a respiração celular e a queima de combustíveis são exemplos. Em todos esses casos, o número de oxidação de pelo menos um elemento muda. Esse tipo de reação será aprofundado no tema de eletroquímica, em que a transferência de elétrons é aproveitada para gerar corrente elétrica.',
  'As reações também podem ser classificadas pela energia: as **exotérmicas** liberam calor ao ambiente (combustões, neutralizações e a maioria das sínteses), enquanto as **endotérmicas** absorvem calor (decomposição térmica do calcário, fotossíntese e dissolução de sais em compressas frias). Controlar a velocidade e a energia de uma reação é essencial na indústria, na culinária e na medicina, e por isso essas ideias se conectam diretamente aos temas de termoquímica e de cinética química.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, as reações químicas aparecem em contextos aplicados: ferrugem, combustão de combustíveis, efervescência, produção de alimentos, tratamento de água, corrosão de monumentos e reciclagem. Em geral, a questão descreve o processo em texto, fornece uma equação ou uma tabela de dados e pergunta qual transformação ocorre, qual é a proporção entre as substâncias ou qual produto é formado. Ler a equação como uma receita, em que os coeficientes indicam as quantidades, é a habilidade central.',
  'Pontos de atenção: verifique sempre se a equação está balanceada antes de usar os coeficientes; lembre que a massa total se conserva, mesmo quando "parece" que a substância desaparece (como na queima de um papel, em que o carbono vai para a atmosfera como CO2); e observe se o sistema é aberto ou fechado, pois em um sistema aberto os gases podem escapar e a massa medida parecer diminuir.',
  'Na hora de revisar, junte os principais temas em uma lista: tipos de reação (síntese, decomposição, simples troca e dupla troca); fila de reatividade dos metais; combustão completa e incompleta; reações exotérmicas e endotérmicas; lei de Lavoisier e lei de Proust. Treine balancear equações simples, pois essa habilidade é a base para todos os cálculos que virão nos próximos temas, como mol, estequiometria e concentração de soluções.'] }
]},
{ t:'Mol e massa molar', txt:[
 { h:'A ideia de mol e a constante de Avogadro', p:[
  'Os átomos e as moléculas são tão pequenos que seria impossível contá-los um a um. Em vez disso, os químicos usam uma unidade de quantidade de matéria, o **mol**, que funciona como uma "dúzia" gigante. Assim como uma dúzia é 12 unidades, um mol é **6,02 × 10^23** unidades (átomos, moléculas, íons, elétrons ou qualquer outra entidade). Esse número é conhecido como **constante de Avogadro**. Um mol de moléculas de água, por exemplo, contém 6,02 × 10^23 moléculas de H2O.',
  'A escolha desse número específico não é aleatória: ele corresponde ao número de átomos de carbono-12 contidos em 12 gramas desse isótopo. Isso permite relacionar uma quantidade microscópica (átomos) com uma quantidade que podemos medir em uma balança (gramas). O mol é, portanto, a ponte entre o mundo dos átomos e o mundo do laboratório, e é por ele que se estabelece a proporção entre as substâncias em uma reação.',
  'Vale ressaltar que o mol é uma unidade de **quantidade**, e não de massa. Um mol de átomos de ferro e um mol de átomos de alumínio contêm o mesmo número de átomos, mas têm massas diferentes. Assim, um mol de ferro tem massa maior do que um mol de alumínio, pois o átomo de ferro é mais pesado. Esse raciocínio é comparável ao de uma dúzia de ovos e uma dúzia de melancias: o mesmo número de unidades, porém massas bem distintas.'] },
 { h:'Massa atômica, massa molecular e massa molar', p:[
  'A **massa atômica** de um elemento, dada na tabela periódica, é expressa em unidades de massa atômica (u) e representa a média ponderada das massas de seus isótopos. Por exemplo, o carbono tem massa atômica aproximadamente 12 u, o hidrogênio 1 u, o oxigênio 16 u e o sódio 23 u. A **massa molecular** de uma substância é a soma das massas atômicas dos átomos que formam sua molécula. A da água, H2O, é 2 × 1 + 16 = 18 u, e a do gás carbônico, CO2, é 12 + 2 × 16 = 44 u.',
  'A **massa molar** é a massa de um mol da substância, expressa em gramas por mol (g/mol). Numericamente, ela é igual à massa atômica ou molecular, mas com outra unidade. Assim, a massa molar do carbono é 12 g/mol, a da água é 18 g/mol e a do CO2 é 44 g/mol. Isso significa que 18 g de água contêm 6,02 × 10^23 moléculas, e que 44 g de gás carbônico contêm a mesma quantidade de moléculas. É essa coincidência numérica que torna o mol tão prático.',
  'Para compostos iônicos, que não formam moléculas, fala-se em **massa da fórmula**, também em g/mol. O NaCl, por exemplo, tem massa molar 23 + 35,5 = 58,5 g/mol. Para calcular a massa molar de substâncias mais complexas, como o ácido sulfúrico (H2SO4), soma-se: 2 × 1 + 32 + 4 × 16 = 98 g/mol. O ENEM geralmente fornece uma tabela com as massas atômicas, portanto não é necessário decorá-las, mas é essencial saber somá-las corretamente.'] },
 { h:'Relações entre massa, mol e número de partículas', p:[
  'As três grandezas principais estão ligadas por proporções simples. Em qualquer substância, 1 mol corresponde à massa molar (em gramas) e a 6,02 × 10^23 partículas. Com isso, resolvem-se os problemas por **regra de três** ou pela fórmula n = m / M, em que n é a quantidade de matéria em mol, m é a massa em gramas e M é a massa molar. Se temos 36 g de água (M = 18 g/mol), a quantidade é n = 36 / 18 = 2 mol, o que equivale a 2 × 6,02 × 10^23 moléculas.',
  'No caso dos gases, existe uma relação adicional. Nas **CNTP** (condições normais de temperatura e pressão, 0 °C e 1 atm), o volume molar de qualquer gás é cerca de **22,4 L/mol**. Nas condições ambientes (25 °C e 1 atm), ele é de cerca de 24,5 L/mol. Isso permite relacionar o volume de um gás com a quantidade de mols e, consequentemente, com a massa e o número de moléculas. Por exemplo, 44,8 L de gás em CNTP correspondem a 2 mol de moléculas.',
  'Também é possível partir do número de átomos para chegar à massa. Para o elemento carbono, 1 mol de átomos tem 12 g; logo, 1 átomo tem massa de 12 / (6,02 × 10^23) gramas, um número extremamente pequeno. Em moléculas, é preciso lembrar a atomicidade: 1 mol de moléculas de H2O contém 2 mol de átomos de hidrogênio e 1 mol de átomos de oxigênio. Esse tipo de contagem aparece com frequência e costuma ser uma pegadinha para quem esquece de multiplicar pelos índices da fórmula.'] },
 { h:'Composição centesimal e fórmulas', p:[
  'A **composição centesimal** (ou percentual em massa) indica a porcentagem, em massa, de cada elemento em um composto. Para calculá-la, divide-se a massa total de cada elemento na fórmula pela massa molar do composto e multiplica-se por 100. Na água, o hidrogênio contribui com 2 g em 18 g, ou seja, cerca de 11,1%, e o oxigênio com 16 g em 18 g, cerca de 88,9%. Esses valores são constantes, o que reflete a lei de Proust, e permitem comparar, por exemplo, o teor de nitrogênio em diferentes fertilizantes.',
  'Com a composição centesimal é possível chegar à **fórmula mínima** (ou empírica), que mostra a menor proporção inteira entre os átomos. O procedimento é: considerar 100 g da amostra, converter a massa de cada elemento em mols (dividindo pela massa atômica), dividir todos os valores pelo menor deles e, se necessário, multiplicar para obter números inteiros. A **fórmula molecular** é um múltiplo inteiro da mínima, determinado quando se conhece a massa molar. A glicose, C6H12O6, tem fórmula mínima CH2O.',
  'Esses cálculos têm aplicações práticas. Na agricultura, compara-se o teor de nitrogênio de ureia (cerca de 47%) e de nitrato de amônio (cerca de 35%) para escolher o fertilizante mais rico. Na nutrição e na medicina, a quantidade de uma substância ativa em um comprimido é expressa em massa, e a dose por quilo de massa corporal envolve conversões semelhantes. Na indústria, a pureza de uma amostra, calculada como porcentagem em massa, é fundamental para determinar rendimentos e custos.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Questões sobre mol raramente cobram apenas a definição. Em geral, elas colocam um contexto, como a quantidade de uma substância em um medicamento, a massa de CO2 emitida por um veículo, o teor de um nutriente ou a dose de um produto, e pedem a conversão entre massa, mol, volume e número de partículas. A leitura atenta da tabela de massas atômicas e da unidade pedida na resposta (gramas, mol ou número de moléculas) evita boa parte dos erros.',
  'Uma estratégia segura é anotar sempre a "ponte" desejada: massa em gramas → mol (dividindo pela massa molar) → número de partículas (multiplicando por 6,02 × 10^23) ou → volume de gás (multiplicando por 22,4 L, nas CNTP). Para evitar contas longas, o ENEM costuma usar números que se simplificam, e arredondar a constante de Avogadro para 6 × 10^23 geralmente basta para identificar a alternativa correta.',
  'Revisão rápida: 1 mol equivale a 6,02 × 10^23 partículas; massa molar em g/mol é numericamente igual à massa molecular em u; n = m / M; em CNTP, 1 mol de gás ocupa 22,4 L; composição centesimal é porcentagem em massa de cada elemento; e a atomicidade importa ao contar átomos em uma molécula. Estes tópicos são pré-requisito direto para a estequiometria e para a concentração de soluções, os dois temas seguintes da matéria.'] }
]},
{ t:'Estequiometria', txt:[
 { h:'O que é estequiometria e como montar um cálculo', p:[
  'A **estequiometria** é o estudo das quantidades de reagentes e de produtos em uma reação química. Ela usa a equação balanceada como uma receita: os coeficientes indicam a proporção em mols entre as substâncias. Na reação N2 + 3 H2 → 2 NH3, por exemplo, 1 mol de nitrogênio reage com 3 mol de hidrogênio e forma 2 mol de amônia. Essa proporção em mols é válida sempre, mas as proporções em massa e em volume dependem da massa molar e do estado físico de cada substância.',
  'Um cálculo estequiométrico segue sempre quatro passos. Primeiro, escreve-se a equação química e **balanceia-se**. Segundo, anotam-se as relações entre as substâncias de interesse, em mols, em massa ou em volume, usando os coeficientes e as massas molares. Terceiro, monta-se uma **regra de três** com o dado do enunciado e a incógnita. Quarto, resolve-se e verifica-se se a resposta tem unidade e valor coerentes. Se o balanceamento estiver errado, todo o cálculo estará errado, por isso o primeiro passo é decisivo.',
  'Exemplo: quantos gramas de água se formam na combustão de 16 g de metano? A equação é CH4 + 2 O2 → CO2 + 2 H2O. A massa molar do CH4 é 16 g/mol e a da água é 18 g/mol. Pela equação, 1 mol de CH4 (16 g) forma 2 mol de H2O (36 g). Portanto, 16 g de metano formam 36 g de água. Esse é o formato típico das questões: dado de uma substância, resposta em outra, com a ponte dos coeficientes entre elas.'] },
 { h:'Reagente limitante e reagente em excesso', p:[
  'Nem sempre os reagentes são colocados exatamente na proporção da equação. Quando um deles está em quantidade menor do que a necessária, ele termina primeiro e "limita" a reação, sendo chamado de **reagente limitante**. O outro, que sobra ao final, é o **reagente em excesso**. A quantidade de produto formada depende somente do reagente limitante. É a mesma lógica de uma receita de sanduíche: se há pão para 10 e recheio para 6, só serão feitos 6 sanduíches.',
  'Para identificar o limitante, compara-se a proporção real com a proporção da equação. Uma forma prática é calcular, para cada reagente, quanta quantidade de produto seria formada se ele fosse consumido totalmente, e escolher a menor. Outra forma é dividir a quantidade em mols de cada reagente pelo seu coeficiente na equação; o menor valor indica o limitante. Depois, calcula-se o excesso por diferença entre o que havia e o que foi consumido.',
  'Esse conceito explica muitas situações cotidianas e industriais. Na combustão, se o oxigênio é o limitante, ocorre combustão incompleta e forma-se CO. Em um fogão de gás, ajustar a entrada de ar mantém o oxigênio em excesso e garante chama azul. Em processos industriais, usa-se de propósito um reagente barato em excesso para consumir totalmente o reagente caro. Por isso, a identificação do limitante tem relevância econômica e ambiental.'] },
 { h:'Rendimento, pureza e reações sucessivas', p:[
  'Na prática, as reações raramente convertem 100% do reagente em produto. O **rendimento** de uma reação é a razão, em porcentagem, entre a quantidade de produto realmente obtida e a quantidade teórica calculada pela estequiometria. Se o cálculo indica 100 g de produto e se obtêm 80 g, o rendimento é de 80%. O rendimento menor que 100% pode se dever a reações incompletas, perdas no processo ou formação de subprodutos. Para o cálculo, basta multiplicar a quantidade teórica pelo rendimento.',
  'A **pureza** é a porcentagem de substância pura em uma amostra impura. Muitas matérias-primas, como o calcário e os minérios, contêm impurezas que não participam da reação. Se uma amostra de 200 g de calcário tem 80% de CaCO3, só 160 g reagem. Assim, antes de usar a estequiometria, deve-se calcular a massa da substância pura. O mesmo vale para soluções, em que apenas o soluto reage, e para gases misturados, como o ar, que tem cerca de 20% de gás oxigênio em volume.',
  'Em processos industriais, é comum que o produto de uma reação seja o reagente da seguinte, formando **reações sucessivas**, como na produção de ácido sulfúrico ou de ferro. Nesses casos, acompanha-se a quantidade de matéria em cada etapa, ou somam-se as equações para obter uma equação global, desde que as substâncias intermediárias se cancelem. É importante, ao calcular o rendimento global, multiplicar os rendimentos de cada etapa, pois uma perda em uma etapa se propaga para as seguintes.'] },
 { h:'Gases, volume e aplicações ambientais', p:[
  'Quando há gases na reação, as relações podem ser feitas por volume. A **lei de Gay-Lussac** afirma que, nas mesmas condições de temperatura e pressão, os volumes dos gases que participam de uma reação guardam entre si uma proporção de números inteiros e pequenos, igual à dos coeficientes. Na síntese da amônia, 1 L de N2 reage com 3 L de H2 e forma 2 L de NH3. Pela **hipótese de Avogadro**, volumes iguais de gases, nas mesmas condições, têm o mesmo número de moléculas.',
  'Para converter o volume em quantidade de matéria, usa-se o volume molar: 22,4 L/mol nas CNTP ou 24,5 L/mol a 25 °C e 1 atm. Se a questão fornece temperatura e pressão diferentes, recorre-se à equação dos gases ideais, PV = nRT. O ENEM costuma evitar esse cálculo complexo e fornece o volume molar ou as condições em que a relação é simples. Nas questões ambientais, é comum calcular a massa de CO2 emitida pela queima de uma quantidade de combustível.',
  'Como exemplo, a combustão completa de 1 mol de octano (C8H18, principal componente da gasolina) produz 8 mol de CO2. Como a massa molar do octano é 114 g/mol e a do CO2 é 44 g/mol, cada 114 g de octano geram 352 g de CO2. Isso mostra por que a massa de CO2 emitida é maior que a massa de combustível queimado, já que o carbono se combina com oxigênio do ar. Esse raciocínio é útil para avaliar emissões, biocombustíveis e créditos de carbono.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'A estequiometria é um dos temas de Química mais cobrados, sempre contextualizada: produção de amônia e de fertilizantes, combustão de combustíveis, fabricação de cimento e de ferro, tratamento de água e emissão de gases do efeito estufa. A questão geralmente fornece uma equação, às vezes já balanceada, os dados de massa de um participante e as massas molares, e pede a quantidade de outro. Ler com calma e identificar o dado e a incógnita é o primeiro passo.',
  'Algumas armadilhas são frequentes: esquecer de balancear; misturar unidades de massa (quilograma e grama) ou de volume (litro e metro cúbico); usar a quantidade de reagente em excesso para calcular o produto; ignorar a pureza ou o rendimento informados; e confundir o coeficiente da equação com o índice da fórmula. Uma boa prática é conferir, ao final, se a massa total dos reagentes consumidos é igual à massa total dos produtos formados.',
  'Para revisar, memorize a sequência: equação balanceada, relação em mols, conversão para a unidade pedida, regra de três e verificação. Treine com poucos exemplos clássicos, como a combustão do metano e do octano, a síntese da amônia e a decomposição do calcário. Dominando isso e o conceito de mol, você estará preparado também para soluções e concentração, em que a estequiometria é aplicada a substâncias dissolvidas em água.'] }
]}
];
