/* Química: textos corridos, temas 19 a 21 */
module.exports = [
{ t:'Radioatividade', txt:[
 { h:'O que é radioatividade e como foi descoberta', p:[
  'A **radioatividade** é a emissão espontânea de partículas ou de ondas eletromagnéticas pelo núcleo de certos átomos instáveis, que assim se transformam em átomos mais estáveis. Ela foi descoberta em 1896 por Henri Becquerel, ao observar que sais de urânio escureciam chapas fotográficas mesmo no escuro. Pouco depois, Marie e Pierre Curie identificaram novos elementos radioativos, o polônio e o rádio, e Marie Curie recebeu dois prêmios Nobel por seu trabalho, um em Física e outro em Química.',
  'Os átomos têm núcleos formados por prótons e nêutrons. Em núcleos grandes, ou com proporção inadequada entre prótons e nêutrons, as forças que mantêm o núcleo coeso não são suficientes para garanti-lo estável, e o átomo emite radiação para atingir uma configuração de menor energia. Esse processo é independente de fatores externos, como temperatura, pressão ou de estar combinado em uma substância. É por isso que a radioatividade é um fenômeno **nuclear**, e não químico: não envolve a eletrosfera.',
  'Em uma transformação nuclear, o elemento muda: o número atômico se altera, e um elemento se transforma em outro. Em reações químicas, ao contrário, os átomos são conservados e apenas rearranjados. Também é por isso que a energia envolvida na radioatividade é milhões de vezes maior do que a de reações químicas comuns. Esse aspecto distingue a energia nuclear, aproveitada em usinas, de outras formas de energia, como a combustão de um combustível.'] },
 { h:'Tipos de radiação: alfa, beta e gama', p:[
  'Existem três tipos principais de emissões. A **radiação alfa (α)** é formada por dois prótons e dois nêutrons, ou seja, um núcleo de hélio, com carga positiva. É lenta e pesada, tem baixo poder de penetração e é barrada por uma folha de papel ou pela camada externa da pele, mas é muito danosa se o emissor for ingerido ou inalado. Quando um núcleo emite uma partícula alfa, seu número atômico diminui em 2 e seu número de massa diminui em 4.',
  'A **radiação beta (β)** é formada por elétrons de alta velocidade, com carga negativa, emitidos pelo núcleo quando um nêutron se transforma em um próton. Seu poder de penetração é médio, e pode ser barrada por uma lâmina de alumínio de poucos milímetros. Na emissão beta, o número atômico **aumenta em 1**, e o número de massa se mantém. A **radiação gama (γ)** é uma onda eletromagnética de altíssima frequência, sem carga e sem massa, e de enorme poder de penetração, que exige barreiras de chumbo ou de concreto espesso.',
  'Para equacionar as transformações, usam-se as **leis da radioatividade**. A primeira lei de Soddy diz que, na emissão alfa, o número de massa A diminui 4 unidades e o número atômico Z diminui 2. A segunda lei, de Soddy, Fajans e Russell, diz que, na emissão beta, A não se altera e Z aumenta 1. Em qualquer equação nuclear, a soma dos números de massa e a soma dos números atômicos devem ser iguais nos dois lados, como em: urânio-238 → tório-234 + alfa.'] },
 { h:'Meia-vida e decaimento radioativo', p:[
  'Os átomos de uma amostra radioativa não se desintegram ao mesmo tempo, e não é possível prever quando um átomo em particular se desintegrará. No entanto, para grandes quantidades, o comportamento é estatisticamente previsível. A **meia-vida** (ou período de semidesintegração) é o tempo necessário para que metade dos átomos radioativos de uma amostra se desintegre. Esse tempo é característico de cada isótopo e não é afetado por temperatura, pressão ou reações químicas.',
  'A cada meia-vida, a quantidade do isótopo cai pela metade: após 1 meia-vida resta 1/2, após 2 resta 1/4, após 3 resta 1/8, e assim por diante. Pode-se usar a fórmula m = m0 / 2^n, em que n é o número de meias-vidas. Se uma amostra de 80 g de um isótopo com meia-vida de 5 anos é guardada por 15 anos, ocorreram 3 meias-vidas, e restam 80 / 8 = 10 g. Em um gráfico, a curva é decrescente e se aproxima de zero, mas, teoricamente, nunca o atinge.',
  'As meias-vidas variam enormemente. O iodo-131, usado em medicina, tem meia-vida de cerca de 8 dias. O césio-137, envolvido no acidente de Goiânia, em 1987, tem cerca de 30 anos. O carbono-14, usado na datação, tem 5.730 anos. O urânio-238 tem 4,5 bilhões de anos. Isótopos com meia-vida curta são muito intensos, mas deixam de ser perigosos mais cedo, enquanto os de meia-vida longa permanecem por muito tempo, o que torna o armazenamento de rejeitos nucleares um desafio de longo prazo.'] },
 { h:'Fissão, fusão, aplicações e riscos', p:[
  'Além do decaimento espontâneo, há reações nucleares provocadas. Na **fissão nuclear**, um núcleo pesado, como o urânio-235, é bombardeado por um nêutron e se divide em núcleos menores, liberando grande energia e novos nêutrons, que atingem outros núcleos e causam uma **reação em cadeia**. Em usinas nucleares, a reação é controlada e a energia aquece a água, gera vapor e movimenta turbinas. Em uma bomba atômica, a reação ocorre sem controle. A fissão não emite CO2, mas gera rejeitos radioativos.',
  'Na **fusão nuclear**, núcleos leves, como os de hidrogênio, se juntam para formar um núcleo maior, como o de hélio, liberando energia ainda maior. É a reação que ocorre no Sol e nas estrelas, e na bomba de hidrogênio. Ela exige temperaturas de milhões de graus, e seu uso controlado para geração de energia ainda está em desenvolvimento. Seus rejeitos seriam bem menos problemáticos do que os da fissão, razão pela qual a fusão é considerada uma fonte promissora de energia limpa.',
  'As aplicações da radioatividade são muitas: na **medicina**, a radioterapia destrói células de tumores, a cintilografia e a tomografia por emissão usam radioisótopos como traçadores, e raios X e gama esterilizam materiais; na **arqueologia**, a datação por carbono-14 estima a idade de fósseis e objetos de origem biológica de até cerca de 50 mil anos; na **agricultura e na indústria**, a irradiação conserva alimentos e detecta falhas em estruturas metálicas. Os **riscos**, por sua vez, vêm da radiação ionizante, que danifica o DNA e pode causar queimaduras, câncer e mutações.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM costuma abordar a radioatividade em contextos como usinas nucleares, acidentes (Chernobyl, Goiânia, Fukushima), tratamento do câncer, datação de fósseis e descarte de lixo radioativo. As questões pedem que o estudante interprete a meia-vida em um gráfico ou em uma tabela, compare os tipos de radiação ou discuta vantagens e desvantagens da energia nuclear em relação a outras matrizes energéticas. Raramente exigem o balanceamento complexo de equações nucleares.',
  'Alguns cuidados ajudam: lembre que a meia-vida não depende da quantidade inicial nem de condições externas; que a radiação alfa tem menor penetração e a gama a maior; que a fissão divide núcleos pesados e a fusão une núcleos leves; e que a radioatividade é um fenômeno nuclear, ao contrário das reações químicas. Em questões de contagem de meias-vidas, divida o tempo total pela meia-vida e use a sequência 1/2, 1/4, 1/8, 1/16.',
  'Revisão rápida: radioatividade é emissão de radiação pelo núcleo; alfa tem dois prótons e dois nêutrons, beta é um elétron e gama é uma onda; cada meia-vida reduz a quantidade à metade; fissão e fusão liberam energia; a datação usa carbono-14; e a destinação do rejeito radioativo exige armazenamento seguro por muito tempo. Conecte o tema com a discussão sobre fontes de energia e o aquecimento global, pois a energia nuclear não emite gases do efeito estufa na operação.'] }
]},
{ t:'Introdução à química orgânica', txt:[
 { h:'O que é Química Orgânica e por que o carbono é especial', p:[
  'A **Química Orgânica** é o ramo que estuda os compostos do carbono. No passado, acreditava-se que essas substâncias só podiam ser produzidas por seres vivos, graças a uma suposta "força vital". Em 1828, Friedrich Wöhler sintetizou a ureia, uma substância presente na urina, a partir de um sal inorgânico, derrubando essa ideia. Hoje, sabe-se que existem milhões de compostos orgânicos, naturais e sintéticos, e que eles formam combustíveis, alimentos, medicamentos, plásticos, tecidos, cosméticos e os próprios seres vivos.',
  'O carbono é o elemento central porque possui propriedades singulares. Ele é **tetravalente**, ou seja, faz quatro ligações, o que permite diferentes combinações. Ele se liga a outros átomos de carbono, formando **cadeias** longas, ramificadas e anéis. Pode formar ligações simples, duplas e triplas. E se liga a diversos elementos, principalmente hidrogênio, oxigênio, nitrogênio, halogênios e enxofre. Essas características explicam a enorme variedade de compostos e a base da vida na Terra.',
  'Alguns compostos de carbono, como o CO, o CO2, os carbonatos, os cianetos e o diamante e a grafite (formas puras do carbono), são considerados inorgânicos por tradição, pois suas propriedades são mais parecidas com as dos compostos minerais. Em geral, os compostos orgânicos têm ligações covalentes, são formados por moléculas, apresentam pontos de fusão e de ebulição relativamente baixos, são combustíveis e, quando apolares, dissolvem-se em solventes apolares e pouco ou nada em água.'] },
 { h:'Classificação do carbono e das cadeias carbônicas', p:[
  'Os átomos de carbono de uma cadeia podem ser classificados pelo número de outros carbonos aos quais estão ligados. O carbono **primário** está ligado a no máximo um outro carbono, o **secundário** a dois, o **terciário** a três e o **quaternário** a quatro. Também se classificam pela ligação: **saturado** quando só faz ligações simples, e **insaturado** quando há ao menos uma ligação dupla ou tripla. Essas classificações ajudam a prever a reatividade e a nomear os compostos.',
  'A **cadeia carbônica** é o conjunto de átomos de carbono ligados entre si, mais os heteroátomos que estejam entre eles. Quanto ao fechamento, pode ser **aberta** ou acíclica (sem anel) e **fechada** ou cíclica (com anel). Quanto à disposição, pode ser **normal** (linear, sem ramificações) ou **ramificada**. Quanto à saturação, é saturada ou insaturada. Quanto à natureza, é **homogênea** (só carbonos) ou **heterogênea** (com um heteroátomo, como O, N ou S, entre carbonos).',
  'Quando a cadeia fechada tem um anel benzênico, com seis carbonos e ligações duplas alternadas, ela é **aromática**; as demais cadeias fechadas são alicíclicas. O benzeno é o composto aromático mais simples. Os compostos aromáticos não são aromáticos por terem cheiro, ainda que muitos o tenham, mas sim pela estrutura do anel. Para classificar uma cadeia, é bom examinar a estrutura passo a passo: aberta ou fechada, ramificada ou não, saturada ou insaturada, homogênea ou heterogênea.'] },
 { h:'Hidrocarbonetos: alcanos, alcenos, alcinos e aromáticos', p:[
  'Os **hidrocarbonetos** são os compostos formados apenas por carbono e hidrogênio. Os **alcanos** possuem só ligações simples (fórmula geral CnH2n+2), e são os menos reativos: metano, etano, propano, butano. Os **alcenos** possuem uma ligação dupla (CnH2n), como o eteno, usado para produzir o polietileno. Os **alcinos** possuem uma ligação tripla (CnH2n-2), como o etino (acetileno), usado em maçaricos de solda. Os **cicloalcanos** são alcanos de cadeia fechada, e os **aromáticos** têm o anel benzênico.',
  'A nomenclatura segue as regras da IUPAC e é formada por três partes: o prefixo, que indica o número de carbonos da cadeia principal (met = 1, et = 2, prop = 3, but = 4, pent = 5, hex = 6, hept = 7, oct = 8, non = 9, dec = 10); o infixo, que indica o tipo de ligação (an = simples, en = dupla, in = tripla); e o sufixo, que indica a função (o, para hidrocarbonetos). Assim, "pent-an-o" é um alcano de cinco carbonos, e "but-2-en-o" é um alceno de quatro carbonos com a dupla no carbono 2.',
  'Nas cadeias ramificadas, escolhe-se a **cadeia principal**, a mais longa que contenha as insaturações, numeram-se os carbonos de modo que as ramificações e as insaturações recebam os menores números, e indicam-se as ramificações (radicais, como metil e etil) antes do nome da cadeia principal. Por exemplo, "2-metilbutano" tem uma cadeia principal de quatro carbonos com um grupo metil no carbono 2. As ramificações são citadas em ordem alfabética, e se repetidas, usam-se os prefixos di, tri e tetra.'] },
 { h:'Petróleo, combustíveis e propriedades físicas', p:[
  'Os hidrocarbonetos são o principal constituinte do **petróleo**, mistura complexa formada ao longo de milhões de anos pela decomposição de matéria orgânica. No refino, a **destilação fracionada** separa o petróleo em frações conforme o ponto de ebulição, já que moléculas com poucos carbonos têm pontos de ebulição baixos, e as maiores, altos. Assim, saem do topo o gás de cozinha (GLP, com propano e butano), a gasolina, o querosene, o diesel, os óleos lubrificantes e, no fundo, o asfalto e o piche.',
  'Como são apolares, os hidrocarbonetos têm apenas forças de dipolo induzido, e seus pontos de fusão e de ebulição **crescem** com o tamanho da cadeia. Também são pouco solúveis em água e menos densos do que ela, o que explica as manchas de petróleo que flutuam nos derramamentos no mar. A ramificação diminui a superfície de contato e reduz os pontos de ebulição em comparação com os isômeros de cadeia normal. Esses conceitos ligam o tema à polaridade e às forças intermoleculares.',
  'A **octanagem** da gasolina mede a resistência à compressão sem detonar. O isoctano, um hidrocarboneto ramificado, recebe o índice 100, e o heptano, linear, o índice 0. Combustíveis de maior octanagem resistem mais antes de queimar espontaneamente no motor. A queima dos hidrocarbonetos libera CO2 e água, e é a principal origem do aumento do efeito estufa. Em combustão incompleta, forma-se CO. Por isso, os biocombustíveis, como o etanol e o biodiesel, são promovidos como alternativas com menor emissão líquida de carbono.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM raramente cobra nomenclatura isolada. Em vez disso, usa a Química Orgânica em contextos como petróleo, refino, combustíveis, derramamentos, biocombustíveis, plásticos, polímeros e fármacos, e exige que o estudante leia uma fórmula estrutural e extraia informações, como o tipo de cadeia, a presença de ligações duplas, o número de carbonos e o caráter polar ou apolar. A leitura de fórmulas em bastão (zigue-zague) é uma habilidade importante.',
  'Para ler a fórmula em bastão, lembre que cada vértice ou extremidade é um átomo de carbono, e que os hidrogênios ligados ao carbono não são desenhados: completam-se até quatro ligações. Os heteroátomos (O, N, Cl) aparecem escritos. Com isso, é possível contar carbonos e hidrogênios e determinar a fórmula molecular. Ao comparar pontos de ebulição ou de fusão de hidrocarbonetos, lembre que a cadeia mais longa e menos ramificada tem pontos mais altos.',
  'Resumo para revisar: o carbono é tetravalente e forma cadeias; classificam-se carbonos em primário, secundário, terciário e quaternário; a cadeia pode ser aberta ou fechada, ramificada ou normal, saturada ou insaturada, homogênea ou heterogênea; os hidrocarbonetos são alcanos, alcenos, alcinos e aromáticos; o petróleo é separado por destilação fracionada. Esses conceitos preparam o terreno para o próximo tema, que apresenta as funções orgânicas e os grupos funcionais.'] }
]},
{ t:'Funções orgânicas', txt:[
 { h:'Grupos funcionais e funções oxigenadas principais', p:[
  'Uma **função orgânica** é um grupo de compostos com propriedades químicas semelhantes, devido à presença de um mesmo **grupo funcional**, ou seja, um átomo ou conjunto de átomos que determina o comportamento da molécula. Conhecer os grupos funcionais permite reconhecer as substâncias e prever suas propriedades, como a polaridade, a acidez e a solubilidade. Além dos hidrocarbonetos, que não têm grupo funcional, as funções mais cobradas são as oxigenadas e as nitrogenadas.',
  'Entre as **oxigenadas**, o **álcool** tem o grupo hidroxila (-OH) ligado a carbono saturado, como o etanol, usado como combustível e em bebidas. O **fenol** tem a hidroxila ligada diretamente ao anel aromático. O **éter** tem um oxigênio entre dois carbonos (R-O-R), como o éter etílico. O **aldeído** tem o grupo carbonila (C=O) na extremidade da cadeia (-CHO), como o formol e o aroma da canela. A **cetona** tem a carbonila no meio da cadeia, como a acetona, solvente de esmaltes.',
  'O **ácido carboxílico** tem o grupo carboxila (-COOH), como o ácido acético do vinagre, o ácido fórmico das formigas e os ácidos graxos das gorduras. O **éster** (R-COO-R) resulta da reação entre ácido e álcool e está em aromas de frutas e em óleos e gorduras (triglicerídeos). Para identificá-las, procure o grupo característico: -OH em carbono saturado é álcool; -COOH é ácido; C=O na ponta é aldeído; C=O no meio é cetona; -COO- é éster; e -O- entre carbonos é éter.'] },
 { h:'Funções nitrogenadas, halogenadas e outras', p:[
  'As **funções nitrogenadas** têm nitrogênio. A **amina** tem o nitrogênio ligado a carbonos (como se fosse uma amônia em que os hidrogênios foram substituídos), e é responsável pelo odor de peixe e por muitos alcaloides. A **amida** tem o grupo -CONH2, presente nas proteínas como a ligação peptídica e no náilon. O **nitrocomposto** tem o grupo -NO2, usado em explosivos como o TNT. Os **nitrilos** têm o grupo -C≡N. Essas funções são comuns em medicamentos, corantes, herbicidas e na própria estrutura das proteínas.',
  'Os **haletos orgânicos** possuem um halogênio (F, Cl, Br, I) ligado a carbono, como o clorofórmio e os CFCs (clorofluorcarbonos), que destroem a camada de ozônio e por isso foram proibidos. Os **compostos sulfurados** possuem enxofre, como os tióis, que dão o cheiro forte do alho, da cebola e do gás de cozinha (ao qual se adiciona um tiol para alertar vazamentos). Os **organometálicos** possuem ligação carbono-metal. Cada grupo funcional tem sua nomenclatura própria, com um sufixo característico.',
  'Muitas substâncias de importância biológica apresentam **mais de um grupo funcional**, o que são chamadas de funções mistas. Os aminoácidos, por exemplo, têm um grupo amina (-NH2) e um grupo carboxila (-COOH). A aspirina tem éster e ácido carboxílico. Os carboidratos têm várias hidroxilas e uma carbonila. Para identificar as funções em uma molécula complexa, localize cada grupo característico e nomeie todos, sem confundir funções diferentes que usam os mesmos átomos, como o éster e o ácido, que têm a carbonila e oxigênio.'] },
 { h:'Propriedades físicas e solubilidade das funções', p:[
  'As propriedades dependem principalmente das **forças intermoleculares**, que por sua vez dependem do grupo funcional. Os **ácidos carboxílicos** e os **álcoois** fazem ligações de hidrogênio, e por isso têm pontos de ebulição elevados. Entre eles, os ácidos têm pontos maiores, pois formam dímeros, ou seja, duplas de moléculas. As **aminas** e as **amidas** também fazem ligações de hidrogênio. Os **aldeídos, cetonas, éteres e ésteres** são polares, mas não fazem ligação de hidrogênio entre si, e têm pontos de ebulição intermediários. Os hidrocarbonetos têm os menores.',
  'Uma sequência típica de pontos de ebulição para compostos de massas molares parecidas é: hidrocarboneto < éter < aldeído e cetona < álcool < ácido carboxílico. Em cada função, quanto maior a cadeia, maior o ponto de ebulição. Esse tipo de comparação é um clássico, e para resolvê-lo, basta identificar o tipo de força de cada composto e a massa molar. Compostos com ligação de hidrogênio têm pontos mais altos do que os que só têm dipolo permanente ou dipolo induzido.',
  'Quanto à **solubilidade em água**, os compostos de cadeia curta com grupos polares, como o metanol, o etanol, a acetona e o ácido acético, são solúveis, pois fazem ligações de hidrogênio com a água. À medida que a cadeia carbônica cresce, o caráter **apolar** aumenta e a solubilidade em água diminui. Álcoois de cadeia longa e ácidos graxos são pouco solúveis. Por isso, o sabão, que tem uma cadeia apolar longa e uma extremidade polar, consegue interagir com a gordura e com a água ao mesmo tempo.'] },
 { h:'Funções no cotidiano: combustíveis, alimentos, fármacos e aromas', p:[
  'O **etanol** é o álcool mais usado, como combustível renovável derivado da cana-de-açúcar, em bebidas e em produtos de limpeza e de higienização (álcool 70%). Os **ésteres** dão aroma e sabor a frutas e são usados em essências, perfumes e na produção do **biodiesel**, obtido pela transesterificação de óleos e gorduras com álcool. Os **ácidos graxos** e os **triglicerídeos** compõem as gorduras e os óleos, e a presença de duplas ligações (insaturações) deixa a gordura líquida a temperatura ambiente, como o azeite, enquanto a gordura saturada tende a ser sólida.',
  'Os **aldeídos** e as **cetonas** são usados como solventes e conservantes, e a acetona remove esmalte por dissolver substâncias apolares. As **aminas** e as **amidas** formam as proteínas e muitos medicamentos. Os **carboidratos** (glicose, frutose, sacarose, amido e celulose) são polialcoóis com grupos carbonila e constituem a principal fonte de energia. Já os **fenóis** são usados em desinfetantes, e alguns, como os antioxidantes das frutas, protegem as células contra radicais livres.',
  'No meio ambiente, as funções também importam: a **gasolina** (hidrocarbonetos), o **etanol** (álcool) e o **biodiesel** (ésteres) são combustíveis que diferem na origem e na emissão. Os **CFCs** (haletos) afetam a camada de ozônio. Os **defensivos agrícolas**, que têm funções nitrogenadas, halogenadas e outras, podem contaminar solos e águas. A capacidade de reconhecer funções e de associar cada uma a propriedades e usos é, portanto, uma competência valiosa para interpretar textos e rótulos em questões de contexto.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM cobra as funções orgânicas, principalmente, por meio da identificação de grupos funcionais em fórmulas estruturais de substâncias do cotidiano, como medicamentos, aromas, hormônios, feromônios, corantes e agrotóxicos. A pergunta costuma ser algo como "quais funções estão presentes nessa molécula?", ou "a presença de determinado grupo explica qual propriedade?". Reconhecer os grupos principais (hidroxila, carbonila, carboxila, éster, amina e amida) resolve a maior parte dos casos.',
  'Outras questões relacionam a função com a solubilidade ou com as forças intermoleculares, como "por que a vitamina C é hidrossolúvel e a vitamina A é lipossolúvel?". A resposta está na quantidade de grupos polares (hidroxilas) em comparação com o tamanho da parte apolar da molécula. Atenção ao caso do éster e do ácido, que se confundem com facilidade, e ao do álcool e do fenol, em que a diferença é a ligação da hidroxila em carbono saturado ou aromático.',
  'Para a revisão, faça uma tabela com o nome da função, o grupo característico e um exemplo cotidiano: álcool (etanol), aldeído (formol), cetona (acetona), ácido carboxílico (vinagre), éster (aroma de frutas), éter (éter etílico), amina (peixe), amida (proteínas) e haleto (CFC). Treine desenhar e identificar cada grupo. O próximo tema, a isomeria, mostrará como compostos com a mesma fórmula molecular podem ter funções e propriedades diferentes, e isso exige um bom domínio das funções.'] }
]}
];
