/* Química: textos corridos, temas 13 a 15 */
module.exports = [
{ t:'Soluções e concentração', txt:[
 { h:'O que é uma solução e como ela se classifica', p:[
  'Uma **solução** é uma mistura homogênea, ou seja, com um único aspecto, formada por um **soluto**, que é a substância dissolvida, e um **solvente**, que é a substância que dissolve e, em geral, está em maior quantidade. O solvente mais comum é a água, e por isso muitas soluções são chamadas de aquosas. No soro fisiológico, por exemplo, o soluto é o sal (NaCl) e o solvente é a água. As soluções podem ser sólidas (como as ligas metálicas), líquidas (como o café) ou gasosas (como o ar atmosférico).',
  'Quanto à quantidade de soluto, a solubilidade em água a uma dada temperatura tem um limite chamado de **coeficiente de solubilidade**, que indica a quantidade máxima de soluto que se dissolve em certa quantidade de solvente. Uma solução **insaturada** tem menos soluto do que o máximo possível, a **saturada** atinge exatamente o limite e a **supersaturada**, que é instável, contém mais do que o limite. Quando há excesso de soluto que não se dissolve, ele se deposita no fundo e é chamado de corpo de fundo.',
  'A solubilidade depende da temperatura. Para a maioria dos sólidos, ela aumenta com o aumento da temperatura, o que explica por que o açúcar se dissolve melhor no chá quente. Para os gases, ocorre o oposto: a solubilidade diminui com o aquecimento, e por isso um refrigerante quente solta mais gás e fica "sem gás" mais rápido. A pressão também influencia a solubilidade dos gases, aumentando-a, o que explica a efervescência ao abrir uma garrafa de refrigerante.'] },
 { h:'Concentração comum, em mol/L e título', p:[
  'A **concentração** expressa a quantidade de soluto presente em certa quantidade de solução. A **concentração comum** (C) é a massa de soluto por volume de solução, normalmente em g/L. Se 20 g de sal são dissolvidos em água até completar 500 mL (0,5 L) de solução, a concentração é de 20 / 0,5 = 40 g/L. É muito importante usar o volume da **solução** e não o do solvente, e converter as unidades, já que mililitros e litros são frequentemente misturados nos enunciados.',
  'A **concentração em quantidade de matéria**, também chamada de **molaridade** (M), é a quantidade de mols de soluto por litro de solução, expressa em mol/L. Ela é calculada por M = n / V, em que n = m / MM. Assim, se dissolvemos 58,5 g de NaCl (1 mol) em água até obter 1 L de solução, a molaridade é 1 mol/L. Existe uma relação direta entre as duas: C = M × MM, isto é, a concentração em g/L é igual à molaridade multiplicada pela massa molar do soluto.',
  'O **título** (ou fração em massa) é a razão entre a massa do soluto e a massa total da solução, e pode ser expresso em porcentagem. Um soro glicosado a 5% tem 5 g de glicose em cada 100 g de solução. Para soluções muito diluídas, como as de poluentes na água, usam-se as unidades **ppm** (partes por milhão) e **ppb** (partes por bilhão). Um ppm equivale a 1 mg por litro de solução aquosa diluída, e é muito usado para indicar limites de contaminantes como mercúrio, chumbo e cloro na água.'] },
 { h:'Diluição, mistura e densidade da solução', p:[
  'Diluir uma solução é adicionar solvente a ela, o que reduz a concentração, mas não altera a quantidade de soluto. Como o número de mols do soluto antes e depois é o mesmo, vale a relação **M1 × V1 = M2 × V2** (e, de forma análoga, C1 × V1 = C2 × V2). Se 100 mL de uma solução 2 mol/L são diluídos até 400 mL, a nova concentração é 2 × 100 / 400 = 0,5 mol/L. A diluição é um procedimento de rotina em laboratórios, na cozinha e em produtos de limpeza concentrados.',
  'Na **mistura de soluções de mesmo soluto**, somam-se as quantidades de soluto e os volumes: M = (M1 × V1 + M2 × V2) / (V1 + V2). Se misturamos 100 mL de uma solução 1 mol/L com 300 mL de outra 2 mol/L, a quantidade total de soluto é 0,1 + 0,6 = 0,7 mol em 0,4 L, ou seja, 1,75 mol/L. Na mistura de soluções de solutos diferentes que **não reagem**, as quantidades de cada soluto se conservam, mas as concentrações diminuem pela diluição causada pelo aumento do volume total.',
  'A **densidade da solução** relaciona a massa total da solução com seu volume, normalmente em g/mL, e é necessária para converter título em concentração. A relação é C = 1000 × d × T, em que d é a densidade em g/mL, T é o título em fração e C é a concentração em g/L. Por exemplo, o ácido sulfúrico comercial, com densidade de cerca de 1,84 g/mL e título de 98%, tem concentração próxima de 1.800 g/L. Esse tipo de dado aparece em rótulos de produtos de limpeza e de laboratório.'] },
 { h:'Soluções em reações e aplicações do cotidiano', p:[
  'Combinando a concentração com a estequiometria, é possível calcular quanto de um reagente em solução é necessário para reagir com outro. A **titulação** é uma técnica em que uma solução de concentração conhecida (o titulante) é adicionada, aos poucos, a um volume conhecido de uma solução de concentração desconhecida, até que a reação se complete, o que é percebido pela mudança de cor de um indicador. Com o volume gasto e a proporção da equação, calcula-se a concentração desconhecida. Ela é usada para medir a acidez do vinagre ou do leite.',
  'Há inúmeras aplicações práticas. O **soro fisiológico** é uma solução de NaCl a 0,9% em massa por volume, isotônica em relação ao sangue, ou seja, com a mesma concentração de partículas dissolvidas. O **soro caseiro** contém sal e açúcar em água e é usado para repor líquidos na desidratação. Os produtos de limpeza, como a água sanitária e os desinfetantes, trazem o teor de princípio ativo no rótulo, e a diluição recomendada precisa ser respeitada para ser eficaz e segura.',
  'No meio ambiente, a concentração define se a água é potável. A legislação estabelece limites máximos de substâncias, como nitratos, metais pesados e cloro residual, expressos em mg/L ou ppm. Em corpos de água, o excesso de nutrientes (fósforo e nitrogênio) leva à eutrofização, e a concentração de oxigênio dissolvido é um indicador da qualidade ambiental. Na saúde, medicamentos líquidos têm concentração em mg/mL, e a dose depende do volume administrado, o que exige atenção às unidades.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em questões de concentração, o ENEM costuma fornecer um texto com dados de um rótulo, de um laudo de água, de uma receita ou de um processo industrial, e pedir a concentração final após diluição ou mistura, a massa de soluto necessária para preparar certo volume ou a comparação entre duas soluções. O principal desafio é a **organização dos dados e das unidades**: converter mL em L, mg em g e porcentagem em fração.',
  'Dicas práticas: escreva sempre qual é a grandeza dada e qual é a pedida; use C = m / V, M = n / V e a relação C = M × MM para transitar entre elas; na diluição, use a conservação da quantidade de soluto (M1 V1 = M2 V2); e lembre que, ao adicionar solvente, o volume aumenta, mas a massa de soluto não muda. Em ppm, pense em "miligramas por litro" para água diluída, e em porcentagem, pense em "gramas em 100 gramas" ou "100 mL".',
  'Para revisar, memorize as definições principais e os dois exemplos clássicos: o soro fisiológico (0,9% de NaCl) e a diluição de um produto concentrado. Pratique a leitura de um rótulo e a conversão de unidades, porque a maior parte dos erros vem daí. Depois, associe o tema ao próximo, as propriedades coligativas, que mostram como a presença de soluto não volátil altera propriedades do solvente, como a temperatura de ebulição e de congelamento.'] }
]},
{ t:'Propriedades coligativas', txt:[
 { h:'O que são propriedades coligativas', p:[
  'Quando um soluto não volátil, como o sal ou o açúcar, é dissolvido em um solvente, algumas propriedades físicas desse solvente mudam. As **propriedades coligativas** são aquelas que dependem apenas da **quantidade de partículas de soluto** dissolvidas, e não da natureza dessas partículas. Em outras palavras, o que importa é quantas partículas há na solução, e não se são de sal, de açúcar ou de outra substância. São quatro: tonoscopia, ebulioscopia, crioscopia e osmose.',
  'A **tonoscopia** é a diminuição da pressão máxima de vapor do solvente quando se adiciona um soluto não volátil. A **ebulioscopia** é o aumento da temperatura de ebulição. A **crioscopia** é a diminuição da temperatura de congelamento. A **osmose** é a passagem do solvente, por uma membrana semipermeável, da solução menos concentrada para a mais concentrada. Todas as quatro têm origem no mesmo fato: as partículas de soluto dificultam a saída das moléculas do solvente, seja para o vapor, seja para o sólido.',
  'É importante comparar soluções com cuidado. Em soluções de substâncias **moleculares** (como o açúcar), cada molécula dissolvida conta como uma partícula. Em soluções de substâncias **iônicas** ou de ácidos e bases que se ionizam, cada fórmula libera vários íons, e o número de partículas é maior. Assim, uma solução 0,1 mol/L de NaCl tem cerca de 0,2 mol/L de partículas (Na+ e Cl-), e uma de CaCl2 com mesma concentração tem cerca de 0,3 mol/L (Ca2+ e dois Cl-). O efeito coligativo é proporcional a esse número.'] },
 { h:'Pressão de vapor, ebulioscopia e crioscopia', p:[
  'A **pressão de vapor** de um líquido é a pressão exercida pelo vapor em equilíbrio com o líquido, e quanto mais volátil o líquido, maior ela é. Um líquido entra em ebulição quando sua pressão de vapor se iguala à pressão externa. Ao adicionar um soluto não volátil, a pressão de vapor do solvente diminui, pois parte da superfície passa a ser ocupada por partículas de soluto. Para atingir a pressão externa, a solução precisa ser aquecida mais, e por isso **a temperatura de ebulição aumenta**.',
  'Esse efeito é visto no cozimento: a água com sal ferve em temperatura um pouco acima de 100 °C, e uma panela de pressão eleva ainda mais a temperatura de ebulição por aumentar a pressão externa. A elevação, no caso do sal de cozinha, é pequena para as quantidades usadas na cozinha, o que contraria a ideia popular de que o sal "faz a água ferver mais rápido". Na verdade, ele a faz ferver em temperatura levemente maior, e o cozimento ocorre um pouco mais quente.',
  'Na **crioscopia**, o soluto atrapalha a formação do sólido, e a solução congela em temperatura mais baixa do que o solvente puro. A água do mar, salgada, congela abaixo de 0 °C. O mesmo princípio é usado ao espalhar sal nas estradas em países frios para evitar o gelo, e ao adicionar **etilenoglicol** (aditivo) à água do radiador dos carros, que impede o congelamento no inverno e eleva a temperatura de ebulição no verão, protegendo o motor. A mistura de gelo e sal também é usada para resfriar bebidas rapidamente.'] },
 { h:'Osmose e pressão osmótica', p:[
  'A **osmose** é a difusão do solvente (em geral a água) por uma **membrana semipermeável**, que deixa passar o solvente, mas não o soluto, do meio menos concentrado (hipotônico) para o mais concentrado (hipertônico). O fluxo continua até que se atinja um equilíbrio ou até que uma pressão contrária o impeça. A pressão que seria necessária para impedir a passagem do solvente é a **pressão osmótica**, que é maior quanto maior for a concentração de partículas na solução.',
  'Esse fenômeno é fundamental para os seres vivos. As células são envoltas por membranas semipermeáveis. Em uma solução **hipertônica**, a célula perde água e murcha; em uma solução **hipotônica**, ela absorve água e pode inchar ou até estourar; em uma solução **isotônica**, mantém seu volume. Por isso o soro fisiológico, de concentração semelhante à do sangue, é usado em injeções e em lavagens nasais, e não se deve beber água do mar, que desidrata o corpo, pois puxa água das células.',
  'A osmose explica a conservação de alimentos com sal ou açúcar (carne seca, bacalhau, doces em calda, geleias), em que a alta concentração de soluto desidrata e mata os microrganismos. Também explica por que uma verdura temperada com sal murcha, por que as plantas absorvem água pelas raízes e por que o uso excessivo de adubo pode "queimar" as raízes. Já a **osmose reversa**, que aplica uma pressão maior do que a osmótica sobre a solução concentrada, faz a água passar no sentido inverso e é usada na dessalinização da água do mar.'] },
 { h:'Comparação entre soluções e cálculos simples', p:[
  'Uma habilidade comum nas provas é **ordenar soluções** por sua temperatura de ebulição, de congelamento ou pressão de vapor, usando apenas o número de partículas. Basta calcular, para cada solução, a concentração total de partículas dissolvidas. A solução com mais partículas tem **maior** temperatura de ebulição, **menor** temperatura de congelamento, **menor** pressão de vapor e **maior** pressão osmótica. É preciso considerar o grau de ionização no caso de compostos iônicos e de ácidos.',
  'Por exemplo, considere quatro soluções de mesma concentração, 0,1 mol/L: glicose, NaCl, CaCl2 e sacarose. A glicose e a sacarose não se ionizam, ficando com 0,1 mol/L de partículas cada. O NaCl libera dois íons por fórmula, totalizando 0,2 mol/L. O CaCl2 libera três, totalizando 0,3 mol/L. Portanto, a ordem crescente de temperatura de ebulição é glicose = sacarose < NaCl < CaCl2, e a ordem de temperatura de congelamento é a inversa.',
  'As equações quantitativas, como ΔTe = Ke × W × i e ΔTc = Kc × W × i, raramente são exigidas de forma completa no ENEM, que costuma privilegiar a análise qualitativa. Ainda assim, é bom saber que o efeito é proporcional à molalidade (W) e ao fator de van\'t Hoff (i), que corresponde ao número de partículas por fórmula. Quando a questão fornece dados numéricos, eles normalmente permitem uma proporção direta, como "dobrando a concentração, dobra-se a variação da temperatura".'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM costuma trazer propriedades coligativas em contextos cotidianos: sal em estradas geladas, aditivo no radiador, conservação de carnes, soro fisiológico, desidratação, dessalinização, água do mar e cozimento de alimentos. A habilidade exigida é reconhecer que o fenômeno se deve à presença de soluto não volátil e escolher a alternativa que explica corretamente o efeito observado em termos de partículas e de variações das temperaturas.',
  'Cuidados importantes: o efeito coligativo depende da quantidade de partículas, e não do tipo de soluto; só vale para solutos não voláteis; para compostos iônicos, conte os íons formados; a presença de soluto **eleva** a temperatura de ebulição e **abaixa** a de congelamento, nunca o contrário; e a osmose ocorre sempre do meio menos concentrado para o mais concentrado. Muitos erros vêm de trocar os sentidos desses efeitos.',
  'Revisando em poucas linhas: as quatro propriedades (tonoscopia, ebulioscopia, crioscopia e osmose) dependem do número de partículas; mais partículas significam menor pressão de vapor, maior temperatura de ebulição, menor temperatura de congelamento e maior pressão osmótica; compostos iônicos produzem mais partículas; e a osmose reversa serve para dessalinizar. Este tema se conecta ao de concentração de soluções e ao de polaridade, já que a dissolução de solutos depende das interações entre as moléculas.'] }
]},
{ t:'Termoquímica', txt:[
 { h:'Energia nas reações: calor, entalpia e processos exotérmicos e endotérmicos', p:[
  'Toda reação química envolve troca de energia com o meio. A **termoquímica** estuda o calor liberado ou absorvido nas transformações. Quando as ligações dos reagentes se rompem, é preciso fornecer energia; quando novas ligações se formam, energia é liberada. O resultado final depende do balanço entre as duas etapas. A grandeza usada para expressar esse balanço, em pressão constante, é a **variação de entalpia** (ΔH), medida em kJ/mol ou kcal/mol, e que corresponde ao calor trocado.',
  'Em uma reação **exotérmica**, a energia contida nos produtos é menor do que a dos reagentes, e a diferença é liberada na forma de calor para o meio, que se aquece. Por convenção, o ΔH é **negativo** (ΔH < 0). A combustão, a neutralização e a respiração são exemplos. Em uma reação **endotérmica**, os produtos têm mais energia do que os reagentes, o calor é absorvido do meio, que esfria, e o ΔH é **positivo** (ΔH > 0). A fotossíntese e a decomposição do calcário são exemplos.',
  'Os mesmos termos valem para as mudanças de estado físico. A fusão, a vaporização e a sublimação são endotérmicas, e é por isso que o suor, ao evaporar, resfria o corpo, e que o gelo derretendo absorve calor do ambiente. A solidificação, a condensação e a deposição são exotérmicas, e é por isso que o vapor de água causa queimaduras mais graves do que a água quente: além do calor da água, ele libera o calor da condensação sobre a pele.'] },
 { h:'Equações termoquímicas e diagramas de energia', p:[
  'A **equação termoquímica** mostra a reação balanceada, o estado físico de cada substância e o valor de ΔH. Por exemplo, H2(g) + 1/2 O2(g) → H2O(l), ΔH = -286 kJ/mol. O sinal negativo indica que a reação é exotérmica, e o valor se refere às quantidades de mol indicadas na equação. Se multiplicarmos os coeficientes por dois, o ΔH também será multiplicado por dois. Se invertermos o sentido da reação, o ΔH mantém o valor, mas troca de sinal.',
  'O **diagrama de entalpia** representa a energia dos reagentes e dos produtos. Em uma reação exotérmica, os produtos ficam abaixo dos reagentes, e o ΔH é a diferença. Em uma endotérmica, os produtos ficam acima. Quando o diagrama inclui o **estado de transição**, o ponto mais alto da curva, a diferença entre os reagentes e esse ponto é a **energia de ativação**, a energia mínima para que a reação comece. Uma reação exotérmica, como uma fogueira, precisa de uma faísca para começar, mesmo liberando energia depois.',
  'A entalpia de uma substância depende de seu estado físico e de sua forma alotrópica. Por isso, é essencial indicar o estado físico na equação: a combustão do hidrogênio que forma água líquida libera mais energia do que a que forma água gasosa, pois a condensação libera energia adicional. Do mesmo modo, o carbono grafite e o diamante têm entalpias diferentes. Por convenção, a entalpia das substâncias simples no estado mais estável e a 25 °C é considerada zero, o que serve de referência para os cálculos.'] },
 { h:'Calor de combustão, formação e a lei de Hess', p:[
  'Alguns tipos de ΔH recebem nomes específicos. A **entalpia de combustão** é o calor liberado na queima completa de 1 mol de uma substância com oxigênio. Ela é sempre negativa e serve para comparar combustíveis. A **entalpia de formação** é a variação de energia na formação de 1 mol de uma substância a partir de substâncias simples no estado padrão. A de neutralização é a energia liberada na formação de 1 mol de água a partir de um ácido e uma base. Esses valores são tabelados e usados em exercícios.',
  'A **lei de Hess** afirma que a variação de entalpia de uma reação depende apenas dos estados inicial e final, e não do caminho percorrido. Com isso, é possível calcular o ΔH de uma reação somando as equações de outras reações conhecidas, como as peças de um quebra-cabeça. Ao somar, é preciso conferir que as substâncias intermediárias se cancelem, inverter equações (trocando o sinal do ΔH) e multiplicar os coeficientes (multiplicando também o ΔH) conforme necessário.',
  'Outra forma de calcular o ΔH é pela **energia de ligação**, que é a energia necessária para romper 1 mol de ligações no estado gasoso. O ΔH da reação é, aproximadamente, a soma das energias das ligações rompidas nos reagentes (valor positivo, pois absorve energia) mais a soma das energias das ligações formadas nos produtos (valor negativo, pois libera energia). Se as ligações formadas são mais fortes do que as rompidas, o saldo é negativo e a reação é exotérmica. Esse método é útil quando faltam as entalpias de formação.'] },
 { h:'Combustíveis, alimentos e energia no cotidiano', p:[
  'A termoquímica é usada para comparar combustíveis. O **poder calorífico** é a quantidade de energia liberada por massa de combustível queimado, em geral em kJ/g ou kcal/kg. O hidrogênio tem poder calorífico muito alto por massa, mas é difícil de armazenar. O etanol libera menos energia por massa do que a gasolina, o que explica o consumo maior de etanol nos carros. Além da energia, o ENEM costuma avaliar o impacto ambiental, a emissão de CO2 por energia gerada e a origem do combustível (fóssil ou renovável).',
  'Nos alimentos, a energia vem da oxidação dos nutrientes no organismo, que é uma combustão controlada. Os carboidratos e as proteínas fornecem cerca de 4 kcal por grama, e os lipídios, cerca de 9 kcal por grama. Por isso as gorduras são mais calóricas. A caloria registrada nos rótulos é, na prática, a quilocaloria (kcal), igual a 1.000 calorias, e 1 cal equivale a cerca de 4,18 J. Para calcular a energia de uma refeição, basta multiplicar a massa de cada nutriente pelo seu valor energético e somar.',
  'Há ainda aplicações cotidianas: as **bolsas térmicas instantâneas** frias usam a dissolução endotérmica de nitrato de amônio, e as quentes usam a dissolução exotérmica de cloreto de cálcio; a cal virgem reage com a água liberando calor; a produção de cimento absorve energia na decomposição do calcário. Também é central na discussão ambiental: a queima de combustíveis fósseis libera energia e CO2, e por isso a busca por fontes renováveis, como o etanol, o biodiesel e o hidrogênio, depende de balanços energéticos e de emissões.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em termoquímica, o ENEM costuma pedir uma comparação de combustíveis, a interpretação de um diagrama de energia, a identificação de processos exotérmicos e endotérmicos em situações cotidianas ou o cálculo simples de energia por meio de dados fornecidos. É frequente receber uma tabela de entalpias de combustão e calcular a energia liberada por uma massa de combustível, convertendo a massa em mols pela massa molar.',
  'Pontos de atenção: o sinal do ΔH (negativo para exotérmica, positivo para endotérmica); a relação entre a quantidade de matéria e a energia (se a massa dobra, a energia dobra); a necessidade de indicar o estado físico; e a diferença entre energia de ativação, que é a "barreira" para a reação começar, e variação de entalpia, que é o saldo energético entre reagentes e produtos. Muitas pessoas trocam esses conceitos e erram questões de interpretação de gráfico.',
  'Para revisar, memorize: exotérmico libera calor, ΔH < 0, produtos com menos energia; endotérmico absorve calor, ΔH > 0; a lei de Hess permite somar equações; a energia de ligação rompida absorve e a formada libera; e o poder calorífico compara combustíveis. Conecte o tema ao de cinética química, que vem a seguir: a energia de ativação e o uso de catalisadores explicam a velocidade das reações, enquanto a entalpia explica o saldo energético.'] }
]}
];
