/* Química: textos corridos, temas 16 a 18 */
module.exports = [
{ t:'Cinética química', txt:[
 { h:'O que estuda a cinética química e como se mede a velocidade', p:[
  'A **cinética química** estuda a velocidade das reações e os fatores que a influenciam. Algumas reações são muito rápidas, como a explosão de uma bomba, e outras são lentas, como a formação do petróleo. Entender esse ritmo é útil para controlar processos industriais, conservar alimentos, produzir medicamentos e evitar acidentes. A velocidade de uma reação mede a rapidez com que os reagentes são consumidos ou os produtos são formados, e é expressa pela variação da quantidade ou da concentração por unidade de tempo.',
  'Na prática, a **velocidade média** é calculada como a variação da concentração de um reagente ou de um produto dividida pelo intervalo de tempo. Para os reagentes, a concentração diminui, e por isso se usa o módulo da variação, de modo que a velocidade seja sempre positiva. Em uma reação do tipo A → B, por exemplo, se a concentração de A cai de 1,0 mol/L para 0,6 mol/L em 20 segundos, a velocidade média é de 0,4 / 20 = 0,02 mol/(L·s). A unidade pode variar, como g/min ou mL/s, conforme o que se mede.',
  'Quando a equação tem coeficientes diferentes de 1, as velocidades de consumo e de formação das substâncias não são iguais, mas são proporcionais aos coeficientes. Em 2 H2 + O2 → 2 H2O, o hidrogênio é consumido com o dobro da velocidade do oxigênio, e a água é formada com a mesma velocidade com que o hidrogênio é consumido. Dividindo cada velocidade pelo respectivo coeficiente, obtém-se a velocidade da reação, que é única para a transformação toda.'] },
 { h:'Teoria das colisões e energia de ativação', p:[
  'Para que uma reação ocorra, as partículas dos reagentes precisam se encontrar, ou seja, **colidir**. Mas nem toda colisão resulta em reação. De acordo com a **teoria das colisões**, são necessárias duas condições: que a colisão tenha **orientação** adequada, de modo que os átomos certos se aproximem, e que as partículas tenham **energia suficiente** para romper as ligações antigas. Essa energia mínima é chamada de **energia de ativação** (Ea). As colisões que atendem às duas condições são chamadas de colisões efetivas.',
  'Ao colidir com energia suficiente, os reagentes formam, por um instante, uma espécie instável e de alta energia, chamada de **complexo ativado** (ou estado de transição), em que as ligações antigas estão se quebrando e as novas estão se formando. Em seguida, esse complexo se desfaz e origina os produtos. No diagrama de energia, o complexo ativado é o ponto mais alto da curva, e a diferença entre ele e os reagentes corresponde à energia de ativação. Quanto menor a Ea, mais fácil a reação ocorrer, e maior a velocidade.',
  'Isso explica por que algumas reações exotérmicas precisam de um "empurrão" inicial. Um palito de fósforo só acende quando é atritado, que fornece a energia de ativação, e depois a reação continua sozinha, pois o calor liberado fornece energia para as próximas colisões. Já em temperaturas baixas, a maioria das partículas não tem energia suficiente, e a reação é lenta. É uma ideia central: **velocidade depende da frequência de colisões efetivas**, e tudo o que aumenta essa frequência acelera a reação.'] },
 { h:'Fatores que alteram a velocidade', p:[
  'Cinco fatores principais são cobrados. O primeiro é a **temperatura**: ao aumentá-la, as partículas ganham energia cinética, colidem com mais frequência e, principalmente, com mais energia, de modo que mais colisões superam a energia de ativação. Uma regra aproximada diz que um aumento de 10 °C pode dobrar ou triplicar a velocidade. Por isso guardamos alimentos na geladeira, para retardar as reações de decomposição, e cozinhamos em panela de pressão, para acelerá-las.',
  'O segundo é a **concentração dos reagentes**: quanto maior a concentração, mais partículas por volume e maior a frequência de colisões, e a reação é mais rápida. Para gases, aumentar a pressão tem efeito parecido. O terceiro é a **superfície de contato**, nas reações com sólidos: quanto mais dividido o sólido (em pó, em vez de em pedaços), maior a área exposta e mais rápida a reação. É por isso que um comprimido efervescente macerado reage mais depressa e que a poeira de grãos pode explodir.',
  'O quarto fator é a **natureza dos reagentes**: reações entre íons, em solução, costumam ser muito rápidas, enquanto reações que exigem a quebra de muitas ligações covalentes são mais lentas. O quinto é a presença de **catalisador**, substância que acelera a reação sem ser consumida. Há ainda a **luz**, que acelera certas reações, como a decomposição da água oxigenada, que por isso é guardada em frascos escuros, e o escurecimento de filmes fotográficos.'] },
 { h:'Catalisadores, enzimas e a lei da velocidade', p:[
  'O **catalisador** diminui a energia de ativação ao oferecer um caminho alternativo para a reação, sem alterar a variação de entalpia, o sentido ou o rendimento final do equilíbrio. Ele participa da reação, mas é regenerado ao final, e por isso é usado em pequenas quantidades. Os catalisadores automotivos, feitos de platina, paládio e ródio, transformam gases poluentes, como CO e NO, em CO2 e N2. Na indústria, o ferro catalisa a síntese da amônia e o níquel catalisa a hidrogenação de óleos.',
  'No organismo, os catalisadores são as **enzimas**, proteínas que aceleram reações com enorme especificidade. A amilase da saliva quebra o amido, e a pepsina digere proteínas no estômago. As enzimas funcionam em faixas de temperatura e de pH específicas: ao serem aquecidas demais, ou submetidas a um pH muito diferente do ideal, perdem a forma e a função, num processo chamado de desnaturação. Por isso a febre muito alta é perigosa e o cozimento de alimentos desativa as enzimas.',
  'A **lei da velocidade** relaciona a velocidade com as concentrações dos reagentes: v = k [A]^a [B]^b, em que k é a constante de velocidade, que depende da temperatura, e os expoentes a e b são as **ordens** da reação em relação a cada reagente, determinadas experimentalmente. Em reações elementares, ou seja, que ocorrem em uma única etapa, os expoentes coincidem com os coeficientes. Em reações com várias etapas, a velocidade total é determinada pela **etapa lenta**, que funciona como o "gargalo" do processo, como a fila mais lenta do caixa de um supermercado.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, a cinética química aparece em situações práticas: conservação de alimentos, uso de panela de pressão, efervescência de comprimidos, catalisadores de automóveis, enzimas, fermentação, queima de combustíveis e explosões de poeira. A questão pode pedir para interpretar um gráfico de concentração em função do tempo, comparar dois experimentos que diferem em um fator ou explicar por que uma medida de conservação funciona. O ponto central é sempre a frequência e a energia das colisões.',
  'Para analisar um experimento comparativo, compare as condições: qual variou (temperatura, concentração, superfície ou catalisador)? Se uma das condições aumenta a velocidade, a reação termina mais cedo, e a curva de consumo do reagente desce mais rápido. Atenção a dois erros comuns: achar que o catalisador altera o rendimento ou a entalpia da reação (ele só altera a velocidade) e achar que a temperatura só afeta reações endotérmicas (ela acelera as endotérmicas e as exotérmicas).',
  'Resumo para revisar: velocidade é variação de concentração por tempo; reação ocorre por colisões efetivas, com orientação e energia maiores que a de ativação; aumentam a velocidade a temperatura, a concentração, a superfície de contato e os catalisadores; o catalisador reduz a energia de ativação sem ser consumido; e a etapa lenta determina a velocidade global. Esse tema se liga diretamente ao próximo, o equilíbrio químico, em que a velocidade das reações direta e inversa se igualam.'] }
]},
{ t:'Equilíbrio químico', txt:[
 { h:'Reações reversíveis e o estado de equilíbrio', p:[
  'Muitas reações não se completam: os produtos formados podem reagir entre si e regenerar os reagentes. Essas reações são **reversíveis** e são representadas por uma seta dupla (⇌). Em um recipiente fechado, a reação direta (reagentes formando produtos) e a reação inversa (produtos formando reagentes) ocorrem simultaneamente. No início, a velocidade da reação direta é máxima e a da inversa é nula. Com o passar do tempo, a primeira diminui e a segunda aumenta, até que as duas se igualem.',
  'Quando as velocidades se igualam, atinge-se o **equilíbrio químico**. Nesse estado, as concentrações de reagentes e de produtos permanecem **constantes**, embora as reações continuem ocorrendo nos dois sentidos. Por isso, o equilíbrio é chamado de **dinâmico**, e não de parado. É um erro comum pensar que, no equilíbrio, as concentrações são iguais. Elas podem ser bem diferentes, mas ficam estáveis ao longo do tempo, já que a quantidade de produto formada é igual à que se desfaz.',
  'O equilíbrio só é possível em **sistema fechado**, em que nenhuma substância escapa. Em um recipiente aberto, um dos produtos, como um gás, pode sair e a reação segue até o fim. Também é preciso aguardar o tempo suficiente, e uma maneira de reconhecer o equilíbrio em um gráfico de concentração por tempo é observar quando as curvas se tornam horizontais. Exemplos conhecidos são o equilíbrio de dissolução do CO2 em refrigerantes e a síntese da amônia, N2 + 3 H2 ⇌ 2 NH3.'] },
 { h:'Constante de equilíbrio (Kc)', p:[
  'Para uma reação genérica aA + bB ⇌ cC + dD, a **constante de equilíbrio** em termos de concentração é Kc = [C]^c [D]^d / ([A]^a [B]^b), com as concentrações no equilíbrio, em mol/L. Os produtos ficam no numerador e os reagentes no denominador, cada um elevado ao seu coeficiente. O valor de Kc depende apenas da **temperatura**, e não das concentrações iniciais. Substâncias sólidas puras e líquidos puros não entram na expressão, pois suas concentrações são constantes.',
  'O valor de Kc informa o **grau de avanço** da reação. Se Kc é muito maior que 1, no equilíbrio há predominância de produtos, e a reação é "favorecida" no sentido direto. Se Kc é muito menor que 1, predominam os reagentes. Se Kc é próximo de 1, há quantidades significativas de ambos. É importante destacar que o Kc indica a extensão da reação, mas não a velocidade com que o equilíbrio é atingido: uma reação com Kc muito grande pode ser lenta.',
  'O cálculo costuma envolver uma tabela com três linhas: as quantidades iniciais, a variação (proporcional aos coeficientes) e as quantidades no equilíbrio. Em seguida, substituem-se os valores na expressão de Kc. Também existe a constante em termos de pressões parciais (Kp), para equilíbrios gasosos. Se a equação for invertida, o novo valor de K é o inverso do original; se for multiplicada por n, o K é elevado a n. Essas relações permitem combinar equilíbrios.'] },
 { h:'Deslocamento do equilíbrio e o princípio de Le Chatelier', p:[
  'O **princípio de Le Chatelier** afirma que, quando um sistema em equilíbrio sofre uma perturbação externa, ele se desloca no sentido que **minimiza** o efeito dessa perturbação, até atingir um novo equilíbrio. Isso permite prever o comportamento sem cálculo. Quando se **aumenta a concentração** de uma substância, o equilíbrio se desloca no sentido que a consome. Quando se retira uma substância, ele se desloca no sentido que a repõe. O valor de Kc, nesse caso, não muda.',
  'Para a **pressão**, que só afeta equilíbrios com gases e variação do número de mols, o aumento de pressão desloca o equilíbrio para o lado de **menor número de mols** gasosos, e a diminuição o desloca para o lado de maior número. Na síntese da amônia (4 mol de gases à esquerda e 2 mol à direita), alta pressão favorece a formação de NH3. A **temperatura**, ao contrário dos outros fatores, altera o valor de Kc: o aumento da temperatura favorece o sentido endotérmico, e a diminuição favorece o sentido exotérmico.',
  'O **catalisador** não desloca o equilíbrio: ele acelera igualmente as reações direta e inversa e só faz o equilíbrio ser atingido mais rapidamente. Da mesma forma, a adição de um gás inerte a volume constante não altera as concentrações e, portanto, não desloca o equilíbrio. Essas distinções são muito cobradas. Na indústria, as condições são escolhidas para equilibrar rendimento e custo: na síntese da amônia (processo Haber-Bosch), usam-se alta pressão, temperatura moderada e catalisador de ferro.'] },
 { h:'Equilíbrios no cotidiano: pH, água do mar e o organismo', p:[
  'O equilíbrio químico está em muitos fenômenos conhecidos. Em um refrigerante fechado, há o equilíbrio CO2(g) ⇌ CO2(aq), e o ácido carbônico se forma na reação CO2 + H2O ⇌ H2CO3 ⇌ H+ + HCO3-. Ao abrir a garrafa, a pressão diminui, o equilíbrio se desloca para a liberação do gás, e o refrigerante "perde gás". Esse mesmo equilíbrio explica a **acidificação dos oceanos**: com mais CO2 na atmosfera, mais CO2 se dissolve na água, o pH diminui e a formação de conchas e corais, feitos de CaCO3, é prejudicada.',
  'No organismo, o transporte de oxigênio pela hemoglobina depende de um equilíbrio: Hb + O2 ⇌ HbO2. Nos pulmões, onde a concentração de O2 é alta, o equilíbrio se desloca para a formação de oxi-hemoglobina; nos tecidos, onde o O2 é consumido, ele se desloca no sentido de liberar o gás. Em grandes altitudes, como a pressão parcial de O2 é menor, o equilíbrio fica desfavorecido, causando cansaço. O corpo se adapta produzindo mais hemácias. O monóxido de carbono, por se ligar à hemoglobina com muito mais força, desloca o equilíbrio e é tóxico.',
  'Outros exemplos incluem as cavernas e os depósitos de calcário (CaCO3 + CO2 + H2O ⇌ Ca2+ + 2 HCO3-), em que a dissolução e a precipitação formam estalactites e estalagmites; o equilíbrio de solubilidade de sais pouco solúveis; as soluções-tampão; e as reações de esterificação em perfumes e aromas. Em todos eles, o raciocínio é o mesmo: identificar a perturbação e prever o sentido de deslocamento para minimizá-la, segundo o princípio de Le Chatelier.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM prefere cobrar o equilíbrio de modo conceitual e contextualizado: acidificação de oceanos, refrigerantes, hemoglobina, formação de cavernas, descalcificação de dentes (cárie), produção industrial de amônia ou de ácido sulfúrico e fenômenos de solubilidade. A questão apresenta uma situação e pede para identificar para onde o equilíbrio se desloca ou qual medida aumenta o rendimento da reação. Raramente exige o cálculo da constante.',
  'Uma estratégia segura: escreva a equação do equilíbrio, identifique a perturbação (concentração, pressão, temperatura) e aplique Le Chatelier. Lembre-se dos pontos de confusão: o catalisador não desloca o equilíbrio; só a temperatura altera Kc; a pressão só importa se houver gases e variação de mols; e, no equilíbrio, as concentrações são constantes, e não necessariamente iguais. Ao ler gráficos, identifique o momento em que as curvas se estabilizam, que corresponde ao equilíbrio.',
  'Para revisar: equilíbrio é dinâmico, as velocidades direta e inversa são iguais e as concentrações são constantes; Kc = produtos sobre reagentes elevados aos coeficientes; o valor de Kc depende apenas da temperatura; Le Chatelier prevê deslocamentos; o catalisador só acelera. Leve também os exemplos ambientais e fisiológicos, que aparecem com frequência. Esse tema prepara a compreensão de pH, soluções-tampão e solubilidade, assuntos que reaparecem em outras áreas da prova.'] }
]},
{ t:'Eletroquímica', txt:[
 { h:'Oxidação, redução e números de oxidação', p:[
  'A **eletroquímica** estuda a relação entre reações químicas e corrente elétrica. Ela se baseia nas reações de **oxirredução**, em que há transferência de elétrons entre espécies. A espécie que **perde** elétrons sofre **oxidação** e é chamada de agente redutor, pois provoca a redução da outra. A espécie que **ganha** elétrons sofre **redução** e é o agente oxidante. As duas ocorrem sempre juntas: não há oxidação sem redução. Uma frase para memorizar: "OIL RIG", em inglês, que significa oxidation is loss, reduction is gain.',
  'Para acompanhar a transferência de elétrons, usa-se o **número de oxidação** (Nox), uma carga real ou aparente de um átomo em uma substância. Algumas regras ajudam: substâncias simples têm Nox zero; íons simples têm Nox igual à carga; o hidrogênio costuma ter +1 e o oxigênio, -2; a soma dos Nox em uma molécula neutra é zero e em um íon é igual à carga. Quando o Nox de um elemento **aumenta**, ele se oxidou; quando **diminui**, ele se reduziu.',
  'Por exemplo, na reação Zn + Cu2+ → Zn2+ + Cu, o zinco passa de Nox 0 para +2 (oxidação) e o cobre passa de +2 para 0 (redução). O zinco é o agente redutor e o íon Cu2+ é o agente oxidante. Esse tipo de reação é espontâneo, e a energia liberada pode ser aproveitada na forma de corrente elétrica. É o princípio das pilhas, e é a base da corrosão dos metais, da respiração celular, da fotossíntese e da combustão.'] },
 { h:'Pilhas e potenciais de redução', p:[
  'A **pilha** (ou célula galvânica) transforma a energia química de uma reação espontânea de oxirredução em energia elétrica. A pilha de Daniell é o modelo clássico: uma lâmina de zinco em solução de ZnSO4 e uma lâmina de cobre em solução de CuSO4, ligadas por um fio condutor e por uma **ponte salina**, que mantém a neutralidade elétrica das soluções. No **ânodo**, onde ocorre a oxidação, o zinco se desgasta e é o polo **negativo**. No **cátodo**, onde ocorre a redução, o cobre se deposita e é o polo **positivo**.',
  'Os elétrons fluem pelo fio externo do ânodo para o cátodo. Para saber qual metal se oxida e qual se reduz, usa-se o **potencial padrão de redução** (E°), tabelado em volts, que indica a tendência de uma espécie a ganhar elétrons. Quanto maior o E°, maior a tendência de se reduzir. Na pilha, a espécie com maior E° sofre redução (cátodo) e a de menor E° sofre oxidação (ânodo). A diferença de potencial (ddp) da pilha é ΔE° = E°(cátodo) - E°(ânodo), e deve ser positiva para a reação ser espontânea.',
  'Para a pilha de Daniell, E°(Cu2+/Cu) = +0,34 V e E°(Zn2+/Zn) = -0,76 V, de modo que o cobre é o cátodo, o zinco é o ânodo e ΔE° = 0,34 - (-0,76) = +1,10 V. A pilha funciona até que os reagentes se esgotem. A tabela de potenciais também permite prever se uma reação ocorre: um metal de menor E° desloca da solução o íon de um metal de maior E°, e isso se relaciona à fila de reatividade dos metais, em que metais mais reativos se oxidam com mais facilidade.'] },
 { h:'Pilhas comerciais, baterias e corrosão', p:[
  'As pilhas e baterias que usamos têm o mesmo princípio. A **pilha seca** (zinco-carbono), a **alcalina**, a de **lítio** (em celulares e notebooks) e a bateria de **chumbo** dos automóveis são exemplos. As **baterias recarregáveis**, como a de íons de lítio, funcionam como pilhas ao fornecer energia e como células eletrolíticas ao serem recarregadas, quando a corrente de uma fonte externa inverte a reação. As células a combustível produzem eletricidade pela reação entre hidrogênio e oxigênio, formando apenas água.',
  'O descarte de pilhas e baterias é um problema ambiental, pois contêm metais pesados, como chumbo, cádmio, mercúrio e níquel, que contaminam o solo e a água e se acumulam nos seres vivos. Por isso elas devem ser entregues em pontos de coleta específicos, e não jogadas no lixo comum. Já as pilhas de lítio e a reciclagem de metais têm importância crescente, com a expansão dos veículos elétricos e dos dispositivos portáteis. O ENEM costuma explorar o impacto desses resíduos.',
  'A **corrosão** é uma oxidação indesejada dos metais, como a formação de ferrugem no ferro, que exige oxigênio e umidade. O ferro se oxida (Fe → Fe2+ + 2 e-) e o oxigênio se reduz, em um processo que forma uma pilha. Para proteger o metal, usam-se a pintura e o revestimento, que isolam o ferro do ar, a **galvanização** (cobertura com zinco) e a **proteção catódica** por **metal de sacrifício**, em que se liga ao ferro um metal mais reativo, como zinco ou magnésio, que se oxida no lugar dele, como nos cascos dos navios e nas tubulações enterradas.'] },
 { h:'Eletrólise e suas aplicações', p:[
  'A **eletrólise** é o processo inverso da pilha: uma corrente elétrica, fornecida por uma fonte externa, provoca uma reação de oxirredução **não espontânea**. A eletrólise pode ser **ígnea**, quando feita com o composto iônico fundido (sem água), ou **aquosa**, quando feita com a substância dissolvida em água, caso em que a água também pode participar. No eletrodo negativo (cátodo), ocorre redução; no positivo (ânodo), oxidação. Ao contrário da pilha, na eletrólise o polo positivo é o ânodo e o polo negativo é o cátodo.',
  'Na eletrólise aquosa, há competição entre os íons e a água para sofrer oxidação ou redução, e a "facilidade de descarga" determina quem reage primeiro. Na eletrólise da solução aquosa de NaCl, por exemplo, formam-se gás hidrogênio no cátodo, gás cloro no ânodo e uma solução de hidróxido de sódio, no processo industrial conhecido como cloro-álcali. Essa é a principal fonte de cloro e de soda cáustica, matérias-primas de enorme importância industrial.',
  'As aplicações são muitas. A **galvanoplastia** reveste objetos com um metal mais nobre, como na cromação, na niquelação e nas joias banhadas a ouro ou prata. A **eletrólise ígnea da alumina** (Al2O3) produz o alumínio, em um processo que consome muita energia, o que torna a **reciclagem do alumínio** muito vantajosa. O refino eletrolítico purifica o cobre e a produção de sódio, magnésio e cloro também dependem dela. A eletrólise da água separa o hidrogênio, considerado um combustível limpo, e o oxigênio.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Em eletroquímica, o ENEM costuma trazer um contexto, como pilhas e baterias, descarte, corrosão e proteção de metais, reciclagem de alumínio, eletrólise e veículos elétricos, e pedir que o estudante interprete um esquema ou uma tabela de potenciais. Os cálculos de ddp são simples, e o foco está em identificar quem oxida e quem reduz, o sentido do fluxo de elétrons, o polo positivo e negativo e a espontaneidade do processo.',
  'Para evitar confusões, memorize: **a oxidação ocorre no ânodo e a redução no cátodo, nos dois processos**. Na pilha, o ânodo é o polo negativo e o cátodo é o positivo; na eletrólise, é o contrário. Na pilha, a reação é espontânea e gera energia; na eletrólise, é forçada e consome energia. O metal de maior E° se reduz, e o de menor E° se oxida. No caso da corrosão, o metal que se oxida é o que se desgasta, e o de sacrifício é sempre o mais reativo.',
  'Para revisar: oxidação é perda de elétrons e redução é ganho; Nox aumenta na oxidação; pilhas convertem energia química em elétrica; ddp = E° do cátodo menos E° do ânodo; eletrólise usa energia elétrica para forçar reações; proteção catódica usa metal de sacrifício; e pilhas usadas devem ser descartadas em locais apropriados. Relacione o tema com termoquímica, já que as reações espontâneas liberam energia, e com química ambiental, pelo descarte de resíduos.'] }
]}
];
