/* Química: textos corridos, temas 7 a 9 */
module.exports = [
{ t:'Polaridade e forças intermoleculares', txt:[
 { h:'Eletronegatividade e polaridade das ligações', p:[
  'Quando dois átomos se ligam, os elétrons da ligação nem sempre são divididos de maneira igual. A **eletronegatividade** mede a tendência de um átomo de atrair para si o par de elétrons compartilhado. Na tabela periódica, ela aumenta da esquerda para a direita e de baixo para cima, de modo que o flúor é o elemento mais eletronegativo e os metais alcalinos estão entre os menos eletronegativos. Se os dois átomos têm eletronegatividades iguais, como no H2 ou no Cl2, o par fica no meio e a ligação é **apolar**.',
  'Se os átomos têm eletronegatividades diferentes, o par de elétrons fica deslocado em direção ao mais eletronegativo, que adquire uma carga parcial negativa (representada por δ-), enquanto o outro fica com carga parcial positiva (δ+). Essa separação de cargas forma um **dipolo** e a ligação é chamada de **polar**. Em geral, quanto maior a diferença de eletronegatividade, mais polar é a ligação. Na ligação O-H, por exemplo, o oxigênio puxa os elétrons, e o hidrogênio fica parcialmente positivo.',
  'É importante não confundir polaridade da ligação com polaridade da molécula. A ligação é uma propriedade entre dois átomos; a molécula é o conjunto. Uma molécula pode ter ligações polares e, mesmo assim, ser apolar, dependendo da forma como elas se distribuem no espaço. Por isso, para classificar uma molécula, o primeiro passo é identificar se as ligações são polares e o segundo é analisar a geometria, que será o assunto do próximo bloco de estudo.'] },
 { h:'Geometria molecular e polaridade da molécula', p:[
  'A forma de uma molécula depende de como os pares de elétrons ao redor do átomo central se repelem e se afastam o máximo possível. Moléculas com dois átomos são sempre **lineares**. Entre as moléculas com três átomos, o CO2 é linear e a água é **angular**, pois o oxigênio central possui dois pares de elétrons não ligantes que empurram os hidrogênios. Com quatro átomos, a amônia (NH3) tem forma de pirâmide, e com cinco átomos, o metano (CH4) é um **tetraedro**.',
  'Para saber se a molécula é polar, usa-se a ideia de **momento dipolar resultante**: cada ligação polar é como uma seta apontando para o átomo mais eletronegativo, e a molécula é apolar quando a soma dessas setas é zero. No CO2, as duas ligações C=O são polares, mas apontam em sentidos opostos e se anulam, então a molécula é **apolar**. Na água, as setas formam um ângulo e não se anulam, e a molécula é **polar**. O mesmo vale para NH3, que é polar, e para CH4, que é apolar.',
  'Uma regra prática ajuda nas provas: se o átomo central não possui pares de elétrons livres e todos os átomos ligados a ele são iguais, a molécula tende a ser apolar, pois as forças se cancelam. Se há pares livres no átomo central, ou se os átomos ligados são diferentes, a molécula tende a ser polar. Assim, BF3 e CCl4 são apolares, enquanto NH3, H2O e CHCl3 são polares. Hidrocarbonetos, em geral, são apolares porque a diferença de eletronegatividade entre C e H é pequena.'] },
 { h:'Os tipos de forças intermoleculares', p:[
  'As ligações químicas mantêm os átomos unidos dentro da molécula. Já as **forças intermoleculares** atuam entre moléculas diferentes e determinam se uma substância é gasosa, líquida ou sólida em certa temperatura. Elas são bem mais fracas do que as ligações covalentes, mas são decisivas para as propriedades físicas, como os pontos de fusão e de ebulição. Existem três tipos principais, que, em ordem crescente de intensidade, são: dipolo induzido, dipolo permanente e ligação de hidrogênio.',
  'As **forças de dipolo induzido** (ou de London) ocorrem em todas as moléculas, mas são as únicas nas apolares. Elas surgem porque a nuvem eletrônica se deforma por instantes e cria dipolos temporários. Entre moléculas **polares** atuam as forças **dipolo permanente**, em que o polo positivo de uma molécula atrai o negativo de outra. A **ligação de hidrogênio** é o caso mais forte e acontece quando o hidrogênio está ligado a flúor, oxigênio ou nitrogênio (F, O, N) e interage com um par de elétrons de outra molécula, como na água, na amônia e no HF.',
  'A intensidade dessas forças também depende do tamanho da molécula. Em substâncias apolares, quanto maior a massa e a superfície da molécula, mais intensas são as forças de dipolo induzido. Por isso, o metano é gás, o octano é líquido e a parafina, formada por cadeias muito longas, é sólida. Essa relação é importante porque nem sempre a polaridade decide sozinha: uma molécula apolar muito grande pode ter ponto de ebulição maior do que uma molécula polar pequena.'] },
 { h:'Pontos de fusão e de ebulição, solubilidade e o "semelhante dissolve semelhante"', p:[
  'Quanto mais intensas as forças intermoleculares, mais energia é necessária para separar as moléculas e, portanto, **maiores** são os pontos de fusão e de ebulição. É por isso que a água (ligação de hidrogênio) ferve a 100 °C, enquanto o H2S, de massa maior mas sem ligação de hidrogênio, é gás à temperatura ambiente. Em um gráfico dos pontos de ebulição dos hidretos dos grupos 14, 15, 16 e 17, as substâncias NH3, H2O e HF aparecem fora da tendência, justamente por fazerem ligações de hidrogênio.',
  'A solubilidade segue a regra "**semelhante dissolve semelhante**". Substâncias polares tendem a se dissolver em solventes polares, como a água, pois podem formar interações do mesmo tipo. Já as apolares se dissolvem em solventes apolares, como a gasolina e o hexano. Por isso, óleo e água não se misturam: o óleo é apolar e a água é polar. O sal de cozinha (iônico) e o açúcar, que faz ligações de hidrogênio com a água, se dissolvem bem em água, mas não em óleo.',
  'Esse princípio explica situações do dia a dia. O sabão e os detergentes possuem uma parte polar, que interage com a água, e uma cadeia apolar, que interage com a gordura, e por isso "puxam" a sujeira para a água. Também explica por que removedores e solventes orgânicos limpam manchas de tinta a óleo, e por que a vitamina A (lipossolúvel) se acumula no organismo, enquanto a vitamina C (hidrossolúvel) é eliminada pela urina com mais facilidade.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM costuma apresentar situações do cotidiano e pedir que você explique o fenômeno pelas interações entre moléculas. Frases como "a substância X é solúvel em óleo", "o líquido Y evapora mais rápido" ou "o material Z é capaz de reter gordura" exigem identificar a polaridade e o tipo de força intermolecular presente. Ao ler o enunciado, o primeiro passo é desenhar, mentalmente, quais partes das moléculas são polares e quais são apolares.',
  'Outra forma de cobrança é a comparação de pontos de ebulição ou de fusão. A sequência de raciocínio é: (1) as substâncias são iônicas, moleculares ou metálicas? (2) Se forem moleculares, são polares ou apolares? (3) Há ligação de hidrogênio? (4) Qual tem a maior massa molar? Seguindo essa ordem, quase todas as questões podem ser resolvidas. Um erro comum é achar que a ligação de hidrogênio é uma ligação química "de verdade": ela é uma força entre moléculas, bem mais fraca.',
  'Revisando: ligação polar é diferença de eletronegatividade; molécula polar é a soma dos dipolos diferente de zero; CO2 e CH4 são apolares, H2O e NH3 são polares. A ordem de intensidade das forças é dipolo induzido, dipolo permanente e ligação de hidrogênio. Quanto mais forte a força, maior o ponto de ebulição. Polar dissolve polar e apolar dissolve apolar. Guarde também os exemplos do cotidiano, como sabão, óleo e água, pois eles aparecem com frequência nos textos-base.'] }
]},
{ t:'Funções inorgânicas', txt:[
 { h:'O que são funções inorgânicas e por que classificá-las', p:[
  'Uma **função química** é um conjunto de substâncias com propriedades semelhantes, que se comportam de forma parecida nas reações. Classificar os compostos inorgânicos em funções ajuda a prever o que acontece quando eles se encontram. As quatro funções principais são **ácidos, bases, sais e óxidos**. A classificação mais usada para ácidos e bases é a de Arrhenius, que se baseia no comportamento da substância em água, quando ela se dissocia ou se ioniza.',
  'Segundo Arrhenius, **ácido** é toda substância que, em água, libera como único cátion o íon H+ (na prática, o H3O+, chamado de hidrônio). **Base** é toda substância que, em água, libera como único ânion o íon hidróxido, OH-. Os **sais** são compostos iônicos formados por um cátion diferente de H+ e um ânion diferente de OH-, e os **óxidos** são compostos binários em que o oxigênio é o elemento mais eletronegativo, como CO2, CaO e Na2O.',
  'Para reconhecer as funções, usa-se a fórmula. Os ácidos começam com H (HCl, H2SO4, HNO3). As bases terminam em OH (NaOH, Ca(OH)2). Os sais têm cátion e ânion (NaCl, CaCO3). Os óxidos têm apenas dois elementos, sendo o oxigênio um deles. Embora existam exceções, esse método resolve a maior parte dos casos. Vale lembrar que a água, H2O, é um óxido de hidrogênio, e não um ácido, apesar de começar com H.'] },
 { h:'Ácidos: classificação e exemplos do cotidiano', p:[
  'Os ácidos são classificados de várias maneiras. Quanto à presença de oxigênio, são **hidrácidos** (sem oxigênio, como HCl e HF) ou **oxiácidos** (com oxigênio, como H2SO4 e HNO3). Quanto ao número de hidrogênios ionizáveis, são monoácidos, diácidos, triácidos, e assim por diante. Já quanto à força, os ácidos podem ser **fortes** (se ionizam quase totalmente em água, como HCl, HNO3 e H2SO4), moderados ou **fracos** (se ionizam pouco, como H2CO3 e CH3COOH).',
  'Cada ácido tem um nome padronizado: os hidrácidos terminam em "ídrico" (ácido clorídrico, HCl; ácido fluorídrico, HF) e os oxiácidos terminam em "ico" ou "oso", conforme a quantidade de oxigênio. O ácido sulfúrico (H2SO4) é o produto químico mais fabricado no mundo e está nas baterias de automóveis e na produção de fertilizantes. O ácido clorídrico está no suco gástrico e no produto de limpeza conhecido como ácido muriático. O ácido nítrico participa da fabricação de explosivos e adubos.',
  'No cotidiano, o ácido acético (CH3COOH) dá o sabor azedo ao vinagre, o ácido cítrico está no limão e na laranja, o ácido carbônico (H2CO3) está nos refrigerantes e na água com gás, e o ácido lático surge nos músculos durante o esforço intenso. As **chuvas ácidas** se formam quando óxidos de enxofre e de nitrogênio emitidos por indústrias e veículos reagem com a água da atmosfera, produzindo ácidos sulfúrico e nítrico, que corroem monumentos, prejudicam plantas e acidificam rios e lagos.'] },
 { h:'Bases, sais e óxidos', p:[
  'As bases são classificadas pela solubilidade e pela força. As bases dos metais alcalinos (NaOH, KOH) são **fortes e muito solúveis**, e as dos alcalinos terrosos (Ca(OH)2, Mg(OH)2) são pouco solúveis, mas fortes. O hidróxido de amônio (NH4OH), presente nos produtos de limpeza, é fraco. O hidróxido de sódio, chamado de soda cáustica, é usado na fabricação de sabão e papel e no desentupimento de pias. O Mg(OH)2 é o "leite de magnésia", um antiácido que neutraliza o excesso de ácido no estômago.',
  'Os **sais** se formam, em geral, na reação entre um ácido e uma base, chamada de **neutralização**, que produz também água. O cloreto de sódio (NaCl) é o sal de cozinha, o carbonato de cálcio (CaCO3) forma o calcário, o mármore e as cascas de ovo, o bicarbonato de sódio (NaHCO3) é usado em antiácidos e fermentos, e os nitratos e fosfatos são componentes de fertilizantes. A maioria dos sais é sólida, solúvel em água e conduz eletricidade quando dissolvida ou fundida.',
  'Os **óxidos** são classificados conforme o comportamento. Os óxidos **básicos** (CaO, Na2O) reagem com água formando bases e com ácidos formando sais. Os óxidos **ácidos** (CO2, SO2, SO3, NO2) reagem com água formando ácidos e com bases formando sais. Existem ainda óxidos neutros, como CO e N2O, que não reagem com água, e os anfóteros, como o ZnO e o Al2O3. A cal virgem (CaO) é muito usada na construção civil, e o CO2 é o gás liberado na combustão e responsável pelo efeito estufa.'] },
 { h:'Reações entre as funções e aplicações', p:[
  'A reação de **neutralização total** entre um ácido e uma base é a mais importante para o estudo. Ela segue o modelo ácido + base → sal + água. Por exemplo, HCl + NaOH → NaCl + H2O. O ácido fornece o cátion H+ e a base fornece o ânion OH-, que se combinam para formar a água. O sal formado é composto pelo ânion do ácido e pelo cátion da base. Essa reação libera calor e é a base do uso de antiácidos, que neutralizam o excesso de HCl no estômago.',
  'Outras reações aparecem com frequência: **ácido + metal** produz sal e gás hidrogênio (por exemplo, Zn + 2 HCl → ZnCl2 + H2); **ácido + carbonato** produz sal, água e gás carbônico, o que explica a efervescência de um comprimido efervescente na água e a corrosão do mármore pela chuva ácida; **óxido ácido + água** produz ácido; e **óxido básico + água** produz base. Reconhecer o padrão ajuda a prever os produtos sem decorar cada caso.',
  'Essas reações têm aplicações ambientais e industriais. A calagem corrige a acidez do solo agrícola usando calcário ou cal, um processo de neutralização. O tratamento de efluentes ácidos de indústrias usa bases para evitar a poluição de rios. O hidróxido de sódio é usado para neutralizar derramamentos ácidos, e o bicarbonato de sódio neutraliza ácidos em pequenos acidentes domésticos, como a queimadura leve por ácido. Em todos os casos, o princípio é o mesmo: o H+ reage com o OH- ou com o carbonato.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, as funções inorgânicas quase nunca aparecem como uma pergunta de classificação direta. Elas surgem em contextos como chuva ácida, correção do solo, antiácidos, produtos de limpeza, conservação de monumentos e tratamento de água. O enunciado costuma citar substâncias pelo nome comum (vinagre, soda, cal, leite de magnésia, sal de cozinha) e pede que você reconheça a função e preveja o que ocorre, normalmente uma neutralização.',
  'Algumas associações são recorrentes e valem a pena memorizar: vinagre é ácido acético; soda cáustica é NaOH; cal virgem é CaO; cal hidratada é Ca(OH)2; calcário e mármore são CaCO3; sal de cozinha é NaCl; leite de magnésia é Mg(OH)2; bicarbonato é NaHCO3; ácido muriático é HCl. Com essas relações, muitas questões se resolvem apenas ao traduzir o nome popular para a fórmula e aplicar a regra da neutralização.',
  'Dica de revisão: ao ver uma questão sobre acidez de solo, de rio ou de lago, pense na reação de um ácido com uma base ou com um carbonato. Ao ver uma questão sobre chuva ácida, lembre que os óxidos ácidos (SO2, NO2) reagem com a água. E ao ver "gás liberado", lembre que o carbonato com ácido libera CO2. Treine escrever as reações com o balanceamento correto, pois o ENEM pode pedir a proporção entre as substâncias.'] }
]},
{ t:'pH e equilíbrio ácido-base', txt:[
 { h:'Autoionização da água e a escala de pH', p:[
  'Mesmo a água pura conduz uma quantidade mínima de eletricidade, porque uma pequena fração de suas moléculas se ioniza: 2 H2O ⇌ H3O+ + OH-. Em água pura a 25 °C, a concentração de H+ e a de OH- são ambas iguais a 10^-7 mol/L. O produto das duas, chamado de **produto iônico da água** (Kw), vale 10^-14 nessa temperatura. Isso quer dizer que, se a concentração de H+ aumenta em uma solução, a de OH- diminui na mesma proporção, e vice-versa.',
  'Para evitar o uso de números tão pequenos, define-se o **pH** como o logaritmo negativo da concentração de H+: pH = -log [H+]. De forma análoga, pOH = -log [OH-], e a 25 °C vale pH + pOH = 14. Na água pura, [H+] = 10^-7 e, portanto, pH = 7, que é o ponto **neutro**. Soluções com pH menor que 7 são **ácidas** e com pH maior que 7 são **básicas** (ou alcalinas). A escala usual vai de 0 a 14, mas é possível ter valores fora dela.',
  'Como a escala é logarítmica, a variação de uma unidade de pH significa uma variação de **dez vezes** na concentração de H+. Uma solução de pH 3, por exemplo, tem concentração de H+ dez vezes maior do que uma de pH 4 e cem vezes maior do que uma de pH 5. Esse ponto é frequentemente cobrado em questões interpretativas. Cuidado com o erro de achar que uma solução de pH 2 é "duas vezes mais ácida" do que uma de pH 4: na verdade, é cem vezes mais.'] },
 { h:'Cálculos de pH, pOH e concentrações', p:[
  'Os cálculos usam sempre a mesma estrutura. Se [H+] = 10^-x mol/L, então pH = x. Assim, uma solução com [H+] = 10^-3 mol/L tem pH 3, e uma com [OH-] = 10^-4 mol/L tem pOH 4 e, portanto, pH 10. Para valores que não são potências exatas de dez, usa-se o logaritmo. O ENEM costuma fornecer o valor de log 2 ou log 3, ou apresentar as concentrações como potências de dez para facilitar o cálculo.',
  'Para ácidos e bases fortes, que se ionizam totalmente, a concentração de H+ (ou de OH-) é igual à concentração do ácido (ou da base), multiplicada pelo número de H+ (ou OH-) liberados por fórmula. Uma solução de HCl 0,01 mol/L tem [H+] = 10^-2 e pH 2. Uma solução de NaOH 0,001 mol/L tem [OH-] = 10^-3, pOH 3 e pH 11. Para ácidos e bases fracos, a ionização é parcial, e a concentração de H+ é muito menor do que a do ácido.',
  'A diluição é outra situação cobrada. Ao diluir dez vezes uma solução ácida forte, o pH aumenta uma unidade, aproximando-se de 7, mas nunca ultrapassando 7 por diluição, pois o ácido não se transforma em base. Ao diluir uma base, o pH diminui, aproximando-se de 7. Misturando um ácido forte com uma base forte em quantidades iguais de H+ e OH-, ocorre a neutralização total, e o pH final é 7. Se sobra ácido, a solução fica ácida; se sobra base, fica básica.'] },
 { h:'Indicadores, medida do pH e exemplos do cotidiano', p:[
  'Os **indicadores ácido-base** são substâncias que mudam de cor conforme o pH do meio. A fenolftaleína, por exemplo, é incolor em meio ácido e rosa-avermelhada em meio básico. O papel de tornassol fica vermelho em meio ácido e azul em meio básico. O extrato de repolho-roxo e de outras plantas, ricos em antocianinas, é um indicador natural que varia do vermelho (ácido) ao verde ou amarelo (básico). Para medidas precisas, usa-se o **pHmetro**, que mede o pH por um eletrodo.',
  'Alguns valores de pH são úteis como referência. O suco gástrico tem pH em torno de 1,5 a 2; o suco de limão, cerca de 2; o vinagre, 3; o café, 5; a chuva "limpa", cerca de 5,6 por causa do CO2 dissolvido; a água pura, 7; o sangue humano, cerca de 7,4; a água do mar, cerca de 8; o leite de magnésia, 10; e os produtos de limpeza com amônia, cerca de 11 a 12. A soda cáustica está próxima do pH 14. Vale decorar a ordem relativa, mais do que os números exatos.',
  'O pH tem papel central em muitos contextos: o solo agrícola, em que cada cultura se desenvolve melhor em uma faixa de pH; as piscinas, que precisam de pH em torno de 7,2 a 7,8 para que o cloro seja eficiente; os xampus e sabonetes, formulados com pH próximo ao da pele; e os ecossistemas aquáticos, em que a chuva ácida e a acidificação dos oceanos prejudicam organismos com conchas e esqueletos de carbonato de cálcio. A alimentação também envolve pH, pois a acidez ajuda a conservar alimentos.'] },
 { h:'Equilíbrio ácido-base, hidrólise de sais e soluções-tampão', p:[
  'Os ácidos e as bases fracos se ionizam de forma parcial e estabelecem um **equilíbrio químico**. Para um ácido fraco HA, vale HA ⇌ H+ + A-, e a constante desse equilíbrio é chamada de **constante de ionização** (Ka). Quanto maior o Ka, mais forte é o ácido. A adição de um dos produtos desloca o equilíbrio no sentido contrário, conforme o **princípio de Le Chatelier**: adicionar A- (um sal do ácido) reduz a ionização e diminui a concentração de H+.',
  'Os sais podem alterar o pH da solução por **hidrólise**. Sais de ácido forte e base forte (como o NaCl) dão solução neutra. Sais de ácido fraco e base forte (como o acetato de sódio e o Na2CO3) dão solução básica, pois o ânion reage com a água e libera OH-. Sais de ácido forte e base fraca (como o NH4Cl) dão solução ácida. Isso explica por que o bicarbonato e o carbonato têm caráter básico e por que o carbonato de sódio é usado para elevar o pH de piscinas.',
  'As **soluções-tampão** resistem a variações do pH quando pequenas quantidades de ácido ou de base são adicionadas. Elas são formadas por um ácido fraco e seu sal (ou por uma base fraca e seu sal). O tampão mais importante do corpo humano é o do sangue, formado por ácido carbônico e bicarbonato, que mantém o pH em cerca de 7,4. Variações pequenas desse valor podem ser graves, e por isso o organismo regula a respiração e a eliminação de bicarbonato para manter o equilíbrio.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Nas provas, o pH aparece em questões sobre solo, água, alimentos, produtos de limpeza, chuva ácida, piscinas e organismo humano. Em geral, o texto traz uma tabela ou um gráfico com valores de pH e pergunta qual substância é mais ácida, qual solução precisa ser usada para corrigir um pH ou como o pH muda após uma diluição. Saber interpretar a escala logarítmica é o ponto mais importante.',
  'Passo a passo para resolver: identifique se a substância é ácida ou básica; escreva a concentração de H+ como potência de dez; converta em pH e lembre que cada unidade equivale a um fator dez. Se o enunciado fala em neutralizar, pense em adicionar uma substância de caráter oposto, como calcário em solo ácido, e em quantidades equivalentes. Se fala em acidificação, pense no CO2 dissolvido formando ácido carbônico, que libera H+ e reduz o pH.',
  'Resumo para revisar: pH = -log [H+]; pH + pOH = 14 a 25 °C; ácido tem pH menor que 7, neutro é 7, base tem pH maior que 7; a cada unidade de pH, a acidez muda dez vezes; a diluição aproxima o pH de 7, sem ultrapassá-lo; sal de ácido fraco e base forte é básico; sal de ácido forte e base fraca é ácido; tampões mantêm o pH quase constante. Com esses pontos e alguns exemplos do cotidiano memorizados, as questões ficam bem mais previsíveis.'] }
]}
];
