/* Sociologia: textos corridos, temas 7 a 9 */
module.exports = [
{ t:'Cultura e sociedade', txt:[
 { h:'O conceito de cultura nas Ciências Sociais', p:[
  'No senso comum, **cultura** costuma significar erudição, ou seja, ter lido muitos livros, frequentado museus e conhecido artes consideradas "elevadas". Nas Ciências Sociais, o conceito é bem mais amplo: cultura é o conjunto de **modos de vida, conhecimentos, crenças, valores, normas, costumes, linguagens, técnicas e símbolos** produzidos e compartilhados por um grupo humano, e transmitidos de geração em geração por meio da aprendizagem, e não por herança biológica. Nesse sentido, **todos os seres humanos têm cultura**, e não existe pessoa ou povo "sem cultura". A forma de cumprimentar, de comer, de vestir, de se casar, de enterrar os mortos e de falar são expressões culturais.',
  'O conceito foi sistematizado pela **Antropologia**. **Edward Tylor**, no século XIX, definiu cultura como "todo complexo que inclui conhecimentos, crenças, arte, moral, leis, costumes e outras capacidades e hábitos adquiridos pelo homem como membro da sociedade". **Franz Boas** (1858-1942) criticou as teorias evolucionistas, que ordenavam os povos em uma escala de "selvageria", "barbárie" e "civilização", e defendeu o **relativismo cultural** e o **particularismo histórico**: cada cultura deve ser compreendida em seus próprios termos e em sua história. **Clifford Geertz** concebeu a cultura como uma "teia de significados" que os seres humanos tecem e na qual estão amarrados, e que cabe ao pesquisador interpretar.',
  'É importante distinguir **natureza** de **cultura**. Muitos comportamentos que parecem "naturais" são aprendidos e variam entre as sociedades. As necessidades biológicas (comer, dormir, reproduzir-se) são universais, mas as formas de satisfazê-las são culturais: o que se come, como e com quem. Da mesma forma, a ideia de que homens e mulheres têm papéis fixos por natureza é questionada, pois esses papéis variam muito entre as culturas. Essa distinção é essencial para combater o **determinismo biológico** e o **determinismo geográfico**, que explicavam as diferenças entre os povos por características raciais ou climáticas, e foram usados para justificar a dominação e o racismo.'] },
 { h:'Etnocentrismo, relativismo cultural e diversidade', p:[
  'O **etnocentrismo** é a tendência de julgar as outras culturas pelos padrões da própria, considerando-a superior e "normal", e as demais "estranhas", "atrasadas" ou "erradas". Está na origem de muitos preconceitos, da xenofobia, da intolerância religiosa e de justificativas para a colonização e a violência, como o colonialismo europeu, que se apresentava como "missão civilizadora". Pode ocorrer em qualquer sociedade, inclusive dentro de um mesmo país, quando um grupo (classe, região ou etnia) desvaloriza os costumes de outro. Levado ao extremo, produz o **genocídio** e a perseguição de minorias.',
  'O **relativismo cultural** é a posição oposta: propõe compreender cada prática dentro de seu **contexto cultural**, sem julgá-la por critérios externos. Não significa aprovar tudo, nem abandonar a crítica, mas reconhecer que as culturas têm lógicas próprias, e que cabe ao pesquisador adotar o **estranhamento** (olhar o familiar como estranho) e a **empatia** (compreender o outro de dentro). Há debates sobre seus limites: ao defender os **direitos humanos universais**, questiona-se se práticas que violam a dignidade, como a mutilação genital ou a escravidão, podem ser justificadas pela cultura. A resposta usual é combinar o respeito à diversidade com a defesa de direitos fundamentais.',
  'A **diversidade cultural** é uma riqueza da humanidade, reconhecida pela **UNESCO**, e o Brasil é um exemplo, com a herança dos povos indígenas, dos africanos escravizados e dos imigrantes europeus e asiáticos, que se combinaram de modo conflituoso e criativo. O conceito de **identidade cultural** refere-se ao sentimento de pertencimento a um grupo, construído em relações de contraste com os outros. Em um mundo globalizado, as identidades são múltiplas e dinâmicas. O **multiculturalismo** defende o reconhecimento e a coexistência de diferentes culturas em uma mesma sociedade, e as **políticas de reconhecimento** buscam proteger a língua, o patrimônio e os direitos de minorias.'] },
 { h:'Cultura material e imaterial, erudita, popular e de massa', p:[
  'A cultura pode ser dividida em **material**, que compreende os objetos, as construções, as ferramentas e as obras (edifícios, roupas, utensílios), e **imaterial** (ou simbólica), que compreende as crenças, os valores, os saberes, a língua, as festas, as danças e as formas de expressão. No Brasil, o **IPHAN** protege o patrimônio cultural material (tombamento) e o **imaterial** (registro), como o samba de roda, o frevo, o modo de fazer o acarajé e as festas populares. A preservação do patrimônio é uma forma de manter a memória e a identidade, e é um tema comum em questões do ENEM.',
  'Outra classificação refere-se à origem e ao público. A **cultura erudita** (ou "alta cultura") é associada às elites e ao ensino formal (música clássica, ópera, literatura canônica). A **cultura popular** é produzida pelo povo, de forma coletiva e tradicional (folclore, festas, artesanato, cordel). A **cultura de massa** é produzida em larga escala pelos meios de comunicação e pela indústria cultural, para um público amplo (televisão, rádio, cinema, música comercial). Essas fronteiras são fluidas: o carnaval é popular, mas também é um espetáculo midiático, e a música sertaneja ou o funk circulam em todas as classes. Rótulos como "alta" e "baixa" cultura costumam esconder preconceitos de classe.',
  'Outros conceitos importantes: **subcultura** (grupo com valores e práticas próprios dentro de uma cultura maior, como os skatistas, os punks e os grupos religiosos), **contracultura** (movimento que rejeita os valores dominantes, como o movimento hippie dos anos 1960), **aculturação** (contato entre culturas, com mudanças em uma ou ambas), **hibridismo cultural** (mistura que cria novas formas, como o sincretismo religioso afro-brasileiro) e **apropriação cultural** (uso de elementos de uma cultura por outra, em geral dominante, sem reconhecimento ou com descaracterização). Esses termos aparecem em textos sobre globalização, identidade e disputas simbólicas.'] },
 { h:'Cultura, poder e mudança social', p:[
  'A cultura não é neutra: está ligada ao **poder**. Os grupos dominantes tendem a impor seus valores e a classificar os dos outros como inferiores. **Gramsci** usou o conceito de **hegemonia cultural** para mostrar como a classe dominante mantém o poder não só pela força, mas pelo consentimento, ao difundir sua visão de mundo pela escola, pela religião e pela mídia. **Bourdieu** mostrou que o gosto e o consumo cultural funcionam como **distinção** social, e que o **capital cultural** é desigualmente distribuído. Esses autores ajudam a perceber que as disputas por reconhecimento e por representação são também disputas de poder.',
  'A cultura muda ao longo do tempo, por fatores internos (invenções, conflitos) e externos (contato entre povos, migrações, tecnologia). A **difusão cultural** espalha traços de uma cultura para outras. O **processo civilizador**, analisado por Norbert Elias, mostra como os costumes (à mesa, no controle da violência) se transformaram na Europa. Hoje, a **globalização** e a internet aceleram as trocas, e geram tanto a **homogeneização** (padronização de gostos, predomínio de produtos de poucos países) quanto a **resistência** e a valorização do local. A "glocalização" expressa essa combinação do global com o local.',
  'Há, ainda, a **indústria cultural** (Adorno e Horkheimer), que transforma a cultura em mercadoria padronizada, e as discussões sobre **cultura digital**, redes sociais e cultura participativa, em que os usuários também produzem conteúdos. Para a prova, vale entender que a cultura é aprendida, simbólica, social, dinâmica e diversa, que está ligada a relações de poder, e que o respeito à diversidade exige combater o etnocentrismo. Esses conceitos servem tanto para a Sociologia quanto para a Redação, na defesa de propostas de valorização cultural e de combate à intolerância.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O tema cultura é recorrente. As questões costumam trazer textos, imagens, charges ou relatos sobre práticas de um povo, e pedem a identificação de **etnocentrismo**, **relativismo cultural**, **diversidade**, **identidade**, **patrimônio imaterial**, **hibridismo**, **indústria cultural** ou **hegemonia**. Também são comuns as perguntas sobre a valorização de manifestações populares, sobre a preservação de línguas indígenas e de tradições, sobre a influência da globalização nas culturas locais e sobre o papel da mídia na difusão de padrões.',
  'Pontos de atenção: cultura não é sinônimo de erudição, todos os povos têm cultura; a cultura é aprendida, e não biológica; etnocentrismo é julgar o outro por seus próprios padrões, e relativismo é compreendê-lo em seu contexto; hibridismo e sincretismo são misturas; patrimônio material e imaterial são protegidos pelo IPHAN; a indústria cultural padroniza e comercializa a cultura; a cultura é campo de disputas e de poder. Evite as alternativas que hierarquizam culturas, que tratam a cultura popular como inferior ou que associam diferenças culturais a diferenças raciais.',
  'Para revisar, monte um glossário com os conceitos e dê um exemplo brasileiro de cada um: capoeira (patrimônio imaterial), sincretismo religioso (hibridismo), carnaval (popular e de massa), língua indígena (diversidade) e os preconceitos contra o sotaque (etnocentrismo). Na Redação, o repertório sobre diversidade e respeito às diferenças pode embasar propostas de educação, de mídia e de políticas públicas. O próximo tema, a socialização, mostra como a cultura é transmitida e interiorizada pelos indivíduos.'] }
]},
{ t:'Socialização', txt:[
 { h:'O que é socialização', p:[
  'A **socialização** é o processo pelo qual os indivíduos aprendem e interiorizam as **normas, os valores, os costumes, as linguagens e os papéis** de sua sociedade, e se tornam membros dela. Começa no nascimento e se estende por toda a vida. Ao nascer, o ser humano é biologicamente muito dependente, e só se torna plenamente humano pela convivência social: aprende a falar, a andar de acordo com certos padrões, a controlar suas necessidades, a se relacionar e a pensar. Casos de crianças isoladas (as chamadas "crianças selvagens") mostram que, sem convivência, o desenvolvimento da linguagem e do pensamento fica gravemente comprometido.',
  'Para Durkheim, a socialização é o processo de transmissão das gerações adultas às novas, que forma o "ser social" a partir do ser biológico, por meio da educação. Para a Sociologia interacionista, o indivíduo não é apenas um receptor passivo: constrói sua identidade em **interação** com os outros. **George Herbert Mead** descreveu o desenvolvimento do "**eu**" (self) pela capacidade de assumir o papel dos outros: primeiro, pela imitação e pelo jogo (brincar de médico ou de mãe), depois pela noção do "outro generalizado", isto é, as expectativas da sociedade como um todo. **Charles Cooley** falou do "eu espelho": nos vemos como os outros nos veem.',
  'A socialização é, portanto, um processo de mão dupla, em que a sociedade molda o indivíduo, mas este também a interpreta, a reproduz ou a transforma. Esse equilíbrio entre **estrutura** e **agência** é um tema clássico da Sociologia. Se a socialização fosse totalmente determinante, não haveria mudança social, nem dissidência. Se fosse irrelevante, não haveria regularidades. Reconhecer que somos moldados pela cultura, mas capazes de refletir e de agir, ajuda a evitar tanto o determinismo social quanto o individualismo extremo, e é uma chave para interpretar muitas questões.'] },
 { h:'Socialização primária e secundária, e agentes socializadores', p:[
  'Os sociólogos **Peter Berger e Thomas Luckmann** distinguem a socialização **primária**, que ocorre na infância, principalmente na **família**, e que forma a base da identidade, da linguagem e dos valores fundamentais, e a **secundária**, que ocorre ao longo da vida, em instituições e grupos (escola, trabalho, grupos religiosos, profissões), e transmite conhecimentos e papéis específicos. A primária é marcada por forte carga afetiva e pela dificuldade de questionar o que se aprendeu. A secundária é mais especializada e racional. Há também a **ressocialização**, quando o indivíduo precisa aprender novos valores e comportamentos, como em um serviço militar, em uma prisão ou em um processo de migração.',
  'Os **agentes de socialização** são as instituições e os grupos que transmitem a cultura. A **família** é o primeiro, e ensina a língua, os afetos, a religião e os papéis de gênero. A **escola** transmite conhecimentos formais, mas também o "currículo oculto": disciplina, hierarquia, competição, pontualidade. A **religião** oferece valores e sentidos. O **grupo de pares** (amigos e colegas) é decisivo na adolescência, e influencia o gosto, o vocabulário e as condutas. Os **meios de comunicação** e, hoje, as **redes sociais** difundem padrões de beleza, de consumo e de comportamento, de modo massivo. O **trabalho** e o **Estado** (leis, serviços) também socializam.',
  'Esses agentes podem reforçar-se ou entrar em conflito. Um jovem pode receber da família valores diferentes dos que encontra na escola, no grupo de amigos ou nas redes. A importância relativa dos agentes mudou: a mídia digital passou a competir com a família e a escola na formação das crianças, com consequências para a atenção, para a identidade e para os padrões de consumo. A discussão sobre o uso de telas, sobre o cyberbullying e sobre a influência dos influenciadores é, em grande parte, uma discussão sobre os novos agentes de socialização e suas responsabilidades.'] },
 { h:'Normas, papéis sociais, status e controle', p:[
  'Pela socialização, aprendemos **normas** (regras de conduta que indicam o que é esperado ou proibido), **valores** (ideias sobre o que é bom, justo e desejável), **papéis sociais** (conjuntos de comportamentos esperados de quem ocupa uma posição) e **status** (posição ocupada em um sistema social, com direitos e deveres). Uma pessoa ocupa vários status e papéis simultaneamente: filha, estudante, trabalhadora, amiga. Quando as expectativas dos papéis entram em choque, há **conflito de papéis**. Os papéis podem ser **atribuídos** (sexo, idade, origem) ou **adquiridos** (profissão, escolaridade).',
  'A socialização inclui a transmissão dos **papéis de gênero**, as expectativas socialmente construídas sobre o que é "de menino" e "de menina": brinquedos, cores, profissões, comportamentos. Muitas diferenças atribuídas à natureza são resultado de aprendizagem social, o que explica por que variam entre culturas e épocas. Questionar esses estereótipos é parte do debate sobre igualdade de gênero. Da mesma forma, a socialização transmite valores de classe, de raça e de religião, e pode reproduzir desigualdades e preconceitos, quando naturaliza hierarquias, o que é analisado por autores como Bourdieu, com o conceito de **habitus**.',
  'O **habitus**, em Bourdieu, é o conjunto de disposições duráveis, de modos de perceber, de sentir e de agir, incorporados pela socialização no ambiente de origem (família, classe), que orienta as práticas sem que o indivíduo perceba. Explica por que pessoas de origens distintas têm gostos, expectativas e trajetórias distintas, e como a escola pode legitimar desigualdades quando valoriza o capital cultural das classes favorecidas. O **controle social**, formal (leis, polícia) e informal (família, vizinhança, opinião pública), garante que as normas sejam seguidas, e age em conjunto com a socialização para manter a ordem.'] },
 { h:'Socialização, identidade e mudanças contemporâneas', p:[
  'A socialização forma a **identidade**, o conjunto de características pelas quais uma pessoa se reconhece e é reconhecida. Na modernidade, as identidades se tornaram mais fluidas, escolhidas e plurais, em oposição às sociedades tradicionais, em que eram atribuídas ao nascimento. **Stuart Hall** fala em identidades fragmentadas e em construção. As redes sociais ampliaram a possibilidade de apresentar-se de diferentes formas, mas também a pressão por aprovação, por padrões de beleza e por consumo. Isso gera debates sobre saúde mental, sobre autoestima e sobre os efeitos das comparações constantes.',
  'Outras transformações: a **infância** é uma construção histórica (na Idade Média, as crianças eram vistas como pequenos adultos, segundo Philippe Ariès); as famílias são hoje mais diversas (monoparentais, homoafetivas, recompostas); a escola enfrenta o desafio de dialogar com a cultura digital; o mundo do trabalho exige socialização contínua, com a aprendizagem permanente. A longevidade e as mudanças tecnológicas fazem com que o aprendizado de novos papéis ocorra em todas as idades. A **socialização política** forma as ideias sobre cidadania e participação, e é fundamental para a democracia.',
  'Entender a socialização é entender como a sociedade se reproduz e se transforma. A educação para a cidadania, a promoção da empatia, o combate ao preconceito e a regulação responsável da mídia são formas de intervir nesse processo. Em propostas de Redação, a socialização fundamenta a defesa de ações da família, da escola e da mídia para formar valores de respeito e de solidariedade. Na prova de Sociologia, aparece como um conceito para explicar comportamentos aprendidos, e não "naturais", em contextos como os de gênero, de consumo e de violência.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM aborda a socialização em textos e questões sobre a família, a escola, a mídia e as redes sociais como formadoras de valores; sobre a construção social de papéis de gênero; sobre a influência do ambiente na formação de preferências e de comportamentos; e sobre o conceito de habitus. Também pode apresentar situações do cotidiano (um jovem que muda de grupo e adota novos hábitos) e pedir a identificação do processo. Costuma cobrar a ideia de que comportamentos que parecem naturais são aprendidos em sociedade.',
  'Pontos de atenção: socialização é aprendizagem social, contínua, que forma identidade; a primária ocorre na família e a secundária, em outras instituições; os agentes são a família, a escola, a religião, os pares, a mídia e o trabalho; os papéis de gênero são construções sociais; o habitus é incorporado pela socialização; a socialização pode reproduzir desigualdades, mas o indivíduo também tem capacidade de reflexão. Cuidado com alternativas que tratem a conduta como puramente biológica ou como escolha totalmente livre, sem considerar o contexto social.',
  'Para revisar, escreva exemplos pessoais de cada agente de socialização e identifique o que aprendeu em cada um. Relacione o conceito com os autores: Durkheim (educação e transmissão), Mead (o eu e o outro generalizado), Berger e Luckmann (primária e secundária) e Bourdieu (habitus). Na Redação, prepare repertórios sobre a influência das redes na formação de jovens. O próximo tema, a estratificação social, mostra como as sociedades se organizam em camadas desiguais e como a socialização contribui para reproduzi-las.'] }
]},
{ t:'Estratificação social', txt:[
 { h:'O que é estratificação social', p:[
  'A **estratificação social** é a forma como uma sociedade se divide em **camadas hierarquizadas**, que ocupam posições desiguais quanto à riqueza, ao poder, ao prestígio e ao acesso a oportunidades. A imagem vem da geologia, em que os estratos são camadas sobrepostas. Toda sociedade complexa tem algum tipo de estratificação, mas as formas variam, assim como a justificativa que lhes é dada. A desigualdade não é apenas diferença de renda: envolve educação, saúde, moradia, segurança, tempo livre e reconhecimento. A Sociologia estuda como essas desigualdades se formam, se mantêm e se transformam.',
  'Os principais **sistemas de estratificação** são quatro. A **escravidão**, em que pessoas são propriedade de outras, sem liberdade, forma extrema de desigualdade, presente na Antiguidade e no Brasil colonial e imperial. As **castas**, típicas da Índia tradicional, em que a posição é atribuída pelo nascimento, é fixa e é justificada pela religião, com restrições de casamento e de contato. Os **estamentos** (ou estados), do feudalismo europeu, formados pela nobreza, pelo clero e pelo povo, com direitos definidos por lei e pela tradição, e com pouca mobilidade. E as **classes sociais**, do capitalismo, baseadas em critérios econômicos, em que a posição pode mudar por esforço, sorte ou estratégia, ao menos em princípio.',
  'Nas sociedades de classes, a igualdade jurídica formal convive com desigualdades reais. A passagem de um sistema a outro não eliminou a hierarquia, e muitos traços anteriores persistem, como o racismo, herança da escravidão no Brasil. Por isso, é importante analisar a estratificação de forma **multidimensional**: classe, raça, gênero, território e geração se combinam. O conceito de **interseccionalidade**, proposto por Kimberlé Crenshaw, mostra que uma mesma pessoa pode sofrer múltiplas desigualdades combinadas, como a mulher negra e pobre, e que não basta analisar cada uma isoladamente.'] },
 { h:'Marx, Weber e as teorias da estratificação', p:[
  'Para **Marx**, a estratificação é determinada pela posição nas **relações de produção**: a divisão fundamental, no capitalismo, é entre **burguesia** (donos dos meios de produção) e **proletariado** (vendedores da força de trabalho). As classes têm interesses opostos, e a luta de classes impulsiona a história. A desigualdade é resultado da exploração. Essa visão é **dicotômica** e centrada na economia, e destaca o conflito. Autores posteriores, como Erik Olin Wright, refinaram a análise para incluir posições intermediárias e contraditórias.',
  'Para **Weber**, a estratificação tem **três dimensões** independentes, ainda que relacionadas: a **classe** (posição econômica, baseada na riqueza e nas chances no mercado), o **status** (prestígio, honra social, estilo de vida) e o **partido** (poder político, capacidade de influenciar decisões). Uma pessoa pode ter alta posição em uma dimensão e baixa em outra: um professor universitário pode ter prestígio, mas pouca renda; um rico recente pode ter dinheiro, mas pouco prestígio. A visão weberiana é **multidimensional** e dá espaço à diversidade de posições.',
  'Já a perspectiva **funcionalista** (Davis e Moore) sustenta que a estratificação é necessária e funcional, pois as posições mais importantes e mais difíceis devem ser mais bem recompensadas, para atrair os mais capazes. É criticada por justificar a desigualdade e por ignorar a herança e as barreiras de acesso. **Bourdieu** acrescenta que, além do capital econômico, existem o **capital cultural** (conhecimentos, diplomas, gostos), o **social** (redes de contatos) e o **simbólico** (prestígio), e que as classes se reproduzem pela transmissão desses capitais. O quadro de comparação entre Marx, Weber e os funcionalistas é muito usado nas questões.'] },
 { h:'Mobilidade social, desigualdade e o caso brasileiro', p:[
  'A **mobilidade social** é a passagem de indivíduos ou grupos de uma posição a outra na estrutura social. Pode ser **vertical** (ascendente ou descendente) ou **horizontal** (mudança sem alteração de posição), **intergeracional** (comparando pais e filhos) ou **intrageracional** (ao longo da vida do indivíduo). Sociedades com alta mobilidade são mais "abertas", e as com baixa mobilidade, mais "fechadas". Fatores como a educação, o mercado de trabalho, a herança, as redes de contato e as políticas públicas (transferência de renda, cotas, bolsas) influenciam a mobilidade. A ideia de **meritocracia**, segundo a qual cada um ocupa a posição que merece por seu esforço, é criticada por ignorar as diferenças nos pontos de partida.',
  'O **Brasil** é um dos países mais desiguais do mundo, e a desigualdade tem raízes históricas: a escravidão, a concentração de terras, o acesso restrito à educação e a abolição sem políticas de inclusão. A desigualdade é medida por indicadores como o **índice de Gini** (de 0, igualdade total, a 1, desigualdade máxima), a renda per capita e o **IDH**. Apresenta também fortes recortes **regionais** (Norte e Nordeste x Sul e Sudeste), **raciais** (a população negra tem menor renda, escolaridade e expectativa de vida) e de **gênero** (diferenças salariais). Nas últimas décadas, houve períodos de redução da pobreza e da desigualdade, com programas como o Bolsa Família e a valorização do salário mínimo, mas persistem grandes disparidades.',
  'As **políticas públicas** para enfrentar a desigualdade incluem as de transferência de renda, a ampliação do acesso à educação, as **ações afirmativas** (cotas raciais e sociais nas universidades, Lei 12.711/2012), a reforma tributária e os investimentos em saneamento e saúde. Há debates sobre a eficácia e a legitimidade de cada uma. As ações afirmativas, por exemplo, visam corrigir desigualdades históricas e ampliar a diversidade, mas são criticadas por quem defende critérios exclusivamente meritocráticos. Compreender os argumentos dos dois lados é útil para a Redação.'] },
 { h:'Exclusão, pobreza e novas desigualdades', p:[
  'A **exclusão social** designa a situação de pessoas ou de grupos que não têm acesso a direitos e a bens básicos (trabalho, educação, saúde, moradia, participação política). Pode ser econômica, cultural ou espacial. A **segregação urbana** separa os territórios: periferias com menos infraestrutura e centros valorizados, condomínios fechados e favelas. A **pobreza** não se limita à renda: é multidimensional, e inclui privações de serviços e de capacidades. **Amartya Sen** define o desenvolvimento como a expansão das liberdades e das capacidades das pessoas, e não apenas o crescimento da renda.',
  'Novas desigualdades surgem com as transformações tecnológicas e econômicas: a **desigualdade digital** (acesso e habilidades no uso da internet), a **precarização do trabalho** (informalidade, trabalho por aplicativo, sem direitos), a concentração da riqueza em poucos bilionários e a desigualdade entre países (centro e periferia do capitalismo global). A pandemia de Covid-19 evidenciou e ampliou as desigualdades de renda, de educação remota e de acesso à saúde. O "**precariado**" (Guy Standing) designa a classe de trabalhadores com vínculos instáveis, sem segurança e perspectivas de carreira.',
  'Combater a desigualdade exige ações combinadas do Estado, do mercado e da sociedade civil: educação de qualidade, geração de empregos dignos, proteção social, combate ao racismo e ao machismo, e participação política. Em termos conceituais, é útil lembrar que a estratificação é uma construção social, e não natural; que as posições não dependem apenas do mérito individual; que as oportunidades iniciais importam; e que a desigualdade extrema compromete a coesão social e a democracia. Esses argumentos servem para a interpretação de gráficos, tabelas e textos sobre renda, sobre trabalho e sobre acesso a direitos.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM cobra a estratificação social por meio de textos, gráficos e tabelas sobre desigualdade de renda, mobilidade, pobreza e acesso a direitos; de comparações entre castas, estamentos e classes; de questões sobre o pensamento de Marx e Weber (classe, status e poder); de políticas de ações afirmativas e transferência de renda; e do debate sobre meritocracia. Também aparecem situações de segregação urbana, de racismo estrutural e de desigualdades de gênero, na Sociologia, na Geografia e na História.',
  'Pontos de atenção: os sistemas de estratificação são escravidão, castas, estamentos e classes; castas e estamentos têm posição fixa e baseada no nascimento, e as classes são abertas, em princípio; Marx enfatiza a relação com os meios de produção; Weber, classe, status e partido; Bourdieu, os capitais econômico, cultural, social e simbólico; mobilidade vertical é subir ou descer, e horizontal é mudar sem alterar a posição; o índice de Gini mede a desigualdade; a meritocracia é criticada por ignorar condições de partida. Atenção às alternativas que tratem a pobreza como fracasso individual.',
  'Para revisar, faça um quadro com os quatro sistemas de estratificação, e um segundo com as teorias (Marx, Weber, funcionalistas e Bourdieu). Pratique a leitura de gráficos de renda por raça e gênero, e relacione-os com a história do Brasil. Para a Redação, reúna repertório de dados e de conceitos (Gini, ações afirmativas, interseccionalidade) e propostas de educação e de proteção social. O próximo tema, Trabalho e sociedade, mostra como a organização do trabalho se liga à estrutura de classes e às transformações do capitalismo.'] }
]}
];
