/* Sociologia: textos corridos, temas 4 a 6 */
module.exports = [
{ t:'Émile Durkheim', txt:[
 { h:'Durkheim e a institucionalização da Sociologia', p:[
  '**Émile Durkheim** (1858-1917), francês, é considerado um dos fundadores da Sociologia como **disciplina científica e acadêmica**. Filho de um rabino, estudou na École Normale Supérieure, em Paris, foi professor em Bordeaux e depois na Sorbonne, e criou, em 1898, a revista **L\'Année Sociologique**, em torno da qual se formou uma escola de pesquisadores. Suas principais obras são **Da Divisão do Trabalho Social** (1893), **As Regras do Método Sociológico** (1895), **O Suicídio** (1897) e **As Formas Elementares da Vida Religiosa** (1912). Preocupado com a **coesão social** em uma época de rápidas mudanças e de conflitos, procurou dar à Sociologia um objeto e um método próprios.',
  'Para Durkheim, a Sociologia precisava se distinguir da Filosofia, da Psicologia e da Biologia, com um **objeto específico**: os **fatos sociais**. Influenciado pelo positivismo de Comte, defendia que esses fatos devem ser estudados de forma **objetiva**, "**como coisas**", ou seja, observados do exterior, com neutralidade, afastando as pré-noções e os preconceitos do senso comum, e buscando as **causas sociais** de cada fenômeno. Segundo ele, a explicação do social deve ser feita por outros fatos sociais, e não por características individuais, o que fundamenta a autonomia da Sociologia como ciência.',
  'Sua visão da sociedade é **organicista**: a sociedade é como um organismo, formado por partes interdependentes (instituições, grupos, normas) que desempenham **funções** para o equilíbrio do conjunto. Essa abordagem deu origem ao **funcionalismo**, que analisa os fenômenos sociais pela função que cumprem para a manutenção da ordem. Para Durkheim, a **sociedade é mais do que a soma dos indivíduos**: tem uma realidade própria, com uma "consciência coletiva" que antecede e ultrapassa os indivíduos, e que se impõe a eles. Esses conceitos são centrais para compreender suas análises.'] },
 { h:'O fato social e suas características', p:[
  'Em **As Regras do Método Sociológico**, Durkheim define o **fato social** como "toda maneira de fazer, fixada ou não, suscetível de exercer sobre o indivíduo uma coerção exterior; ou ainda, que é geral na extensão de uma sociedade dada, tendo, ao mesmo tempo, uma existência própria, independente das suas manifestações individuais". Em outras palavras, são as formas de agir, de pensar e de sentir que existem fora do indivíduo e que se impõem a ele. Exemplos: as leis, os costumes, a moral, a religião, a língua, as regras de etiqueta, o sistema monetário, as crenças e as práticas profissionais.',
  'O fato social tem três características essenciais. É **exterior** ao indivíduo: existe antes dele e independentemente de sua vontade, e é transmitido pela educação e pela convivência; ninguém inventa a língua que fala nem as regras sociais que encontra ao nascer. É **coercitivo**: exerce pressão sobre as pessoas, que são levadas a se conformar, sob pena de sanções, formais (como multas e prisões) ou informais (reprovação, ridicularização, isolamento). E é **geral**: é compartilhado por um grupo, e se manifesta de forma coletiva. Muitas vezes, nem percebemos a coerção, porque já interiorizamos as regras, mas ela se revela quando tentamos romper com elas.',
  'Do ponto de vista metodológico, Durkheim propõe regras para o estudo dos fatos sociais: **considerar os fatos sociais como coisas**; **afastar sistematicamente as pré-noções**; definir objetivamente o grupo de fenômenos a estudar; buscar a causa de um fato social em **outros fatos sociais** anteriores (e não em estados psicológicos individuais); e distinguir o **normal** do **patológico** (um fenômeno é normal se é geral em uma sociedade de determinado tipo e em certa fase de seu desenvolvimento, e patológico quando foge dessa generalidade). Para ele, até o crime é "normal", pois existe em todas as sociedades, e cumpre uma função, ao reafirmar os valores coletivos.'] },
 { h:'Divisão do trabalho, solidariedade e anomia', p:[
  'Em **Da Divisão do Trabalho Social**, Durkheim analisa o que mantém a coesão da sociedade. Distingue dois tipos de **solidariedade**. A **solidariedade mecânica** predomina em sociedades **tradicionais**, simples, pequenas, com pouca divisão do trabalho: os indivíduos são parecidos entre si (compartilham as mesmas crenças, valores e funções), e a coesão vem da **semelhança** e da **consciência coletiva**, que é forte e que reprime duramente os desvios, com um **direito repressivo** (penal). A **solidariedade orgânica** predomina em sociedades **modernas**, complexas, com intensa divisão do trabalho: os indivíduos são diferentes e **especializados**, e dependem uns dos outros, como os órgãos de um corpo, e a coesão vem da **interdependência**, com um **direito restitutivo** (civil, comercial, que visa reparar).',
  'A divisão do trabalho, portanto, não é apenas econômica: ela produz **laços sociais** e **moralidade**. Mas pode também gerar problemas, quando se desenvolve de forma desregulada. Durkheim fala então de **anomia**, a situação em que as **normas** que regulam as relações sociais se enfraquecem ou desaparecem, e os indivíduos ficam sem orientação e sem limites. Ela ocorre em períodos de **mudança rápida** ou de **crise** (como as crises econômicas e as grandes transformações sociais), quando as regras antigas perdem eficácia e novas ainda não se estabeleceram, produzindo desorientação, insatisfação e comportamentos desviantes.',
  'Durkheim também discute a **divisão do trabalho forçada**, em que a desigualdade de oportunidades impede que as pessoas ocupem as funções para as quais têm aptidão, e gera conflitos. Para que a solidariedade orgânica funcione, é preciso que a divisão do trabalho seja **justa**, com regras claras e com a igualdade das condições externas de competição. Em sua visão, instituições intermediárias, como as **corporações profissionais**, poderiam criar a regulação moral necessária, entre o indivíduo e o Estado. Esse tema é essencial para compreender os debates sobre trabalho, desigualdade e coesão nas sociedades atuais.'] },
 { h:'O suicídio como fato social e a educação', p:[
  'Em **O Suicídio** (1897), Durkheim mostra como a Sociologia pode explicar um fenômeno aparentemente individual e íntimo. Ao analisar estatísticas de diversos países, constatou que as **taxas de suicídio** variam de forma regular entre grupos sociais (religiões, estados civis, países, épocas), e são estáveis ao longo do tempo. Concluiu que o suicídio tem **causas sociais**, ligadas ao grau de **integração** do indivíduo ao grupo e à **regulação** das normas. Distinguiu quatro tipos. O **egoísta** ocorre quando o indivíduo está pouco integrado ao grupo (por exemplo, entre solteiros e protestantes, em comparação aos casados e católicos), e sente isolamento e falta de sentido.',
  'O **altruísta** ocorre quando a integração é excessiva, e o indivíduo se sacrifica pelo grupo (como em soldados e em certas culturas). O **anômico** ocorre quando faltam normas e limites, em momentos de crise econômica ou de mudanças bruscas, que desorientam os indivíduos (por exemplo, aumento de suicídios em tempos de depressão econômica, mas também de prosperidade súbita). O **fatalista**, mencionado brevemente, resulta de uma regulação excessiva e opressiva. A pesquisa é um modelo de investigação sociológica: usa dados, compara grupos e procura relações causais, mostrando que fatores sociais condicionam comportamentos individuais.',
  'Durkheim também se dedicou à **educação**, que considerava um processo de **socialização**: a geração adulta transmite à nova as normas, os valores e os conhecimentos da sociedade, para formar o "ser social" a partir do ser biológico. A educação moral, para ele, deve formar o **espírito de disciplina**, o **apego aos grupos** e a **autonomia**. Em **As Formas Elementares da Vida Religiosa**, analisa a religião, em sociedades australianas, como expressão da vida coletiva: o sagrado simboliza a própria sociedade, e os rituais reforçam a coesão e os sentimentos comuns. Assim, a religião cumpre uma função social, independentemente das crenças.'] },
 { h:'Críticas, legado e como o tema aparece no ENEM', p:[
  'As **críticas** a Durkheim incluem a de que sua visão é muito **conservadora**, com ênfase na ordem, na coesão e na regulação, e pouca atenção aos **conflitos** e às desigualdades (crítica de Marx e de teóricos do conflito); a de que desconsidera o **sentido** que os indivíduos dão a suas ações (crítica de Weber); e a de que o conceito de fato social e a metáfora organicista podem tratar a sociedade como um bloco, em vez de perceber suas contradições. Ainda assim, seu legado é imenso: o **funcionalismo**, a Sociologia empírica, o estudo das instituições, a Sociologia da religião e da educação, e os conceitos de **anomia** e de **solidariedade**.',
  'No ENEM, Durkheim aparece em questões que trazem trechos de suas obras ou descrevem fenômenos sociais e pedem a identificação dos conceitos de **fato social** (exterioridade, coercitividade e generalidade), de **solidariedade mecânica e orgânica**, de **anomia** e de **coesão social**, ou a aplicação desses conceitos a situações como as regras de convivência, os costumes, a educação, o desemprego e a violência. Também são frequentes as comparações entre Durkheim, Marx e Weber: Durkheim, ordem e coesão; Marx, conflito e classes; Weber, ação e sentido.',
  'Pontos de atenção: o fato social é externo ao indivíduo, coercitivo e geral; a sociedade é mais do que a soma dos indivíduos; a solidariedade mecânica é por semelhança e a orgânica é por interdependência; a anomia é a ausência ou o enfraquecimento das normas; o suicídio é explicado por causas sociais; a educação é socialização. Para revisar, monte um quadro com os conceitos e um exemplo atual para cada um (as regras de trânsito como fato social, a especialização do trabalho como solidariedade orgânica e a crise econômica como situação de anomia). O próximo tema é Karl Marx, que analisa a sociedade a partir da economia e dos conflitos de classe.'] }
]},
{ t:'Karl Marx', txt:[
 { h:'Marx, o contexto e as bases de seu pensamento', p:[
  '**Karl Marx** (1818-1883), alemão, foi filósofo, economista, historiador e militante político. Estudou Direito e Filosofia, e foi influenciado por **Hegel** (a dialética), por **Feuerbach** (o materialismo) e pela **economia política** inglesa (Adam Smith e Ricardo) e pelo **socialismo** francês. Exilado por suas ideias, viveu em Paris, em Bruxelas e, a partir de 1849, em Londres, onde escreveu **O Capital** (1867) e outras obras. Em parceria com **Friedrich Engels**, escreveu o **Manifesto Comunista** (1848), que expressa a ideia de que "a história de todas as sociedades até hoje é a história da luta de classes". Foi fundamental para a Sociologia, a Economia, a História e a Filosofia.',
  'O pensamento de Marx surge da observação do **capitalismo industrial** do século XIX, com a pobreza e a exploração dos operários. Seu objetivo não era apenas explicar a sociedade, mas **transformá-la**, como afirma na 11ª tese sobre Feuerbach: "os filósofos apenas interpretaram o mundo; o que importa é transformá-lo". Seu método é o **materialismo histórico e dialético**. **Materialista**, porque parte das condições **materiais** de existência (a produção da vida) para explicar a sociedade e as ideias, e não o contrário. **Histórico**, porque considera que as sociedades se transformam ao longo do tempo. **Dialético**, porque vê a história movida por **contradições** e conflitos.',
  'Diferentemente de Durkheim, que enfatiza a ordem e a coesão, Marx enfatiza o **conflito** e a **mudança**. Para ele, a sociedade é dividida em **classes sociais** com interesses antagônicos, e a dominação de uma classe sobre a outra é o centro da análise. Também se distingue de Weber, que destaca a ação e o sentido. Para Marx, o essencial está na forma como os seres humanos **produzem** seus meios de vida, em cada época. A produção é social: as pessoas estabelecem relações entre si, independentes de suas vontades, e essas relações formam a base da sociedade. Esse é o ponto de partida do conceito de modo de produção.'] },
 { h:'Modo de produção, infraestrutura e superestrutura', p:[
  'O **modo de produção** é a forma como uma sociedade organiza a produção dos bens necessários à vida. Compõe-se das **forças produtivas** (os instrumentos de trabalho, as máquinas, as técnicas, os conhecimentos, os recursos naturais e a força de trabalho) e das **relações de produção** (as relações sociais estabelecidas na produção, em especial as de **propriedade** dos meios de produção e de divisão do trabalho). Na história, Marx identifica diferentes modos de produção: o **comunismo primitivo**, o **escravista** (Antiguidade), o **feudal** e o **capitalista**, e prevê a transição para o **socialismo**. Cada um tem suas contradições internas, que levam à sua superação.',
  'A sociedade se divide em duas dimensões. A **infraestrutura** (ou base econômica) é formada pelas forças produtivas e pelas relações de produção. Sobre ela, ergue-se a **superestrutura**, que compreende as instituições jurídicas e políticas (Estado, leis) e as formas de consciência social (religião, moral, arte, filosofia e ciência). Em geral, a infraestrutura **condiciona** a superestrutura: "não é a consciência dos homens que determina o seu ser, mas, ao contrário, é o seu ser social que determina a sua consciência". Assim, as ideias dominantes de uma época refletem as relações de produção, e servem para legitimá-las: "as ideias da classe dominante são, em cada época, as ideias dominantes".',
  'Esse esquema é frequentemente mal compreendido como um determinismo econômico simples. Marx e Engels reconhecem que a superestrutura também influencia a base, e que a relação entre ambas é dialética. Mas a economia é decisiva "em última instância". A noção de **ideologia** se liga a isso: é o conjunto de ideias que expressam os interesses da classe dominante, mas se apresentam como universais e naturais, e ocultam as relações de dominação. A educação, a religião, a mídia e o direito podem reproduzir a ideologia, e levar os dominados a aceitar a ordem como natural e inevitável, o que dificulta a consciência de sua situação.'] },
 { h:'Classes sociais, luta de classes e exploração', p:[
  'Para Marx, as **classes sociais** se definem pela posição que ocupam nas relações de produção, em especial, pela relação com os **meios de produção** (terras, fábricas, máquinas, matérias-primas). No **capitalismo**, as duas classes fundamentais são a **burguesia**, que possui os meios de produção e vive do lucro, e o **proletariado**, que não os possui e precisa vender sua **força de trabalho**, em troca de salário, para sobreviver. Há também outras classes e frações (pequena burguesia, camponeses, o "lumpemproletariado"), mas o antagonismo central é entre as duas primeiras. Não se trata apenas de diferença de renda: é uma relação de **poder** e de **exploração**.',
  'A **exploração** se explica pela teoria da **mais-valia**. O trabalhador recebe um salário, que corresponde ao valor necessário à reprodução de sua força de trabalho, mas produz um valor superior em sua jornada. A diferença entre o valor produzido e o salário pago é a **mais-valia**, apropriada pelo capitalista, e é a fonte do **lucro** e da acumulação de capital. Assim, a exploração não resulta de fraude, mas do funcionamento normal do sistema, em que o trabalho é uma mercadoria. A busca de maior mais-valia leva à intensificação do trabalho, ao prolongamento da jornada e à introdução de máquinas, o que gera o desemprego e as crises.',
  'A **luta de classes** é o motor da história: os conflitos entre exploradores e explorados (senhores e escravos, nobres e servos, burgueses e proletários) provocam as transformações. No capitalismo, as contradições entre o caráter social da produção e a apropriação privada da riqueza geram crises, concentração e miséria, e, ao mesmo tempo, **unem** e **organizam** o proletariado nas fábricas, o que o transforma em uma **classe para si**, consciente de seus interesses (a **consciência de classe**), e capaz de se organizar em sindicatos e partidos. A revolução proletária destruiria a ordem capitalista, e levaria a uma sociedade sem classes, em uma fase de transição (ditadura do proletariado) até o comunismo.'] },
 { h:'Alienação, fetichismo e atualidade de Marx', p:[
  'Marx descreve a **alienação** do trabalhador no capitalismo. O trabalho, que deveria ser a atividade criadora pela qual o ser humano se realiza, torna-se um meio de sobrevivência, imposto e controlado por outros. O trabalhador se aliena do **produto** (que não lhe pertence), da **atividade** (que não controla, e que é repetitiva e fragmentada), de sua **essência humana** (a criatividade) e dos **outros seres humanos** (com quem compete). O resultado é um trabalhador "estranho" a si mesmo. O **fetichismo da mercadoria** é a ilusão de que as coisas têm valor por si mesmas, e escondem as relações sociais e o trabalho humano que as produzem.',
  'As ideias de Marx foram, e são, muito influentes. Inspiraram movimentos operários, partidos e revoluções (a Russa, de 1917, a Chinesa e a Cubana), embora os regimes que se declararam marxistas tenham sido criticados por seu autoritarismo. Influenciaram a Sociologia (a análise das classes, do poder e da desigualdade, da Escola de Frankfurt, de Gramsci e de Bourdieu), a História, a Economia e as lutas sociais. As **críticas** incluem o **determinismo econômico**, o fracasso das previsões (a revolução não ocorreu nos países industriais avançados), a subestimação de outras formas de desigualdade (gênero e raça) e os problemas do socialismo real.',
  'Mesmo assim, a **atualidade** de Marx é notável. Em um mundo de grande concentração de renda, de precarização do trabalho, de trabalhadores "uberizados", de crises financeiras e de mercantilização de todos os aspectos da vida, seus conceitos de exploração, de alienação, de ideologia e de classe são retomados. A discussão sobre quem controla a tecnologia, os dados e os meios de produção contemporâneos (as plataformas digitais) pode ser feita com categorias marxistas. Compreender Marx, de forma crítica e histórica, sem caricaturas, é parte da formação sociológica e filosófica, e um conteúdo muito cobrado em provas.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Marx aparece no ENEM em questões com trechos do Manifesto Comunista, de O Capital ou de comentadores, e pedem a identificação dos conceitos de **classes sociais**, **luta de classes**, **mais-valia**, **alienação**, **ideologia**, **infraestrutura e superestrutura** e **modo de produção**. Também são frequentes as situações de trabalho (precarização, terceirização, jornadas longas, desigualdade salarial, trabalho por aplicativo) em que se pede a análise à luz da exploração e da alienação, e as comparações entre Marx, Durkheim e Weber.',
  'Pontos de atenção: para Marx, a história é a luta de classes; as classes se definem pela relação com os meios de produção; a mais-valia é a base do lucro e da exploração; a alienação é a perda do controle sobre o trabalho e seu produto; a ideologia expressa os interesses da classe dominante; a infraestrutura condiciona a superestrutura; o materialismo histórico explica a sociedade pelas condições materiais. Evite confundir Marx com os regimes que se disseram marxistas, e com Durkheim: Marx enfatiza o conflito e a transformação, e Durkheim, a coesão e a ordem.',
  'Para revisar, monte um esquema com o modo de produção capitalista (burguesia e proletariado, meios de produção, mais-valia, ideologia) e uma lista de exemplos atuais para cada conceito. Compare Marx e Durkheim em um quadro (conflito versus consenso, classe versus solidariedade, exploração versus anomia). O próximo tema é Max Weber, que oferece uma abordagem complementar, centrada na ação social, no sentido que os indivíduos atribuem a suas ações, e na racionalização do mundo moderno.'] }
]},
{ t:'Max Weber', txt:[
 { h:'Weber e a Sociologia compreensiva', p:[
  '**Max Weber** (1864-1920), alemão, foi sociólogo, economista, jurista e historiador, um dos maiores nomes da Sociologia. Estudou Direito e foi professor em Freiburg, Heidelberg e Munique. Suas principais obras são **A Ética Protestante e o Espírito do Capitalismo** (1904 a 1905), **Economia e Sociedade** (publicada após sua morte), **Ciência e Política: Duas Vocações** e estudos sobre as religiões mundiais. Diferentemente de Durkheim, que privilegiava as estruturas e os fatos sociais, e de Marx, que privilegiava a economia e as classes, Weber enfatizou a **ação social** e o **sentido** que os indivíduos atribuem ao que fazem, e desenvolveu uma Sociologia **compreensiva**.',
  'Para Weber, o objeto da Sociologia é a **ação social**, a conduta humana a que o agente atribui um **sentido subjetivo** e que se orienta pela conduta de outros. A tarefa do sociólogo é **compreender** (Verstehen) esse sentido, interpretando as motivações dos agentes, e **explicar** causalmente seus efeitos. Isso exige métodos distintos dos das ciências naturais, pois o mundo social é feito de significados. Weber distingue quatro tipos de ação social: a **racional com relação a fins** (calcula meios e fins para atingir um objetivo, como o empresário que investe visando ao lucro), a **racional com relação a valores** (orientada por convicções, independentemente do resultado, como alguém que age por honra ou fé), a **afetiva** (guiada por emoções) e a **tradicional** (guiada por hábitos e costumes).',
  'Weber propõe também a **neutralidade axiológica** (ou "liberdade de valores"): o cientista deve separar a **análise** dos fatos dos **julgamentos de valor**, sem impor suas preferências ao descrever a realidade, embora seus valores influenciem a escolha dos temas de pesquisa ("relação com valores"). O instrumento metodológico central é o **tipo ideal**, uma construção conceitual que acentua certos traços de um fenômeno, como um "modelo puro", para permitir a comparação com os casos reais, que nunca o realizam completamente. Por exemplo, o tipo ideal de burocracia ou de capitalismo. Não é uma descrição da realidade, nem um ideal moral, mas uma ferramenta analítica.'] },
 { h:'A ética protestante e o espírito do capitalismo', p:[
  'Em **A Ética Protestante e o Espírito do Capitalismo**, Weber investiga a relação entre a religião e o surgimento do capitalismo moderno. Observou que, em países europeus de religião mista, os proprietários de empresas, os empresários e os trabalhadores qualificados eram predominantemente **protestantes**. Argumenta que certos valores do protestantismo, em especial do **calvinismo**, contribuíram para formar o "**espírito do capitalismo**": uma mentalidade que valoriza o **trabalho disciplinado**, a **poupança**, a **racionalidade**, a vida austera e o lucro reinvestido, e vê o trabalho como uma "vocação" (Beruf), um chamado divino.',
  'A doutrina calvinista da **predestinação** sustenta que Deus escolheu, desde sempre, quem será salvo, e ninguém pode saber ao certo se está entre os eleitos. Isso gerava grande angústia, e os fiéis passaram a buscar, no sucesso profissional e na vida disciplinada, **sinais** da graça divina. O trabalho incessante, a poupança e o ascetismo no mundo (sem desperdício e luxo) levaram à **acumulação de capital**, que era reinvestida, sem ser consumida. Assim, uma motivação religiosa teria produzido, de forma não intencional, um comportamento econômico favorável ao capitalismo. A conclusão não é que a religião "causou" o capitalismo, mas que valores religiosos contribuíram, junto com outros fatores.',
  'Essa tese contrasta com a visão de Marx, que considerava as ideias e a religião como superestrutura, determinada pela economia. Weber argumenta que as ideias podem ter **influência causal** sobre a economia, e que a relação é de **afinidade eletiva**. Ele mostra, ainda, que, com o tempo, o capitalismo se tornou independente de suas origens religiosas, e passou a funcionar por si mesmo, como uma "**gaiola de ferro**" (ou "jaula de aço"), em que os indivíduos ficam presos a uma lógica racional, impessoal, de eficiência e de cálculo, que os obriga a adotar certos comportamentos, mesmo sem convicção religiosa. Essa imagem expressa a ambiguidade do progresso moderno.'] },
 { h:'Racionalização, burocracia, poder e dominação', p:[
  'Para Weber, a característica marcante da modernidade ocidental é a **racionalização**: um processo em que a vida social passa a ser organizada por critérios de **cálculo**, de **eficiência**, de **previsibilidade** e de **regras impessoais**, em substituição à tradição, à magia e às emoções. Ele a chama de "**desencantamento do mundo**": a explicação religiosa e mágica cede lugar à ciência e à técnica. A racionalização está presente na economia (contabilidade, empresa capitalista), no direito, na ciência, na administração e na organização do trabalho. Traz ganhos de eficiência e de liberdade em relação à tradição, mas também perda de sentido, de espontaneidade e de autonomia.',
  'Um exemplo dessa racionalização é a **burocracia**, forma de organização baseada em regras escritas, **hierarquia** de cargos, **impessoalidade**, divisão de funções, **competência técnica** e documentação. Weber a considerava a forma mais eficiente de administração, em empresas, em exércitos e no Estado moderno, mas alertava para seus riscos: a desumanização, a rigidez, o **formalismo** e a possibilidade de que os funcionários se tornem "peças" de uma máquina, preocupados com o procedimento, e não com o fim. A "gaiola de ferro" da burocracia pode limitar a liberdade individual, tema atual nos debates sobre as organizações.',
  'Weber também analisou o **poder** (a probabilidade de impor a própria vontade, mesmo contra resistências) e a **dominação** (a probabilidade de obediência a ordens), e distinguiu três tipos de **dominação legítima**, conforme o fundamento da legitimidade. A **tradicional** baseia-se na crença na santidade das tradições e dos costumes (o patriarca, o monarca hereditário). A **carismática** baseia-se na devoção a uma pessoa excepcional, a quem se atribui dons extraordinários (o profeta, o líder revolucionário). A **racional-legal** baseia-se na crença na legalidade de regras impessoais e no direito de comando de quem exerce o poder segundo elas (o Estado moderno e a burocracia). Para Weber, o **Estado** é a organização que detém o **monopólio do uso legítimo da violência** em um território.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Weber aparece no ENEM em questões que trazem trechos de A Ética Protestante ou de Economia e Sociedade, e pedem a identificação de conceitos como **ação social**, **tipo ideal**, **racionalização**, **burocracia**, **dominação legítima** (tradicional, carismática e racional-legal), **monopólio da violência legítima** e a relação entre a religião e o capitalismo. Também são comuns as situações em que um líder, uma instituição ou uma norma se justificam de modo tradicional, carismático ou legal, e a pergunta é qual tipo de dominação está presente. As comparações entre Weber, Marx e Durkheim são frequentes.',
  'Pontos de atenção: a Sociologia de Weber é compreensiva, e busca o sentido da ação social; os quatro tipos de ação (racional com relação a fins, racional com relação a valores, afetiva e tradicional); o tipo ideal é uma ferramenta analítica; o espírito do capitalismo está ligado à ética protestante (calvinismo, vocação e poupança); a racionalização é o desencantamento do mundo; a burocracia é impessoal, hierárquica e baseada em regras; a dominação pode ser tradicional, carismática ou racional-legal; o Estado detém o monopólio da força legítima. Evite confundir Weber com determinismo econômico: ele valoriza o papel das ideias.',
  'Para revisar, monte uma tabela com os três clássicos (Durkheim, Marx e Weber): objeto, método, conceitos-chave e visão da sociedade. Treine identificar, em exemplos do dia a dia, os tipos de ação social e de dominação (por exemplo, a obediência ao pai por costume, ao influenciador pelo carisma e à lei por sua legalidade). Com este tema, você conclui os clássicos da Sociologia, e passa aos conceitos fundamentais para a análise social, a começar pela cultura e pela sociedade, a socialização e a estratificação social.'] }
]}
];

module.exports[2].txt.splice(3,0,{ h:'Weber, ciência e política: as vocações', p:[
  'Em **Ciência e Política: Duas Vocações**, Weber reflete sobre o papel do cientista e do político no mundo moderno. Para ele, a ciência é uma vocação que exige especialização, rigor e honestidade intelectual, e não pode oferecer ao indivíduo respostas sobre o sentido último da vida ou sobre quais valores seguir. Cabe à ciência esclarecer os meios, as consequências e a coerência das escolhas, mas a decisão entre valores concorrentes é uma escolha pessoal. Essa posição fundamenta a neutralidade axiológica: o professor não deve usar a sala de aula como palanque, e o pesquisador deve distinguir o que é constatação do que é preferência.',
  'Quanto à política, Weber distingue a **ética da convicção**, em que o agente age por princípios e se preocupa com a pureza de suas intenções, sem considerar tanto as consequências, e a **ética da responsabilidade**, em que o agente avalia os efeitos previsíveis de seus atos e responde por eles. O bom político, segundo Weber, precisa combinar paixão, senso de responsabilidade e senso de proporção. Como o Estado detém o monopólio da violência legítima, quem faz política lida com meios perigosos, e deve assumir o peso moral de suas decisões, sem se esconder atrás de boas intenções.',
  'Essas ideias ajudam a analisar debates atuais sobre o papel da ciência e dos governantes. Quando se discute se decisões públicas devem seguir apenas a técnica, apenas as convicções ou o equilíbrio entre ambas, aplica-se o raciocínio weberiano. Também permitem criticar a ideia de que a ciência, sozinha, resolve dilemas morais, e a de que os políticos podem agir sem considerar as consequências. No ENEM, o tema surge de forma indireta, em textos sobre ética, poder e responsabilidade, em que o candidato deve reconhecer a distinção entre convicção e responsabilidade.'] });
