/* Sociologia: textos corridos, temas 1 a 3 */
module.exports = [
{ t:'O que é Sociologia', txt:[
 { h:'Objeto e origem da Sociologia', p:[
  'A **Sociologia** é a ciência que estuda a **sociedade**: as relações entre os indivíduos, a organização dos grupos e das instituições, os processos de mudança social e as formas como as pessoas pensam, agem e se relacionam. Seu nome foi criado por **Auguste Comte**, no século XIX, e vem da junção do latim socius (companheiro, sociedade) com o grego logos (estudo). Diferentemente de outras ciências, a Sociologia estuda um objeto do qual o próprio pesquisador faz parte, o que exige cuidado para distinguir a análise rigorosa das opiniões e dos preconceitos do senso comum.',
  'O objeto central da Sociologia são os **fatos sociais**, as relações e os processos que ocorrem entre as pessoas em sociedade, e que não podem ser explicados apenas pelas características individuais. Por exemplo, uma pessoa estar desempregada pode ter explicações pessoais, mas o desemprego, como taxa que varia entre países e épocas, é um fenômeno social, ligado à economia, às políticas públicas e à estrutura do trabalho. Assim, a Sociologia busca **explicações sociais** para os fenômenos humanos, e procura relacionar a **vida individual** com a **estrutura social** mais ampla.',
  'A Sociologia nasceu no século XIX, na Europa, em um contexto de profundas transformações: a **Revolução Industrial**, a **urbanização**, a **Revolução Francesa**, o crescimento do proletariado, a desigualdade e os conflitos sociais. Era preciso compreender as mudanças e os problemas da sociedade moderna, e os pensadores buscaram métodos científicos para isso. Seus fundadores, ou "clássicos", são **Auguste Comte**, **Émile Durkheim**, **Karl Marx** e **Max Weber**, que ofereceram explicações diferentes, e cujas ideias seguem sendo a base para a análise social, como veremos nos temas seguintes.'] },
 { h:'A imaginação sociológica e o senso comum', p:[
  'O sociólogo **C. Wright Mills**, em **A Imaginação Sociológica** (1959), propôs a ideia de que a Sociologia permite relacionar a **biografia** (a experiência individual) com a **história** (a estrutura social). Ela ajuda a perceber que muitos problemas que parecem **pessoais** (desemprego, endividamento, divórcio, violência) são, na verdade, **problemas públicos**, ligados a condições sociais, econômicas e históricas. Essa mudança de perspectiva é o que se chama de **imaginação sociológica**: a capacidade de ver o social por trás do individual, e de **desnaturalizar** o que parece natural.',
  'A **desnaturalização** é uma atitude central. Muitos aspectos da vida social parecem naturais e eternos (a divisão de papéis entre homens e mulheres, a pobreza, a organização da família), mas são **construções históricas e sociais**, que mudam no tempo e variam entre culturas. Ao mostrar que são produzidas por relações sociais, a Sociologia revela que podem ser **modificadas**. Outra atitude é o **estranhamento**: olhar o familiar como se fosse estranho, questionando hábitos e costumes que seguimos sem pensar, e, ao mesmo tempo, procurar entender o que é diferente, evitando julgá-lo pelos próprios padrões.',
  'O **senso comum** é o conhecimento do dia a dia, adquirido pela experiência e pela tradição, e é útil, mas costuma ser baseado em generalizações, em preconceitos e em explicações simplistas ("pobre é pobre porque não trabalha", "mulher é emotiva"). A Sociologia, como ciência, exige **método**, **evidências**, **conceitos** e **crítica**, e busca explicações fundamentadas, com dados e teorias. Isso não significa desprezar o senso comum, que também pode ser objeto de estudo, mas questioná-lo. A distinção entre a ciência e as crenças é um ponto importante, pois as provas valorizam a capacidade de analisar a realidade social com base em conceitos e dados.'] },
 { h:'Ramos, métodos e o lugar da Sociologia entre as ciências', p:[
  'A Sociologia tem diversas **áreas de estudo**, que se multiplicaram ao longo do tempo: Sociologia da **educação**, do **trabalho**, da **religião**, da **família**, **urbana** e **rural**, da **cultura**, da **comunicação**, do **desvio** e da violência, da **saúde**, do **meio ambiente**, de **gênero** e das **relações raciais**, entre outras. Pode analisar fenômenos em escala **macro** (sociedades, instituições e estruturas, como o capitalismo e o Estado) e em escala **micro** (as interações entre as pessoas no cotidiano, como em uma sala de aula ou em uma conversa). A combinação das escalas oferece uma visão mais completa.',
  'Os **métodos** de pesquisa incluem abordagens **quantitativas** (pesquisas estatísticas, questionários, censos, análise de dados) e **qualitativas** (entrevistas, observação participante, histórias de vida, estudos de caso, análise de documentos e de discursos). Os dois tipos se complementam: os números mostram padrões e tendências, e os estudos qualitativos revelam sentidos, motivações e experiências. A pesquisa sociológica precisa de rigor, de transparência quanto aos métodos e de reflexão sobre a **neutralidade**: Weber defendia a "neutralidade axiológica" (separar o julgamento de valor da análise), embora reconhecesse que os valores orientam a escolha dos temas.',
  'A Sociologia faz parte das **Ciências Humanas**, e se relaciona com a **Antropologia** (que estuda a cultura e a diversidade dos povos), a **Ciência Política** (poder e Estado), a **Economia**, a **História**, a **Geografia** e a **Psicologia Social**. Cada uma tem foco e métodos próprios, mas há muitos diálogos. A Sociologia também tem uma dimensão **crítica**, pois, ao analisar as relações sociais, pode apontar desigualdades e injustiças e contribuir para a formulação de políticas públicas e para a transformação social. Em outras palavras, produz conhecimento sobre a sociedade, e com ele subsídios para a cidadania.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'O ENEM cobra o conceito de Sociologia de forma implícita, em questões que pedem a análise de fenômenos sociais a partir de conceitos e de dados: a desigualdade, o desemprego, a violência, as relações de gênero e de raça, as mudanças no trabalho e na família. Muitas questões usam textos de sociólogos (Durkheim, Marx, Weber, Bauman, Bourdieu e outros) e esperam que o estudante identifique a perspectiva e a aplique. A atitude sociológica, que desnaturaliza e estranha o cotidiano, é a habilidade central.',
  'Pontos de atenção: a Sociologia estuda os fatos sociais e as relações entre indivíduo e sociedade; surgiu no século XIX, em resposta às transformações da modernidade; os clássicos são Comte, Durkheim, Marx e Weber; a imaginação sociológica liga a biografia à história; desnaturalizar é mostrar que o que parece natural é construído socialmente; o senso comum é um conhecimento acrítico, que a ciência questiona. Evite explicações individualistas para problemas coletivos ("é falta de esforço"), e prefira as que consideram o contexto social.',
  'Para revisar, escreva com suas palavras o objeto da Sociologia, o contexto de seu surgimento, o que é desnaturalização e a diferença para o senso comum, e dê dois exemplos de fenômenos que parecem naturais, mas são construções sociais (por exemplo, o tempo de trabalho e os papéis de gênero). Esse tema abre a matéria e prepara o seguinte, que detalha o contexto histórico do surgimento da Sociologia, e depois os quatro clássicos, que fornecem os principais conceitos e teorias da área.'] }
]},
{ t:'Surgimento e contexto histórico da Sociologia', txt:[
 { h:'A Revolução Industrial e a sociedade moderna', p:[
  'A Sociologia surgiu na Europa, no século XIX, como resposta às **grandes transformações** que marcaram a passagem da sociedade tradicional para a **moderna**. A **Revolução Industrial** (a partir de meados do século XVIII, na Inglaterra) substituiu o trabalho artesanal e agrícola pelo trabalho em fábricas, organizado pelo ritmo das máquinas, com **divisão do trabalho**, jornadas longas e salários baixos. Surgiu uma nova classe, o **proletariado**, que vendia sua força de trabalho, e uma **burguesia** industrial, dona dos meios de produção. Essa nova organização do trabalho alterou profundamente os modos de vida e as relações sociais.',
  'Ao mesmo tempo, ocorreu uma intensa **urbanização**: milhões de pessoas deixaram o campo e se mudaram para as cidades industriais, como Manchester e Londres, onde viviam em condições precárias, em moradias superlotadas, sem saneamento, com doenças, pobreza, criminalidade e novas formas de **desigualdade**. A cidade modificou os laços sociais: as comunidades pequenas, em que todos se conheciam, deram lugar a grandes aglomerados anônimos, com vínculos mais impessoais e fragmentados. Os problemas sociais, como a miséria, o desemprego e a violência, ganharam visibilidade e passaram a exigir explicações e soluções.',
  'A sociedade tradicional, baseada na **terra**, na **hierarquia** de nascimento, na **religião** e na **comunidade**, foi substituída por uma sociedade baseada no **mercado**, no **salário**, no **contrato** e no **indivíduo**. O sociólogo alemão **Ferdinand Tönnies** distinguiu a **comunidade** (Gemeinschaft), com laços afetivos e tradicionais, da **sociedade** (Gesellschaft), com relações impessoais, racionais e contratuais. Essa mudança trouxe liberdade e oportunidades, mas também **insegurança**, **individualismo** e **perda de referências**, que os primeiros sociólogos procuraram entender.'] },
 { h:'As revoluções políticas e o Iluminismo', p:[
  'Além das mudanças econômicas, houve grandes transformações **políticas**. A **Revolução Francesa** (1789) derrubou o Antigo Regime, aboliu os privilégios da nobreza e do clero e proclamou a liberdade, a igualdade e a fraternidade, e a soberania popular. A queda da ordem tradicional trouxe instabilidade e conflitos, em um período de guerras e de revoluções (1830, 1848). Pensadores se perguntaram como reconstruir a **ordem social** depois da ruptura: o que mantém a sociedade unida? Como conciliar a liberdade individual com a coesão social? Essas questões estiveram na base de teorias como as de Comte e de Durkheim.',
  'O **Iluminismo** (século XVIII) forneceu as bases intelectuais. A confiança na **razão**, na ciência e no progresso levou à ideia de que os fenômenos sociais, assim como os naturais, podem ser estudados de modo racional e objetivo, por meio de leis. Os iluministas criticaram o dogmatismo, a superstição e os privilégios, e defenderam a liberdade e o conhecimento. Esse ambiente favoreceu a ideia de uma **ciência da sociedade**. Também contribuíram a **economia política** (Adam Smith, David Ricardo), que analisava a produção e a riqueza, e a **Filosofia da História** (Hegel), que via a história como um processo racional.',
  'A **Revolução Científica** e o sucesso das ciências naturais (a Física de Newton, a Biologia de Darwin) serviram de modelo. O **positivismo** de Comte pretendia aplicar o mesmo método às questões sociais, e Durkheim, influenciado por ele, defendeu que os fatos sociais devem ser tratados "como coisas". Outros pensadores, como Marx e Weber, desenvolveram abordagens diferentes, que consideravam as especificidades do mundo humano, como a história, os conflitos e o sentido das ações. Assim, desde o início, a Sociologia teve **diferentes perspectivas**, que dialogam e disputam a explicação da sociedade.'] },
 { h:'Os problemas que a Sociologia buscou entender', p:[
  'Os primeiros sociólogos se confrontaram com questões práticas e teóricas. Como explicar a **desigualdade** e a **pobreza** das cidades industriais? O que causa os **conflitos** entre as classes? Como manter a **ordem** e a **coesão** em uma sociedade mais individualista, em que a religião e a tradição perdem força? Que efeitos tem a **divisão do trabalho** sobre os indivíduos? O que significa **progredir**? Qual o papel do **Estado**? Para responder, desenvolveram conceitos que usamos até hoje: **fato social**, **solidariedade**, **anomia**, **classe social**, **luta de classes**, **alienação**, **ação social**, **racionalização**, **burocracia**.',
  'As respostas variaram conforme o autor. **Comte** buscava a **ordem** e o **progresso**, por meio do conhecimento científico da sociedade. **Durkheim** estudava a **coesão social** e as consequências da divisão do trabalho, o suicídio e a anomia. **Marx** analisava a **exploração** e os **conflitos de classe**, e defendia a transformação revolucionária do capitalismo. **Weber** investigava o **sentido** que os indivíduos dão a suas ações, a **racionalização** do mundo moderno e a relação entre a religião e o capitalismo. Cada um enfatizava aspectos diferentes: a ordem, o conflito e o significado.',
  'Essas teorias refletem também diferentes **posições políticas** e visões de mundo: o conservadorismo preocupado com a ordem, o liberalismo e o reformismo, o socialismo revolucionário. A Sociologia nasceu, assim, como uma ciência **comprometida** com o debate sobre os rumos da sociedade, e não como um saber neutro e isolado. Compreender o contexto de cada teoria é importante para entender suas ideias e seus limites, e para perceber que as teorias sociais não são verdades definitivas, mas instrumentos de análise, que devem ser comparados e criticados, em permanente diálogo com a realidade.'] },
 { h:'A institucionalização da Sociologia e seu desenvolvimento', p:[
  'A Sociologia foi se tornando uma disciplina **acadêmica** no final do século XIX e no início do XX. Na França, **Durkheim** criou a primeira cátedra de Sociologia, na Universidade de Bordeaux (1887), e fundou a revista **L\'Année Sociologique** (1898). Na Alemanha, Weber, Simmel e Tönnies foram figuras centrais. Nos Estados Unidos, a **Escola de Chicago**, a partir de 1892, desenvolveu estudos urbanos e pesquisas empíricas sobre imigrantes, gangues e a vida nas cidades. Com o tempo, surgiram novas correntes: o funcionalismo (Parsons, Merton), o interacionismo simbólico (Mead, Goffman), a teoria crítica (Frankfurt) e a sociologia de Bourdieu.',
  'No século XX, a Sociologia ampliou seus temas e métodos, e passou a investigar a **cultura de massa**, a **burocracia**, o **trabalho**, a **educação**, as **minorias**, o **gênero**, a **globalização**, as **redes** e a **tecnologia**. Surgiram autores contemporâneos importantes, como **Pierre Bourdieu**, **Anthony Giddens**, **Zygmunt Bauman**, **Michel Foucault** (que também influenciou a Sociologia), **Manuel Castells** e **Boaventura de Sousa Santos**. A Sociologia também se expandiu por todo o mundo, adaptando-se a contextos locais, como o da América Latina e o do Brasil, onde se desenvolveu uma sociologia atenta à desigualdade, à herança colonial e à questão racial.',
  'No Brasil, a Sociologia chegou ao ensino no início do século XX, e se consolidou nas universidades a partir da década de 1930, com a criação da USP e da Escola Livre de Sociologia e Política. Os nomes de **Gilberto Freyre**, **Florestan Fernandes**, **Sérgio Buarque de Holanda**, **Darcy Ribeiro** e **Fernando Henrique Cardoso**, entre outros, marcaram o pensamento social brasileiro. A disciplina foi tornada obrigatória no ensino médio em 2008. Compreender essa trajetória mostra que a Sociologia é uma ciência **histórica**, que muda com as sociedades que estuda, e mostra por que ela é relevante para pensar os desafios do presente.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'No ENEM, o surgimento da Sociologia aparece em questões que relacionam as transformações do século XIX (industrialização, urbanização, revoluções) com os problemas que motivaram o pensamento sociológico, e que pedem a identificação de conceitos, como a divisão do trabalho, a classe social e a comunidade e a sociedade. Os textos podem descrever a vida nas cidades industriais, o trabalho nas fábricas ou as mudanças nos laços sociais, e a pergunta é como a Sociologia buscou explicá-los. A relação com a História (Revolução Industrial e Revolução Francesa) é frequente.',
  'Pontos de atenção: a Sociologia nasce da modernidade, marcada por industrialização, urbanização e revoluções políticas; seu surgimento se liga à necessidade de compreender a nova ordem social; o Iluminismo e o positivismo forneceram a ideia de uma ciência da sociedade; Comte, Durkheim, Marx e Weber são os clássicos, com abordagens distintas; a passagem da comunidade à sociedade expressa a mudança dos laços sociais. Evite pensar que a Sociologia é uma opinião sobre a sociedade: ela é um conhecimento sistemático, com teorias e métodos.',
  'Para revisar, monte um quadro: contexto (Revolução Industrial, urbanização, Revolução Francesa), problemas (desigualdade, coesão, conflito, individualismo), conceitos criados e os quatro clássicos, com uma frase para cada um. Reflita sobre como esses problemas continuam atuais. Os próximos temas apresentam os pensadores clássicos, em detalhe, iniciando por Auguste Comte e o positivismo, passando por Durkheim, Marx e Weber, e aprofundam os conceitos que você poderá usar na prova e na redação.'] }
]},
{ t:'Auguste Comte', txt:[
 { h:'Comte e o positivismo: contexto e proposta', p:[
  '**Auguste Comte** (1798-1857), filósofo francês, é considerado o **fundador da Sociologia** e do **positivismo**. Viveu em um período de grandes instabilidades na França, após a Revolução Francesa, as guerras napoleônicas e as revoltas de 1830 e 1848. Foi secretário do pensador socialista utópico **Saint-Simon**, que o influenciou, e depois seguiu um caminho próprio. Em sua obra principal, o **Curso de Filosofia Positiva** (1830 a 1842), propôs uma nova ciência da sociedade, que primeiro chamou de "física social" e, depois, de **Sociologia**. Também escreveu o Sistema de Política Positiva e o Catecismo Positivista.',
  'O **positivismo** é uma corrente que defende que o único conhecimento válido é o **científico**, baseado na observação, na experiência e na comprovação dos fatos ("positivo" quer dizer real, certo, útil, preciso), e que rejeita explicações teológicas e metafísicas. Para Comte, o método das ciências naturais (observação, experimentação, comparação) deve ser aplicado ao estudo da sociedade, para descobrir as **leis** que regem os fenômenos sociais, tão necessárias e invariáveis quanto as leis naturais. O conhecimento dessas leis permitiria **prever** e **controlar** os fenômenos, e orientar a reorganização da sociedade.',
  'Comte acreditava que a crise social de seu tempo, de desordem e conflito, resultava da **desordem intelectual**: a ausência de um sistema de ideias comum, que organizasse a sociedade. A solução seria uma **reforma intelectual**, em que o conhecimento científico, o saber positivo, tomasse o lugar das velhas crenças teológicas e metafísicas. Assim, o objetivo era conciliar a **ordem** e o **progresso**, expressão que se tornou lema do positivismo ("Amor por princípio, ordem por base e progresso por fim"), e que está na bandeira do Brasil, resultado da influência dessa doutrina sobre os republicanos de 1889.'] },
 { h:'A lei dos três estados e a classificação das ciências', p:[
  'A principal teoria de Comte é a **lei dos três estados**, segundo a qual o espírito humano e a sociedade passam, historicamente, por três estágios sucessivos. O **estado teológico** (ou fictício) é a fase em que os fenômenos são explicados pela ação de seres sobrenaturais (deuses e espíritos), e inclui o fetichismo, o politeísmo e o monoteísmo; corresponde à sociedade com base militar e na autoridade religiosa. O **estado metafísico** (ou abstrato) é a fase de transição, em que as explicações recorrem a entidades abstratas (a natureza, as essências, os direitos naturais), e corresponde ao período da Idade Média e da crítica da Revolução Francesa.',
  'O **estado positivo** (ou científico) é a fase final, em que a mente humana renuncia a buscar as causas últimas e passa a observar os fenômenos e a descobrir suas **leis**, por meio da razão e da observação. Corresponde à sociedade industrial, em que a ciência e a indústria organizam a vida social, e os cientistas e industriais conduzem. Cada ciência passa por esses estágios, em um ritmo próprio. Comte propôs uma **classificação das ciências**, em ordem de generalidade e de complexidade: Matemática, Astronomia, Física, Química, Biologia e, no topo, a **Sociologia**, a mais complexa, que dependia dos conhecimentos das anteriores, e que estudaria a sociedade.',
  'A Sociologia, para Comte, divide-se em duas partes. A **estática social** estuda a **ordem**: as estruturas e as instituições que mantêm a sociedade coesa (a família, a linguagem, a religião, a propriedade e o Estado). A **dinâmica social** estuda o **progresso**: as leis do desenvolvimento e da transformação histórica, entre elas a lei dos três estados. Comte via a sociedade como um **organismo**, em que as partes são interdependentes e cumprem funções, e essa analogia com a Biologia influenciou Durkheim e o funcionalismo. A ênfase na harmonia e na ordem fez do positivismo uma doutrina conservadora, voltada a evitar revoluções.'] },
 { h:'A "religião da humanidade", críticas e legado', p:[
  'Nos últimos anos de sua vida, Comte, preocupado com o fato de que a ciência sozinha não bastaria para unir as pessoas, propôs uma nova **"Religião da Humanidade"**, sem Deus, em que o objeto de culto seria a própria humanidade, e com rituais, sacerdotes (os sociólogos) e um calendário. Esse projeto, visto como excêntrico, afastou muitos discípulos, mas revela sua preocupação com a **coesão social** e com a necessidade de valores comuns, que a sociedade industrial exigia. Os positivistas fundaram "igrejas positivistas" em vários países, inclusive no Brasil, onde o Templo da Humanidade, no Rio de Janeiro, ainda existe.',
  'O positivismo recebeu muitas **críticas**. Primeira: a ideia de que a sociedade pode ser estudada como a natureza, com a **neutralidade** e com leis invariáveis, ignora a **subjetividade**, a **história**, a **cultura** e a **ação** dos indivíduos, como destacaram Weber e a tradição interpretativa. Segunda: a ênfase na ordem e no consenso minimiza os **conflitos** e as **desigualdades**, o que, para Marx e os críticos, serve à manutenção do status quo. Terceira: a crença em um progresso linear e inevitável, com a ciência como guia, foi questionada diante de guerras, de crises e dos efeitos sociais e ambientais do desenvolvimento, como argumentou a Escola de Frankfurt.',
  'Apesar das críticas, o legado de Comte é grande. Foi o primeiro a defender a criação de uma ciência da sociedade, e influenciou **Durkheim**, que adotou a ideia de que os fatos sociais devem ser estudados de forma objetiva. O **positivismo** marcou as ciências e a cultura do século XIX e XX, inclusive na política e na educação. No **Brasil**, teve forte influência: a campanha republicana, o lema "Ordem e Progresso" na bandeira, a atuação de militares como Benjamin Constant e do Marechal Rondon, a organização da educação e a visão modernizadora e autoritária da Primeira República. O termo "positivismo" é usado, hoje, também para designar uma visão excessivamente objetivista da ciência.'] },
 { h:'Positivismo no Brasil e a ideia de progresso', p:[
  'O positivismo chegou ao Brasil na segunda metade do século XIX, e encontrou terreno fértil entre militares, engenheiros e intelectuais, descontentes com a monarquia e com a escravidão, e desejosos de modernização. Os **positivistas** defendiam a república, a abolição, a educação laica e científica e um Estado forte, que conduzisse o progresso com ordem. **Benjamin Constant**, professor da Escola Militar, formou gerações de oficiais nas ideias de Comte, e teve papel na proclamação da República (1889). A **bandeira do Brasil**, com o lema "Ordem e Progresso", simboliza essa influência.',
  'Na Primeira República, o positivismo orientou a **política**, em especial no Rio Grande do Sul, onde o governo de Júlio de Castilhos e de Borges de Medeiros seguiu o modelo de uma "ditadura republicana" (um governo forte, voltado ao progresso), e a **ciência**, a medicina e o urbanismo, em programas como o saneamento do Rio de Janeiro, de Oswaldo Cruz e Pereira Passos. Na relação com os povos indígenas, o **Marechal Rondon**, positivista, criou o Serviço de Proteção aos Índios (1910), com o lema "morrer, se preciso for; matar, nunca". A visão positivista de progresso também justificou intervenções autoritárias, como a repressão a Canudos e a reforma urbana excludente.',
  'A ideia de **progresso** permanece em discussões atuais, e vale uma reflexão crítica. Em que consiste progredir? Crescimento econômico, avanço tecnológico, melhoria das condições de vida, ampliação de direitos? Os efeitos do desenvolvimento (desigualdade, destruição ambiental, desemprego tecnológico) mostram que o progresso material não equivale ao progresso social. A herança positivista, com sua confiança na ciência e na ordem, convive com críticas que valorizam a pluralidade, a participação e o questionamento. Para o ENEM, é essencial saber relacionar o positivismo com a história do Brasil e com a ideia de ciência e de progresso, de modo crítico.'] },
 { h:'Como esse conteúdo aparece no ENEM', p:[
  'Comte aparece no ENEM em questões que trazem trechos do Curso de Filosofia Positiva, descrições da lei dos três estados ou referências ao lema "Ordem e Progresso", e pedem a identificação do positivismo e de suas ideias (ciência como único conhecimento válido, leis sociais, ordem e progresso). Também há questões que relacionam o positivismo ao contexto brasileiro (a república, a bandeira, o exército) ou que o comparam a outras correntes (Marx, Weber, Durkheim). A análise crítica do cientificismo e da ideia de progresso pode ser pedida.',
  'Pontos de atenção: Comte criou o termo Sociologia e o positivismo; propõe que a sociedade seja estudada por métodos científicos, semelhantes aos das ciências naturais; a lei dos três estados descreve a evolução teológica, metafísica e positiva; a Sociologia estuda a estática (ordem) e a dinâmica (progresso) social; o lema "Ordem e Progresso" é positivista; a visão da sociedade como organismo influenciou Durkheim. Evite confundir Comte com Marx (conflito de classes) ou com Weber (compreensão do sentido da ação), pois são abordagens diferentes.',
  'Para revisar, escreva a lei dos três estados com um exemplo para cada um, explique em poucas linhas o que é positivismo e por que ele foi criticado, e relacione-o à bandeira do Brasil. Esse tema abre a galeria dos clássicos da Sociologia. Em seguida, estudaremos Émile Durkheim, que transformou a ideia de uma ciência social em uma disciplina com método próprio, conceitos como fato social, solidariedade e anomia, e pesquisas, como a clássica sobre o suicídio.'] }
]}
];

/* quinto bloco do tema O que é Sociologia */
{
  const so = module.exports[0];
  const ult = so.txt.pop();
  so.txt.push({ h:'Sociologia, cidadania e a vida cotidiana', p:[
    'Estudar Sociologia não é apenas uma exigência escolar: é uma forma de **compreender o mundo em que vivemos** e de atuar nele. Ela fornece ferramentas para entender as notícias, os conflitos políticos, as desigualdades, as mudanças no trabalho e na família, a violência urbana, as relações entre gerações e as transformações da tecnologia. Um cidadão que conhece conceitos sociológicos tem mais condições de analisar criticamente a realidade, de reconhecer interesses e discursos, e de participar de modo informado das decisões coletivas, o que é essencial em uma democracia.',
    'A Sociologia também contribui para o **respeito à diversidade**. Ao mostrar que costumes, valores e instituições variam entre sociedades e épocas, ela combate o **etnocentrismo**, a tendência a considerar a própria cultura como superior e a julgar as outras pelos seus padrões. Ao analisar as desigualdades de classe, de gênero, de raça e de região, revela como elas são produzidas e mantidas, e abre caminho para políticas de inclusão e de justiça. Por isso, é uma disciplina muito ligada aos direitos humanos e à construção de uma sociedade mais plural e igualitária.',
    'No cotidiano, a atitude sociológica pode ser exercitada com perguntas simples: por que as pessoas agem assim? Que regras, escritas ou não, orientam este comportamento? Quem se beneficia da forma como as coisas estão organizadas? O que mudou ao longo do tempo? Que outras formas seriam possíveis? Esse exercício de questionamento, aplicado ao trabalho, à escola, à família, aos meios de comunicação e às redes sociais, ajuda a perceber o social em tudo e a ampliar a capacidade de reflexão, tanto para as questões do ENEM quanto para a redação, que exige um olhar crítico sobre os problemas da sociedade.'
  ]});
  so.txt.push(ult);
}
